const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const SOURCE_FILE = path.join(__dirname, 'source', 'weapons.source.json');
const OUTPUT_FILE = path.join(ROOT, 'shared', 'weapons.ts');
const REPORT_FILE = path.join(__dirname, 'generated', 'weapons-import-report.json');

const CATEGORY_MAP = {
  unarmed: 'unarmed',
  simple: 'simple',
  martial: 'martial',
  advanced: 'advanced',
};

const DAMAGE_TYPES = new Set([
  'bludgeoning',
  'piercing',
  'slashing',
  'bleed',
  'fire',
  'cold',
  'electricity',
  'sonic',
  'acid',
  'vitality',
  'void',
  'spirit',
  'poison',
  'mental',
  'force',
  'precision',
  'negative',
]);

function fail(message) {
  throw new Error(`[foundry-import:weapons] ${message}`);
}

function assert(condition, message) {
  if (!condition) fail(message);
}

function readSource() {
  if (!fs.existsSync(SOURCE_FILE)) {
    fail(`Source file missing: ${SOURCE_FILE}`);
  }
  const raw = fs.readFileSync(SOURCE_FILE, 'utf8');
  return JSON.parse(raw);
}

function validateAndNormalize(sourceWeapons) {
  const seen = new Set();
  const normalized = sourceWeapons.map((weapon, index) => {
    const required = ['id', 'name', 'category', 'damageDie', 'damageType', 'type', 'hands'];
    for (const field of required) {
      assert(weapon[field] !== undefined && weapon[field] !== null && weapon[field] !== '', `Weapon[${index}] missing field '${field}'`);
    }

    assert(!seen.has(weapon.id), `Duplicate weapon id '${weapon.id}'`);
    seen.add(weapon.id);

    assert(CATEGORY_MAP[weapon.category], `Weapon '${weapon.id}' has invalid category '${weapon.category}'`);
    assert(weapon.type === 'melee' || weapon.type === 'ranged', `Weapon '${weapon.id}' has invalid type '${weapon.type}'`);
    assert(DAMAGE_TYPES.has(weapon.damageType), `Weapon '${weapon.id}' has unsupported damage type '${weapon.damageType}'`);

    const hands = Number(weapon.hands);
    assert(Number.isFinite(hands) && hands >= 0 && hands <= 2, `Weapon '${weapon.id}' has invalid hands '${weapon.hands}'`);

    const range = weapon.type === 'ranged'
      ? Number(weapon.range || 6)
      : 1;

    const price = Number(weapon.price || 0);

    return {
      id: String(weapon.id),
      name: String(weapon.name),
      damageFormula: String(weapon.damageDie),
      damageType: String(weapon.damageType),
      type: weapon.type,
      range,
      hands,
      proficiencyCategory: CATEGORY_MAP[weapon.category],
      rarity: weapon.rarity || 'common',
      traits: Array.isArray(weapon.traits) ? weapon.traits.map((t) => String(t)).sort((a, b) => a.localeCompare(b)) : [],
      price,
      icon: weapon.icon || (weapon.type === 'ranged' ? '🏹' : weapon.category === 'unarmed' ? '👊' : '⚔️'),
      description: weapon.description || `${weapon.name} imported from Foundry source.`,
      group: weapon.group || 'unknown',
      bulk: weapon.bulk || '-',
      reload: weapon.reload || null,
    };
  });

  normalized.sort((a, b) => a.id.localeCompare(b.id));
  return normalized;
}

function renderWeaponsTs(weapons) {
  const header = `/**\n * Weapon definitions for PF2e Rebirth\n *\n * AUTO-GENERATED by scripts/foundry-import/import-weapons.js\n * Source: scripts/foundry-import/source/weapons.source.json\n * Do not edit this file manually; rerun npm run import:foundry.\n */\n\nimport { DamageType } from './spells';\n\nexport interface Weapon {\n  id: string;\n  name: string;\n  damageFormula: string; // e.g., "1d6", "2d8+2"\n  damageType: DamageType;\n  type: 'melee' | 'ranged';\n  range?: number; // Range in squares\n  hands: number; // 1 or 2\n  proficiencyCategory: 'unarmed' | 'simple' | 'martial' | 'advanced';\n  rarity: 'common' | 'uncommon' | 'rare' | 'unique';\n  traits: string[];\n  price: number; // GP cost\n  icon: string;\n  description: string;\n}\n\nexport const WEAPON_CATALOG: Record<string, Weapon> = {\n`;

  const body = weapons
    .map((weapon) => {
      const traits = weapon.traits.map((trait) => `'${trait.replace(/'/g, "\\'")}'`).join(', ');
      return `  '${weapon.id}': {\n    id: '${weapon.id}',\n    name: '${weapon.name.replace(/'/g, "\\'")}',\n    damageFormula: '${weapon.damageFormula}',\n    damageType: '${weapon.damageType}',\n    type: '${weapon.type}',\n    range: ${weapon.range},\n    hands: ${weapon.hands},\n    proficiencyCategory: '${weapon.proficiencyCategory}',\n    rarity: '${weapon.rarity}',\n    traits: [${traits}],\n    price: ${weapon.price},\n    icon: '${weapon.icon}',\n    description: '${weapon.description.replace(/'/g, "\\'")}',\n  },`;
    })
    .join('\n');

  const footer = `\n};\n\nexport const getWeapon = (weaponId: string): Weapon | undefined => {\n  return WEAPON_CATALOG[weaponId];\n};\n`;

  return header + body + footer;
}

function writeReport(weapons) {
  const categoryCounts = weapons.reduce((acc, weapon) => {
    acc[weapon.proficiencyCategory] = (acc[weapon.proficiencyCategory] || 0) + 1;
    return acc;
  }, {});

  const report = {
    generatedAt: new Date().toISOString(),
    sourceFile: path.relative(ROOT, SOURCE_FILE).replace(/\\/g, '/'),
    outputFile: path.relative(ROOT, OUTPUT_FILE).replace(/\\/g, '/'),
    weaponCount: weapons.length,
    categoryCounts,
    meetsPhase13Target: weapons.length >= 80,
  };

  fs.writeFileSync(REPORT_FILE, JSON.stringify(report, null, 2));
  return report;
}

function run() {
  const source = readSource();
  assert(Array.isArray(source.weapons), 'Expected source.weapons to be an array');

  const weapons = validateAndNormalize(source.weapons);
  assert(weapons.length >= 80, `Expected at least 80 weapons, found ${weapons.length}`);

  const tsContent = renderWeaponsTs(weapons);
  fs.writeFileSync(OUTPUT_FILE, tsContent);

  const report = writeReport(weapons);
  console.log(`[foundry-import] Imported ${report.weaponCount} weapons into shared/weapons.ts`);
  console.log(`[foundry-import] Category counts:`, report.categoryCounts);
}

if (require.main === module) {
  run();
}

module.exports = { run };
