/**
 * Feat import script — transforms feats.source.json → shared/ancestryFeats.ts, generalFeats.ts, skillFeats.ts
 *
 * Part of the Foundry VTT Data Pipeline (Phase 13).
 * Run via: npm run import:foundry
 *
 * Generates the three universal feat catalog files from a single source.
 * Does NOT touch class feat files (fighterFeats.ts, rogueFeats.ts, etc.)
 * as those are deeply integrated with implementation logic.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const SOURCE_FILE = path.join(__dirname, 'source', 'feats.source.json');
const REPORT_FILE = path.join(__dirname, 'generated', 'feats-import-report.json');

const OUTPUT_FILES = {
  ancestry: path.join(ROOT, 'shared', 'ancestryFeats.ts'),
  general: path.join(ROOT, 'shared', 'generalFeats.ts'),
  skill: path.join(ROOT, 'shared', 'skillFeats.ts'),
};

const VALID_CATEGORIES = new Set(['ancestry', 'general', 'skill']);
const VALID_IMPL_STATUS = new Set(['full', 'partial', 'stub', 'not_implemented']);
const VALID_ACTION_COSTS = new Set([1, 2, 3, 'reaction', 'free', 'passive']);
const MIN_ANCESTRY_COUNT = 50;
const MIN_GENERAL_COUNT = 10;
const MIN_SKILL_COUNT = 50;

function fail(message) {
  throw new Error(`[foundry-import:feats] ${message}`);
}

function assert(condition, message) {
  if (!condition) fail(message);
}

function readSource() {
  if (!fs.existsSync(SOURCE_FILE)) {
    fail(`Source file missing: ${SOURCE_FILE}`);
  }
  const raw = fs.readFileSync(SOURCE_FILE, 'utf8');
  return JSON.parse(raw);
}

function validateFeat(f, index) {
  const ctx = `Feat[${index}] "${f.name || f.id || '?'}"`;

  const required = ['id', 'name', 'category', 'level', 'description', 'implemented'];
  for (const field of required) {
    assert(f[field] !== undefined && f[field] !== null, `${ctx} missing field '${field}'`);
  }

  assert(typeof f.id === 'string' && f.id.length > 0, `${ctx} id must be non-empty string`);
  assert(typeof f.name === 'string' && f.name.length > 0, `${ctx} name must be non-empty string`);
  assert(VALID_CATEGORIES.has(f.category), `${ctx} invalid category '${f.category}'`);
  assert(typeof f.level === 'number' && f.level >= 1 && f.level <= 20, `${ctx} level must be 1-20`);
  assert(typeof f.description === 'string', `${ctx} description must be string`);
  assert(VALID_IMPL_STATUS.has(f.implemented), `${ctx} invalid implemented '${f.implemented}'`);

  // source is required for ancestry feats, null/absent for general/skill
  if (f.category === 'ancestry') {
    assert(typeof f.source === 'string' && f.source.length > 0, `${ctx} ancestry feats require source`);
  }

  if (f.actionCost !== undefined) {
    assert(VALID_ACTION_COSTS.has(f.actionCost), `${ctx} invalid actionCost '${f.actionCost}'`);
  }

  if (f.traits) {
    assert(Array.isArray(f.traits), `${ctx} traits must be array`);
  }

  if (f.prerequisites) {
    assert(Array.isArray(f.prerequisites), `${ctx} prerequisites must be array`);
  }
}

function esc(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function renderFeat(f) {
  const lines = [];
  lines.push('  {');
  lines.push(`    id: '${esc(f.id)}',`);
  lines.push(`    name: '${esc(f.name)}',`);

  // source: string for ancestry, null for general/skill
  if (f.category === 'ancestry') {
    lines.push(`    source: '${esc(f.source)}',`);
  } else {
    lines.push(`    source: null,`);
  }

  lines.push(`    category: '${f.category}',`);
  lines.push(`    level: ${f.level},`);
  lines.push(`    description: '${esc(f.description)}',`);
  lines.push(`    implemented: '${f.implemented}',`);

  if (f.traits && f.traits.length > 0) {
    const traitStr = f.traits.map((t) => `'${esc(t)}'`).join(', ');
    lines.push(`    traits: [${traitStr}],`);
  }

  if (f.actionCost !== undefined) {
    if (typeof f.actionCost === 'number') {
      lines.push(`    actionCost: ${f.actionCost},`);
    } else {
      lines.push(`    actionCost: '${f.actionCost}',`);
    }
  }

  if (f.prerequisites && f.prerequisites.length > 0) {
    const preStr = f.prerequisites.map((p) => `'${esc(p)}'`).join(', ');
    lines.push(`    prerequisites: [${preStr}],`);
  }

  lines.push('  },');
  return lines.join('\n');
}

function groupBySource(feats) {
  const groups = {};
  for (const f of feats) {
    const key = f.source || '__none__';
    if (!groups[key]) groups[key] = [];
    groups[key].push(f);
  }
  return groups;
}

function renderAncestryFeats(feats) {
  const header = `/**
 * Ancestry feat definitions for PF2e Rebirth
 *
 * AUTO-GENERATED by scripts/foundry-import/import-feats.js
 * Source: scripts/foundry-import/source/feats.source.json
 * Do not edit this file manually; rerun npm run import:foundry.
 */
import type { FeatEntry } from './featTypes';

export const ANCESTRY_FEAT_CATALOG: FeatEntry[] = [\n`;

  const groups = groupBySource(feats);
  const ancestries = Object.keys(groups).sort();
  const bodyParts = [];

  for (const ancestry of ancestries) {
    const ancestryFeats = groups[ancestry].sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));
    // Group by level within ancestry
    const levels = [...new Set(ancestryFeats.map((f) => f.level))].sort((a, b) => a - b);
    for (const level of levels) {
      bodyParts.push(`  // ========== ${ancestry.toUpperCase()} — Level ${level} ==========`);
      for (const f of ancestryFeats.filter((f) => f.level === level)) {
        bodyParts.push(renderFeat(f));
      }
    }
  }

  return header + bodyParts.join('\n') + '\n];\n';
}

function renderGeneralFeats(feats) {
  const header = `/**
 * General feat definitions for PF2e Rebirth
 *
 * AUTO-GENERATED by scripts/foundry-import/import-feats.js
 * Source: scripts/foundry-import/source/feats.source.json
 * Do not edit this file manually; rerun npm run import:foundry.
 */
import type { FeatEntry } from './featTypes';

export const GENERAL_FEAT_CATALOG: FeatEntry[] = [\n`;

  const sorted = feats.sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));
  const levels = [...new Set(sorted.map((f) => f.level))].sort((a, b) => a - b);
  const bodyParts = [];

  for (const level of levels) {
    bodyParts.push(`  // ========== Level ${level} ==========`);
    for (const f of sorted.filter((f) => f.level === level)) {
      bodyParts.push(renderFeat(f));
    }
  }

  return header + bodyParts.join('\n') + '\n];\n';
}

function renderSkillFeats(feats) {
  const header = `/**
 * Skill feat definitions for PF2e Rebirth
 *
 * AUTO-GENERATED by scripts/foundry-import/import-feats.js
 * Source: scripts/foundry-import/source/feats.source.json
 * Do not edit this file manually; rerun npm run import:foundry.
 */
import type { FeatEntry } from './featTypes';

export const SKILL_FEAT_CATALOG: FeatEntry[] = [\n`;

  const sorted = feats.sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));
  const levels = [...new Set(sorted.map((f) => f.level))].sort((a, b) => a - b);
  const bodyParts = [];

  for (const level of levels) {
    bodyParts.push(`  // ========== Level ${level} ==========`);
    for (const f of sorted.filter((f) => f.level === level)) {
      bodyParts.push(renderFeat(f));
    }
  }

  return header + bodyParts.join('\n') + '\n];\n';
}

function writeReport(feats) {
  const categoryCounts = {};
  const implCounts = {};
  const sourceCounts = {};
  const levelCounts = {};

  for (const f of feats) {
    categoryCounts[f.category] = (categoryCounts[f.category] || 0) + 1;
    implCounts[f.implemented] = (implCounts[f.implemented] || 0) + 1;
    if (f.source) {
      sourceCounts[f.source] = (sourceCounts[f.source] || 0) + 1;
    }
    levelCounts[f.level] = (levelCounts[f.level] || 0) + 1;
  }

  const report = {
    generatedAt: new Date().toISOString(),
    sourceFile: path.relative(ROOT, SOURCE_FILE).replace(/\\/g, '/'),
    outputFiles: Object.fromEntries(
      Object.entries(OUTPUT_FILES).map(([k, v]) => [k, path.relative(ROOT, v).replace(/\\/g, '/')])
    ),
    totalFeats: feats.length,
    meetsPhase13Target: feats.length >= MIN_ANCESTRY_COUNT + MIN_GENERAL_COUNT + MIN_SKILL_COUNT,
    categoryCounts,
    implCounts,
    sourceCounts,
    levelCounts,
  };

  const genDir = path.dirname(REPORT_FILE);
  if (!fs.existsSync(genDir)) {
    fs.mkdirSync(genDir, { recursive: true });
  }

  fs.writeFileSync(REPORT_FILE, JSON.stringify(report, null, 2));
  return report;
}

function run() {
  const source = readSource();
  assert(Array.isArray(source.feats), 'Expected source.feats to be an array');

  // Validate all
  const seen = new Set();
  source.feats.forEach((f, i) => {
    validateFeat(f, i);
    assert(!seen.has(f.id), `Duplicate feat id '${f.id}'`);
    seen.add(f.id);
  });

  // Split by category
  const ancestry = source.feats.filter((f) => f.category === 'ancestry');
  const general = source.feats.filter((f) => f.category === 'general');
  const skill = source.feats.filter((f) => f.category === 'skill');

  assert(ancestry.length >= MIN_ANCESTRY_COUNT, `Expected at least ${MIN_ANCESTRY_COUNT} ancestry feats, found ${ancestry.length}`);
  assert(general.length >= MIN_GENERAL_COUNT, `Expected at least ${MIN_GENERAL_COUNT} general feats, found ${general.length}`);
  assert(skill.length >= MIN_SKILL_COUNT, `Expected at least ${MIN_SKILL_COUNT} skill feats, found ${skill.length}`);

  // Generate output files
  fs.writeFileSync(OUTPUT_FILES.ancestry, renderAncestryFeats(ancestry));
  fs.writeFileSync(OUTPUT_FILES.general, renderGeneralFeats(general));
  fs.writeFileSync(OUTPUT_FILES.skill, renderSkillFeats(skill));

  const report = writeReport(source.feats);
  console.log(`[foundry-import] Imported ${report.totalFeats} feats`);
  console.log(`[foundry-import]   Ancestry: ${ancestry.length}, General: ${general.length}, Skill: ${skill.length}`);
  console.log(`[foundry-import]   Implementation: `, report.implCounts);
}

if (require.main === module) {
  run();
}

module.exports = { run };
