/**
 * Alchemist Class Features & Feats — PF2e Remastered (Player Core 2)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=56
 *
 * Key Attribute: INT | HP: 8 + CON
 * Perception: Trained → Expert (L9)
 * Fort: Expert → Master (L11, Chemical Hardiness, success→crit)
 * Reflex: Expert → Master (L15, Explosion Dodger, success→crit)
 * Will: Trained → Expert (L7)
 * Weapons: Trained simple+alch bombs → Expert (L7) → Master (L15)
 * Armor: Light+Med Trained → Expert (L13) → Master (L19)
 * Class DC: Trained → Expert (L9) → Master (L17)
 * Alchemy: Versatile Vials, Quick Alchemy, Research Field
 */

import type { FeatEntry } from './featTypes';
import { WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION, createClassFeature } from './sharedFeats';

// ── Alchemist Class Features ─────────────────────────────

export const ALCHEMIST_CLASS_FEATURES: FeatEntry[] = [
  {
    id: 'alchemist-alchemy',
    name: 'Alchemy',
    source: 'Alchemist',
    category: 'class_feature',
    level: 1,
    description: 'You understand the complex interactions of natural and unnatural substances and can use the Craft activity to create alchemical items. You gain the Alchemical Crafting feat and can automatically identify alchemical items you have formulas for. You start with a formula book containing formulas for two common 1st-level alchemical items plus those from your research field.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-versatile-vials',
    name: 'Versatile Vials',
    source: 'Alchemist',
    category: 'class_feature',
    level: 1,
    description: 'You can prepare versatile vials from reagents. During daily preparations you create 2 + INT modifier vials (max). While exploring, regain 2 vials per 10 minutes. Vials can be thrown as acid bombs (1d6 acid + 1 splash at L1, scaling at L4/12/18) or used for Quick Alchemy.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-research-field',
    name: 'Research Field',
    source: 'Alchemist',
    category: 'class_feature',
    level: 1,
    description: 'Choose your research field: Bomber, Chirurgeon, Mutagenist, or Toxicologist. Your field grants formulas, versatile vial options, and field discoveries at higher levels.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    subChoices: { label: 'Choose a research field', options: [
      { id: 'bomber', name: 'Bomber', description: 'Specialize in alchemical bombs; bonus splash damage' },
      { id: 'chirurgeon', name: 'Chirurgeon', description: 'Specialize in healing elixirs and Medicine' },
      { id: 'mutagenist', name: 'Mutagenist', description: 'Specialize in mutagens; personal mutagenic flashback' },
      { id: 'toxicologist', name: 'Toxicologist', description: 'Specialize in poisons; bonus to apply and craft' },
    ] },
  },
  {
    id: 'alchemist-field-discovery',
    name: 'Field Discovery',
    source: 'Alchemist',
    category: 'class_feature',
    level: 5,
    description: 'You learn the field discovery listed in your research field, granting a significant advantage with your specialty.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-powerful-alchemy',
    name: 'Powerful Alchemy',
    source: 'Alchemist',
    category: 'class_feature',
    level: 5,
    description: 'Alchemical items you create with infused reagents are particularly potent. When you create an infused alchemical item that allows a saving throw, you can change its DC to your class DC.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-alchemical-weapon-expertise',
    name: 'Alchemical Weapon Expertise',
    source: 'Alchemist',
    category: 'class_feature',
    level: 7,
    description: 'Your proficiency ranks for simple weapons, alchemical bombs, and unarmed attacks increase to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-will-expertise',
    name: 'Will Expertise',
    source: 'Alchemist',
    category: 'class_feature',
    level: 7,
    description: 'Your proficiency rank for Will saves increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-alchemical-expertise',
    name: 'Alchemical Expertise',
    source: 'Alchemist',
    category: 'class_feature',
    level: 9,
    description: 'Your proficiency rank for your alchemist class DC increases to expert. When you gather reagents during exploration, you regain 3 vials instead of 2.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-double-brew',
    name: 'Double Brew',
    source: 'Alchemist',
    category: 'class_feature',
    level: 9,
    description: 'When using Quick Alchemy, you can create two items instead of one. These don\'t have to be the same. If you create two consumables, you expend a versatile vial for each one.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-perception-expertise',
    name: 'Perception Expertise',
    source: 'Alchemist',
    category: 'class_feature',
    level: 9,
    description: 'Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-advanced-vials',
    name: 'Advanced Vials',
    source: 'Alchemist',
    category: 'class_feature',
    level: 11,
    description: 'Your experience helps you improve your field vials with a benefit particular to your research field.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-chemical-hardiness',
    name: 'Chemical Hardiness',
    source: 'Alchemist',
    category: 'class_feature',
    level: 11,
    description: 'Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-greater-field-discovery',
    name: 'Greater Field Discovery',
    source: 'Alchemist',
    category: 'class_feature',
    level: 13,
    description: 'You learn an incredible discovery that advances your understanding of your field.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-medium-armor-expertise',
    name: 'Medium Armor Expertise',
    source: 'Alchemist',
    category: 'class_feature',
    level: 13,
    description: 'Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Alchemist', 13),
  {
    id: 'alchemist-alchemical-weapon-mastery',
    name: 'Alchemical Weapon Mastery',
    source: 'Alchemist',
    category: 'class_feature',
    level: 15,
    description: 'Your proficiency ranks for simple weapons, alchemical bombs, and unarmed attacks increase to master.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-explosion-dodger',
    name: 'Explosion Dodger',
    source: 'Alchemist',
    category: 'class_feature',
    level: 15,
    description: 'Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-abundant-vials',
    name: 'Abundant Vials',
    source: 'Alchemist',
    category: 'class_feature',
    level: 17,
    description: 'You\'re permanently quickened, and can use the extra action only to use Quick Alchemy to create a quick vial.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-alchemical-mastery',
    name: 'Alchemical Mastery',
    source: 'Alchemist',
    category: 'class_feature',
    level: 17,
    description: 'Your proficiency rank for your alchemist class DC increases to master.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-medium-armor-mastery',
    name: 'Medium Armor Mastery',
    source: 'Alchemist',
    category: 'class_feature',
    level: 19,
    description: 'Your proficiency ranks for light armor, medium armor, and unarmored defense increase to master.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
];

// ── Alchemist Class Feats ────────────────────────────────

export const ALCHEMIST_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'alchemist-alchemical-assessment',
    name: 'Alchemical Assessment',
    source: 'Alchemist',
    category: 'class',
    level: 1,
    description: 'You quickly assess an alchemical item. You Interact to examine an alchemical item you\'re holding and attempt a Crafting check to identify it.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Alchemist'],
    prerequisites: ['Trained in Crafting'],
  },
  {
    id: 'alchemist-alchemical-familiar',
    name: 'Alchemical Familiar',
    source: 'Alchemist',
    category: 'class',
    level: 1,
    description: 'You have used alchemy to create life, a homunculus-like creature formed from alchemical materials, reagents, and a bit of your own blood. You gain a familiar.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-blowgun-poisoner',
    name: 'Blowgun Poisoner',
    source: 'Alchemist',
    category: 'class',
    level: 1,
    description: 'You are trained with the blowgun. When you apply an injury poison to a blowgun dart, the poison does not expire during your current turn.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-far-lobber',
    name: 'Far Lobber',
    source: 'Alchemist',
    category: 'class',
    level: 1,
    description: 'You\'ve learned to throw a longer distance. The range increment for your alchemical bombs increases to 30 feet.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-quick-bomber',
    name: 'Quick Bomber',
    source: 'Alchemist',
    category: 'class',
    level: 1,
    description: 'You Interact to draw a bomb, then Strike with it.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-soothing-vials',
    name: 'Soothing Vials',
    source: 'Alchemist',
    category: 'class',
    level: 1,
    description: 'When a creature drinks a versatile vial you created to regain Hit Points, it also gains temporary Hit Points equal to your level that last for 1 minute.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['chirurgeon research field'],
  },

  // ── Level 2 ──
  {
    id: 'alchemist-clotting-elixirs',
    name: 'Clotting Elixirs',
    source: 'Alchemist',
    category: 'class',
    level: 2,
    description: 'A creature that drinks one of your elixirs with the healing trait gains resistance to persistent bleed damage equal to your Intelligence modifier for 1 minute.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-improvise-admixture',
    name: 'Improvise Admixture',
    source: 'Alchemist',
    category: 'class',
    level: 2,
    description: 'You scrounge ingredients to produce versatile vials on the fly. You create a number of versatile vials equal to half your Intelligence modifier (minimum 1). These last until your next daily preparations. Once per day.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Alchemist', 'Concentrate', 'Manipulate'],
  },
  {
    id: 'alchemist-pernicious-poison',
    name: 'Pernicious Poison',
    source: 'Alchemist',
    category: 'class',
    level: 2,
    description: 'You add a toxic additive to an alchemical poison to splash poison on the target when you Strike.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },
  {
    id: 'alchemist-poison-resistance',
    name: 'Poison Resistance',
    source: 'Alchemist',
    category: 'class',
    level: 2,
    description: 'You gain poison resistance equal to half your level.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist', 'Druid'],
  },
  {
    id: 'alchemist-revivifying-mutagen',
    name: 'Revivifying Mutagen',
    source: 'Alchemist',
    category: 'class',
    level: 2,
    description: 'You metabolize a mutagen to heal yourself. You end the benefits and drawbacks of the mutagen and regain Hit Points equal to 2 × the mutagen\'s item level.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Alchemist', 'Concentrate'],
    prerequisites: ['under effects of a mutagen'],
  },
  {
    id: 'alchemist-smoke-bomb',
    name: 'Smoke Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 2,
    description: 'You add a tarry additive to an alchemical bomb to make it emit smoke. The bomb creates a cloud of smoke in a 10-foot-radius burst that lasts for 1 minute, concealing creatures within.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },

  // ── Level 4 ──
  {
    id: 'alchemist-calculated-splash',
    name: 'Calculated Splash',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'You have calculated the angles to maximize splash. When you throw an alchemical bomb with splash damage, you can add your Intelligence modifier to the splash damage.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-efficient-alchemy',
    name: 'Efficient Alchemy',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'You create additional items during daily preparations. You can create 2 additional alchemical items during your daily preparations without spending additional reagents.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-enduring-alchemy',
    name: 'Enduring Alchemy',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'Items you create with Quick Alchemy that would last until the start of your next turn instead last until the end of your next turn.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-healing-bomb',
    name: 'Healing Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'You add a foamy catalyst to an elixir of life, turning it into a throwable bomb with a range increment of 30 feet. On a hit, the target regains the elixir\'s healing.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },
  {
    id: 'alchemist-invigorating-elixir',
    name: 'Invigorating Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'You mix an aromatic salve into an elixir with the healing trait. When the creature drinks it, it can reduce its clumsy, enfeebled, or sickened condition by 1.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },
  {
    id: 'alchemist-regurgitate-mutagen',
    name: 'Regurgitate Mutagen',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'You redirect a mutagen within your body to spit acid. Make a ranged attack against a creature within 30 feet, dealing acid damage based on the mutagen\'s item level.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Alchemist', 'Manipulate'],
    prerequisites: ['under effects of a mutagen'],
  },
  {
    id: 'alchemist-tenacious-toxins',
    name: 'Tenacious Toxins',
    source: 'Alchemist',
    category: 'class',
    level: 4,
    description: 'Your poisons last longer. The duration of infused poisons you create is doubled.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },

  // ── Level 6 ──
  {
    id: 'alchemist-combine-elixirs',
    name: 'Combine Elixirs',
    source: 'Alchemist',
    category: 'class',
    level: 6,
    description: 'You add a second elixir to one you\'re creating to make a hybrid. A creature drinking it gets both elixir effects.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },
  {
    id: 'alchemist-debilitating-bomb',
    name: 'Debilitating Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 6,
    description: 'You add a crystalline additive to a bomb. On a hit, choose one: dazzled, deafened, off-guard, or -5-foot status penalty to Speed, lasting until the start of your next turn.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },
  {
    id: 'alchemist-directional-bombs',
    name: 'Directional Bombs',
    source: 'Alchemist',
    category: 'class',
    level: 6,
    description: 'You angle a bomb\'s splash in a 15-foot cone originating from the target rather than splashing in all directions. Allies outside the cone are unaffected by splash.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-fortified-elixirs',
    name: 'Fortified Elixirs',
    source: 'Alchemist',
    category: 'class',
    level: 6,
    description: 'Your elixirs can counteract diseases and poisons. When a creature drinks one of your elixirs with the healing trait, it can attempt a counteract check against one disease or poison affecting it.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-sticky-poison',
    name: 'Sticky Poison',
    source: 'Alchemist',
    category: 'class',
    level: 6,
    description: 'A weapon you\'ve applied an injury poison to retains the poison for 2 additional Strikes before the poison is consumed.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },

  // ── Level 8 ──
  {
    id: 'alchemist-alter-admixture',
    name: 'Alter Admixture',
    source: 'Alchemist',
    category: 'class',
    level: 8,
    description: 'You spend 1 minute modifying an already-created infused consumable. You can change it into a different consumable of the same or lower item level that you could have originally created.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist', 'Exploration'],
  },
  {
    id: 'alchemist-improved-invigorating-elixir',
    name: 'Improved Invigorating Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 8,
    description: 'Choose physical or mental invigoration. Physical adds fatigued and slowed to your choices. Mental adds confused and stupefied to your choices.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Invigorating Elixir'],
  },
  {
    id: 'alchemist-mutant-physique',
    name: 'Mutant Physique',
    source: 'Alchemist',
    category: 'class',
    level: 8,
    description: 'When you consume a bestial mutagen, you gain an unarmed attack. With a juggernaut mutagen, gain resistance. With a quicksilver mutagen, you\'re not off-guard to flanking.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-pinpoint-poisoner',
    name: 'Pinpoint Poisoner',
    source: 'Alchemist',
    category: 'class',
    level: 8,
    description: 'When you successfully Strike an off-guard creature with a poisoned weapon, the creature takes a -2 circumstance penalty to its initial save against the poison.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-sticky-bomb',
    name: 'Sticky Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 8,
    description: 'You mix a sticky additive into a bomb. On a hit, the bomb deals persistent damage equal to and of the same type as its item damage dice.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },
  {
    id: 'alchemist-perpetual-breadth',
    name: 'Perpetual Breadth',
    source: 'APG',
    category: 'class',
    level: 8,
    description: 'You have expanded your supply of near-infinite items. Choose two additional common alchemical items within the level ranges of your perpetual infusions.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['perpetual infusions'],
  },

  // ── Level 10 ──
  {
    id: 'alchemist-advanced-efficient-alchemy',
    name: 'Advanced Efficient Alchemy',
    source: 'Alchemist',
    category: 'class',
    level: 10,
    description: 'You create 4 additional items during daily preparations instead of 2 from Efficient Alchemy.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Efficient Alchemy'],
  },
  {
    id: 'alchemist-expanded-splash',
    name: 'Expanded Splash',
    source: 'Alchemist',
    category: 'class',
    level: 10,
    description: 'Bombs that deal splash damage in a 5-foot burst deal splash damage in a 10-foot burst instead.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-greater-debilitating-bomb',
    name: 'Greater Debilitating Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 10,
    description: 'You can choose from additional debilitations: enfeebled 1, clumsy 1, stupefied 1, or a -10-foot status penalty to Speed.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Debilitating Bomb'],
  },
  {
    id: 'alchemist-merciful-elixir',
    name: 'Merciful Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 10,
    description: 'You add a calming additive to an elixir of life. When drunk, it also attempts to counteract one fear or paralysis effect on the drinker.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive 2', 'Alchemist'],
  },
  {
    id: 'alchemist-potent-poisoner',
    name: 'Potent Poisoner',
    source: 'Alchemist',
    category: 'class',
    level: 10,
    description: 'Your poisons use your class DC if it\'s higher than the poison\'s normal DC.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Powerful Alchemy'],
  },
  {
    id: 'alchemist-unstable-concoction',
    name: 'Unstable Concoction',
    source: 'Alchemist',
    category: 'class',
    level: 10,
    description: 'You mix a volatile liquid into a consumable. The item\'s initial dice-based effect gains +2 damage per die, but on a critical failure of any attack roll, it backfires and deals damage to you.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive', 'Alchemist'],
  },

  // ── Level 12 ──
  {
    id: 'alchemist-extend-elixir',
    name: 'Extend Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 12,
    description: 'Elixirs you consume that have a duration of 1 minute or longer have their duration doubled when consumed by you.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-supreme-invigorating-elixir',
    name: 'Supreme Invigorating Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 12,
    description: 'For counteracting effects with invigorating elixirs, treat your level as 2 higher.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Invigorating Elixir'],
  },
  {
    id: 'alchemist-uncanny-bombs',
    name: 'Uncanny Bombs',
    source: 'Alchemist',
    category: 'class',
    level: 12,
    description: 'Your bombs lob unerringly. You reduce the penalty for range increments by 2 and your bombs don\'t require a line of effect if within 2 range increments.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Far Lobber'],
  },

  // ── Level 14 ──
  {
    id: 'alchemist-double-poison',
    name: 'Double Poison',
    source: 'Alchemist',
    category: 'class',
    level: 14,
    description: 'You can apply two different infused injury poisons to the same weapon, though not to ammunition. Both poisons are delivered on the next successful Strike.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-greater-merciful-elixir',
    name: 'Greater Merciful Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 14,
    description: 'Your additives contain panaceas. Your Merciful Elixir can also attempt to counteract blinded, deafened, sickened, or slowed.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Merciful Elixir'],
  },
  {
    id: 'alchemist-true-debilitating-bomb',
    name: 'True Debilitating Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 14,
    description: 'Your debilitations from Debilitating Bomb last for 1 minute instead of until the start of your next turn.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
    prerequisites: ['Greater Debilitating Bomb'],
  },

  // ── Level 16 ──
  {
    id: 'alchemist-eternal-elixir',
    name: 'Eternal Elixir',
    source: 'Alchemist',
    category: 'class',
    level: 16,
    description: 'If an elixir you create with Quick Alchemy would last until the start of your next turn, it instead lasts until your next daily preparations.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
  {
    id: 'alchemist-chemical-contagion',
    name: 'Chemical Contagion',
    source: 'Alchemist',
    category: 'class',
    level: 16,
    description: 'When a creature within 30 feet of your bomb\'s target fails its save against one of your debilitating bomb effects, a creature adjacent to it is also affected.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },

  // ── Level 18 ──
  {
    id: 'alchemist-mega-bomb',
    name: 'Mega Bomb',
    source: 'Alchemist',
    category: 'class',
    level: 18,
    description: 'You supercharge a bomb with massive destructive power. The bomb deals splash damage in a 30-foot-radius burst instead of its normal area, and deals maximum splash damage.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Additive 3', 'Alchemist'],
  },

  // ── Level 20 ──
  {
    id: 'alchemist-perfect-mutagen',
    name: 'Perfect Mutagen',
    source: 'Alchemist',
    category: 'class',
    level: 20,
    description: 'You have perfected your mutagen formulas. When you create a mutagen, you can make it a perfect mutagen that provides its benefits without its drawback.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Alchemist'],
  },
];
