/**
 * Animist Class Features & Feats — PF2e Remastered (War of Immortals)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=64
 *
 * Key Attribute: WIS | HP: 8 + CON
 * Perception: Trained → Expert (L9)
 * Fort: Trained → Expert (L3)
 * Reflex: Trained → Expert (L11, Expert Protections)
 * Will: Expert → Master (L13, Master of Mind and Spirit, success→crit)
 * Weapons: Trained simple+unarmed → Expert (L11)
 * Armor: Light+Med Trained → Expert (L11, Expert Protections)
 * Spellcasting: Divine prepared + Apparition spontaneous
 * Apparitions: Spiritual entities granting bonus spells, lore skills, vessel spells
 */

import type { FeatEntry } from './featTypes';
import { WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION, createClassFeature } from './sharedFeats';

// ── Animist Class Features ───────────────────────────────

export const ANIMIST_CLASS_FEATURES: FeatEntry[] = [
  {
    id: 'animist-apparition-attunement',
    name: 'Apparition Attunement',
    source: 'Animist',
    category: 'class_feature',
    level: 1,
    description: 'Animists have a gift for divine magic that allows them to serve as conduits or bridges for otherworldly spiritual entities known collectively as apparitions; through them, these entities can commune and interact with the physical world in a process called attunement. Each day during your daily preparations, choose two apparitions to attune to. Of these, choose one to be your primary apparition. Your attuned apparitions each grant you knowledge in the form of Lore skills and a repertoire of additional spells you can cast using apparition spellcasting, and your primary apparition grants you even further power in the form of a unique vessel focus spell and, when you are higher level, a unique avatar form. When you Refocus, you can change which of your currently attuned apparitions is your primary apparition.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
    subChoices: { label: 'Choose your primary apparition', options: [
      { id: 'custodian-of-groves-and-gardens', name: 'Custodian of Groves and Gardens', description: 'Nature and plant magic' },
      { id: 'imposter-in-hidden-places', name: 'Imposter in Hidden Places', description: 'Deception and illusion' },
      { id: 'lady-of-decay-and-renewal', name: 'Lady of Decay and Renewal', description: 'Death and rebirth cycles' },
      { id: 'lurker-in-shadowed-places', name: 'Lurker in Shadowed Places', description: 'Shadow and stealth' },
      { id: 'monarch-of-the-fey-court', name: 'Monarch of the Fey Court', description: 'Fey enchantment magic' },
      { id: 'reveler-in-lost-luxury', name: 'Reveler in Lost Luxury', description: 'Opulence and indulgence' },
      { id: 'sage-of-the-folding-wind', name: 'Sage of the Folding Wind', description: 'Air and movement magic' },
      { id: 'stalker-in-darkened-boughs', name: 'Stalker in Darkened Boughs', description: 'Predatory hunting spirit' },
      { id: 'steward-of-stone-and-fire', name: 'Steward of Stone and Fire', description: 'Earth and fire elemental magic' },
      { id: 'the-silent-whisper', name: 'The Silent Whisper', description: 'Death and communication with the dead' },
      { id: 'wandering-revenant', name: 'Wandering Revenant', description: 'Undead and vengeance' },
      { id: 'witness-to-ancient-battles', name: 'Witness to Ancient Battles', description: 'War and martial spirits' },
    ] },
  },
  {
    id: 'animist-spellcasting',
    name: 'Animist & Apparition Spellcasting',
    source: 'Animist',
    category: 'class_feature',
    level: 1,
    description: 'Your role as a spiritual medium connecting the mortal Universe to the realms beyond lets you cast your magic in two distinct ways: you both learn and prepare spells from the divine tradition yourself, and you also channel the knowledge and power of your attuned apparitions, gaining spell slots and a repertoire of spells from them that you can cast spontaneously. You are a prepared spellcaster for your animist spells and a spontaneous spellcaster for your apparition spells. All your apparition spells are signature spells. The clearly delineated partnership between an animist and their apparitions means you can\'t cast your animist spells using your apparition spell slots or vice versa.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Divine'],
  },
  {
    id: 'animist-animistic-practice',
    name: 'Animistic Practice',
    source: 'Animist',
    category: 'class_feature',
    level: 1,
    description: 'At 1st level, you choose an animistic practice that influences the way your power grows and develops, and you gain its first invocation. At 9th level, you gain its second invocation, and at 17th, you gain its third.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
    subChoices: { label: 'Choose a practice', options: [
      { id: 'channeler', name: 'Channeler', description: 'Channel apparition power through your body' },
      { id: 'invoker', name: 'Invoker', description: 'Invoke apparition power at range' },
      { id: 'sage', name: 'Sage', description: 'Draw on apparition knowledge and wisdom' },
    ] },
  },
  {
    id: 'animist-vessel-spells',
    name: 'Vessel Spells',
    source: 'Animist',
    category: 'class_feature',
    level: 1,
    description: 'Your primary attuned apparition can use your body as a conduit, allowing you to cast a unique vessel spell. Vessel spells are a type of focus spell. It costs 1 Focus Point to cast a focus spell, and you start with a focus pool of 1 Focus Point. You refill your focus pool during your daily preparations, and you can regain 1 Focus Point by spending 10 minutes using the Refocus activity to treat with nearby spirits, meditate on resolving an issue pertaining to the balance of spirits and mortals, or tell a story. Focus spells are automatically heightened to half your level rounded up.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-fortitude-expertise',
    name: 'Fortitude Expertise',
    source: 'Animist',
    category: 'class_feature',
    level: 3,
    description: 'Spiritual energy reinforces your body, making you more resilient. Your proficiency rank for Fortitude saves increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Animist',
    category: 'class_feature',
    level: 7,
    description: 'The magic of the spirits flows freely through you. Your proficiency ranks for spell attack modifier and spell DC increase to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-third-apparition',
    name: 'Third Apparition',
    source: 'Animist',
    category: 'class_feature',
    level: 7,
    description: 'You\'ve learned to shelter more spirits, gaining access to more magic. When you attune to apparitions during your daily preparations, you choose three apparitions to attune to, with one of them being your primary apparition. The number of Focus Points in your focus pool increases by 1 (maximum 3).',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-perception-expertise',
    name: 'Perception Expertise',
    source: 'Animist',
    category: 'class_feature',
    level: 9,
    description: 'Your apparitions call attention to minute details you might otherwise overlook. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-expert-protections',
    name: 'Expert Protections',
    source: 'Animist',
    category: 'class_feature',
    level: 11,
    description: 'The spiritual entities that protect you warn you of harm before it would occur, giving you more time to react, and help bear the burden of your armor when it is necessary. Your proficiency rank for light armor, medium armor, unarmored defense, and Reflex saves increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-simple-weapon-expertise',
    name: 'Simple Weapon Expertise',
    source: 'Animist',
    category: 'class_feature',
    level: 11,
    description: 'Training and magical assistance from your spiritual companions have improved your weapon technique. Your proficiency rank for simple weapons and unarmed attacks increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-master-of-mind-and-spirit',
    name: 'Master of Mind and Spirit',
    source: 'Animist',
    category: 'class_feature',
    level: 13,
    description: 'Your apparitions gird your mind against hostile intrusion and shield you from the effects of entities seeking to control your mind. Your proficiency rank for Will saves increases to master. When you roll a success at a Will save, you get a critical success instead.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Animist', 13),
  {
    id: 'animist-fourth-apparition',
    name: 'Fourth Apparition',
    source: 'Animist',
    category: 'class_feature',
    level: 15,
    description: 'You\'re truly loved by the spirits, with apparitions flocking to you from far and wide. When you attune to apparitions during your daily preparations, you choose four apparitions to attune to, with one of them being your primary apparition. The number of Focus Points in your focus pool increases by 1 (maximum 3).',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Animist',
    category: 'class_feature',
    level: 15,
    description: 'Your affinity with the apparitions you bond to has further enhanced the potency of your magic. Your proficiency ranks for spell attack modifier and spell DC increase to master.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-legendary-spellcaster',
    name: 'Legendary Spellcaster',
    source: 'Animist',
    category: 'class_feature',
    level: 19,
    description: 'You are a near-perfect channel for the magical energies of the realms beyond. Your proficiency ranks for spell attack modifier and spell DC increase to legendary.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-supreme-incarnation',
    name: 'Supreme Incarnation',
    source: 'Animist',
    category: 'class_feature',
    level: 19,
    description: 'You become a nexus between the mortal and spiritual realms through which your apparition can embody its full might. You gain a 10th-rank apparition spell slot. In addition to heightened versions of your apparition spells, you can use this slot to cast avatar. When you cast avatar in this way, you do not become an avatar of a deity; rather, your primary attuned apparition incarnates itself using your body, transforming you into the avatar described in your primary attuned apparition\'s entry.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Divine'],
  },
];

// ── Animist Class Feats ──────────────────────────────────

export const ANIMIST_CLASS_FEATS: FeatEntry[] = [

  // ── Level 1 ──
  {
    id: 'animist-apparition-sense',
    name: 'Apparition Sense',
    source: 'Animist',
    category: 'class',
    level: 1,
    description: 'You can see and interact with things others can\'t. You gain a vague sense that alerts you to the presence of apparitions, spirits, and undead that are hidden or concealed within 30 feet of you. This gives you no information about their precise location but allows you to detect them. In addition, if you are adjacent to an invisible spiritual entity (such as an invisible ghost), you can see it using this sense.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Divine'],
  },
  {
    id: 'animist-channelers-stance',
    name: 'Channeler\'s Stance',
    source: 'Animist',
    category: 'class',
    level: 1,
    description: 'You enter a stance that allows power to flow through you. While in this stance, you can use the Cast a Spell activity to cast spells using your apparition spell slots as if they were one action shorter (minimum 1 action). This applies only to apparition spells, not your prepared animist spells.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Stance'],
  },
  {
    id: 'animist-circle-of-spirits',
    name: 'Circle of Spirits',
    source: 'Animist',
    category: 'class',
    level: 1,
    description: 'With a thought, word, or gesture, you reach your mind out to another spirit. You can swap which of your attuned apparitions is your primary apparition. You gain all the benefits of having that apparition as your primary apparition, including access to its vessel spell. This does not require Refocusing. Frequency: once per round.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Concentrate'],
  },
  {
    id: 'animist-relinquish-control',
    name: 'Relinquish Control',
    source: 'Animist',
    category: 'class',
    level: 1,
    description: 'Your apparition takes over and shields you from outside influence. Trigger: Your turn begins. Until the end of your current turn, you are controlled by your primary apparition, which takes your actions for you. You gain a +2 circumstance bonus to saves against mental effects and effects that would possess you for the duration. You can\'t voluntarily act during this time, but neither can you be compelled to act against the apparition\'s nature.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Animist', 'Apparition'],
  },
  {
    id: 'animist-spirit-familiar',
    name: 'Spirit Familiar',
    source: 'Animist',
    category: 'class',
    level: 1,
    description: 'When you attune to your apparitions during your daily preparations, you can choose to dedicate a small amount of your life force to allow one of them to physically manifest as a familiar, which gains the spirit trait. You gain a familiar. Your spirit familiar has the normal number of familiar and master abilities based on your level, but its spirit nature means it is incorporeal unless you spend a familiar ability to make it corporeal for the day.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },

  // ── Level 2 ──
  {
    id: 'animist-conceal-spell',
    name: 'Conceal Spell',
    source: 'Animist',
    category: 'class',
    level: 2,
    description: 'Through sheer mental effort, you can simplify the incantations and gestures needed to spellcast, leaving them barely noticeable. If the next action you use is to Cast a Spell, attempt a Deception check against all observers\' Perception DCs. If you succeed, the spell is hidden from that observer, and they don\'t notice you\'re Casting a Spell.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Concentrate', 'Spellshape'],
  },
  {
    id: 'animist-embodiment-of-the-balance',
    name: 'Embodiment Of The Balance',
    source: 'Animist',
    category: 'class',
    level: 2,
    description: 'Your place in the balance between the forces of life and entropy expands the spells you can pull from the spirit realms. You add heal and harm to your apparition spell repertoire, regardless of your attuned apparitions. You can cast these spells using your apparition spell slots.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
  {
    id: 'animist-enhanced-familiar',
    name: 'Enhanced Familiar',
    source: 'Animist',
    category: 'class',
    level: 2,
    description: 'You infuse your familiar with additional magical energy, increasing its abilities. You can select four familiar or master abilities each day, instead of two.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
    prerequisites: ['a familiar'],
  },
  {
    id: 'animist-grasping-spirits',
    name: 'Grasping Spirits',
    source: 'Animist',
    category: 'class',
    level: 2,
    description: 'Gaining substance from your magic, your apparitions increase the range of your spells, which then pull your enemy closer. If the next action you use is to Cast a Spell that has a range, increase that spell\'s range by 30 feet. If the spell requires a spell attack roll and hits, or if the target critically fails its saving throw, the target is also pulled 5 feet closer to you. Frequency: once per 10 minutes.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Concentrate', 'Spellshape'],
  },
  {
    id: 'animist-spiritual-expansion',
    name: 'Spiritual Expansion',
    source: 'Animist',
    category: 'class',
    level: 2,
    description: 'Your apparitions manifest to scatter the energy of your spell. If the next action you use is to Cast a Spell that has an area, you can change the area to a 10-foot burst. The burst must be centered within the spell\'s original area or range.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Concentrate', 'Spellshape'],
  },

  // ── Level 4 ──
  {
    id: 'animist-apparitions-enhancement',
    name: 'Apparition\'s Enhancement',
    source: 'Animist',
    category: 'class',
    level: 4,
    description: 'Spiritual power encases your weapon or unarmed attack. Your most recent action must have been to cast a non-cantrip spell. You gain a +1 status bonus to attack rolls and deal an additional 1d6 spirit damage on your next Strike before the end of your turn. At 12th level, the status bonus increases to +2 and the extra damage increases to 2d6. Frequency: once per turn.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Animist', 'Apparition', 'Divine', 'Spirit'],
  },
  {
    id: 'animist-channeled-protection',
    name: 'Channeled Protection',
    source: 'Animist',
    category: 'class',
    level: 4,
    description: 'Your apparition uses excess energy to protect you. You must be in Channeler\'s Stance and your last action must have been to Cast a Spell from your spell slots. You gain a +1 circumstance bonus to AC and saving throws until the start of your next turn. If the spell you cast was 3rd rank or higher, the bonus increases to +2.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Aura'],
    prerequisites: ['Channeler\'s Stance'],
  },
  {
    id: 'animist-walk-the-wilds',
    name: 'Walk the Wilds',
    source: 'Animist',
    category: 'class',
    level: 4,
    description: 'You know the ways of birds and beasts and have gained the right to wear their forms. You add animal form to your animist spell list. In addition, you can prepare pest form as a 1st-rank spell, and you can cast it without spending a spell slot once per day.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },

  // ── Level 6 ──
  {
    id: 'animist-apparition-stabilization',
    name: 'Apparition Stabilization',
    source: 'Animist',
    category: 'class',
    level: 6,
    description: 'Your attuned apparition ensures that even if you would be distracted or disrupted, your magic does not go to waste. When you lose a spell from being disrupted or from failing to Sustain it, your apparition catches the energy. You retain the spell slot, though you can\'t use it again until your next turn.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Apparition', 'Wandering'],
  },
  {
    id: 'animist-blazing-spirit',
    name: 'Blazing Spirit',
    source: 'Animist',
    category: 'class',
    level: 6,
    description: 'Your apparition grants fiery defenses. When a creature damages you with a melee attack, you deal fire damage to the attacker equal to half your level. Your attuned apparition must grant Battlegrounds Lore or Volcano Lore as an apparition skill. Frequency: once per 10 minutes.',
    implemented: 'full',
    actionCost: 'reaction',
    traits: ['Animist', 'Apparition', 'Divine', 'Fire', 'Wandering'],
  },
  {
    id: 'animist-grudge-strike',
    name: 'Grudge Strike',
    source: 'Animist',
    category: 'class',
    level: 6,
    description: 'You channel the spiritual power of spiteful grudges. Make a melee Strike. On a hit, the target takes additional spirit damage equal to your level and is enfeebled 1 until the end of your next turn. Your attuned apparition must grant Heraldry Lore or Underworld Lore as an apparition skill.',
    implemented: 'full',
    actionCost: 2,
    traits: ['Animist', 'Apparition', 'Divine', 'Wandering'],
  },
  {
    id: 'animist-mediums-awareness',
    name: 'Medium\'s Awareness',
    source: 'Animist',
    category: 'class',
    level: 6,
    description: 'Your apparitions watch over you. You gain a +1 circumstance bonus to Perception checks and saving throws against hazards, traps, and ambient dangers while exploring. In addition, you gain a +2 circumstance bonus to initiative rolls when you roll Perception for initiative.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Apparition', 'Divine', 'Wandering'],
  },
  {
    id: 'animist-roaring-heart',
    name: 'Roaring Heart',
    source: 'Animist',
    category: 'class',
    level: 6,
    description: 'You surge forward inexorably. Stride up to your Speed toward an enemy you can see, then make a melee Strike against that enemy. If you moved at least 10 feet, you gain a +1 circumstance bonus to the attack roll. Your attuned apparition must grant Mountain Lore as an apparition skill.',
    implemented: 'full',
    actionCost: 2,
    traits: ['Animist', 'Apparition', 'Divine', 'Wandering'],
  },

  // ── Level 8 ──
  {
    id: 'animist-apparitions-reflection',
    name: 'Apparition\'s Reflection',
    source: 'Animist',
    category: 'class',
    level: 8,
    description: 'Your apparition infuses your body with additional power. You can use 1 to 3 actions to cast this spellshape. If your next action is to Cast a Spell, the spell is reflected by your apparition. The spell gains additional effects based on the number of actions you spent: 1 action gives a +1 status bonus to the spell attack roll or +1 to the DC; 2 actions increases the spell\'s damage by 2d6; 3 actions does both. Frequency: once per hour.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Spellshape'],
  },
  {
    id: 'animist-incredible-familiar',
    name: 'Incredible Familiar',
    source: 'Animist',
    category: 'class',
    level: 8,
    description: 'Your familiar is imbued with even more magic than other familiars. You can select six familiar or master abilities each day, instead of four.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
    prerequisites: ['Enhanced Familiar'],
  },
  {
    id: 'animist-instinctive-maneuvers',
    name: 'Instinctive Maneuvers',
    source: 'Animist',
    category: 'class',
    level: 8,
    description: 'When you allow an apparition control over your body, it might vent its fury against your foes. When you use Relinquish Control, the apparition controlling you can attempt one Athletics check to Disarm, Grapple, Shove, or Trip a creature adjacent to you as a free action, using your attack modifier.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Apparition'],
    prerequisites: ['Relinquish Control'],
  },
  {
    id: 'animist-spirit-walk',
    name: 'Spirit Walk',
    source: 'Animist',
    category: 'class',
    level: 8,
    description: 'Your allied apparitions ward you against the predations of their restless peers. While exploring, you and allies within a 15-foot emanation gain a +1 circumstance bonus to saves and AC against spirits, undead, and haunts. If a haunt would trigger within this aura, you can attempt a Religion check to prevent it from activating.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Apparition', 'Aura', 'Exploration'],
    prerequisites: ['Apparition Sense'],
  },
  {
    id: 'animist-wind-seeker',
    name: 'Wind Seeker',
    source: 'Animist',
    category: 'class',
    level: 8,
    description: 'Wings free you from the shackles of the ground below. You add aerial form to your animist spell list. In addition, when you cast a polymorph spell that grants a fly Speed, you can increase the fly Speed granted by 10 feet.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
    prerequisites: ['Walk the Wilds'],
  },

  // ── Level 10 ──
  {
    id: 'animist-apparitions-quickening',
    name: 'Apparition\'s Quickening',
    source: 'Animist',
    category: 'class',
    level: 10,
    description: 'If your next action is to cast a cantrip or a spell that is at least 2 ranks lower than the highest-rank spell slot you have, you can draw power from one of your attuned apparitions to reduce the number of actions to cast it by 1 (minimum 1 action). You must be attuned to at least 2 apparitions. Frequency: once per round.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Animist', 'Apparition', 'Concentrate', 'Spellshape'],
  },
  {
    id: 'animist-fly-on-shadowed-wings',
    name: 'Fly on Shadowed Wings',
    source: 'Animist',
    category: 'class',
    level: 10,
    description: 'Your apparition embraces you, feeding on your magic to become a pair of protective wings. You disperse one of your non-primary attuned apparitions to gain a fly Speed equal to your Speed for 10 minutes. While flying this way, you also gain a +1 circumstance bonus to AC. The dispersed apparition returns after 10 minutes or during your next daily preparations, whichever comes first. Frequency: once per hour.',
    implemented: 'full',
    actionCost: 2,
    traits: ['Animist', 'Apparition'],
  },

  // ── Level 12 ──
  {
    id: 'animist-apparition-cloud',
    name: 'Apparition Cloud',
    source: 'Animist',
    category: 'class',
    level: 12,
    description: 'With a mere thought, you discorporate your familiar into a thousand shards of spiritual magic, protecting both it and yourself from physical harm while making it difficult for enemies to move near you. Your familiar disperses into a 15-foot emanation around you for 1 minute. Enemies in the emanation treat it as difficult terrain. While the cloud is active, you gain a +2 circumstance bonus to AC. Your familiar can\'t act while dispersed. Trigger: You are targeted by an attack. Your familiar must be adjacent to you or in your space.',
    implemented: 'full',
    actionCost: 'reaction',
    traits: ['Animist', 'Misfortune', 'Wandering'],
    prerequisites: ['Spirit Familiar'],
  },
  {
    id: 'animist-shadows-within-shadows',
    name: 'Shadows Within Shadows',
    source: 'Animist',
    category: 'class',
    level: 12,
    description: 'Your apparition possesses a furtive and elusive nature that can influence and blend with your spiritual energy to form a protective and nearly impenetrable shroud of nondetection around you. When you would be detected by an enemy Seeking you, or an enemy would succeed at a counteract check against a spell making you hidden, concealed, or undetected, the enemy must reroll the check and use the worse result. Your attuned apparition must grant Hunting Lore or Underworld Lore as one of its apparition skills.',
    implemented: 'full',
    actionCost: 'reaction',
    traits: ['Animist', 'Apparition', 'Divine', 'Misfortune', 'Wandering'],
  },
  {
    id: 'animist-whisper-of-warning',
    name: 'Whisper of Warning',
    source: 'Animist',
    category: 'class',
    level: 12,
    description: 'Your protective apparitions alert you to an incoming attack. When you would be hit, but not critically hit, by an attack, the attacker must reroll the attack roll and use the lower result. Frequency: once per 10 minutes.',
    implemented: 'full',
    actionCost: 'reaction',
    traits: ['Animist', 'Apparition', 'Divine', 'Misfortune', 'Wandering'],
  },

  // ── Level 14 ──
  {
    id: 'animist-banish-falsehoods-of-flesh',
    name: 'Banish Falsehoods of Flesh',
    source: 'Animist',
    category: 'class',
    level: 14,
    description: 'Your ability to manipulate supernatural energy allows you to deploy divine magic directly against a disguised enemy to reveal them as they truly are, or to cleanse an ally from an unwilling transformation. You attempt to counteract a polymorph effect or magical disguise on a creature within 30 feet. You use your spell DC and your counteract rank is half your level rounded up.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Concentrate', 'Divine'],
  },
  {
    id: 'animist-cardinal-guardians',
    name: 'Cardinal Guardians',
    source: 'Animist',
    category: 'class',
    level: 14,
    description: 'You focus your divine magic to allow your apparitions to work in concert using the magic from one to weaken an enemy against the power of the next. When you cast a spell that deals damage and then cast a spell with a different damage type before the end of your next turn, the target\'s resistance to the second spell\'s damage type is reduced by an amount equal to half your level.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },

  // ── Level 16 ──
  {
    id: 'animist-forests-heart',
    name: 'Forest\'s Heart',
    source: 'Animist',
    category: 'class',
    level: 16,
    description: 'You adopt a stance that allows your apparitions to channel spiritual energy down through you to inhabit roots, control vines, and command plant-life from the ground you stand on to fight on your behalf. While in this stance, difficult terrain made of plants doesn\'t impede you, and at the start of each of your turns, plants erupt in a 15-foot emanation around you, making the area difficult terrain for enemies. You can also command the plants to Strike creatures within the emanation as a single action. Your attuned apparition must grant Forest Lore or Herbalism Lore as one of its apparition skills.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Divine', 'Stance', 'Wandering'],
  },
  {
    id: 'animist-jesters-gambol',
    name: 'Jester\'s Gambol',
    source: 'Animist',
    category: 'class',
    level: 16,
    description: 'You adopt a stance that makes your movements carefree and sublimely unpredictable, allowing you to move past impediments with ease and resist the attacks and importunateness of natural threats. While in this stance, you gain a +10-foot status bonus to your Speed, you ignore difficult terrain, and you gain a +2 circumstance bonus to AC against reactions triggered by your movement. You must be attuned to an apparition that grants Circus Lore or Fey Lore as one of its apparition skills.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Divine', 'Stance', 'Wandering'],
  },
  {
    id: 'animist-monstrous-inclinations',
    name: 'Monstrous Inclinations',
    source: 'Animist',
    category: 'class',
    level: 16,
    description: 'Your apparitions share with you the monstrous nature of those creatures who dwell in deep seas or ancient woods. You gain darkvision, a swim Speed equal to your land Speed, and resistance to cold and electricity equal to half your level. Your attuned apparition must grant Forest Lore or Ocean Lore as one of its apparition skills.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Apparition', 'Wandering'],
  },
  {
    id: 'animist-spiritual-spellshape-stance',
    name: 'Spiritual Spellshape Stance',
    source: 'Animist',
    category: 'class',
    level: 16,
    description: 'You feed excess magical power into your apparition, allowing it to grow ethereal limbs it can use to help shape and focus your spells. While in this stance, when you Cast a Spell that has a verbal or somatic component, you can replace one of those components with a free-hand interaction from your apparition, effectively allowing you to cast spells with fewer free hands needed.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Apparition', 'Divine', 'Stance', 'Wandering'],
  },

  // ── Level 18 ──
  {
    id: 'animist-cycle-of-souls',
    name: 'Cycle of Souls',
    source: 'Animist',
    category: 'class',
    level: 18,
    description: 'Your spiritual allies guide your movements, allowing you to prepare for the trials before you at a speed faster than thought. Trigger: Your turn begins. You can enter or change your stance as a free action and Stride up to half your Speed. You must have the liturgist practice and at least one animist stance.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Animist', 'Apparition'],
    prerequisites: ['liturgist practice', 'at least one animist stance'],
  },
  {
    id: 'animist-echoing-channel',
    name: 'Echoing Channel',
    source: 'Animist',
    category: 'class',
    level: 18,
    description: 'When you pull forth vitality or void energy, you also create a smaller pocket of that energy. If the next action you use is to cast a heal or harm spell, after the spell resolves, a secondary burst of the same energy affects a different target within 30 feet. The secondary burst heals or deals damage equal to the spell\'s rank.',
    implemented: 'full',
    actionCost: 1,
    traits: ['Animist', 'Concentrate', 'Spellshape'],
    prerequisites: ['Embodiment Of The Balance'],
  },
  {
    id: 'animist-spirits-sacrifice',
    name: 'Spirit\'s Sacrifice',
    source: 'Animist',
    category: 'class',
    level: 18,
    description: 'Your attuned apparition gathers all of the energy it can through your shared bond and uses that power to disperse itself while channeling the energy back into you, saving your life. Trigger: You would die. One of your attuned apparitions disperses, and you are instead restored to half your maximum Hit Points. You lose access to the dispersed apparition\'s benefits until your next daily preparations.',
    implemented: 'full',
    actionCost: 'free',
    traits: ['Animist', 'Apparition'],
  },

  // ── Level 20 ──
  {
    id: 'animist-eternal-guide',
    name: 'Eternal Guide',
    source: 'Animist',
    category: 'class',
    level: 20,
    description: 'Your attuned apparitions recognize that you still have essential work to do and refuse to allow you to pass on, gathering up your essence to carry your soul back to the community you call home. If you die, your apparitions carry your soul to a safe location familiar to you, and after 24 hours, you return to life at that location with 1 Hit Point. Frequency: once per week.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist', 'Apparition'],
  },
  {
    id: 'animist-true-channel',
    name: 'True Channel',
    source: 'Animist',
    category: 'class',
    level: 20,
    description: 'You are a true conduit for spiritual power, able to unleash the greatest spells. Once per day, when you cast a spell using one of your highest-rank animist spell slots, you don\'t expend the spell slot.',
    implemented: 'full',
    actionCost: 'passive',
    traits: ['Animist'],
  },
];
