import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Lost Omens: Knight Reclaimant,
// Knight Vigilant, Lastwall Sentry
// Character Guide / World Guide / Knights of Lastwall /
// Legends / Claws of the Tyrant
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// KNIGHT RECLAIMANT  (Character Guide pg. 95)
// ──────────────────────────────────────────────────────────

export const KNIGHT_RECLAIMANT_FEATS: FeatEntry[] = [
  {
    id: 'knight-reclaimant-dedication',
    name: 'Knight Reclaimant Dedication',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have sworn the Crimson Oath and become a full member of the Crimson Reclaimers. You gain expert proficiency in Stealth and Survival. Whenever you roll a success on a saving throw against an undead\'s special ability, you get a critical success instead. This applies to any abilities that come from being undead, including an undead\'s innate spells (but not its prepared or spontaneous spells).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Stealth and Survival', 'Member of the Knights of Lastwall of knight rank'],
    mechanics: 'Uncommon. Expert Stealth + Survival. Success on saves vs undead special abilities → crit success.',
  },
  {
    id: 'knight-reclaimant-ashen-veil',
    name: 'Ashen Veil',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'By smearing ash or tainted earth over your skin and armor, you shroud yourself from the dead. You become concealed to undead using vision or lifesense, allowing you to Hide and Sneak without other sources of cover or concealment. This effect lasts only as long as you continue to take no actions other than to Hide, Sneak, or other surreptitious actions. The GM determines which actions end the effect, but attacking, casting spells, activating items, and the like always do.',
    implemented: 'full',
    traits: ['Archetype', 'Manipulate', 'Skill'],
    actionCost: 3,
    prerequisites: ['Knight Reclaimant Dedication', 'Expert in Religion', 'Master in Stealth'],
    mechanics: '3-action. Concealed to undead (vision/lifesense). Hide/Sneak w/o cover. Ends on hostile actions.',
  },
  {
    id: 'knight-reclaimant-voice-cold-as-death',
    name: 'Voice Cold as Death',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'You utter a threat in a tone so icy it freezes the blood. Attempt an Intimidation check to Demoralize; you don\'t suffer a penalty if the target doesn\'t understand the language you\'re speaking, but this otherwise functions as normal. You can\'t use Intimidating Glare or any other effect that would cause your Demoralize attempt to lose the auditory trait as part of using this feat. If you critically succeed at your Intimidation check, the target becomes stunned 1, or stunned 2 if the target is undead. After using this feat, you are fatigued until the end of your next turn, and you can\'t use this feat again until the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Concentrate', 'Emotion', 'Fear', 'Mental', 'Skill'],
    actionCost: 1,
    prerequisites: ['Knight Reclaimant Dedication', 'Master in Intimidation'],
    mechanics: '1-action Demoralize. No language penalty. Crit success: stunned 1 (stunned 2 vs undead). Fatigued until end of next turn.',
  },
  {
    id: 'knight-reclaimant-invoke-crimson-oath',
    name: 'Invoke the Crimson Oath',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can invoke the Crimson Oath to unleash blasts of ruby energy from your weapon. You gain the invoke the Crimson Oath focus spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point, which you can regain using the Refocus activity to recite the Crimson Oath and meditate on its teachings; if you already have a focus pool, increase the number of Focus Points in your focus pool by 1. Your knight reclaimant focus spells are divine spells; when you gain this feat, you become trained in divine spell attacks and spell DCs. Your key spellcasting ability for these spells is Charisma.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication'],
    mechanics: 'Gain invoke the Crimson Oath focus spell. +1 Focus Point. Divine tradition, Charisma.',
  },
  {
    id: 'knight-reclaimant-survivor-of-desolation',
    name: 'Survivor of Desolation',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain a +2 circumstance bonus to saving throws against unnatural weather events or environmental hazards occurring in blighted or otherwise unnaturally marred regions. If you roll a success on a saving throw against such an effect, you get a critical success instead; if you roll a critical failure, you get a failure instead. This does not apply to unnatural events created or directed by active effects, such as spells that create anomalous weather or hazardous areas.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication'],
    mechanics: '+2 circumstance to saves vs unnatural weather/hazards in blighted regions. Success → crit success; crit fail → failure.',
  },
  {
    id: 'knight-reclaimant-hilt-hammer',
    name: 'Hilt Hammer',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You know how to turn any weapon into a bone-crushing implement of skeletal destruction. Melee weapons you wield gain the versatile B trait. You can use the weapon only to deal bludgeoning damage when making melee attacks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication'],
    mechanics: 'Melee weapons gain versatile B. Can deal bludgeoning only via versatile.',
  },
  {
    id: 'knight-reclaimant-shall-not-falter',
    name: 'Shall Not Falter, Shall Not Rout',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You gain the shall not falter, shall not rout focus spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point, which you can regain using the Refocus activity to recite the Crimson Oath and meditate on its teachings. If you already have a focus pool, increase the number of Focus Points in your focus pool by 1. Your knight reclaimant focus spells are divine spells; when you gain this feat, you become trained in divine spell attacks and spell DCs and your spellcasting ability is Charisma.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication'],
    mechanics: 'Rare. Gain shall not falter, shall not rout focus spell. +1 Focus Point. Divine, Charisma.',
  },
  {
    id: 'knight-reclaimant-blade-crimson-oath',
    name: 'Blade of the Crimson Oath',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You call upon the Crimson Oath to smite undead and then make a weapon or unarmed Strike against an undead foe. The Strike deals two extra weapon damage dice, and you can convert all the physical damage from the attack into vitality damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Knight Reclaimant Dedication'],
    mechanics: '2-action Strike vs undead. +2 weapon dice. Convert physical → vitality damage.',
  },
  {
    id: 'knight-reclaimant-for-love-for-lightning',
    name: 'For Love, For Lightning',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Rumors suggest this technique was pioneered by knights who undertook missions for Clarethe Iomedar at the half-moon, but many Crimson Reclaimers have since mastered it. You learn the for love, for lightning focus spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point; if you already have a focus pool, increase the number of Focus Points in your focus pool by 1. Your knight reclaimant focus spells are divine spells; Charisma is the key spellcasting ability.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication'],
    mechanics: 'Rare. Gain for love, for lightning focus spell. +1 Focus Point. Divine, Charisma.',
  },
  {
    id: 'knight-reclaimant-reaper-of-repose',
    name: 'Reaper of Repose',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your skill and fervor allow you to pierce undead defenses and exploit their weaknesses. When you make an attack using a weapon with which you have master proficiency and hit an undead creature, you ignore 5 points of the creature\'s resistances, and the undead\'s weaknesses are 2 higher against your attack.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication', 'Master proficiency in a weapon'],
    mechanics: 'Hit undead with master weapon: ignore 5 resistance, weaknesses +2 vs your attack.',
  },
  {
    id: 'knight-reclaimant-reclaimant-plea',
    name: 'Reclaimant Plea',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You call on the power of the Crimson Oath to gain magical aid. Choose one of the following spells: air walk, dimensional anchor, freedom of movement, invisibility, remove curse, searing light. You can cast that spell once per day as a 4th-level divine innate spell. At 14th level, the spell heightens to 5th level, and at 16th level, the spell heightens to 6th level. If you anger the mysterious source of the Crimson Oath\'s power, you lose the ability to cast the spell until you atone. Special: You can select this feat a second time at 14th level (gaining a second spell or death ward/flame strike), and a third time at 18th level (gaining a third spell or sunburst); all heighten to 7th level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication', 'Ability to cast divine spells'],
    mechanics: 'Choose 1 spell from list. 1/day as 4th-level divine innate. Heightens at 14th (5th), 16th (6th). Repeatable at 14 and 18.',
    subChoices: { label: 'Choose a spell', options: [
      { id: 'air-walk', name: 'Air Walk', description: 'Walk on air as if solid ground' },
      { id: 'dimensional-anchor', name: 'Dimensional Anchor', description: 'Prevent target from teleporting' },
      { id: 'freedom-of-movement', name: 'Freedom of Movement', description: 'Move freely despite impediments' },
      { id: 'invisibility', name: 'Invisibility', description: 'Become invisible' },
      { id: 'remove-curse', name: 'Remove Curse', description: 'Attempt to remove a curse' },
      { id: 'searing-light', name: 'Searing Light', description: 'Beam of holy light dealing fire damage' },
    ] },
  },
  {
    id: 'knight-reclaimant-shepherd-of-desolation',
    name: 'Shepherd of Desolation',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You know how to keep others alive in the Gravelands\' murkiest shadows. Allies within 10 feet of you gain the benefit of Survivor of Desolation. If you are a champion, this aura is a champion aura, even though you gained it from Knight Reclaimant instead of a champion feat or feature.',
    implemented: 'full',
    traits: ['Archetype', 'Aura'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication', 'Survivor of Desolation'],
    mechanics: '10-ft aura. Allies gain Survivor of Desolation benefit. Champion aura if champion.',
  },
  {
    id: 'knight-reclaimant-crimson-oath-devotion',
    name: 'Crimson Oath Devotion',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You\'ve made the Crimson Oath a part of yourself; you mumble it in your sleep and recite it under your breath as you march. You become an expert in divine spell attacks and spell DCs. If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Reclaimant Dedication', 'Ability to cast focus spells'],
    mechanics: 'Expert divine spell attacks/DCs. Spent 2+ FP → recover 2 FP on Refocus.',
  },
  {
    id: 'knight-reclaimant-grave-threat',
    name: 'Grave Threat',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You use your imposing demeanor to set up the undead for defeat. Make a Strike against an undead creature using a weapon with which you have master proficiency. If you hit, all Strikes against that creature gain the benefits of Reaper of Repose for 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Reaper of Repose'],
    mechanics: '1-action Strike vs undead (master weapon). Hit: all Strikes vs target gain Reaper of Repose for 1 round.',
  },
  {
    id: 'knight-reclaimant-cut-them-down',
    name: 'Cut them Down, Burn them Out',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Inspired by the sixth line of the Crimson Oath, when you oppose the enemies of Lastwall, you aim to excise the rot from the land itself. Make a Strike against an undead creature using a weapon with which you have master proficiency. On a success, in addition to the attack\'s other effects, the creature takes a –2 status penalty to the DC of any curses, diseases, or poisons it can inflict for 1 round. On a critical success, the penalty lasts 1 round, then a –1 penalty for an additional round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Knight Reclaimant Dedication', 'Master proficiency in a weapon'],
    mechanics: '1-action Strike vs undead (master weapon). Success: –2 status to curse/disease/poison DCs 1 round. Crit: –2 then –1.',
  },
  {
    id: 'knight-reclaimant-may-death-reconsider',
    name: 'May Death Itself Reconsider',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'Your will is so steadfast that even death can\'t stop you. You gain the ability to cast breath of life up to three times per day as a 5th-rank divine innate spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Reclaimant Plea'],
    mechanics: 'Cast breath of life 3/day as 5th-rank divine innate spell.',
  },
  {
    id: 'knight-reclaimant-the-tyrant-falls',
    name: 'The Tyrant Falls!',
    source: 'Knight Reclaimant (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You\'ve reached the apex of the Crimson Oath\'s power. When you use this feat, you cry out the final line of the Crimson Oath, unleashing unbridled power for 1 minute (Dismissible). At the beginning of each of your turns, you become drained 1 or increase drained by 1 (can\'t reduce while active; drained doesn\'t penalize Fort save). You can cast invoke the Crimson Oath at will without spending Focus Points (area increases to 40-ft cone). You gain resistance to all damage equal to half your level. Melee weapons gain reach (or +5 ft reach) and deal extra 2d6 vitality or void damage (whichever is more effective).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Knight Reclaimant Dedication', 'Invoke the Crimson Oath'],
    mechanics: '2-action, 1/day. 1-min Dismissible. Each turn: drained +1. At-will invoke Crimson Oath (40-ft cone). Resist all = half level. Weapons: reach + 2d6 vitality/void.',
  },
];

// ──────────────────────────────────────────────────────────
// KNIGHT VIGILANT  (Character Guide pg. 94)
// ──────────────────────────────────────────────────────────

export const KNIGHT_VIGILANT_FEATS: FeatEntry[] = [
  {
    id: 'knight-vigilant-dedication',
    name: 'Knight Vigilant Dedication',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You are dedicated to the cause of the Shining Sentinels. You gain expert proficiency in Religion. When you are between an ally and a foe and would provide lesser cover to your ally against the foe\'s attacks, you twist to become even more obtrusive, providing standard cover instead.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Religion', 'Member of the Knights of Lastwall of knight rank'],
    mechanics: 'Uncommon. Expert Religion. Lesser cover you provide to allies becomes standard cover.',
  },
  {
    id: 'knight-vigilant-divine-healing',
    name: 'Divine Healing',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Although you aren\'t a proper champion of your faith, your deity still recognizes your efforts and provides you with a small divine ability to help others. You gain the lay on hands devotion spell. You gain a focus pool of 1 Focus Point or increase the number of Focus Points in your focus pool by 1. You are trained in divine spell attack rolls and spell DCs. Your spellcasting ability is Charisma. You must refrain from performing your deity\'s anathema or lose the ability to cast this spell until you atone.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Expert in Religion', 'Worship a deity with a divine font that grants heal'],
    mechanics: 'Gain lay on hands focus spell. +1 Focus Point. Divine, Charisma. Lose on anathema.',
  },
  {
    id: 'knight-vigilant-interrupt-charge',
    name: 'Interrupt Charge',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You attempt to snag the foe before they run away. Attempt an Athletics check against the higher of the triggering creature\'s Athletics DC or Fortitude DC. Critical Success: disrupt the movement. Success: –10-foot circumstance penalty to Speed for rest of triggering movement. Failure: –5-foot penalty instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: 'Reaction. Trigger: foe within reach moves away. Athletics vs Athletics DC/Fort DC. Crit: disrupt. Success: –10 ft Speed. Fail: –5 ft.',
  },
  {
    id: 'knight-vigilant-phalanx-formation',
    name: 'Phalanx Formation',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You know how to clear a line of fire for your allies. You don\'t provide lesser cover to enemies against your allies\' attacks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: 'You don\'t provide lesser cover to enemies vs allies\' attacks.',
  },
  {
    id: 'knight-vigilant-unshakable-idealism',
    name: 'Unshakable Idealism',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your faith and hope can\'t be shaken, and you won\'t flee when lives are at stake. You gain a +1 circumstance bonus on saves against fear effects and emotion effects that inflict despair. When you would gain the fleeing condition, you can choose to stand your ground and be stunned for the effect\'s duration as well, preventing you from running and allowing you to re-enter the fight more quickly when the effect ends.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Expert in Will saves'],
    mechanics: '+1 circumstance vs fear/despair. Can replace fleeing with stunned.',
  },
  {
    id: 'knight-vigilant-emissary-of-peace',
    name: 'Emissary of Peace',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Even when bloodshed is inevitable, you would rather see your foes surrender. You attempt a Diplomacy check to Make an Impression against a single foe whose Hit Points are at less than half of their maximum value, followed by an immediate Request to convince that creature to cease fighting. You take a –5 penalty to your Diplomacy check. The GM sets the DC of the Request based on the circumstances; it\'s generally at least a very hard DC for the creature\'s level.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 3,
    prerequisites: ['Knight Vigilant Dedication', 'Master in Diplomacy'],
    mechanics: '3-action. Diplomacy (–5) Make Impression + Request vs foe below half HP to cease fighting.',
  },
  {
    id: 'knight-vigilant-endure-deaths-touch',
    name: 'Endure Death\'s Touch',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your conviction redirects the undead\'s attack through your armor and then harmlessly away. You gain resistance 5 to physical damage and resistance 10 to void damage against the triggering attack. You gain a +2 circumstance bonus on any saving throws against effects from the undead\'s natural attack; if you succeed at the saving throw, you get a critical success instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Knight Vigilant Dedication', 'Expert in medium or heavy armor'],
    mechanics: 'Reaction. Trigger: undead hits you with unarmed attack (wearing expert medium/heavy). Resist 5 physical + 10 void. +2 saves vs effects; success → crit.',
  },
  {
    id: 'knight-vigilant-instant-armor',
    name: 'Instant Armor',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'A knight is nothing without their armor, and you know how to keep yours ready. You can perform a 10-minute ritual (conjuration, magical) to divert heavy armor you\'re wearing into an extradimensional space. You can use a 3-action activity (concentrate, conjuration, teleportation) to phase the armor back and instantly don it. The armor automatically phases away if you don other armor, become unconscious, or die.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: '10-min ritual stores heavy armor. 3-action to recall and don instantly.',
  },
  {
    id: 'knight-vigilant-lead-the-way',
    name: 'Lead the Way',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You move forward, creating an opening for others to follow. Choose one adjacent ally who has a reaction available. You Stride, and that ally can use their reaction to immediately Stride. The ally must end their Stride adjacent to you. If the ally Strides in this way, they don\'t trigger reactions that are normally triggered by movement. You, however, still trigger those reactions normally.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: '2-action. Stride + 1 adjacent ally uses reaction to Stride (ends adjacent to you). Ally doesn\'t trigger movement reactions.',
  },
  {
    id: 'knight-vigilant-stalwart-standard',
    name: 'Stalwart Standard',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your banner makes it harder for your foes to push your allies around and encourages your allies to protect the innocent. Allies benefiting from your Cavalier\'s Banner feat gain a +1 circumstance bonus to Fortitude and Reflex DCs against Disarm, Grapple, Shove, and Trip. Each benefited ally also gains a +1 status bonus to attack rolls against any creature that has dealt damage to an innocent of a lower level within the last round.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Cavalier\'s Banner', 'Knight Vigilant Dedication'],
    mechanics: 'Uncommon. Banner allies: +1 circumstance to Fort/Ref DC vs maneuvers. +1 status to attacks vs foes who hurt innocents.',
  },
  {
    id: 'knight-vigilant-vigils-walls-rise-anew',
    name: 'Vigil\'s Walls Rise Anew!',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'As part of daily preparation, you can drill with a number of allies up to your Charisma modifier. When you use this feat\'s benefit, you and all drilled companions within 30 feet who are wielding shields Raise a Shield. Allies who Raise their Shields keep them raised until the start of their next turn, as normal.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 2,
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: 'Rare. 2-action. Drill CHA mod allies (daily prep). You + drilled allies within 30 ft Raise Shield.',
  },
  {
    id: 'knight-vigilant-aegis-of-arnisant',
    name: 'Aegis of Arnisant',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Inspired by the tale of Arnisant, you transform your shield into a magic ward. Until the beginning of your next turn, you gain Absorb into the Aegis reaction: when an enemy casts a spell targeting you or an ally within 15 feet, attempt a counteract check using Religion modifier. On success, the spell is counteracted and your shield takes damage equal to 4× spell rank. On failure, the shield takes 2× spell rank damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Knight Vigilant Dedication', 'Shield Block', 'Master in Religion'],
    mechanics: '2-action. Until next turn: reaction to counteract spells (Religion). Shield takes 4× or 2× spell rank damage.',
  },
  {
    id: 'knight-vigilant-guarded-advance',
    name: 'Guarded Advance',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You slowly advance on the battlefield, taking utmost caution. You either Step and Raise a Shield or Raise a Shield and Step.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: '1-action. Step + Raise Shield or Raise Shield + Step.',
  },
  {
    id: 'knight-vigilant-knight-in-shining-armor',
    name: 'Knight in Shining Armor',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'As a knight in shining armor, you train daily in the heaviest armor, expanding your expertise to heavy armor. You gain expert proficiency in heavy armor.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Expert in light armor, medium armor, or unarmored defense', 'Trained in heavy armor'],
    mechanics: 'Gain expert proficiency in heavy armor.',
  },
  {
    id: 'knight-vigilant-vigilant-benediction',
    name: 'Vigilant Benediction',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Unwilling to be outdone by the Crimson Reclaimers and their oath, you\'ve petitioned the gods of good for a sliver of divine magic. Choose a deity whose requirements you meet. You gain a 4th-level divine innate spell and become trained in divine spell DCs and attack rolls. Heightens at 14th (5th) and 16th (6th). Spell options vary by deity (e.g., Any Deity: freedom of movement, remove curse, resist energy, spell immunity, status; Iomedae: fire shield; etc.). Repeatable at 14th and 18th levels.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'must follow chosen deity\'s edicts'],
    mechanics: 'Choose deity + spell. 1/day 4th-level divine innate. Heightens 14th (5th), 16th (6th). Repeatable at 14, 18 (all → 7th).',
    subChoices: { label: 'Choose a benediction spell', options: [
      { id: 'freedom-of-movement', name: 'Freedom of Movement', description: '4th-level spell; move freely' },
      { id: 'remove-curse', name: 'Remove Curse', description: '4th-level spell; counteract a curse' },
      { id: 'resist-energy', name: 'Resist Energy', description: '4th-level spell; resist energy damage' },
      { id: 'spell-immunity', name: 'Spell Immunity', description: '4th-level spell; immune to one spell' },
      { id: 'status', name: 'Status', description: '4th-level spell; track ally condition' },
      { id: 'fire-shield', name: 'Fire Shield', description: '4th-level spell; fiery retaliation' },
    ] },
  },
  {
    id: 'knight-vigilant-instinctual-interception',
    name: 'Instinctual Interception',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You react to movement with hardly a thought, seeming constantly poised to spring. At the start of each of your turns, you gain an additional reaction that you can use only to Interrupt Charge.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Interrupt Charge'],
    mechanics: 'Gain additional reaction each turn for Interrupt Charge only.',
  },
  {
    id: 'knight-vigilant-keep-up-the-good-fight',
    name: 'Keep up the Good Fight',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your devotion to helping others and doing good keeps you going, even against insurmountable odds. Instead of being knocked out, you are reduced to 1 Hit Point, gain a number of temporary Hit Points equal to your level for 1 round, and increase your wounded value by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: 'Reaction, 1/hour. Trigger: foe Strike reduces you to 0 HP (must have had >1 HP, not lethal). Stay at 1 HP + level temp HP (1 round) + wounded +1.',
  },
  {
    id: 'knight-vigilant-preternatural-polish',
    name: 'Preternatural Polish',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Armor you polish shines with righteous grace. You can take 10 minutes to recite prayers or oaths while polishing heavy armor. Attempt a DC 35 Crafting check. Critical Success: once in the next hour, wearer can use reaction to counteract darkness effects (your Crafting modifier); also gains extra reaction each turn for this. Success: as critical success, but no extra reaction.',
    implemented: 'full',
    traits: ['Archetype', 'Exploration', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Legendary in Crafting'],
    mechanics: '10-min exploration. DC 35 Crafting. Crit: counteract darkness reaction + extra reaction. Success: counteract darkness reaction only. 1/day per armor.',
  },
  {
    id: 'knight-vigilant-rallying-charge',
    name: 'Rallying Charge',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'When you lead your allies to the front lines, you leave no one behind. When you Lead the Way, instead of choosing one ally, you can choose any number of allies within 10 feet of you. Any chosen allies that use their reaction to immediately Stride can end their Stride anywhere within 10 feet of you.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Lead the Way'],
    mechanics: 'Upgrades Lead the Way: any number of allies within 10 ft; they end within 10 ft of you.',
  },
  {
    id: 'knight-vigilant-body-barrier',
    name: 'Body Barrier',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'When your allies are in danger, you don\'t hesitate to take the brunt of the blow for them. You grant all allies in the area standard cover against the triggering effect, and you gain weakness to all damage against the triggering effect equal to twice the number of allies that gain cover in this way.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: 'Reaction. Trigger: you + allies in Reflex save area. Allies gain standard cover. You gain weakness = 2× allies covered.',
  },
  {
    id: 'knight-vigilant-empyreal-aura',
    name: 'Empyreal Aura',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'As an ultimate foe of the unholy and protector of the innocent, your very presence is a ward against wickedness. Each unholy creature within 30 feet of you at the end of your turn must succeed at a Will save against the higher of your class DC or spell DC or else become slowed 1 (slowed 2 on a critical failure). On a successful save, the creature is temporarily immune for 10 minutes.',
    implemented: 'full',
    traits: ['Archetype', 'Aura'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication', 'Legendary in Religion'],
    mechanics: '30-ft aura. Unholy creatures: Will vs class/spell DC. Fail: slowed 1. Crit fail: slowed 2. Save: immune 10 min.',
  },
  {
    id: 'knight-vigilant-tower-shield-mastery',
    name: 'Tower Shield Mastery',
    source: 'Knight Vigilant (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You\'ve learned how to maximize the defensive abilities of your tower shield. You are constantly quickened and can use the additional action only to Take Cover behind your tower shield after you have Raised it.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Knight Vigilant Dedication'],
    mechanics: 'Constantly quickened. Extra action: Take Cover behind raised tower shield only.',
  },
];

// ──────────────────────────────────────────────────────────
// LASTWALL SENTRY  (World Guide pg. 47)
// ──────────────────────────────────────────────────────────

export const LASTWALL_SENTRY_FEATS: FeatEntry[] = [
  {
    id: 'lastwall-sentry-dedication',
    name: 'Lastwall Sentry Dedication',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve sworn yourself as a sentry for the Knights of Lastwall, the first line of defense against incursions by the Whispering Tyrant throughout Golarion. You become trained in Athletics and in Undead Lore; if you were already trained, you become an expert instead. Finally, you gain the Reactive Shield fighter feat.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Member of the Knights of Lastwall', 'Shield Block'],
    mechanics: 'Uncommon. Trained Athletics + Undead Lore (or expert). Gain Reactive Shield.',
  },
  {
    id: 'lastwall-sentry-always-ready',
    name: 'Always Ready',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Extensive training against undead has taught you to cover your weak points, even when you think that you\'re alone. You aren\'t off-guard to hidden, undetected, or flanking undead of your level or lower. However, the undead can still help their allies flank. If all of your opponents are undead, you gain a +1 circumstance bonus to initiative rolls.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Not off-guard to hidden/undetected/flanking undead ≤ your level. All-undead fights: +1 circumstance to initiative.',
  },
  {
    id: 'lastwall-sentry-bless-shield',
    name: 'Bless Shield',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your uttered prayers become an aegis, drawing the blessing of your deity across the surface of your shield. Until the beginning of your next turn your shield, any shield boss, or shield spikes gain the effects of a ghost touch property rune. Additionally, damage you take as a result of an incorporeal creature\'s Strike can trigger your Shield Block reaction, even if the damage isn\'t physical damage.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 1,
    prerequisites: ['Lastwall Sentry Dedication', 'You worship a deity with holy sanctification'],
    mechanics: '1-action. Shield gains ghost touch until next turn. Incorporeal damage can trigger Shield Block.',
  },
  {
    id: 'lastwall-sentry-eye-of-ozem',
    name: 'Eye of Ozem',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned how to spot danger at a distance, allowing you to serve as a sentry with ease. You gain a +2 circumstance bonus to initiative rolls when using Perception, and when you\'re Scouting, you grant your allies a +2 circumstance bonus instead of +1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication', 'Expert in Perception'],
    mechanics: '+2 circumstance to Perception initiative. Scouting: allies get +2 instead of +1.',
  },
  {
    id: 'lastwall-sentry-familiar-foe',
    name: 'Familiar Foe',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You regularly face off against undead and can identify many with a glance. You gain a +2 circumstance bonus to checks to Recall Knowledge about undead. Whenever you roll a critical failure on a check to Recall Knowledge about undead, you get a failure instead.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication', 'Expert in Religion or Undead Lore'],
    mechanics: '+2 circumstance to Recall Knowledge (undead). Crit fail → failure.',
  },
  {
    id: 'lastwall-sentry-final-rest',
    name: 'Final Rest',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'As stubborn in death as you are in life, you vow you\'ll never aid your hated enemies. You can\'t be transformed into an undead, except by effects that originate from an artifact or deity. Undead creatures that touch your corpse take 1 vitality damage each time they do, or 1d6 vitality damage each time they expose themselves to your corpse in a more thorough manner (biting, carrying, etc.).',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Can\'t be turned undead (except artifact/deity). Corpse deals 1 or 1d6 vitality to undead touching it.',
  },
  {
    id: 'lastwall-sentry-necromantic-resistance',
    name: 'Necromantic Resistance',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'As part of your training, you\'ve inured yourself against necromancy through repeated exposure. You gain a +1 circumstance bonus to saves against necromancy effects and gain resistance to void damage equal to half your level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: '+1 circumstance vs necromancy. Resistance void = half level.',
  },
  {
    id: 'lastwall-sentry-nonlethal-takedown',
    name: 'Nonlethal Takedown',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You prefer to use nonlethal means against living opponents, but the weapons you carry are lethal enough to destroy undead. You don\'t take the normal –2 circumstance penalty when attacking nonlethally with a weapon that lacks the nonlethal trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'No –2 penalty for nonlethal attacks with lethal weapons.',
  },
  {
    id: 'lastwall-sentry-rescuers-press',
    name: 'Rescuer\'s Press',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Any shield you wield gains the shove trait. When you Shove using a shield and Stride as part of that action, you can move an additional 5 feet to either side of the creature you Shoved. In addition, if you are in the Everstand Stance and successfully Shove a creature using a shield that you wield two-handed, you can increase the distance of your Shove to 10 feet.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Rare. Shields gain shove trait. Shove + Stride: +5 ft movement to side. Everstand 2H: Shove 10 ft.',
  },
  {
    id: 'lastwall-sentry-grave-sense',
    name: 'Grave Sense',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your time spent hunting the undead allows you to sense them. You sense undead as a vague sense similar to a human\'s sense of smell, an uncomfortable sensation akin to smelling something cloying and rotting. When in proximity to the undead, you eventually sense their presence, though you might not do so instantly, and you can\'t pinpoint their location. An undead using a disguise or trying to hide its presence must attempt a Deception check against your Perception DC to hide from you. On success, temporarily immune 1 day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Vague sense for undead. Undead: Deception vs your Perception DC to hide. Immune 1 day on success.',
  },
  {
    id: 'lastwall-sentry-practiced-opposition',
    name: 'Practiced Opposition',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'ve battled more undead than you care to remember, often with little time to prepare between foes. Attempt a check to Recall Knowledge about an undead you can see and then Strike that undead. If your attempt to Recall Knowledge is successful, your Strike treats the target\'s resistances as 5 lower. The target is then immune to your Practiced Opposition for 24 hours.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: '1-action. Recall Knowledge + Strike vs undead. Success: ignore 5 resistance. Target immune 24 hours.',
  },
  {
    id: 'lastwall-sentry-repulse-the-wicken',
    name: 'Repulse the Wicken',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You use your foe\'s failure as an opening to push them away. Attempt to Shove the undead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Reaction. Trigger: undead within reach crit fails attack vs you. Free Shove attempt.',
  },
  {
    id: 'lastwall-sentry-sacred-armaments',
    name: 'Sacred Armaments',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Through the power of your faith or the blessing of a priest, your weapons are fully effective against incorporeal creatures. Weapons you wield have the effects of a ghost touch property rune for as long as you wield them.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'All wielded weapons gain ghost touch.',
  },
  {
    id: 'lastwall-sentry-flashing-shield',
    name: 'Flashing Shield',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your shield flares with holy light as you block the attack, searing the undead with the power of your faith. The triggering undead takes vitality damage equal to half your level and becomes off-guard for 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Lastwall Sentry Dedication', 'You worship a deity with holy sanctification'],
    mechanics: 'Free action. Trigger: Shield Block vs adjacent undead. Undead takes half-level vitality damage + off-guard 1 round.',
  },
  {
    id: 'lastwall-sentry-necromantic-bulwark',
    name: 'Necromantic Bulwark',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Regular exposure to necromantic effects left you better able to defend against them. When you have your shield raised, you gain your shield\'s circumstance bonus to saving throws against effects that would deal void damage. If you have the Shield Block reaction, void damage you take can trigger the reaction, even though the damage isn\'t physical damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Shield raised: shield bonus to saves vs void damage. Shield Block can trigger on void damage.',
  },
  {
    id: 'lastwall-sentry-necromantic-tenacity',
    name: 'Necromantic Tenacity',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your training against necromantic effects allows you to escape the worst of their touch. If you roll a success on a saving throw against a necromancy effect, you get a critical success instead; if you roll a critical failure on such a save, you get a failure instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Necromantic Resistance'],
    mechanics: 'Success → crit success vs necromancy. Crit fail → failure vs necromancy.',
  },
  {
    id: 'lastwall-sentry-grave-sight',
    name: 'Grave Sight',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your ability to sense undead has improved. You sense undead as an imprecise sense with a range of 60 feet. When in proximity to an undead, you can sense its presence, but it has the hidden condition instead of the observed condition. An undead using a disguise or trying to hide must attempt a Deception or Stealth check against your Perception DC. If the creature succeeds, it\'s undetected, and you need Seek to detect it.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication', 'Grave Sense'],
    mechanics: 'Imprecise sense 60 ft for undead. Undead: Deception/Stealth vs Perception DC to be undetected.',
  },
  {
    id: 'lastwall-sentry-lastwall-warden',
    name: 'Lastwall Warden',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You use your shield to protect your allies, not just yourself, especially against the undead. When you have a shield raised, you can use your Shield Block reaction when an attack is made against an ally adjacent to you, in addition to its usual trigger. If an undead makes an attack against an ally within 10 feet, you can Step to become adjacent to your ally and then use Shield Block as part of the same reaction.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Shield Block for adjacent ally. Vs undead: Step to ally within 10 ft + Shield Block.',
  },
  {
    id: 'lastwall-sentry-no-stranger-to-death',
    name: 'No Stranger to Death',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your regular exposure to the insidious putrescence of undeath inured you to its effects. You gain a +2 circumstance bonus to saving throws made against spells and effects with the death, disease, and unholy traits. Whenever you become drained or sickened, reduce the status penalty you take from the condition by 1, to a minimum of 0.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: '+2 circumstance vs death/disease/unholy. Drained/sickened penalty reduced by 1 (min 0).',
  },
  {
    id: 'lastwall-sentry-resolute-defender',
    name: 'Resolute Defender',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You hold your shield together with the power of your faith and conviction, refusing to let wood splinter and steel shatter until the day\'s battles are won. If a shield would be destroyed due to damage taken during your Shield Block, the shield remains intact at 1 Hit Point instead. Its construction is weakened until you repair it, preventing you from using Resolute Defender to save the same shield again until your next daily preparations.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Shield Block destruction → shield stays at 1 HP instead. Can\'t save same shield again until daily prep.',
  },
  {
    id: 'lastwall-sentry-thwart-evil',
    name: 'Thwart Evil',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You react instinctively when you sense unholy power forming, thrusting your spiritual energy toward the source to snuff it out before it fully manifests. Attempt to counteract the triggering spell or ability using your Religion modifier as your counteract modifier.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Lastwall Sentry Dedication', 'Expert in Religion'],
    mechanics: 'Reaction, 1/day. Trigger: creature uses unholy/void spell/ability. Counteract with Religion.',
  },
  {
    id: 'lastwall-sentry-withstand-death',
    name: 'Withstand Death',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Through repeated exposure, you\'ve trained to resist the damage wrought by undead. Your resistance to void damage also applies to damage dealt by the attacks and abilities of undead creatures, regardless of damage type.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication', 'Necromantic Resistance'],
    mechanics: 'Void resistance extends to all damage from undead attacks/abilities.',
  },
  {
    id: 'lastwall-sentry-spirit-of-vigil',
    name: 'Spirit of Vigil',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Though the city of Vigil itself has been destroyed, you will carry on its warrior spirit to the end of your days. The value of your dying condition at which you die increases by 1 (normally to dying 5, or dying 6 if you have Diehard), and the reduction to your maximum dying value from the doomed condition is 1 less severe (to a minimum of 0).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['No Stranger to Death'],
    mechanics: 'Die at dying 5 (6 with Diehard). Doomed reduces max dying by 1 less.',
  },
  {
    id: 'lastwall-sentry-uncanny-vitae',
    name: 'Uncanny Vitae',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your warrior spirit is infused with a potent vital essence that imbues your gear. Any shield you wield treats its Hardness as 5 higher against damage dealt by undead creatures.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lastwall Sentry Dedication'],
    mechanics: 'Shields: +5 Hardness vs undead damage.',
  },
  {
    id: 'lastwall-sentry-cenotaph-stance',
    name: 'Cenotaph Stance',
    source: 'Lastwall Sentry (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You take on a stance that marks your location as a place where none will fall. When you enter this stance and at the beginning of each of your turns, you gain 10 temporary Hit Points that last until the start of your next turn. If you move or are forced to move, you leave Cenotaph Stance. While in this stance, you\'re treated as always having the required shield raised. You can use Shield Block when an ally within 15 feet takes physical damage. You gain an additional reaction each turn for Shield Block only.',
    implemented: 'full',
    traits: ['Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Lastwall Warden'],
    mechanics: '1-action stance. 10 temp HP/turn. Ends on movement. Shield always raised. Shield Block for allies within 15 ft. Extra reaction for Shield Block.',
  },
];

// ══════════════════════════════════════════════════════════
export const STANDALONE_ARCHETYPE_FEATS_LEGACY_LO2: FeatEntry[] = [
  ...KNIGHT_RECLAIMANT_FEATS,
  ...KNIGHT_VIGILANT_FEATS,
  ...LASTWALL_SENTRY_FEATS,
];
