import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — L through R
// Lion Blade, Munitions Master, Palatine Detective,
// Prophet of Kalistrade, Red Mantis Assassin
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// LION BLADE  (Shining Kingdoms pg. 170–171)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=319
// Access: You're from Taldor.
// ──────────────────────────────────────────────────────────

export const LION_BLADE_FEATS: FeatEntry[] = [
  {
    id: 'lion-blade-dedication',
    name: 'Lion Blade Dedication',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your Lion Blade spy training helps you conceal yourself and your identity. You become trained in your choice of Deception or Stealth; if already trained, you become an expert instead. You gain the Additional Lore skill feat for Espionage Lore. You never take circumstance penalties for attempting to take a disguise of a different ancestry, age, and so on, as long as the disguised form is appropriate for your size.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Member of the Lion Blades', 'Trained in Performance'],
    mechanics: 'Access: You\'re from Taldor. Trained in Deception or Stealth (or expert if already trained). Gains Espionage Lore. Removes circumstance penalties on disguise for different ancestry/age. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'lion-blade-inspiring-recitation',
    name: 'Inspiring Recitation',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You quietly speak or recall coded phrases whose meanings inspire you. You gain a +1 status bonus to one skill of your choice until the beginning of your next turn. You can Sustain this effect for up to 1 minute. If you\'re an expert in Performance, the bonus increases to +2; master +3; legendary +4.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Emotion', 'Mental'],
    actionCost: 1,
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Frequency: once per hour. Scalable status bonus to a chosen skill (+1 to +4 based on Performance proficiency). Sustainble up to 1 minute.',
  },
  {
    id: 'lion-blade-lost-in-the-crowd',
    name: 'Lost in the Crowd',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You move at full Speed in crowds and can use cover from crowds to Hide and Sneak, gaining a +2 circumstance bonus to Stealth checks when in a crowd of at least 10 creatures and a +4 circumstance bonus in a crowd of at least 100 creatures.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Full Speed in crowds. Use crowd cover to Hide/Sneak. +2 circumstance to Stealth (10+ crowd), +4 (100+ crowd).',
  },
  {
    id: 'lion-blade-crowd-mastery',
    name: 'Crowd Mastery',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You use the crowd to your advantage, diverting your foes\' attention to potential hidden dangers. When determining if your foe is flanked, treat all squares occupied by a crowd as if they were occupied by an ally with a melee reach of 5 feet.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lost in the Crowd'],
    mechanics: 'Crowd-occupied squares count as allies for flanking purposes.',
  },
  {
    id: 'lion-blade-expeditious-advance',
    name: 'Expeditious Advance',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You advance and retreat quickly. You gain a +10-foot status bonus to your Speed.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Requires unarmored or wearing light armor. +10-foot status bonus to Speed.',
  },
  {
    id: 'lion-blade-interposing-crowd',
    name: 'Interposing Crowd',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your enemies can\'t stop you when there\'s a host of people between you. Your movement actions don\'t trigger reactions as long as you remain in a crowd for the entire duration of the action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lost in the Crowd'],
    mechanics: 'Movement actions don\'t trigger reactions while in a crowd.',
  },
  {
    id: 'lion-blade-lions-magic',
    name: 'Lion\'s Magic',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can cast a 4th-rank suggestion as an occult innate spell once per day. At 12th level, you can also cast a 5th-rank subconscious suggestion once per day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lion Blade Dedication'],
    mechanics: '1/day 4th-rank suggestion (occult innate). At 12th level, also 1/day 5th-rank subconscious suggestion.',
  },
  {
    id: 'lion-blade-spys-countermeasures',
    name: 'Spy\'s Countermeasures',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you succeed at a save against a detection, mental, or scrying effect, you can attempt to identify the effect via Identify Magic using the magical tradition skill or Espionage Lore. If you successfully identify it and it would normally fail, you can make the caster think it succeeded — providing false results, pretending to be affected, or disregarding commands through a mental link.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Trigger: succeed at a save vs detection/mental/scrying. Identify via tradition skill or Espionage Lore, then feed false information to the caster or pretend to be affected.',
  },
  {
    id: 'lion-blade-flickering-twirl',
    name: 'Flickering Twirl',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You use your movements and disguises to make yourself a flickering blur. You gain concealment until the beginning of your next turn. As usual for concealment involving an obvious visual manifestation, you can\'t use this concealment to Hide.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Grants concealment until start of next turn (cannot use to Hide).',
  },
  {
    id: 'lion-blade-slowing-strike',
    name: 'Slowing Strike',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You wound your enemy so they can\'t move nimbly. The target must attempt a Fortitude save against your class DC or spell DC, whichever is higher. Success: –10-foot status penalty to Speeds until start of your next turn. Failure: –10-foot penalty for 1 minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Frequency: once per round. Trigger: your Strike hits an off-guard creature and deals damage. Fort save vs class/spell DC. Success: –10 ft Speed (1 turn). Failure: –10 ft Speed (1 minute). Crit success: unaffected.',
  },
  {
    id: 'lion-blade-stunning-surprise',
    name: 'Stunning Surprise',
    source: 'Lion Blade (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You move up to your Speed then make a melee Strike. If you hit and deal damage, the target attempts a Fortitude save against your class DC or spell DC. Critical Success: Unaffected. Success: Stunned 1, no reactions until next turn. Failure: Stunned 3, no reactions until next turn. Critical Failure: Unconscious for 1 minute. Target is then immune for 24 hours.',
    implemented: 'full',
    traits: ['Archetype', 'Incapacitation'],
    actionCost: 2,
    prerequisites: ['Lion Blade Dedication'],
    mechanics: 'Requires being undetected by the target. Move + melee Strike; Fort save or stunned (1/3/unconscious). Incapacitation trait. 24-hour immunity after.',
  },
];

// ──────────────────────────────────────────────────────────
// MUNITIONS MASTER  (Battlecry! pg. 64–65)
// Category: Class (Inventor) — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=329
// Class archetype for Inventor with light mortar innovation
// ──────────────────────────────────────────────────────────

export const MUNITIONS_MASTER_FEATS: FeatEntry[] = [
  {
    id: 'munitions-master-dedication',
    name: 'Munitions Master Dedication',
    source: 'Munitions Master (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have drilled enough with your light mortar to operate it with unrivaled efficiency. You gain the Engineer\'s Efficiency action [1-action]: Frequency once per turn; Requirements you are adjacent to your light mortar; Effect: You Aim your light mortar and then either Load or Launch it.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Light mortar innovation'],
    mechanics: 'Class archetype for Inventor. Grants Engineer\'s Efficiency (1-action, 1/turn): Aim + Load/Launch light mortar while adjacent. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'munitions-master-focused-fire',
    name: 'Focused Fire',
    source: 'Munitions Master (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You limit the blast of your shot for accuracy. You Launch your light mortar, targeting a single square. The blast is limited to the targeted square but deals one additional die of damage.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Munitions Master Dedication'],
    mechanics: 'Launch targeting single square (no burst area) but with +1 damage die. Flourish (once per turn).',
  },
  {
    id: 'munitions-master-wrapped-in-smoke',
    name: 'Wrapped in Smoke',
    source: 'Munitions Master (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You ignite a small portion of powder in a rapid, inefficient burn, creating a hazy cloud. You create a cloud of smoke in a 5-foot emanation centered on your innovation, which lasts for 1 minute. All creatures and objects within become concealed, and those outside become concealed to those within.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Munitions Master Dedication'],
    mechanics: 'Creates 5-ft smoke cloud centered on mortar for 1 minute. Grants mutual concealment.',
  },
  {
    id: 'munitions-master-siege-celerity',
    name: 'Siege Celerity',
    source: 'Munitions Master (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You push yourself and your light mortar beyond your limits. You are quickened for 1 action to Load or Launch your light mortar. This doesn\'t allow you to bypass the normal limit of one Launch per round.',
    implemented: 'full',
    traits: ['Archetype', 'Manipulate', 'Unstable'],
    actionCost: 'free',
    prerequisites: ['Munitions Master Dedication'],
    mechanics: 'Trigger: your turn begins. Unstable free action: quickened for 1 action (Load or Launch only). Can\'t exceed 1 Launch/round.',
  },
  {
    id: 'munitions-master-recoiling-relocation',
    name: 'Recoiling Relocation',
    source: 'Munitions Master (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your innovation contains a chamber to store compressed exhaust gas. You can release this gas coinciding with recoil to propel your mortar and yourself through the air. You and your light mortar move up to the light mortar\'s Speed in the direction of your choice. You must end this movement adjacent to your innovation.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish', 'Unstable'],
    actionCost: 'free',
    prerequisites: ['Munitions Master Dedication'],
    mechanics: 'Trigger: you launch your light mortar. Requires adjacency. Unstable free action: reposition yourself + mortar up to mortar\'s Speed. Must end adjacent to mortar.',
  },
  {
    id: 'munitions-master-burrowing-shot',
    name: 'Burrowing Shot',
    source: 'Munitions Master (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You tune your light mortar to maximize penetration into hard surfaces. You Launch your light mortar, dealing half the normal amount of damage to creatures in the area of the blast but double damage to objects and structures.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Munitions Master Dedication'],
    mechanics: 'Launch that deals half damage to creatures, double damage to objects/structures.',
  },
];

// ──────────────────────────────────────────────────────────
// PALATINE DETECTIVE  (Divine Mysteries pg. 288–289)
// Category: Profession / Class / Multiclass — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=306
// Class archetype for Investigator (esoterica methodology)
// ──────────────────────────────────────────────────────────

export const PALATINE_DETECTIVE_FEATS: FeatEntry[] = [
  {
    id: 'palatine-detective-dedication',
    name: 'Palatine Detective Dedication',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have crafted a small charm that soothes your mind and protects you against harm. While you wear this charm, you gain a +1 status bonus to saving throws against mental effects. You also gain the Mystic Aegis reaction [reaction] (concentrate, magical): Trigger: a creature you have successfully Recalled Knowledge about would damage you; Requirements: free hand; Effect: you gain resistance to all damage equal to 2 + half your level (rounded up) against the triggering effect.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Investigator class'],
    mechanics: 'Class archetype for Investigator. +1 status bonus to saves vs mental. Mystic Aegis reaction: resistance to all damage = 2 + half your level vs creature you\'ve Recalled Knowledge about. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'palatine-detective-esoteric-spellcasting',
    name: 'Esoteric Spellcasting',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Choose a 1st-rank occult or divine spell. You can cast this spell once per day as an innate spell. At 6th level, you gain a 2nd-rank spell of the same tradition, and at 8th level, you gain a 3rd-rank spell. You can take this feat a second time, choosing spells from the other tradition.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: 'Innate spell 1/day (occult or divine): 1st-rank at 4th, 2nd-rank at 6th, 3rd-rank at 8th. Special: can take twice for both traditions.',
  },
  {
    id: 'palatine-detective-text-decoder',
    name: 'Text Decoder',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can always use Occultism or Religion when you Decipher Writing, no matter the subject matter. You can ignore language constraints when Deciphering Writing, and when you critically fail, you get a failure instead.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: 'Use Occultism/Religion for any Decipher Writing. Ignore language constraints. Crit fail → failure.',
  },
  {
    id: 'palatine-detective-enchantment',
    name: 'Palatine Enchantment',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Whenever you Devise a Stratagem against a creature about which you could Recall Knowledge using Occultism or Religion, you can make the subsequent Strike against that creature as if the weapon has either a ghost touch or vitalizing property rune.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: 'Strikes after Devise a Stratagem vs Occultism/Religion-targetable creatures can treat weapon as ghost touch or vitalizing.',
  },
  {
    id: 'palatine-detective-challenge-insight',
    name: 'Challenge Insight',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your deep grasp of the mystical lets you know exactly what to say to make others doubt their own power. Attempt a counteract check against the triggering spell. Your counteract rank is half your level rounded up. Use Occultism (occult tradition) or Religion (divine tradition) as your counteract modifier. If you successfully counteract the spell, the caster becomes stupefied 1 until the end of their next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory'],
    actionCost: 'reaction',
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: 'Frequency: once per day. Trigger: a creature you can see Casts a divine or occult spell; they must hear/understand you. Counteract + stupefied 1 on success.',
  },
  {
    id: 'palatine-detective-strike',
    name: 'Palatine Strike',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your strikes are particularly deadly against supernatural creatures. Whenever you deal precision damage with strategic strike to a creature about which you have successfully used Occultism or Religion to Recall Knowledge, you deal an additional 2d6 precision damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: '+2d6 precision damage on strategic strikes vs creatures you\'ve Recalled Knowledge about using Occultism/Religion.',
  },
  {
    id: 'palatine-detective-cursebreaker',
    name: 'Cursebreaker',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'It takes 10 minutes to perform these rites on a willing creature within your reach. Attempt to counteract one curse; your counteract rank is half your level rounded up, using Occultism or Religion as your modifier. If the afflicted creature or the curse-placer is your active lead via Pursue a Lead, gain a +1 circumstance bonus. A success against a cursed item means the target can rid itself of it, but doesn\'t remove the curse from the item.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Healing', 'Manipulate'],
    actionCost: 'passive',
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: 'Frequency: once per day. 10-minute rite to counteract a curse (Occultism/Religion). +1 circumstance if target or curse-source is your active Pursue a Lead.',
  },
  {
    id: 'palatine-detective-open-blazing-eye',
    name: 'Open the Blazing Eye',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'A lightless flame appears in the center of your forehead. For 1 minute, you gain the benefits of see the unseen. Strikes against creatures you could Recall Knowledge about using Occultism or Religion ignore circumstance penalties and concealment/hidden flat checks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Palatine Detective Dedication'],
    mechanics: 'Frequency: once per day. 1-minute see the unseen. Strikes vs Occultism/Religion-targetable creatures ignore circumstance penalties and concealment flat checks.',
  },
  {
    id: 'palatine-detective-greater-esoteric-spellcasting',
    name: 'Greater Esoteric Spellcasting',
    source: 'Palatine Detective (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You become an expert in spell attack modifier and spell DC statistics. Choose a tradition from Esoteric Spellcasting. You gain a 4th-rank spell of that tradition as an innate spell 1/day. At 12th level, a 5th-rank spell; at 14th level, a 6th-rank spell. You can take this feat a second time for the other tradition.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Esoteric Spellcasting'],
    mechanics: 'Expert spell attack/DC. Additional innate spells (4th at 12, 5th at 12, 6th at 14). Special: can take twice for both traditions.',
  },
];

// ──────────────────────────────────────────────────────────
// PROPHET OF KALISTRADE  (Shining Kingdoms pg. 74–75)
// Category: Faction / Mystical — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=315
// Access: You're from Druma.
// ──────────────────────────────────────────────────────────

export const PROPHET_OF_KALISTRADE_FEATS: FeatEntry[] = [
  {
    id: 'prophet-of-kalistrade-dedication',
    name: 'Prophet of Kalistrade Dedication',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become an expert in Society and can use Society instead of Diplomacy to Make an Impression on merchants and traders. If you don\'t already cast spells from spell slots, you gain spontaneous occult cantrips: two common occult cantrips plus either prestidigitation or read aura. You\'re trained in spell attack modifier and spell DC. Charisma is your key spellcasting attribute.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Society and Mercantile Lore', 'Charisma 14+'],
    mechanics: 'Access: You\'re from Druma. Expert Society. Society for Make an Impression on merchants. Spontaneous occult cantrips (2 common + prestidigitation/read aura). CHA key. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'prophet-of-kalistrade-basic-spellcasting',
    name: 'Basic Prophet Spellcasting',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the basic spellcasting benefits. Each time you gain a spell slot of a new rank from this archetype, add a common occult spell of the appropriate rank (or another appropriate occult spell you\'ve learned or discovered) to your repertoire.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Prophet of Kalistrade Dedication'],
    mechanics: 'Basic spellcasting benefits (occult spontaneous). Adds spells to repertoire as new ranks unlock.',
  },
  {
    id: 'prophet-of-kalistrade-smile-at-failure',
    name: 'Smile at Failure',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When a creature you\'re interacting with decreases its attitude from indifferent to unfriendly or from unfriendly to hostile, you gain a +2 circumstance bonus to Make an Impression on the creature for the next hour. If this decrease leads to combat, you gain a +1 circumstance bonus to the subsequent initiative roll instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Prophet of Kalistrade Dedication'],
    mechanics: 'When creature\'s attitude drops: +2 circumstance to Make Impression for 1 hour, or +1 to initiative if it leads to combat.',
  },
  {
    id: 'prophet-of-kalistrade-fortunes-favor',
    name: 'Fortune\'s Favor',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You understand when an investment in you has the chance to pay off. You gain a +2 circumstance bonus to the triggering roll.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Prophet of Kalistrade Dedication'],
    mechanics: 'Frequency: once per day. Trigger: you\'re about to reroll a failed skill check or saving throw due to a fortune effect. +2 circumstance bonus to the reroll.',
  },
  {
    id: 'prophet-of-kalistrade-prolific-spellcasting',
    name: 'Prolific Prophet Spellcasting',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Increase the number of spells in your repertoire and spell slots from prophet of Kalistrade archetype feats by 1 for each spell rank other than your two highest prophet of Kalistrade spell slots.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Prophet Spellcasting'],
    mechanics: '+1 spell slot and +1 repertoire spell per rank (except 2 highest ranks).',
  },
  {
    id: 'prophet-of-kalistrade-lockbox',
    name: 'Prophet\'s Lockbox',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You can cast imaginary lockbox as a 5th-rank innate occult spell once per day. At 12th level and every 2 levels thereafter, the maximum Bulk you can target increases by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Prophet of Kalistrade Dedication'],
    mechanics: '1/day 5th-rank imaginary lockbox (occult innate). Bulk capacity scales at 12th+ every 2 levels.',
  },
  {
    id: 'prophet-of-kalistrade-expert-spellcasting',
    name: 'Expert Prophet Spellcasting',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You gain the expert spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Prophet Spellcasting', 'Master in Society'],
    mechanics: 'Expert spellcasting benefits (expert proficiency in spell attack/DC, additional higher-rank slots).',
  },
  {
    id: 'prophet-of-kalistrade-master-merchant',
    name: 'Master Merchant',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When you fail (but not critically fail) at a Society or Mercantile Lore check to Earn Income and are allowed to continue working, you can retry the next day. If you succeed on the retry, you get a critical success and continue earning that amount for the remainder of the task.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Prophet of Kalistrade Dedication'],
    mechanics: 'On failed (not crit failed) Earn Income: retry next day; success on retry = critical success for remaining duration.',
  },
  {
    id: 'prophet-of-kalistrade-master-spellcasting',
    name: 'Master Prophet Spellcasting',
    source: 'Prophet of Kalistrade (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You gain the master spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Expert Prophet Spellcasting', 'Legendary in Society'],
    mechanics: 'Master spellcasting benefits (master proficiency, highest-rank spell slots).',
  },
];

// ──────────────────────────────────────────────────────────
// RED MANTIS ASSASSIN  (Prey for Death pg. 108–109)
// Category: Faction / Combat Style — Uncommon, PFS Limited
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=271
// Access: You are from Mediogalti Island.
// ──────────────────────────────────────────────────────────

export const RED_MANTIS_ASSASSIN_FEATS: FeatEntry[] = [
  {
    id: 'red-mantis-assassin-dedication',
    name: 'Red Mantis Assassin Dedication',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become trained in Stealth and Assassin Lore; if already trained, you become an expert instead. Whenever your proficiency in any weapon increases to expert or beyond, you also gain that new proficiency with sawtooth sabers. You become bound by Achaekek\'s anathema and can receive his sanctification.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in sawtooth sabers', 'Worshipper of Achaekek', 'Member of the Red Mantis assassins'],
    mechanics: 'Access: You are from Mediogalti Island. PFS Limited. Trained in Stealth and Assassin Lore (or expert). Sawtooth saber proficiency scales with any weapon proficiency increase. Bound by Achaekek\'s anathema. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'red-mantis-assassin-basic-magic',
    name: 'Basic Red Mantis Magic',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the Cast a Spell activity. You can prepare two common divine cantrips each day. You also gain the basic spellcasting benefits. You\'re trained in spell attack modifier and spell DC. Charisma is your key spellcasting attribute, and they are divine Red Mantis spells. You gain access to the Red Mantis magic school — you can prepare spells from it alongside regular divine spells. If you gain a Focus Pool from Red Mantis feats, you can Refocus by praying to Achaekek or researching your assigned kill.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Red Mantis Assassin Dedication'],
    mechanics: 'Prepared divine cantrips (2/day) + basic spellcasting benefits. Access to Red Mantis magic school. CHA key attribute. Refocus via prayer/research.',
  },
  {
    id: 'red-mantis-assassin-crimson-shroud',
    name: 'Crimson Shroud',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You swathe yourself in a veil of red mist for 1 minute. While active, you gain fast healing equal to half your level. You can Interact with your shroud to gain a +1 circumstance bonus to AC until the beginning of your next turn. If you die while the shroud is active, you can choose to have your body vanish into red mist, leaving behind only your gear. At 10th level, you can use this once per hour instead of once per day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Red Mantis Assassin Dedication'],
    mechanics: 'Frequency: 1/day (1/hour at 10th). 1-minute red mist: fast healing (half level). Interact for +1 AC. Optional body vanish on death.',
  },
  {
    id: 'red-mantis-assassin-school-spell',
    name: 'Red Mantis School Spell',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You gain the Red Mantis magic school\'s initial school spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Red Mantis Magic'],
    mechanics: 'Grants initial Red Mantis school focus spell + focus pool.',
  },
  {
    id: 'red-mantis-assassin-achaekeks-grip',
    name: 'Achaekek\'s Grip',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You sense if a creature you have slain in the last year has been restored to life, as long as you and that creature are on the same plane. You also gain the Achaekek\'s clutch focus spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Red Mantis Magic'],
    mechanics: 'Sense resurrection of your kills (same plane, within 1 year). Gains Achaekek\'s clutch focus spell + focus pool.',
  },
  {
    id: 'red-mantis-assassin-mantis-form',
    name: 'Mantis Form',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain the mantis form focus spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Red Mantis Magic'],
    mechanics: 'Grants mantis form focus spell + focus pool.',
  },
  {
    id: 'red-mantis-assassin-fading',
    name: 'Fading',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You partially fade from reality. The attacker must attempt a DC 11 flat check; on a failure, the attack passes harmlessly through the image of your body. An instant later you return to reality, and your Crimson Shroud ends.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Teleportation'],
    actionCost: 'reaction',
    prerequisites: ['Crimson Shroud'],
    mechanics: 'Frequency: once per Crimson Shroud. Trigger: targeted with a Strike by someone you can detect. Requires active Crimson Shroud. DC 11 flat check or attack misses. Crimson Shroud ends afterward.',
  },
  {
    id: 'red-mantis-assassin-expert-magic',
    name: 'Expert Red Mantis Magic',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You gain the expert spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Master in Religion', 'Basic Red Mantis Magic'],
    mechanics: 'Expert spellcasting benefits.',
  },
  {
    id: 'red-mantis-assassin-vernai-training',
    name: 'Vernai Training',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'To resurrect a creature you\'ve slain, a spellcaster must counteract your influence on its death; the DC is your class DC or spell DC, whichever is higher. You also gain +1 spell slot per rank (except your two highest Red Mantis spell slots), restricted to Red Mantis magic school spells.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Achaekek\'s Grip', 'Basic Red Mantis Magic'],
    mechanics: 'Resurrection of your kills requires counteract check vs your DC. +1 spell slot per rank (except 2 highest), restricted to Red Mantis school.',
  },
  {
    id: 'red-mantis-assassin-prayer-attack',
    name: 'Prayer Attack',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Attempt to Feint an enemy within 30 feet. If successful, when you use Prayer Attack on subsequent turns you automatically make the target off-guard against your melee attacks without rolling, so long as you remain visible and within 30 feet. If you target a different creature, you must Feint normally. Your next successful sawtooth saber Strike that turn deals 2d6 persistent bleed damage.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Red Mantis Assassin Dedication'],
    mechanics: 'Requires wielding a sawtooth saber in each hand. 30-ft Feint; once successful, auto-Feint on subsequent turns vs same target. Next sawtooth saber Strike deals 2d6 persistent bleed.',
  },
  {
    id: 'red-mantis-assassin-master-magic',
    name: 'Master Red Mantis Magic',
    source: 'Red Mantis Assassin (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You gain the master spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Religion', 'Basic Red Mantis Magic'],
    mechanics: 'Master spellcasting benefits.',
  },
];

// ══════════════════════════════════════════════════════════
// CATALOG — Non-Core Archetype Feats L–R
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_LR: FeatEntry[] = [
  ...LION_BLADE_FEATS,
  ...MUNITIONS_MASTER_FEATS,
  ...PALATINE_DETECTIVE_FEATS,
  ...PROPHET_OF_KALISTRADE_FEATS,
  ...RED_MANTIS_ASSASSIN_FEATS,
];
