import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — I through V
// Iridian Choirmaster, Seneschal, Venture-Gossip, Vindicator
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// IRIDIAN CHOIRMASTER  (Battlecry! pg. 62–63)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=328
// Features a bonded "student" partner for coordinated combat.
// ──────────────────────────────────────────────────────────

export const IRIDIAN_CHOIRMASTER_FEATS: FeatEntry[] = [
  {
    id: 'iridian-choirmaster-dedication',
    name: 'Iridian Choirmaster Dedication',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'When you take this dedication, choose one willing, non-minion ally to be your student. You teach your student the necessary mindset and techniques; they gain the benefits of your abilities without having to take any feats of their own. You gain the benefits of your Iridian Choirmaster archetype feats only if both you and your student are alive and conscious. You and your student can trade nonverbal messages as a single action, which have the effects of the message spell but are non-magical. This requires a single action, has the concentrate, mental, and linguistic traits, and requires that you be able to see each other. If your student dies or you part ways, you can choose a new student by spending 1 week of downtime.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Occultism'],
    mechanics: 'Choose a willing non-minion ally as student. Archetype benefits require both alive/conscious. Non-magical message-like communication (1 action, visual range). Student replacement: 1 week downtime. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'iridian-choirmaster-lesson-of-the-broken-wing',
    name: 'Lesson of the Broken Wing',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You make yourself appear to be a tempting target to draw an enemy in, distracting them from your student\'s attacks. Choose an enemy creature within 60 feet that you are aware of. You take a –1 penalty to your AC against that creature\'s Strikes until the beginning of your next turn, and your student gains a +1 circumstance bonus to their Strikes against the target creature during that time.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Self-debuff: –1 AC vs one enemy within 60 ft until start of next turn. Student gains +1 circumstance to Strikes vs that enemy.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-the-circling-gale',
    name: 'Lesson of the Circling Gale',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You and your student have trained with footwork drills to mirror each other\'s movements. You Step, and your student can immediately Step as a reaction.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'You Step (1 action); student gets free Step as reaction. Upgraded by Lesson of the Hurricane\'s Might at level 14.',
  },
  {
    id: 'iridian-choirmaster-ensnaring-disarm',
    name: 'Ensnaring Disarm',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You smack your foe\'s item out of their hand so that your student can grab it. Instead of the item falling to the ground in the target\'s space, you aim your blow to send the disarmed item flying, allowing your student to immediately catch it as a free action; they must have a free hand to do so.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Trigger: Your last action was a critical success to Disarm. Requires student within 15 feet with a free hand. Disarmed item goes to student instead of dropping.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-bonded-eyes',
    name: 'Lesson of Bonded Eyes',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You and your student share an understanding of your surroundings. As long as you and your student can see (giving this effect the visual trait) or hear (giving this effect the auditory trait) each other, if a hidden creature is observed by either of you, it\'s observed by both of you.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Passive shared perception — hidden creatures observed by one partner are observed by both (requires visual or auditory contact between partners).',
  },
  {
    id: 'iridian-choirmaster-repeat-lesson',
    name: 'Repeat Lesson',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You immediately attempt the same action that your student failed against the same target. You must meet the action\'s requirements.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Trigger: Student fails or critically fails Athletics check to Disarm, Grapple, Reposition, Shove, or Trip. You attempt the same combat maneuver as a reaction.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-mutual-gambits',
    name: 'Lesson of Mutual Gambits',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You create an opening for your student, setting them up for their own attack. The creature you Feinted is off-guard to the first Strike or spell attack roll your student makes against it before the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Requires last action was a successful Feint. Extends off-guard from Feint to student\'s next attack (Strike or spell attack) vs the Feinted target until end of your next turn.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-sympathetic-vulnerability',
    name: 'Lesson of Sympathetic Vulnerability',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You temporarily borrow the essence of your student\'s attack to infuse yourself. Until the end of your current turn, damage you deal to enemies from Strikes and spells is the same type that triggered the creature\'s weakness instead of its usual type.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Trigger: Student triggered a creature\'s energy weakness with a Strike/spell on their previous turn. Convert all your Strike/spell damage to that energy type for the rest of your turn.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-the-splintered-aegis',
    name: 'Lesson of the Splintered Aegis',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'With your attack, you demonstrate to your student a hole in your enemy\'s defenses. Before the beginning of your next turn, your student can roll their next Strike or spell attack roll against that same enemy twice and take the better result.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Fortune'],
    actionCost: 1,
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Requires last action was a Strike that dealt damage. Student gets fortune on their next attack vs same enemy (roll twice, take better).',
  },
  {
    id: 'iridian-choirmaster-seize-advantage',
    name: 'Seize Advantage',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You take the openings granted by your student\'s success to reposition yourself. You Step or Stride up to your Speed.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Trigger: Student critically succeeds at a Strike or spell attack roll. Free Step or Stride as a reaction.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-unified-elusion',
    name: 'Lesson of Unified Elusion',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You and your student react as one to common threats. When you and your student are both targeted by the same effect that requires a Reflex saving throw, you and your student take the better of each of your die rolls for the save. You each still add your own Reflex save modifier to the die result.',
    implemented: 'full',
    traits: ['Archetype', 'Fortune'],
    actionCost: 'passive',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Passive fortune: share best Reflex die roll when both targeted by same AoE. Each applies own modifier separately.',
  },
  {
    id: 'iridian-choirmaster-pupils-guard',
    name: 'Pupil\'s Guard',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'re intimately familiar with your student\'s abilities and are always prepared to cover for them at a moment\'s notice should anything threaten to disrupt them. You interpose yourself between the attack and your student, becoming the target of the reaction and taking all damage and associated effects yourself. This allows your student to complete their action without interruption.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Trigger: Student would be targeted with a reaction (e.g. Reactive Strike) due to Stride or manipulate action. Requires adjacency to student. Redirect enemy reaction to yourself.',
  },
  {
    id: 'iridian-choirmaster-lesson-of-the-hurricanes-might',
    name: 'Lesson of the Hurricane\'s Might',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You and your student enact a graceful dance of battle. When you use Lesson of the Circling Gale, you can Strike as a free action after you Step. Your multiple attack penalty applies to this Strike as normal. Your student can Strike after they Step as part of their reaction. This Strike doesn\'t count toward your student\'s multiple attack penalty, and their multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lesson of the Circling Gale'],
    mechanics: 'Upgrades Circling Gale: you get a free Strike (MAP applies) after your Step. Student gets a free Strike (no MAP impact either way) after their reaction Step.',
  },
  {
    id: 'iridian-choirmaster-simultaneous-strike',
    name: 'Simultaneous Strike',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Moving in unison, you and your student unleash an attack against a foe. Strike a creature, and your student can use their reaction to make a Strike against the same creature. If both attacks are successful, total the damage for the two attacks for the purpose of resistances and weaknesses.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Coordinated double-strike: your 1 action + student\'s reaction. If both hit, combine damage for resistances/weaknesses calculation.',
  },
  {
    id: 'iridian-choirmaster-shared-mind-shared-heart',
    name: 'Shared Mind, Shared Heart',
    source: 'Iridian Choirmaster (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Your thoughts and dreams are your student\'s thoughts and dreams, and vice versa. You develop a permanent mental connection, allowing you to communicate telepathically as long as you\'re on the same plane. When one of you fails a save against a mental effect, the other can choose to take the results of the failed save instead. If both of you are targeted by the same mental effect requiring a saving throw, you and your student take the better of each of your die rolls for the save. You each still add your own save modifier to the die result. This is a fortune effect.',
    implemented: 'full',
    traits: ['Archetype', 'Mental'],
    actionCost: 'passive',
    prerequisites: ['Iridian Choirmaster Dedication'],
    mechanics: 'Permanent telepathy (same-plane). Either partner can absorb the other\'s mental effect failures. Fortune on Will saves vs same mental effect (share best die roll, own modifiers).',
  },
];

// ──────────────────────────────────────────────────────────
// SENESCHAL  (War of Immortals pg. 62–63)
// Category: Class Archetype (Witch) — Rare
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=281
// Must be a Seneschal Witch (patron has gone silent).
// ──────────────────────────────────────────────────────────

export const SENESCHAL_FEATS: FeatEntry[] = [
  {
    id: 'seneschal-witch-dedication',
    name: 'Seneschal Witch Dedication',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'As you work to understand the connection with your missing patron, it\'s increasingly easy to form bonds with those around you. Raw magical energy spills easily through the connection but, without a patron\'s control, it sometimes resists your demands for it to form proper spells. You gain the Witch\'s Charge feat, but can\'t choose your familiar or another creature with the minion trait as a charge. When you cast or Sustain manifest will, as long as your charge is within 30 feet, you can choose to center the spell\'s emanation on your charge instead of yourself.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Seneschal Witch'],
    mechanics: 'Grants Witch\'s Charge (no familiar/minion charges allowed). Can redirect manifest will emanation to charge within 30 ft. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'seneschal-patrons-glamour',
    name: 'Patron\'s Glamour',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Gathering up threads of your old connection, you can temporarily disguise yourself as your missing patron. You gain illusory disguise as an innate spell of your patron\'s tradition, automatically heightened to the rank of your witch cantrips, but you can use it only to disguise yourself as the humanoid representation of your patron. Detection spells of lower rank than this illusory disguise give your patron\'s information rather than your own.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Illusion'],
    actionCost: 'passive',
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Innate illusory disguise (patron\'s tradition, auto-heightened to cantrip rank) — patron appearance only. Lower-rank detection returns patron info instead of yours.',
  },
  {
    id: 'seneschal-seneschal-spell',
    name: 'Seneschal Spell',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can channel even complex spells through your connection to your charge. If your next action is to Cast a Spell and your charge is within 30 feet, you can have the spell originate from your charge instead. That creature can use their reaction to roughly complete the spell\'s incantation, which gives the spell the subtle trait for you (but not for them) as the manifestation appears solely around your charge.',
    implemented: 'full',
    traits: ['Archetype', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Frequency: once per hour. Spellshape — redirect next spell\'s origin to charge within 30 ft. Charge can use reaction to make it subtle for you.',
  },
  {
    id: 'seneschal-multifaceted-will',
    name: 'Multifaceted Will',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Without the firm hand of a patron, your power begins to reflect deeper complexities, sometimes latching onto entirely unexpected sources of magical potency. When you cast or Sustain manifest will, you can choose any tradition\'s manifestation. While the spell is active, you and allies in its area gain a +1 status bonus to saves against spells with that tradition trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Can select any tradition for manifest will. +1 status bonus to saves vs spells of the chosen tradition for you and allies in the emanation.',
  },
  {
    id: 'seneschal-spiritual-secret',
    name: 'Spiritual Secret',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You gain deeper insights into your patron\'s abandoned power, allowing you to draw on that power more directly. If your next action is to cast a witch cantrip or witch spell that deals damage, it deals spirit damage instead of its normal type. It also loses any traits related to its damage, such as the fire or mental trait, and gains the sanctified and spirit traits instead.',
    implemented: 'full',
    traits: ['Archetype', 'Spellshape'],
    actionCost: 'free',
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Frequency: once per hour. Spellshape — convert next damaging witch spell to spirit damage, gaining sanctified and spirit traits. Loses original damage-type traits.',
  },
  {
    id: 'seneschal-watcher-on-the-wall',
    name: 'Watcher on the Wall',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You claim a patron\'s symbol that you can etch onto any surface. Etch a symbol onto an adjacent surface; you can see and hear what you could from the symbol\'s location as long as you are on the same plane. This effect lasts until you place another symbol or the surface is destroyed.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Remote scrying sensor — etch symbol on adjacent surface, gain persistent visual/auditory perception from that location (same plane). Only one active symbol at a time.',
  },
  {
    id: 'seneschal-patrons-whisper',
    name: 'Patron\'s Whisper',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You gain the ability to speak to your charge over great distances. You gain message as an innate cantrip of your former patron\'s tradition. You can send a message to a creature regardless of range if they have ever been your charge. If you Lie as part of the message, the target receives a –2 circumstance penalty to their Perception DC and to Sense Motive checks to reveal the lie.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory'],
    actionCost: 'passive',
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Innate message cantrip (unlimited range to former/current charges). Lies via this cantrip harder to detect (–2 penalty for target).',
  },
  {
    id: 'seneschal-unstable-patronage',
    name: 'Unstable Patronage',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You can act as a magical patron for your charges. When you finish your daily preparations, choose a spell your familiar knows and one of your charges. Once before your next daily preparations, that creature can Cast the Spell as an innate spell; this spell can be of no higher a rank than the highest rank of spells you can cast –2.',
    implemented: 'full',
    traits: ['Archetype', 'Spellshape'],
    actionCost: 'passive',
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'During daily prep: grant one charge a single-use innate spell from familiar\'s known spells (max rank = your max spell rank –2).',
  },
  {
    id: 'seneschal-patron-reborn',
    name: 'Patron Reborn',
    source: 'Seneschal (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You have fully realized the ability to serve as a patron. Your newfound abilities enhance your senses, rolling back the veil of a realm hidden to most mortals where great beings vie for unimaginable influence over vast worlds. You gain darkvision, constant truesight, and the ability to see into all other transitive planes that overlap the one you are in. You can be a patron for other witches. Choose a single type of patron you represent. An allied witch you can observe who has that patron counts as and gains the benefits of your Witch\'s Charge feat. You learn the wish ritual and can impart that knowledge to your charges. Once per month, when one of your charges performs the wish ritual, you can roll the skill check in their place.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Seneschal Witch Dedication'],
    mechanics: 'Darkvision + constant truesight + transitive plane sight. Become patron for allied witches of your chosen patron type (auto-charge). Access to wish ritual; can roll for charges once/month.',
  },
];

// ──────────────────────────────────────────────────────────
// VENTURE-GOSSIP  (Foolish Housekeeping and Other Articles)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=326
// Requires Pathfinder Agent Dedication.
// ──────────────────────────────────────────────────────────

export const VENTURE_GOSSIP_FEATS: FeatEntry[] = [
  {
    id: 'venture-gossip-dedication',
    name: 'Venture-Gossip Dedication',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You have two identities: your day job as a Pathfinder agent, and your real job as one of the many voices of the Venture-Gossip tabloid. If someone attempts to figure out if you\'re a venture-gossip, they must use a Seek action to attempt a Perception check against one of your influence skills of your choice: Deception, Diplomacy, or Intimidation (DC = 20 + your proficiency modifier). You gain Tell Me More: spend 2 actions (fortune) to roll twice on all social influence checks against a target that shares your language while not in combat.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication', 'Member of the Pathfinder Society'],
    mechanics: 'Dual identity (Pathfinder / tabloid gossip). Hidden identity seekable at DC 20 + proficiency. Tell Me More [two-actions, fortune]: roll twice on social influence vs target (out of combat, shared language). Special: can select even without 3 Pathfinder Agent feats. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'venture-gossip-verbose-distraction',
    name: 'Verbose Distraction',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You talk so much it can be distracting to your enemies and you\'re often quick to remind your enemies that you\'re just a little guy! You gain a +2 circumstance bonus to your AC against the triggering attack.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory'],
    actionCost: 'reaction',
    prerequisites: ['Venture-Gossip Dedication'],
    mechanics: 'Trigger: You are the target of a physical melee attack. +2 circumstance bonus to AC against the triggering attack.',
  },
  {
    id: 'venture-gossip-hey-over-here',
    name: 'Hey! Over Here!',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You distract an ally from a harmful auditory effect with your incessant chatter. Your targeted ally treats the result of their saving throw as one degree of success better. Once an ally has been targeted by this effect, they\'re immune for 24 hours.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory'],
    actionCost: 'reaction',
    prerequisites: ['Venture-Gossip Dedication'],
    mechanics: 'Trigger: An ally within 30 feet rolls a saving throw against an auditory effect. Ally improves save result by one degree. Target immune 24 hours after use.',
  },
  {
    id: 'venture-gossip-a-little-bird-told-me',
    name: 'A Little Bird Told Me...',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You transform into a small bird, such as a finch or a sparrow, allowing you to eavesdrop on others. You become Tiny, gain the animal trait, and you can\'t make Strikes. You can Dismiss the effect. You gain: AC = 20 + your level (ignore armor check penalty and Speed reduction), Fly speed 25 feet, Weakness 5 to physical damage, Low-light vision and imprecise scent 30 feet, Acrobatics and Stealth modifiers of +10 (unless yours is higher), Athletics modifier –4.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Manipulate', 'Polymorph'],
    actionCost: 'passive',
    prerequisites: ['Venture-Gossip Dedication'],
    mechanics: 'Polymorph into Tiny bird for infiltration. No Strikes. AC = 20 + level, Fly 25 ft, Weakness 5 physical, low-light vision, imprecise scent 30 ft, Acrobatics/Stealth +10 (or yours if higher), Athletics –4. Dismissible.',
  },
  {
    id: 'venture-gossip-define-report',
    name: 'Define "Report"',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Getting caught in a lie is a normal part of venture-gossip life. When you fail a Deception check, reroll with your Diplomacy modifier. On a success, there are no hard feelings and the other person\'s attitude condition doesn\'t worsen. On a critical success, you can attempt the Deception again with no consequences.',
    implemented: 'full',
    traits: ['Archetype', 'Fortune'],
    actionCost: 'free',
    prerequisites: ['Venture-Gossip Dedication', 'Master in Diplomacy'],
    mechanics: 'Fortune — reroll failed Deception using Diplomacy modifier. Success: attitude doesn\'t worsen. Crit success: retry Deception with no consequences.',
  },
  {
    id: 'venture-gossip-catch-and-kill',
    name: 'Catch and Kill',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When you\'ve decided to quash a story, no one can escape from you with any incriminating information. Make a melee Strike against the triggering creature. On a hit, the triggering creature is grabbed, and on a critical hit, they\'re slowed 1. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Venture-Gossip Dedication'],
    mechanics: 'Trigger: A creature within reach uses a move action or leaves a square during a move action. Melee Strike (no MAP interaction). Hit = grabbed, crit = also slowed 1.',
  },
  {
    id: 'venture-gossip-muckraking',
    name: 'Muckraking',
    source: 'Venture-Gossip (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Pulling out your fan mail, you read your fans\' scathing remarks about your enemy to their face, letting them feel just how much everyone hates them and everything that they\'ve done. Your enemy takes 10d10 mental damage, with a basic Will save. On a critical failure, they\'re off-guard until the beginning of your next turn and lose all reactions.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Concentrate', 'Emotion', 'Mental'],
    actionCost: 3,
    prerequisites: ['Venture-Gossip Dedication'],
    mechanics: '10d10 mental damage (basic Will save). Crit fail: off-guard + lose all reactions until start of your next turn.',
  },
];

// ──────────────────────────────────────────────────────────
// VINDICATOR  (War of Immortals pg. 64–65)
// Category: Class Archetype (Ranger) — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=283
// Must be a Ranger with the Vindicator hunter's edge.
// ──────────────────────────────────────────────────────────

export const VINDICATOR_FEATS: FeatEntry[] = [
  {
    id: 'vindicator-dedication',
    name: 'Vindicator Dedication',
    source: 'Vindicator (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your church ensures that you are cared for. You can use Religion to Coerce, and if the target of the check is also a worshipper of your deity or is your hunted prey, you gain a +2 circumstance bonus to the check.',
    implemented: 'full',
    traits: ['Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Vindicator (hunter\'s edge)'],
    mechanics: 'Religion replaces Intimidation for Coerce. +2 circumstance bonus if target shares your faith or is hunted prey. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'vindicator-interrogate',
    name: 'Interrogate',
    source: 'Vindicator (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You ask questions you know will be answered. Ask a question of a non-allied creature that you can see and have been conversing with. Attempt an Intimidation check against the creature\'s Will DC; if the creature is a member of the same religion as you, or is an undead or werecreature pretending to be a member of your faith, you get a +2 circumstance bonus. Critical Success: target must answer; +4 to detect lies. Success: target must answer; +2 to detect lies. Failure: target can refuse, becomes unfriendly. Critical Failure: target refuses, becomes hostile; can\'t retry for 24 hours.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Concentrate', 'Linguistic', 'Mental'],
    actionCost: 1,
    prerequisites: ['Vindicator Dedication'],
    mechanics: 'Intimidation vs Will DC (+2 vs co-religionists/disguised undead/werecreatures). Forces answers on success; bonus to detect lies depends on degree. Target temp immune 1 hour.',
  },
  {
    id: 'vindicator-silence-the-profane',
    name: 'Silence the Profane (Vindicator)',
    source: 'Vindicator (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your training included instruction on how to prevent enemy spellcasters from using their magic against you. Make a Strike with your deity\'s favored weapon against the triggering creature. On a success, the target is off-guard until the end of your next turn. The triggering spell is disrupted on a critical success, or on a success if the target is your hunted prey and the spell is a divine spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Vindicator Dedication'],
    mechanics: 'Trigger: A creature you can observe within reach of your deity\'s favored weapon casts a spell. Requires wielding deity\'s favored weapon. Hit = off-guard; crit = disrupts spell. Against hunted prey casting divine: regular hit disrupts. Ranged variant for ranged favored weapons (first range increment). PFS: Limited.',
  },
  {
    id: 'vindicator-vindicators-judgement',
    name: 'Vindicator\'s Judgement',
    source: 'Vindicator (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You can pronounce judgment on your foes, making them magically susceptible to your attacks. You gain the vindicator\'s judgment focus spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vindicator Dedication', 'Warden Spells'],
    mechanics: 'Grants vindicator\'s judgment focus spell (divine warden spell).',
  },
  {
    id: 'vindicator-call-the-hunt',
    name: 'Call the Hunt',
    source: 'Vindicator (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You instruct your allies on how best to defeat your prey. Until the start of your next turn, whenever your hunted prey is within reach of you and at least one of your allies, it is off-guard to all melee attacks. If you are sanctified, the unarmed attacks and weapon Strikes of you and all your allies gain the benefits of your sanctification against your hunted prey.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Vindicator Dedication'],
    mechanics: 'Requires observing hunted prey. Prey off-guard to all melee when in reach of you + ally until start of your next turn. If sanctified, extends holy/unholy to all ally attacks vs prey.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG  (all non-core I–V archetypes)
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_IV: FeatEntry[] = [
  ...IRIDIAN_CHOIRMASTER_FEATS,
  ...SENESCHAL_FEATS,
  ...VENTURE_GOSSIP_FEATS,
  ...VINDICATOR_FEATS,
];
