import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Lost Omens: Halcyon Speaker,
// Crystal Keeper, Zephyr Guard, Turpin Rowe Lumberjack
// Character Guide / Claws of the Tyrant / Pathfinder AP #148–153
// ══════════════════════════════════════════════════════════

// ─── HALCYON SPEAKER ─────────────────────────────────────
export const HALCYON_SPEAKER_FEATS: FeatEntry[] = [
  {
    id: 'halcyon-speaker-dedication',
    name: 'Halcyon Speaker Dedication',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You devote much of your study to halcyon magic. You gain two common Halcyon cantrips and two common 1st-level halcyon spells. In addition to being able to cast your halcyon spells via your arcane or primal spell slots, you also gain a 1st-level halcyon spell slot. You can use your halcyon spell slots to spontaneously cast your halcyon spells.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication', 'member of the Magaambya of conversant rank'],
    mechanics: 'Uncommon. Gain 2 halcyon cantrips + 2 common 1st-level halcyon spells + 1st-level halcyon spell slot. Cast halcyon spells spontaneously from halcyon slots.',
  },
  {
    id: 'dualistic-synergy',
    name: 'Dualistic Synergy',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'If your next action is to Cast a Spell from your spell slots, you gain a benefit. If the spell is arcane, you can attempt a skill check to Recall Knowledge with a +1 status bonus to the check after casting the spell, or a +2 status bonus if the spell is 7th level or higher. If the spell is primal, you gain a number of temporary Hit Points equal to the spell\'s level for 1 round. If the spell is a halcyon spell, you gain both benefits.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 1,
    prerequisites: ['Halcyon Speaker Dedication'],
    mechanics: 'Metamagic. Next Cast a Spell: arcane → Recall Knowledge +1 status (+2 if 7th+); primal → temp HP = spell rank for 1 rd; halcyon → both.',
  },
  {
    id: 'persistent-creation',
    name: 'Persistent Creation',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can cast creation as an innate spell at will, choosing whether it is arcane or primal each time. The created object lasts until you spend 1 hour not within its immediate vicinity or until it is destroyed. Such objects are called persistent creations. If you cast creation again, any persistent creation you previously created with the spell immediately disintegrates.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Speaker Dedication'],
    mechanics: 'Cast creation innate at will (arcane or primal). Object lasts until 1 hr away or destroyed. New casting disintegrates old.',
  },
  {
    id: 'halcyon-spellcasting-initiate',
    name: 'Halcyon Spellcasting Initiate',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your knowledge of halcyon magic increases. You gain two common 2nd-level halcyon spells and two 3rd-level halcyon spells. You also gain a 2nd-level halcyon spell slot and a 3rd-level halcyon spell slot. These and all future halcyon spell slots work like the 1st-level halcyon spell slot you gained from Halcyon Speaker Dedication.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Speaker Dedication'],
    mechanics: 'Gain 2 common 2nd-level + 2 common 3rd-level halcyon spells. Gain 2nd + 3rd halcyon spell slots.',
  },
  {
    id: 'shared-synergy',
    name: 'Shared Synergy',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You can grant the benefit from Dualistic Synergy to an ally within 30 feet instead of yourself, either allowing that ally to Recall Knowledge, granting that ally temporary Hit Points, or both, depending on the spell\'s tradition.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dualistic Synergy'],
    mechanics: 'Grant Dualistic Synergy benefit to ally within 30 ft instead of self.',
  },
  {
    id: 'charged-creation',
    name: 'Charged Creation',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your magic is drawn to your persistent creations. While you are within 30 feet of and have line of effect to your persistent creation, you can use it as the origin point for your line or cone spells. For instance, a lightning bolt could originate from the persistent creation rather than from you.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Persistent Creation'],
    mechanics: 'Within 30 ft of persistent creation: use it as origin for line/cone spells.',
  },
  {
    id: 'flexible-halcyon-spellcasting',
    name: 'Flexible Halcyon Spellcasting',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You broaden your ability to channel your power into halcyon magic. You gain one more common halcyon spell of each level of halcyon spell you can cast other than your highest (you do not gain an additional cantrip). You also gain one additional halcyon spell slot for each level of halcyon spell you can cast, other than the highest.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Spellcasting Initiate'],
    mechanics: 'Gain 1 more halcyon spell per level (except highest, no cantrip). Gain 1 more halcyon slot per level (except highest).',
  },
  {
    id: 'halcyon-spellcasting-adept',
    name: 'Halcyon Spellcasting Adept',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You refine your halcyon magic. You gain two common 4th-level halcyon spells and two 5th-level halcyon spells. You also gain a 4th-level halcyon spell slot and a 5th-level halcyon spell slot. Your proficiency rank in either arcane or primal spell DCs and spell attack rolls advances from trained to expert.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Spellcasting Initiate', 'master in either Arcana or Nature, expert in the other'],
    mechanics: 'Gain 2 common 4th + 2 common 5th halcyon spells. Gain 4th + 5th halcyon slots. Advance arcane or primal spell prof to expert.',
  },
  {
    id: 'shattered-sacrament',
    name: 'Shattered Sacrament',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When Vigil fell to Tar-Baphon\'s Radiant Fire, that lost innocence brought you a deeper understanding of what faith means in the context of your own magic. When you cast a halcyon spell, you can choose for it to be a divine spell instead of arcane or primal. You gain a halcyon cantrip and a 1st-rank halcyon spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Speaker Dedication', 'Cascade Bearer\'s Spellcasting'],
    mechanics: 'Halcyon spells can be divine instead of arcane/primal. Gain 1 halcyon cantrip + 1 1st-rank halcyon spell.',
  },
  {
    id: 'speak-for-the-gravelands',
    name: 'Speak for the Gravelands',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You have heard the cries of the lands scarred by Tar-Baphon and gained the ability to speak for them. You gain the Geomancer Dedication archetype feat, even if you normally couldn\'t take another dedication feat until you take more feats from your current archetype. You can benefit from the Gravelands terrain attunement when in the Gravelands, gaining a +1 status bonus to saving throws against the spells and abilities of haunts and undead creatures for 1 round.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Speaker Dedication', 'trained in Nature', 'can cast at least one spell with the vitality trait'],
    mechanics: 'Uncommon. Gain Geomancer Dedication (bypass dedication lock). Gravelands attunement: +1 status to saves vs haunts/undead for 1 rd.',
  },
  {
    id: 'fulminating-synergy',
    name: 'Fulminating Synergy',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'When you draw upon your spells\' synergy, you create a physical manifestation of their magical resonance and invoke it to harm a foe. When you use Dualistic Synergy, choose a damage type: acid, cold, electricity, or fire. In addition to Dualistic Synergy\'s normal effect, a foe within 30 feet of you takes an amount of damage of the chosen type equal to the spell\'s level. If the spell already deals damage of the chosen type, combine the damage before applying weaknesses and resistances.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dualistic Synergy'],
    mechanics: 'On Dualistic Synergy: choose acid/cold/electricity/fire. 1 foe within 30 ft takes spell-rank damage of that type.',
    subChoices: { label: 'Choose damage type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
    ] },
  },
  {
    id: 'vellumis-excision',
    name: 'Vellumis Excision',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You seek to excise the rot from the Gravelands and have made progress to do so. You can cast field of life as a 6th-rank halcyon spell, and you gain a 6th-rank halcyon spell slot. When you cast your halcyon field of life as a primal spell, any living creatures in the area when you Sustain the spell gain a +2 status bonus to saving throws against curses, diseases, and poisons for 1 round.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Spellcasting Adept'],
    mechanics: 'Uncommon. Cast field of life as 6th-rank halcyon. Gain 6th-rank halcyon slot. As primal: living creatures +2 status to saves vs curses/diseases/poisons for 1 rd on Sustain.',
  },
  {
    id: 'halcyon-spellcasting-sage',
    name: 'Halcyon Spellcasting Sage',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your command over halcyon magic is nearly unmatched. You gain two common 6th-level and 7th-level halcyon spells. You also gain a 6th-level halcyon spell slot and a 7th-level halcyon spell slot. Your proficiency rank in either arcane or primal spell DCs and spell attack rolls advances from expert to master.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Halcyon Spellcasting Adept', 'legendary in either Arcana or Nature, master in the other'],
    mechanics: 'Gain 2 common 6th + 2 common 7th halcyon spells. Gain 6th + 7th halcyon slots. Advance spell prof to master.',
  },
  {
    id: 'tripartite-omen',
    name: 'Tripartite Omen',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You invoke religious portents to ward yourself against danger without losing sight of the history that led to this point. When you use Dualistic Synergy, if your next action is to Cast a Spell from your spell slots and that spell is divine, you gain a +1 status bonus to AC for 1 round. If the spell is a halcyon spell, you gain this benefit in addition to the benefits described in Dualistic Synergy.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dualistic Synergy', 'Shattered Sacrament', 'master in Religion'],
    mechanics: 'On Dualistic Synergy: divine spell → +1 status AC for 1 rd. Halcyon spell → this + normal Dualistic Synergy benefits.',
  },
  {
    id: 'synergistic-spell',
    name: 'Synergistic Spell',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You can combine the power of two spells to cast two spells at once. If the next action you use is to Cast a Spell from one of your halcyon spell slots, after that spell resolves, you can Cast another Spell as a free action. This spell must be cast from one of your halcyon spell slots and be a spell that would normally take two actions to cast.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 1,
    prerequisites: ['Halcyon Spellcasting Initiate', 'Fulminating Synergy', 'legendary in Arcana and Nature'],
    mechanics: 'Metamagic. After casting halcyon spell, Cast another Spell free action from halcyon slot (must be 2-action spell).',
  },
  {
    id: 'vigils-palisades',
    name: 'Vigil\'s Palisades',
    source: 'Halcyon Speaker (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'When you use Persistent Creation, you can create up to three special wooden shields that provide a +2 circumstance bonus to AC and have Hardness 15, 120 HP, and BT 60. A creature that Raises a Shield with one of these shields also gains resistance 5 to void damage while the shield is raised.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Persistent Creation'],
    mechanics: 'Persistent Creation: up to 3 shields (+2 AC, Hardness 15, 120 HP, BT 60). Raise Shield → resistance 5 void.',
  },
];

// ─── CRYSTAL KEEPER ──────────────────────────────────────
export const CRYSTAL_KEEPER_FEATS: FeatEntry[] = [
  {
    id: 'crystal-keeper-dedication',
    name: 'Crystal Keeper Dedication',
    source: 'Crystal Keeper (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can use Arcana, Occultism, Religion, or Society to Decipher Writing and roll a critical failure, you get a failure instead, and when you Decipher Writing and roll a success, you get a critical success instead (while meditating before a crystal). Additionally, you gain resistance 10 to damage from hazards associated with crystals.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['trained in Society or Elven Lore'],
    mechanics: 'Rare. Decipher Writing (w/ crystal): crit fail → fail, success → crit success. Resistance 10 crystal hazard damage.',
  },
  {
    id: 'crystal-ward-spells',
    name: 'Crystal Ward Spells',
    source: 'Crystal Keeper (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your study of crystals and the energies held within a gem\'s facets grants you special arcane crystal ward spells, which are a type of focus spell. It costs 1 Focus Point to cast a focus spell, and you start with a focus pool of 1 Focus Point. You refill your focus pool when you make your next daily preparations, and you can regain 1 Focus Point by spending 10 minutes using the Refocus activity to research and memorize the properties of gems. Focus spells are automatically heightened to half your level rounded up. Certain feats can give you more focus spells and increase the size of your focus pool, though your focus pool can never hold more than 3 Focus Points. You gain the electrified crystal ward focus spell, and you are trained in arcane spell attack rolls and spell DCs. Your spellcasting ability is Intelligence.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crystal Keeper Dedication'],
    mechanics: 'Gain electrified crystal ward focus spell. Focus pool 1 FP. Trained arcane spell attacks/DCs (Int). Refocus: 10 min studying gems.',
  },
  {
    id: 'simple-crystal-magic',
    name: 'Simple Crystal Magic',
    source: 'Crystal Keeper (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'As long as you meditate before a gemstone worth at least 10 gp as part of your daily preparations, you are capable of seeing magic as flowing runes that reveal information about magic objects, and you can scribe a personal rune that represents you. You gain the read aura and sigil cantrips. You cast these cantrips as arcane innate spells at will. A cantrip is heightened to a spell rank equal to half your level rounded up.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crystal Keeper Dedication'],
    mechanics: 'Meditate before gem (10+ gp): gain read aura and sigil cantrips as arcane innate at will.',
  },
  {
    id: 'armor-rune-shifter',
    name: 'Armor Rune Shifter',
    source: 'Crystal Keeper (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You learn the secrets of armor runes by viewing them through gems and can alter them at your discretion. Once per day when you make your daily preparations, you can focus on a rune\'s magical energies through a crystal\'s facets to alter a single property rune on one suit of armor in your possession to suppress its normal effects and make it function as a different property rune. You can temporarily alter the rune to function as one of the following runes: energy-resistant, fortification, glamered, invisibility, shadow, or slick. The property rune remains altered until you make your next daily preparations. The armor must meet the prerequisites for the temporary rune, and any other runes that required the suppressed rune are also suppressed while the rune is transformed. The rune is obviously altered, and thus the armor can\'t be sold as though it had the temporary rune.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crystal Keeper Dedication'],
    mechanics: '1/day at daily prep: swap 1 armor property rune to energy-resistant, fortification, glamered, invisibility, shadow, or slick until next prep.',
    subChoices: { label: 'Choose armor property rune', options: [
      { id: 'energy-resistant', name: 'Energy-Resistant', description: 'Resistance 5 to chosen energy type' },
      { id: 'fortification', name: 'Fortification', description: 'DC 17 flat check to resist critical hits' },
      { id: 'glamered', name: 'Glamered', description: 'Change armor appearance at will' },
      { id: 'invisibility', name: 'Invisibility', description: 'Cast invisibility once per day' },
      { id: 'shadow', name: 'Shadow', description: '+1 item bonus to Stealth' },
      { id: 'slick', name: 'Slick', description: '+1 item bonus to Acrobatics (Escape)' },
    ] },
  },
  {
    id: 'weapon-rune-shifter',
    name: 'Weapon-Rune Shifter',
    source: 'Crystal Keeper (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You learn how to alter the magic of weapon runes by using a crystal as a focusing component. Once per day during your daily preparations, you can focus on a rune\'s magical energies through a crystal\'s facets to alter a single property rune on one weapon in your possession to suppress its normal effects and make it function as a different property rune. You can temporarily alter the rune to function as one of the following runes: corrosive, flaming, frost, ghost touch, grievous, returning, shock, or thundering. The weapon must meet the prerequisites for the temporary rune, and any other runes that required the suppressed rune are also suppressed while the rune is transformed. The rune is obviously altered, and thus the weapon can\'t be sold as though it had the temporary rune.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crystal Keeper Dedication'],
    mechanics: '1/day at daily prep: swap 1 weapon property rune to corrosive, flaming, frost, ghost touch, grievous, returning, shock, or thundering until next prep.',
    subChoices: { label: 'Choose weapon property rune', options: [
      { id: 'corrosive', name: 'Corrosive', description: '+1d6 acid damage' },
      { id: 'flaming', name: 'Flaming', description: '+1d6 fire damage' },
      { id: 'frost', name: 'Frost', description: '+1d6 cold damage' },
      { id: 'ghost-touch', name: 'Ghost Touch', description: 'Full damage to incorporeal creatures' },
      { id: 'grievous', name: 'Grievous', description: 'Additional critical specialization effect' },
      { id: 'returning', name: 'Returning', description: 'Thrown weapon returns after attack' },
      { id: 'shock', name: 'Shock', description: '+1d6 electricity damage' },
      { id: 'thundering', name: 'Thundering', description: '+1d6 sonic damage' },
    ] },
  },
];

// ─── ZEPHYR GUARD ────────────────────────────────────────
export const ZEPHYR_GUARD_FEATS: FeatEntry[] = [
  {
    id: 'zephyr-guard-dedication',
    name: 'Zephyr Guard Dedication',
    source: 'Zephyr Guard (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'As a Zephyr Guard, you\'re always vigilant against crime and threats to the city\'s safety. You gain a +1 circumstance bonus to Perception checks against attempts to Palm an Object, Steal, or Conceal an Object (including when you\'re Seeking concealed objects). You become trained in Society and Katapesh Lore; if you were already trained, you become an expert instead.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'Uncommon. +1 circumstance to Perception vs Palm an Object, Steal, Conceal an Object. Trained Society + Katapesh Lore (or expert).',
  },
  {
    id: 'know-the-beat',
    name: 'Know the Beat',
    source: 'Zephyr Guard (Archetype)',
    category: 'archetype',
    level: 3,
    description: 'You become trained in your choice of Guild Lore, Legal Lore, Mercantile Lore, or Underworld Lore. You gain a +1 circumstance bonus to Diplomacy checks to Gather Information and to checks made to investigate crimes.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Zephyr Guard Dedication'],
    mechanics: 'Trained in Guild/Legal/Mercantile/Underworld Lore (choose 1). +1 circumstance to Gather Information + investigate crimes.',
    subChoices: { label: 'Choose Lore type', options: [
      { id: 'guild', name: 'Guild Lore' },
      { id: 'legal', name: 'Legal Lore' },
      { id: 'mercantile', name: 'Mercantile Lore' },
      { id: 'underworld', name: 'Underworld Lore' },
    ] },
  },
  {
    id: 'decry-thief',
    name: 'Decry Thief',
    source: 'Zephyr Guard (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you attempt to Demoralize, you can make it harder for the target to flee, in place of the action\'s normal effects. Critical Success: For 1 round, the target takes a -10-foot status penalty to Speed and a -4 status penalty to Stealth. Success: For 1 round, the target takes a -5-foot status penalty to Speed and a -2 status penalty to Stealth.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Zephyr Guard Dedication', 'trained in Intimidation'],
    mechanics: 'Demoralize alternative: Crit Success → -10 ft Speed, -4 Stealth 1 rd. Success → -5 ft Speed, -2 Stealth 1 rd.',
  },
  {
    id: 'relentless-disarm',
    name: 'Relentless Disarm',
    source: 'Zephyr Guard (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you succeed, but don\'t critically succeed, at a check to Disarm a creature, your circumstance bonus to further checks to Disarm that creature is +4 instead of +2. Other creatures gain only the normal bonus. When you critically succeed at a Disarm check, you can immediately Demoralize your target as a reaction.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Zephyr Guard Dedication', 'trained in Athletics'],
    mechanics: 'Disarm success (non-crit): +4 circumstance (instead of +2) to further Disarm. Crit success: free Demoralize as reaction.',
  },
  {
    id: 'unfazed-assessment',
    name: 'Unfazed Assessment',
    source: 'Zephyr Guard (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You have witnessed hundreds of fighting styles and quickly adapt to defend against complicated maneuvers. Choose a creature within 30 feet who you\'re aware of, and attempt a Perception check against that target\'s Will DC. If you succeed, you size up their fighting style, gaining a +1 circumstance bonus to AC and saving throws against that creature\'s attacks (or a +2 circumstance bonus for a critical success). These benefits last until the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Zephyr Guard Dedication', 'expert in Perception'],
    mechanics: '1 action. Perception vs target Will DC (30 ft): success → +1 AC/saves vs that creature; crit → +2. Until end of next turn.',
  },
];

// ─── TURPIN ROWE LUMBERJACK ──────────────────────────────
export const TURPIN_ROWE_LUMBERJACK_FEATS: FeatEntry[] = [
  {
    id: 'turpin-rowe-lumberjack-dedication',
    name: 'Turpin Rowe Lumberjack Dedication',
    source: 'Turpin Rowe Lumberjack (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your logging training has made you intimately familiar with all aspects of forestry, and you have trained extensively to reach around trees and utilize their bulk to your advantage. You become trained in Milling Lore and Forest Lore, or an expert if you were already trained. You can always Take Cover when you are within forest terrain to gain cover, even if you\'re not next to an obstacle you can Take Cover behind. In addition, any enemy who gains standard cover from a tree gains only lesser cover against your attacks (or only standard cover, if the enemy otherwise gains greater cover).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['trained in Survival'],
    mechanics: 'Uncommon. Trained Milling Lore + Forest Lore (or expert). Take Cover in forest terrain always. Enemy tree cover reduced by 1 step vs your attacks.',
  },
  {
    id: 'axe-climber',
    name: 'Axe Climber',
    source: 'Turpin Rowe Lumberjack (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you are climbing a wooden surface and have a hatchet or battle axe in each hand, you have a climb Speed equal to half your normal Speed. You must still have both legs available to climb and can\'t use either of the axes in combat while climbing. This feat can also be used to climb a surface of ice if you have a light pick in each hand.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Turpin Rowe Lumberjack Dedication'],
    mechanics: 'Climb wood with hatchet/battle axe in each hand: climb Speed = half Speed. Also works on ice with light pick in each hand.',
  },
  {
    id: 'log-roll',
    name: 'Log Roll',
    source: 'Turpin Rowe Lumberjack (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You shuffle your feet to dislodge the surface beneath you or otherwise cause your opponent to become unsteady. Attempt an Acrobatics check against the adjacent creature\'s Reflex saving throw DC. On a success, the creature falls. On a critical failure, you fall.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Turpin Rowe Lumberjack Dedication'],
    mechanics: '1 action. Req: both on narrow/uneven ground, target off-guard. Acrobatics vs Reflex DC: success → target falls; crit fail → you fall.',
  },
  {
    id: 'axe-thrower',
    name: 'Axe Thrower',
    source: 'Turpin Rowe Lumberjack (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have mastered the weight and balance of a variety of axes and can lob them with ease. Any one-handed axe weapon you wield has the thrown trait with a range of 10 feet. For axes that already have the thrown trait, the range increases by 10 feet. When you critically succeed at an attack roll with a thrown axe weapon, you apply the axe\'s critical specialization effect.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Turpin Rowe Lumberjack Dedication'],
    mechanics: 'All 1h axes gain thrown 10 ft (or +10 ft if already thrown). Crit with thrown axe: apply axe crit spec.',
  },
  {
    id: 'widen-the-gap',
    name: 'Widen the Gap',
    source: 'Turpin Rowe Lumberjack (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Once you have penetrated a foe\'s defenses, you can home in on the same spot to exploit your opponent\'s wound and deal some serious damage. The second time you hit and deal damage with a melee axe Strike to the same opponent or object during your turn, you ignore half of the opponent\'s or object\'s Hardness, if any. If you hit and deal damage with a melee axe Strike to the same opponent or object a third or fourth time during your turn, you ignore all of its Hardness, if any.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Turpin Rowe Lumberjack Dedication'],
    mechanics: '2nd melee axe hit same target/turn: ignore half Hardness. 3rd+ hit: ignore all Hardness.',
  },
];

// ─── COMBINED EXPORT ─────────────────────────────────────
export const STANDALONE_ARCHETYPE_FEATS_LEGACY_LO5: FeatEntry[] = [
  ...HALCYON_SPEAKER_FEATS,
  ...CRYSTAL_KEEPER_FEATS,
  ...ZEPHYR_GUARD_FEATS,
  ...TURPIN_ROWE_LUMBERJACK_FEATS,
];
