import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — B through E
// Avenger, Battle Harbinger, Blackjacket, Eagle Knight
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// AVENGER  (War of Immortals pg. 58–59)
// Category: Class Archetype (Rogue) — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=282
// Must be a Rogue with the Avenger racket.
// ──────────────────────────────────────────────────────────

export const AVENGER_FEATS: FeatEntry[] = [
  {
    id: 'avenger-dedication',
    name: 'Avenger Dedication',
    source: 'Avenger (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your training regimen has given you particular advantages when it comes to enforcing the interests of your faith. You gain a +1 status bonus to saving throws against divine spells and effects that deal spirit damage. You can use Religion to Coerce, Gather Information, or Track as long as you are in a town or city with a church dedicated to your deity, extracting clues from the faithful with displays of your piety.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Avenger (racket)'],
    mechanics: '+1 status bonus to saves vs divine spells and spirit damage effects. Religion substitutes for Intimidation (Coerce), Diplomacy (Gather Information), or Survival (Track) in towns/cities with a church of your deity. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'avenger-zealous-inevitability',
    name: 'Zealous Inevitability',
    source: 'Avenger (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You channel your zeal through a sacred weapon, bringing a foe closer to their demise. Strike a target with the required weapon. On a success, the target becomes doomed 1 or increases the value of their doomed condition by 1. Creatures doomed in this way take a status penalty to their saving throws against divine spells equal to their doomed value. A creature that would become doomed 4 by this Strike can attempt a Will saving throw against your class DC to avoid increasing the value of their doomed condition. When this occurs, this ability gains the incapacitation trait.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Avenger Dedication'],
    mechanics: 'Requires wielding deity\'s favored weapon. Strike inflicts doomed 1 (or +1 doomed). Doomed from this imposes status penalty to saves vs divine spells = doomed value. Reaching doomed 4 triggers Will save (class DC) with incapacitation trait.',
  },
  {
    id: 'avenger-silence-the-profane',
    name: 'Silence the Profane (Avenger)',
    source: 'Avenger (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your training included instruction on how to prevent enemy priests from using their magic against you, a technique you have mastered and adapted. Make a Strike with your deity\'s favored weapon against the triggering creature. On a success, the target is off-guard until the end of your next turn. The triggering spell is disrupted on a critical success, or on a success if the target is your hunted prey and the spell is a divine spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Avenger Dedication'],
    mechanics: 'Trigger: A creature you can observe within reach of your deity\'s favored weapon casts a spell. Requires wielding deity\'s favored weapon. On success: target off-guard until end of your next turn. Disrupts spell on crit success, or on success if target is hunted prey casting divine. Ranged variant if deity\'s favored weapon is ranged (first range increment).',
  },
  {
    id: 'avenger-shadow-of-death',
    name: 'Shadow of Death',
    source: 'Avenger (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Strikes you make with your deity\'s favored weapon against a creature with the doomed condition have the death trait, causing the target to be instantly killed when reduced to 0 Hit Points. When killed in this way, attempts to communicate with it, return it to life, turn it into an undead, or otherwise disturb its afterlife fail unless the effect\'s counteract rank is higher than half your level when you killed the creature (rounded up), or originates from an artifact or a deity.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Avenger Dedication'],
    mechanics: 'Favored weapon Strikes vs doomed creatures gain the death trait (instant kill at 0 HP). Resurrection/communication/undead creation fail unless counteract rank > half your level (rounded up), or from artifact/deity. Synergizes with Zealous Inevitability.',
  },
  {
    id: 'avenger-slay',
    name: 'Slay',
    source: 'Avenger (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You finish your target with a vicious attack. Make a Strike against the target. If you hit, the target takes 4d6 extra precision damage with a basic Fortitude save against your class DC. If the target critically fails, they die. This is an incapacitation effect. The creature then becomes temporarily immune to your Slay for 1 day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Avenger Dedication'],
    mechanics: 'Requires target doomed 2+. On hit: 4d6 extra precision damage (basic Fort save vs class DC). Crit fail on save = death (incapacitation). 1-day temp immunity.',
  },
];

// ──────────────────────────────────────────────────────────
// BATTLE HARBINGER  (Divine Mysteries pg. 272–275)
// Category: Class Archetype (Cleric) — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=304
// Must be a Cleric with the Battle Creed doctrine.
// ──────────────────────────────────────────────────────────

export const BATTLE_HARBINGER_FEATS: FeatEntry[] = [
  {
    id: 'battle-harbinger-dedication',
    name: 'Battle Harbinger Dedication',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have trained extensively in combat, battlefield tactics, and stamina, focusing on being an exceptional warrior for your faith in exchange for less time studying the traditional spells and scriptures. You become trained in your choice of Athletics or Acrobatics; if you are already trained in both skills, you instead become trained in another skill of your choice. You gain the Toughness general feat. If you already have this feat, you gain another general feat of your choice.',
    implemented: 'full',
    traits: ['Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Battle Creed (doctrine)'],
    mechanics: 'Trained in Athletics or Acrobatics (or free skill if already trained in both). Grants Toughness feat (or substitute general feat). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'battle-harbinger-aura-enhancement',
    name: 'Aura Enhancement',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve enhanced your training with your battle magic, allowing you access to a more potent divine font. Add benediction and malediction to the spells you can prepare with your additional slots from your divine font. These spells are also battle auras.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Expands divine font options — adds benediction and malediction as battle auras available for battle font slots.',
  },
  {
    id: 'battle-harbinger-tandem-onslaught',
    name: 'Tandem Onslaught',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You have trained your body and mind to work in tandem, and you can combine your combat and spellcasting prowess to better support yourself in battle. The first time each round that you successfully hit and deal damage to an enemy creature with a Strike using a weapon or unarmed attack, you can automatically Sustain a single battle aura that you currently have active, applying any additional effects that come with Sustaining the spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Once per round, when you hit and deal damage with a Strike, you get a free Sustain on one active battle aura.',
  },
  {
    id: 'battle-harbinger-exigent-aura',
    name: 'Exigent Aura',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'The power of your deity and your own convictions leave an impression on creatures even when they normally would be unable to comprehend your words or the feelings spurred on by your god. Your battle auras can affect mindless creatures, though they gain a +4 circumstance bonus on saving throws to resist the battle aura\'s effects.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Battle auras now work against mindless creatures but they get a +4 circumstance bonus to saves.',
  },
  {
    id: 'battle-harbinger-harbingers-protection',
    name: 'Harbinger\'s Protection',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You often work on missions alone, making sure to cover up your weaknesses more effectively than other members of your faith. You are trained in heavy armor. When you gain expert or greater proficiency in any type of armor, you also gain that proficiency in heavy armor.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Grants heavy armor training. Heavy armor proficiency automatically scales to match your highest armor proficiency.',
  },
  {
    id: 'battle-harbinger-creed-magic',
    name: 'Creed Magic',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You\'ve expanded your divine capabilities, granting you magic that better supports your combat focus. You gain two special 2nd-rank creed spell slots, which can be used to prepare resist energy, see the unseen, sure strike, and water breathing as divine spells. At 10th level, the extra slots increase to 3rd rank and you add haste and heroism. At 14th level, the extra slots increase to 4th rank and you add fly and unfettered movement.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Two bonus creed spell slots scaling in rank (2nd at 8th, 3rd at 10th, 4th at 14th). Limited to specific combat-support spells that expand: resist energy/see the unseen/sure strike/water breathing; +haste/heroism at 10th; +fly/unfettered movement at 14th.',
  },
  {
    id: 'battle-harbinger-harbingers-armament',
    name: 'Harbinger\'s Armament',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your deity grants you extra power that you have learned to channel into your weapons. Select one weapon or handwraps of mighty blows when you make your daily preparations. While in your hands it gains the effect of one property rune. Choose either fearsome, ghost touch, returning, shifting, or vitalizing. This rune does not count toward your maximum rune count, and this choice lasts 24 hours or until you make your next daily preparations, whichever comes first.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'During daily prep: pick one weapon/handwraps and grant it a free property rune (fearsome, ghost touch, returning, shifting, or vitalizing) that doesn\'t count against rune limits. Lasts 24 hours.',
    subChoices: { label: 'Choose property rune', options: [
      { id: 'fearsome', name: 'Fearsome' },
      { id: 'ghost-touch', name: 'Ghost Touch' },
      { id: 'returning', name: 'Returning' },
      { id: 'shifting', name: 'Shifting' },
      { id: 'vitalizing', name: 'Vitalizing' },
    ] },
  },
  {
    id: 'battle-harbinger-empowered-onslaught',
    name: 'Empowered Onslaught',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When your body and mind are perfectly in sync and pushed to the limit, it can produce even greater results. You channel your combat focus into the power of your battle auras. Choose one active battle aura you have; that battle aura\'s status bonus or penalty increases by 1, to a maximum of 4. This value remains for the rest of the aura\'s duration.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Tandem Onslaught'],
    mechanics: 'Trigger: You critically hit and Sustain a battle aura. Frequency: once per round. Boosts one active battle aura\'s status bonus/penalty by +1 (max 4) for remaining duration.',
  },
  {
    id: 'battle-harbinger-tandem-auras',
    name: 'Tandem Auras',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'ve learned how to maintain multiple auras at once, reinforcing them simultaneously. When you Sustain a battle aura, you can also Sustain a different battle aura you have active.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'When Sustaining one battle aura, also Sustain a second different active battle aura for free.',
  },
  {
    id: 'battle-harbinger-aura-expertise',
    name: 'Aura Expertise',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You\'ve become so accustomed to maintaining your battle auras that it\'s become second nature to you. You immediately gain the effects of the Sustain action for one of your battle auras.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Trigger: Your turn begins. Free Sustain on one battle aura at the start of every turn.',
  },
  {
    id: 'battle-harbinger-greater-armament',
    name: 'Greater Armament',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Your weapons have greater power available to them. Add brilliant, corrosive, flaming, frost, holy, shock, thundering, and unholy to the list of property runes you can choose from with Harbinger\'s Armament.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Harbinger\'s Armament'],
    mechanics: 'Expands Harbinger\'s Armament rune list: adds brilliant, corrosive, flaming, frost, holy, shock, thundering, and unholy (in addition to the original 5).',
  },
  {
    id: 'battle-harbinger-live-the-creed',
    name: 'Live the Creed',
    source: 'Battle Harbinger (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You\'ve become an unparalleled figure among your faith, able to align your divine abilities with unparalleled swiftness. You cast a battle aura using one of your divine font slots.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Battle Harbinger Dedication'],
    mechanics: 'Frequency: once per 10 minutes. Cast a battle aura from a divine font slot using 1 action instead of normal casting time.',
  },
];

// ──────────────────────────────────────────────────────────
// BLACKJACKET  (Shining Kingdoms pg. 76–77)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=316
// Access: You're from Druma.
// ──────────────────────────────────────────────────────────

export const BLACKJACKET_FEATS: FeatEntry[] = [
  {
    id: 'blackjacket-dedication',
    name: 'Blackjacket Dedication',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have entered the ranks of the Mercenary League and now wear the black uniform that\'s the source of the organization\'s popular epithet. You become trained in Intimidation; if you were already trained, you become an expert instead. You gain the Additional Lore skill feat for Warfare Lore; if you were already trained in Warfare Lore, you also become trained in a Lore skill of your choice. While wearing medium or heavy armor, you gain a +1 circumstance bonus to Intimidation checks.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in medium armor and martial weapons'],
    mechanics: 'Access: You\'re from Druma. Intimidation training (or expert). Additional Lore (Warfare Lore). +1 circumstance to Intimidation in medium/heavy armor. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'blackjacket-belay-that',
    name: 'Belay That!',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can recognize when a strategy isn\'t working and advise your ally to change course. The next Strike the triggering ally makes before the end of their turn has the same multiple attack penalty as the critically failed Strike, but it counts toward their multiple attack penalty as normal.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory'],
    actionCost: 'reaction',
    prerequisites: ['Blackjacket Dedication'],
    mechanics: 'Trigger: An ally within 30 feet critically fails a Strike. Ally\'s next Strike that turn uses the crit-failed Strike\'s MAP (effectively a retry at the same penalty). Still increments MAP normally.',
  },
  {
    id: 'blackjacket-mercenary-motivation',
    name: 'Mercenary Motivation',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'A large part of being in the Mercenary League entails doing mercenary work. You spend 1 minute planning a course of action that will allow you to complete a task you\'ve been hired or requested to do. Whenever you attempt a Perception check or skill check that will advance your course of action, you gain a +1 circumstance bonus to the check. You can have only one course of action planned at a time. When you complete the course of action, you don\'t lose the bonus until you make a different plan or voluntarily Dismiss it.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Exploration'],
    actionCost: 'passive',
    prerequisites: ['Blackjacket Dedication'],
    mechanics: 'Exploration activity (1 minute). Grants +1 circumstance bonus to Perception and skill checks advancing your active mission. One plan at a time. Persists after completion until replaced/dismissed. Gateway for Nothing Personal and Close Contract.',
  },
  {
    id: 'blackjacket-battlefield-agility',
    name: 'Battlefield Agility',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your enemies might think they have you surrounded, but you know just how to extricate yourself. Make a melee Strike against one of the enemies flanking you and Step, in any order.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Blackjacket Dedication'],
    mechanics: 'Requires being flanked by at least 2 enemies. 1-action: melee Strike + Step (any order). Efficient repositioning out of a flank.',
  },
  {
    id: 'blackjacket-lead-by-example',
    name: 'Lead by Example',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You telegraph your next attack to let your allies in on your strategy. Make a melee or ranged Strike with a –2 circumstance penalty. On a hit, the next ally to target the same creature with a Strike gains a +2 circumstance bonus to their attack roll. On a critical hit, the bonus applies to any allies who act before the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Blackjacket Dedication'],
    mechanics: '1-action Flourish. Strike at –2 circumstance penalty. Hit: next ally gets +2 circumstance to attack vs same target. Crit: ALL allies acting before your next turn get +2.',
  },
  {
    id: 'blackjacket-nothing-personal',
    name: 'Nothing Personal',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you\'re on a job, you can\'t allow anyone to stop you. Designate a single creature you can see as being an impediment to your active course of action. The first time you Strike your impediment in a round, you deal an extra die of weapon damage. At 14th level, this increases to two extra dice, and at 20th level, this increases to three extra dice. You can have only one creature designated as an impediment at a time. Otherwise, your designation lasts for 1 hour.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Mercenary Motivation'],
    mechanics: 'Designate one visible enemy as impediment (requires active Mercenary Motivation plan). First Strike/round vs impediment: +1 weapon die (scaling to +2 at 14th, +3 at 20th). One impediment at a time, lasts 1 hour.',
  },
  {
    id: 'blackjacket-close-contract',
    name: 'Close Contract',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You\'re bolstered when a plan comes together. You Dismiss your current course of action and gain 15 temporary Hit Points that last for 1 hour. The number of temporary Hit Points increases by 5 at 12th level and every 2 levels thereafter.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Mercenary Motivation'],
    mechanics: 'Requires completed active Mercenary Motivation plan (not yet dismissed). Dismiss plan for 15 temp HP (1 hour). Scales: +5 temp HP at 12th and every 2 levels after.',
  },
  {
    id: 'blackjacket-opportune-opening',
    name: 'Opportune Opening',
    source: 'Blackjacket (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your combat training taught you to capitalize on any moment of weakness from your foe. You make a melee Strike against the same creature your ally just hit. The creature is off-guard against this Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Blackjacket Dedication'],
    mechanics: 'Trigger: An ally lands a critical hit on a creature within your melee reach. Melee Strike vs that enemy — it\'s off-guard against this Strike.',
  },
];

// ──────────────────────────────────────────────────────────
// EAGLE KNIGHT  (Shining Kingdoms pg. 50–51)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=314
// Access: You're invited by a current member of the Eagle
// Knights or the People's Council.
// ──────────────────────────────────────────────────────────

export const EAGLE_KNIGHT_FEATS: FeatEntry[] = [
  {
    id: 'eagle-knight-dedication',
    name: 'Eagle Knight Dedication',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Eagle Knights are the marshals and envoys of Andoran and are committed to keeping the peace. On the first round of combat, if you roll Diplomacy for initiative, creatures that haven\'t acted are off-guard to you. You gain the Additional Lore skill feat for Politics Lore. If you were already trained in Politics Lore, you also become trained in a Lore skill of your choice. You can use Politics Lore to Make an Impression on or make a Request of government officials or to Gather Information about them. If you critically succeed at a check to Gather Information with Politics Lore, you know the information without having to spend any time gathering it.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Diplomacy and Society'],
    mechanics: 'Access: Invited by Eagle Knights or People\'s Council. Diplomacy initiative: creatures that haven\'t acted are off-guard to you in round 1. Additional Lore (Politics Lore) with expanded government official use. Crit Gather Information = instant results. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'eagle-knight-commitment-to-equality',
    name: 'Commitment to Equality',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You help an ally shake off any impediment that would give an enemy an unfair advantage. You rally a creature within 30 feet in an attempt to reduce its frightened or stupefied condition. When you\'re a master in Diplomacy, add clumsy and enfeebled. When you\'re legendary in Diplomacy, add stunned. Attempt a Diplomacy check against the saving throw DC of the effect that caused the condition. Critical Success: Reduce the condition\'s value by 2. Success: Reduce by 1. Critical Failure: Increase by 1.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Mental', 'Skill'],
    actionCost: 2,
    prerequisites: ['Eagle Knight Dedication', 'Expert in Diplomacy'],
    mechanics: 'Diplomacy vs effect save DC (or hard DC). Targets frightened/stupefied at expert; +clumsy/enfeebled at master; +stunned at legendary. Crit success: –2 value. Success: –1 value. Crit fail: +1 value. Target immune 1 hour after attempt.',
  },
  {
    id: 'eagle-knight-interpose',
    name: 'Interpose',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You put yourself between an ally and danger. Stride up to your Speed. You must end your movement adjacent to an ally. You and your ally then swap positions with each other. After changing positions, you can make a melee Strike against an enemy within your reach.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Eagle Knight Dedication'],
    mechanics: 'Stride (must end adjacent to ally) → swap positions → optional melee Strike. Shield an ally by taking their position.',
  },
  {
    id: 'eagle-knight-commitment-to-justice',
    name: 'Commitment to Justice',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When your allies are harmed, you deliver retribution. Make a Strike against the required creature. If this Strike hits, you gain a circumstance bonus to damage equal to three times the number of weapon damage dice.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Eagle Knight Dedication'],
    mechanics: 'Requires witnessing a creature kill or down an ally since your last turn. Strike that creature; on hit: +3× weapon damage dice as circumstance bonus to damage.',
  },
  {
    id: 'eagle-knight-commitment-to-liberty',
    name: 'Commitment to Liberty',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can\'t abide when a foe has one of your allies in its grip. Make a Strike against the required creature. If this Strike hits, the grabbed or restrained ally can immediately attempt to Escape as a free action. If the Strike was a critical hit, that ally gains a +2 circumstance bonus to their Escape attempt.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Eagle Knight Dedication'],
    mechanics: 'Requires a creature grabbing/restraining an ally. Strike the grabber; on hit: ally gets free Escape attempt. On crit: +2 circumstance to Escape.',
  },
  {
    id: 'eagle-knight-bolster-ally',
    name: 'Bolster Ally',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You shout encouragement to your embattled ally. The ally can use your saving throw modifier instead of their own against the triggering spell.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory'],
    actionCost: 'reaction',
    prerequisites: ['Eagle Knight Dedication'],
    mechanics: 'Trigger: Ally within 30 feet is targeted by a spell/ability requiring a save. Frequency: once per 10 minutes. Ally uses YOUR save modifier instead of theirs.',
  },
  {
    id: 'eagle-knight-stir-allies',
    name: 'Stir Allies',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You shout a command for your allies to scramble. Allies within 30 feet can use a reaction to Step. If you\'re legendary in Diplomacy, they can instead Stride.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Eagle Knight Dedication'],
    mechanics: 'All allies within 30 feet may use a reaction to Step (or Stride if legendary in Diplomacy). Mass team repositioning.',
  },
  {
    id: 'eagle-knight-aura-of-confidence',
    name: 'Aura of Confidence',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your will and your faith in your nation is unassailable, and the feeling is contagious. You gain resistance to mental damage equal to half your level. You and all allies within 15 feet gain a +2 status bonus to saving throws against mental effects.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Mental'],
    actionCost: 'passive',
    prerequisites: ['Eagle Knight Dedication'],
    mechanics: 'Mental resistance = half level. You + allies within 15 feet: +2 status bonus to saves vs mental effects.',
  },
  {
    id: 'eagle-knight-talmandors-shout',
    name: 'Talmandor\'s Shout',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'After seeing an enemy harm one of your allies, you deliver a righteous shout in the name of the celestial Talmandor. Attempt an Intimidation check to Demoralize, comparing the result to the Will DC of each enemy within a 60-foot emanation; this Demoralize attempt doesn\'t take any penalty for not sharing a language. It\'s possible to get a different degree of success for each target.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Eagle Knight Dedication', 'Master in Intimidation'],
    mechanics: 'Frequency: once per day. Requires witnessing ally take damage since last turn. Mass Demoralize — Intimidation vs Will DC of all enemies in 60-foot emanation. No language penalty. Different results per target.',
  },
  {
    id: 'eagle-knight-even-the-odds',
    name: 'Even the Odds',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Even when overpowered, Eagle Knights hold out hope. If your next action is to use Commitment to Equality, you roll the Diplomacy check twice and take the higher result. If you succeed, the target also gains 25 temporary Hit Points that last for 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Fortune'],
    actionCost: 'free',
    prerequisites: ['Commitment to Equality'],
    mechanics: 'Frequency: once per day. Fortune effect preceding Commitment to Equality: roll Diplomacy twice, take higher. On success: target also gains 25 temp HP (1 minute).',
  },
  {
    id: 'eagle-knight-immediate-rebuke',
    name: 'Immediate Rebuke',
    source: 'Eagle Knight (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You can use Reactive Strike when a creature within your reach Strikes one of your allies.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Commitment to Justice', 'Reactive Strike'],
    mechanics: 'Expands Reactive Strike trigger — triggers when enemy Strikes ally within reach (not just on manipulate/move). Transforms into a bodyguard who punishes attacks on allies.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG  (all non-core B–E archetypes)
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_BE: FeatEntry[] = [
  ...AVENGER_FEATS,
  ...BATTLE_HARBINGER_FEATS,
  ...BLACKJACKET_FEATS,
  ...EAGLE_KNIGHT_FEATS,
];
