import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — Guns & Gears (Part 2)
// Firework Technician, Overwatch, Sniping Duo,
// Trapsmith, Trick Driver, Vehicle Mechanic
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// FIREWORK TECHNICIAN  (Guns & Gears pg. 134–135)
// Category: Profession / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=119
// ──────────────────────────────────────────────────────────

export const FIREWORK_TECHNICIAN_FEATS: FeatEntry[] = [
  {
    id: 'firework-technician-dedication',
    name: 'Firework Technician Dedication',
    source: 'Firework Technician (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve learned the secrets of making fire and sound bloom using black powder, metals, and paper. You become trained in Fireworks Lore (or expert if already trained). You gain quick alchemy benefits, creating up to 4 pyrotechnic versatile vials during daily preparations. You gain the Launch Fireworks 1-action activity (manipulate, Cost 1 versatile vial) with three basic effects: Comet (60-foot line of bright light, can Point Out a creature), Flower (20-foot emanation with Fortitude save — dazzled 1 round on failure, 2 rounds on critical failure), and Salute (auditory — help fascinated or confused ally within 60 feet).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Crafting'],
    mechanics: 'Uncommon. Grants Launch Fireworks [1-action] (manipulate). DC = class DC or spell DC (higher). Three basic effects: Comet (visual, 60-ft line bright light + Point Out), Flower (visual, 20-ft emanation, Fort save, dazzled on fail), Salute (auditory, 60-ft range, ends fascinated/helps confused).',
  },
  {
    id: 'firework-technician-coughing-dragon',
    name: 'Coughing Dragon Display',
    source: 'Firework Technician (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the Coughing Dragon fireworks display. When you Launch Fireworks, you can spend 2 actions to choose either auditory or visual and attempt to counteract one or more effects in a 60-foot emanation with that trait. On a success, the effect is suppressed until the start of your next turn. Use Fireworks Lore as your counteract modifier with counteract rank equal to half your level rounded up. Spend 2 versatile vials and 3 actions to counteract both auditory and visual effects at the same time.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Firework Technician Dedication'],
    mechanics: 'Adds Coughing Dragon to Launch Fireworks. 2 actions: choose auditory OR visual, counteract effects in 60-ft emanation. Uses Fireworks Lore as counteract modifier. 3 actions + 2 vials: counteracts both auditory AND visual.',
  },
  {
    id: 'firework-technician-expert-crafter',
    name: 'Expert Fireworks Crafter',
    source: 'Firework Technician (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'re particularly adept at crafting fireworks, allowing you to create more fireworks than you otherwise could. Your number of versatile vials per day increases to 5.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Firework Technician Dedication', 'Expert in Crafting'],
    mechanics: 'Increases daily versatile vials to 5.',
  },
  {
    id: 'firework-technician-jumping-jenny',
    name: 'Jumping Jenny Display',
    source: 'Firework Technician (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain the Jumping Jenny fireworks display. When you Launch Fireworks, spend 1 action to target a flying creature within 60 feet. Until the start of your next turn, each time that creature attempts to Fly, they must succeed at an Acrobatics check to Maneuver in Flight against your Launch Fireworks DC, or the Fly action is disrupted. If all the creature\'s attempts to Fly are disrupted, at the end of its turn, it falls harmlessly to the ground.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Firework Technician Dedication'],
    mechanics: 'Adds Jumping Jenny [1-action] to Launch Fireworks. Targets flying creature within 60 ft. Fly attempts require Acrobatics check vs your DC or disrupted. Falls harmlessly if all Fly attempts disrupted.',
  },
  {
    id: 'firework-technician-goblin-jubilee',
    name: 'Goblin Jubilee Display',
    source: 'Firework Technician (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You gain the Goblin Jubilee fireworks display. When you Launch Fireworks, spend 3 actions to fill a 20-foot burst within 120 feet with chaos. All creatures in the area take 3d6 fire damage and 3d6 sonic damage with a Fortitude save. Every 3 levels, both increase by 1d6. You can expend 2 versatile vials to increase each by 1d6 (or 2d6 each at 16th level). Critical Success: unaffected. Success: dazzled and deafened until end of next turn, half damage. Failure: dazzled and deafened for 1 minute, full damage. Critical Failure: blinded for 1 round, dazzled and deafened for 1 minute, double damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Firework Technician Dedication'],
    mechanics: 'Adds Goblin Jubilee [3-actions] (fire, sonic, visual) to Launch Fireworks. 20-ft burst in 120 ft. 3d6 fire + 3d6 sonic, Fort save. Scales +1d6 each every 3 levels. 2 vials: extra 1d6 each (2d6 at 16th).',
  },
  {
    id: 'firework-technician-banshee-cry',
    name: 'Banshee Cry Display',
    source: 'Firework Technician (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You gain the Banshee Cry fireworks display. When a creature within 30 feet Casts a Spell or Activates an Item using a concentrate activation, you can use this reaction to set off a firework with a loud screech. The creature must attempt a Will save. Failure: the creature must use an additional action on the triggering action or activity, or it\'s disrupted. Critical Failure: the triggering action is disrupted.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Firework Technician Dedication'],
    mechanics: 'Adds Banshee Cry [reaction] to Launch Fireworks. Trigger: creature within 30 ft Casts a Spell or Activates Item with concentrate. Will save. Failure: extra action or disrupted. Critical Failure: disrupted.',
  },
];

// ──────────────────────────────────────────────────────────
// OVERWATCH  (Guns & Gears pg. 50–51)
// Category: Combat Style / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=109
// ──────────────────────────────────────────────────────────

export const OVERWATCH_FEATS: FeatEntry[] = [
  {
    id: 'overwatch-dedication',
    name: 'Overwatch Dedication',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have an innate knack for tactical observation. You\'re surrounded by an overwatch field aura in a 30-foot emanation (auditory, visual). You and allies within your overwatch field receive a +2 circumstance bonus when using Perception for Initiative checks.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Expert in Perception'],
    mechanics: 'Uncommon. 30-ft overwatch field aura (auditory, visual). You and allies in aura get +2 circumstance bonus to Perception-based Initiative checks.',
  },
  {
    id: 'overwatch-spyglass-modification',
    name: 'Spyglass Modification',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your enhanced visual gear includes a regulating scope and reflectors that allow you to see around a single corner within the area of your overwatch field. Your overwatch field extends around that corner and you can see around it. This doesn\'t let you see through walls, see around a second corner, or make ranged attacks without line of effect.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Overwatch Dedication'],
    mechanics: 'Overwatch field extends around one corner. You can see around that corner. No line of effect for attacks.',
  },
  {
    id: 'overwatch-swift-intervention',
    name: 'Swift Intervention',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When an ally within your overwatch field fails an attempt to Arrest a Fall, Balance, Grab a Ledge, or Maneuver in Flight, you make a ranged attack roll against the DC of the triggering check. Your ally uses the result of your ranged attack roll in place of their original roll. You must have line of effect to your ally.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Overwatch Dedication'],
    mechanics: 'Reaction. Trigger: ally in overwatch field fails Arrest a Fall/Balance/Grab a Ledge/Maneuver in Flight. Make ranged attack vs DC of check. Ally uses your result. Requires line of effect.',
  },
  {
    id: 'overwatch-topple-giants',
    name: 'Topple Giants',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When an ally within your overwatch field attempts to Disarm, Shove, or Trip an opponent within your overwatch field and fails, you coordinate efforts to provide a +2 circumstance bonus to the next Athletics check by a different ally to attempt the same action on the same target before that target\'s next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Overwatch Dedication'],
    mechanics: 'When ally fails Disarm/Shove/Trip in overwatch field, next different ally gets +2 circumstance to same action vs same target before target\'s next turn.',
  },
  {
    id: 'overwatch-wide-overwatch',
    name: 'Wide Overwatch',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You have become able to observe and maintain your overwatch at a much greater distance. Increase the size of your overwatch field from 30 feet to 60 feet.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Overwatch Dedication', 'Master in Perception'],
    mechanics: 'Overwatch field increases from 30 ft to 60 ft.',
  },
  {
    id: 'overwatch-forewarn',
    name: 'Forewarn',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Once per minute, when an enemy within your overwatch field attacks an ally also within the field, the triggering attack roll targets your Perception DC instead of your ally\'s AC. This doesn\'t remove conditions or penalties affecting your ally\'s AC — those still apply to damage calculations like sneak attack.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Overwatch Dedication', 'Master in Perception'],
    mechanics: 'Reaction. Frequency: once per minute. Trigger: enemy attacks ally in overwatch field. Attack targets your Perception DC instead of ally\'s AC. Conditions on ally still apply for damage features.',
  },
  {
    id: 'overwatch-master-spotter',
    name: 'Master Spotter',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your incredible perception and trusty enhanced visual gear allow you to see things others miss. Your proficiency rank in Perception increases to master.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Overwatch Dedication', 'Expert in Perception'],
    mechanics: 'Perception proficiency increases to master.',
  },
  {
    id: 'overwatch-control-tower',
    name: 'Control Tower',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You and allies in your overwatch field gain a +2 circumstance bonus when using Seek to find hidden or undetected creatures within the field. You and your allies don\'t need to succeed at a flat check to target a concealed creature in the field. When targeting a hidden creature in the field, reduce the flat check DC to 5.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Overwatch Dedication', 'Master in Perception'],
    mechanics: '+2 circumstance to Seek hidden/undetected in overwatch field. No flat check for concealed. Hidden flat check reduced to DC 5.',
  },
  {
    id: 'overwatch-converge',
    name: 'Converge',
    source: 'Overwatch (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'When you successfully make a ranged Strike against an opponent in your overwatch field who is within reach of an ally also in the field, that ally can make a melee Strike as a reaction. This Strike doesn\'t count toward the ally\'s multiple attack penalty, and their MAP doesn\'t apply. If the ally\'s Strike succeeds, combine damage from both attacks for resistances and weaknesses.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Overwatch Dedication', 'Master in Perception'],
    mechanics: 'Reaction. Trigger: your successful ranged Strike vs opponent in overwatch field within ally\'s reach. Ally makes melee Strike as reaction (no MAP). On hit, combine damage for resistances/weaknesses.',
  },
];

// ──────────────────────────────────────────────────────────
// SNIPING DUO  (Guns & Gears pg. 137–139)
// Category: Combat Style / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=121
// ──────────────────────────────────────────────────────────

export const SNIPING_DUO_FEATS: FeatEntry[] = [
  {
    id: 'sniping-duo-dedication',
    name: 'Sniping Duo Dedication',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Choose one willing, non-minion ally as your spotter. Your spotter doesn\'t need feats to grant the effects. You only gain benefits if both you and your spotter are alive and conscious. You and your spotter don\'t grant lesser cover against each other\'s Strikes. When either of you successfully Strikes a target, the other gains a +1 circumstance bonus per weapon damage die on next Strike against that target before end of their next turn. You can change your spotter with 3 days of downtime.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in at least one crossbow or firearm weapon', 'Trained in Stealth'],
    mechanics: 'Designate a spotter ally. No lesser cover between duo. On successful Strike, other member gets +1 circ per weapon damage die to next Strike vs same target. Change spotter: 3 days downtime.',
  },
  {
    id: 'sniping-duo-triangulate',
    name: 'Triangulate',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'As long as both you and your spotter can see the target, you don\'t take a penalty for attacking within your weapon\'s second range increment. The penalty for the third range increment is –3, with an additional –2 for each increment beyond (–5 fourth, –7 fifth, –9 sixth).',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Visual'],
    actionCost: 'passive',
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: 'No range penalty in 2nd increment (both must see target). 3rd increment: –3, 4th: –5, 5th: –7, 6th: –9.',
  },
  {
    id: 'sniping-duo-exploit-opening',
    name: 'Exploit Opening',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When your spotter critically succeeds at a Strike against a creature within your crossbow or firearm\'s first range increment, you can make a ranged Strike against the same target with a +2 circumstance bonus.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: 'Reaction. Trigger: spotter crit succeeds a Strike vs target in your 1st range increment. Make ranged Strike with +2 circumstance.',
  },
  {
    id: 'sniping-duo-targeted-redirection',
    name: 'Targeted Redirection',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You aim a shot at your spotter, who redirects it to hit your foe from a better angle. If your next action is a ranged Strike, treat your spotter\'s position as your own for cover and range. Your spotter must be within your weapon\'s first range increment and uses a reaction to redirect.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: '1 action. Next ranged Strike uses spotter\'s position for cover/range. Spotter must be in 1st range increment and uses a reaction.',
  },
  {
    id: 'sniping-duo-duos-aim',
    name: 'Duo\'s Aim',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'With assistance from your spotter, you aim for an especially accurate attack. Make a ranged weapon Strike against a foe within your spotter\'s melee reach or first range increment. You gain a +2 circumstance bonus to the attack roll and ignore the target\'s concealment. If using a kickback firearm, you don\'t take the normal circumstance penalty.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 2,
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: '2 actions. Strike vs foe in spotter\'s reach/1st range increment. +2 circumstance to attack, ignore concealment. No kickback penalty.',
  },
  {
    id: 'sniping-duo-vantage-shot',
    name: 'Vantage Shot',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you successfully make a ranged Strike, your spotter can use a reaction to attempt a Stealth check against the foe\'s Perception DC. On success, the foe is off-guard against the spotter\'s next attack before end of their next turn. This works in reverse too — when your spotter Strikes, you can attempt the Stealth check.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: 'On successful ranged Strike, other duo member can react with Stealth vs foe Perception DC. Success: foe off-guard vs their next attack. Works both ways.',
  },
  {
    id: 'sniping-duo-tag-team',
    name: 'Tag Team',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you or your spotter misses a Strike against a creature within the other\'s melee reach or first range increment, the other member can use a reaction to make a Strike against the same target. Strikes from this feat don\'t count toward multiple attack penalty and MAP doesn\'t apply to them.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: 'Reaction. Trigger: you or spotter misses Strike. Other member makes Strike (melee or ranged) vs same target. No MAP interaction.',
  },
  {
    id: 'sniping-duo-eagle-eyes',
    name: 'Eagle Eyes',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'As long as you can see or hear each other, neither you nor your spotter is off-guard to hidden, undetected, or flanking creatures of your level or lower, or from surprise attacks by such creatures. Those creatures can still help their allies flank.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Visual'],
    actionCost: 'passive',
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: 'While you can see/hear spotter: neither off-guard to hidden/undetected/flanking creatures ≤ your level, or surprise attacks from them. Enemies can still help allies flank.',
  },
  {
    id: 'sniping-duo-concentrated-assault',
    name: 'Concentrated Assault',
    source: 'Sniping Duo (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'If you and your spotter both use the Ready activity to make a Strike against the same opponent with the same trigger, resolve attacks at the same time. Each can use the higher of the two attack rolls with their own modifier (fortune effect). If both Strikes succeed, total the damage for resistances and weaknesses.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Sniping Duo Dedication'],
    mechanics: 'Both Ready Strike vs same target with same trigger. Resolve simultaneously. Each uses higher attack roll (fortune). On dual success, combine damage for resistances/weaknesses.',
  },
];

// ──────────────────────────────────────────────────────────
// TRAPSMITH  (Guns & Gears pg. 54)
// Category: Combat Style / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=111
// ──────────────────────────────────────────────────────────

export const TRAPSMITH_FEATS: FeatEntry[] = [
  {
    id: 'trapsmith-dedication',
    name: 'Trapsmith Dedication',
    source: 'Trapsmith (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You use gears and cogwheels to manufacture snares. If you construct a snare using gears and a creature fails their saving throw, all creatures are concealed to that creature for 1 round as a burst of steam obscures its vision.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Snarecrafter Dedication or Snare Specialist ranger class feat'],
    mechanics: 'Uncommon. Gear snares: on failed save, target treats all creatures as concealed for 1 round (steam burst). You can take this even without 3 Snarecrafter feats.',
  },
  {
    id: 'trapsmith-gear-gnash',
    name: 'Gear Gnash',
    source: 'Trapsmith (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Creatures attempting to Disable your gear snares must succeed at an additional Thievery check. On a failed check, the grinding mechanisms deal bludgeoning damage equal to half your level. The snare still triggers on a critical failure as normal.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Trapsmith Dedication', 'Expert in Crafting'],
    mechanics: 'Gear snares require extra Thievery check to Disable. Failed Disable: bludgeoning damage = half your level. Critical failure: snare triggers normally.',
  },
  {
    id: 'trapsmith-propeller-attachment',
    name: 'Propeller Attachment',
    source: 'Trapsmith (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'You can attach clockwork propellers to your daily quick-deploy gear snares. This allows placement in the air or underwater, where they hover for up to 10 minutes before the propeller runs out. A propeller snare\'s location is usually obvious unless you use additional precautions to hide it.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Trapsmith Dedication', 'Master in Crafting'],
    mechanics: 'Daily quick-deploy gear snares can be placed in air/underwater. Lasts 10 minutes before falling. Usually visible unless hidden.',
  },
  {
    id: 'trapsmith-recycled-cogwheel',
    name: 'Recycled Cogwheel',
    source: 'Trapsmith (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can deconstruct a daily quick-deploy gear snare that didn\'t trigger to set it up somewhere else. This takes the same number of actions as setting the snare originally. You recover the snare and can deploy it in another location.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Trapsmith Dedication'],
    mechanics: 'Recover untriggered gear snares (same action cost as setting). Redeploy elsewhere.',
  },
  {
    id: 'trapsmith-repurposed-parts',
    name: 'Repurposed Parts',
    source: 'Trapsmith (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Using two of the snares you prepared for quick deployment during daily preparations, you can quickly deploy a different snare that you know how to Craft, even if you didn\'t prepare that snare during your daily preparations.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Trapsmith Dedication'],
    mechanics: 'Spend 2 prepared quick-deploy snares to deploy a different snare you know how to Craft (even if not prepared).',
  },
  {
    id: 'trapsmith-finessed-features',
    name: 'Finessed Features',
    source: 'Trapsmith (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'ve learned how to build gear snares that trigger based on visual features of a creature. For example, only Large+ creatures, or creatures wearing red clothing. You can specify triggers for creatures that typically don\'t trigger snares (smaller than Small), though the creature must still otherwise satisfy the snare\'s trigger.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Trapsmith Dedication'],
    mechanics: 'Gear snares can trigger based on visual features (size, clothing, etc.). Can specify triggers for creatures that normally don\'t trigger snares.',
  },
];

// ──────────────────────────────────────────────────────────
// TRICK DRIVER  (Guns & Gears pg. 55)
// Category: Profession / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=112
// ──────────────────────────────────────────────────────────

export const TRICK_DRIVER_FEATS: FeatEntry[] = [
  {
    id: 'trick-driver-dedication',
    name: 'Trick Driver Dedication',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You are equally at home piloting any vehicle. Whenever piloting requires Piloting Lore or Sailing Lore, you can use Driving Lore instead, and you can use Dexterity in place of Intelligence for piloting checks with Driving Lore. You become an expert in Driving Lore. At 7th level you become master, and at 15th level legendary.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: [],
    mechanics: 'Uncommon. Use Driving Lore instead of Piloting/Sailing Lore. Use Dex instead of Int for Driving Lore. Expert in Driving Lore (master 7th, legendary 15th).',
  },
  {
    id: 'trick-driver-express-driver',
    name: 'Express Driver',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'When calculating travel speed while piloting a vehicle, you can attempt a Driving Lore check to increase travel speed. The DC is based on the vehicle\'s piloting DC or environment difficulty. On a success, increase the vehicle\'s travel speed by half. No effect on encounter movement.',
    implemented: 'full',
    traits: ['Archetype', 'Exploration', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Trick Driver Dedication'],
    mechanics: 'Exploration activity. Driving Lore check to increase vehicle travel speed by 50% on success. No effect in encounters.',
  },
  {
    id: 'trick-driver-take-the-wheel',
    name: 'Take the Wheel',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Diving into a moving vehicle and seizing the controls is nothing new for you. You Board and Take Control of an adjacent vehicle.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Trick Driver Dedication', 'Expert in Driving Lore'],
    mechanics: '1 action. Requirement: adjacent to vehicle\'s point of entry. Board and Take Control in a single action.',
  },
  {
    id: 'trick-driver-power-slide',
    name: 'Power Slide',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You throw the vehicle into a barely controlled skid, turning sharply. You Drive with a –2 penalty to your piloting check for 1–3 actions. At the end of movement, on success, you can turn the vehicle up to 90 degrees. On a critical success, up to 180 degrees.',
    implemented: 'full',
    traits: ['Archetype', 'Move', 'Reckless', 'Skill'],
    actionCost: 1,
    prerequisites: ['Trick Driver Dedication'],
    mechanics: '1–3 actions. Drive with –2 penalty. On success: turn up to 90°. On critical success: turn up to 180°. Requirement: piloting a vehicle.',
  },
  {
    id: 'trick-driver-push-it',
    name: 'Push It',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'Whenever you succeed at a piloting check, the vehicle you are piloting gains a +5-foot circumstance bonus to all its Speeds until the end of your turn. If you critically succeed, this bonus increases to +10 feet.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Trick Driver Dedication', 'Master in Driving Lore'],
    mechanics: 'On piloting success: vehicle +5 ft all Speeds until end of turn. Critical success: +10 ft.',
  },
  {
    id: 'trick-driver-roadkill',
    name: 'Roadkill',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you use Run Over, you can use your class DC in place of the vehicle\'s collision DC. Your vehicle can Run Over any number of creatures up to one Size smaller or ram one target up to the vehicle\'s size.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Trick Driver Dedication'],
    mechanics: 'Run Over: use class DC instead of collision DC. Can affect any number of creatures up to 1 Size smaller, or ram 1 target up to vehicle size. Requirement: piloting a vehicle.',
  },
  {
    id: 'trick-driver-drive-by-attack',
    name: 'Drive-By Attack',
    source: 'Trick Driver (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You Drive for 1–3 actions. At any point during your vehicle\'s movement, you can also make a Strike.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Trick Driver Dedication'],
    mechanics: '1–3 actions. Drive + Strike at any point during movement. Requirement: piloting a vehicle.',
  },
];

// ──────────────────────────────────────────────────────────
// VEHICLE MECHANIC  (Guns & Gears pg. 56–57)
// Category: Profession / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=113
// ──────────────────────────────────────────────────────────

export const VEHICLE_MECHANIC_FEATS: FeatEntry[] = [
  {
    id: 'vehicle-mechanic-dedication',
    name: 'Vehicle Mechanic Dedication',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become an expert in Crafting and choose one vehicle you own as your signature vehicle. Pilots gain a +1 circumstance bonus to piloting checks to control your signature vehicle (+2 if you\'re a master in Crafting). You can change your signature vehicle by spending 1 week of downtime.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Intelligence +2', 'Trained in Crafting'],
    mechanics: 'Uncommon. Expert in Crafting. Designate signature vehicle. Pilots get +1 circ to piloting checks (+2 if master Crafting). Change vehicle: 1 week downtime.',
  },
  {
    id: 'vehicle-mechanic-engine-bay',
    name: 'Engine Bay',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the Quick Repair skill feat (or another 1st-level skill feat if you already have it). When you successfully Repair a vehicle, restore an additional 10 Hit Points, or 20 on a critical success.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Vehicle Mechanic Dedication', 'Expert in Crafting'],
    mechanics: 'Gain Quick Repair feat. Repair vehicles: +10 HP on success, +20 HP on critical success.',
  },
  {
    id: 'vehicle-mechanic-patch-job',
    name: 'Patch Job',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the Improvised Repair general feat. When you use Improvised Repair, you can attempt a Crafting check with the same DC as Repair. If you succeed, you can use the object as normal until it takes damage again, instead of as a shoddy object.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vehicle Mechanic Dedication'],
    mechanics: 'Gain Improvised Repair feat. On Crafting check success, repaired object is normal quality (not shoddy) until damaged again.',
  },
  {
    id: 'vehicle-mechanic-superior-propulsion',
    name: 'Superior Propulsion',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Each time the pilot Drives your signature vehicle as a 2- or 3-action activity and succeeds, the vehicle produces an additional propulsion effect: Alchemical (adjacent creatures take acid damage = your level), Clockwork (broken vehicle skips flat check), Magical (+1 circ to saves vs spells), Pulled (+10 circ to Speed), Rowed (rowers below decks gain greater cover), Steam (concealed during movement), Wind (can turn normally instead of straight line).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vehicle Mechanic Dedication'],
    mechanics: 'On successful 2+action Drive of signature vehicle, gain propulsion bonus based on type: Alchemical (acid damage=level to adjacent), Clockwork (no broken flat check), Magical (+1 vs spells), Pulled (+10 Speed), Rowed (greater cover for rowers), Steam (concealed), Wind (free turning).',
  },
  {
    id: 'vehicle-mechanic-efficient-controls',
    name: 'Efficient Controls',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'Reduce the number of crew required to operate your signature vehicle by 25%. This doesn\'t reduce the pilot requirement.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Vehicle Mechanic Dedication', 'Master in Crafting'],
    mechanics: 'Signature vehicle: crew requirement reduced by 25%. Pilot still required.',
  },
  {
    id: 'vehicle-mechanic-impervious-vehicle',
    name: 'Impervious Vehicle',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your signature vehicle gains a +1 circumstance bonus to AC and Fortitude saves, and increases its Hit Points by an amount equal to twice your level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vehicle Mechanic Dedication'],
    mechanics: 'Signature vehicle: +1 circ to AC and Fort saves, +2×level HP.',
  },
  {
    id: 'vehicle-mechanic-miraculous-flight',
    name: 'Miraculous Flight',
    source: 'Vehicle Mechanic (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your signature vehicle gains magical propulsion and a fly Speed equal to its fastest current Speed. If it already had a fly Speed, reduce the turning distance to half the usual length.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 'passive',
    prerequisites: ['Vehicle Mechanic Dedication'],
    mechanics: 'Signature vehicle gains fly Speed = fastest current Speed. If already has fly Speed, turning distance halved.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_GG2: FeatEntry[] = [
  ...FIREWORK_TECHNICIAN_FEATS,
  ...OVERWATCH_FEATS,
  ...SNIPING_DUO_FEATS,
  ...TRAPSMITH_FEATS,
  ...TRICK_DRIVER_FEATS,
  ...VEHICLE_MECHANIC_FEATS,
];
