import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Lost Omens: Butterfly Blade,
// Ghost Eater, Gray Gardener, Bright Lion
// Pathfinder #166 / Night of the Gray Death / #172 / Legends
// ══════════════════════════════════════════════════════════

// ─── BUTTERFLY BLADE ─────────────────────────────────────
// Source: Pathfinder #166: Despair on Danger Island pg. 78
// ─────────────────────────────────────────────────────────

export const BUTTERFLY_BLADE_FEATS: FeatEntry[] = [
  {
    id: 'butterfly-blade-dedication',
    name: 'Butterfly Blade Dedication',
    source: 'Butterfly Blade (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You become trained in Deception and Stealth; if you were already trained, you become an expert instead. Whenever your proficiency rank in any weapon increases to expert or beyond, you also gain that new proficiency rank with butterfly swords. You gain access to butterfly swords.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['trained in butterfly swords'],
    mechanics: 'Uncommon. Trained Deception + Stealth (or expert). Weapon prof increases extend to butterfly swords. Gain access to butterfly swords.',
  },
  {
    id: 'butterfly-blade-butterflys-kiss',
    name: 'Butterfly\'s Kiss',
    source: 'Butterfly Blade (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can make nonlethal Strikes with a butterfly sword without taking a penalty.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Butterfly Blade Dedication'],
    mechanics: 'Nonlethal butterfly sword Strikes with no penalty.',
  },
  {
    id: 'butterfly-blade-butterflys-sting',
    name: 'Butterfly\'s Sting',
    source: 'Butterfly Blade (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You gain the sneak attack class feature (1d6). You don\'t increase the number of dice as you gain levels.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Butterfly Blade Dedication'],
    mechanics: 'Gain sneak attack 1d6 (doesn\'t increase with level).',
  },
  {
    id: 'butterfly-blade-masterminds-eye',
    name: 'Mastermind\'s Eye',
    source: 'Butterfly Blade (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you succeed at identifying a creature using Recall Knowledge, that creature is off-guard against your attacks until the start of your next turn; if you critically succeed, it\'s off-guard against your attacks for 1 minute. This feat serves as the rogue\'s mastermind racket for the purpose of meeting prerequisites.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Butterfly Blade Dedication'],
    mechanics: 'Recall Knowledge success: target off-guard vs your attacks until start of next turn (1 min on crit). Counts as mastermind racket for prereqs.',
  },
  {
    id: 'butterfly-blade-deadly-butterfly',
    name: 'Deadly Butterfly',
    source: 'Butterfly Blade (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain access to the butterfly sword\'s critical specialization effect. If you already had access to the critical specialization effect or you gain the effect at a later time, you also gain the critical specialization effect for knives when you critically hit with a butterfly sword. You can benefit from only one critical specialization effect at a time.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Butterfly Blade Dedication'],
    mechanics: 'Gain butterfly sword crit spec. If already had: also gain knife crit spec on butterfly sword crits (only 1 at a time).',
  },
  {
    id: 'butterfly-blade-innocent-butterfly',
    name: 'Innocent Butterfly',
    source: 'Butterfly Blade (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You know how to alter the perceptions of others. You can cast aura of the unremarkable once per day as an innate arcane spell. The spell uses your class DC or spell DC, whichever is higher.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Butterfly Blade Dedication'],
    mechanics: '1/day aura of the unremarkable (innate arcane). Uses higher of class DC or spell DC.',
  },
];

// ─── GHOST EATER ─────────────────────────────────────────
// Source: Pathfinder #166: Despair on Danger Island pg. 79
// ─────────────────────────────────────────────────────────

export const GHOST_EATER_FEATS: FeatEntry[] = [
  {
    id: 'ghost-eater-dedication',
    name: 'Ghost Eater Dedication',
    source: 'Ghost Eater (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have trained as a ghost eater, a hunter specialized in the destruction of spirits. Your weapon and unarmed attack Strikes become magical. Against incorporeal creatures, they also gain the effects of a ghost touch property rune.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['trained in Occultism or Religion'],
    mechanics: 'Uncommon. Strikes become magical. Vs incorporeal: gain ghost touch property rune effects.',
  },
  {
    id: 'ghost-eater-reach-beyond',
    name: 'Reach Beyond',
    source: 'Ghost Eater (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned to move your spiritual energy past yourself to attack spirits where others can\'t. You can make melee Strikes against incorporeal creatures that are inside solid objects as long as the object is within your reach. An incorporeal creature inside of a solid object is hidden, requiring you to succeed at a DC 11 flat check when you target it. You can spend an action, which has the concentrate trait, to focus on a creature inside of a solid object. If you do, the next melee Strike you make this turn requires you to succeed at only a DC 6 flat check to affect the creature.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghost Eater Dedication'],
    mechanics: 'Melee Strike incorporeal in solid objects (within reach, DC 11 flat check). 1-action concentrate: reduce to DC 6 flat check for next Strike this turn.',
  },
  {
    id: 'ghost-eater-disrupting-strikes',
    name: 'Disrupting Strikes',
    source: 'Ghost Eater (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You call forth vitality energy from within to help you destroy undead. Your weapon and unarmed Strikes gain the effects of a disrupting property rune until the start of your next turn. If you\'re 14th level or higher, your Strikes instead gain the effects of a greater disrupting property rune. The DC for the rune\'s effect is equal to your class DC or spell DC, whichever is higher.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Ghost Eater Dedication'],
    mechanics: '1 action. Strikes gain disrupting rune until start of next turn. 14th+: greater disrupting. DC = higher of class/spell DC.',
  },
  {
    id: 'ghost-eater-cross-the-threshold',
    name: 'Cross the Threshold',
    source: 'Ghost Eater (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You can cast ethereal jaunt as an occult innate spell once per day. You don\'t need to Sustain the Spell; instead, it lasts for 10 minutes or until you choose to return to your material form as a free action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghost Eater Dedication'],
    mechanics: '1/day ethereal jaunt (occult innate). No Sustain needed; lasts 10 min or free action to return.',
  },
];

// ─── GRAY GARDENER ───────────────────────────────────────
// Source: Night of the Gray Death pg. 64-65
// Uses Vigilante Dedication (APG pg. 196) as entry point
// ─────────────────────────────────────────────────────────

export const GRAY_GARDENER_FEATS: FeatEntry[] = [
  {
    id: 'gray-gardener-vigilante-dedication',
    name: 'Vigilante Dedication',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have two identities, each with its own name, alignment, and abilities. Your social identity is an upstanding member of society, while your vigilante identity is a skilled and cunning warrior. Neither of these identities is a false front; you really are both of these people, and as such, your two identities can be at most one alignment step from each other. If someone attempts to discern your other identity, they must use a Seek action to attempt a Perception check against your Deception DC, as if you were using the Impersonate action. Your Deception DC against such attempts is 20 + your proficiency modifier instead of the normal DC. Changing from one identity to the other takes 1 minute and must be done out of sight from other creatures. Your two identities are completely distinct. You have your current identity\'s alignment for effects that rely on alignment. Checks to Recall Knowledge about one of your identities don\'t reveal information about the other unless the person attempting the check knows both identities are the same person. To maintain the separation between your identities, some of your abilities have one of two traits: social or vigilante. You can use social feats only while in your social identity. Your class feats and vigilante feats are associated with your vigilante identity, and using them while in your social identity risks exposing you as a vigilante.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['trained in Deception'],
    mechanics: 'Uncommon. Two identities (social + vigilante). Change: 1 min out of sight. Deception DC = 20 + prof mod vs identification. Social/vigilante trait feats restricted by identity.',
  },
  {
    id: 'gray-gardener-executioner-weapon-training',
    name: 'Executioner Weapon Training',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your Gray Gardener training has made you deeply skilled with the weapons that execute with a swift chop to the neck. You become trained with the following weapons: battle axe, falchion, greataxe, and scimitar. Whenever you gain a class feature that grants you expert or greater proficiency with a given weapon or weapons, you also gain that proficiency for these weapons.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: 'Trained: battle axe, falchion, greataxe, scimitar. Class prof increases extend to these weapons.',
  },
  {
    id: 'gray-gardener-harsh-judgment',
    name: 'Harsh Judgment',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Choose one creature you can see, and loudly declare the creature\'s life forfeit by your judgment. That creature becomes your condemned foe until they are defeated, you use Harsh Judgment on a different creature, or the encounter ends. You gain a +2 circumstance bonus to Perception checks to Seek your condemned foe and on Intimidation checks to Demoralize them. You have a -1 circumstance penalty to Perception checks to Seek creatures other than your condemned foe and on Intimidation checks to Demoralize anyone other than your condemned foe. You typically can use Harsh Judgment only during an encounter, and if you try to use it to declare someone\'s life forfeit during exploration or downtime, you are likely to start an encounter.',
    implemented: 'full',
    traits: ['Archetype', 'Vigilante'],
    actionCost: 1,
    prerequisites: ['Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: '1 action. Condemn 1 creature: +2 Perception (Seek) and Intimidation (Demoralize) vs condemned; -1 to same vs others. Until defeated/new target/encounter ends.',
  },
  {
    id: 'gray-gardener-voice-of-authority',
    name: 'Voice of Authority',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You easily command the attention of others, and when the time comes to turn threats into action, your authoritative voice causes foes to falter. Your voice can be heard easily by any creatures within 300 feet if you wish, regardless of the level of ambient noise, although your voice can\'t penetrate silence or similar effect. If you roll Intimidation for initiative, on the first round of combat, creatures that haven\'t acted yet are off-guard to you.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Vigilante'],
    actionCost: 'passive',
    prerequisites: ['expert in Intimidation', 'Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: 'Voice heard within 300 ft (ignores noise, not silence). Intimidation initiative: creatures that haven\'t acted are off-guard to you round 1.',
  },
  {
    id: 'gray-gardener-discerning-gaze',
    name: 'Discerning Gaze',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have a sense for when people are lying. You gain a +1 circumstance bonus on your secret Perception checks to Sense Motive. If you use Sense Motive on a creature you have currently condemned with Harsh Judgment, your GM rolls the Perception check twice and takes the higher result (this is a fortune effect).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: '+1 circumstance to Sense Motive. Vs Harsh Judgment condemned: GM rolls twice, takes higher (fortune).',
  },
  {
    id: 'gray-gardener-frightful-condemnation',
    name: 'Frightful Condemnation',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your willingness to follow through on your pitiless judgment is frightful to the person you have condemned, and they begin to dread what you will do to them next. Your condemned foe is frightened 1, or frightened 2 if the triggering Strike was a critical hit.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Fear', 'Mental', 'Vigilante'],
    actionCost: 'free',
    prerequisites: ['Harsh Judgment', 'Vigilante Dedication'],
    mechanics: 'Free action. Trigger: hit condemned foe same turn as Harsh Judgment. Target frightened 1 (frightened 2 on crit hit).',
  },
  {
    id: 'gray-gardener-accurate-swing',
    name: 'Accurate Swing',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You strike cleanly with wide, sweeping attacks to inflict maximum damage, taking advantage of your judged foe\'s fear to land a felling blow. If you Strike a creature you condemned with Harsh Judgment that has the frightened condition with a sweep melee weapon or a sweep unarmed attack, you gain a circumstance bonus to the Strike\'s damage equal to the number of weapon damage dice your weapon deals.',
    implemented: 'full',
    traits: ['Archetype', 'Vigilante'],
    actionCost: 'passive',
    prerequisites: ['Vigilante Dedication', 'Harsh Judgment', 'member of the Gray Gardeners'],
    mechanics: 'Strike frightened condemned foe with sweep weapon: circumstance bonus to damage = weapon damage dice count.',
  },
  {
    id: 'gray-gardener-gardeners-resolve',
    name: 'Gardener\'s Resolve',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'The Gray Gardeners are known for having nerves of steel and an unbreakable resolve. When you would be overwhelmed by terror, you can draw upon this resolve to keep your composure and remain undaunted. You take mental damage equal to twice your level, and the saving throw is a success.',
    implemented: 'full',
    traits: ['Archetype', 'Vigilante'],
    actionCost: 'reaction',
    prerequisites: ['Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: 'Reaction, 1/day. Trigger: fail (not crit fail) Will vs fear. Take 2×level mental damage; save becomes success.',
  },
  {
    id: 'gray-gardener-strident-command',
    name: 'Strident Command',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'The common folk heed your demands, and though your true foes rarely bend to your commands, when they do the hesitation can cost them the battle. You can cast command once every 10 minutes as a 1st-level occult innate spell. If you\'re in your vigilante identity, you can command the target only to approach you, drop prone, or stand in place. If you\'re in your social identity, you can command the target only to run away or release what the target is holding.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['master in Intimidation', 'Vigilante Dedication', 'Voice of Authority', 'member of the Gray Gardeners'],
    mechanics: '1/10 min command (1st-level occult innate). Vigilante: approach/prone/stand. Social: flee/release.',
  },
  {
    id: 'gray-gardener-execution',
    name: 'Execution',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You swing wide, attempting to behead your condemned foe. Make a melee Strike against your condemned foe. If you hit, your condemned foe takes 8d6 extra precision damage with a basic Fortitude save against your class DC or spell DC, whichever is higher. If the condemned foe is reduced to 0 Hit Points by the execution and requires a head to live, they die. For creatures with multiple heads, this usually kills the creature only if you sever its last head. The creature then becomes temporarily immune to your Execution for 1 day.',
    implemented: 'full',
    traits: ['Archetype', 'Vigilante'],
    actionCost: 2,
    prerequisites: ['Harsh Judgment', 'Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: '2 actions. Melee Strike vs condemned: +8d6 precision (basic Fort vs class/spell DC). 0 HP + needs head → dies. Temp immune 1 day.',
  },
  {
    id: 'gray-gardener-terrifying-countenance',
    name: 'Terrifying Countenance',
    source: 'Gray Gardener (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You can erect a magical cowl that terrorizes your enemies. Once per day, you can cast mask of terror as an innate occult spell, targeting yourself. If you critically hit a creature that\'s temporarily immune to the spell, the creature\'s temporary immunity ends.',
    implemented: 'full',
    traits: ['Archetype', 'Vigilante'],
    actionCost: 'free',
    prerequisites: ['Vigilante Dedication', 'member of the Gray Gardeners'],
    mechanics: '1/day mask of terror (innate occult, self). Crit hit vs temp immune creature: ends their temp immunity.',
  },
];

// ─── BRIGHT LION ─────────────────────────────────────────
// Source: Pathfinder #172: Secrets of the Temple City pg. 79
//         / Legends pg. 101
// ─────────────────────────────────────────────────────────

export const BRIGHT_LION_FEATS: FeatEntry[] = [
  {
    id: 'bright-lion-dedication',
    name: 'Bright Lion Dedication',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have learned enough worship of Walkena in your daily life to avoid suspicion. You typically don\'t need to Lie or Impersonate to pass yourself off as a worshipper of Walkena. Against careful inspection, you gain a +4 circumstance bonus to Deception checks specifically to pass yourself off as a version of yourself faithful to Walkena.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['member of the Bright Lions', 'not a worshipper of Walkena', 'trained in Stealth'],
    mechanics: 'Uncommon. Pass as Walkena worshipper without Lie/Impersonate. +4 circumstance Deception under careful inspection.',
  },
  {
    id: 'bright-lion-blessing-of-the-sun-gods',
    name: 'Blessing of the Sun Gods',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'The Old Sun Gods share their power with you. Select a domain from ambition, cities, darkness, fire, nature, or sun. You gain an initial domain spell for that domain. If you don\'t already have one, you gain a focus pool of 1 Focus Point, which you can regain using the Refocus activity to pray to the Old Sun Gods; if you already have a focus pool, increase the number of Focus Points in your focus pool by 1. Your Bright Lion focus spells are divine spells; you become trained in divine spell attacks and spell DCs, using Charisma as your spellcasting ability score.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bright Lion Dedication'],
    mechanics: 'Choose domain (ambition/cities/darkness/fire/nature/sun): gain initial domain spell. Focus pool 1 FP (or +1). Trained divine spells (Cha). Repeatable.',
    subChoices: { label: 'Choose a domain', options: [
      { id: 'ambition', name: 'Ambition' },
      { id: 'cities', name: 'Cities' },
      { id: 'darkness', name: 'Darkness' },
      { id: 'fire', name: 'Fire' },
      { id: 'nature', name: 'Nature' },
      { id: 'sun', name: 'Sun' },
    ] },
  },
  {
    id: 'bright-lion-lions-might',
    name: 'Lion\'s Might',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve trained with the weapons of the Bright Lions. You gain access to lion scythes and sun slings. Whenever you gain a class feature that grants you expert or greater proficiency in certain weapons, you also gain that proficiency rank with lion scythes and sun slings.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bright Lion Dedication'],
    mechanics: 'Access to lion scythes + sun slings. Class weapon prof increases extend to these weapons.',
  },
  {
    id: 'bright-lion-warding-light',
    name: 'Warding Light',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain a tattoo that serves as a special ward to defend you against Walkena\'s forces. The tattoo allows you to cast the light cantrip as a divine innate spell at will. The cantrip is heightened to a spell level equal to half your level rounded up. If you die, the tattoo immediately casts gentle repose on your corpse, heightened to the same spell level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bright Lion Dedication'],
    mechanics: 'Tattoo: light cantrip divine innate at will. On death: auto-casts gentle repose on corpse (heightened).',
  },
  {
    id: 'bright-lion-suns-fury',
    name: 'Sun\'s Fury',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'The Old Sun Gods have granted you a gift in your fight against Walkena. You gain the sun\'s fury focus spell. If you don\'t already have one, you gain a focus pool of 1 Focus Point, which you can regain using the Refocus activity to pray to the Old Sun Gods; if you already have a focus pool, increase the number of Focus Points in your focus pool by 1. Your Bright Lion focus spells are divine spells; when you gain this feat, if you aren\'t already, you become trained in divine spell attacks and spell DCs, using Charisma as your spellcasting ability score.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bright Lion Dedication'],
    mechanics: 'Gain sun\'s fury focus spell. Focus pool 1 FP (or +1). Trained divine spells (Cha) if not already.',
  },
  {
    id: 'bright-lion-elude-the-divine',
    name: 'Elude the Divine',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You are able to escape inquisitions involving divine magic, allowing you to blend in well in Mzali but also to avoid unwanted attention in other oppressive theocracies. You gain the Slippery Secrets skill feat, and its benefits also apply against divination effects that attempt to discern your deity. When using Slippery Secrets against a divine divination, you gain a +2 circumstance bonus, and on a critical success, the divination reveals false information appropriate to your false persona, rather than nothing.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bright Lion Dedication'],
    mechanics: 'Gain Slippery Secrets (extends to deity divination). +2 circumstance vs divine divination; crit success → false info.',
  },
  {
    id: 'bright-lion-lions-fury',
    name: 'Lion\'s Fury',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain access to the lion scythe\'s and sun sling\'s critical specialization effects.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lion\'s Might'],
    mechanics: 'Gain lion scythe + sun sling critical specialization effects.',
  },
  {
    id: 'bright-lion-greater-sun-blessing',
    name: 'Greater Sun Blessing',
    source: 'Bright Lion (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your connection to the Old Sun Gods grows stronger. You gain an advanced domain spell from a domain you chose with Blessing of the Sun Gods. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Blessing of the Sun Gods'],
    mechanics: 'Gain advanced domain spell (from Blessing of the Sun Gods domain). +1 Focus Point. Repeatable (different domain each time).',
  },
];

// ══════════════════════════════════════════════════════════
// COMBINED EXPORT
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_LEGACY_LO6: FeatEntry[] = [
  ...BUTTERFLY_BLADE_FEATS,
  ...GHOST_EATER_FEATS,
  ...GRAY_GARDENER_FEATS,
  ...BRIGHT_LION_FEATS,
];
