import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Lost Omens: Magaambyan Attendant,
// Pathfinder Agent, Scrollmaster, Spellmaster
// Character Guide / World Guide
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// MAGAAMBYAN ATTENDANT  (Character Guide pg. 101)
// ──────────────────────────────────────────────────────────

export const MAGAAMBYAN_ATTENDANT_FEATS: FeatEntry[] = [
  {
    id: 'magaambyan-attendant-dedication',
    name: 'Magaambyan Attendant Dedication',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You gain the ability to cast a single arcane or primal cantrip of your choice. You become trained in that tradition\'s spell DCs and spell attack rolls (Int for arcane, Wis for primal). Become trained in Arcana or Nature, or expert if already trained. Choose affiliation: Cascade Bearers, Emerald Boughs, Rain-Scribes, Tempest-Sun Mages, or Uzunjati.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Arcana or Nature', 'Member of the Magaambya of attendant rank'],
    mechanics: 'Uncommon. Gain 1 arcane/primal cantrip. Trained spell DCs/attacks. Trained Arcana/Nature (or expert). Choose branch affiliation.',
    subChoices: { label: 'Choose branch affiliation', options: [
      { id: 'cascade-bearers', name: 'Cascade Bearers' },
      { id: 'emerald-boughs', name: 'Emerald Boughs' },
      { id: 'rain-scribes', name: 'Rain-Scribes' },
      { id: 'tempest-sun', name: 'Tempest-Sun Mages' },
      { id: 'uzunjati', name: 'Uzunjati' },
    ] },
  },
  {
    id: 'magaambyan-attendant-mask-familiar',
    name: 'Mask Familiar',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your mask takes on a personality of its own, serving as your familiar. Detaching or reattaching is a 2-action activity. In mask form, it can hide its supernatural qualities (mask freeze: +4 circumstance to Deception DC against active observation).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication'],
    mechanics: 'Mask becomes familiar. 2-action to detach/reattach. Mask freeze: +4 Deception DC vs observation.',
  },
  {
    id: 'magaambyan-attendant-adaptive-mask-familiar',
    name: 'Adaptive Mask Familiar',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your mask familiar adapts quickly to material form, allowing it to gain more familiar and master abilities. You select four master and familiar abilities each day instead of two.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Mask Familiar'],
    mechanics: '4 familiar/master abilities per day instead of 2.',
  },
  {
    id: 'magaambyan-attendant-cascade-bearers-flexibility',
    name: 'Cascade Bearer\'s Flexibility',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You call upon your Cascade Bearer training to adjust a spell. Until end of turn, gain a single metamagic feat from druid or wizard class, level req no more than half your level.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 'free',
    prerequisites: ['Magaambyan Attendant Dedication', 'Cascade Bearers affiliation'],
    mechanics: 'Free action, 1/day. Before acting on turn. Gain 1 druid/wizard metamagic feat (\u2264 half level) until end of turn.',
  },
  {
    id: 'magaambyan-attendant-emerald-boughs-accustomation',
    name: 'Emerald Boughs Accustomation',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you Subsist with Society, crit fail becomes fail; success becomes crit success; crit success feeds an extra creature. Recall Knowledge about cultural practices: crit fail becomes fail.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication', 'Emerald Boughs affiliation', 'Expert in Society'],
    mechanics: 'Improved Society Subsist (crit fail\u2192fail, success\u2192crit, crit\u2192extra creature). Cultural RK: crit fail\u2192fail.',
  },
  {
    id: 'magaambyan-attendant-rain-scribe-sustenance',
    name: 'Rain-Scribe Sustenance',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Don\'t need to eat or drink; 6 hours rest to feel well rested. Must still rest 8 hours for daily prep. Can stay awake while resting (full benefits without sleep), but loses sustenance benefits for 1 week after.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication', 'Rain-Scribes affiliation'],
    mechanics: 'No food/drink needed. 6 hours rest. Can rest without sleeping (loses benefits 1 week).',
  },
  {
    id: 'magaambyan-attendant-tempest-sun-redirection',
    name: 'Tempest-Sun Redirection',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'If next action is Cast a Spell that damages creatures, select any targets and reduce damage by spell level. Until next turn, when those targets damage you, reduce by 2\u00d7 spell level.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 1,
    prerequisites: ['Magaambyan Attendant Dedication', 'Tempest-Sun Mages affiliation'],
    mechanics: '1-action metamagic. Reduce spell damage to selected targets by spell level. Those targets\' damage to you reduced by 2\u00d7 spell level until next turn.',
  },
  {
    id: 'magaambyan-attendant-uzunjati-storytelling',
    name: 'Uzunjati Storytelling',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Roll a check with an expert Recall Knowledge skill using Perform result entry. Might influence Diplomacy DCs vs observers.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Skill'],
    actionCost: 1,
    prerequisites: ['Magaambyan Attendant Dedication', 'Uzunjati affiliation', 'Master in a Recall Knowledge skill'],
    mechanics: '1-action. Roll RK skill (expert+) using Perform results. May affect Diplomacy DCs.',
  },
  {
    id: 'magaambyan-attendant-cascade-bearers-spellcasting',
    name: 'Cascade Bearer\'s Spellcasting',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Select halcyon spells from divine/occult lists in addition to arcane/primal. Gain a halcyon cantrip and 1st-level halcyon spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication', 'Cascade Bearers affiliation'],
    mechanics: 'Halcyon spells from all 4 traditions. Gain 1 halcyon cantrip + 1st-level spell.',
  },
  {
    id: 'magaambyan-attendant-emerald-boughs-hideaway',
    name: 'Emerald Boughs Hideaway',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Create small extradimensional space (like type I bag of holding). Holds 1 object up to highest mental ability modifier Bulk. Free action envision to retrieve. Only you can access it. Dispel magic expels contents. Reforms when conscious.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication', 'Emerald Boughs affiliation'],
    mechanics: 'Extradimensional space. 1 object \u2264 highest mental mod Bulk. Free action retrieval. Only you can access.',
  },
  {
    id: 'magaambyan-attendant-rain-scribe-mobility',
    name: 'Rain-Scribe Mobility',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Surround yourself in Rain-Scribe magic and Stride twice; difficult terrain doesn\'t reduce Speed. Clears difficult terrain in entered squares until next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Magaambyan Attendant Dedication', 'Rain-Scribes affiliation'],
    mechanics: '2-action. Stride twice ignoring difficult terrain. Clears difficult terrain in squares until next turn.',
  },
  {
    id: 'magaambyan-attendant-tempest-sun-shielding',
    name: 'Tempest-Sun Shielding',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Expend a spell slot to reduce triggering damage by 4\u00d7 slot level when you or an ally within 30 feet takes damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Tempest-Sun Redirection'],
    mechanics: 'Reaction. Trigger: you/ally within 30 ft takes damage. Expend spell slot: reduce damage by 4\u00d7 slot level.',
  },
  {
    id: 'magaambyan-attendant-uzunjati-recollection',
    name: 'Uzunjati Recollection',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Recall Knowledge with master skill, then use Uzunjati Storytelling with same skill. +1 circumstance to Storytelling check.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 1,
    prerequisites: ['Uzunjati Storytelling', 'Master in a Recall Knowledge skill'],
    mechanics: '1-action. Recall Knowledge (master) + Uzunjati Storytelling in one action. +1 circumstance to Storytelling.',
  },
  {
    id: 'magaambyan-attendant-adept-storyteller',
    name: 'Adept Storyteller',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Use Recall Knowledge skill proficiency to meet Performance feat prerequisites. Gain 2 Performance skill feats of 7th level or lower.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Uzunjati Storytelling', 'Master in a Recall Knowledge skill'],
    mechanics: 'Use RK skill rank for Performance feat prereqs. Gain 2 Performance skill feats (\u2264 7th level).',
  },
  {
    id: 'magaambyan-attendant-cautious-word',
    name: 'Cautious Word',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When an enemy hits you with a Strike and you can\'t cast shield (because you used Shield Block with it this turn), immediately cast shield and gain the AC bonus anyway. Become slowed 1 for 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Uzunjati Storytelling', 'Ability to cast shield'],
    mechanics: 'Free action, 1/round. Trigger: hit by Strike when shield unavailable. Cast shield anyway. Slowed 1 for 1 round.',
  },
  {
    id: 'magaambyan-attendant-janatimos-lessons',
    name: 'Janatimo\'s Lessons',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When using Uzunjati Recollection in combat and succeeding at both checks, allies get +1 circumstance to next attack, save, and AC vs that creature. Crit success on both: +1 to all attacks, saves, AC vs creature for 2 rounds.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Uzunjati Recollection'],
    mechanics: 'Rare. Uzunjati Recollection in combat: both succeed \u2192 allies +1 attack/save/AC vs creature. Both crit \u2192 +1 all for 2 rounds.',
  },
  {
    id: 'magaambyan-attendant-crusaders-masquerade',
    name: 'Crusader\'s Masquerade',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Become concealed, allowing Hide and Sneak without cover. Lasts while only taking surreptitious actions (Hide, Sneak, Recall Knowledge, Command familiar). Requires wearing mask familiar in mask form.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Skill'],
    actionCost: 1,
    prerequisites: ['Mask Familiar', 'Expert in Stealth'],
    mechanics: '1-action. Become concealed (Hide/Sneak w/o cover). Ends on hostile/non-surreptitious actions. Requires mask worn.',
  },
  {
    id: 'magaambyan-attendant-faith-in-the-fallen',
    name: 'Faith in the Fallen',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Gain spirit dwelling. Daily prep attracts 1 spirit wisp. Gain wisp when haunt/incorporeal undead destroyed within 30 ft. Spirit Sanctification: 1-action (concentrate, spellshape), cost 1 wisp. If next action is halcyon spell, +1 status saves + resist void = spell rank for 1 round.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magaambyan Attendant Dedication'],
    mechanics: 'Uncommon. Spirit dwelling attracts wisps (daily prep + destroyed haunts/incorporeal within 30 ft). Spirit Sanctification: 1-action, 1 wisp \u2192 +1 saves + void resist = halcyon spell rank, 1 round.',
  },
  {
    id: 'magaambyan-attendant-i-knew-the-heroes',
    name: 'I Knew the Heroes',
    source: 'Magaambyan Attendant (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'When using Uzunjati Recollection with legendary skill, +1 circumstance to Recall Knowledge check and +2 circumstance to Storytelling (up from +1).',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Uzunjati Recollection', 'Legendary in a Recall Knowledge skill'],
    mechanics: 'Legendary RK skill: +1 circumstance to RK, +2 circumstance to Storytelling (from Uzunjati Recollection).',
  },
];

// ──────────────────────────────────────────────────────────
// PATHFINDER AGENT  (World Guide pg. 23)
// ──────────────────────────────────────────────────────────

export const PATHFINDER_AGENT_FEATS: FeatEntry[] = [
  {
    id: 'pathfinder-agent-dedication',
    name: 'Pathfinder Agent Dedication',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Become trained in 1 skill (or expert if trained). Trained in Pathfinder Lore (or expert). Untrained skill proficiency bonus equals your level instead of 0. Gain access to wayfinders.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Member of the Pathfinder Society'],
    mechanics: 'Uncommon. Trained 1 skill (or expert). Pathfinder Lore trained/expert. Untrained proficiency = level. Access wayfinders.',
  },
  {
    id: 'pathfinder-agent-careful-explorer',
    name: 'Careful Explorer',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Even if you aren\'t Searching, you get a check to find traps that normally require you to Search. Must meet other requirements.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Find traps without Searching. Must meet other requirements.',
  },
  {
    id: 'pathfinder-agent-dead-reckoning',
    name: 'Dead Reckoning',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You immediately intuit which direction is north.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Skill'],
    actionCost: 2,
    prerequisites: ['Pathfinder Agent Dedication', 'Trained in Survival'],
    mechanics: '2-action. Instantly know which direction is north.',
  },
  {
    id: 'pathfinder-agent-deft-cooperation',
    name: 'Deft Cooperation',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you successfully Aid an attack/AC, gain +1 circumstance to same vs that enemy until end of next turn. When you Aid a skill check and attempt same skill check next turn, gain +1 circumstance.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Successful Aid: gain +1 circumstance to same roll type until end of next turn.',
  },
  {
    id: 'pathfinder-agent-environmental-explorer',
    name: 'Environmental Explorer',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Even if you aren\'t Searching, you can attempt a check to find environmental hazards that normally require Searching.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Find environmental hazards without Searching.',
  },
  {
    id: 'pathfinder-agent-observant-explorer',
    name: 'Observant Explorer',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can attempt a check to notice hidden creatures attempting to Avoid Notice nearby even if you aren\'t actively Searching.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Notice hidden creatures without Searching.',
  },
  {
    id: 'pathfinder-agent-remember-your-training',
    name: 'Remember Your Training',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Recall Knowledge about a creature you can see, adding level as proficiency bonus if untrained. Failure (not crit fail) becomes success.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: '1-action, 1/day. RK with level as untrained bonus. Failure \u2192 success.',
  },
  {
    id: 'pathfinder-agent-spiritual-explorer',
    name: 'Spiritual Explorer',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Even if you aren\'t Searching, you can attempt a check to find haunts that normally require you to Search.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Find haunts without Searching.',
  },
  {
    id: 'pathfinder-agent-thorough-reports',
    name: 'Thorough Reports',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Track creatures you identify with Recall Knowledge. +2 circumstance on later Recall Knowledge checks against them. Learn extra fact on success.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Track identified creatures. +2 circumstance RK vs previously identified types. Extra fact on success.',
  },
  {
    id: 'pathfinder-agent-watch-and-learn',
    name: 'Watch and Learn',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When an ally succeeds or critically succeeds at a STR/DEX skill check you\'re untrained in, for 1 minute, add level as proficiency bonus to that skill (doesn\'t allow trained actions unless otherwise able).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Reaction. Trigger: ally succeeds STR/DEX skill check. 1 min: add level as proficiency to that skill.',
  },
  {
    id: 'pathfinder-agent-wayfinder-resonance-tinkerer',
    name: 'Wayfinder Resonance Tinkerer',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Choose 1 cantrip from any tradition. Cast as innate spell at will. Can Activate wayfinder (1-action envision) to transform it into nondescript pin or brooch for 1 hour.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Choose 1 cantrip (any tradition) as innate at will. 1-action: disguise wayfinder as pin/brooch (1 hour).',
    subChoices: { label: 'Choose cantrip tradition', options: [
      { id: 'arcane', name: 'Arcane', description: 'Choose a cantrip from the arcane tradition' },
      { id: 'divine', name: 'Divine', description: 'Choose a cantrip from the divine tradition' },
      { id: 'occult', name: 'Occult', description: 'Choose a cantrip from the occult tradition' },
      { id: 'primal', name: 'Primal', description: 'Choose a cantrip from the primal tradition' },
    ] },
  },
  {
    id: 'pathfinder-agent-archaeologists-warning',
    name: 'Archaeologist\'s Warning',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When about to roll Perception, Society, or Thievery for initiative, warn companions, granting +1 circumstance to their initiative rolls. Gains visual or auditory trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Free action. Trigger: roll initiative (Perception/Society/Thievery). Allies +1 circumstance to initiative.',
  },
  {
    id: 'pathfinder-agent-craft-facsimile',
    name: 'Craft Facsimile',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Spend 1 minute to create a facsimile of an object of 1 Bulk or less. Same shape and Bulk; passes casual inspection but not close examination.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Expert in Crafting', 'Pathfinder Agent Dedication'],
    mechanics: '1 minute. Create facsimile of \u2264 1 Bulk object. Passes casual inspection only.',
  },
  {
    id: 'pathfinder-agent-discerning-strike',
    name: 'Discerning Strike',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Strike a target you successfully identified with Recall Knowledge this combat. Success: +1d6 precision damage. If creature type previously recorded via Thorough Reports, also 1 persistent bleed. Target immune 1 day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Pathfinder Agent Dedication', 'Thorough Reports'],
    mechanics: '1-action Strike. +1d6 precision if RK identified. +1 persistent bleed if recorded (Thorough Reports). Immune 1 day.',
  },
  {
    id: 'pathfinder-agent-forced-entry',
    name: 'Forced Entry',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'No penalty to Force Open without crowbar. Success on Force Open becomes critical success.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Expert in Athletics', 'Pathfinder Agent Dedication'],
    mechanics: 'No crowbar penalty for Force Open. Success \u2192 crit success.',
  },
  {
    id: 'pathfinder-agent-westyrs-wayfinder-repository',
    name: 'Westyr\'s Wayfinder Repository',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'During daily prep, store one 1st-level spell in wayfinder. Cast from wayfinder; expended after use.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication', 'Wayfinder Resonance Tinkerer'],
    mechanics: 'Daily prep: store 1st-level spell in wayfinder. Cast from it; expended after.',
  },
  {
    id: 'pathfinder-agent-diverse-recognition',
    name: 'Diverse Recognition',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'After successfully using Recall Knowledge against a creature with a master skill, attempt Recall Knowledge against a different creature using the same skill.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'free',
    prerequisites: ['Pathfinder Agent Dedication', 'Master in a skill used to Recall Knowledge'],
    mechanics: 'Free action, 1/round. After successful RK (master): attempt RK on different creature with same skill.',
  },
  {
    id: 'pathfinder-agent-recognize-threat',
    name: 'Recognize Threat',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When your first turn of an encounter begins and you can see a creature, attempt a Recall Knowledge check against the triggering creature.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'free',
    prerequisites: ['Master in a Recall Knowledge skill', 'Pathfinder Agent Dedication'],
    mechanics: 'Free action. Trigger: first turn, see creature. Attempt RK (master skill).',
  },
  {
    id: 'pathfinder-agent-snap-out-of-it',
    name: 'Snap Out of It!',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Medicine check on adjacent ally who is fascinated, frightened, stunned, or stupefied. Choose condition; DC equals the effect\'s DC. Crit success: reduce by 2 (fascinated ends). Success: reduce by 1 (fascinated ends). Crit fail: increase by 1.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 2,
    prerequisites: ['Master in Medicine', 'Pathfinder Agent Dedication'],
    mechanics: '2-action Medicine vs effect DC on adjacent ally. Reduce fascinated/frightened/stunned/stupefied. Crit: \u20132, Success: \u20131, Crit Fail: +1.',
  },
  {
    id: 'pathfinder-agent-wayfinder-resonance-infiltrator',
    name: 'Wayfinder Resonance Infiltrator',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Once per day, activate wayfinder to cast illusory disguise as 2nd-level arcane innate. Also: 1-action envision to transform wayfinder into replica badge of membership (1 hour).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication', 'Wayfinder Resonance Tinkerer'],
    mechanics: '1/day: illusory disguise (2nd-level arcane innate) via wayfinder. 1-action: wayfinder \u2192 replica badge (1 hour).',
  },
  {
    id: 'pathfinder-agent-eidetic-memorization',
    name: 'Eidetic Memorization',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Quickly memorize writing of 1 page or less. Accurately recreate later with writing kit. Memory lasts until next daily prep. Only 1 memorization at a time.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 3,
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: '3-action. Memorize \u2264 1 page writing. Recreate later. Lasts until daily prep. 1 at a time.',
  },
  {
    id: 'pathfinder-agent-everyone-duck',
    name: 'Everyone Duck!',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you fail, but don\'t critically fail, to Disable a Device on a trap, you set off the trap with precautions. For the next 2 rounds: trap critical success on attack becomes success; anyone\'s critical failure on save becomes failure.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: 'Reaction. Trigger: fail Disable Device on trap. 2 rounds: trap crit attacks \u2192 success; crit fail saves \u2192 failure.',
  },
  {
    id: 'pathfinder-agent-educated-assessment',
    name: 'Educated Assessment',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Attempt Recall Knowledge about a creature; GM uses same secret roll against creature\'s Deception or Stealth DC for Battle Assessment info. Different degrees possible. With Battle Assessment feat, this applies to all Recall Knowledge.',
    implemented: 'full',
    traits: ['Archetype', 'Secret'],
    actionCost: 1,
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: '1-action. RK + Battle Assessment in one check. Same roll vs creature Deception/Stealth DC.',
  },
  {
    id: 'pathfinder-agent-swap-investment',
    name: 'Swap Investment',
    source: 'Pathfinder Agent (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Invest a magic item and remove a previously invested item. Previous item no longer counts against 10-item limit.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pathfinder Agent Dedication'],
    mechanics: '1/day. Invest new item + remove old invested item (doesn\'t count against limit).',
  },
];

// ──────────────────────────────────────────────────────────
// SCROLLMASTER  (Character Guide pg. 113)
// ──────────────────────────────────────────────────────────

export const SCROLLMASTER_FEATS: FeatEntry[] = [
  {
    id: 'scrollmaster-dedication',
    name: 'Scrollmaster Dedication',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'For 24 hours after learning a prominent fact, recall it without a check. +2 circumstance to remember details from current adventure. If you have Thorough Reports and expert in Recall Knowledge skill, the bonus increases to +4.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Expert in any Lore skill', 'Member of the Pathfinder Society affiliated with the School of Scrolls'],
    mechanics: 'Uncommon. Auto-recall prominent facts for 24h. +2 circumstance to remember adventure details. With Thorough Reports (expert): +4 to RK vs creatures.',
  },
  {
    id: 'scrollmaster-foolproof-instructions',
    name: 'Foolproof Instructions',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'During daily prep, select a scroll and instruct an ally in its use. Ally can attempt 1-action manipulate to use scroll (skill check per tradition). Use your level as proficiency bonus and ally\'s highest mental modifier.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'Daily prep: 1 scroll taught to 1 ally. Ally: 1-action manipulate to attempt scroll use.',
  },
  {
    id: 'scrollmaster-innate-magic-intuition',
    name: 'Innate Magic Intuition',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'First successful Recall Knowledge to identify a creature: learn names of 3 highest-level innate spells. +2 circumstance to next save vs innate spell from that creature.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'First RK success: learn 3 highest innate spells. +2 circumstance to next save vs its innate spells.',
  },
  {
    id: 'scrollmaster-lore-seeker',
    name: 'Lore Seeker',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Cast comprehend language, restore senses, and see invisibility as innate spells 1/day each. Same tradition as your spells (or arcane, Int-based). Trained in arcane spell attacks and DCs.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'Innate 1/day: comprehend language, restore senses, see invisibility. Arcane (Int) if no tradition.',
  },
  {
    id: 'scrollmaster-magic-finder',
    name: 'Magic Finder',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Cast detect magic and read aura at will. Cast locate 1/day (magic items only). Same tradition (or arcane, Int). +2 circumstance to disbelieve magic aura and item facade.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'At will: detect magic, read aura. 1/day: locate (magic items). +2 circumstance vs magic aura/item facade.',
  },
  {
    id: 'scrollmaster-transcribe-moment',
    name: 'Transcribe Moment',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Gain transcribe moment focus spell. Focus pool of 1 Focus Point (or +1 if you already have one). Refocus by studying text or recording notes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'Gain transcribe moment focus spell. +1 Focus Point. Refocus via study/notes.',
  },
  {
    id: 'scrollmaster-unravel-mysteries',
    name: 'Unravel Mysteries',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Decipher Writing takes half time. No \u20132 penalty on failure for further attempts.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Master in a Decipher Writing skill', 'Scrollmaster Dedication'],
    mechanics: 'Half time for Decipher Writing. No \u20132 penalty on failure for further attempts.',
  },
  {
    id: 'scrollmaster-bestiary-scholar',
    name: 'Bestiary Scholar',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Choose 1 master skill. Use it to Recall Knowledge about any creature (normally identified by any of those skills). Crit success: +1 circumstance to next attack or save vs that creature.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Master in Arcana, Crafting, Nature, Occultism, or Religion', 'Scrollmaster Dedication'],
    mechanics: 'Choose 1 master skill for all creature RK. Crit success: +1 circumstance to next attack/save vs creature.',
  },
  {
    id: 'scrollmaster-cautious-delver',
    name: 'Cautious Delver',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Cast dispel magic, knock, and resist energy as innate spells 1/day each. Same tradition (or arcane, Int).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'Innate 1/day: dispel magic, knock, resist energy. Arcane (Int) if no tradition.',
  },
  {
    id: 'scrollmaster-font-of-knowledge',
    name: 'Font of Knowledge',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you succeed at Recall Knowledge, gain additional info or context. Crit success: even more at GM\'s discretion.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'Success on RK: extra info. Crit success: even more info (GM discretion).',
  },
  {
    id: 'scrollmaster-masterful-obfuscation',
    name: 'Masterful Obfuscation',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Choose 1 master Recall Knowledge skill. Use it instead of Deception to Lie about facts related to that skill. Crit success convinces even those who heard contradictory info (unless certain from direct experience). Once caught, can\'t use vs that creature again.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Master in a skill with Recall Knowledge action', 'Scrollmaster Dedication'],
    mechanics: 'Choose master RK skill to Lie about related facts (replaces Deception). Crit success: convinces even skeptics.',
  },
  {
    id: 'scrollmaster-determined-lore-seeker',
    name: 'Determined Lore Seeker',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Choose 1 Lore Seeker innate spell; cast 3/day instead of 1. All Lore Seeker spells gain bonuses: comprehend language heightened to 4th; restore senses heightened to half level; see invisibility grants 1-action to see invisible normally until end of next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lore Seeker'],
    mechanics: 'Choose 1 Lore Seeker spell: 3/day. Comprehend language \u2192 4th. Restore senses \u2192 half level. See invisibility: 1-action to see normally.',    subChoices: { label: 'Choose Lore Seeker spell', options: [
      { id: 'comprehend-language', name: 'Comprehend Language', description: 'Heightened to 4th rank' },
      { id: 'restore-senses', name: 'Restore Senses', description: 'Heightened to half your level' },
      { id: 'see-invisibility', name: 'See Invisibility', description: '1-action to see normally' },
    ] },  },
  {
    id: 'scrollmaster-ward-mind',
    name: 'Ward Mind',
    source: 'Scrollmaster (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'When your turn ends and you are affected by a mental effect from a failed (not critically failed) save, ignore that single mental effect until end of next turn. Can only suppress each effect once (even with Cognitive Loophole). Can use even if mental effect prevents reactions.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Scrollmaster Dedication'],
    mechanics: 'Reaction (trigger: turn ends). Ignore 1 mental effect (from failed save) until end of next turn. Works even if reactions prevented.',
  },
];

// ──────────────────────────────────────────────────────────
// SPELLMASTER  (Character Guide pg. 114)
// ──────────────────────────────────────────────────────────

export const SPELLMASTER_FEATS: FeatEntry[] = [
  {
    id: 'spellmaster-dedication',
    name: 'Spellmaster Dedication',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 6,
    description: '+2 circumstance when you Identify Magic with a trained or higher skill. If you have Wayfinder Resonance Tinkerer, you can change that cantrip each day.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Intelligence 14, Wisdom 14, or Charisma 14', 'Ability to cast focus spells', 'Member of the Pathfinder Society affiliated with the School of Spells'],
    mechanics: 'Uncommon. +2 circumstance to Identify Magic (trained+ skill). Resonance Tinkerer cantrip changeable daily.',
  },
  {
    id: 'spellmaster-familiar-form',
    name: 'Familiar Form',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Gain familiar form focus spell. +1 Focus Point.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spellmaster Dedication'],
    mechanics: 'Gain familiar form focus spell. +1 Focus Point.',
  },
  {
    id: 'spellmaster-glyph-expert',
    name: 'Glyph Expert',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: '+2 circumstance to Perception (find magical traps), AC vs magical traps, saves vs magical traps, checks to Disable magical traps. Find magical traps without Searching. Against magical writing traps: success becomes crit success; crit fail becomes failure.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spellmaster Dedication'],
    mechanics: '+2 circumstance vs magical traps (Perception, AC, saves, Disable). Find without Searching. Writing traps: success\u2192crit, crit fail\u2192fail.',
  },
  {
    id: 'spellmaster-surreptitious-spellcaster',
    name: 'Surreptitious Spellcaster',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Gain Conceal Spell wizard feat (not counted as a wizard feat for you). +2 circumstance to Stealth (Conceal Spell) and Deception (conceal verbal components).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spellmaster Dedication'],
    mechanics: 'Gain Conceal Spell. +2 circumstance to Stealth/Deception for concealing spells.',
  },
  {
    id: 'spellmaster-recover-spell',
    name: 'Recover Spell',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'If an enemy disrupted your spell since the beginning of your last turn, regain the disrupted spell; you must immediately Cast it again with your next action. Can change area, targets, action count.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Metamagic'],
    actionCost: 1,
    prerequisites: ['Spellmaster Dedication'],
    mechanics: '1-action metamagic. Recover disrupted spell; must recast immediately with next action.',
  },
  {
    id: 'spellmaster-spellmasters-ward',
    name: 'Spellmaster\'s Ward',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Gain spellmaster\'s ward focus spell. +1 Focus Point.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spellmaster Dedication'],
    mechanics: 'Gain spellmaster\'s ward focus spell. +1 Focus Point.',
  },
  {
    id: 'spellmaster-ward-casting',
    name: 'Ward Casting',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you attempt a flat check for Steady Spellcasting (before rolling), reduce the DC of the flat check from 15 to 10.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Spellmaster Dedication', 'Steady Spellcasting'],
    mechanics: 'Reaction. Reduce Steady Spellcasting flat check DC from 15 to 10.',
  },
  {
    id: 'spellmaster-communal-sustain',
    name: 'Communal Sustain',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Choose one sustained spell an ally within 30 feet has in effect. Ally can Sustain as a free action at the start of their next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Spellmaster Dedication'],
    mechanics: '1-action, 1/round. Ally within 30 ft Sustains their spell as free action at start of next turn.',
  },
  {
    id: 'spellmaster-spellmasters-resilience',
    name: 'Spellmaster\'s Resilience',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Choose a magical tradition. +1 circumstance to saves vs spells and effects of that tradition. Resistance 5 to damage from that tradition\'s spells and effects. Must actually be cast or created with that tradition.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spellmaster Dedication'],
    mechanics: 'Choose tradition. +1 circumstance saves + resist 5 damage vs spells/effects of that tradition.',
    subChoices: { label: 'Choose magical tradition', options: [
      { id: 'arcane', name: 'Arcane' },
      { id: 'divine', name: 'Divine' },
      { id: 'occult', name: 'Occult' },
      { id: 'primal', name: 'Primal' },
    ] },
  },
  {
    id: 'spellmaster-absorb-spell',
    name: 'Absorb Spell',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When you critically succeed on a save vs a foe\'s spell of a level you can cast, absorb it. Spontaneous: cast triggering spell once in 10 min (even if not on list). Prepared: replace 1 prepared spell of same level (must cast in 10 min). Uses your tradition, DC, and stats.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Spellmaster Dedication', 'Spell repertoire or ability to prepare spells'],
    mechanics: 'Reaction, 1/10 min. Trigger: crit succeed save vs foe spell. Spontaneous: cast once/10 min. Prepared: replace 1 spell. Your tradition/stats.',
  },
  {
    id: 'spellmaster-spellmasters-tenacity',
    name: 'Spellmaster\'s Tenacity',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When you critically fail a save vs a foe\'s spell of your chosen tradition, fail instead of critically fail. For 1 minute: Resilience bonus increases to +2 saves and resistance 10.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Spellmaster\'s Resilience'],
    mechanics: 'Reaction, 1/day. Crit fail \u2192 fail vs chosen tradition spell. 1 min: +2 saves + resist 10.',
  },
  {
    id: 'spellmaster-masters-counterspell',
    name: 'Master\'s Counterspell',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'When a creature Casts a spell you have prepared, in a tradition where you have master proficiency, expend a prepared spell or slot of at least the triggering spell level. Attempt to counteract (\u20132 penalty, may be waived if same spell or thematically appropriate).',
    implemented: 'full',
    traits: ['Archetype', 'Abjuration'],
    actionCost: 'reaction',
    prerequisites: ['Spellmaster Dedication', 'Master in spell attack rolls and spell DCs'],
    mechanics: 'Reaction. Expend spell \u2265 trigger level. Counteract (\u20132 penalty, waivable). Master proficiency tradition only.',
  },
  {
    id: 'spellmaster-mobile-magical-combat',
    name: 'Mobile Magical Combat',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'While wielding a melee weapon and having cast a spell requiring at least 1 action this turn, Stride once. If ending within melee reach, make a melee Strike. Can use while Burrowing, Climbing, Flying, or Swimming.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Spellmaster Dedication'],
    mechanics: '1-action Flourish. After casting spell: Stride + melee Strike if in reach. Works with Burrow/Climb/Fly/Swim.',
  },
  {
    id: 'spellmaster-retain-absorbed-spell',
    name: 'Retain Absorbed Spell',
    source: 'Spellmaster (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Spontaneous: cast absorbed spell up to 3 times. Prepared: replace up to 3 prepared spells. Can extend absorption to 1 hour (can\'t use Absorb Spell again until hour passes).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Absorb Spell'],
    mechanics: 'Absorbed spell: 3 casts (spontaneous) or 3 replacements (prepared). Can extend to 1 hour (blocks Absorb Spell).',
  },
];

// ══════════════════════════════════════════════════════════
export const STANDALONE_ARCHETYPE_FEATS_LEGACY_LO3: FeatEntry[] = [
  ...MAGAAMBYAN_ATTENDANT_FEATS,
  ...PATHFINDER_AGENT_FEATS,
  ...SCROLLMASTER_FEATS,
  ...SPELLMASTER_FEATS,
];
