import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Secrets of Magic & Grand Bazaar (Part 1)
// Captivator, Cathartic Mage, Flexible Spellcaster, Geomancer
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// CAPTIVATOR  (Grand Bazaar pg. 120–121)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=133
// ──────────────────────────────────────────────────────────

export const CAPTIVATOR_FEATS: FeatEntry[] = [
  {
    id: 'captivator-dedication',
    name: 'Captivator Dedication',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your ability to captivate others borders on the preternatural. Choose Deception or Diplomacy — you become trained (or expert if already trained). Choose two cantrips from the occult list, each from enchantment or illusion school. You gain Cast a Spell and can cast these as occult innate spells. Trained in occult spell attacks and DCs. Key ability: Charisma. Free hand replaces material components with somatic.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Charisma 14', 'Trained in Deception or Diplomacy'],
    mechanics: 'Choose Deception or Diplomacy (trained/expert). 2 occult cantrips (enchantment/illusion). Occult innate spells. Key: Cha.',
    subChoices: { label: 'Choose a skill', options: [
      { id: 'deception', name: 'Deception', description: 'Become trained (or expert) in Deception' },
      { id: 'diplomacy', name: 'Diplomacy', description: 'Become trained (or expert) in Diplomacy' },
    ] },
  },
  {
    id: 'captivator-basic-spellcasting',
    name: 'Basic Captivator Spellcasting',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your innate ability to fascinate develops into full spellcasting. Choose a 1st-level occult spell from enchantment or illusion. Cast as occult innate. At 6th level gain a 2nd-level spell, at 8th a 3rd-level spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captivator Dedication'],
    mechanics: '1st-level occult innate spell (enchantment/illusion). 6th: +2nd-level. 8th: +3rd-level.',
  },
  {
    id: 'captivator-captivating-intensity',
    name: 'Captivating Intensity',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can use your captivator abilities more often. You can cast each occult innate spell granted by captivator feats one additional time per day. This applies to all levels except your two highest non-cantrip captivator spell levels.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Captivator Spellcasting'],
    mechanics: 'Extra cast/day per captivator spell (except 2 highest levels). Heightened Captivation: 2nd cast at 2 levels lower.',
  },
  {
    id: 'captivator-countercharm',
    name: 'Countercharm',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your enchantments and illusions are so dominant you can counteract similar magic. When a creature Casts a Spell from enchantment or illusion school, you lose an innate non-cantrip spell of the same school and attempt to counteract the triggering spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Basic Captivator Spellcasting'],
    mechanics: 'Reaction. Trigger: creature casts enchantment/illusion spell. Requirement: you have innate non-cantrip of same school. Lose spell to counteract.',
  },
  {
    id: 'captivator-heightened-captivation',
    name: 'Heightened Captivation',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Choose one captivator spell (not your highest level non-cantrip). That spell is heightened to your highest captivator spell level. Cannot later change the chosen spell. Repeatable with different spells.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 'passive',
    prerequisites: ['Captivator Dedication'],
    mechanics: 'Heighten 1 captivator spell to highest level. Repeatable (different spells).',
  },
  {
    id: 'captivator-expert-spellcasting',
    name: 'Expert Captivator Spellcasting',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You learn more powerful spells. Gain a 4th-level occult spell (enchantment/illusion). At 12th: 5th-level. At 14th: 6th-level. Expert in occult spell attacks and DCs.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Captivator Spellcasting'],
    mechanics: '4th-level spell. 12th: +5th. 14th: +6th. Expert proficiency.',
  },
  {
    id: 'captivator-reactive-charm',
    name: 'Reactive Charm',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When targeted by a spell or attack, you cast a 1st-level enchantment spell that takes 2 actions or fewer. This affects the attacker before their action resolves. If charmed, they can choose a different target. Attacker must be in range and a valid target.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Captivator Dedication'],
    mechanics: 'Reaction. Frequency: 1/day. Trigger: targeted by spell/attack. Cast 1st-level enchantment vs attacker before their action.',
  },
  {
    id: 'captivator-effortless-captivation',
    name: 'Effortless Captivation',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You maintain your innate enchantments and illusions with hardly a thought. At the start of your turn, you immediately gain the effects of Sustain a Spell, usable only for enchantment or illusion spells.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 'free',
    prerequisites: ['Captivator Dedication'],
    mechanics: 'Free action. Trigger: your turn begins. Free Sustain a Spell for enchantment/illusion.',
  },
  {
    id: 'captivator-master-spellcasting',
    name: 'Master Captivator Spellcasting',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You master the most powerful enchantments and illusions. Gain a 7th-level occult spell. At 18th: 8th-level. At 20th: 9th-level. Must be enchantment/illusion. Master in occult spell attacks and DCs.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Expert Captivator Spellcasting'],
    mechanics: '7th-level spell. 18th: +8th. 20th: +9th. Master proficiency.',
  },
  {
    id: 'captivator-look-again',
    name: 'Look Again',
    source: 'Captivator (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'If your next action is to cast an innate enchantment or illusion spell and it fails to affect any targets, you don\'t lose the spell. You must recast the same spell on your following turn using the same number of actions; if you can\'t or choose not to, those actions are wasted. After the second casting, you lose the spell regardless.',
    implemented: 'full',
    traits: ['Archetype', 'Metamagic'],
    actionCost: 1,
    prerequisites: ['Captivator Dedication'],
    mechanics: '1 action. Frequency: 1/day. If next innate enchantment/illusion misses all targets, spell isn\'t lost. Must recast next turn or waste actions.',
  },
];

// ──────────────────────────────────────────────────────────
// CATHARTIC MAGE  (Secrets of Magic pg. 194–195)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=97
// ──────────────────────────────────────────────────────────

export const CATHARTIC_MAGE_FEATS: FeatEntry[] = [
  {
    id: 'cathartic-mage-dedication',
    name: 'Cathartic Mage Dedication',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve learned to harness a particular emotion and mix it into your magic. Choose a catharsis emotion. If you don\'t already cast spells from slots, you become a spontaneous caster with one cantrip of your choice (key: Charisma). If you can already cast, you learn one additional cantrip. You gain Catharsis [reaction]: trigger determined by emotion; gain activation effects and emotional fervor for 3 rounds, then suffer emotional fallout. You gain Settle Emotions (10 min concentrate to reset Catharsis).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Charisma 14, or ability to cast spells from spell slots'],
    mechanics: 'Uncommon. Choose catharsis emotion. Spontaneous casting (1 cantrip, Cha) if non-caster. Catharsis [reaction]: activation + 3-round fervor → fallout. Settle Emotions: 10 min to reset.',
    subChoices: { label: 'Choose catharsis emotion', options: [
      { id: 'anger', name: 'Anger', description: 'Activation: bonus damage. Fervor: +speed. Fallout: fatigued.' },
      { id: 'dedication', name: 'Dedication', description: 'Activation: grant ally temp HP. Fervor: +saves. Fallout: off-guard.' },
      { id: 'fear', name: 'Fear', description: 'Activation: frighten foe. Fervor: +Perception. Fallout: frightened.' },
      { id: 'hatred', name: 'Hatred', description: 'Activation: bonus vs target. Fervor: +damage. Fallout: must attack target.' },
      { id: 'joy', name: 'Joy', description: 'Activation: heal self. Fervor: +skill checks. Fallout: stupefied.' },
      { id: 'misery', name: 'Misery', description: 'Activation: sicken foe. Fervor: +saves vs emotion. Fallout: slowed.' },
      { id: 'remorse', name: 'Remorse', description: 'Activation: reduce damage. Fervor: resistance. Fallout: clumsy.' },
    ] },
  },
  {
    id: 'cathartic-mage-basic-spellcasting',
    name: 'Basic Cathartic Spellcasting',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the basic spellcasting benefits. Each time you gain a spell slot of a new level from this archetype, add a spell of that level from your chosen tradition to your repertoire.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Cathartic Mage Dedication'],
    mechanics: 'Basic spellcasting benefits. Add spell to repertoire per new slot level.',
  },
  {
    id: 'cathartic-mage-focus-spell',
    name: 'Cathartic Focus Spell',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You learn the focus spell listed under your emotion\'s entry. You can cast it only while in emotional fervor. If you don\'t already have one, you gain a focus pool of 1 Focus Point. You can Refocus while using Settle Emotions.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Cathartic Mage Dedication'],
    mechanics: 'Emotion focus spell (cast only during fervor). 1 Focus Point (Refocus via Settle Emotions).',
  },
  {
    id: 'cathartic-mage-work-yourself-up',
    name: 'Work Yourself Up',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You concentrate on your mental state, tapping into raw emotional energy. Take your Catharsis reaction, activating it and entering emotional fervor as normal, but the fervor lasts only until end of your turn. Emotional fallout occurs at end of fervor as normal.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 2,
    prerequisites: ['Cathartic Mage Dedication'],
    mechanics: '2 actions. Requirement: reaction available, not prevented from Catharsis. Self-trigger Catharsis; fervor ends at end of turn.',
  },
  {
    id: 'cathartic-mage-expert-spellcasting',
    name: 'Expert Cathartic Spellcasting',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You gain the expert spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Cathartic Spellcasting'],
    mechanics: 'Expert spellcasting benefits.',
  },
  {
    id: 'cathartic-mage-infectious-emotions',
    name: 'Infectious Emotions',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When you use Catharsis, one ally within 30 feet gains the catharsis activation benefits in addition to you. If benefits require an emotional focus, they use your focus (empathic imprint).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Cathartic Mage Dedication'],
    mechanics: 'Catharsis shares activation benefits with 1 ally within 30 ft.',
  },
  {
    id: 'cathartic-mage-master-spellcasting',
    name: 'Master Cathartic Spellcasting',
    source: 'Cathartic Mage (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You gain the master spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Expert Cathartic Spellcasting'],
    mechanics: 'Master spellcasting benefits.',
  },
];

// ──────────────────────────────────────────────────────────
// FLEXIBLE SPELLCASTER  (Secrets of Magic pg. 209)
// Class archetype — single dedication feat
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=99
// ──────────────────────────────────────────────────────────

export const FLEXIBLE_SPELLCASTER_FEATS: FeatEntry[] = [
  {
    id: 'flexible-spellcaster-dedication',
    name: 'Flexible Spellcaster Dedication',
    source: 'Flexible Spellcaster (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You now have four cantrips per day instead of three. At 4th level, you have five cantrips per day instead of four. This is a class archetype that fundamentally changes how a prepared caster works — you gain a spell collection instead of individual slot preparation, with reduced slots per level.',
    implemented: 'full',
    traits: ['Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Flexible spell preparation (prepared caster class feature)'],
    mechanics: 'Class archetype. 4 cantrips/day (5 at 4th). Changes prepared casting to spell collection with reduced slots.',
  },
];

// ──────────────────────────────────────────────────────────
// GEOMANCER  (Secrets of Magic pg. 212–213)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=100
// ──────────────────────────────────────────────────────────

export const GEOMANCER_FEATS: FeatEntry[] = [
  {
    id: 'geomancer-dedication',
    name: 'Geomancer Dedication',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You feel a deep connection to the world — terrain attunement. When you cast a spell with a trait matching your current terrain (aquatic/water, arctic/cold, desert/fire, forest/plant, mountain/earth, plains/plant, sky/air, swamp/plant, underground/earth), you gain that terrain\'s attunement effect. Effects vary: swim Speed, enemy Speed penalties, fatigued, clumsy, physical resistance, temp HP, fly, persistent poison, darkvision+tremorsense.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Nature', 'Ability to cast spells from spell slots', 'At least one spell with air, cold, earth, fire, plant, or water trait'],
    mechanics: 'Terrain attunement. Casting matching-trait spell grants terrain bonus. 9 terrain types with varied effects (buff self or debuff enemies).',
  },
  {
    id: 'geomancer-attunement-shift',
    name: 'Attunement Shift',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You alter your terrain attunement to match a trait of the spell you just cast. This lets you gain attunement benefits for a different terrain than your actual surroundings. Reverts to actual terrain after 1 minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Geomancer Dedication'],
    mechanics: 'Free action. Frequency: 1/10 min. Requirement: previous action cast a spell with air/cold/earth/fire/plant/water. Change attunement to matching terrain. Reverts in 1 min.',
  },
  {
    id: 'geomancer-shared-attunement',
    name: 'Shared Attunement',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you would gain a terrain attunement benefit, you can grant it to one ally within 30 feet instead. No effect if the attunement affects foes instead of granting you a benefit.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Geomancer Dedication'],
    mechanics: 'Grant terrain attunement benefit to 1 ally within 30 ft (self-buff attunements only).',
  },
  {
    id: 'geomancer-rough-terrain-stance',
    name: 'Rough Terrain Stance',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You enter a stance that makes it difficult to move around you. Each square adjacent to you becomes difficult terrain matching your current attunement. You ignore this difficult terrain. Stance ends if you move into a different terrain type.',
    implemented: 'full',
    traits: ['Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Geomancer Dedication', 'Expert in Nature'],
    mechanics: '1 action. Requirement: gained terrain attunement this turn. Adjacent squares = difficult terrain. Self-immune. Ends on terrain change.',
  },
  {
    id: 'geomancer-attuned-stride',
    name: 'Attuned Stride',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can move freely through terrain you\'re attuned to. When you gain a terrain attunement benefit, you ignore difficult terrain in that terrain type until end of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Geomancer Dedication', 'Expert in Nature'],
    mechanics: 'Ignore difficult terrain in attuned terrain type until end of next turn.',
  },
  {
    id: 'geomancer-draw-from-the-land',
    name: 'Draw from the Land',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You pull strength from the surrounding terrain. Gain temporary HP equal to your level for 1 round. If you previously gained plains attunement this turn, combine the temp HP.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Geomancer Dedication', 'Expert in Nature'],
    mechanics: '1 action. Requirement: gained terrain attunement this turn matching actual terrain. Temp HP = level (1 round). Stacks with plains attunement.',
  },
  {
    id: 'geomancer-read-the-land',
    name: 'Read the Land',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You learn the commune with nature ritual if you didn\'t know it. You can perform it with a casting time of 1 hour instead of 1 day and without a secondary caster.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Geomancer Dedication', 'Master in Nature'],
    mechanics: 'Uncommon. Commune with nature ritual: 1 hour (not 1 day), no secondary caster.',
  },
  {
    id: 'geomancer-shifting-terrain',
    name: 'Shifting Terrain',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You cause terrain around you to shift. Each creature in your Rough Terrain Stance difficult terrain must attempt a Reflex save vs your spell DC. Crit Success: unaffected. Success: clumsy 1 (1 round). Failure: clumsy 2 (1 round). Crit Failure: clumsy 2 + prone. Recharge: 1d4 rounds.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Rough Terrain Stance', 'Master in Nature'],
    mechanics: '1 action. Requirement: attuned to actual terrain + in Rough Terrain Stance. Reflex save. Fail: clumsy 2 (1 round). Crit Fail: clumsy 2 + prone. 1d4 round cooldown.',
  },
  {
    id: 'geomancer-terrain-shield',
    name: 'Terrain Shield',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'The land rises to protect you. When a Strike would damage you, gain resistance to physical damage equal to double your level against the triggering Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Geomancer Dedication', 'Master in Nature'],
    mechanics: 'Reaction. Frequency: 1/10 min. Trigger: Strike would damage you. Requirement: gained matching attunement since turn start. Resistance physical = 2×level vs triggering Strike.',
  },
  {
    id: 'geomancer-quickened-attunement',
    name: 'Quickened Attunement',
    source: 'Geomancer (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'If your next action is to Cast a Spell that grants your terrain attunement bonus, reduce the number of actions to cast it by 1 (minimum 1 action). Can\'t use with Quickened Casting in the same round.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Metamagic'],
    actionCost: 'free',
    prerequisites: ['Geomancer Dedication', 'Legendary in Nature'],
    mechanics: 'Free action. Frequency: 1/day. Requirement: previous action was Attunement Shift. Next attunement spell costs 1 fewer action (min 1). Not with Quickened Casting.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_LEGACY_SM1: FeatEntry[] = [
  ...CAPTIVATOR_FEATS,
  ...CATHARTIC_MAGE_FEATS,
  ...FLEXIBLE_SPELLCASTER_FEATS,
  ...GEOMANCER_FEATS,
];
