import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — Guns & Gears
// Artillerist, Beast Gunner, Bullet Dancer,
// Demolitionist, Spellshot, Sterling Dynamo
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// ARTILLERIST  (Guns & Gears pg. 128–129)
// Category: Profession / Core — PFS Limited
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=115
// ──────────────────────────────────────────────────────────

export const ARTILLERIST_FEATS: FeatEntry[] = [
  {
    id: 'artillerist-dedication',
    name: 'Artillerist Dedication',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'If you\'re serving on a siege weapon crew, you and all other members on that crew gain a +2 circumstance bonus to any checks to Load, Aim, move, or Repair the weapon. When you Aim a siege weapon, you can move the weapon\'s aim twice as far as normal.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in martial weapons'],
    mechanics: 'PFS Limited. Entire siege crew gains +2 circumstance bonus to Load/Aim/move/Repair. Your Aim moves twice as far. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'artillerist-named-artillery',
    name: 'Named Artillery',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can spend a full day adjusting and working on a single siege weapon to designate it as your named artillery. The siege weapon gains a +2 circumstance bonus to AC, Fortitude saves, and Reflex saves as well as additional Hit Points equal to twice your level. During daily preparations you must spend at least one hour on maintenance to service it.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Artillerist Dedication', 'Trained in Crafting'],
    mechanics: 'Downtime activity: designate a siege weapon. Named artillery gains +2 circ to AC/Fort/Reflex and +2×level HP. Requires 1 hour daily maintenance. Only one artillerist per siege weapon.',
  },
  {
    id: 'artillerist-shorthanded',
    name: 'Shorthanded',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can operate a siege weapon with fewer than the minimum number of crew, at an increasing penalty. You and your crew take a –2 penalty to checks to Load, Aim, Launch, move, or Repair the weapon for each person below the minimum crew. The maximum number of missing minimum crew members you can handle is 5.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Artillerist Dedication'],
    mechanics: 'Operate siege weapon below minimum crew. –2 penalty per missing crew member to all siege weapon checks (Load/Aim/Launch/move/Repair). Max 5 missing members.',
  },
  {
    id: 'artillerist-cannon-corner-shot',
    name: 'Cannon Corner Shot',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'If you personally contribute an additional Load action to the siege weapon\'s loading, above the minimum, you can change a burst into a line twice as long as the size of the burst, or vice versa (so a 10-foot burst turns into a 20-foot line, or a 20-foot line turns into a 10-foot burst).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Artillerist Dedication'],
    mechanics: 'Spend 1 extra Load action to convert siege weapon burst → line (2× burst length) or line → burst (half line length).',
  },
  {
    id: 'artillerist-field-artillery',
    name: 'Field Artillery',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can Interact with an adjacent mounted siege weapon to increase its Speed by 10 feet for one round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Expert in Crafting'],
    mechanics: 'Also available via Munitions Master archetype. 1-action Interact: adjacent mounted siege weapon gains +10 ft Speed for 1 round.',
  },
  {
    id: 'artillerist-live-ammunition',
    name: 'Live Ammunition',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Loading a creature into a siege weapon requires two additional Load actions, which you must conduct personally. The creature must be willing, unconscious, or restrained throughout the process, and the siege weapon must be physically capable of firing the creature. When you Launch, if the weapon usually targets an area, you target a single 5-foot square instead. The siege weapon deals its normal damage to the target and to the creature fired.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Artillerist Dedication'],
    mechanics: 'Load a willing/unconscious/restrained creature (2 extra Load actions, done personally). On Launch, target a single 5-foot square if weapon normally targets area. Normal damage to target and to creature fired.',
  },
  {
    id: 'artillerist-master-siege-engineer',
    name: 'Master Siege Engineer',
    source: 'Artillerist (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'What you don\'t know about artillery isn\'t worth knowing and your mastery allows you to perform an impossible number of actions as part of a siege weapon\'s crew. You\'re permanently quickened. You can only use the extra action to Aim or Launch a siege weapon.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Artillerist Dedication'],
    mechanics: 'Also available via Munitions Master archetype. Permanently quickened; extra action can only be used to Aim or Launch a siege weapon.',
  },
];

// ──────────────────────────────────────────────────────────
// BEAST GUNNER  (Guns & Gears pg. 130–131)
// Category: Core — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=116
// Interlocks with Spellshot; beast guns are magical
// firearms crafted from hunted creatures.
// ──────────────────────────────────────────────────────────

export const BEAST_GUNNER_FEATS: FeatEntry[] = [
  {
    id: 'beast-gunner-dedication',
    name: 'Beast Gunner Dedication',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'ve bonded to your beast gun and unlocked the first hints of its hidden potential. You treat all beast guns as martial firearms when determining your proficiency with them, even beast guns that are normally advanced weapons. You learn to cast spontaneous spells and gain the Cast a Spell activity. You gain a spell repertoire with one cantrip of your choice from either the arcane or primal spell list (must require a spell attack roll). Your key spellcasting ability is Charisma or Intelligence (chosen when you take this feat). You also gain Spellsling [3-actions]: Cast a Spell (1–2 actions, spell attack) imbued into your beast gun, then Strike — one attack roll resolves both (counts as 2 attacks for MAP, penalty delayed).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication', 'Magical'],
    actionCost: 'passive',
    prerequisites: ['Trained in Arcana and Crafting', 'Expert with at least one type of firearm', 'You own a beast gun and have slain the creature associated with it in a fair hunt'],
    mechanics: 'All beast guns count as martial. Spontaneous arcane/primal casting: 1 cantrip (spell attack required), CHA or INT key. Includes Spellsling [3-actions]: combine spell + Strike (single roll for both, 2 attacks for MAP but penalty delayed). Special: can\'t take another dedication except Spellshot until 2 other spellshot/beast gunner feats. Synergy: if you also have Spell-Woven Shot, free magical ammo activation 1/10 min before Spellsling.',
  },
  {
    id: 'beast-gunner-basic-spellcasting',
    name: 'Basic Beast Gunner Spellcasting',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You\'ve unlocked the first secrets of beast guns, granting you the power of their synergistic magic. You gain the basic spellcasting benefits. Each time you gain a spell slot of a new level from this archetype, add a spell of the appropriate spell level to your repertoire, either a common spell of your chosen tradition or another spell of that tradition you\'ve learned or discovered.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Beast Gunner Dedication'],
    mechanics: 'Grants basic spellcasting benefits (archetype spellcasting progression). Add a spell to repertoire each time you gain a new slot rank.',
  },
  {
    id: 'beast-gunner-call-gun',
    name: 'Call Gun',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You build a powerful magical connection with a chosen gun or crossbow. During your daily preparations, choose a single crossbow or firearm. Until your next daily preparations, you can use the Call Gun action [1-action] to hold aloft a free hand and call the weapon into your hand. As long as the weapon is on the same plane, it appears in your hand.',
    implemented: 'full',
    traits: ['Archetype', 'Magical', 'Teleportation'],
    actionCost: 'passive',
    prerequisites: ['Spellshot Dedication or Beast Gunner Dedication'],
    mechanics: 'Shared feat: Spellshot & Beast Gunner. During daily prep, bond to a firearm/crossbow. 1-action to teleport it to your hand from anywhere on the same plane. Free hand required. PFS Note: Can only be used on a gun in the character\'s possession.',
  },
  {
    id: 'beast-gunner-drain-vitality',
    name: 'Drain Vitality',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You draw out the bestial magic energy within your bonded beast gun to fortify yourself, purge ongoing harm, and bolster your life force. You gain temporary Hit Points equal to your level and attempt a flat check against any ongoing persistent damage, using the DC appropriate for particularly effective assistance. Using this ability depletes the magic within your bonded beast gun, preventing you from using any of its activated abilities until the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Magical', 'Necromancy'],
    actionCost: 1,
    prerequisites: ['Beast Gunner Dedication'],
    mechanics: 'Frequency: once per minute. Requires possession of bonded beast gun. Gain temp HP = your level + flat check vs persistent damage (DC 10, particularly effective). Bonded beast gun\'s activated abilities disabled until end of your next turn.',
  },
  {
    id: 'beast-gunner-expert-spellcasting',
    name: 'Expert Beast Gunner Spellcasting',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'ve learned the deeper secrets of beast guns, making you an expert in the magic they grant you. You gain the expert spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Beast Gunner Spellcasting or Basic Wizard Spellcasting'],
    mechanics: 'Upgrades to expert spellcasting benefits (expert proficiency in spell attack/DC, additional higher-rank spell slots). Cross-archetype prerequisite: Basic Wizard Spellcasting (from Spellshot) also qualifies.',
  },
  {
    id: 'beast-gunner-controlled-bullet',
    name: 'Controlled Bullet',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You create a direct magical connection with your beast gun, allowing you to guide its next shot through the air, steering it to continue to hit target after target. Make a beast gun Strike against a creature within the first range increment. On a hit, the shot tears through the target and continues toward another target you can see (no farther from the previous target than the beast gun\'s range increment). On a hit, you can direct the bullet toward a new target. Continue until you miss. You can\'t strike the same target twice. Each attack counts toward MAP, but don\'t increase your penalty until all attacks resolve.',
    implemented: 'full',
    traits: ['Archetype', 'Evocation', 'Magical'],
    actionCost: 2,
    prerequisites: ['Beast Gunner Dedication'],
    mechanics: 'Frequency: once per day. Chain-shot: Strike within first range increment → on hit, bullet continues to a new target within one range increment of the previous → repeat until miss. Each target once only. MAP doesn\'t increase until all attacks resolve.',
  },
  {
    id: 'beast-gunner-master-spellcasting',
    name: 'Master Beast Gunner Spellcasting',
    source: 'Beast Gunner (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You\'ve learned the final truth of beast guns, making you a master in the magic they grant you. You gain the master spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Expert Wizard Spellcasting or Expert Beast Gunner Spellcasting'],
    mechanics: 'Upgrades to master spellcasting benefits (master proficiency in spell attack/DC, highest-rank spell slots). Cross-archetype prerequisite: Expert Wizard Spellcasting (from Spellshot) also qualifies.',
  },
];

// ──────────────────────────────────────────────────────────
// BULLET DANCER  (Guns & Gears pg. 132)
// Category: Combat Style — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=117
// Access: Home Region of Alkenstar, Dongun Hold, or
// the Shackles (PFS note)
// ──────────────────────────────────────────────────────────

export const BULLET_DANCER_FEATS: FeatEntry[] = [
  {
    id: 'bullet-dancer-dedication',
    name: 'Bullet Dancer Dedication',
    source: 'Bullet Dancer (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You gain familiarity with bayonets, reinforced stocks, martial firearms, and martial combination weapons, treating them as simple weapons for proficiency and abilities from this archetype. You gain access to uncommon combination weapons with a firearm ranged form. You also gain the Bullet Dancer Stance action [1-action] (stance): Requirements: unarmored and wielding a simple firearm or simple combination weapon. While in stance, you can only Strike with bayonets, reinforced stocks, and simple firearms, but you can use Flurry of Blows with these weapons and use monk feats/abilities with them (firearms within half first range increment).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Expert in unarmored defense', 'Trained in unarmed attack'],
    mechanics: 'Access: Home Region of Alkenstar, Dongun Hold, or the Shackles. Martial firearms/combo weapons treated as simple. Includes Bullet Dancer Stance (1-action): enables Flurry of Blows with bayonets/stocks/simple firearms, and monk feats/abilities (firearms within half first range increment). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'bullet-dancer-burn',
    name: 'Bullet Dancer Burn',
    source: 'Bullet Dancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'While in Bullet Dancer Stance, when you successfully Strike with a bayonet or reinforced stock, the next ranged Strike against that opponent doesn\'t trigger reactions that would trigger on a ranged attack (such as Reactive Strike). When you make a successful ranged Strike against an opponent within your melee reach using a firearm, the next reinforced stock or bayonet attack deals an additional 1 fire damage and 1 persistent fire damage per weapon damage die. Benefits expire at end of next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bullet Dancer Dedication'],
    mechanics: 'Two-way combo in Bullet Dancer Stance: (1) Melee hit → next ranged Strike vs same target doesn\'t provoke ranged reactions. (2) Ranged hit within melee reach → next bayonet/stock hit deals +1 fire and +1 persistent fire per weapon damage die. Benefits expire end of next turn.',
  },
  {
    id: 'bullet-dancer-black-powder-blaze',
    name: 'Black Powder Blaze',
    source: 'Bullet Dancer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You learn to take advantage of every shot, flying across the battlefield with the help of your weapon\'s recoil. Stride and use Black Powder Boost. Make a melee Strike with the required weapon at any point during the Black Powder Boost. If you have Bullet Dancer Burn, apply the additional fire damage to the granted Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Black Powder Boost'],
    mechanics: 'Requires wielding a loaded firearm. Stride + Black Powder Boost (Leap with +10 ft from recoil) + melee Strike at any point during the boost. Synergizes with Bullet Dancer Burn for bonus fire damage.',
  },
  {
    id: 'bullet-dancer-reload',
    name: 'Bullet Dancer Reload',
    source: 'Bullet Dancer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You\'ve learned to reload your simple firearms with uncanny grace, the ammunition simply falling into place as though part of a well-practiced kata. You Strike with a simple firearm, and then Interact to reload that same firearm. You don\'t need a free hand to reload your simple firearm in this way.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Bullet Dancer Burn'],
    mechanics: 'Requires Bullet Dancer Stance. 1-action: Strike with simple firearm + free Interact to reload (no free hand needed). Flourish trait (once per turn).',
  },
  {
    id: 'bullet-dancer-ranged-disarm',
    name: 'Ranged Disarm',
    source: 'Bullet Dancer (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When using a simple firearm, you can shoot objects right out of your enemy\'s hands. Attempt to Disarm the target using a ranged attack roll with your simple firearm, instead of attempting an Athletics check against the target\'s Reflex DC.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Bullet Dancer Dedication', 'Trick Shot'],
    mechanics: 'Requires wielding a simple firearm. 1-action Disarm at range using ranged attack roll instead of Athletics vs Reflex DC.',
  },
];

// ──────────────────────────────────────────────────────────
// DEMOLITIONIST  (Guns & Gears pg. 133)
// Category: Combat Style / Core — Uncommon, PFS Limited
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=118
// ──────────────────────────────────────────────────────────

export const DEMOLITIONIST_FEATS: FeatEntry[] = [
  {
    id: 'demolitionist-dedication',
    name: 'Demolitionist Dedication',
    source: 'Demolitionist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become trained in Engineering Lore (expert if already trained). You gain the Set Explosives action [2-actions] (concentrate): attach 1–2 bombs to an inanimate object within your reach, rigged to detonate at a set time (up to 1 minute). Bombs deal their damage and splash damage to the object; combined damage ignores an amount of the object\'s Hardness equal to your level. Adjacent creatures take the bombs\' combined splash damage.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'PFS Limited. Trained in Engineering Lore (or expert if already trained). Set Explosives [2-actions, concentrate]: attach 1–2 bombs, timed detonation up to 1 min. Combined damage ignores Hardness = your level. Adjacent creatures take splash. Only one Set Explosives active at a time. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'demolitionist-safety-measures',
    name: 'Safety Measures',
    source: 'Demolitionist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you have cover from a bomb, you gain resistance to damage caused by that bomb equal to half your level, plus a value equal to the circumstance bonus to AC granted by the cover. You gain these benefits against your own bombs regardless of whether you have cover.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Demolitionist Dedication'],
    mechanics: 'Bomb resistance = half your level + cover\'s circumstance bonus to AC. Against your own bombs, always get this resistance even without cover.',
  },
  {
    id: 'demolitionist-explosive-entry',
    name: 'Explosive Entry',
    source: 'Demolitionist (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'You Set Explosives on a door, window, container, or similar object and immediately detonate them. You can then attempt an Engineering Lore check to Force Open the target. If a bomb would add an item bonus to attack rolls, add that item bonus to your Engineering Lore check. Since you\'re blasting your way in, you can\'t avoid breaking the object — if you roll a critical success, you get a success instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Demolitionist Dedication', 'Master in Engineering Lore'],
    mechanics: 'Set Explosives + immediate detonation + Engineering Lore check to Force Open. Bomb item bonus to attack applies to the check. Critical success → success (object always breaks).',
  },
  {
    id: 'demolitionist-controlled-blast',
    name: 'Controlled Blast',
    source: 'Demolitionist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You maximize the effectiveness of your explosives by controlling every possible parameter of the blast meticulously. If you have the Directional Bombs feat, you can use it with Set Explosives or Demolition Charge. If you have the bomber research field discovery, you can apply the additional splash damage to one of the bombs when you Set Explosives or use Demolition Charge, and you can apply the increased splash area from Expanded Splash to all the bombs.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Demolitionist Dedication', 'Directional Bombs or Expanded Splash'],
    mechanics: 'Enables Directional Bombs with Set Explosives/Demolition Charge. Also allows bomber field discovery extra splash on one bomb and Expanded Splash\'s increased area on all bombs placed.',
  },
  {
    id: 'demolitionist-collapse-wall',
    name: 'Collapse Wall',
    source: 'Demolitionist (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You detonate pre-placed bombs to bring a wall down on a creature when it moves into the bombs\' splash area. If your bombs deal enough damage to reduce the wall\'s Hit Points below its Broken Threshold, the wall partially collapses on the creature. The creature takes bludgeoning damage equal to the damage dealt to the wall (basic Reflex save; DC = your class DC or spell DC, whichever is higher). On a failure, they must spend an Interact action to dig themselves out; on a critical failure, 2 Interact actions.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Demolitionist Dedication'],
    mechanics: 'Trigger: a creature moves into the bombs\' splash area. Requirements: within 30 ft of rigged wall (Set Explosives or Demolition Charge). If wall goes below Broken Threshold, creature takes bludgeoning = wall damage (basic Reflex, class/spell DC). Failure: 1 Interact to escape; crit failure: 2 Interact.',
  },
];

// ──────────────────────────────────────────────────────────
// SPELLSHOT  (Guns & Gears pg. 140–141)
// Category: Class archetype (Gunslinger — Way of the Spellshot)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=122
// Interlocks with Beast Gunner; counts as Wizard multiclass
// ──────────────────────────────────────────────────────────

export const SPELLSHOT_FEATS: FeatEntry[] = [
  {
    id: 'spellshot-dedication',
    name: 'Spellshot Dedication',
    source: 'Spellshot (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You cast arcane spells like a wizard, gaining a spellbook with four common arcane cantrips and two common 1st-level arcane spells. You prepare spells from your spellbook, preparing two cantrips each day. You\'re trained in the spell attack modifier and spell DC. Your key spellcasting attribute is Intelligence, and they are arcane spells. You become trained in Arcana; if already trained, you become trained in a skill of your choice. This counts as the wizard archetype for the benefits of Basic Wizard Spellcasting.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Way of the Spellshot'],
    mechanics: 'Class archetype: uses Gunslinger class feat slots. Prepared arcane casting (wizard-style): spellbook with 4 cantrips + 2 1st-level spells, prepare 2 cantrips/day. INT key ability. Trained in spell attack/DC. Counts as wizard multiclass dedication. Special: can\'t take another dedication except Beast Gunner until 2 other spellshot/beast gunner feats.',
  },
  {
    id: 'spellshot-spell-woven-shot',
    name: 'Spell-Woven Shot',
    source: 'Spellshot (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You combine your own magic with that of your magical crossbow or firearm. You gain the Spell-Woven Shot activity [3-actions]: Cast a Spell that takes 1–2 actions and requires a spell attack roll, imbuing it into your magic weapon. Make a Strike with that weapon — your attack roll resolves both the Strike and the spell. Counts as two attacks for MAP, but penalty doesn\'t apply until after.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 'passive',
    prerequisites: ['Spellshot Dedication'],
    mechanics: 'Grants Spell-Woven Shot [3-actions]: combine a 1–2 action spell (spell attack required) with a firearm/crossbow Strike. One attack roll resolves both. Counts as 2 attacks for MAP but penalty delayed. Requires a magic weapon.',
  },
  {
    id: 'spellshot-fulminating-shot',
    name: 'Fulminating Shot',
    source: 'Spellshot (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You channel potent magic into your next shot, empowering it with a blast of crackling energy. Choose acid, cold, electricity, or fire. If you hit with your next attack roll using a firearm or crossbow before the end of your turn, you deal 1d6 additional damage of this type. At 12th level, this increases to 2d6, and at 18th level, to 3d6.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 1,
    prerequisites: ['Spellshot Dedication'],
    mechanics: 'Frequency: once per round. Choose energy type (acid/cold/electricity/fire). Next firearm/crossbow hit this turn deals +1d6 energy damage. Scales: 2d6 at 12th, 3d6 at 18th.',
  },
  {
    id: 'spellshot-phase-bullet',
    name: 'Phase Bullet',
    source: 'Spellshot (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You can aim your bullets in additional dimensions, removing all obstacles between you and your target. Attempt a crossbow or firearm Strike against a foe who\'s observed or hidden to you (but not undetected). The ammunition passes through any non-magical barriers or walls (magical barriers and force effects stop it). The shot ignores all cover, the concealed condition, the hidden condition, and circumstance bonuses to AC from shields. It has a +4 status bonus to hit creatures wearing any type of armor. The Strike\'s damage can\'t be reduced with a Shield Block reaction using a non-magical shield.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 1,
    prerequisites: ['Spellshot Dedication'],
    mechanics: 'Frequency: once per day. Dimensional shot: bullet phases through non-magical walls/barriers. Ignores cover, concealed, hidden, and shield AC bonuses. +4 status bonus vs armored targets. Can\'t be non-magical Shield Blocked. Only works on observed or hidden targets (not undetected).',
  },
  {
    id: 'spellshot-black-powder-embodiment',
    name: 'Black Powder Embodiment',
    source: 'Spellshot (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You merge your body with your ammunition, enabling you to travel the same path as your bolt or bullet. Strike a creature with the required weapon. On a success, if the target was within 120 feet, you and all your gear are teleported to an open space of your choice within 10 feet of the target.',
    implemented: 'full',
    traits: ['Archetype', 'Teleportation'],
    actionCost: 2,
    prerequisites: ['Spellshot Dedication', 'Master in Arcana'],
    mechanics: 'Requires wielding loaded magical firearm or crossbow. Strike + teleport combo: hit a creature → teleport yourself + gear to within 10 ft of target (if within 120 ft). Requires master Arcana.',
  },
];

// ──────────────────────────────────────────────────────────
// STERLING DYNAMO  (Guns & Gears pg. 52–53)
// Category: Combat Style / Core — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=165
// ──────────────────────────────────────────────────────────

export const STERLING_DYNAMO_FEATS: FeatEntry[] = [
  {
    id: 'sterling-dynamo-dedication',
    name: 'Sterling Dynamo Dedication',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You obtain a sterling dynamo prosthetic, which allows you to replace or augment a limb, or add a simple new non-prehensile limb (such as a tail). Your prosthesis is optimized for combat, granting you a dynamo melee unarmed attack (brawling group, made of silver). Choose power driver (1d6 B; shove) or percussive striker (1d4 B; agile, finesse). Optionally, make it manually controlled (increases damage die by one size, but requires a free hand). Wind it for 1 minute for 24 hours of operation; enemies can Disable it to reduce time.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'Silver unarmed dynamo attack (brawling group). Choose: power driver (1d6 B, shove) or percussive striker (1d4 B, agile, finesse). Optional manual control: +1 die size but needs free hand. Wind 1 min for 24 hrs; enemies Disable (level = your level) to reduce 1–2 hrs. Dedication-lock enforced by validateDedicationTaking().',
    subChoices: { label: 'Choose dynamo attack', options: [
      { id: 'power-driver', name: 'Power Driver', description: '1d6 bludgeoning, shove' },
      { id: 'percussive-striker', name: 'Percussive Striker', description: '1d4 bludgeoning, agile, finesse' },
    ] },
  },
  {
    id: 'sterling-dynamo-modular',
    name: 'Modular Dynamo',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your dynamo has modular configurations. It gains the modular trait and one new configuration: power driver (1d6 B; shove), percussive striker (1d4 B; agile, finesse), rotating sickle (1d6 S; trip), or entangling barbs (1d6 P; grapple). Manual dynamos can also choose extendable baton (1d4 B; finesse, reach, already factored up). Use Interact to swap configurations with the modular trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Sterling Dynamo Dedication'],
    mechanics: 'Adds modular trait + one new configuration. Options: rotating sickle (1d6 S, trip), entangling barbs (1d6 P, grapple), extendable baton (1d4 B, finesse/reach — manual only). Interact to swap. Special: can be taken multiple times for additional configurations.',
  },
  {
    id: 'sterling-dynamo-piston-punch',
    name: 'Piston Punch',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You lash out with a powerful punch, extending your dynamo to attack two creatures in a row. Make a single bludgeoning or piercing dynamo Strike and compare the attack roll result to the ACs of up to two foes. The first foe must be within your melee reach and the second must be adjacent to the first in a straight line away from you. Roll damage only once and apply to each creature you hit. Counts as two attacks for MAP. Reduces operational time by 1 hour.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Sterling Dynamo Dedication'],
    mechanics: 'Single dynamo Strike (bludgeoning/piercing) vs 2 foes in a line. One attack roll vs both ACs, single damage roll applied to both. Counts as 2 for MAP. Costs 1 hr operational time.',
  },
  {
    id: 'sterling-dynamo-stasian-smash',
    name: 'Stasian Smash',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You\'ve modified your dynamo with Stasian coils. Make a dynamo Strike. On a success, deal an additional 1d12 electricity damage to the target, as well as 1d4 electricity damage to up to two other foes within 10 feet as sparks leap across. If you critically fail, you take 1d12 electricity damage. Counts as two attacks for MAP. At 18th level, increases to 2d12 and 2d4. Reduces operational time by 1 hour.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 2,
    prerequisites: ['Sterling Dynamo Dedication'],
    mechanics: 'Access: You are from Ustalav. Dynamo Strike + 1d12 electricity to target + 1d4 electricity to 2 foes within 10 ft. Crit fail = self-damage 1d12 electricity. Counts as 2 for MAP. Costs 1 hr operational time. Scales: 2d12/2d4 at 18th level.',
  },
  {
    id: 'sterling-dynamo-beast-howl',
    name: 'Beast Dynamo Howl',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You\'ve incorporated beast tech from Arcadia into your dynamo, adding components from terrifying creatures. Attempt Intimidation checks to Demoralize against each enemy within 30 feet; you don\'t take a penalty when you attempt to Demoralize a creature that doesn\'t understand your language. Then, make a dynamo Strike. Reduces operational time by 1 hour.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 2,
    prerequisites: ['Sterling Dynamo Dedication'],
    mechanics: 'Access: You are from Arcadia. Mass Demoralize (all enemies within 30 ft, no language penalty) + dynamo Strike. Costs 1 hr operational time.',
  },
  {
    id: 'sterling-dynamo-golem',
    name: 'Golem Dynamo',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'ve learned the secrets of Jistkan golem prostheses, allowing you to incorporate golem components into your dynamo. You gain a +1 status bonus to saving throws against magic, and your dynamo Strikes become magical.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Sterling Dynamo Dedication'],
    mechanics: 'Access: You are an automaton or are otherwise from the ancient Jistka Imperium. +1 status bonus to saves vs magic. Dynamo Strikes gain the magical trait.',
  },
  {
    id: 'sterling-dynamo-soaring',
    name: 'Soaring Dynamo',
    source: 'Sterling Dynamo (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You\'ve built clockwork wings or jets into your dynamo, allowing you to use your prosthesis to fly. You gain a fly Speed equal to your Speed. Each minute of flight reduces the operational time of your sterling dynamo by 1 hour, measured from the first time you use the Fly action in a given minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Sterling Dynamo Dedication'],
    mechanics: 'Gain fly Speed = your Speed. Each minute of flight costs 1 hour of operational time.',
  },
];

// ──────────────────────────────────────────────────────────
// PISTOL PHENOM  (Guns & Gears pg. 135–136)
// Category: Combat Style / Core — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=120
// Access: Home Region of Alkenstar, Dongun Hold, or
// the Shackles
// ──────────────────────────────────────────────────────────

export const PISTOL_PHENOM_FEATS: FeatEntry[] = [
  {
    id: 'pistol-phenom-dedication',
    name: 'Pistol Phenom Dedication',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You gain the Pistol Twirl gunslinger feat, enabling you to Feint against a foe within the first range increment of a one-handed firearm you\'re wielding by spinning the weapon. Whenever you Feint with a one-handed firearm, you can choose to attempt a Performance check instead of a Deception check.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in at least one type of one-handed firearm', 'Trained in Deception and Performance'],
    mechanics: 'Access: Home Region of Alkenstar, Dongun Hold, or the Shackles. Grants Pistol Twirl (Feint at range with one-handed firearm). Can use Performance instead of Deception for firearm Feints. Counts as Pistol Twirl for prerequisites. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'pistol-phenom-gunpowder-gauntlet',
    name: 'Gunpowder Gauntlet',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Attempt a Performance check against the Will DC of a single target within your one-handed firearm\'s first range increment. Critical Success: The target takes a –2 status penalty to attack rolls against creatures other than you until the beginning of your next turn. Success: The target takes a –1 status penalty to attack rolls against creatures other than you until the beginning of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Pistol Phenom Dedication'],
    mechanics: 'Requires wielding a loaded one-handed firearm. Performance vs Will DC to impose status penalty on foe\'s attacks vs your allies (–1 on success, –2 on crit success) until start of your next turn. Essentially a "taunt" ability.',
  },
  {
    id: 'pistol-phenom-dazzling-bullet',
    name: 'Dazzling Bullet',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Attempt a Performance check against the target creature\'s Will DC and make a ranged firearm Strike against that target. If the Strike deals damage and you succeed at the Performance check, the creature is dazzled for 1 round.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Pistol Phenom Dedication'],
    mechanics: 'Performance check + ranged firearm Strike in 1 action. On hit + Performance success, target is dazzled 1 round. Flourish (once per turn).',
  },
  {
    id: 'pistol-phenom-hot-foot',
    name: 'Hot Foot',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You shoot at the ground near a target\'s feet, causing them to react involuntarily. Make an attack roll against the Reflex DC of a target within your firearm\'s first range increment. Critical Success: The creature can\'t use reactions, is off-guard, and takes a –2 circumstance penalty to Reflex saves until the start of its next turn. Success: The creature can\'t use reactions until the start of its next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Pistol Phenom Dedication'],
    mechanics: 'Requires wielding a loaded firearm. Attack roll vs Reflex DC: success denies reactions; crit success also imposes off-guard + –2 Reflex saves until start of target\'s next turn.',
  },
  {
    id: 'pistol-phenom-verve',
    name: 'Phenom\'s Verve',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'If you critically succeed at a Performance check for Pistol Twirl or a pistol phenom archetype feat, you gain a +1 status bonus to your attack rolls with one-handed firearms and one-handed melee weapons until the end of your turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Pistol Phenom Dedication'],
    mechanics: 'Passive bonus: on critical success on any Performance check from Pistol Twirl or pistol phenom feats, +1 status bonus to attack rolls with one-handed firearms and one-handed melee weapons until end of turn.',
  },
  {
    id: 'pistol-phenom-reach-for-the-sky',
    name: 'Reach for the Sky',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You fire your firearm and then attempt a single Intimidation check to Demoralize each enemy within 30 feet. Creatures who become frightened instinctively put their hands in the air — losing Raised Shield benefits and unable to use reactions or free actions that require hands or held items until each creature\'s next turn. Each creature is then temporarily immune to Reach for the Sky for 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Visual'],
    actionCost: 2,
    prerequisites: ['Pistol Phenom Dedication'],
    mechanics: 'Requires wielding a loaded firearm. Mass Demoralize (all enemies in 30 ft with one Intimidation check). Frightened targets lose Raised Shield and can\'t use hand-requiring reactions/free actions until their next turn. 1-minute temp immunity per creature.',
  },
  {
    id: 'pistol-phenom-whirling-knockdown',
    name: 'Whirling Knockdown',
    source: 'Pistol Phenom (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Make a ranged firearm Strike against a creature within the reach of your melee weapon and then attempt a Performance check against the creature\'s Reflex DC. If the Strike critically succeeds, the target takes a –2 circumstance penalty to its Reflex DC. Critical Success: The target falls prone and takes 2d6 bludgeoning damage. Success: The target falls prone. Critical Failure: You drop your melee weapon.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Pistol Phenom Dedication'],
    mechanics: 'Requires wielding a loaded one-handed firearm and a one-handed melee weapon. Ranged Strike + Performance vs Reflex DC to knock prone. Crit Strike gives –2 to target\'s Reflex DC. Crit Performance success: prone + 2d6 bludgeoning. Crit failure: drop melee weapon.',
  },
];

// ──────────────────────────────────────────────────────────
// UNEXPECTED SHARPSHOOTER  (Guns & Gears pg. 142–143)
// Category: Combat Style / Core — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=123
// Access: Home Region of Alkenstar, Dongun Hold, or
// the Shackles
// ──────────────────────────────────────────────────────────

export const UNEXPECTED_SHARPSHOOTER_FEATS: FeatEntry[] = [
  {
    id: 'unexpected-sharpshooter-dedication',
    name: 'Unexpected Sharpshooter Dedication',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You gain the Accidental Shot activity [2-actions] (fortune, frequency: once per day): Make a Strike with a ranged weapon, rolling the attack and damage twice and using the better results for each. The attack ignores circumstance penalties to the attack roll and any flat check required due to the target being concealed or hidden.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'Access: Home Region of Alkenstar, Dongun Hold, or the Shackles. Grants Accidental Shot (2-actions, fortune, 1/day): ranged Strike rolling attack and damage twice, taking the better. Ignores circumstance penalties and concealment/hidden flat checks. No class prerequisites. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'unexpected-sharpshooter-lucky-escape',
    name: 'Lucky Escape',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your enemy lines up the perfect shot, then you duck down to notice something on the ground. The attacker must roll the attack twice and use the worse result.',
    implemented: 'full',
    traits: ['Archetype', 'Misfortune'],
    actionCost: 'reaction',
    prerequisites: ['Unexpected Sharpshooter Dedication'],
    mechanics: 'Frequency: once per day. Trigger: a creature targets you with an attack (even if you\'re unaware). Force attacker to roll twice and take the worse result (misfortune).',
  },
  {
    id: 'unexpected-sharpshooter-no-hard-feelings',
    name: 'No Hard Feelings',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can choose to add the nonlethal trait to your ranged weapons, making the choice of whether to add the trait or not just before each Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Unexpected Sharpshooter Dedication'],
    mechanics: 'Freely toggle the nonlethal trait on ranged weapon Strikes, decided before each Strike.',
  },
  {
    id: 'unexpected-sharpshooter-close-one',
    name: 'That Was a Close One, Huh?',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'You laugh innocently about the luck of your last shot or how close the attack that just missed you came. Attempt to Demoralize either the foe you hit with Accidental Shot or the foe that missed you due to Lucky Escape. You use Deception instead of Intimidation to attempt the Demoralize check.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 1,
    prerequisites: ['Unexpected Sharpshooter Dedication', 'Master in Deception'],
    mechanics: 'Frequency: once per round. Requires: you used Accidental Shot and hit this turn, or Lucky Escape made an attack miss since your last turn. Demoralize using Deception instead of Intimidation.',
  },
  {
    id: 'unexpected-sharpshooter-unbelievable-luck',
    name: 'Unbelievable Luck',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You demonstrate a greater ability to hit your targets regardless of obstacles. You can use the Accidental Shot activity once per hour instead of once per day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Unexpected Sharpshooter Dedication'],
    mechanics: 'Upgrades Accidental Shot from 1/day to 1/hour.',
  },
  {
    id: 'unexpected-sharpshooter-meant-to-do-that',
    name: 'I Meant to Do That',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Somehow your stray bullet causes an unintended reaction that creates a problem for your enemy. Roll a Deception check to attempt to Shove, Trip, or Disarm the foe you missed.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Unexpected Sharpshooter Dedication', 'Trained in Deception'],
    mechanics: 'Frequency: once per hour. Requires: your previous action was a ranged weapon Strike that missed a foe within 60 ft. Use Deception to attempt Shove, Trip, or Disarm against the missed foe.',
  },
  {
    id: 'unexpected-sharpshooter-unbelievable-escape',
    name: 'Unbelievable Escape',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your ability to narrowly evade danger defies all logic. You can use Lucky Escape once per hour instead of once per day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Unexpected Sharpshooter Dedication'],
    mechanics: 'Upgrades Lucky Escape from 1/day to 1/hour.',
  },
  {
    id: 'unexpected-sharpshooter-chain-reaction',
    name: 'Chain Reaction',
    source: 'Unexpected Sharpshooter (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You fire your gun once, creating a devastating chain of events. Make a Strike with a ranged weapon; if you hit, make another Strike at a target within 30 feet of the first. If you hit the second, Strike a third within 30 feet of the second, and so on until you miss. You can\'t target the same creature twice. Only the first target suffers special bullet effects (e.g., magical ammo), but each target takes the same damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 3,
    prerequisites: ['Unexpected Sharpshooter Dedication'],
    mechanics: 'Frequency: once per 10 minutes. Chain of ranged Strikes: hit → next target within 30 ft → repeat until miss. Each target once only. Only first target gets special ammo effects. GM may change damage type based on narrative of the chain reaction.',
  },
];

// ══════════════════════════════════════════════════════════
// CATALOG — Non-Core Archetype Feats (Guns & Gears)
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_GG: FeatEntry[] = [
  ...ARTILLERIST_FEATS,
  ...BEAST_GUNNER_FEATS,
  ...BULLET_DANCER_FEATS,
  ...DEMOLITIONIST_FEATS,
  ...PISTOL_PHENOM_FEATS,
  ...SPELLSHOT_FEATS,
  ...STERLING_DYNAMO_FEATS,
  ...UNEXPECTED_SHARPSHOOTER_FEATS,
];
