import { FeatEntry } from './featTypes';
import { DOMAIN_OPTIONS } from './subChoiceOptions';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — MORTAL HERALD
// Single massive archetype with 29 feats (Divine Mysteries)
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// MORTAL HERALD  (Divine Mysteries pg. 279–283)
// Category: Mythic — Rare
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=274
// A mortal chosen to serve as a deity's herald in the world.
// Level 12+ Dedication. Massive mythic-tier archetype with
// fly speed, teleportation, avatar form, and immortality.
// ──────────────────────────────────────────────────────────

export const MORTAL_HERALD_FEATS: FeatEntry[] = [
  // ─── Level 12 ───
  {
    id: 'mortal-herald-dedication',
    name: 'Mortal Herald Dedication',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your deity has chosen you as their mortal herald, elevating you above other followers to serve as a direct representative of divine will. You gain a +2 status bonus to Diplomacy and Intimidation checks when representing your deity\'s interests. You gain the Herald\'s Call focus spell. You become an expert in your deity\'s favored weapon. Your sanctification aura registers as overwhelming to effects that detect holy or unholy power.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication', 'Rare'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Religion', 'Worships a deity', 'Your deity has no current herald or their herald has been destroyed'],
    mechanics: '+2 status to Diplomacy + Intimidation for deity matters. Expert in deity\'s favored weapon. Herald\'s Call focus spell (divine). Overwhelming sanctification aura. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'mortal-herald-heralds-armament',
    name: "Herald's Armament",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your deity blesses your weapon with divine power. Your deity\'s favored weapon (or a weapon you wield that is the same type) gains the effects of a holy or unholy rune (matching your deity\'s sanctification). The weapon also gains a +1 status bonus to damage rolls. At 16th level, the status bonus increases to +2.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Deity\'s favored weapon: gains holy or unholy rune effect. +1 status to damage (+2 at 16th).',
  },
  {
    id: 'mortal-herald-divine-emissary',
    name: 'Divine Emissary',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You serve as your deity\'s voice in diplomatic matters. You can speak and understand all languages. When you attempt a Diplomacy check to represent your deity\'s interests, you roll twice and take the better result.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Fortune'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Tongues effect (all languages). Fortune on Diplomacy for deity interests.',
  },
  {
    id: 'mortal-herald-heralds-resilience',
    name: "Herald's Resilience",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Divine power suffuses your body, granting you supernatural resilience. You gain resistance 5 to physical damage. This resistance increases to 10 at 16th level and 15 at 20th level.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Resistance 5 physical (10 at 16th, 15 at 20th).',
  },
  {
    id: 'mortal-herald-empyreal-aura',
    name: 'Empyreal Aura',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Holy radiance surrounds you, bolstering your allies. You emanate a 15-foot aura. Allies within the aura gain a +1 status bonus to saving throws against effects with the unholy trait and resistance 5 to void damage.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Divine', 'Holy'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication', 'Your deity is holy'],
    mechanics: '15-foot aura. Allies: +1 status to saves vs unholy effects + void resistance 5.',
  },
  {
    id: 'mortal-herald-abyssal-aura',
    name: 'Abyssal Aura',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'A dark and terrible presence surrounds you, unnerving enemies. You emanate a 15-foot aura. Enemies within the aura take a -1 status penalty to saving throws against your spells and abilities. Enemies that start their turn in the aura take 2d6 void damage (basic Will save).',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Divine', 'Unholy'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication', 'Your deity is unholy'],
    mechanics: '15-foot aura. Enemies: -1 status to saves vs your effects. Start of their turn: 2d6 void (basic Will).',
  },
  {
    id: 'mortal-herald-mythic-strike',
    name: 'Mythic Strike',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You channel divine power into a devastating blow. Make a Strike with your deity\'s favored weapon. The Strike deals an additional 2d6 spirit damage. If the target is anathema to your deity, the damage increases to 4d6 spirit damage.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Strike with favored weapon + 2d6 spirit damage. 4d6 spirit vs deity\'s anathema targets. Flourish (1/turn).',
  },

  // ─── Level 14 ───
  {
    id: 'mortal-herald-heralds-wings',
    name: "Herald's Wings",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Divine wings sprout from your back, granting you flight. You gain a fly Speed equal to your Speed. The wings\' appearance reflects your deity\'s nature — feathered wings for holy deities, bat-like or spectral wings for unholy deities, or wings of pure energy for neutral deities.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Fly Speed = your Speed. Wings visually match deity\'s nature. Permanent.',
  },
  {
    id: 'mortal-herald-beacon-of-faith',
    name: 'Beacon of Faith',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You shine with divine radiance that inspires your deity\'s followers. Allies within 30 feet who worship the same deity gain a +1 status bonus to attack rolls and saving throws. This is an aura effect and lasts as long as you are conscious.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: '30-foot aura. Allies worshipping same deity: +1 status to attack rolls and saves. While conscious.',
  },
  {
    id: 'mortal-herald-greater-armament',
    name: 'Greater Armament',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your deity\'s blessing on your weapon intensifies. Your Herald\'s Armament weapon gains the effects of a greater striking rune. It also gains an additional property rune based on your deity\'s domains (for example, flaming for fire deities, frost for cold deities).',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ["Herald's Armament"],
    mechanics: 'Herald\'s Armament weapon gains greater striking + domain-appropriate property rune.',
  },
  {
    id: 'mortal-herald-divine-retribution',
    name: 'Divine Retribution',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When enemies dare to strike your deity\'s chosen, divine wrath answers. When a creature within 30 feet deals damage to you, you can call divine retribution. The creature takes 4d6 spirit damage (basic Will save against your class DC or spell DC).',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'reaction',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Trigger: creature within 30 feet deals damage to you. 4d6 spirit damage (basic Will). Frequency: once per round.',
  },
  {
    id: 'mortal-herald-heralds-sanctuary',
    name: "Herald's Sanctuary",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You create a zone of divine sanctuary. You and allies within 10 feet gain the effects of the sanctuary spell for 1 round. Enemies that attempt to attack a sanctified creature must succeed on a Will save or lose the action.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 2,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Frequency: once per 10 minutes. You + allies in 10 feet gain sanctuary (1 round). Enemies: Will save to attack sanctified targets or lose action.',
  },
  {
    id: 'mortal-herald-righteous-condemnation',
    name: 'Righteous Condemnation',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You pronounce divine judgment on a creature that has acted against your deity\'s edicts. Choose a creature within 60 feet that you have witnessed violating your deity\'s anathema. The creature must attempt a Will save against your class DC or spell DC. Failure: frightened 2 and off-guard for 1 minute. Critical Failure: frightened 3, off-guard, and fleeing for 1 round.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Emotion', 'Fear', 'Mental'],
    actionCost: 2,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Target: 60 feet, must have witnessed anathema. Will save. Failure: frightened 2 + off-guard 1 min. Crit fail: frightened 3 + off-guard + fleeing 1 round.',
  },

  // ─── Level 16 ───
  {
    id: 'mortal-herald-heralds-teleportation',
    name: "Herald's Teleportation",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You can teleport to locations sacred to your deity. Once per day, you can cast teleport as a divine innate spell, but only to travel to or from a location sanctified to your deity (such as a temple, shrine, or holy site). At 18th level, you can use this ability twice per day.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Teleportation'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Innate teleport 1/day (2/day at 18th). Must travel to/from deity\'s sanctified location.',
  },
  {
    id: 'mortal-herald-avatar-transformation',
    name: 'Avatar Transformation',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You temporarily transform into a divine avatar of your deity. For 1 minute, you grow to Large size, gain a +10-foot status bonus to Speed, your Strikes deal an additional 2d6 spirit damage, and you gain temporary Hit Points equal to twice your level. When the transformation ends, you are fatigued.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Morph'],
    actionCost: 3,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Frequency: once per day. 1 minute: Large size, +10 Speed, +2d6 spirit on Strikes, temp HP = 2 × level. Fatigued after.',
  },
  {
    id: 'mortal-herald-miracle-worker',
    name: 'Miracle Worker',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Your deity channels powerful healing through you. You can cast heal as a 7th-rank divine innate spell once per day. If you already have the ability to cast heal, you gain an additional 7th-rank spell slot that can be used only for heal.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Innate heal (7th rank) 1/day. If you can already cast heal, gain +1 7th-rank slot for heal only.',
  },
  {
    id: 'mortal-herald-heralds-judgment',
    name: "Herald's Judgment",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You pronounce divine judgment on those who defy your deity. Choose a creature within 60 feet. The creature takes 10d6 spirit damage and must attempt a Will save against your class DC or spell DC. Critical Success: half damage. Success: full damage. Failure: full damage and stunned 1. Critical Failure: double damage and stunned 3.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Incapacitation'],
    actionCost: 2,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Frequency: once per 10 minutes. 60 feet, 10d6 spirit. Will save: failure = stunned 1, crit fail = stunned 3. Incapacitation trait.',
  },
  {
    id: 'mortal-herald-greater-resilience',
    name: 'Greater Resilience',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Your divine resilience expands to protect you from more exotic threats. You gain resistance 10 to two energy types associated with your deity\'s domains. You also gain a +2 status bonus to saving throws against death effects and effects that would drain your life force.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ["Herald's Resilience"],
    mechanics: 'Resistance 10 to two deity-domain energy types. +2 status to saves vs death effects and drain effects.',
  },
  {
    id: 'mortal-herald-divine-weaponry',
    name: 'Divine Weaponry',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You can conjure a weapon of pure divine energy. As a 2-action activity, you create a weapon made of divine force that takes any form you choose. It functions as a +2 greater striking weapon of your chosen type and deals spirit damage instead of its normal damage type. The weapon lasts for 1 minute or until you Dismiss it.',
    implemented: 'full',
    traits: ['Archetype', 'Conjuration', 'Divine'],
    actionCost: 2,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Conjure +2 greater striking weapon of any type. Deals spirit damage. Lasts 1 minute. Dismissible.',
  },

  // ─── Level 18 ───
  {
    id: 'mortal-herald-perfect-armament',
    name: 'Perfect Armament',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your Herald\'s Armament weapon reaches its full divine potential. It gains the effects of a major striking rune and two additional property runes of your choice. The weapon also bypasses all damage resistances and immunities when striking creatures that are anathema to your deity.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Greater Armament'],
    mechanics: 'Herald\'s Armament weapon: major striking + 2 additional property runes. Bypasses all resistance/immunity vs deity anathema creatures.',
  },
  {
    id: 'mortal-herald-aura-of-authority',
    name: 'Aura of Authority',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your divine authority is absolute and unmistakable. Your aura expands to 30 feet. Enemies that enter or start their turn in the aura must succeed on a Will save or become frightened 1 (frightened 2 on a critical failure). A creature that succeeds is temporarily immune for 1 hour.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Divine', 'Emotion', 'Fear', 'Mental'],
    actionCost: 'passive',
    prerequisites: ['Empyreal Aura or Abyssal Aura'],
    mechanics: '30-foot aura. Enemies entering/starting turn: Will save or frightened 1 (crit fail: frightened 2). 1-hour immunity on success.',
  },
  {
    id: 'mortal-herald-divine-immunity',
    name: 'Divine Immunity',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your divine nature protects you from many mortal ailments. You are immune to disease and poison. You no longer need to breathe, eat, or drink, though you can still do so if you wish. You also gain a +4 status bonus to saving throws against death effects.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Immune to disease + poison. No need to breathe/eat/drink. +4 status vs death effects.',
  },
  {
    id: 'mortal-herald-greater-wings',
    name: 'Greater Wings',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your divine wings grow to immense proportions. Your fly Speed increases by 20 feet. You can hover without using an action. When you Fly, you can carry up to 2 willing Medium or smaller creatures with you.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ["Herald's Wings"],
    mechanics: 'Fly Speed + 20 feet. Hover without action. Carry up to 2 willing Medium or smaller creatures while flying.',
  },
  {
    id: 'mortal-herald-heralds-wrath',
    name: "Herald's Wrath",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You unleash a devastating burst of divine energy. All enemies within a 30-foot emanation take 12d6 spirit damage (basic Fortitude save against your class DC or spell DC). Creatures anathema to your deity take 16d6 spirit damage instead. You can then make a Strike against one creature in the area as a free action.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 3,
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Frequency: once per 10 minutes. 30-foot emanation: 12d6 spirit (basic Fort). 16d6 vs anathema. Free Strike on one creature in area.',
  },

  // ─── Level 20 ───
  {
    id: 'mortal-herald-spark-of-immortality',
    name: 'Spark of Immortality',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'Your deity grants you a spark of true immortality. You stop aging and can\'t be magically aged. If you die, your deity restores you to life after 1 week at the nearest sanctified location to your deity, as if by a 10th-rank resurrect spell. Each time this occurs, you lose a permanent level. If you drop to level 0, your deity can no longer restore you.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Stop aging. Auto-resurrect in 1 week at deity\'s sanctified site (as 10th-rank resurrect). Lose 1 permanent level each resurrection. Level 0 = permanent death.',
  },
  {
    id: 'mortal-herald-true-avatar',
    name: 'True Avatar',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'Your avatar transformation reaches its apotheosis. When you use Avatar Transformation, you gain all the following additional benefits: your size becomes Huge, your Strikes deal an additional 4d6 spirit damage (instead of 2d6), you gain a +20-foot status bonus to all Speeds, and you gain 40 temporary Hit Points. The transformation now lasts for 10 minutes instead of 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Morph'],
    actionCost: 'passive',
    prerequisites: ['Avatar Transformation'],
    mechanics: 'Upgrades Avatar Transformation: Huge size, +4d6 spirit on Strikes, +20 Speed, 40 temp HP, 10-minute duration.',
  },
  {
    id: 'mortal-herald-heralds-miracle',
    name: "Herald's Miracle",
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You can channel your deity\'s power to produce miraculous effects. Once per week, you can cast wish as a divine innate spell, but only to produce effects that align with your deity\'s edicts and domains. The GM determines whether a particular wish is appropriate.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Innate wish 1/week. Must align with deity\'s edicts and domains. GM adjudicates appropriateness.',
  },
  {
    id: 'mortal-herald-perfect-herald',
    name: 'Perfect Herald',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You have become the perfect mortal vessel for your deity\'s will. You gain master proficiency in your deity\'s favored weapon. Your sanctification aura acts as a permanent sanctified ground effect in a 60-foot emanation. Allies within the aura gain fast healing 10 while below half their maximum HP.',
    implemented: 'full',
    traits: ['Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Mortal Herald Dedication'],
    mechanics: 'Master in deity\'s favored weapon. 60-foot sanctified ground aura. Allies below half HP: fast healing 10.',
  },
  {
    id: 'mortal-herald-deific-aura',
    name: 'Deific Aura',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'Your aura becomes a manifestation of your deity\'s domain itself. The aura expands to 60 feet. You choose one of your deity\'s domains; the aura gains an additional effect based on the domain. For example: fire domain deals 4d6 fire damage to enemies in the aura, healing domain grants fast healing 5 to allies, death domain deals 4d6 void damage and enfeebles enemies.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Aura of Authority'],
    mechanics: '60-foot aura with domain-based effect. Examples: fire = 4d6 fire to enemies, healing = fast healing 5 to allies, death = 4d6 void + enfeebled to enemies. Choice made at daily prep.',
    subChoices: { label: 'Choose deity domain for aura effect', options: DOMAIN_OPTIONS },
  },
  {
    id: 'mortal-herald-ultimate-judgment',
    name: 'Ultimate Judgment',
    source: 'Mortal Herald (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You pass absolute divine judgment upon a creature. The creature must attempt a Will save against your class DC or spell DC. This effect automatically overcomes the incapacitation trait (functions fully regardless of level). Critical Success: unaffected, immune for 24 hours. Success: 10d6 spirit damage and stunned 1. Failure: 20d6 spirit damage, stunned 3, and drained 1. Critical Failure: 40d6 spirit damage, paralyzed for 1 round, drained 2, and the creature\'s soul is temporarily bound (can\'t be resurrected for 24 hours).',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Incapacitation'],
    actionCost: 3,
    prerequisites: ["Herald's Judgment"],
    mechanics: 'Frequency: once per day. Overcomes incapacitation trait. Will save. Crit fail: 40d6 spirit + paralyzed 1 round + drained 2 + no resurrection for 24 hours.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_MH: FeatEntry[] = [
  ...MORTAL_HERALD_FEATS,
];
