import { FeatEntry } from './featTypes';
import { ARCANE_CANTRIP_OPTIONS } from './subChoiceOptions';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Lost Omens: Living Monolith,
// Student of Perfection, Magic Warrior, Runescarred
// World Guide / Impossible Lands
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// LIVING MONOLITH  (World Guide pg. 59)
// ──────────────────────────────────────────────────────────

export const LIVING_MONOLITH_FEATS: FeatEntry[] = [
  {
    id: 'living-monolith-dedication',
    name: 'Living Monolith Dedication',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve begun to inscribe a magical stone called a ka stone that you will some day tie to your soul. If you fail a recovery check while dying, your dying condition does not increase; if you critically fail, your dying condition increases by only 1. You become trained in Ancient Osirion Lore, or expert if you were already trained.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Ancient Osiriani and Sphinx languages', 'Trained in Crafting'],
    mechanics: 'Uncommon. Fail recovery: dying doesn\'t increase. Crit fail: dying +1 only. Trained Ancient Osirion Lore (or expert).',
  },
  {
    id: 'living-monolith-ka-stone-ritual',
    name: 'Ka Stone Ritual',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You inscribe your true name on your ka stone and embed it in your forehead in a special ritual. The ka stone is an invested item that auto-invests daily. Can\'t be removed without permission or dispelled. Grants +1 item bonus to saves vs death and void effects (+2 at 8th, +3 at 14th, +4 at 20th). Activate (2-action envision) a number of times per day equal to your Living Monolith class feats: cast enlarge on yourself or use later feat abilities.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Living Monolith Dedication', 'A sphinx or living monolith with this feat performs a ritual with you'],
    mechanics: 'Rare. Ka stone: auto-invest, irremovable. +1/+2/+3/+4 item saves vs death/void. Activate 2-action (uses/day = LM feats): enlarge self or later abilities.',
  },
  {
    id: 'living-monolith-stone-blood',
    name: 'Stone Blood',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can selectively stop your bleeding with ease. Reduce the DC of flat checks to stop persistent bleed damage you have from 15 to 10, and you can use a single action that has the concentrate trait to gain an early flat check without physically binding the wounds. You recover naturally from the drained condition twice as quickly as normal.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ka Stone Ritual'],
    mechanics: 'Bleed flat check DC 15 → 10. 1-action (concentrate) for early flat check. Recover drained 2× fast.',
  },
  {
    id: 'living-monolith-fortified-flesh',
    name: 'Fortified Flesh',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your flesh takes on the hardness of stone. You gain resistance to physical damage (except adamantine) equal to your number of class feats from the Living Monolith archetype.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ka Stone Ritual'],
    mechanics: 'Resist physical (except adamantine) = number of Living Monolith class feats.',
  },
  {
    id: 'living-monolith-attunement-to-stone',
    name: 'Attunement to Stone',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You become attuned to the stone around you. When in contact with a stone surface, you gain tremorsense (imprecise) 5 feet along that surface, and you can activate your ka stone to cast meld into stone.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ka Stone Ritual'],
    mechanics: 'On stone: tremorsense (imprecise) 5 ft. Ka stone activation: cast meld into stone.',
  },
  {
    id: 'living-monolith-judgment-of-the-monolith',
    name: 'Judgment of the Monolith',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You can use the oaths bound in your ka stone to compel the truth from the living and the dead. You can activate your ka stone to target a single living creature, causing that creature to experience the effects of being in a zone of truth. You can also activate it with a 10-minute activation (envision) to cast talking corpse.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ka Stone Ritual'],
    mechanics: 'Ka stone activation: zone of truth on 1 creature. 10-min activation: talking corpse.',
  },
  {
    id: 'living-monolith-stone-communion',
    name: 'Stone Communion',
    source: 'Living Monolith (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You gain a unique communion with the earth and stones. You learn the Terran language and you can Activate your ka stone with a 10-minute activation (envision) to cast stone tell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ka Stone Ritual'],
    mechanics: 'Learn Terran. Ka stone 10-min activation: cast stone tell.',
  },
];

// ──────────────────────────────────────────────────────────
// STUDENT OF PERFECTION  (World Guide pg. 83)
// ──────────────────────────────────────────────────────────

export const STUDENT_OF_PERFECTION_FEATS: FeatEntry[] = [
  {
    id: 'student-of-perfection-dedication',
    name: 'Student of Perfection Dedication',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have learned the martial arts techniques of your House of Perfection. You become trained in your choice of Acrobatics or Athletics and Warfare Lore; if you were already trained, you become an expert instead. You gain the Ki Strike monk class feat, which grants you the ki strike ki spell and a focus pool of 1 Focus Point that you can recover using the Refocus activity as a monk does. Your ki spells from Student of Perfection are occult spells.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Powerful fist, or expert in unarmed attacks', 'Member of a House of Perfection'],
    mechanics: 'Uncommon. Trained Acrobatics/Athletics + Warfare Lore (or expert). Gain Ki Strike + 1 FP. Occult tradition.',
  },
  {
    id: 'student-of-perfection-perfect-strike',
    name: 'Perfect Strike',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the perfect strike ki spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Student of Perfection Dedication'],
    mechanics: 'Gain perfect strike ki spell. +1 Focus Point.',
  },
  {
    id: 'student-of-perfection-perfect-weaponry',
    name: 'Perfect Weaponry',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain the Monastic Weaponry monk class feat. You can use melee monk weapons with any Student of Perfection feats or Student of Perfection focus spells that normally require unarmed attacks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Student of Perfection Dedication'],
    mechanics: 'Gain Monastic Weaponry. Monk weapons work with Student of Perfection feats/spells.',
  },
  {
    id: 'student-of-perfection-perfect-ki-adept',
    name: 'Perfect Ki Adept',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You gain the appropriate ki spell for your School of Perfection: unblinking flame revelation for Unblinking Flame, unbreaking wave advance for Unbreaking Waves, unfolding wind rush for Unfolding Wind, or untwisting iron augmentation for Untwisting Iron. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Student of Perfection Dedication'],
    mechanics: 'Gain school-specific ki spell (flame/wave/wind/iron). +1 Focus Point.',
  },
  {
    id: 'student-of-perfection-perfect-resistance',
    name: 'Perfect Resistance',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain resistance equal to half your level to all damage from effects with the appropriate trait for your School of Perfection: fire for Unblinking Flame, water for Unbreaking Waves, air for Unfolding Wind, and earth for Untwisting Iron. After using a Student of Perfection ki spell, the resistance increases to be equal to your level for 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Student of Perfection Dedication'],
    mechanics: 'Resist school element = half level. After ki spell: resist = level for 1 round.',
  },
  {
    id: 'student-of-perfection-perfect-ki-expert',
    name: 'Perfect Ki Expert',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You gain an appropriate ki spell for your School of Perfection: unblinking flame aura for Unblinking Flame, unbreaking wave vapor for Unbreaking Waves, unfolding wind buffet for Unfolding Wind, or untwisting iron roots for Untwisting Iron. Increase the number of Focus Points in your focus pool by 1. You become an expert in occult spell DCs and occult spell attack rolls.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Student of Perfection Dedication'],
    mechanics: 'Gain school-specific ki spell (aura/vapor/buffet/roots). +1 FP. Expert occult spell DCs/attacks.',
  },
  {
    id: 'student-of-perfection-perfect-ki-exemplar',
    name: 'Perfect Ki Exemplar',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You gain an appropriate ki spell for your School of Perfection: unblinking flame emblem for Unblinking Flame, unbreaking wave barrier for Unbreaking Waves, unfolding wind blitz for Unfolding Wind, or untwisting iron pillar for Untwisting Iron. Increase the number of Focus Points in your focus pool by 1. You become an expert in occult spell DCs and occult spell attack rolls.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Student of Perfection Dedication'],
    mechanics: 'Gain school-specific ki spell (emblem/barrier/blitz/pillar). +1 FP. Expert occult DCs/attacks.',
  },
  {
    id: 'student-of-perfection-perfect-ki-grandmaster',
    name: 'Perfect Ki Grandmaster',
    source: 'Student of Perfection (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You gain an appropriate ki spell for your School of Perfection: unblinking flame ignition for Unblinking Flame, unbreaking wave containment for Unbreaking Waves, unfolding wind crash for Unfolding Wind, or untwisting iron break for Untwisting Iron. Increase the number of Focus Points in your focus pool by 1. You become a master in occult spell DCs and occult spell attack rolls.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Perfect Ki Expert', 'or Perfect Ki Exemplar'],
    mechanics: 'Gain school-specific ki spell (ignition/containment/crash/break). +1 FP. Master occult DCs/attacks.',
  },
];

// ──────────────────────────────────────────────────────────
// MAGIC WARRIOR  (World Guide pg. 95)
// ──────────────────────────────────────────────────────────

export const MAGIC_WARRIOR_FEATS: FeatEntry[] = [
  {
    id: 'magic-warrior-dedication',
    name: 'Magic Warrior Dedication',
    source: 'Magic Warrior (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have taken up a nameless mask and sworn the oath of the magic warriors. You become trained in your choice of Arcana or Nature and in Magic Warrior Lore; if already trained, you become an expert. You hide your identity behind a mask representing an animal (corresponding to animal form types). You gain a +1 circumstance bonus to saves against divination effects. If another creature learns your true face or name, you lose archetype abilities. Close allies who knew beforehand don\'t break the taboo unless they share the info. To regain abilities: discard mask, obtain new one of different animal, retrain. Focus spells match your other spell tradition.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Ability to cast focus spells'],
    mechanics: 'Uncommon. Trained Arcana/Nature + Magic Warrior Lore (or expert). +1 circumstance vs divination. Lose abilities if identity revealed. Focus spells match your tradition.',
  },
  {
    id: 'magic-warrior-aspect',
    name: 'Magic Warrior Aspect',
    source: 'Magic Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can alter your form to gain an aspect of the animal your mask represents. You gain the magic warrior aspect focus spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magic Warrior Dedication'],
    mechanics: 'Gain magic warrior aspect focus spell.',
  },
  {
    id: 'magic-warrior-transformation',
    name: 'Magic Warrior Transformation',
    source: 'Magic Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can transform fully into the animal your mask represents. You gain the magic warrior transformation focus spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magic Warrior Dedication'],
    mechanics: 'Gain magic warrior transformation focus spell.',
  },
  {
    id: 'magic-warrior-nameless-anonymity',
    name: 'Nameless Anonymity',
    source: 'Magic Warrior (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your mask protects you further from divination. Once per day, you can cast nondetection on yourself, heightened to the highest level of spell you can cast; the spell ends immediately if your mask is removed for even a moment. The spell is of the same tradition as your focus spells.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magic Warrior Dedication'],
    mechanics: '1/day: nondetection on self (heightened to max spell rank). Ends if mask removed. Same tradition as focus spells.',
  },
];

// ──────────────────────────────────────────────────────────
// RUNESCARRED  (World Guide pg. 119)
// ──────────────────────────────────────────────────────────

export const RUNESCARRED_FEATS: FeatEntry[] = [
  {
    id: 'runescarred-dedication',
    name: 'Runescarred Dedication',
    source: 'Runescarred (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Whether through blood or exposure to rune magic, you have become runescarred, with visible, glowing runes on your body. You become an expert in Arcana and trained in Thassilon Lore (or expert if already trained). Choose one cantrip from the arcane list. One of the runes on your body corresponds to the chosen cantrip, and you can cast it as an innate arcane spell.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Arcana'],
    mechanics: 'Uncommon. Expert Arcana. Thassilon Lore trained/expert. Choose 1 arcane cantrip as innate spell.',
    subChoices: { label: 'Choose an arcane cantrip', options: ARCANE_CANTRIP_OPTIONS },
  },
  {
    id: 'runescarred-spell-runes',
    name: 'Spell Runes',
    source: 'Runescarred (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'The magical runes on your body grant you several magical abilities. Choose a 1st-level arcane spell. You gain a spell rune corresponding to the chosen spell, which you can cast once per day as an innate spell. At 6th level, you gain a spell rune corresponding to a 2nd-level arcane spell, and at 8th level, you gain a spell rune corresponding to a 3rd-level arcane spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Runescarred Dedication'],
    mechanics: '1/day arcane innate: 1st-level spell. +2nd-level at 6th, +3rd-level at 8th.',
  },
  {
    id: 'runescarred-living-rune',
    name: 'Living Rune',
    source: 'Runescarred (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'ve bridged a connection between the runes on your body and the magic of runestones, allowing you to place an armor rune on your living flesh. Your body can hold a single property rune; you can\'t etch a rune that has requirements on armor type/category or that affects the armor instead of its wearer. If you wear armor, you gain the property rune\'s effects in addition to any effects of that armor.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Runescarred Dedication'],
    mechanics: 'Body holds 1 armor property rune (no armor type requirements). Stacks with worn armor.',
  },
  {
    id: 'runescarred-warding-rune',
    name: 'Warding Rune',
    source: 'Runescarred (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your runes provide a warding effect that protects you against a specific school of magic. Choose a school of magic other than divination. You gain a rune on your body corresponding to that school, and you gain a +2 circumstance bonus to all saving throws against effects of that school.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Runescarred Dedication'],
    mechanics: 'Choose school (not divination). +2 circumstance to saves vs that school.',
    subChoices: { label: 'Choose magic school', options: [
      { id: 'abjuration', name: 'Abjuration' },
      { id: 'conjuration', name: 'Conjuration' },
      { id: 'enchantment', name: 'Enchantment' },
      { id: 'evocation', name: 'Evocation' },
      { id: 'illusion', name: 'Illusion' },
      { id: 'necromancy', name: 'Necromancy' },
      { id: 'transmutation', name: 'Transmutation' },
    ] },
  },
  {
    id: 'runescarred-greater-spell-runes',
    name: 'Greater Spell Runes',
    source: 'Runescarred (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You gain more powerful spell runes. You gain a spell rune corresponding to a 4th-level arcane spell. At 12th level, you gain a spell rune corresponding to a 5th-level arcane spell, and at 14th level, you gain a spell rune corresponding to a 6th-level arcane spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Runes'],
    mechanics: '1/day arcane innate: +4th-level spell. +5th at 12th, +6th at 14th.',
  },
];

// ══════════════════════════════════════════════════════════
export const STANDALONE_ARCHETYPE_FEATS_LEGACY_LO4: FeatEntry[] = [
  ...LIVING_MONOLITH_FEATS,
  ...STUDENT_OF_PERFECTION_FEATS,
  ...MAGIC_WARRIOR_FEATS,
  ...RUNESCARRED_FEATS,
];
