import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — C through P (scholars/occult)
// Campfire Chronicler, Necrologist, Psychic Duelist
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// CAMPFIRE CHRONICLER  (Rival Academies pg. 34–35)
// Category: Profession — Common
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=308
// Storytellers who bolster and protect allies through tales.
// ──────────────────────────────────────────────────────────

export const CAMPFIRE_CHRONICLER_FEATS: FeatEntry[] = [
  {
    id: 'campfire-chronicler-dedication',
    name: 'Campfire Chronicler Dedication',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve trained in the art of campfire storytelling, whether to entertain companions, teach valuable lessons, or preserve important stories. You become trained in Performance. If you\'re already trained, you instead become trained in a skill of your choice. You gain the Offer Story action: you spend 10 minutes telling a story from your repertoire to an audience. Each ally who listens gains a +1 circumstance bonus to the skill check most relevant to the story\'s lesson for the next 24 hours.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Society or Performance'],
    mechanics: 'Trained in Performance (or a free skill). Offer Story (10 min): allies who listen gain +1 circ to a relevant skill for 24h. You know 3 stories, +1 per 2 levels. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'campfire-chronicler-cautionary-tale',
    name: 'Cautionary Tale',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You recall a story about a grim fate that could befall the unwary. You tell a cautionary tale as a reaction when an ally within 30 feet is about to attempt a saving throw. The ally gains a +1 circumstance bonus to that saving throw.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Linguistic'],
    actionCost: 'reaction',
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Trigger: ally within 30 feet attempts a saving throw. +1 circumstance bonus to the save.',
  },
  {
    id: 'campfire-chronicler-epic-recollection',
    name: 'Epic Recollection',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You draw upon a vast catalogue of stories to provide useful knowledge. When you Recall Knowledge about a creature, hazard, or location, you can use Performance in place of the usual skill. On a success, you also share a relevant story that grants allies a +1 circumstance bonus to their next check against the subject.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Use Performance for Recall Knowledge about creatures, hazards, or locations. On success: allies get +1 circ to next check vs the subject.',
  },
  {
    id: 'campfire-chronicler-inspiring-narrative',
    name: 'Inspiring Narrative',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your stories inspire allies to feats of great courage. When you use Offer Story, allies who listened gain temporary Hit Points equal to your level in addition to the skill bonus. These temporary Hit Points last until your next daily preparations or until used.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Mental'],
    actionCost: 'passive',
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Offer Story also grants temp HP = your level to listening allies. Lasts until daily prep or used.',
  },
  {
    id: 'campfire-chronicler-rally-the-troops',
    name: 'Rally the Troops',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'In the heat of battle, you rally your allies with a rousing cry drawn from an epic tale. Allies within 30 feet who can hear you gain a +1 status bonus to attack rolls and Will saving throws until the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Emotion', 'Linguistic', 'Mental'],
    actionCost: 2,
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Frequency: once per 10 minutes. Allies within 30 feet: +1 status to attack rolls and Will saves until start of next turn.',
  },
  {
    id: 'campfire-chronicler-tall-tale',
    name: 'Tall Tale',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You weave a story so outlandish that enemies can\'t believe their eyes. You attempt a Performance check against the Will DC of a creature within 30 feet. On a success, the creature is fascinated by your story for 1 round (or 2 rounds on a critical success). The creature is then temporarily immune for 10 minutes.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Concentrate', 'Emotion', 'Linguistic', 'Mental'],
    actionCost: 2,
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Performance vs Will DC. Success: fascinated 1 round. Crit success: fascinated 2 rounds. 10-min immunity after.',
  },
  {
    id: 'campfire-chronicler-legendary-lesson',
    name: 'Legendary Lesson',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your stories carry such weight that they impart real skill to your listeners. When you use Offer Story, each listener can choose to gain a +2 circumstance bonus to the relevant skill check instead of +1. In addition, you can share two different stories at the same time, allowing allies to benefit from both.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Upgrades Offer Story: +2 circ bonus (up from +1). Can tell two stories simultaneously.',
  },
  {
    id: 'campfire-chronicler-unforgettable-epic',
    name: 'Unforgettable Epic',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You tell a story so compelling that it becomes etched in the memories of all who hear it. When you use Offer Story, the benefits last for 48 hours instead of 24. Additionally, allies who heard your story can retell it to others — up to 4 additional creatures can gain the story\'s benefits as the ally spends 10 minutes retelling it.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Legendary Lesson'],
    mechanics: 'Offer Story lasts 48 hours (up from 24). Allies can retell your story to up to 4 others (10 min retelling).',
  },
  {
    id: 'campfire-chronicler-living-legend',
    name: 'Living Legend',
    source: 'Campfire Chronicler (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your stories have become legendary, and you embody the heroes of your tales. Once per day, you can invoke the spirit of a legendary hero from your stories for 1 minute. During this time, you gain a +2 status bonus to attack rolls, saving throws, and skill checks. When this effect ends, you become fatigued.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Mental'],
    actionCost: 1,
    prerequisites: ['Campfire Chronicler Dedication'],
    mechanics: 'Frequency: once per day. 1 minute: +2 status to attacks, saves, and skill checks. Fatigued after.',
  },
];

// ──────────────────────────────────────────────────────────
// NECROLOGIST  (Battlecry! pg. 66–67)
// Category: Mystical — Rare
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=310
// Scholars who study undead and command small hordes.
// ──────────────────────────────────────────────────────────

export const NECROLOGIST_FEATS: FeatEntry[] = [
  {
    id: 'necrologist-dedication',
    name: 'Necrologist Dedication',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have dedicated yourself to the study of undead creatures and the forces that animate them. You become trained in Religion. If you\'re already trained, you become trained in a skill of your choice. You gain a +1 circumstance bonus to Recall Knowledge checks about undead. You also learn to perform the Create Undead ritual, though you can create only skeleton guards and zombie shamblers, and each ritual creates only a single undead creature.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication', 'Rare'],
    actionCost: 'passive',
    prerequisites: ['Trained in Arcana or Religion'],
    mechanics: 'Trained in Religion (or free skill). +1 circ to Recall Knowledge about undead. Gain Create Undead ritual (skeleton guard or zombie shambler only, 1 creature). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'necrologist-bolster-undead',
    name: 'Bolster Undead',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You channel void energy to empower your undead minions. Choose one undead creature you control within 30 feet. It gains temporary Hit Points equal to your level + your key ability modifier. These temporary Hit Points last for 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Void'],
    actionCost: 1,
    prerequisites: ['Necrologist Dedication'],
    mechanics: 'Target: undead you control within 30 feet. Temp HP = level + key ability mod, lasts 1 min. 1 action.',
  },
  {
    id: 'necrologist-command-the-horde',
    name: 'Command the Horde',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You issue commands to multiple undead simultaneously. When you use a single action to Command an undead minion, you can command up to 2 undead minions with the same action, giving both the same command. At 10th level, you can command up to 3 undead minions with a single command.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Necrologist Dedication'],
    mechanics: 'Command up to 2 undead minions with 1 action (same command). At 10th level: up to 3.',
  },
  {
    id: 'necrologist-warding-sigils',
    name: 'Warding Sigils',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You inscribe protective sigils on your undead minions that ward against common weaknesses. Choose one of your controlled undead within touch range. It gains resistance 5 to vitality damage. At 10th level, this increases to resistance 10.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Necrologist Dedication'],
    mechanics: '10-min activity. Your undead minion gains vitality resistance 5 (10 at level 10). Lasts until daily prep.',
  },
  {
    id: 'necrologist-anatomical-knowledge',
    name: 'Anatomical Knowledge',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your study of undead anatomy extends to all creatures. You gain a +1 circumstance bonus to Medicine checks. When you successfully Recall Knowledge about undead, you also learn one of its resistances or weaknesses (your choice) in addition to the normal information.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Necrologist Dedication'],
    mechanics: '+1 circ to Medicine. Successful Recall Knowledge about undead also reveals one resistance or weakness.',
  },
  {
    id: 'necrologist-improved-creation',
    name: 'Improved Creation',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'ve expanded your repertoire of undead creation. You can now use Create Undead to create skeleton champions, zombie brutes, and festrog. You can also create two undead creatures with a single Create Undead ritual instead of one.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Necrologist Dedication'],
    mechanics: 'Creates skeleton champions, zombie brutes, and festrogs. Create 2 undead per ritual.',
  },
  {
    id: 'necrologist-shared-senses',
    name: 'Shared Senses',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can perceive the world through your undead minion\'s senses. You close your eyes and see, hear, and smell through the senses of an undead creature you control within 120 feet. While using this ability, your own body is blinded and deafened. You can Dismiss this effect.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 2,
    prerequisites: ['Necrologist Dedication'],
    mechanics: 'Range: 120 feet. Perceive through controlled undead\'s senses. You are blinded + deafened while active. Sustained. Dismissible.',
  },
  {
    id: 'necrologist-undead-shield',
    name: 'Undead Shield',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You command your undead to interpose itself between you and harm. The undead minion takes the damage from the triggering attack instead of you. If the damage destroys the undead, any excess damage is dealt to you.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Necrologist Dedication'],
    mechanics: 'Trigger: You are hit by a Strike while adjacent to a controlled undead minion. Minion takes the damage instead. Excess damage spills to you.',
  },
  {
    id: 'necrologist-greater-creation',
    name: 'Greater Creation',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your mastery of undead creation reaches new heights. You can create more powerful undead such as wights and wraiths using the Create Undead ritual. You can maintain up to 4 undead creatures at a time (instead of the normal limit).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Improved Creation'],
    mechanics: 'Create wights and wraiths. Maintain up to 4 undead at once.',
  },
  {
    id: 'necrologist-death-knell-aura',
    name: 'Death Knell Aura',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your undead minions emit an aura of void energy that saps the strength of the living. Each enemy that starts its turn within 10 feet of one of your controlled undead must succeed at a Fortitude save against your class DC or become enfeebled 1 for 1 round. A creature that critically fails is enfeebled 2 instead.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Void'],
    actionCost: 'passive',
    prerequisites: ['Necrologist Dedication'],
    mechanics: 'Your undead emit 10-foot aura. Enemies starting turn in aura: Fort save or enfeebled 1 (1 round). Crit fail: enfeebled 2.',
  },
  {
    id: 'necrologist-undead-army',
    name: 'Undead Army',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You can maintain a small army of undead. You can control up to 6 undead creatures at a time. When you Command your undead, you can issue different commands to each undead in a single action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Greater Creation'],
    mechanics: 'Control up to 6 undead. Issue different individual commands with a single Command action.',
  },
  {
    id: 'necrologist-master-necrologist',
    name: 'Master Necrologist',
    source: 'Necrologist (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You are a master of the art of undead creation. You can create powerful undead such as devourers and mohrgs. Your undead minions gain a +2 status bonus to all saving throws and deal an additional die of damage on all Strikes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Undead Army'],
    mechanics: 'Create devourers and mohrgs. All your undead: +2 status to saves + one extra damage die on Strikes.',
  },
];

// ──────────────────────────────────────────────────────────
// PSYCHIC DUELIST  (Dark Archive Remastered pg. 203)
// Category: Combat — Rare
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=149
// Masters of mental combat using psychic duels.
// ──────────────────────────────────────────────────────────

export const PSYCHIC_DUELIST_FEATS: FeatEntry[] = [
  {
    id: 'psychic-duelist-dedication',
    name: 'Psychic Duelist Dedication',
    source: 'Psychic Duelist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Through dangerous practice, you\'ve learned to focus your mental energy into potent attacks during a psychic duel. You can initiate a psychic duel with a willing participant or an unwilling creature that fails a Will save against your class or spell DC. During a psychic duel, combatants use mental actions on a psychic battlefield, and the loser takes 4d6 mental damage and is stunned 1.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication', 'Rare'],
    actionCost: 'passive',
    prerequisites: ['Trained in Occultism'],
    mechanics: 'Initiate Psychic Duel [3 actions]: Will save to resist. Mental combat on psychic battlefield. Loser: 4d6 mental + stunned 1. Each round: mental actions determine outcome. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'psychic-duelist-duel-spell-advantage',
    name: 'Duel Spell Advantage',
    source: 'Psychic Duelist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you begin a psychic duel, you can bring along the mental echo of a spell as a psychic manifestation. Choose one spell you have prepared or in your repertoire of 3rd rank or lower. During the duel, you can cast the mental echo of that spell as a psychic duel action, gaining its benefits on the psychic battlefield.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Psychic Duelist Dedication'],
    mechanics: 'Bring one prepared/known spell (rank 3 or lower) into psychic duel as mental echo. Cast it as duel action.',
  },
  {
    id: 'psychic-duelist-mental-balm',
    name: 'Mental Balm',
    source: 'Psychic Duelist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you win a psychic duel, the rush of victory heals your mind. When you win a psychic duel, you regain Hit Points equal to twice the psychic duel\'s level (double the normal Hit Point loss the loser would take). You also gain a +1 circumstance bonus to Will saves for 1 minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Psychic Duelist Dedication'],
    mechanics: 'On psychic duel win: regain HP = 2 × duel level. +1 circ to Will saves for 1 minute.',
  },
  {
    id: 'psychic-duelist-psychic-fencing',
    name: 'Psychic Fencing',
    source: 'Psychic Duelist (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'re a master of mental combat and can maintain a psychic duel while also fighting in the physical world. You can take physical actions during a psychic duel without ending the duel. You still take a -2 penalty to physical actions while maintaining the duel, but can act on both battlefields simultaneously.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Psychic Duelist Dedication'],
    mechanics: 'Act physically during psychic duel without ending it. -2 penalty to physical actions while dueling.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_CP: FeatEntry[] = [
  ...CAMPFIRE_CHRONICLER_FEATS,
  ...NECROLOGIST_FEATS,
  ...PSYCHIC_DUELIST_FEATS,
];
