import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Book of the Dead (Part 2)
// Hallowed Necromancer, Lich, Mummy
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// HALLOWED NECROMANCER  (Book of the Dead pg. 24–25)
// Category: Mystical / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=106
// ──────────────────────────────────────────────────────────

export const HALLOWED_NECROMANCER_FEATS: FeatEntry[] = [
  {
    id: 'hallowed-necromancer-dedication',
    name: 'Hallowed Necromancer Dedication',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve studied the undead so you can destroy them. You gain the ability to cast divine spells using the Cast a Spell activity. You become trained in spell attack rolls and spell DCs for divine spells. Your key spellcasting ability is Intelligence or Wisdom (choose when you take this feat). You gain a spell repertoire and two divine cantrips: vitality lash and one cantrip with the void trait. You\'re trained in Religion.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Expert in Religion'],
    mechanics: 'Uncommon. Divine spontaneous caster. Key: Int or Wis. 2 cantrips: vitality lash + 1 void cantrip. Trained in Religion + divine spell attacks/DCs.',
  },
  {
    id: 'hallowed-necromancer-hallowed-initiate',
    name: 'Hallowed Initiate',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve expanded your repertoire of anti-undead magic. You gain a 1st-level spell slot and add one of the following to your spell repertoire: heal, magic missile, purifying veil, or spirit link.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hallowed Necromancer Dedication'],
    mechanics: 'Gain 1st-level divine slot. Add one of: heal, magic missile, purifying veil, spirit link to repertoire.',
  },
  {
    id: 'hallowed-necromancer-sacred-spells',
    name: 'Sacred Spells',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Add the following spells to your spell list and spell repertoire as they become available at each spell rank: 1st: protecting ward; 2nd: calm emotions, gentle repose; 3rd: circle of protection, holy light; 4th: holy cascade; 5th: wall of flesh; 6th: field of life; 7th: sunburst; 8th: moment of renewal; 9th: overwhelming presence.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hallowed Necromancer Dedication'],
    mechanics: 'Add specific spells to divine repertoire at each level from 1st–9th (protecting ward, calm emotions, gentle repose, circle of protection, holy light, holy cascade, wall of flesh, field of life, sunburst, moment of renewal, overwhelming presence).',
  },
  {
    id: 'hallowed-necromancer-death-warden',
    name: 'Death Warden',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your study of necromancy grants you resistance to the dark powers. You gain a +2 status bonus to saving throws against effects that come from undead, including undead abilities, spells, and haunts.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hallowed Necromancer Dedication'],
    mechanics: '+2 status to saves vs undead effects (abilities, spells, haunts).',
  },
  {
    id: 'hallowed-necromancer-advanced-hallowed-spell',
    name: 'Advanced Hallowed Spell',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You dig deeper into the divine magic protecting the world from undead. You gain a spell slot of one level lower than your highest hallowed necromancer spell slot. Choose one of the following spells to add to your repertoire. This spell is added at the appropriate level: heal (heightened), magic missile (heightened), purifying veil (heightened), or spirit link (heightened).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hallowed Necromancer Dedication', 'hallowed-necromancer-hallowed-initiate OR hallowed-necromancer-sacred-spells'],
    mechanics: 'Gain spell slot 1 level below highest. Add heightened version of heal, magic missile, purifying veil, or spirit link.',
    subChoices: { label: 'Choose a spell', options: [
      { id: 'heal', name: 'Heal', description: 'Restore hit points to a living creature' },
      { id: 'magic-missile', name: 'Magic Missile', description: 'Unerring force damage missiles' },
      { id: 'purifying-veil', name: 'Purifying Veil', description: 'Protective ward against undead' },
      { id: 'spirit-link', name: 'Spirit Link', description: 'Transfer HP between you and target' },
    ] },
  },
  {
    id: 'hallowed-necromancer-positive-luminance',
    name: 'Positive Luminance',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You learn to emit a searing light when channeling positive energy. When you cast a vitality spell from your hallowed necromancer spell slots, you can change the appearance of the spell. If you do, any creature targeted or in the area who takes vitality damage also takes additional persistent positive damage equal to the spell rank.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hallowed Necromancer Dedication'],
    mechanics: 'When casting vitality spell: add persistent positive damage = spell rank to all targets that take vitality damage.',
  },
  {
    id: 'hallowed-necromancer-consecrated-aura',
    name: 'Consecrated Aura',
    source: 'Hallowed Necromancer (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your body radiates a field of positive energy. You constantly emit a 30-foot aura of vitality energy. Undead that end their turn in the aura take positive damage equal to half your level (minimum 1). Living creatures who end their turn in the aura regain 1 HP (living creatures can only heal from this 1/min).',
    implemented: 'full',
    traits: ['Archetype', 'Abjuration', 'Aura', 'Positive'],
    actionCost: 'passive',
    prerequisites: ['Hallowed Necromancer Dedication'],
    mechanics: '30-ft aura. Undead: positive damage = half level at end of their turn. Living: heal 1 HP (1/min per creature).',
  },
];

// ──────────────────────────────────────────────────────────
// LICH  (Book of the Dead pg. 50–51)
// Category: Undead / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=107
// ──────────────────────────────────────────────────────────

export const LICH_FEATS: FeatEntry[] = [
  {
    id: 'lich-dedication',
    name: 'Lich Dedication',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'After years of study and the creation of a soul cage, you have become a lich. You gain the undead and lich traits and basic undead benefits. Your undead craving is consuming souls. You gain a soul cage—a magical receptacle for your soul. If your body is destroyed, you reform at your soul cage in 1d10 days. Destroying the soul cage (Hardness 9, HP 36) ends this. The soul cage must be a Tiny object worth at least 3,500 gp. Your connection to the soul cage prevents you from being truly killed; while it exists, you always reform.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You performed a ritual to become a lich'],
    mechanics: 'Rare. Lich/undead traits + basic undead benefits. Soul cage: Tiny, ≥3,500 gp, Hardness 9, HP 36. Reform 1d10 days if destroyed. Craving: souls.',
  },
  {
    id: 'lich-drain-soul-cage',
    name: 'Drain Soul Cage',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You tap into the power of your soul cage to recover from being drained, doomed, fatigued, or stunned. You must be within 100 feet of your soul cage. The soul cage darkens and can\'t be drained again for 1d4 hours.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Lich Dedication'],
    mechanics: 'Free action. Within 100 ft of soul cage. Remove drained, doomed, fatigued, or stunned. Recharge: 1d4 hours.',
  },
  {
    id: 'lich-enshroud-soul-cage',
    name: 'Enshroud Soul Cage',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You disguise and protect your soul cage with deceptive magic. You cast a permanent 3rd-level nondetection on your soul cage (counteract DC = your spell DC). You can also place the soul cage in a permanent magnificent mansion that has only one entrance. You can enter/exit freely. If either is dispelled, you can recast during daily preparations.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lich Dedication'],
    mechanics: 'Permanent nondetection (3rd-level) on soul cage. Can place in permanent magnificent mansion with 1 entrance. Recast if dispelled.',
  },
  {
    id: 'lich-hand-of-the-lich',
    name: 'Hand of the Lich',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Negative energy flows through your fingers. You gain a hand of the lich unarmed attack (1d8 negative, finesse, Unarmed group). On a critical hit with your hand of the lich, the target must succeed at a Fortitude save against your spell DC or be paralyzed for 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lich Dedication'],
    mechanics: 'Hand of the lich: 1d8 negative (finesse, unarmed). Crit: Fort save or paralyzed 1 round.',
  },
  {
    id: 'lich-bolster-soul-cage',
    name: 'Bolster Soul Cage',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You bolster the defenses of your soul cage. The Hardness increases to 14, HP increases to 56. Additionally, if anyone touches or damages the soul cage, you can sense it and learn the direction and approximate distance to it.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Drain Soul Cage'],
    mechanics: 'Soul cage: Hardness 14, HP 56. Sense any touch/damage to soul cage (direction + approx distance).',
  },
  {
    id: 'lich-spell-gem',
    name: 'Spell Gem',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You can embed a spell into a gem on your body (usually your forehead). During daily preparations, you can embed one spell you can cast into the spell gem. You can cast this spell once that day using your spell gem instead of a spell slot, at the normal spell rank. At 18th level, you can embed two spells.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Lich Dedication'],
    mechanics: 'Daily: embed 1 prepared spell into gem. Cast once/day without slot. 18th level: embed 2 spells.',
  },
  {
    id: 'lich-frightful-aura',
    name: 'Frightful Aura',
    source: 'Lich (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You\'re surrounded by a palpable sense of menace. You gain a frightful presence aura of 60 feet (DC = your spell DC). Creatures must attempt a Will save when they first enter the aura. Critical Success: immune 1 minute. Success: immune 24 hours. Failure: frightened 1. Critical Failure: frightened 2.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Emotion', 'Fear', 'Mental'],
    actionCost: 'passive',
    prerequisites: ['Lich Dedication'],
    mechanics: '60-ft frightful presence aura. Will save on entry. Fail: frightened 1. Crit Fail: frightened 2. Success: immune 24 hrs. Crit Success: immune 1 min.',
  },
];

// ──────────────────────────────────────────────────────────
// MUMMY  (Book of the Dead pg. 52–53)
// Category: Undead / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=108
// ──────────────────────────────────────────────────────────

export const MUMMY_FEATS: FeatEntry[] = [
  {
    id: 'mummy-dedication',
    name: 'Mummy Dedication',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Whether through necromantic ritual or natural mummification, you\'ve risen as a dried husk of your former self. You gain the mummy and undead traits and basic undead benefits. Your undead craving is living warmth. You take 5 additional fire damage from fire effects (or 10 if you gain the advanced undead benefits). You gain Mummy\'s Despair (an emotion, fear, mental, aura that can be activated), but you haven\'t yet learned to control it.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You were mummified through ritual or natural means'],
    mechanics: 'Rare. Mummy/undead traits + basic undead benefits. Weakness: +5 fire (or +10 with advanced benefits). Gain Mummy\'s Despair aura (dormant until feat unlocked).',
  },
  {
    id: 'mummy-one-with-the-land',
    name: 'One with the Land',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your connection to the land around your tomb is strengthened. While within environment of your tomb, you gain tremorsense 30 feet, +2 circumstance bonus to Stealth checks, and +1 circumstance bonus to Initiative.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Mummy Dedication'],
    mechanics: 'In tomb\'s environment: tremorsense 30 ft, +2 circ Stealth, +1 circ Initiative.',
  },
  {
    id: 'mummy-semblance-of-life',
    name: 'Semblance of Life',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your appearance changed as you dried and withered, but you now know how to make yourself look alive. You can cast illusory disguise on yourself at will as a 1st-level innate divine spell. The spell ends if you use a hostile action.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Illusion'],
    actionCost: 'passive',
    prerequisites: ['Mummy Dedication'],
    mechanics: 'At-will illusory disguise (1st-level innate divine). Ends on hostile action.',
  },
  {
    id: 'mummy-grave-mummification',
    name: 'Grave Mummification',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your body continues to change and harden. You gain advanced undead benefits. The additional fire damage from your Mummy Dedication increases to 10. You also gain resistance 2 to physical damage (except magical) and resistance 2 to poison.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Mummy Dedication'],
    mechanics: 'Advanced undead benefits. +10 fire weakness. Resistance 2 physical (except magical), resistance 2 poison.',
  },
  {
    id: 'mummy-mummys-despair',
    name: 'Mummy\'s Despair',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have learned to control your dread aura. You emanate a 30-foot aura of despair. Creatures entering or starting their turn in the aura must attempt a Will save against your class DC or spell DC (whichever higher). Failure: frightened 1 (frightened 2 on critical failure). Success: temporarily immune 10 minutes.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Divine', 'Emotion', 'Enchantment', 'Fear', 'Mental'],
    actionCost: 2,
    prerequisites: ['Mummy Dedication'],
    mechanics: '2 actions to activate. 30-ft aura. Will save on entry/start of turn. Fail: frightened 1. Crit Fail: frightened 2. Success: immune 10 min.',
  },
  {
    id: 'mummy-accursed-touch',
    name: 'Accursed Touch',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You deliver a cursed touch to your enemies. Make an unarmed Strike against a living creature. On hit, the target additionally must attempt a Fortitude save. Failure: the target is cursed with mummy rot (disease). Level equals half your level. Onset: 1 round. Maximum stage 4.',
    implemented: 'full',
    traits: ['Archetype', 'Curse', 'Disease', 'Divine', 'Necromancy'],
    actionCost: 2,
    prerequisites: ['Mummy Dedication'],
    mechanics: '2 actions. Unarmed Strike. On hit: Fort save or mummy rot (disease). Level = half your level, onset 1 round, max stage 4.',
  },
  {
    id: 'mummy-storm-shroud',
    name: 'Storm Shroud',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your bandages and dry form can conjure a localized sandstorm or dust storm. Until the start of your next turn, creatures adjacent to you are concealed from each other. You are not concealed from adjacent creatures. This also provides environmental protection: creatures in the area take a –2 circumstance penalty to Perception checks.',
    implemented: 'full',
    traits: ['Archetype', 'Conjuration', 'Divine'],
    actionCost: 2,
    prerequisites: ['Mummy Dedication'],
    mechanics: '2 actions. Until next turn: adjacent creatures concealed from each other (not you). –2 circ Perception in area.',
  },
  {
    id: 'mummy-channel-rot',
    name: 'Channel Rot',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You channel your mummy rot through a weapon you wield. When you Strike a living creature with a melee weapon or unarmed attack and deal damage, you can also deal 1d6 persistent negative damage. The creature must then attempt a Fortitude save against your class DC or spell DC. Failure: affected by mummy rot as if you had used Accursed Touch.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Necromancy'],
    actionCost: 'free',
    prerequisites: ['Accursed Touch'],
    mechanics: 'Free action on melee hit. +1d6 persistent negative. Fort save or mummy rot. Works with weapons + unarmed.',
  },
  {
    id: 'mummy-ensnaring-wrappings',
    name: 'Ensnaring Wrappings',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your bandages lash out to grab your opponents. When you successfully Grapple a creature that is within 10 feet, you can pull that creature adjacent to you. Also you can Grapple a creature up to 10 feet away instead of only adjacent.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Mummy Dedication'],
    mechanics: 'Grapple reach: 10 ft. On success: pull target adjacent.',
  },
  {
    id: 'mummy-terrain-form',
    name: 'Terrain Form',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You can become one with the terrain surrounding your tomb. If within your tomb\'s terrain type, you can spend 3 actions to merge into the terrain, becoming a part of it. While merged, you can sense tremorsense 60 feet, can\'t take actions, can\'t be targeted, and are healed by 10 HP per hour. You can emerge as a 3-action activity.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Transmutation'],
    actionCost: 3,
    prerequisites: ['One with the Land'],
    mechanics: '3 actions to merge into tomb terrain. Merged: tremorsense 60 ft, untargetable, heal 10 HP/hr. 3 actions to emerge.',
  },
  {
    id: 'mummy-desiccating-inhalation',
    name: 'Desiccating Inhalation',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You draw the moisture from the living in a 30-foot cone with a powerful inhalation. Living creatures in the cone take 6d8 negative damage (basic Fortitude save). You regain HP equal to the highest single damage dealt. Frequency: once per hour.',
    implemented: 'full',
    traits: ['Archetype', 'Divine', 'Necromancy'],
    actionCost: 2,
    prerequisites: ['Mummy Dedication'],
    mechanics: '2 actions. 30-ft cone: 6d8 negative, basic Fort. Heal = highest single damage dealt. 1/hour.',
  },
  {
    id: 'mummy-greater-despair',
    name: 'Greater Despair',
    source: 'Mummy (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your aura of despair grows heavier and more oppressive. Your Mummy\'s Despair aura increases to 60 feet. Creatures that fail the saving throw are also slowed 1 for 1 round (in addition to being frightened).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Mummy\'s Despair'],
    mechanics: 'Despair aura expands to 60 ft. Failure: frightened + slowed 1 for 1 round.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_LEGACY_BD2: FeatEntry[] = [
  ...HALLOWED_NECROMANCER_FEATS,
  ...LICH_FEATS,
  ...MUMMY_FEATS,
];
