import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — U through W (military/nature)
// Ulfen Guard, Verduran Shadow, War Mage, Warrior of Legend
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// ULFEN GUARD  (Shining Kingdoms pg. 172)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=197
// Elite bodyguard tradition of the Ulfen people.
// ──────────────────────────────────────────────────────────

export const ULFEN_GUARD_FEATS: FeatEntry[] = [
  {
    id: 'ulfen-guard-dedication',
    name: 'Ulfen Guard Dedication',
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have dedicated yourself to the tradition of the Ulfen Guard, sworn protectors who act as personal bodyguards. You become trained in Intimidation. You gain the Designate Ally free action; at the start of each of your turns, you designate one willing ally within 30 feet as the target of your protection. You gain a +1 circumstance bonus to Perception checks to Seek creatures within 10 feet of your designated ally.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication', 'Uncommon'],
    actionCost: 'passive',
    prerequisites: ['Expert in at least one melee weapon'],
    mechanics: 'Trained in Intimidation. Designate Ally [free] at start of turn: choose willing ally within 30 feet. +1 circ to Perception to Seek within 10 feet of designated ally. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'ulfen-guard-defenders-grit',
    name: "Defender's Grit",
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your fury at seeing your ally harmed fuels your fighting spirit. You gain temporary Hit Points equal to half your level (minimum 1). These temporary Hit Points last until the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Mental'],
    actionCost: 'free',
    prerequisites: ['Ulfen Guard Dedication'],
    mechanics: 'Trigger: A creature within your reach deals damage to your designated ally. Gain temp HP = half level (min 1) until start of next turn.',
  },
  {
    id: 'ulfen-guard-guards-fury',
    name: "Guard's Fury",
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your blood boils when a creature dares to harm your ward. Make a melee Strike against the triggering creature.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Ulfen Guard Dedication'],
    mechanics: 'Trigger: A creature within your reach critically hits your designated ally. Make a melee Strike against the triggering creature. Normal MAP applies.',
  },
  {
    id: 'ulfen-guard-guarded-mind',
    name: 'Guarded Mind',
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your devotion to your designated ally steels your mind. You gain a +2 circumstance bonus to saving throws against mental effects while your designated ally is within 30 feet of you.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ulfen Guard Dedication'],
    mechanics: '+2 circumstance bonus to saves vs mental effects while designated ally is within 30 feet.',
  },
  {
    id: 'ulfen-guard-wounded-party',
    name: 'Wounded Party',
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When your charge is injured, your protective instincts kick in. You and your designated ally each gain temporary Hit Points equal to your level until the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Ulfen Guard Dedication'],
    mechanics: 'Trigger: designated ally takes damage from a Strike. Frequency: once per 10 minutes. Both you and ally gain temp HP = level until end of your next turn.',
  },
  {
    id: 'ulfen-guard-tight-follower',
    name: 'Tight Follower',
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You stay close to your charge, shadowing their every move. You Step or Stride. You must end this movement within 10 feet of your designated ally.',
    implemented: 'full',
    traits: ['Archetype', 'Move'],
    actionCost: 'reaction',
    prerequisites: ['Ulfen Guard Dedication'],
    mechanics: 'Trigger: Your designated ally moves using a move action. Step or Stride, must end within 10 feet of them.',
  },
  {
    id: 'ulfen-guard-protective-strike',
    name: 'Protective Strike',
    source: 'Ulfen Guard (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You throw yourself in the path of danger to protect your ward. You take the damage instead of your ally, including any effects that would be caused by the triggering Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Ulfen Guard Dedication'],
    mechanics: 'Trigger: Your designated ally within your reach is hit by a melee Strike. You take all the damage and effects instead of your ally. Frequency: once per round.',
  },
];

// ──────────────────────────────────────────────────────────
// VERDURAN SHADOW  (Pathfinder #201: Pactbreaker pg. 79–81)
// Category: Faction — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=302
// Forest-dwelling scouts who blend with the Verduran Forest.
// ──────────────────────────────────────────────────────────

export const VERDURAN_SHADOW_FEATS: FeatEntry[] = [
  {
    id: 'verduran-shadow-dedication',
    name: 'Verduran Shadow Dedication',
    source: 'Verduran Shadow (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have become skilled at blending in with the forest environment. You\'re trained in Stealth and Survival. If you were already trained, you instead become trained in a skill of your choice. When in forest terrain, you can use Survival in place of Stealth to Hide and Sneak.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication', 'Uncommon'],
    actionCost: 'passive',
    prerequisites: ['Trained in Stealth or Survival'],
    mechanics: 'Trained in Stealth and Survival (or free skill if already trained). Use Survival for Hide and Sneak in forest terrain. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'verduran-shadow-canopy-predator',
    name: 'Canopy Predator',
    source: 'Verduran Shadow (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You are an expert at traversing the forest canopy. You gain a climb Speed of 10 feet when climbing trees or other large plants. If you already have a climb Speed, it increases by 5 feet when climbing trees. When you Strike a creature below you from an elevated position, you gain a +1 circumstance bonus to the attack roll.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Verduran Shadow Dedication'],
    mechanics: 'Climb Speed 10 feet (trees/plants only, +5 if you already have climb speed). +1 circumstance to attacks from higher elevation.',
  },
  {
    id: 'verduran-shadow-underbrush-trailblazer',
    name: 'Underbrush Trailblazer',
    source: 'Verduran Shadow (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You move through the densest undergrowth as though it were an open trail. You ignore difficult terrain caused by undergrowth and non-magical plants. In addition, when you use the Survival skill to Track in forest terrain, you gain a +2 circumstance bonus.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Verduran Shadow Dedication'],
    mechanics: 'Ignore difficult terrain from undergrowth and non-magical plants. +2 circumstance to Track in forests.',
  },
  {
    id: 'verduran-shadow-verduran-ambush',
    name: 'Verduran Ambush',
    source: 'Verduran Shadow (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You strike from your forest hiding place with deadly precision. If you are hidden from a creature and in forest terrain, you can Interact to draw a weapon and then Strike the creature. If you are using Survival to Hide (via Verduran Shadow Dedication), you can also attempt a Survival check to remain hidden after the Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Verduran Shadow Dedication'],
    mechanics: 'Requires hidden + forest terrain. Interact (draw weapon) + Strike in 2 actions. Use Survival to remain hidden after Strike in forest.',
  },
  {
    id: 'verduran-shadow-death-from-above',
    name: 'Death from Above',
    source: 'Verduran Shadow (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You drop from the canopy to deliver a devastating strike. You Leap from a higher elevation down to a square adjacent to a creature, then make a melee Strike against the creature. The Strike deals an additional 2d6 damage. If you critically succeed, the creature is also off-guard until the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Canopy Predator'],
    mechanics: 'Leap down from elevation + Strike. +2d6 damage. Crit success = target off-guard until start of your next turn.',
  },
  {
    id: 'verduran-shadow-sense-the-strike',
    name: 'Sense the Strike',
    source: 'Verduran Shadow (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You have developed a supernatural awareness for danger in the forest. While you are in forest terrain and not off-guard, creatures don\'t gain the benefit of being hidden or undetected from you when making Strikes against you, as long as they are within 15 feet.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Verduran Shadow Dedication'],
    mechanics: 'In forest terrain and not off-guard: enemies within 15 feet can\'t benefit from hidden/undetected when Striking you.',
  },
];

// ──────────────────────────────────────────────────────────
// WAR MAGE  (Battlecry! pg. 68–69)
// Category: Class Archetype (Wizard) — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=311
// Wizards who apply arcane knowledge to battlefield tactics.
// ──────────────────────────────────────────────────────────

export const WAR_MAGE_FEATS: FeatEntry[] = [
  {
    id: 'war-mage-dedication',
    name: 'War Mage Dedication',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You are a war mage, a wizard who takes to the battlefield rather than the academy. You become trained in medium armor. If you are already trained in medium armor, you become trained in heavy armor instead. You also become trained in one martial weapon of your choice. You gain the Tactical Repositioning focus spell, which lets you mystically reposition an ally within 30 feet, moving them up to 15 feet to a space they could normally stand.',
    implemented: 'full',
    traits: ['Archetype', 'Class', 'Dedication', 'Uncommon'],
    actionCost: 'passive',
    prerequisites: ['Wizard class'],
    mechanics: 'Trained in medium armor (or heavy if already medium). Trained in one martial weapon. Gain Tactical Repositioning focus spell (30 feet, move ally 15 feet). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'war-mage-mages-field-dressing',
    name: "Mage's Field Dressing",
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned to magically stabilize wounds on the battlefield. You gain the Mage\'s Field Dressing focus spell. When cast on an ally within 30 feet, the target regains Hit Points equal to 1d8 + your spellcasting modifier. The spell is heightened at higher ranks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['War Mage Dedication'],
    mechanics: 'Gain Mage\'s Field Dressing focus spell. Heal ally within 30 feet for 1d8 + spellcasting mod. Heightened (+1): +1d8. 2 actions to cast.',
  },
  {
    id: 'war-mage-shield-spell-reinforcement',
    name: 'Shield Spell Reinforcement',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast shield or similar protective spells, nearby allies benefit from your magical protection. When you have your shield spell active, allies adjacent to you gain a +1 circumstance bonus to AC.',
    implemented: 'full',
    traits: ['Archetype', 'Aura'],
    actionCost: 'passive',
    prerequisites: ['War Mage Dedication'],
    mechanics: 'While your shield cantrip is active, adjacent allies gain +1 circumstance to AC.',
  },
  {
    id: 'war-mage-siege-ritualist',
    name: 'Siege Ritualist',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'ve studied the art of siege warfare from a magical perspective. You gain the ability to perform special rituals to fortify a position. You can cast wall of stone as a ritual with a casting time of 1 hour. The wall lasts for 8 hours. You also gain a +2 circumstance bonus to checks made to Recall Knowledge about structures and fortifications.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['War Mage Dedication'],
    mechanics: 'Wall of stone as 1-hour ritual (lasts 8 hours). +2 circ to Recall Knowledge about structures/fortifications.',
  },
  {
    id: 'war-mage-arcana-of-iron',
    name: 'Arcana of Iron',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your arcane knowledge extends to the magical properties of metal equipment. You can spend 10 minutes to counteract a magical effect on a weapon or piece of armor. Your counteract rank is half your level rounded up, and your counteract modifier is your Arcana modifier.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['War Mage Dedication'],
    mechanics: '10-minute activity: counteract magic on weapon or armor. Counteract rank = half level (rounded up). Uses Arcana modifier.',
  },
  {
    id: 'war-mage-intimidating-spell',
    name: 'Intimidating Spell',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your offensive spells carry the weight of your martial bearing. When you successfully deal damage to a creature with a spell, you can attempt to Demoralize that creature as a free action. You use your spell DC - 10 in place of your Intimidation modifier for this check.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Fear', 'Mental'],
    actionCost: 'free',
    prerequisites: ['War Mage Dedication'],
    mechanics: 'Trigger: Deal damage to creature with a spell. Free action Demoralize using spell DC - 10 as Intimidation modifier.',
  },
  {
    id: 'war-mage-shielding-formation',
    name: 'Shielding Formation',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You extend your shield spell\'s protection to cover your entire unit. When you cast shield, all willing allies within 10 feet gain a +1 circumstance bonus to AC until the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Aura'],
    actionCost: 'passive',
    prerequisites: ['Shield Spell Reinforcement'],
    mechanics: 'Upgrades Shield Spell Reinforcement: extends +1 circ AC to all willing allies within 10 feet (up from adjacent only). Until start of next turn.',
  },
  {
    id: 'war-mage-spellshield',
    name: 'Spellshield',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'ve learned to reactively deploy magical defenses. When an ally within 30 feet is targeted by a spell, you can spend one of your spell slots to grant them a +2 status bonus to their saving throw against that spell. If the attacking spell\'s rank is lower than the slot you expend, the bonus increases to +3.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['War Mage Dedication'],
    mechanics: 'Trigger: ally within 30 feet targeted by spell. Spend a spell slot: +2 status bonus to save. +3 if your slot rank > spell rank.',
  },
  {
    id: 'war-mage-secrets-of-steel',
    name: 'Secrets of Steel',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You can temporarily imbue weapons with arcane energy. You spend 10 minutes to enchant up to 4 weapons within touch range, granting each a +1 status bonus to attack rolls and dealing an additional 1d6 force damage for 1 hour. At 18th level, this increases to a +2 status bonus and 2d6 force damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Arcana of Iron'],
    mechanics: '10-min activity: enchant up to 4 weapons. +1 status to attack + 1d6 force damage for 1 hour. At 18th: +2 status + 2d6 force.',
  },
  {
    id: 'war-mage-battlefield-arcana',
    name: 'Battlefield Arcana',
    source: 'War Mage (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You can reshape the terrain of the battlefield with a powerful display of arcane might. You can cast an area spell and simultaneously reshape the terrain in its area: difficult terrain becomes normal, or normal terrain becomes difficult. This terrain alteration is permanent. Additionally, you can use Tactical Repositioning on up to 3 allies simultaneously.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['War Mage Dedication'],
    mechanics: 'When casting an area spell, reshape terrain in the area (toggle difficult terrain). Permanent change. Tactical Repositioning targets up to 3 allies simultaneously.',
  },
];

// ──────────────────────────────────────────────────────────
// WARRIOR OF LEGEND  (War of Immortals pg. 66–67)
// Category: Class Archetype (Fighter) — Rare
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=288
// Mythic warriors cursed with doom but empowered by fate.
// ──────────────────────────────────────────────────────────

export const WARRIOR_OF_LEGEND_FEATS: FeatEntry[] = [
  {
    id: 'warrior-of-legend-dedication',
    name: 'Warrior of Legend Dedication',
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have been marked by fate as a warrior of great renown, but with this power comes a terrible doom. You gain the doomed 1 condition, which can\'t be reduced below 1 except by the specific means described in your doom\'s prophecy. You gain a +1 status bonus to attack rolls and damage rolls. Whenever you take the dying condition, your doomed value does not increase from the dying condition.',
    implemented: 'full',
    traits: ['Archetype', 'Class', 'Dedication', 'Rare'],
    actionCost: 'passive',
    prerequisites: ['Fighter class'],
    mechanics: 'Permanently doomed 1 (can\'t go below 1 except via prophecy). +1 status to attack and damage. Dying doesn\'t increase doomed. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'warrior-of-legend-heroic-defiance',
    name: 'Heroic Defiance',
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You refuse to fall when your doom has not yet come. When you would be reduced to 0 Hit Points, you are instead reduced to 1 Hit Point and gain temporary Hit Points equal to your level. These temporary Hit Points last until the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Warrior of Legend Dedication'],
    mechanics: 'Trigger: Reduced to 0 HP. Frequency: once per day. Stay at 1 HP, temp HP = level (until end of next turn).',
  },
  {
    id: 'warrior-of-legend-piercing-doom',
    name: 'Piercing Doom',
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your attacks carry the weight of doom itself. Your Strikes ignore an amount of a creature\'s resistance equal to your doomed value × 3. If the creature also has the doomed condition, your Strikes ignore all of that creature\'s resistances.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Warrior of Legend Dedication'],
    mechanics: 'Strikes ignore resistance = doomed × 3. If target is also doomed, ignore ALL resistances.',
  },
  {
    id: 'warrior-of-legend-spear-of-doom',
    name: 'Spear of Doom',
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You channel the energy of your impending doom into a devastating strike. Your next Strike deals additional void damage equal to twice your doomed value. If the target is doomed, it also becomes enfeebled 1 until the end of its next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Void'],
    actionCost: 1,
    prerequisites: ['Warrior of Legend Dedication'],
    mechanics: 'Next Strike deals +void damage = 2 × doomed value. If target is doomed, also enfeebled 1 (1 round).',
  },
  {
    id: 'warrior-of-legend-know-thy-doom',
    name: 'Know Thy Doom',
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You can sense the touch of doom on others. You can detect the presence of doomed creatures within 60 feet as an imprecise sense. You can also spend a single action to focus on a creature you can see; you learn whether that creature is doomed and what their doomed value is.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 'passive',
    prerequisites: ['Warrior of Legend Dedication'],
    mechanics: 'Imprecise sense: doomed creatures within 60 feet. 1-action: determine exact doomed value of visible creature.',
  },
  {
    id: 'warrior-of-legend-only-my-doom-may-claim-me',
    name: 'Only My Doom May Claim Me',
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You are destined to meet your end in a specific way, and nothing else can take that from you. You gain resistance to all damage equal to your doomed value. When you would gain the dying condition, you can choose to increase your doomed value by 1 (to a maximum of doomed 4) instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Warrior of Legend Dedication'],
    mechanics: 'Resistance all damage = doomed value. When gaining dying, can choose to increase doomed by 1 (max 4) instead.',
  },
  {
    id: 'warrior-of-legend-razors-edge',
    name: "Razor's Edge",
    source: 'Warrior of Legend (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'The closer you are to your doom, the more devastating your attacks become. You deal additional damage on all Strikes equal to your doomed value × your weapon\'s number of damage dice. When your doomed value is 3 or higher, your Strikes deal an additional die of weapon damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Warrior of Legend Dedication'],
    mechanics: 'Strikes deal +damage = doomed × number of weapon damage dice. At doomed 3+, add one additional weapon damage die.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_UW: FeatEntry[] = [
  ...ULFEN_GUARD_FEATS,
  ...VERDURAN_SHADOW_FEATS,
  ...WAR_MAGE_FEATS,
  ...WARRIOR_OF_LEGEND_FEATS,
];
