import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Lost Omens: Firebrand Braggart, Hellknights
// LO Character Guide / World Guide
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// FIREBRAND BRAGGART  (Character Guide pg. 74)
// ──────────────────────────────────────────────────────────

export const FIREBRAND_BRAGGART_FEATS: FeatEntry[] = [
  {
    id: 'firebrand-braggart-dedication',
    name: 'Firebrand Braggart Dedication',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your Firebrand training taught you that achieving something is more satisfying if you boast first. Declare a boast about a skill action. First time you attempt it within 1 minute, roll twice and use the lower result (misfortune). If you succeed, gain +1 circumstance bonus to that action for 10 minutes. If you fail or don\'t attempt within 1 minute, take –1 penalty for 1 hour. Once per daily preparation per action.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication', 'Misfortune'],
    actionCost: 1,
    prerequisites: ['Charisma 14', 'Second mark member of the Firebrands'],
    mechanics: 'Uncommon. 1-action boast about skill action. Misfortune on first attempt. Success: +1 circumstance (10 min). Fail: –1 penalty (1 hour). 1/day per action.',
  },
  {
    id: 'firebrand-braggart-boasters-challenge',
    name: 'Boaster\'s Challenge',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Select one creature and declare a challenge. Attempt Deception, Diplomacy, or Intimidation vs Will DC. Success: +2 status to damage (master: +4, legendary: +6) until end of next turn. Critical success: lasts 3 rounds. Witnesses gain +4 to Will DC vs your challenges for 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Mental'],
    actionCost: 1,
    prerequisites: ['Expert in Deception, Diplomacy, or Intimidation', 'Firebrand Braggart Dedication'],
    mechanics: '1-action challenge. Skill vs Will DC. Success: +2/+4/+6 status to damage. Crit: 3 rounds. Witnesses immune 1 min.',
  },
  {
    id: 'firebrand-braggart-daring-act',
    name: 'Daring Act',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Attempt a death-defying maneuver. Select one foe within reach, attempt Acrobatics or Athletics vs Reflex DC. Success: Stride half Speed without triggering reactions from target, target is off-guard vs your next melee attack this turn. Critical success: full Speed.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Trained in Acrobatics or Athletics', 'Firebrand Braggart Dedication'],
    mechanics: '2-action. Acrobatics/Athletics vs Reflex DC. Success: Stride half Speed, target off-guard. Crit: full Speed.',
  },
  {
    id: 'firebrand-braggart-bravos-determination',
    name: 'Bravo\'s Determination',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When a foe\'s Strike reduces you to 0 HP (not from 1 HP, not killed), attempt Deception vs attack DC. Penalty = 2× wounded value. If crit hit, worsen result by one degree. Critical success: stay at 1 HP. Success: stay at 1 HP but increase wounded by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Expert in Deception', 'Firebrand Braggart Dedication'],
    mechanics: 'Reaction. Trigger: foe reduces to 0 HP. Deception vs attack DC (–2×wounded). Crit success/success: stay at 1 HP.',
  },
  {
    id: 'firebrand-braggart-great-boaster',
    name: 'Great Boaster',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'If you succeed at a boast, you can attempt a great boast about the same action during the bonus duration. Great boast success: +2 circumstance bonus for 1 hour. Failure: –2 penalty for 4 hours. Minimum hard DC for level. Once per daily prep per action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Charisma 16', 'Firebrand Braggart Dedication'],
    mechanics: 'After successful boast, great boast available. Success: +2 (1 hour). Fail: –2 (4 hours). Hard DC minimum.',
  },
  {
    id: 'firebrand-braggart-daring-flourish',
    name: 'Daring Flourish',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'At the end of a successful Daring Act, you can make a melee Strike or attempt to Disarm. The target is off-guard against both the Daring Act Strike and your next melee attack before end of turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Daring Act'],
    mechanics: 'After successful Daring Act: free Strike or Disarm. Target off-guard vs both.',
  },
  {
    id: 'firebrand-braggart-demanding-challenge',
    name: 'Demanding Challenge',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'If your Boaster\'s Challenge succeeds, the target takes –1 circumstance penalty to attack rolls (–2 on critical success) until end of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Boaster\'s Challenge'],
    mechanics: 'On challenge success: target –1 attack (–2 on crit) until end of next turn.',
  },
  {
    id: 'firebrand-braggart-daredevils-gambit',
    name: 'Daredevil\'s Gambit',
    source: 'Firebrand Braggart (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'On critical success at Daring Act, enter the target\'s space until start of your next turn or target moves. Gain +2 circumstance to AC; target off-guard vs your attacks. If another creature hits you, DC 15 flat check: on success, resolve attack against your target instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Daring Act'],
    mechanics: 'Crit Daring Act: enter target space. +2 AC, target off-guard. Others hit you: DC 15 flat → redirect to target.',
  },
];

// ──────────────────────────────────────────────────────────
// HELLKNIGHT ARMIGER  (World Guide pg. 107)
// ──────────────────────────────────────────────────────────

export const HELLKNIGHT_ARMIGER_FEATS: FeatEntry[] = [
  {
    id: 'hellknight-armiger-dedication',
    name: 'Hellknight Armiger Dedication',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your Hellknight training teaches you to terrorize others. You gain resistance to mental damage equal to 1 + your number of class feats from Hellknight archetypes. Become trained in Intimidation and Hell Lore (or expert if already trained).',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Member of a Hellknight Order', 'Trained in heavy armor and order\'s favored weapon'],
    mechanics: 'Uncommon. Resistance mental = 1 + Hellknight archetype class feats. Trained Intimidation + Hell Lore.',
  },
  {
    id: 'hellknight-armiger-ardent-armiger',
    name: 'Ardent Armiger',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain +1 circumstance to saves vs mental effects improving your attitude and to Will DC vs Coerce, Demoralize, Make an Impression, Request. If compelled to violate order tenets, reaction for new Will save.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Armiger Dedication'],
    mechanics: '+1 circumstance vs mental attitude/social. Compelled to violate tenets: reaction new Will save.',
  },
  {
    id: 'hellknight-armiger-diabolic-certitude',
    name: 'Diabolic Certitude',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When your turn begins and you can observe a devil, attempt to Recall Knowledge about it. Critical failure becomes failure.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'free',
    prerequisites: ['Hellknight Armiger Dedication'],
    mechanics: 'Free action on turn start. Recall Knowledge about observed devil. Crit fail → fail.',
  },
  {
    id: 'hellknight-armiger-mortification',
    name: 'Mortification',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Choose bludgeoning, piercing, or slashing. Gain resistance to that damage type equal to your number of class feats from Hellknight archetypes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Armiger Dedication'],
    mechanics: 'Choose B/P/S. Resistance = # Hellknight archetype class feats.',
    subChoices: { label: 'Choose damage type', options: [
      { id: 'bludgeoning', name: 'Bludgeoning' },
      { id: 'piercing', name: 'Piercing' },
      { id: 'slashing', name: 'Slashing' },
    ] },
  },
  {
    id: 'hellknight-armiger-armigers-mobility',
    name: 'Armiger\'s Mobility',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'In heavy armor meeting Str requirement, reduce movement penalty by 10 ft instead of 5 (typically to 0). Dwarves with Unburdened Iron gain +5 Speed.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Expert in heavy armor', 'Hellknight Armiger Dedication'],
    mechanics: 'Heavy armor: reduce Speed penalty by 10 instead of 5. Dwarf Unburdened Iron: +5 Speed.',
  },
  {
    id: 'hellknight-armiger-order-training',
    name: 'Order Training',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain the lesser order benefit for the Hellknight order to which you belong.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Armiger Dedication'],
    mechanics: 'Uncommon. Gain lesser order benefit of your Hellknight order.',
  },
  {
    id: 'hellknight-armiger-advanced-order-training',
    name: 'Advanced Order Training',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You gain the greater order benefit for the Hellknight order to which you belong.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Armiger Dedication', 'Hellknight Dedication or Hellknight Signifer Dedication'],
    mechanics: 'Uncommon. Gain greater order benefit of your Hellknight order.',
  },
  {
    id: 'hellknight-armiger-order-cross-training',
    name: 'Hellknight Order Cross-Training',
    source: 'Hellknight Armiger (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Gain the lesser order benefit of a different Hellknight order. Must be in good standing. Selectable multiple times for different orders.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Armiger Dedication', 'Hellknight Dedication or Hellknight Signifer Dedication'],
    mechanics: 'Uncommon. Gain lesser order benefit from another order. Repeatable.',
  },
];

// ──────────────────────────────────────────────────────────
// HELLKNIGHT  (Character Guide pg. 84)
// ──────────────────────────────────────────────────────────

export const HELLKNIGHT_FEATS: FeatEntry[] = [
  {
    id: 'hellknight-dedication',
    name: 'Hellknight Dedication',
    source: 'Hellknight (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have forged your body to comply with the Measure and the Chain. Expert in Intimidation (or another trained skill). Gain Hellknight plate armor specialization (resistance +1 higher). +1 circumstance to Intimidation while wearing Hellknight plate.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Armiger Dedication', 'Member of a Hellknight Order', 'Passed the Hellknight Test'],
    mechanics: 'Uncommon. Expert Intimidation. Hellknight plate specialization (resistance +1). +1 Intimidation in plate.',
  },
  {
    id: 'hellknight-sense-chaos',
    name: 'Sense Chaos',
    source: 'Hellknight (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You sense the presence of extradimensional disorder as an uncomfortable nervous energy (vague sense like smell). Detect powerful/overwhelming chaotic auras eventually. Creatures with the chaotic trait use Deception vs your Perception DC to hide their nature. Success: immune 1 day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Dedication'],
    mechanics: 'Vague sense: detect powerful/overwhelming chaotic auras. Chaotic creature: Deception vs Perception DC.',
  },
  {
    id: 'hellknight-blade-of-law',
    name: 'Blade of Law',
    source: 'Hellknight (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Make a Strike against a foe you\'ve witnessed breaking the law or acting disorderly. The Strike deals two extra weapon damage dice if target is chaotic. You can convert physical damage to lawful damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Hellknight Dedication'],
    mechanics: '2-action. Strike vs lawbreaker. +2 weapon dice if chaotic. Convert physical → lawful damage.',
  },
  {
    id: 'hellknight-hells-armaments',
    name: 'Hell\'s Armaments',
    source: 'Hellknight (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'If you have expert proficiency in any weapon/unarmed, gain expert in your order\'s weapon as well. If expert in any armor/unarmored, gain expert in Hellknight plate.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Dedication'],
    mechanics: 'Expert any weapon → expert order weapon. Expert any armor → expert Hellknight plate.',
  },
];

// ──────────────────────────────────────────────────────────
// HELLKNIGHT SIGNIFER  (Character Guide pg. 85)
// ──────────────────────────────────────────────────────────

export const HELLKNIGHT_SIGNIFER_FEATS: FeatEntry[] = [
  {
    id: 'hellknight-signifer-dedication',
    name: 'Hellknight Signifer Dedication',
    source: 'Hellknight Signifer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You receive a signifer mask (no eyeholes, doesn\'t obscure your vision). While wearing it: +1 circumstance to Deception (Lie), Intimidation, and Deception DC vs Sense Motive. Expert in Intimidation and one of Arcana/Nature/Occultism/Religion.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Spellcasting class feature', 'Hellknight Armiger Dedication', 'Member of Hellknight Order', 'Passed Hellknight Test'],
    mechanics: 'Uncommon. Signifer mask: +1 Deception (Lie), Intimidation, Deception DC vs Sense Motive. Expert Intimidation + Arcana/Nature/Occultism/Religion.',
  },
  {
    id: 'hellknight-signifer-masked-casting',
    name: 'Masked Casting',
    source: 'Hellknight Signifer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you begin Casting a Spell while wearing your signifer\'s mask, you Avert your Gaze as a free action, protecting from visual effects.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Hellknight Signifer Dedication'],
    mechanics: 'Free action. Trigger: begin Casting a Spell. Avert Gaze. Requires signifer mask.',
  },
  {
    id: 'hellknight-signifer-gaze-of-veracity',
    name: 'Gaze of Veracity',
    source: 'Hellknight Signifer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Channel your mask\'s power to see truth. +1 Focus Point. While wearing mask, cast glimpse the truth as a divine focus spell.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Signifer Dedication', 'Ability to cast focus spells'],
    mechanics: '+1 FP. Gain glimpse the truth divine focus spell. Requires signifer mask.',
  },
  {
    id: 'hellknight-signifer-signifers-sight',
    name: 'Signifer\'s Sight',
    source: 'Hellknight Signifer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'While wearing your signifer\'s mask, gain darkvision. If dazzled and target concealed only from dazzle, reduce flat check DC from 5 to 3.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Signifer Dedication'],
    mechanics: 'Mask: darkvision + reduce dazzled concealment flat check DC to 3.',
  },
  {
    id: 'hellknight-signifer-armor-expertise',
    name: 'Signifer Armor Expertise',
    source: 'Hellknight Signifer (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'If you have expert proficiency in any armor or unarmored defense, you also gain expert proficiency in medium and heavy armor.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Hellknight Signifer Dedication'],
    mechanics: 'Expert any armor → expert medium + heavy armor.',
  },
];

// ══════════════════════════════════════════════════════════
export const STANDALONE_ARCHETYPE_FEATS_LEGACY_LO1: FeatEntry[] = [
  ...FIREBRAND_BRAGGART_FEATS,
  ...HELLKNIGHT_ARMIGER_FEATS,
  ...HELLKNIGHT_FEATS,
  ...HELLKNIGHT_SIGNIFER_FEATS,
];
