import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Grand Bazaar: Spell Trickster
// 26 feats — each modifies a specific spell
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=103
// ══════════════════════════════════════════════════════════

export const SPELL_TRICKSTER_FEATS: FeatEntry[] = [
  // ── Dedication ──
  {
    id: 'spell-trickster-dedication',
    name: 'Spell Trickster Dedication',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your experience with magic lets you specialize in casting certain spells, customizing familiar spells to create novel effects. Whenever you gain a feat from this archetype, you either learn to modify one spell or change a previous modification. Each time you Cast the corresponding spell, you decide whether to cast its normal or modified version. Only one modification per spell at a time. Choose up to two 4th-level spell trickster feats for which you meet the prerequisite; you gain those feats ignoring level.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Able to cast spells', 'Trained in Arcana, Nature, Occultism, or Religion'],
    mechanics: 'Gain 2 free 4th-level spell trickster feats. Each feat modifies one spell. One modification per spell at a time.',
  },

  // ── Level 4 feats ──
  {
    id: 'spell-trickster-agile-hand',
    name: 'Agile Hand',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast mage hand, you can modify its target to be thieves\' tools. The tools move up to 20 feet toward a device or lock. When you Sustain, you can attempt Thievery checks to Disable a Device or Pick a Lock within range at a –2 penalty. On a critical failure, the spell ends and you can\'t use this modification for 24 hours.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast mage hand'],
    mechanics: 'Modify mage hand: target thieves\' tools. Sustain to Thievery (–2) for Disable Device / Pick Lock. Crit fail: ends, 24h cooldown.',
  },
  {
    id: 'spell-trickster-barrier-shield',
    name: 'Barrier Shield',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast shield, you can modify it to create a solid barrier for cover instead of blocking. You can\'t use Shield Block with this modification, but you can Take Cover behind it for standard cover (only you benefit).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast shield'],
    mechanics: 'Modify shield: no Shield Block, but can Take Cover (1 action) for standard cover (you only).',
  },
  {
    id: 'spell-trickster-forceful-push',
    name: 'Forceful Push',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast mage hand, you can modify its target to be 1 creature. Make a spell attack roll against the target\'s Fortitude DC. On a success, push the target 5 feet away. On a critical success, push 10 feet away.',
    implemented: 'full',
    traits: ['Archetype', 'Attack'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast mage hand'],
    mechanics: 'Modify mage hand: target 1 creature. Spell attack vs Fortitude DC. Success: push 5 ft. Crit: push 10 ft.',
  },
  {
    id: 'spell-trickster-shining-arms',
    name: 'Shining Arms',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast light, you can modify its target to be 1 melee weapon (unattended or held by you/willing ally) and duration to 1 minute. When wielder critically hits, you can Dismiss the spell as a reaction to dazzle the foe for 1 round. After using this reaction, can\'t use this modification for 10 minutes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast light'],
    mechanics: 'Modify light: target melee weapon, 1 min. Crit hit → Dismiss (reaction) → dazzled 1 round. 10 min cooldown.',
  },
  {
    id: 'spell-trickster-summon-ensemble',
    name: 'Summon Ensemble',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast summon instrument, you can modify duration to sustained (up to 1 minute). Summon instruments equal to your spellcasting modifier that play autonomously. Once per turn on Sustain, choose an opponent within 30 feet who can hear; it attempts a Will save. On failure, it becomes off-guard for 1 round. Target is then immune for 24 hours.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast summon instrument'],
    mechanics: 'Modify summon instrument: sustained 1 min. Instruments = spellcasting mod. Sustain: 1 enemy Will save or off-guard 1 round. 24h immune.',
  },
  {
    id: 'spell-trickster-tracing-sigil',
    name: 'Tracing Sigil',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast sigil, you can modify it: the target leaves a magical trail. You and others can Track the target substituting Arcana, Nature, Occultism, or Religion for Survival. Must follow from where target has been. Only one target marked at a time; marking a second ends the first.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast sigil'],
    mechanics: 'Modify sigil: target leaves trackable magical trail. Arcana/Nature/Occultism/Religion instead of Survival. 1 marked target at a time.',
  },
  {
    id: 'spell-trickster-wild-lights',
    name: 'Wild Lights',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you cast dancing lights, you can modify duration to 1 minute and create a single floating light shaped like a Tiny creature instead of four lights. It hovers over your head; spend 1 action (concentrate) to direct it up to 30 feet. If it moves beyond 120 feet from you, it winks out.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast dancing lights'],
    mechanics: 'Modify dancing lights: 1 min, Tiny-creature light. 1 action to move 30 ft. Winks out beyond 120 ft.',
  },

  // ── Level 6 feats ──
  {
    id: 'spell-trickster-animate-net',
    name: 'Animate Net',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast animate rope, modify target to 1 net. The net throws itself at a Medium or smaller creature within 20 feet. Spell attack vs Reflex DC. Success: target is off-guard and takes –10 ft penalty to Speeds until Escape. Critical success: also immobilized. Escape DC = spell DC while spell lasts.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast animate rope'],
    mechanics: 'Modify animate rope: target 1 net. Spell attack vs Reflex DC. Success: off-guard + –10 Speed. Crit: immobilized. Escape DC = spell DC.',
  },
  {
    id: 'spell-trickster-confounding-image',
    name: 'Confounding Image',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast mirror image, modify duration to sustained (1 min) and range to 30 feet. Create an illusory duplicate in an unoccupied square. It takes up space (5 ft reach), allies can flank with it. AC = spell DC, saves = spell DC – 10. Ends if hit, fails a save, or you move 30+ ft away. Sustain to move it.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast mirror image'],
    mechanics: 'Modify mirror image: sustained 1 min, range 30 ft. Flanking-capable duplicate. AC = spell DC. Ends if hit/failed save/30+ ft away.',
  },
  {
    id: 'spell-trickster-disk-rider',
    name: 'Disk Rider',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast floating disk, modify duration to sustained (10 min). Heightened (3rd): holds 10 Bulk, you can ride it without ending the spell. While riding, Sustain moves it up to 30 ft or your Speed (slower). Can cross liquids but must end on solid ground.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast floating disk'],
    mechanics: 'Modify floating disk: sustained 10 min. Heightened 3rd: ride disk, Sustain = move 30 ft/Speed. Crosses liquids.',
  },
  {
    id: 'spell-trickster-drenching-mist',
    name: 'Drenching Mist',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast obscuring mist, add heightened (3rd) entry: non-magical fires in area auto-extinguished. Choose one magical fire or fire spell in area and attempt to counteract it.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast obscuring mist'],
    mechanics: 'Modify obscuring mist: Heightened 3rd: extinguish non-magic fire, counteract 1 magic fire.',
  },
  {
    id: 'spell-trickster-obscured-terrain',
    name: 'Obscured Terrain',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast obscuring mist, you can modify: the area becomes difficult terrain for creatures that can\'t see through fog or mist. You can Dismiss the cloud.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast obscuring mist'],
    mechanics: 'Modify obscuring mist: area is difficult terrain for creatures that can\'t see through fog. Dismissible.',
  },
  {
    id: 'spell-trickster-uneasy-rest',
    name: 'Uneasy Rest',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast sleep, modify: targets that failed or critically failed the save experience troubled dreams. When they wake, they are frightened 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast sleep'],
    mechanics: 'Modify sleep: failed/crit-failed targets wake frightened 1.',
  },
  {
    id: 'spell-trickster-volatile-grease',
    name: 'Volatile Grease',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you cast grease, modify target to 1 creature. Reflex save. Critical Success: unaffected. Success: weakness 2 to fire until end of your next turn; Interact to remove. Failure: weakness 2 to fire for 1 minute. Heightened (+2): weakness +1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast grease'],
    mechanics: 'Modify grease: 1 creature, Reflex. Success: weakness 2 fire (1 turn). Failure: weakness 2 fire (1 min). Heightened +2: +1 weakness.',
  },

  // ── Level 8 feats ──
  {
    id: 'spell-trickster-beacon-mark',
    name: 'Beacon Mark',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast sigil, add heightened (4th): you can spend 1 action (concentrate, detection, divination) to learn the direction to the marked target within 1 mile. If target is a creature (or carried by one), it can Will save vs your spell DC; success blocks for 1 day. One target at a time.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Tracing Sigil'],
    mechanics: 'Modify sigil: Heightened 4th: 1 action to locate target within 1 mile. Creature: Will save to block (1 day). 1 target at a time.',
  },
  {
    id: 'spell-trickster-larcenous-hand',
    name: 'Larcenous Hand',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast mage hand, modify: no duration, range 20 feet, target attended object within Bulk limit. Willing creature: hand carries item. Unwilling: attempt Steal (Thievery). Normal Steal restrictions apply. Crit fail: can\'t use for 1 hour. Master in Thievery: can Steal from combat/guarded targets (+1 action casting time).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Agile Hand', 'Pickpocket skill feat'],
    mechanics: 'Modify mage hand: range 20 ft, Steal attended objects. Crit fail: 1h cooldown. Master Thievery: Steal from guarded (+1 action).',
  },
  {
    id: 'spell-trickster-lingering-flames',
    name: 'Lingering Flames',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast fireball, modify: base damage decreases to 5d6 but deals 2 persistent fire damage to creatures that fail their save (doubled on crit fail). Heightened (+1): +1d6 damage and +2 persistent fire.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast fireball'],
    mechanics: 'Modify fireball: 5d6 base + 2 persistent fire on fail. Heightened +1: +1d6, +2 persistent.',
  },
  {
    id: 'spell-trickster-scattered-fire',
    name: 'Scattered Fire',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast fireball, you can modify its area to be two non-overlapping 10-foot bursts instead of the standard area.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast fireball'],
    mechanics: 'Modify fireball: area becomes two non-overlapping 10-ft bursts.',
  },
  {
    id: 'spell-trickster-siphoning-touch',
    name: 'Siphoning Touch',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast vampiric touch, modify: instead of gaining temporary HP yourself, grant them to an ally within 30 feet. After 1 minute, the ally loses remaining temporary HP.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast vampiric touch'],
    mechanics: 'Modify vampiric touch: grant temp HP to ally within 30 ft instead of self. Lasts 1 min.',
  },
  {
    id: 'spell-trickster-smoldering-explosion',
    name: 'Smoldering Explosion',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast fireball heightened to at least 4th level, modify: the fireball leaves a brief cloud of smoke in its area (as obscuring mist but smoke, lasting 1 round).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast fireball'],
    mechanics: 'Modify fireball (4th+): leaves smoke cloud (as obscuring mist, 1 round).',
  },
  {
    id: 'spell-trickster-steal-vitality',
    name: 'Steal Vitality',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you cast vampiric touch, modify: instead of gaining temp HP, if target fails/crit fails its save, attempt a counteract check to remove clumsy or enfeebled from yourself. If condition was from an ongoing effect you don\'t remove, it returns end of next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast vampiric touch'],
    mechanics: 'Modify vampiric touch: on target fail, counteract clumsy/enfeebled on self. Ongoing: returns end of next turn.',
  },

  // ── Level 10 feats ──
  {
    id: 'spell-trickster-surrounding-flames',
    name: 'Surrounding Flames',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you cast wall of fire, modify: instead of a 5-foot-thick, 10-foot-radius ring, form the wall into a 10-foot-radius hemisphere of fire.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast wall of fire'],
    mechanics: 'Modify wall of fire: 10-ft-radius fire hemisphere instead of ring.',
  },
  {
    id: 'spell-trickster-toppling-tentacles',
    name: 'Toppling Tentacles',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When you cast black tentacles, replace standard effects: tentacles attempt to Trip each creature (spell attack vs Reflex DC). Success: knocked prone + 3d6 bludgeoning. Each turn end in area: Trip if not prone, 1d6 bludgeoning if already prone. Area is difficult terrain.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast black tentacles'],
    mechanics: 'Modify black tentacles: Trip all (spell attack vs Reflex DC). Success: prone + 3d6 B. Turn end: Trip/1d6 B. Difficult terrain.',
  },

  // ── Level 12 feats ──
  {
    id: 'spell-trickster-choking-smoke',
    name: 'Choking Smoke',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When you cast fireball heightened to at least 6th level, modify: reduce damage by 6d6. The fireball leaves behind a lingering cloud of toxic smoke (as stinking cloud) in its area.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Smoldering Explosion'],
    mechanics: 'Modify fireball (6th+): –6d6 damage, leaves stinking cloud in area.',
  },
  {
    id: 'spell-trickster-directed-poison',
    name: 'Directed Poison',
    source: 'Spell Trickster (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'When you cast cloudkill, modify duration to sustained (1 min). The cloud no longer moves away each round. When you Sustain, you can move the cloud 10 feet in a direction of your choice.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Spell Trickster Dedication', 'Ability to cast cloudkill'],
    mechanics: 'Modify cloudkill: sustained 1 min. No auto-move. Sustain: move cloud 10 ft.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_LEGACY_SM3: FeatEntry[] = [
  ...SPELL_TRICKSTER_FEATS,
];
