import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Book of the Dead (Part 1)
// Exorcist, Ghost, Ghoul
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// EXORCIST  (Book of the Dead pg. 22–23)
// Category: Mystical / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=103
// ──────────────────────────────────────────────────────────

export const EXORCIST_FEATS: FeatEntry[] = [
  {
    id: 'exorcist-dedication',
    name: 'Exorcist Dedication',
    source: 'Exorcist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned to attract, quell, and purify spirits, housing them in a spirit dwelling. One mundane object becomes your spirit dwelling. Each day during daily preparations, it attracts a spirit wisp. You can spend 10 minutes to attract another. You can collect stronger spirit remnants from vanquished undead (Collect Spirit Remnant [3-actions]). You gain Spirit\'s Mercy [reaction] (necromancy): when you take positive/negative damage or damage from a haunt/ghost/incorporeal undead, expend 1 wisp or remnant for resistance. Wisp: resistance = 2× level. Remnant: resistance = 3× remnant source level.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Occultism or Religion'],
    mechanics: 'Spirit dwelling attracts wisps daily. Collect Spirit Remnant [3-actions] from destroyed ghosts/haunts within 30 ft. Spirit\'s Mercy [reaction]: resist positive/negative (or all from haunts/incorporeal) = 2×level (wisp) or 3×source level (remnant).',
  },
  {
    id: 'exorcist-cast-out',
    name: 'Cast Out',
    source: 'Exorcist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You attempt to cast a malevolent entity out of the creature or object it\'s possessing. Roll a counteract check against the possession effect; you must be within 30 feet. Your counteract level is half your level rounded up, and your counteract modifier is your Occultism modifier, Religion modifier, or spell DC – 10 (whichever highest). Success: entity driven out, can\'t possess that target for 1 week. Failure: possessing creature immune to your Cast Out for a year and a day.',
    implemented: 'full',
    traits: ['Abjuration', 'Archetype', 'Concentrate', 'Manipulate'],
    actionCost: 2,
    prerequisites: ['Exorcist Dedication'],
    mechanics: '2 actions. Counteract possession within 30 ft. Counteract level = half level (round up). Modifier = highest of Occultism/Religion/spell DC–10. Success: expelled 1 week. Fail: immune 1 year and 1 day.',
  },
  {
    id: 'exorcist-spirits-absolution',
    name: 'Spirit\'s Absolution',
    source: 'Exorcist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You purify a spirit by absolving it of its sins and regrets. This restores your Hit Points or those of an adjacent ally. If you expend a spirit wisp, the target recovers 1d4 HP per level you have. If you expend a spirit remnant, the target recovers 1d6 HP per level of the source creature.',
    implemented: 'full',
    traits: ['Archetype', 'Healing', 'Necromancy', 'Positive'],
    actionCost: 1,
    prerequisites: ['Exorcist Dedication'],
    mechanics: '1 action. Cost: 1 wisp or remnant. Requirement: holding spirit dwelling. Heal self or adjacent ally. Wisp: 1d4×level HP. Remnant: 1d6×source level HP.',
  },
  {
    id: 'exorcist-spirits-anguish',
    name: 'Spirit\'s Anguish',
    source: 'Exorcist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You purify a spirit by coaxing it to release its anguish in a final cathartic howl. This deals sonic damage to all creatures in a 30-foot cone, with a basic Will save against your class DC or spell DC (whichever higher). Wisp: 1d4 sonic per level. Remnant: 1d6 sonic per source level.',
    implemented: 'full',
    traits: ['Archetype', 'Evocation', 'Sonic'],
    actionCost: 2,
    prerequisites: ['Exorcist Dedication'],
    mechanics: '2 actions. Cost: 1 wisp or remnant. Requirement: holding spirit dwelling. 30-ft cone sonic damage, basic Will. Wisp: 1d4×level. Remnant: 1d6×source level.',
  },
  {
    id: 'exorcist-enticing-dwelling',
    name: 'Enticing Dwelling',
    source: 'Exorcist (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your spirit dwelling is particularly inviting to spirit wisps. During your daily preparations, and whenever you spend 10 minutes to find more wisps, you entice two wisps into your spirit dwelling instead of one.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Exorcist Dedication'],
    mechanics: 'Daily preparations and 10-min ritual attract 2 wisps instead of 1.',
  },
];

// ──────────────────────────────────────────────────────────
// GHOST  (Book of the Dead pg. 46–47)
// Category: Undead / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=104
// ──────────────────────────────────────────────────────────

export const GHOST_FEATS: FeatEntry[] = [
  {
    id: 'ghost-dedication',
    name: 'Ghost Dedication',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have risen as a shell of your former self, a spirit of mist and anguish. You gain the ghost, spirit, and undead traits and basic undead benefits. Your undead craving is to settle your unfinished business. You also gain the incorporeal trait (can\'t pass through solid objects unless you select Pass Through). Floating: replace land Speed with equal fly Speed, can\'t rise more than a few inches above ground. Items: spend 10 minutes to incorporate physical items into your form. Incorporated weapons gain ghost touch. Attacks: unarmed attacks become magical and deal negative damage. Strength: keep normal Str but only for checks against incorporeal creatures. Choose a bound site and unfinished business with your GM.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You died and returned as a ghost'],
    mechanics: 'Rare. Ghost/spirit/undead/incorporeal traits. Fly Speed = land Speed (ground-tethered). Incorporate items 10 min (ghost touch). Unarmed = magical negative. Choose bound site + unfinished business.',
  },
  {
    id: 'ghost-frightful-moan',
    name: 'Frightful Moan',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You let out a low moan of anguish. Living creatures in a 30-foot emanation must attempt a Will save against your class DC or spell DC (whichever higher). Success: unaffected, immune 1 minute. Failure: frightened 1. Critical Failure: frightened 2.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Divine', 'Emotion', 'Enchantment', 'Fear', 'Mental'],
    actionCost: 2,
    prerequisites: ['Ghost Dedication'],
    mechanics: '2 actions. 30-ft emanation. Will save. Success: immune 1 min. Failure: frightened 1. Crit Fail: frightened 2.',
  },
  {
    id: 'ghost-ghostly-resistance',
    name: 'Ghostly Resistance',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your ghostly form gains resistance to many forms of damage but your max HP is reduced by your level. You gain resistance 1 to all damage except force, positive, and ghost touch weapons (resistance 2 if non-magical). At 10th level: 2 (4 non-magical). At 16th level: 3 (5 non-magical).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghost Dedication'],
    mechanics: 'Max HP reduced by level. Resistance 1 all (except force/positive/ghost touch), 2 vs non-magical. Scales at 10th (2/4) and 16th (3/5).',
  },
  {
    id: 'ghost-ghostly-grasp',
    name: 'Ghostly Grasp',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your control over your ghostly form grows. You gain the advanced undead benefits and can interact with physical objects, with limits. You can attempt Strength-based skill checks against physical creatures and objects. You can Interact with physical objects, but the action has no effect unless you succeed at a DC 20 Athletics or DC 20 Thievery check.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghost Dedication'],
    mechanics: 'Advanced undead benefits. Interact with physical objects: DC 20 Athletics or Thievery check required.',
  },
  {
    id: 'ghost-ghost-flight',
    name: 'Ghost Flight',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can suppress your tether to the ground, overcoming your resistance to fly free. For 10 minutes, your fly Speed doesn\'t restrict you to only a few inches off the ground, allowing you to travel to any height you choose.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Ghost Dedication'],
    mechanics: '2 actions. Frequency: 1/day. Unrestricted flight for 10 minutes.',
  },
  {
    id: 'ghost-pass-through',
    name: 'Pass Through',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Filtering your form through the substance of an object, you can pass through walls, doors, and more. You Fly up to your Speed. During this movement, you can try to move through one object with an Acrobatics check (DC 30 for 5-ft wall, 15 for door, 10 for window). Success: treat square as difficult terrain. Failure: movement ends. You can\'t pass through magical force barriers.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 3,
    prerequisites: ['Ghost Dedication', 'Master in Acrobatics'],
    mechanics: '3 actions. Frequency: 1/10 min. Fly up to Speed, attempt Acrobatics to move through 1 solid object. DC varies by thickness. Can\'t pass through force effects.',
  },
  {
    id: 'ghost-rejuvenation',
    name: 'Rejuvenation',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'The call of your unfinished business recreates you after destruction. When you\'re destroyed, you reform after 2d4 days within your bound site, fully healed. If your unfinished business is resolved while you\'re waiting, you pass on immediately unless you and the GM determine you have new unfinished business.',
    implemented: 'full',
    traits: ['Rare', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghost Dedication'],
    mechanics: 'On destruction: reform in 2d4 days at bound site, fully healed. Resolved business = pass on (or new business).',
  },
  {
    id: 'ghost-unlimited-ghost-flight',
    name: 'Unlimited Ghost Flight',
    source: 'Ghost (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You put your connection to the material world farther behind you. Your fly Speed no longer restricts the height you can fly. When you use Ghost Flight, instead of its normal effect, you gain a +10-foot status bonus to your fly Speed for 10 minutes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghost Flight'],
    mechanics: 'Permanent unrestricted fly height. Ghost Flight now grants +10 ft status to fly Speed for 10 min.',
  },
];

// ──────────────────────────────────────────────────────────
// GHOUL  (Book of the Dead pg. 48–49)
// Category: Undead / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=105
// ──────────────────────────────────────────────────────────

export const GHOUL_FEATS: FeatEntry[] = [
  {
    id: 'ghoul-dedication',
    name: 'Ghoul Dedication',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have succumbed to ghoul fever, dying and returning as a ghoul. You gain the ghoul and undead traits and basic undead benefits. Your undead craving is for dead flesh. You gain two unarmed attacks in the brawling group: claw (1d4 slashing, agile, finesse) and jaws (1d6 piercing, finesse). You gain the Consume Flesh action [one-action] (manipulate): adjacent to a Small+ corpse that died within 1 hour, you devour a chunk and become satiated for 1 hour. Many ghoul feats have extra abilities when satiated (using them ends satiation).',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You were killed by ghoul fever'],
    mechanics: 'Rare. Ghoul/undead traits + basic undead benefits. Claw: 1d4 S (agile, finesse, brawling). Jaws: 1d6 P (finesse, brawling). Consume Flesh [1-action]: satiated 1 hr from adjacent fresh corpse.',
  },
  {
    id: 'ghoul-replenishing-consumption',
    name: 'Replenishing Consumption',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you devour corpses and satiate your hunger, you also recover from some of your wounds. Once every 10 minutes, when you Consume Flesh, you regain 1d6 Hit Points for every 2 levels you have, rounded up.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghoul Dedication'],
    mechanics: 'Consume Flesh: heal 1d6 per 2 levels (1/10 min).',
  },
  {
    id: 'ghoul-swift-leap',
    name: 'Swift Leap',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your undead physiology allows you to leap quickly toward or away from your opponent. You Leap. This movement doesn\'t trigger reactions. If satiated, you can end satiation to instead High Jump or Long Jump without triggering reactions.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Ghoul Dedication'],
    mechanics: '1 action. Leap (no reactions). Satiated: end satiation for High/Long Jump (no reactions).',
  },
  {
    id: 'ghoul-feverish-enzymes',
    name: 'Feverish Enzymes',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your claws and fangs exude infectious enzymes. Strike with claw or jaws — deals negative damage instead of normal type; on hit, target halves any healing until start of your next turn. Target or adjacent ally can spend 2 Interact actions to remove. If satiated, end satiation on hit to increase duration to 1 minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Ghoul Dedication'],
    mechanics: '2 actions. Claw/jaws Strike deals negative. Hit: target halves healing until next turn (2 Interact to remove). Satiated: end for 1-min duration.',
  },
  {
    id: 'ghoul-grave-strength',
    name: 'Grave Strength',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'The flesh you\'ve consumed has made you stronger. You gain the advanced undead benefits. In addition, you gain a +5-foot status bonus to your Speed while satiated.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghoul Dedication'],
    mechanics: 'Advanced undead benefits. +5 ft status to Speed while satiated.',
  },
  {
    id: 'ghoul-paralyzing-slash',
    name: 'Paralyzing Slash',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your enzymes can paralyze foes. Strike with claw or jaws. If you hit a living non-elf creature, it becomes paralyzed unless it succeeds at a Fortitude save against your class DC or spell DC (whichever higher). Immune 24 hours regardless. Paralyzed creature can attempt a new save at end of each turn (DC decreases by 1 each save).',
    implemented: 'full',
    traits: ['Archetype', 'Incapacitation', 'Necromancy', 'Occult'],
    actionCost: 2,
    prerequisites: ['Feverish Enzymes'],
    mechanics: '2 actions. Claw/jaws Strike vs living non-elf. Fort save or paralyzed. DC decreases by 1 per new save. Immune 24 hrs.',
  },
  {
    id: 'ghoul-sickening-bite',
    name: 'Sickening Bite',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your saliva causes severe nausea in the living. When you critically hit a creature with your jaws, the creature is sickened 1 (disease). If satiated, you can end satiation to make target sickened 1 on a regular hit instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghoul Dedication'],
    mechanics: 'Jaws crit: sickened 1 (disease). Satiated: end for sickened 1 on regular hit.',
  },
  {
    id: 'ghoul-glutton-for-flesh',
    name: 'Glutton for Flesh',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'If you Consume Flesh while satiated, you become fully satiated (3 hours, then satiated 1 hour). If fully satiated when an ability would end satiation, you instead stop being fully satiated but remain satiated. If you have Grave Strength, fully satiated = +10 ft status to Speed instead of +5.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Ghoul Dedication'],
    mechanics: 'Consume Flesh while satiated: fully satiated 3 hrs → satiated 1 hr. Ending satiation drops to satiated instead. Grave Strength: +10 ft Speed when fully satiated.',
  },
  {
    id: 'ghoul-corpse-stench',
    name: 'Corpse Stench',
    source: 'Ghoul (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your body exudes an overwhelming scent of decay in a 10-foot emanation. Any creature starting its turn in the aura must succeed at a Fort save against your class DC or spell DC or be sickened 1 (plus slowed 1 on crit fail). While in the aura, –2 circumstance to saves vs disease and to recover from sickened. Success: immune 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Aura', 'Olfactory'],
    actionCost: 'passive',
    prerequisites: ['Ghoul Dedication'],
    mechanics: '10-ft emanation aura. Fort save at turn start. Fail: sickened 1. Crit Fail: sickened 1 + slowed 1. In aura: –2 circ to disease saves/sickened recovery. Success: immune 1 min.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_LEGACY_BD1: FeatEntry[] = [
  ...EXORCIST_FEATS,
  ...GHOST_FEATS,
  ...GHOUL_FEATS,
];
