import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — Howl of the Wild
// Werecreature, Winged Warrior
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// WERECREATURE  (Howl of the Wild pg. 76–79)
// Category: Background / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=225
// ──────────────────────────────────────────────────────────

export const WERECREATURE_FEATS: FeatEntry[] = [
  {
    id: 'werecreature-dedication',
    name: 'Werecreature Dedication',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'re a werecreature, able to shift between your humanoid shape, an animal shape, and a monstrous hybrid of the two. You gain the beast and werecreature traits. Choose your werecreature type (werebat, werebear, wereboar, werecrocodile, weremoose, wererat, wereshark, weretiger, or werewolf). Once chosen, this can\'t be changed. You gain the Toughness feat but also a weakness to silver equal to half your level. You gain the Change Shape action [one-action] (concentrate, polymorph, primal): transform into your hybrid or animal shape. Equipment transforms with you. Your animal shape cannot use weapons, shields, or other held items and cannot use manipulate actions. You gain a movement speed, unarmed attacks, and potentially other abilities based on your type. These unarmed attacks are in the brawling group. You can Dismiss the effect to return to humanoid shape, and you resume humanoid shape automatically at 0 HP. On the night of the full moon, you automatically Change Shape into hybrid and can\'t voluntarily activate or dismiss it until sunrise.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You were born into a lineage of true werecreatures or were afflicted with the curse of the werecreature'],
    mechanics: 'Rare. Gain beast and werecreature traits. Choose type: werebat (10ft/fly 15ft, fangs 1d8P), werebear (25ft, jaws 1d8P + claw 1d6S agile), wereboar (30ft, tusk 1d8S sweep), werecrocodile (25ft/swim 15ft, jaws 1d8P grapple), weremoose (25ft, antler 1d8P shove), wererat (25ft, jaws 1d6P + claw 1d4S agile/finesse, Small animal), wereshark (15ft/swim 25ft, jaws 1d8P grapple, hybrid amphibious), weretiger (25ft, jaws 1d8P + claw 1d6S agile), werewolf (30ft, jaws 1d8P trip). Gain Toughness. Weakness silver = half level. Change Shape [1-action]. Full moon: forced hybrid.',
    subChoices: { label: 'Choose werecreature type', options: [
      { id: 'werebat', name: 'Werebat', description: '10ft/fly 15ft, fangs 1d8P' },
      { id: 'werebear', name: 'Werebear', description: '25ft, jaws 1d8P + claw 1d6S agile' },
      { id: 'wereboar', name: 'Wereboar', description: '30ft, tusk 1d8S sweep' },
      { id: 'werecrocodile', name: 'Werecrocodile', description: '25ft/swim 15ft, jaws 1d8P grapple' },
      { id: 'weremoose', name: 'Weremoose', description: '25ft, antler 1d8P shove' },
      { id: 'wererat', name: 'Wererat', description: '25ft, jaws 1d6P + claw 1d4S agile/finesse' },
      { id: 'wereshark', name: 'Wereshark', description: '15ft/swim 25ft, jaws 1d8P grapple' },
      { id: 'weretiger', name: 'Weretiger', description: '25ft, jaws 1d8P + claw 1d6S agile' },
      { id: 'werewolf', name: 'Werewolf', description: '30ft, jaws 1d8P trip' },
    ] },
  },
  {
    id: 'werecreature-animal-fleetness',
    name: 'Animal Fleetness',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'re adept at using your animal shape\'s natural means of locomotion. While you\'re in animal shape, the Speeds granted by that shape increase by 10 feet.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Animal shape Speeds +10 ft.',
  },
  {
    id: 'werecreature-beastkin-resilience',
    name: 'Beastkin Resilience',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve regained beastkin protections after becoming a full werecreature. You no longer gain silver weakness from Werecreature Dedication.',
    implemented: 'full',
    traits: ['Archetype', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication', 'Beastkin heritage'],
    mechanics: 'Removes silver weakness from Werecreature Dedication.',
  },
  {
    id: 'werecreature-feral-senses',
    name: 'Feral Senses',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'The eyes and noses of animals are naturally sharper than most humanoids. While in your hybrid or animal shape, you gain low-light vision and imprecise scent with a range of 30 feet.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Hybrid/animal shape: gain low-light vision + imprecise scent 30 ft.',
  },
  {
    id: 'werecreature-antler-rush',
    name: 'Antler Rush',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Stride twice. If you end your movement within your antlers\' reach of an enemy, you can Disarm, Shove, or Strike with your antlers.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication', 'Weremoose type'],
    mechanics: '2 actions. Requirement: moose or hybrid shape. Stride twice. If within antler reach of enemy: free Disarm, Shove, or antler Strike.',
  },
  {
    id: 'werecreature-bear-hug',
    name: 'Bear Hug',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You hug your opponent. You make another claw Strike against the same target. If this Strike hits, the target is grabbed until the end of your next turn, unless you move or your target Escapes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication', 'Werebear type'],
    mechanics: '2 actions. Requirement: bear or hybrid shape, last action successful claw Strike. Make claw Strike; on hit target grabbed until end of next turn.',
  },
  {
    id: 'werecreature-death-roll',
    name: 'Death Roll',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You corkscrew your body, twisting your victim. You attempt a jaws Strike against the grabbed creature, with a +2 circumstance bonus if you\'re fighting in water. If the Strike hits, you knock the creature prone; if it misses, they escape your grab.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Werecreature Dedication', 'Werecrocodile type'],
    mechanics: '1 action. Requirement: crocodile or hybrid shape, creature grabbed. Jaws Strike (+2 circ in water). Hit: target prone. Miss: target escapes grab.',
  },
  {
    id: 'werecreature-echolocation',
    name: 'Echolocation',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'When you take the Seek action, you can use hearing as a precise sense with a range of 40 feet until the start of your next turn. You can also use this sense while you Search.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication', 'Werebat type'],
    mechanics: 'Seek: hearing becomes precise 40 ft until start of next turn. Also works with Search.',
  },
  {
    id: 'werecreature-fearful-symmetry',
    name: 'Fearful Symmetry',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You attack with a feline grace as captivatingly beautiful as it is deadly. All enemies within 30 feet of the creature you critically hit must attempt a Will save against your class DC. Enemies that fail their saves become frightened 1 and are fascinated with you for 1 round. Your hostile actions don\'t end this fascination, but those of your allies do. Regardless of the effects of the save, the creature is immune to Fearful Symmetry for 1 hour.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Fear', 'Mental', 'Visual'],
    actionCost: 1,
    prerequisites: ['Werecreature Dedication', 'Weretiger type'],
    mechanics: '1 action. Requirement: hybrid or tiger shape, last action a critical unarmed Strike. Will save vs class DC for enemies within 30 ft. Fail: frightened 1 + fascinated 1 round (hostile actions from allies end it). Immune 1 hour.',
  },
  {
    id: 'werecreature-feeding-frenzy',
    name: 'Feeding Frenzy',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your serrated teeth rip and tear at your prey. When you critically hit with your jaws Strike from Werecreature Dedication, your target takes 1d4 persistent bleed damage and you gain a +1 circumstance bonus to jaws Strikes against the target until the end of your turn. If you have scent as a special sense, it\'s a precise sense with double its normal range when locating creatures taking persistent bleed damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication', 'Wereshark type'],
    mechanics: 'Jaws crit: 1d4 persistent bleed + +1 circ to jaws vs target until end of turn. Scent becomes precise with double range for locating bleeding creatures.',
  },
  {
    id: 'werecreature-pack-attack',
    name: 'Pack Attack',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have mastered techniques for hunting alongside your pack. Your Strikes deal an additional 1d4 precision damage to creatures within reach of at least two of your allies.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication', 'Werewolf type'],
    mechanics: 'Strikes deal +1d4 precision to creatures within reach of 2+ allies.',
  },
  {
    id: 'werecreature-plague-rat',
    name: 'Plague Rat',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your bites carry a cursed infection. When you hit and deal damage to a creature with a jaws Strike while in hybrid or rat shape, the creature is cursed until the start of your next turn. Whenever they regain Hit Points during that time, they must attempt a Fortitude save against your class DC or spell DC (whichever is higher). Success: regain HP normally. Failure: regain half HP. Critical Failure: regain no HP.',
    implemented: 'full',
    traits: ['Archetype', 'Curse', 'Disease', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication', 'Wererat type'],
    mechanics: 'Jaws hit in hybrid/rat shape: target cursed until start of next turn. On HP recovery, Fort save vs class/spell DC. Success: normal HP. Failure: half HP. Crit Fail: no HP.',
  },
  {
    id: 'werecreature-rushing-boar',
    name: 'Rushing Boar',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You embrace the pain of the triggering attack, allowing it to drive you into a violent rush. You Stride in a straight line toward the triggering creature.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Emotion', 'Mental'],
    actionCost: 'reaction',
    prerequisites: ['Werecreature Dedication', 'Wereboar type'],
    mechanics: 'Reaction. Trigger: non-adjacent creature damages you. Requirement: boar or hybrid shape. Stride in straight line toward triggering creature.',
  },
  {
    id: 'werecreature-cornered-animal',
    name: 'Cornered Animal',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You become more dangerous when surrounded by enemies. You make unarmed Strikes against two different creatures flanking you. The attacks take a –2 penalty if the unarmed weapon is not agile. Both attacks count toward your multiple attack penalty, but the penalty doesn\'t increase until after you\'ve made both of them.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication'],
    mechanics: '2 actions. Requirement: animal or hybrid form, flanked. Strike 2 different flanking creatures. –2 penalty if not agile. Both count toward MAP but penalty applies after both.',
  },
  {
    id: 'werecreature-feral-mending',
    name: 'Feral Mending',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can heal your wounds while reshaping your flesh. You regain 1d6 Hit Points for every 2 levels you have (minimum 1d6).',
    implemented: 'full',
    traits: ['Archetype', 'Healing', 'Primal'],
    actionCost: 1,
    prerequisites: ['Werecreature Dedication', 'You were not afflicted with the curse of the werecreature'],
    mechanics: '1 action. Frequency: once per hour. Requirement: previous action was Change Shape. Heal 1d6 per 2 levels (min 1d6).',
  },
  {
    id: 'werecreature-terrifying-transformation',
    name: 'Terrifying Transformation',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your flesh tears and warps as you transform. Attempt Intimidation checks to Demoralize each enemy within 30 feet. This Demoralize loses the auditory trait and gains the visual trait, and you don\'t need to share a language. Regardless of the results of your checks, each creature is temporarily immune to Terrifying Transformation for 1 minute.',
    implemented: 'full',
    traits: ['Archetype', 'Visual'],
    actionCost: 1,
    prerequisites: ['Werecreature Dedication', 'You were afflicted with the curse of the werecreature'],
    mechanics: '1 action. Demoralize all enemies within 30 ft. Visual (not auditory), no shared language needed. Immune 1 minute.',
  },
  {
    id: 'werecreature-you-dont-smell-right',
    name: 'You Don\'t Smell Right',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can sniff out fellow werecreatures and master impersonators alike. You gain scent as an imprecise sense with a range of 30 feet or extend the range of your scent by 30 feet. When a creature that\'s transformed into another form or is Impersonating a specific creature passes within range of your scent ability, the GM rolls a secret Perception check for you to realize that the creature is transformed, even if you didn\'t spend an action to Seek. When you actively Seek a creature within range of your scent, you gain a +2 circumstance bonus to your Perception check to determine if it\'s disguised.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Gain scent imprecise 30 ft (or extend existing by 30 ft). Auto secret Perception check when transformed/Impersonating creature enters scent range. +2 circ to Seek disguised creatures in scent range.',
  },
  {
    id: 'werecreature-dire-growth',
    name: 'Dire Growth',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You transform into a primal reflection of your animal shape. If you aren\'t already in your animal shape from Werecreature Dedication, you Change Shape into it. As long as you stay in animal shape, you have the effects of enlarge.',
    implemented: 'full',
    traits: ['Archetype', 'Primal'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication', 'Your animal shape is not Small'],
    mechanics: '2 actions. Change Shape into animal if not already. Gain effects of enlarge while in animal shape.',
  },
  {
    id: 'werecreature-feral-lunge',
    name: 'Feral Lunge',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You spring on an unsuspecting opponent, tearing at them with your teeth. You Stride up to 10 feet and make a jaws Strike at the end of that movement. If you began this action hidden, you remain hidden until after this Strike. If you have a fly or swim Speed, you can Fly or Swim up to 10 feet instead of Stride.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Werecreature Dedication', 'Your animal shape grants a fangs or jaws unarmed attack'],
    mechanics: '1 action. Requirement: hybrid or animal shape. Stride 10 ft + jaws Strike. Stay hidden if started hidden. Can Fly/Swim 10 ft instead.',
  },
  {
    id: 'werecreature-feral-scramble',
    name: 'Feral Scramble',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Sinking your claws in, you propel yourself at shocking speed. You Climb up to your land Speed and make a claw Strike at any point during that movement. After you finish the movement, attempt an Athletics check against the surface\'s Climb DC. Success: you maintain your position. Failure: you slide down 60 feet or to the ground without taking falling damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication', 'Your animal shape grants a claw unarmed attack'],
    mechanics: '2 actions. Requirement: hybrid or animal shape. Climb up to land Speed + claw Strike during movement. Athletics vs Climb DC: success = hold position, failure = slide 60 ft (no fall damage).',
  },
  {
    id: 'werecreature-feral-toss',
    name: 'Feral Toss',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You hurl foes away with a shake of your head. You Strike with your antler, horn, or tusk. If you hit and damage a creature of your size or smaller, push it 5 feet from you (10 feet on a critical hit). This is forced movement.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication', 'Your animal shape grants an antler, horn, or tusk unarmed attack'],
    mechanics: '2 actions. Requirement: hybrid or animal shape. Strike with antler/horn/tusk. Hit vs ≤ your size: push 5 ft (10 ft on crit). Forced movement.',
  },
  {
    id: 'werecreature-touch-of-lunacy',
    name: 'Touch of Lunacy',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'In moments of viciousness, your curse can partially infect your prey. Whenever you critically succeed with an unarmed attack from the werecreature archetype, the target must attempt a Fortitude save against the higher of your class DC or spell DC, or become clumsy 2 until the beginning of your next turn as their bones elongate and form warps. On a critical failure, the target is also clumsy 1 for one minute as the transformation lingers.',
    implemented: 'full',
    traits: ['Archetype', 'Curse', 'Morph', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'On crit with werecreature unarmed attack: target Fort save vs class/spell DC. Fail: clumsy 2 until start of next turn. Crit Fail: also clumsy 1 for 1 minute.',
  },
  {
    id: 'werecreature-pouncing-transformation',
    name: 'Pouncing Transformation',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'By transforming as you move, you attack from odd angles. You Change Shape or Dismiss the change then Stride. Any creature adjacent to you at the end of your movement is off-guard until the end of your turn and is then temporarily immune for 1 hour.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Werecreature Dedication', 'Your animal shape has a land Speed only'],
    mechanics: '1 action. Change Shape or Dismiss, then Stride. Adjacent creatures off-guard until end of turn. Immune 1 hour.',
  },
  {
    id: 'werecreature-shared-tide',
    name: 'Shared Tide',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You Swim up to twice the normal distance. Any ally you pass within 30 feet of during that movement gains your swim Speed until the beginning of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Werecreature Dedication', 'Your animal shape has a swim Speed'],
    mechanics: '2 actions. Swim up to 2× distance. Allies within 30 ft during movement gain your swim Speed until start of next turn.',
  },
  {
    id: 'werecreature-undying-beast',
    name: 'Undying Beast',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You can be injured by non-silver sources but recover with staggering speed. When you are reduced to 0 Hit Points by non-silver damage and don\'t immediately die from a death effect or a high dying value, you stabilize immediately afterward. You gain the wounded condition as normal.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Reduced to 0 HP by non-silver damage: stabilize immediately (not death effects or high dying). Wounded applies normally.',
  },
  {
    id: 'werecreature-wings-of-the-moon',
    name: 'Wings of the Moon',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You can stay aloft with Fly normally when using the fly Speed from your animal shape, letting you fly long distances without breaks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication', 'Your animal shape has a fly Speed'],
    mechanics: 'Fly normally with animal shape fly Speed. No need to land between turns.',
  },
  {
    id: 'werecreature-scarred-hide',
    name: 'Scarred Hide',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your hide is an impenetrable mass of scars, accrued over countless bloody conflicts. When in your hybrid or animal shape, you gain resistance to non-silver slashing damage equal to half your level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Hybrid/animal shape: resistance to non-silver slashing = half level.',
  },
  {
    id: 'werecreature-rapid-hybridization',
    name: 'Rapid Hybridization',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When danger threatens, your instincts kick in, and you can assume a different shape at a moment\'s notice. You use Change Shape to enter your hybrid shape.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Free action. Trigger: you roll initiative. Change Shape into hybrid shape.',
  },
  {
    id: 'werecreature-force-of-nature',
    name: 'Force of Nature',
    source: 'Werecreature (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You\'re a nigh-unstoppable killing machine, with only silver able to quell your rampage. When in hybrid or animal shape, you gain fast healing 5. If you take damage from a silver weapon, your fast healing deactivates until the end of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Healing', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Werecreature Dedication'],
    mechanics: 'Hybrid/animal shape: fast healing 5. Silver damage: fast healing deactivates until end of next turn.',
  },
];

// ──────────────────────────────────────────────────────────
// WINGED WARRIOR  (Howl of the Wild pg. 82–83)
// Category: Combat Style / Core — PFS Standard
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=227
// ──────────────────────────────────────────────────────────

export const WINGED_WARRIOR_FEATS: FeatEntry[] = [
  {
    id: 'winged-warrior-dedication',
    name: 'Winged Warrior Dedication',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Through rigorous training, you have strengthened your wings, granting you enough thrust to gain additional altitude. When you make a horizontal Leap, increase the distance by 10 feet up to a maximum of your Speed. Any fly Speed granted by ancestry feats and other permanent wings increases by 5 feet.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You have permanent wings (such as from an ancestry or graft)'],
    mechanics: 'Horizontal Leap distance +10 ft (max your Speed). Permanent fly Speeds +5 ft.',
  },
  {
    id: 'winged-warrior-battering-wings',
    name: 'Battering Wings',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Though not powerful enough for flight, your wings can deliver a thrashing to anyone who gets close. You gain a wing unarmed attack that deals 1d4 bludgeoning damage. Your wing attack is in the brawling group and has the agile, finesse, and unarmed traits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: 'Gain wing unarmed attack: 1d4 B, brawling group, agile + finesse + unarmed traits.',
  },
  {
    id: 'winged-warrior-gusting-spell',
    name: 'Gusting Spell',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You manipulate the currents of your spell\'s energy, allowing you to gracefully glide with your wings. If the next action you use is to Cast a Spell with the air or electricity trait, you can Fly up to 10 feet before or after the spell is cast.',
    implemented: 'full',
    traits: ['Air', 'Archetype', 'Manipulate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '1 action. Spellshape. Next action: Cast Spell with air/electricity trait. Fly 10 ft before or after casting.',
  },
  {
    id: 'winged-warrior-wing-bounce',
    name: 'Wing Bounce',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You rush forward, flapping your wings for a bit of lift, and can use that momentum to knock down a foe. Leap, and if you land within melee reach of at least one enemy, you can attempt to Trip that enemy. You don\'t need to have one hand free. If you successfully knock the target prone, you can Leap again. If you have a fly Speed, you can Fly instead of Leap.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '2 actions. Leap + Trip if within reach (no free hand needed). On prone: Leap again. Fly instead of Leap if you have fly Speed.',
  },
  {
    id: 'winged-warrior-sunbird-glare',
    name: 'Sunbird Glare',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'By keeping your feathers clean and sleek, you can catch the light across your wings to create a startling glare in the eyes of a creature within 20 feet. The target must succeed at a Fortitude save against your class DC or be dazzled for 1 round (1 minute on a critical failure). Regardless of their result, the target is temporarily immune to Sunbird Glare for 10 minutes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '1 action. Requirement: bright light. Target within 20 ft, Fort save vs class DC. Fail: dazzled 1 round. Crit Fail: dazzled 1 minute. Immune 10 minutes.',
  },
  {
    id: 'winged-warrior-feathered-flechettes',
    name: 'Feathered Flechettes',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Unfurling your wings in a quick snap, you send feathers scattering in all directions. Creatures in a 15-foot emanation take 6d6 slashing damage (basic Reflex save against your class DC). This increases to 10d6 if your unarmed attacks have a greater striking rune, such as by etching it onto handwraps of mighty blows, and 16d6 if they have a major striking rune.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '2 actions. Frequency: once per hour. 15-ft emanation slashing damage: 6d6 (10d6 greater striking, 16d6 major striking). Basic Reflex vs class DC.',
  },
  {
    id: 'winged-warrior-pluck-from-the-sky',
    name: 'Pluck From the Sky',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'The skies are your rightful place, and you will not suffer another to occupy them. Make a Strike against a flying creature. If the attack deals damage, the target must attempt a Reflex save against your class DC. Critical Success: no effect. Success: target falls 15 feet (no falling damage if reaches ground). Failure: target falls 30 feet (no falling damage). Critical Failure: as failure, but takes falling damage.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '2 actions. Access: tengu, strix, or awakened animal (flying). Strike vs flying creature. On damage: Reflex vs class DC. Success: fall 15 ft. Failure: fall 30 ft. Crit Fail: fall 30 ft + falling damage.',
  },
  {
    id: 'winged-warrior-wing-shove',
    name: 'Wing Shove',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You spread your wings wide, pushing foes away from you. Attempt to Shove one of the flanking enemies, and then make a second Shove attempt against a different enemy that is flanking you. You don\'t need one hand free. The second Shove attempt has the same multiple attack penalty as the first and doesn\'t count toward your MAP. On a success or critical success, you can\'t Stride after a target, but that target is also off-guard until the beginning of their next turn. On a critical failure, you\'re off-guard until the beginning of your next turn instead of falling prone.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '1 action. Requirement: flanked by 2+ enemies. Shove one flanker, then Shove another (same MAP, doesn\'t increase). No free hand needed. Success: can\'t Stride after but target off-guard. Crit Fail: off-guard (not prone).',
  },
  {
    id: 'winged-warrior-falcon-swoop',
    name: 'Falcon Swoop',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Like the fastest of predatory birds, you soar toward your prey at great speeds. Fly twice. At any point during this movement, you can make a Strike against one enemy within reach or within the first range increment of a ranged weapon. That enemy is off-guard against the Strike if you\'re attacking them from above.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '2 actions. Requirement: fly Speed. Fly twice + Strike during movement. Target off-guard if attacking from above.',
  },
  {
    id: 'winged-warrior-redirecting-draft',
    name: 'Redirecting Draft',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You flap your wings to blow arrows off course. You or the triggering ally gain a +2 circumstance bonus to AC against the triggering attack. If the attack misses, you redirected the attack\'s flight path.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: 'Reaction. Trigger: you or ally within 10 ft targeted by ranged physical Strike. +2 circ to AC vs that attack.',
  },
  {
    id: 'winged-warrior-smooth-hover',
    name: 'Smooth Hover',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You remain airborne through sheer effort. You don\'t fall, even if you didn\'t use Fly or a similar action this turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: 'Free action. Frequency: once per hour. Trigger: airborne at end of turn. Don\'t fall even without Fly action this turn.',
  },
  {
    id: 'winged-warrior-thunderous-landing',
    name: 'Thunderous Landing',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You hurl away enemies with the force of your landing. You Fly and, if you end your movement on a solid surface, your landing sends out a shock wave of air. Each creature within 10 feet of your landing position must succeed at a Reflex save against your class DC or be pushed 10 feet away. This is forced movement.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '1 action. Requirement: fly Speed, airborne. Fly + land: Reflex vs class DC, 10-ft push on fail. Forced movement.',
  },
  {
    id: 'winged-warrior-bombing-run',
    name: 'Bombing Run',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Using your elevation and speed to your advantage, you deliver aerial payloads with greater force. You Fly and can Interact to draw a bomb. At any point during your movement, you can also make a Strike with an alchemical bomb. The bomb deals its splash damage to every creature within 10 feet of the target.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '2 actions. Requirement: fly Speed. Fly + Interact to draw bomb + Strike with bomb during movement. Splash: 10 ft of target.',
  },
  {
    id: 'winged-warrior-cratering-drop',
    name: 'Cratering Drop',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You follow up your enemy\'s fall, driving you both to the earth in a meteoric descent. You Fly straight down, increasing the amount the enemy falls by your Fly speed. If you reach the ground, you drive the enemy into the ground, dealing double the normal falling damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Pluck From the Sky'],
    mechanics: '1 action. Requirement: previous action was Pluck From the Sky (melee), target failed/crit failed. Fly down: target falls extra = your fly Speed. Ground: double falling damage.',
  },
  {
    id: 'winged-warrior-sonic-strafe',
    name: 'Sonic Strafe',
    source: 'Winged Warrior (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You can now achieve such flight speeds that your passage splits the very air. Fly twice. Any creature that is adjacent to you at any point during your movement takes 10d6 sonic damage (basic Fortitude save against your class DC). On a critical failure, the creature is also deafened for 1 hour.',
    implemented: 'full',
    traits: ['Air', 'Archetype', 'Sonic'],
    actionCost: 2,
    prerequisites: ['Winged Warrior Dedication'],
    mechanics: '2 actions. Frequency: once per hour. Requirement: fly Speed. Fly twice. Adjacent creatures: 10d6 sonic, basic Fort. Crit Fail: deafened 1 hour.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_HW: FeatEntry[] = [
  ...WERECREATURE_FEATS,
  ...WINGED_WARRIOR_FEATS,
];
