import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — A through C
// Aldori Duelist, Alter Ego, Captain, Clawdancer,
// Crossbow Infiltrator
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// ALDORI DUELIST  (Battlecry! pg. 54)
// Category: Faction / Combat Style — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=324
// ──────────────────────────────────────────────────────────

export const ALDORI_DUELIST_FEATS: FeatEntry[] = [
  {
    id: 'aldori-duelist-dedication',
    name: 'Aldori Duelist Dedication',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become trained in your choice of Acrobatics or Athletics (expert if already trained). You gain Additional Lore for Dueling Lore (if already trained, you also gain a Lore skill of your choice). You have familiarity with Aldori dueling swords, treating them as martial weapons for proficiency. You gain access to Aldori dueling swords.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in martial weapons'],
    mechanics: 'Access: You are from the Broken Lands region. Trained in Acrobatics or Athletics (expert if already trained). Gain Dueling Lore via Additional Lore. Aldori dueling swords treated as martial. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'aldori-duelist-dueling-acumen',
    name: 'Dueling Acumen',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'When you\'re in a duel or can see exactly one creature, you can always roll Dueling Lore for initiative. If you do so while in a duel, you must choose from either Deception, Intimidation, or Perception when you roll for initiative; you\'re considered to have rolled the chosen skill for initiative for the purpose of dueling actions.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'In a duel or when seeing exactly one creature → can use Dueling Lore for initiative. During duel: choose Deception, Intimidation, or Perception for initiative (counts as that skill for dueling actions).',
  },
  {
    id: 'aldori-duelist-aldori-parry',
    name: 'Aldori Parry',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Aldori dueling swords you wield gain the parry trait. If you have your other hand or hands free while wielding an Aldori dueling sword, you gain a +2 circumstance bonus to AC while parrying instead of the usual +1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Aldori dueling swords gain parry trait. Free hand → +2 circumstance bonus to AC while parrying (instead of +1).',
  },
  {
    id: 'aldori-duelist-duelists-edge',
    name: 'Duelist\'s Edge',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain a +2 circumstance bonus to the triggering initiative roll, and you can immediately Interact to draw an Aldori dueling sword.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Trigger: You roll initiative, and you are observing at least one opponent. +2 circumstance bonus to initiative. Interact to draw Aldori dueling sword.',
  },
  {
    id: 'aldori-duelist-aldori-riposte',
    name: 'Aldori Riposte',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You riposte when your enemy leaves an opening. Make a melee Strike against or attempt to Disarm the triggering opponent using your Aldori dueling sword.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Aldori Parry'],
    mechanics: 'Trigger: An opponent within your reach critically fails a Strike against you. Req: Using Aldori dueling sword to parry. Make melee Strike or Disarm using Aldori dueling sword.',
  },
  {
    id: 'aldori-duelist-unnerving-prowess',
    name: 'Unnerving Prowess',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You attempt to Demoralize the target of your Strike or Disarm. This Demoralize attempt does not have the auditory trait, nor do you take a penalty to the check if the target doesn\'t understand your language.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Trigger: Crit succeed at Strike or Disarm with Aldori dueling sword, or succeed at Strike or Disarm during your first turn of an encounter. Attempt Demoralize (no auditory trait, no language penalty).',
  },
  {
    id: 'aldori-duelist-saving-slash',
    name: 'Saving Slash',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You quickly whirl your blade, trying to deflect enough momentum to avoid the worst of the attack. Attempt a DC 15 flat check. If you succeed, the attack becomes a normal hit instead of a critical hit.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Trigger: An opponent critically hits you with a melee attack. DC 15 flat check → success downgrades crit to normal hit.',
  },
  {
    id: 'aldori-duelist-one-on-one',
    name: 'One-on-One',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You attempt to Feint and then Strike an adjacent creature with an Aldori dueling sword. The Feint attempt must be against the same target as your Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Aldori Duelist Dedication', 'Trained in Deception'],
    mechanics: 'Freq: 1/round. Feint + Strike (same target, must be adjacent, must use Aldori dueling sword).',
  },
  {
    id: 'aldori-duelist-aldoris-retort',
    name: 'Aldori\'s Retort',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'At the start of each of your turns, you gain an additional reaction that you can use only for Aldori Riposte, Saving Slash, or any dueling action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Gain extra reaction each turn for Aldori Riposte, Saving Slash, or dueling actions only.',
  },
  {
    id: 'aldori-duelist-duelists-form',
    name: 'Duelist\'s Form',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'While in this stance, you are quickened. You can use this extra action only to Step or use a single-action activity gained from the Aldori duelist archetype. If you use your free hand for anything, this stance ends. When this stance ends, you become fatigued until you rest for at least 10 minutes.',
    implemented: 'full',
    traits: ['Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Req: Wielding only Aldori dueling sword with other hand free; not fatigued. Stance → quickened (extra action only for Step or Aldori duelist single-action activities). Ends if free hand used → fatigued until 10 min rest.',
  },
  {
    id: 'aldori-duelist-tempo-duelist',
    name: 'Tempo Duelist',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You move with an unpredictable tempo, shifting between unnervingly slow and rapid movements. You are concealed for 1 round. As the nature of this effect still leaves your location obvious, you can\'t use this concealment to Hide or Sneak.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Gain concealed for 1 round. Cannot use to Hide or Sneak (location remains obvious).',
  },
  {
    id: 'aldori-duelist-devastating-duelist',
    name: 'Devastating Duelist',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Strike an opponent with your Aldori dueling sword. If the Strike is successful, attempt a Dueling Lore check against the target\'s Will DC. On a success, the target becomes frightened 2. This is an emotion, fear, and mental effect.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Aldori Duelist Dedication'],
    mechanics: 'Strike with Aldori dueling sword → success: Dueling Lore vs target Will DC → frightened 2 (emotion, fear, mental).',
  },
  {
    id: 'aldori-duelist-aldori-swordlord',
    name: 'Aldori Swordlord',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You are an Aldori swordlord. You gain free room and board at the Aldori Academy. You can use Dueling Lore instead of Diplomacy to Make an Impression or Request if the target knows of Aldori swordlords. Whenever you successfully Strike with an Aldori dueling sword, you gain 5 temporary HP (10 on crit) lasting 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Aldori Duelist Dedication', 'You have taken the last name of Aldori and sworn to the Aldori swordpact'],
    mechanics: 'Free room/board at Aldori Academy. Dueling Lore for Make an Impression/Request. Strike success → 5 temp HP (crit → 10 temp HP), lasts 1 round. Special: Cannot also take Swordlord Exile.',
  },
  {
    id: 'aldori-duelist-swordlord-exile',
    name: 'Swordlord Exile',
    source: 'Aldori Duelist (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'You have abandoned or been abandoned by the Aldori Academy. Aldori swordlords are honor-bound to challenge you on sight. You can use Dueling Lore instead of Intimidation to Coerce and Demoralize while your Aldori dueling sword is visible. The first time you hit a creature with an Aldori dueling sword each round, you deal 5 additional precision damage.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Aldori Duelist Dedication', 'You have broken or forsaken the Aldori swordpact'],
    mechanics: 'Dueling Lore for Coerce/Demoralize (sword visible). First hit per round → +5 precision damage. Special: Cannot also take Aldori Swordlord.',
  },
];

// ──────────────────────────────────────────────────────────
// ALTER EGO  (Dark Archives Remastered pg. 126)
// Category: Core / Mystical — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=258
// ──────────────────────────────────────────────────────────

export const ALTER_EGO_FEATS: FeatEntry[] = [
  {
    id: 'alter-ego-dedication',
    name: 'Alter Ego Dedication',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become an expert in Deception. You gain the Assume a Role activity. When you Assume a Role, you set up a specific cover identity with a new name. While in the role, you gain a +1 circumstance bonus to Deception checks to Impersonate your cover identity and a +1 circumstance bonus to Deception-based initiative rolls. You also gain a +1 circumstance bonus to Lore checks involving your cover identity\'s area of expertise.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Deception', 'Trained in Stealth'],
    mechanics: 'Expert in Deception. Gain Assume a Role activity (set up cover identity). While in role: +1 circ to Deception to Impersonate, +1 circ to Deception-based initiative, +1 circ to relevant Lore. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'alter-ego-change-of-face',
    name: 'Change of Face',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You don\'t need a disguise kit when Impersonating someone as part of Assuming a Role or while maintaining a role. Your Impersonate attempts gain the occult trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'No disguise kit needed for Impersonate during Assume a Role. Impersonate gains occult trait.',
  },
  {
    id: 'alter-ego-fake-it-till-you-make-it',
    name: 'Fake It Till You Make It',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you Assume a Role, choose two skills. While in the role, you gain a +1 circumstance bonus to checks with those skills. At 7th level, you can choose three skills instead of two.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Assume a Role → choose 2 skills (3 at 7th level) → +1 circumstance bonus to those skill checks while in role.',
  },
  {
    id: 'alter-ego-in-plain-sight',
    name: 'In Plain Sight',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'While you are in a role, you can use Deception instead of Stealth for Avoid Notice during exploration. When you do, creatures observing you don\'t automatically notice inconsistencies in your Impersonation from your movement alone.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'While in role: Deception instead of Stealth for Avoid Notice. Observers don\'t auto-notice Impersonation inconsistencies from movement.',
  },
  {
    id: 'alter-ego-sound-mirror',
    name: 'Sound Mirror',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can cast figment as an innate occult cantrip. You also gain silence and ventriloquism as innate occult spells, each usable once per day. Your spell DC for these is your class DC or spell DC, whichever is higher, using Charisma as your spellcasting attribute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Innate occult: figment (cantrip), silence (1/day), ventriloquism (1/day). DC = class DC or spell DC (higher), CHA-based.',
  },
  {
    id: 'alter-ego-muscle-mimicry',
    name: 'Muscle Mimicry',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'You study an opponent\'s movements and copy their technique. You gain a +1 circumstance bonus to the same action against the triggering creature before the end of your next turn. If you\'re a master in Deception, the bonus is +2.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Trigger: A creature you can see uses Disarm, Escape, Grapple, Shove, or Trip. Gain +1 circ bonus (or +2 if master in Deception) to the same action vs that creature before end of next turn.',
  },
  {
    id: 'alter-ego-swap-reflections',
    name: 'Swap Reflections',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You project your own reflection into a reflective surface within 120 feet (such as a mirror, pool of water, or polished metal) and then step through, teleporting to that location and swapping places with a creature adjacent to the surface. The creature must attempt a Will save against your class DC or spell DC, whichever is higher.',
    implemented: 'full',
    traits: ['Archetype', 'Conjuration', 'Occult', 'Teleportation'],
    actionCost: 2,
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Teleport to reflective surface within 120 ft, swap with adjacent creature. Will save vs class/spell DC (higher). Incapacitation on crit fail. Freq: 1/10 minutes.',
  },
  {
    id: 'alter-ego-borrow-memories',
    name: 'Borrow Memories',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You gain mind probe as an innate occult spell usable once per day. When you Assume a Role based on a specific person and use this spell on someone who knows that person, you can ask up to 10 questions about the person and their behaviors, mannerisms, and knowledge, rather than the usual questions.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Innate occult: mind probe (1/day). Enhanced during Assume a Role targeting specific person → up to 10 questions about that person.',
  },
  // Shared feats from Firebrands (Legacy)
  {
    id: 'alter-ego-were-on-the-list',
    name: 'We\'re on the List',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 3,
    description: 'Legacy (Firebrands pg. 91). You and your allies can talk or sneak your way past guards and bouncers. When you successfully Impersonate someone with the access you need or Lie to convince someone to let your group in, you can bring along up to 3 additional creatures who also gainentry.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Shared: Alter Ego / Archaeologist. Legacy (Firebrands). Success on Impersonate or Lie to gain entry → bring up to 3 allies past as well.',
  },
  {
    id: 'alter-ego-illusory-identity',
    name: 'Illusory Identity',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Legacy (Firebrands pg. 92). You can cast illusory disguise as an innate occult spell at will, heightened to half your level rounded up. You must be in a role to use this.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Shared: Alter Ego / Vigilante. Legacy (Firebrands). Innate occult illusory disguise at will (heightened to half level, rounded up). Must be in role.',
  },
  {
    id: 'alter-ego-it-was-me-all-along',
    name: 'It Was Me All Along!',
    source: 'Alter Ego (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Legacy (Firebrands pg. 93). When you reveal your true identity by dropping a disguise or otherwise making your real identity known, attempt a Deception check against the Perception DC of each creature within 30 feet. On a success, the creature is stunned 1; on a critical success, stunned 2.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Emotion', 'Mental'],
    actionCost: 'free',
    prerequisites: ['Alter Ego Dedication'],
    mechanics: 'Shared: Alter Ego / Vigilante. Legacy (Firebrands). Trigger: You reveal your true identity. Deception vs Perception DC of creatures within 30 ft. Success → stunned 1, crit success → stunned 2.',
  },
];

// ──────────────────────────────────────────────────────────
// CAPTAIN  (Battlecry! pg. 82)
// Category: Combat Style / Core — Uncommon, PFS Restricted
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=312
// ──────────────────────────────────────────────────────────

export const CAPTAIN_FEATS: FeatEntry[] = [
  {
    id: 'captain-dedication',
    name: 'Captain Dedication',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become trained in Diplomacy or Intimidation (if trained in both, train another skill instead). You gain Group Impression or Group Coercion skill feat (if you have both, gain any 1st-level skill feat you qualify for). You gain a dedicated follower with the minion trait who begins as a novice follower.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Charisma 12', 'You don\'t have an animal companion, construct companion, or other similar companion'],
    mechanics: 'Trained in Diplomacy or Intimidation. Gain Group Impression or Group Coercion. Gain novice follower (minion trait). Special: Once you have a follower, can never take feats granting animal/construct companion. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'captain-additional-follower',
    name: 'Additional Follower',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Another novice follower with the minion trait joins you. When you gain a 2nd follower, you also gain Call Follower (exploration activity, 1 minute: switch your active follower for another).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication'],
    mechanics: 'Gain additional novice follower (minion). 2nd follower → gain Call Follower (exploration, 1 min). Special: Selectable multiple times (max 4 total followers).',
  },
  {
    id: 'captain-experienced-follower',
    name: 'Experienced Follower',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'All your followers become experienced followers. Even without using Direct Follower, your active follower can still use 1 action on your turn to Stride or Strike (at any point while you aren\'t taking an action). If they do, that\'s all actions they get that round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication'],
    mechanics: 'Followers upgrade to experienced. Active follower gets free 1 action per turn (Stride or Strike only) even without Direct Follower. If used, no further directing that round.',
  },
  {
    id: 'captain-leader-of-all',
    name: 'Leader of All',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can take followers from any common ancestry (uncommon/rare at GM discretion). Your follower gains their ancestry\'s traits, size, Speeds, languages, and special abilities. They don\'t use the ancestry\'s HP or attribute boosts/flaws, and don\'t gain abilities that allow extra action types.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication'],
    mechanics: 'Followers from any common ancestry. Gain ancestry traits, size, Speeds, languages, special abilities. No ancestry HP/attribute changes, no extra action type abilities.',
  },
  {
    id: 'captain-cadre',
    name: 'Cadre',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'A loyal cadre of retainers joins you (non-combat NPCs). When in a place where your cadre can assist: +1 circumstance bonus to Craft, Create a Forgery, Earn Income, and Subsist checks and other downtime activities at GM discretion. Retraining is faster: for every 5 days spent, you make a week\'s worth of progress.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication', 'Expert in Diplomacy or Intimidation'],
    mechanics: '+1 circ to Craft, Create a Forgery, Earn Income, Subsist (with cadre present). Retraining: 5 days = 1 week progress.',
  },
  {
    id: 'captain-tactical-guidance',
    name: 'Tactical Guidance',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can spend 2 actions to Direct your Follower instead of 1. If you do, your follower gains an additional action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication'],
    mechanics: 'Spend 2 actions to Direct Follower → follower gains extra action (3 total instead of 2).',
  },
  {
    id: 'captain-veteran-follower',
    name: 'Veteran Follower',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'All your followers become veteran followers.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Experienced Follower'],
    mechanics: 'Followers upgrade to veteran rank. See Follower rules for stat improvements.',
  },
  {
    id: 'captain-coordinated-tactics',
    name: 'Coordinated Tactics',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Whenever you and your active follower are adjacent to the same foe, you are both flanking that foe with each other, regardless of your actual positions.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication'],
    mechanics: 'You + active follower adjacent to same foe → automatic flanking (ignores positioning requirements).',
  },
  {
    id: 'captain-exceptional-follower',
    name: 'Exceptional Follower',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'All your followers become exceptional followers.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Veteran Follower'],
    mechanics: 'Followers upgrade to exceptional rank. See Follower rules for stat improvements.',
  },
  {
    id: 'captain-legendary-leader',
    name: 'Legendary Leader',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 15,
    description: 'When you first attempt to Coerce or Make an Impression on someone, you can attempt a DC 11 flat check to determine if they have heard of you. On a success, +2 circumstance modifier to the skill check. You can also Earn Income using the prerequisite skill with a +2 circumstance bonus (+3 if you have Cadre).',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication', 'Legendary in Diplomacy or Intimidation'],
    mechanics: 'DC 11 flat check on first Coerce/Make an Impression → success: +2 circ bonus. Earn Income via Diplomacy/Intimidation +2 circ (+3 with Cadre).',
  },
  {
    id: 'captain-peerless-captain',
    name: 'Peerless Captain',
    source: 'Captain (Archetype)',
    category: 'archetype',
    level: 20,
    description: 'When you have an active follower in an encounter, you are quickened. You can use the extra action only to Direct your Follower.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Captain Dedication'],
    mechanics: 'Active follower in encounter → quickened (extra action for Direct Follower only).',
  },
];

// ──────────────────────────────────────────────────────────
// CLAWDANCER  (Howl of the Wild pg. 68)
// Category: Combat Style / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=253
// ──────────────────────────────────────────────────────────

export const CLAWDANCER_FEATS: FeatEntry[] = [
  {
    id: 'clawdancer-dedication',
    name: 'Clawdancer Dedication',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You gain two stance actions: Claw Stance (frenzied claw: 1d6 S, agile, finesse, grapple, versatile P) and Talon Stance (spinning talon: 1d8 S, finesse, sweep). Both are brawling group unarmed attacks.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Permanent unarmed claw or talon attack (such as one granted by your ancestry or a graft)'],
    mechanics: 'Claw Stance [1-action] (stance): frenzied claw 1d6 S, brawling, agile, finesse, grapple, unarmed, versatile P. Talon Stance [1-action] (stance): spinning talon 1d8 S, brawling, finesse, sweep, unarmed. No free hand needed for spinning talon. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'clawdancer-claw-snag',
    name: 'Claw Snag',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You hook into the target, pulling yourself forward and rending flesh. You shift to claw stance if you aren\'t in it already, then make a frenzied claw Strike against the triggering creature.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Trigger: A creature attempts to Escape while you have them grappled or restrained. Shift to claw stance (if not already) → frenzied claw Strike vs triggering creature.',
  },
  {
    id: 'clawdancer-dashing-pounce',
    name: 'Dashing Pounce',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You Leap, and if you end adjacent to an enemy, you make two frenzied claw unarmed Strikes against it. Apply MAP normally. If both Strikes miss, you fall prone.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Claw stance, two open hands. Leap → adjacent to enemy → two frenzied claw Strikes (normal MAP). Both miss → fall prone.',
  },
  {
    id: 'clawdancer-talon-sweep',
    name: 'Talon Sweep',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You shift to talon stance if you weren\'t in it already. If the Strike misses, you can make a spinning talon Strike against any creature flanking you.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Trigger: A creature attempts to Strike you while flanking you. Shift to talon stance → if triggering Strike misses, make spinning talon Strike vs any flanking creature.',
  },
  {
    id: 'clawdancer-abscission-shards',
    name: 'Abscission Shards',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You twist your claw, breaking off a piece in your target. The shard deals 1d6 persistent bleed damage (2d6 with 3 weapon damage dice, 3d6 with 4 dice).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Last action was successful frenzied claw or spinning talon Strike. 1d6 persistent bleed (2d6 with greater striking, 3d6 with major striking).',
  },
  {
    id: 'clawdancer-hindquarter-kick',
    name: 'Hindquarter Kick',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You shift to talon stance and make two spinning talon Strikes against the grabbed creature. Apply MAP normally. You then release the grabbed creature.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Claw stance, grabbed a creature. Shift to talon stance → two spinning talon Strikes (normal MAP) → release grabbed creature.',
  },
  {
    id: 'clawdancer-spinning-stand',
    name: 'Spinning Stand',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You enter talon stance if you weren\'t already, make a spinning talon Strike against an enemy in reach, and then Stand. No -2 penalty for attacking while prone; your Stand doesn\'t trigger reactions. Spend 2 actions to make two spinning talon Strikes instead (must be against separate targets).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Prone. 1-action: talon stance + spinning talon Strike + Stand (no prone penalty, Stand doesn\'t trigger reactions). 2-action variant: two Strikes vs separate targets then Stand.',
  },
  {
    id: 'clawdancer-wheeling-grab',
    name: 'Wheeling Grab',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You shift into claw stance and Tumble Through. If you moved through an enemy\'s space, you can Grapple it.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Clawdancer Dedication', 'Trained in Acrobatics'],
    mechanics: 'Shift to claw stance → Tumble Through → if through enemy space, can Grapple that enemy.',
  },
  {
    id: 'clawdancer-feline-dance',
    name: 'Feline Dance',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You roll twice on the Reflex save and take the higher result. If you were in claw stance, you shift to talon stance, and vice versa.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Fortune'],
    actionCost: 'reaction',
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Access: Catfolk ancestry. Freq: 1/hour. Trigger: Attempt a basic Reflex save while in claw or talon stance. Roll twice, take higher. Switch stance (claw↔talon).',
  },
  {
    id: 'clawdancer-tear-tendons',
    name: 'Tear Tendons',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Make two frenzied claw attacks against the same target (MAP increases normally). If both hit, the target must succeed at a Fortitude save vs. your class DC or be enfeebled 2 for 1 round; on a critical failure, enfeebled 2 for 1 minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Claw stance, two open hands. Two frenzied claw Strikes (same target, normal MAP). Both hit → Fort save vs class DC: fail → enfeebled 2 (1 round), crit fail → enfeebled 2 (1 minute).',
  },
  {
    id: 'clawdancer-hunting-snag',
    name: 'Hunting Snag',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Make a claw or talon unarmed Strike. On a critical hit, if the trigger is a move action, disrupt that action. If it hits and the creature left a square adjacent to you, you can Step into that square.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 'reaction',
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Trigger: Creature within reach uses move action or leaves a square during move action. Claw/talon Strike; crit hit → disrupt move. Hit + creature left adjacent square → can Step into that square.',
  },
  {
    id: 'clawdancer-springboard',
    name: 'Springboard',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You Leap (doesn\'t trigger reactions from the struck enemy). If you land within melee reach of an enemy, you can make a spinning talon Strike against them.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Previous action was successful spinning talon Strike vs adjacent foe. Leap (no reactions from struck enemy). Land within melee reach → spinning talon Strike.',
  },
  {
    id: 'clawdancer-claw-and-talon-flow',
    name: 'Claw and Talon Flow',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You Strike with your current stance\'s unarmed attack, then switch into the other stance (frenzied claw Strike → talon stance, or spinning talon Strike → claw stance).',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: In claw or talon stance. Strike with current stance → switch to other stance.',
  },
  {
    id: 'clawdancer-precise-hooks',
    name: 'Precise Hooks',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When you critically hit with your claw or talon, you apply an additional critical specialization effect: claw stance → knife weapon group effect; talon stance → axe group effect. These are in addition to the normal brawling critical specialization effect.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Crit with claw/talon → extra crit spec: claw stance → knife group crit spec, talon stance → axe group crit spec (in addition to brawling crit spec).',
  },
  {
    id: 'clawdancer-storm-of-claws',
    name: 'Storm of Claws',
    source: 'Clawdancer (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'Strike three times (MAP increases normally). After each attack that hits and deals damage, you can Step.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 3,
    prerequisites: ['Clawdancer Dedication'],
    mechanics: 'Req: Claw or talon stance. Three Strikes (normal MAP). After each hit that deals damage → can Step.',
  },
];

// ──────────────────────────────────────────────────────────
// CROSSBOW INFILTRATOR  (Battlecry! pg. 56)
// Category: Combat Style / Core
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=90
// ──────────────────────────────────────────────────────────

export const CROSSBOW_INFILTRATOR_FEATS: FeatEntry[] = [
  {
    id: 'crossbow-infiltrator-dedication',
    name: 'Crossbow Infiltrator Dedication',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You gain familiarity with the gauntlet bow, hand crossbow, and repeating hand crossbow. Treat the repeating hand crossbow as martial and the gauntlet bow as simple for proficiency. If you\'re at least expert, you gain access to critical specialization. You also gain Infiltrator\'s Draw: Interact to draw the weapon then Strike (or Strike then stow), once per round.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Stealth'],
    mechanics: 'Familiarity: gauntlet bow (simple), hand crossbow, repeating hand crossbow (martial). Expert+ → crit spec. Infiltrator\'s Draw [1-action] (freq: 1/round): draw + Strike, or Strike + stow. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'crossbow-infiltrator-crescent-cross-training',
    name: 'Crescent Cross Training',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain familiarity with the crescent cross, treating both its configurations as simple weapons. You gain Crescent Spray [2-actions] (flourish): Strike up to three times with ranged crescent cross. Each attack counts toward MAP but penalty doesn\'t increase until all attacks are made.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crossbow Infiltrator Dedication'],
    mechanics: 'Crescent cross familiarity (both configs as simple). Archetype feats for gauntlet bow also work with crescent cross. Crescent Spray [2-actions] (flourish): up to 3 ranged Strikes, MAP applied after all.',
  },
  {
    id: 'crossbow-infiltrator-repeating-hand-crossbow-training',
    name: 'Repeating Hand Crossbow Training',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You gain access to repeating hand crossbows and repeater bandoliers. If you have Running Reload or similar, you can reload a magazine as a 3-action activity (2-action with repeater bandolier) after performing the other granted action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crossbow Infiltrator Dedication'],
    mechanics: 'Access: repeating hand crossbows, repeater bandoliers. Running Reload compatibility: 3-action (reload magazine + other action) or 2-action with repeater bandolier.',
  },
  {
    id: 'crossbow-infiltrator-infiltrators-reload',
    name: 'Infiltrator\'s Reload',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You Interact to reload a weapon you have familiarity with from this archetype, then either Hide, Sneak, or Take Cover.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Crossbow Infiltrator Dedication', 'Expert in Stealth'],
    mechanics: 'Interact (reload archetype weapon) + Hide, Sneak, or Take Cover.',
  },
  {
    id: 'crossbow-infiltrator-reloading-trick',
    name: 'Reloading Trick',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Interact to reload your hand crossbow or gauntlet bow and attempt a ranged Strike with it. If you have Repeating Hand Crossbow Training, you can use this with a repeating hand crossbow to load an entire magazine, but only fire one bolt before it jams.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish', 'Manipulate'],
    actionCost: 1,
    prerequisites: ['Crossbow Infiltrator Dedication'],
    mechanics: 'Req: Wielding unloaded hand crossbow or gauntlet bow. Reload + ranged Strike. With Repeating Hand Crossbow Training: load full magazine but only 1 bolt before jam.',
  },
  {
    id: 'crossbow-infiltrator-lethargy-poisoner',
    name: 'Lethargy Poisoner',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'During daily preparations, prepare a dose of lethargy poison from ordinary materials. Expert in Crafting → stupor poison instead. Master → 2 doses, legendary → 3 doses. DC = class DC. Only you can use them; they expire at next daily preparations.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crossbow Infiltrator Dedication', 'Trained in Crafting'],
    mechanics: 'Daily prep: craft lethargy poison (expert Crafting → stupor poison). Master → 2 doses, legendary → 3. DC = class DC. Personal use, expire at next daily prep.',
  },
  {
    id: 'crossbow-infiltrator-infiltration-assassination',
    name: 'Infiltration Assassination',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Make a melee Strike using your gauntlet bow as a gauntlet. If successful, automatically latch onto the target (grabbed condition), then make a ranged Strike against them with your gauntlet bow. This ranged Strike does not trigger reactions normally triggered by ranged attacks. You can apply an injury poison as a free action before the ranged Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Crossbow Infiltrator Dedication'],
    mechanics: 'Req: Wielding loaded gauntlet bow. Melee Strike (gauntlet) → success: target grabbed → ranged Strike (no ranged reaction triggers). Free action: apply held injury poison before ranged Strike.',
  },
  {
    id: 'crossbow-infiltrator-unseen-shot',
    name: 'Unseen Shot',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'The first time each round that you Strike a target you are undetected or unnoticed by while using a weapon you have familiarity with from this archetype, you are hidden from the target after the attack, as they cannot tell where the attack came from.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Crossbow Infiltrator Dedication'],
    mechanics: 'First Strike per round while undetected/unnoticed with archetype weapon → remain hidden after attack (not observed).',
  },
  {
    id: 'crossbow-infiltrator-infiltrators-blitz',
    name: 'Infiltrator\'s Blitz',
    source: 'Crossbow Infiltrator (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You can attempt to Escape any immobilizing effect. You gain a +10-foot circumstance bonus to your Speed and can Stride up to three times. At any point during each Stride, you can Strike with an archetype weapon and immediately Interact to reload it. Afterward, you become fatigued for 1 minute.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 3,
    prerequisites: ['Crossbow Infiltrator Dedication'],
    mechanics: 'Attempt Escape. +10 ft Speed. Three Strides, each with Strike + Interact (reload) at any point. Fatigued 1 minute after.',
  },
];

// ══════════════════════════════════════════════════════════
// CATALOG — Non-Core Archetype Feats A–C
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_AC: FeatEntry[] = [
  ...ALDORI_DUELIST_FEATS,
  ...ALTER_EGO_FEATS,
  ...CAPTAIN_FEATS,
  ...CLAWDANCER_FEATS,
  ...CROSSBOW_INFILTRATOR_FEATS,
];
