import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// LEGACY ARCHETYPE FEATS — Book of the Dead (Part 4)
// Undead Slayer, Vampire, Zombie
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// UNDEAD SLAYER  (Book of the Dead pg. 28–29)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=112
// ──────────────────────────────────────────────────────────

export const UNDEAD_SLAYER_FEATS: FeatEntry[] = [
  {
    id: 'undead-slayer-dedication',
    name: 'Undead Slayer Dedication',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Your training has prepared you to recognize most undead on sight. You become trained in two Lore skills, each about a specific type of undead (such as Vampire Lore or Zombie Lore). If you were already trained, you become an expert. You gain the Slayer\'s Identification free action: when you roll initiative and can observe a creature you know is undead, attempt to Recall Knowledge with a +1 circumstance bonus (+2 if master in the skill).',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Religion'],
    mechanics: 'Trained in 2 undead Lore skills (expert if already trained). Slayer\'s Identification [free]: +1 circ (+2 master) to Recall Knowledge vs undead on initiative.',
  },
  {
    id: 'undead-slayer-blessed-medicine',
    name: 'Blessed Medicine',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You know the diseases and maladies of the undead intimately. When you fail a check to Treat a Disease that was inflicted by an undead creature, you can reroll the check and use the new result.',
    implemented: 'full',
    traits: ['Archetype', 'Fortune', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Undead Slayer Dedication'],
    mechanics: 'Trigger: fail Treat Disease check vs undead-inflicted disease. Reroll and use new result.',
  },
  {
    id: 'undead-slayer-hunters-sanctum',
    name: 'Hunter\'s Sanctum',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You establish a safe house (20-foot cube) where you can prepare for your hunt. Setting up or moving takes 1 week downtime. The sanctum has nondetection (Religion modifier for counteract DC, half level rounded up for counteract level). Undead attempting to locate the entrance must succeed against your Religion DC or the normal DC, whichever higher.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Undead Slayer Dedication'],
    mechanics: 'Safe house ~20-ft cube. 1-week setup. Nondetection vs magical detection + undead. Uses Religion DC.',
  },
  {
    id: 'undead-slayer-necromantic-resistance',
    name: 'Necromantic Resistance',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'As part of your training, you\'ve inured yourself against necromancy through grueling, repeated exposure. You gain a +1 circumstance bonus to saves against necromancy effects and gain resistance to negative damage equal to half your level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Undead Slayer Dedication'],
    mechanics: '+1 circ to saves vs necromancy. Resistance negative = half level.',
  },
  {
    id: 'undead-slayer-slayers-strike',
    name: 'Slayer\'s Strike',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve dedicated yourself to learning ancient prayers against undead. Make a Strike against a creature you know is undead. This counts as two attacks for MAP. On hit: +1 extra die of positive damage (same die as weapon). Further Strikes against same target before your next turn with same weapon deal extra positive = number of weapon dice. At 10th level: +2 extra dice. At 18th level: +3 extra dice.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish', 'Necromancy', 'Occult', 'Positive'],
    actionCost: 2,
    prerequisites: ['Undead Slayer Dedication'],
    mechanics: '2 actions. Strike vs known undead (counts as 2 for MAP). Hit: +1 die positive (10th: +2, 18th: +3). Further Strikes this turn: +positive = weapon dice count.',
  },
  {
    id: 'undead-slayer-frighten-undead',
    name: 'Frighten Undead',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your very presence chills undead to their core. Attempt to Demoralize an undead target using your Religion modifier instead of Intimidation if higher. If you use Religion, the Demoralize loses the emotion and mental traits, affecting even mindless undead on an instinctual level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Undead Slayer Dedication', 'Trained in Intimidation'],
    mechanics: '1 action. Demoralize undead using Religion modifier (if higher). With Religion: loses emotion/mental traits, works on mindless undead.',
  },
  {
    id: 'undead-slayer-gear-up',
    name: 'Gear Up',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You always have the right tools for undead vulnerabilities. You gain Prescient Planner and Prescient Consumable feats. When using Prescient Planner for an item to exploit an undead\'s weakness/vulnerability, you can pull it out as a 2-action activity instead of 1 minute. If you have Hunter\'s Sanctum, 1 hour in your sanctum refreshes Prescient Planner requirements.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Undead Slayer Dedication'],
    mechanics: 'Gain Prescient Planner + Prescient Consumable. For undead weaknesses: 2-action draw instead of 1 min. Sanctum: 1 hr refreshes supplies.',
  },
  {
    id: 'undead-slayer-slayers-blessing',
    name: 'Slayer\'s Blessing',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You carry scraps of materials dangerous to undead and can apply them to your weapon. When you use Slayer\'s Strike, before making the Strike, choose either the ghost touch property rune or a precious material: cold iron, darkwood, or silver. The Strike gains that benefit. At 14th level, add adamantine and mithral to the list.',
    implemented: 'full',
    traits: ['Archetype', 'Manipulate'],
    actionCost: 'passive',
    prerequisites: ['Slayer\'s Strike'],
    mechanics: 'On Slayer\'s Strike: choose ghost touch rune OR cold iron/darkwood/silver material. At 14th: +adamantine/mithral.',
  },
  {
    id: 'undead-slayer-slayers-presence',
    name: 'Slayer\'s Presence',
    source: 'Undead Slayer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your very presence strikes fear into the undead. When you use Slayer\'s Identification and succeed at your check, you can Frighten Undead as a free action, targeting the creature you identified. Any time you get a critical success to Frighten Undead, if the target\'s level is lower than yours, the target is fleeing for 1 round.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Frighten Undead'],
    mechanics: 'On successful Slayer\'s Identification: free Frighten Undead. Crit success vs lower-level: target fleeing 1 round.',
  },
];

// ──────────────────────────────────────────────────────────
// VAMPIRE  (Book of the Dead pg. 58–59)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=113
// ──────────────────────────────────────────────────────────

export const VAMPIRE_FEATS: FeatEntry[] = [
  {
    id: 'vampire-dedication',
    name: 'Vampire Dedication',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'re a newly risen vampire. You gain the undead and vampire traits and basic undead benefits. Your undead craving is for blood. You gain a fangs unarmed attack (1d6 piercing, brawling, grapple, unarmed). You gain revulsion (garlic, religious symbols of non-evil deities — fleeing, DC 25 Will to overcome) and sunlight vulnerabilities (slowed 1, increasing each turn, destroyed if all actions lost). You gain Drink Blood [one-action] (divine, necromancy): grabbed/paralyzed/restrained/unconscious/willing creature within reach, Athletics vs Fort DC. Success: target drained 1, you gain temp HP = target\'s level for 10 min.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You were killed by a vampire drinking your blood'],
    mechanics: 'Rare. Vampire/undead traits + basic undead benefits. Fangs: 1d6 P (brawling, grapple). Drink Blood [1-action]: Athletics vs Fort DC → drained 1, temp HP = target level (10 min). Revulsion + sunlight vulnerabilities.',
  },
  {
    id: 'vampire-clinging-climber',
    name: 'Clinging Climber',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You climb like a spider. You gain a climb Speed of 15 feet.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication', 'Trained in Athletics'],
    mechanics: 'Climb Speed 15 ft.',
  },
  {
    id: 'vampire-manipulative-charm',
    name: 'Manipulative Charm',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Against humanoids, you gain a +1 circumstance bonus to Deception checks to Lie, Diplomacy to Gather Information, and Diplomacy to Make an Impression. Once per day, you can cast charm as a divine innate spell (class DC or spell DC, whichever higher). Requires staring into target\'s eyes (visual trait). Heightened every 2 levels to max 9th-level at 19th.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication', 'Trained in Deception or Diplomacy'],
    mechanics: '+1 circ Deception (Lie), Diplomacy (Gather Info + Make an Impression) vs humanoids. 1/day charm (divine innate, visual, heightens every 2 levels).',
  },
  {
    id: 'vampire-nocturnal-kindred',
    name: 'Nocturnal Kindred',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You have an innate connection with creatures of the night. You can ask questions of, receive answers from, and use Diplomacy with bats, rats, and wolves. +1 circumstance bonus to Make an Impression on such animals. Once per day, cast animal allies as divine innate spell (bats/rats/wolves only). Heightened every 2 levels to max 9th at 19th.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication', 'Trained in Nature'],
    mechanics: 'Communicate with bats/rats/wolves. +1 circ Make an Impression on them. 1/day animal allies (divine innate, heightens every 2 levels).',
  },
  {
    id: 'vampire-daywalker',
    name: 'Daywalker',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Through a profane pledge or a bloodline quirk, you can tolerate the sun\'s light. You gain advanced undead benefits and can\'t be destroyed by sunlight. This doesn\'t prevent you from becoming slowed by exposure to the sun.',
    implemented: 'full',
    traits: ['Abjuration', 'Archetype', 'Divine'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication'],
    mechanics: 'Advanced undead benefits. Can\'t be destroyed by sunlight (still slowed).',
  },
  {
    id: 'vampire-predatory-claws',
    name: 'Predatory Claws',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your nails grow into sharp claws. You gain a claw unarmed attack (1d4 slashing, brawling, agile, finesse). If you hit the same enemy with two consecutive claw Strikes in the same round, you can attempt to Grapple as a free action immediately after the second Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication'],
    mechanics: 'Claw: 1d4 S (brawling, agile, finesse). Two consecutive claw hits: free Grapple.',
  },
  {
    id: 'vampire-vicious-fangs',
    name: 'Vicious Fangs',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You aim for your victim\'s prominent arteries. Your fangs Strike deals an additional 1d6 persistent bleed damage on a critical hit. At 14th level: 2d6 persistent bleed. At 20th level: 3d6 persistent bleed.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication'],
    mechanics: 'Fangs crit: +1d6 persistent bleed (14th: 2d6, 20th: 3d6).',
  },
  {
    id: 'vampire-bat-form',
    name: 'Bat Form',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You can transform into a bat. You gain the effects of a 4th-level pest form (bat form only). At 14th level, you can instead gain the effects of a 4th- or 5th-level aerial form (bat form only).',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Divine', 'Polymorph', 'Transmutation'],
    actionCost: 1,
    prerequisites: ['Vampire Dedication'],
    mechanics: '1 action. Frequency: 1/hour. 4th-level pest form (bat). At 14th: 4th/5th-level aerial form (bat).',
  },
  {
    id: 'vampire-turn-to-mist',
    name: 'Turn to Mist',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You turn into vapor, gaining the effects of gaseous form.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Divine', 'Transmutation'],
    actionCost: 1,
    prerequisites: ['Vampire Dedication'],
    mechanics: '1 action. Frequency: 1/day. Gain effects of gaseous form.',
  },
  {
    id: 'vampire-coffin-bound',
    name: 'Coffin Bound',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You bind your spirit to a coffin filled with soil of your homeland. Rest inside for 10 min: regain HP = Con mod × half level. If destroyed, remain near death instead (unconscious, 1 hour to be destroyed). Returned to coffin in time: 1 hour rest → regain 1 HP, lose dying/wounded. Can\'t heal otherwise when near death. Staking: only if unconscious (3 actions). Lose benefits if coffin destroyed or soil lost.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Divine', 'Necromancy', 'Negative'],
    actionCost: 'passive',
    prerequisites: ['Vampire Dedication'],
    mechanics: 'Uncommon. Coffin rest 10 min: heal Con×(level/2). On destruction: near death 1 hr instead. Return to coffin + 1 hr rest = 1 HP + remove dying/wounded. Staking: 3 actions vs unconscious.',
  },
  {
    id: 'vampire-mist-escape',
    name: 'Mist Escape',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'As you fall, your body reacts to defend itself. When reduced to 0 HP, you automatically Turn to Mist (doesn\'t expend daily use). You unconsciously move toward your coffin. While at 0 HP in mist form, unaffected by further damage. Return to corporeal form (unconscious) at coffin or after 1 hour (destroyed).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Turn to Mist', 'Coffin Bound'],
    mechanics: 'Reaction. Trigger: reduced to 0 HP. Free Turn to Mist. Immune to damage at 0 HP in mist. Move toward coffin. Corporeal at coffin or destroyed after 1 hr.',
  },
  {
    id: 'vampire-dominating-gaze',
    name: 'Dominating Gaze',
    source: 'Vampire (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You stare into your target\'s eyes and enthrall them. Once per day, cast 7th-level dominate as divine innate spell (class DC or spell DC, visual trait). At 18th: 8th-level. At 20th: 9th-level. Success: immune 24 hours. If you\'re destroyed, all dominate spells from this feat end.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Manipulative Charm'],
    mechanics: 'Uncommon. 1/day dominate (7th level, divine innate, visual). 18th: 8th level. 20th: 9th level. Destruction ends all dominations.',
  },
];

// ──────────────────────────────────────────────────────────
// ZOMBIE  (Book of the Dead pg. 60–61)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=114
// ──────────────────────────────────────────────────────────

export const ZOMBIE_FEATS: FeatEntry[] = [
  {
    id: 'zombie-dedication',
    name: 'Zombie Dedication',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Despite death and reanimation as a rotting corpse, you retain your mind and identity. You gain the undead and zombie traits and basic undead benefits. You\'re not mindless. All Speeds reduced by 5 feet. Your fist loses the nonlethal trait. Your body deteriorates each day after rest (slowed 1 when deteriorated; 10-min repair or daily preparations to fix). You gain a jaws unarmed attack (1d8 piercing, brawling, unarmed) usable only against grabbed/restrained creatures.',
    implemented: 'full',
    traits: ['Rare', 'Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You died and were animated as a husk zombie'],
    mechanics: 'Rare. Zombie/undead traits + basic undead benefits. –5 ft all Speeds. Fist loses nonlethal. Daily deterioration: slowed 1 (10-min or daily prep repair). Jaws: 1d8 P (brawling, vs grabbed/restrained only).',
  },
  {
    id: 'zombie-ankle-biter',
    name: 'Ankle Biter',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You fight just as well on the ground as standing. While prone: always Taking Cover vs ranged, ignore prone attack penalty, +1 circumstance to Athletics Trip. Crawl: move up to half Speed. Full Speed Crawl: DC 6 flat check or deteriorate.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Zombie Dedication'],
    mechanics: 'Prone: cover vs ranged, no prone penalty, +1 circ Trip. Crawl at half Speed (full Speed: DC 6 flat check or deteriorate).',
  },
  {
    id: 'zombie-feast',
    name: 'Feast',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You feast upon an adjacent restrained/unconscious creature or a deceased creature that died in the past hour. If alive, you deal jaws damage. Whether alive or dead, gain temp HP = half your level for 1 minute. Can instead gain temp HP = double level, but DC 6 flat check or deteriorate.',
    implemented: 'full',
    traits: ['Archetype', 'Manipulate'],
    actionCost: 2,
    prerequisites: ['Zombie Dedication'],
    mechanics: '2 actions. Adjacent restrained/unconscious/fresh corpse. Alive: deal jaws damage. Temp HP = half level (1 min). Double level option: DC 6 flat or deteriorate.',
  },
  {
    id: 'zombie-ravenous-charge',
    name: 'Ravenous Charge',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Hungry for the flesh of the living, you hurl yourself into the fray. You Stride. If you end within melee reach of a living creature, you can make an Athletics check to Grapple that creature. If you succeed, you then make a jaws Strike against that creature.',
    implemented: 'full',
    traits: ['Archetype', 'Open'],
    actionCost: 2,
    prerequisites: ['Zombie Dedication'],
    mechanics: '2 actions. Stride → Grapple (Athletics) → jaws Strike if Grapple succeeds.',
  },
  {
    id: 'zombie-brains',
    name: 'Brains!',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You consume the brains of your foe, causing synapses long rotten to fire. You gain a +1 status bonus on skill checks to Recall Knowledge for 1 hour. If the humanoid had a higher modifier than you for that skill, the bonus increases to +2.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Feast'],
    mechanics: 'Free action. Trigger: Feast upon a non-mindless humanoid\'s brain. +1 status Recall Knowledge 1 hr (+2 if target\'s modifier was higher).',
  },
  {
    id: 'zombie-numb',
    name: 'Numb',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'As your body rots, your senses deaden and undead powers grow. You gain advanced undead benefits and a +1 circumstance bonus on saves against emotion and pain effects. While deteriorated: bonus increases to +2, and success on emotion/pain saves becomes critical success.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Zombie Dedication'],
    mechanics: 'Advanced undead benefits. +1 circ saves vs emotion/pain. Deteriorated: +2 circ, success → crit success.',
  },
  {
    id: 'zombie-out-of-hand',
    name: 'Out of Hand',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When your arm is severed, it gains the minion trait and acts independently. It has familiar stats (Speed 5, can\'t go >100 ft from you), can Interact and make unarmed Strikes (your bonus/damage, shared MAP). At 0 HP or >100 ft: inert until reattached. Gain Lay Down Arms [one-action]: detach arm to adjacent square or reattach (10 min if at 0 HP).',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Zombie Dedication'],
    mechanics: 'Severed arm: minion, familiar stats, Speed 5, ≤100 ft, can Strike (your bonus). Lay Down Arms [1-action]: detach/reattach.',
  },
  {
    id: 'zombie-shamble',
    name: 'Shamble',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You may be slower than in life, but your pace is unfaltering. Stride twice (2 actions) or three times (3 actions). During this movement, ignore difficult and greater difficult terrain. Can ignore all circumstance/status penalties to Speed: DC 6 flat check after Shambling or deteriorate.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Zombie Dedication'],
    mechanics: '2 or 3 actions. Stride 2× (or 3×). Ignore difficult/greater difficult terrain. Optional: ignore Speed penalties (DC 6 flat or deteriorate).',
  },
  {
    id: 'zombie-unkillable',
    name: 'Unkillable',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You\'re relentless and nigh unkillable. When you would be reduced to 0 HP, you are reduced to 1 HP instead. You must succeed at a DC 6 flat check or your body deteriorates.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Zombie Dedication'],
    mechanics: 'Reaction. Frequency: 1/hour. Trigger: reduced to 0 HP. Stay at 1 HP instead. DC 6 flat check or deteriorate.',
  },
  {
    id: 'zombie-festering-wound',
    name: 'Festering Wound',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Wounds from your unarmed attacks fester and rot. On a critical hit with jaws or fist, target takes 1d6 persistent bleed damage (disease effect). Fort save: success negates, crit success = immune 24 hrs. While taking this bleed, target can\'t regain HP unless Fort save succeeds. Heal spell, successful Treat Wounds/Treat Disease, or reaching full HP ends the effect.',
    implemented: 'full',
    traits: ['Archetype', 'Disease', 'Divine', 'Necromancy'],
    actionCost: 'passive',
    prerequisites: ['Zombie Dedication'],
    mechanics: 'Jaws/fist crit: 1d6 persistent bleed (disease). Fort save negates. While bleeding: can\'t regain HP (Fort to overcome). Heal/Treat/full HP ends.',
  },
  {
    id: 'zombie-seize',
    name: 'Seize',
    source: 'Zombie (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You seize your foe and pull it close. After a successful fist Strike against a creature no more than one size larger, the foe is grabbed as if you succeeded at an Athletics check to Grapple.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Zombie Dedication'],
    mechanics: '1 action. Requirement: last action was successful fist Strike vs ≤1 size larger. Target is grabbed.',
  },
];

// ══════════════════════════════════════════════════════════
// Combined catalog for barrel import
// ══════════════════════════════════════════════════════════

export const STANDALONE_ARCHETYPE_FEATS_LEGACY_BD4: FeatEntry[] = [
  ...UNDEAD_SLAYER_FEATS,
  ...VAMPIRE_FEATS,
  ...ZOMBIE_FEATS,
];
