import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// STANDALONE ARCHETYPE FEATS — D (cont.) through G
// Dual-Weapon Warrior, Duelist, Eldritch Archer,
// Familiar Master, Gladiator
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// DUAL-WEAPON WARRIOR (Player Core 2 pg. 196)
// ──────────────────────────────────────────────────────────

export const DUAL_WEAPON_WARRIOR_FEATS: FeatEntry[] = [
  {
    id: 'dual-weapon-warrior-dedication',
    name: 'Dual-Weapon Warrior Dedication',
    source: 'Dual-Weapon Warrior (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'re exceptional in your use of two weapons. You gain the Double Slice fighter feat.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'Grants the Double Slice fighter feat (2 actions: make 2 Strikes, one per weapon, combine MAP). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'dual-weapon-warrior-dual-thrower',
    name: 'Dual Thrower',
    source: 'Dual-Weapon Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You know how to throw two weapons as easily as strike with them. Whenever a feat you gained from the dual-weapon warrior archetype allows you to make a melee Strike, you can instead make a ranged Strike with a thrown weapon or a one-handed ranged weapon you are wielding (weapons that need "1+" hand, such as longbows, don\'t qualify). Any effects from these feats that apply to one-handed melee weapons or melee Strikes also apply to one-handed ranged weapons and ranged Strikes.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dual-Weapon Warrior Dedication'],
    mechanics: 'DWW archetype feats that allow melee Strikes also allow ranged Strikes with thrown or 1-hand ranged weapons. Melee weapon/Strike effects apply to ranged equivalents.',
  },
  {
    id: 'dual-weapon-warrior-dual-weapon-reload',
    name: 'Dual-Weapon Reload',
    source: 'Dual-Weapon Warrior (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You carry your ammunition in a way that allows you to reload while holding two weapons. While you\'re wielding two one-handed weapons, each in a different hand, you don\'t need a free hand to reload a one-handed ranged weapon you\'re wielding.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dual-Weapon Warrior Dedication or Crossbow Infiltrator Dedication'],
    mechanics: 'While wielding 2 one-handed weapons in different hands, no free hand needed to reload a 1-hand ranged weapon wielded.',
  },
  {
    id: 'dual-weapon-warrior-flensing-slice',
    name: 'Flensing Slice',
    source: 'Dual-Weapon Warrior (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you hit with both attacks with Double Slice, you flense the target, making it bleed and creating a weak spot. The target takes 1d8 persistent bleed damage per weapon damage die of whichever of the weapons you used that has the most weapon damage dice (maximum 4d8 for a major striking weapon). In addition, until the start of your next turn the target is off-guard, and its resistances to any physical damage types are reduced by 5.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Dual-Weapon Warrior Dedication'],
    mechanics: 'Requires last action was Double Slice and both attacks hit. Target takes 1d8 persistent bleed per weapon damage die (max 4d8), is off-guard until start of your next turn, and physical resistances reduced by 5.',
  },
  {
    id: 'dual-weapon-warrior-dual-weapon-blitz',
    name: 'Dual-Weapon Blitz',
    source: 'Dual-Weapon Warrior (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You attack as you weave your way around the battlefield. Stride up to your Speed. During this movement, you can Strike once with each of the two one-handed melee weapons. Each of these Strikes can be made at any point during your movement.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Dual-Weapon Warrior Dedication'],
    mechanics: 'Requires wielding 2 one-handed melee weapons. Stride up to Speed, Strike once with each weapon at any point during the Stride.',
  },
  {
    id: 'dual-weapon-warrior-dual-onslaught',
    name: 'Dual Onslaught',
    source: 'Dual-Weapon Warrior (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'When you lash out with both weapons, you leave no room for the target to escape your attack. When you use Double Slice, if you miss with both Strikes, choose one of the two weapons and apply the effects of a hit with that weapon. You can\'t choose a weapon if your attack roll with that weapon was a critical failure, meaning you still miss entirely if both attack rolls were critical failures.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dual-Weapon Warrior Dedication'],
    mechanics: 'When Double Slice misses both Strikes, choose one weapon to apply hit effects (unless that weapon\'s roll was crit fail). Still miss if both rolls were crit fails.',
  },
];

// ──────────────────────────────────────────────────────────
// DUELIST (Player Core 2 pg. 197)
// ──────────────────────────────────────────────────────────

export const DUELIST_FEATS: FeatEntry[] = [
  {
    id: 'duelist-dedication',
    name: 'Duelist Dedication',
    source: 'Duelist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You are always ready to draw your weapon and begin a duel, no matter the circumstances. You gain the Quick Draw feat, enabling you to both draw and attack with a weapon as 1 action.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in light armor', 'Trained in simple weapons'],
    mechanics: 'Grants Quick Draw feat (1 action: Interact to draw a weapon, then Strike with it). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'duelist-duelists-challenge',
    name: "Duelist's Challenge",
    source: 'Duelist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Select one enemy you can see and proclaim a challenge against it. That enemy is your dueling opponent until it\'s defeated, it flees from the encounter, or the encounter ends. Any time you hit that enemy using a single one-handed melee weapon while your other hand or hands are free, you gain a circumstance bonus to the Strike\'s damage equal to the number of damage dice your weapon deals. If you attack a creature other than your dueling opponent, you take a circumstance penalty to damage equal to the number of damage dice your weapon deals.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Duelist Dedication'],
    mechanics: '1 action. Select one visible enemy as dueling opponent (until defeated/fled/encounter ends). Hits with 1-hand melee (free off-hand) gain circ bonus to damage = weapon damage dice. Attacking non-opponent takes circ penalty to damage = weapon damage dice.',
  },
  {
    id: 'duelist-watch-this',
    name: 'Watch This!',
    source: 'Duelist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'A common saying among Firebrands is, "There\'s always a fool who thinks they can do it better—and they\'re often right." You verbally commit to using an action on your next turn to make a melee Strike against the same enemy your ally has missed. If your attack hits, you deal additional damage equal to twice the number of damage dice.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Auditory', 'Emotion'],
    actionCost: 'reaction',
    prerequisites: ['Duelist Dedication or Pirate Dedication'],
    mechanics: 'Reaction. Trigger: ally misses or crit misses enemy you can see. Commit to melee Strike vs that enemy on your next turn. On hit, deal additional damage = 2 × weapon damage dice. Legacy Firebrands content.',
  },
  {
    id: 'duelist-selfless-parry',
    name: 'Selfless Parry',
    source: 'Duelist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You protect those near to you with a flash of steel and a stroke of good luck. When you\'re benefiting from Dueling Parry, allies adjacent to you gain a +1 circumstance bonus to AC. If you have Dueling Riposte, you can use it when an enemy within your reach critically fails a Strike against an ally adjacent to you, not just against yourself.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Dueling Parry (Fighter)', 'Duelist Dedication'],
    mechanics: 'While benefiting from Dueling Parry: adjacent allies gain +1 circ bonus to AC. If you have Dueling Riposte, can use it when enemy crit fails Strike vs adjacent ally.',
  },
  {
    id: 'duelist-student-of-the-dueling-arts',
    name: 'Student of the Dueling Arts',
    source: 'Duelist (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Dueling is your art, and your weapon is your instrument. During your daily preparations, you can swap out any number of your duelist archetype feats for other duelist archetype feats of the appropriate level for which you are qualified. You can\'t swap out Duelist Dedication or Student of the Dueling Arts in this way. In addition, you can enter a stance from a duelist archetype feat you don\'t have by increasing the number of actions it takes to enter the stance by 1 (typically to 2 actions). You must still meet the stance feat\'s prerequisites.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Duelist Dedication'],
    mechanics: 'During daily prep, swap any duelist archetype feats (except Dedication and this feat) for other qualified duelist feats. Can enter stances from duelist feats you don\'t have at +1 action cost.',
    subChoices: { label: 'Choose duelist feat to swap in', options: [
      { id: 'duelist-duelists-challenge', name: "Duelist's Challenge (4th)", description: 'Challenge a foe for +2 damage when dueling' },
      { id: 'duelist-watch-this', name: 'Watch This! (6th)', description: 'Demoralize foe after successful Strike' },
      { id: 'duelist-selfless-parry', name: 'Selfless Parry (8th)', description: 'Use Dueling Parry to protect an adjacent ally' },
    ] },
  },
];

// ──────────────────────────────────────────────────────────
// ELDRITCH ARCHER (Player Core 2 pg. 198)
// ──────────────────────────────────────────────────────────

export const ELDRITCH_ARCHER_FEATS: FeatEntry[] = [
  {
    id: 'eldritch-archer-dedication',
    name: 'Eldritch Archer Dedication',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You channel powerful magic with your archery. If you don\'t already cast spells from spell slots, you learn to cast spontaneous spells and gain the Cast a Spell activity. You gain a spell repertoire with one cantrip of your choice from a tradition of your choice. This cantrip must require a spell attack roll. You\'re trained in spell attack modifier and spell DC. Your key spellcasting attribute is Charisma. You also gain Eldritch Shot: 3 actions, Cast a Spell (1 or 2 actions, requires spell attack) imbued into bow, then Strike. Use attack roll for both Strike and spell effects. Counts as 2 attacks for MAP but don\'t apply penalty until after.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication', 'Magical'],
    actionCost: 'passive',
    prerequisites: ['Expert in at least one weapon from the bow or crossbow weapon group'],
    mechanics: 'If no spell slots: gain spontaneous cantrip (requires spell attack roll, any tradition), trained in spell attack/DC, key ability Cha. Grants Eldritch Shot (3 actions: Cast a Spell 1-2 actions + Strike; use attack roll for both; counts as 2 MAP but don\'t apply until after). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'eldritch-archer-basic-spellcasting',
    name: 'Basic Eldritch Archer Spellcasting',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You gain the basic spellcasting benefits. Each time you gain a spell slot of a new level from this archetype, add a spell of the appropriate spell rank to your repertoire, either a common spell of your chosen tradition or another spell of that tradition you have learned or discovered.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: 'Grants basic spellcasting benefits (see archetype spellcasting rules). Add a spell to repertoire each time you gain a new spell slot level.',
  },
  {
    id: 'eldritch-archer-enchanting-shot',
    name: 'Enchanting Shot',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'With a single whisper carried on the wind, you enchant your ammunition to make a foe more vulnerable to your attacks. Make a bow or crossbow Strike. On a hit, the target takes an additional 2d6 mental damage. On a critical hit, the target also becomes stunned 1. The mental damage increases to 3d6 if your weapon has a greater striking rune, or to 4d6 if your weapon has a major striking rune.',
    implemented: 'full',
    traits: ['Archetype', 'Emotion', 'Magical', 'Mental'],
    actionCost: 2,
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: '2 actions. Make bow/crossbow Strike. Hit: +2d6 mental (3d6 greater striking, 4d6 major striking). Crit hit: also stunned 1.',
  },
  {
    id: 'eldritch-archer-magic-ammunition',
    name: 'Magic Ammunition',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You imbue your ammunition with raw and potent magic, transforming it to suit your needs. When you select this feat, choose three types of common magical ammunition of 4th level or lower. You gain Transform Ammunition (free action, magical, frequency once per round): transform a non-magical arrow or bolt into magical ammunition of one chosen type. Must shoot before end of turn or magic dissipates. If ammunition has an Activate entry, you still need the required actions. You can select this feat multiple times, choosing three additional types each time.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 'passive',
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: 'Choose 3 types of common magical ammo (4th level or lower). Transform Ammunition (free action, 1/round): convert non-magical ammo to chosen type. Must fire by end of turn. Can take this feat multiple times for +3 types each.',
  },
  {
    id: 'eldritch-archer-precious-ammunition',
    name: 'Precious Ammunition',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You enchant a piece of ammunition on your person with the magical essence of a precious material. Choose cold iron or silver; if you shoot the arrow or bolt before the end of your turn, it counts as that material. At 14th level, add adamantine to the list of materials you can choose from.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 1,
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: '1 action. Choose cold iron or silver (adamantine at 14th). Shoot before end of turn → counts as that material.',
    subChoices: { label: 'Choose precious material', options: [
      { id: 'cold-iron', name: 'Cold Iron', description: 'Effective against fey and other cold iron-vulnerable creatures' },
      { id: 'silver', name: 'Silver', description: 'Effective against fiends, werewolves, and other silver-vulnerable creatures' },
      { id: 'adamantine', name: 'Adamantine', description: 'Available at 14th level; bypasses hardness' },
    ] },
  },
  {
    id: 'eldritch-archer-eldritch-reload',
    name: 'Eldritch Reload',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You integrate your talent for magic into your use of reloading weapons. You Interact to reload a weapon you are wielding.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'free',
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: 'Free action. Requires last action was Eldritch Shot, Cast a Spell from slot, or activate magical ammunition. Interact to reload wielded weapon.',
  },
  {
    id: 'eldritch-archer-expert-spellcasting',
    name: 'Expert Eldritch Archer Spellcasting',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You learn additional eldritch archer magic. You gain the expert spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Basic Eldritch Archer Spellcasting'],
    mechanics: 'Grants expert spellcasting benefits (see archetype spellcasting rules).',
  },
  {
    id: 'eldritch-archer-homing-shot',
    name: 'Homing Shot',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your shots zip around corners and fly at impossible angles to reach your target. Make a bow or crossbow Strike against a foe you can see; the ammunition travels to your target, even going around corners. You ignore the target\'s concealed condition and all cover.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 1,
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: '1 action. Bow/crossbow Strike ignoring target\'s concealed condition and all cover.',
  },
  {
    id: 'eldritch-archer-incorporeal-shot',
    name: 'Incorporeal Shot',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You concentrate an immense amount of magic to create a piece of ammunition that phases through everything but your target. Make a bow or crossbow Strike against an observed or hidden foe. The ammunition travels in a straight line, passing through non-magical barriers/walls. It ignores all cover, concealed, hidden, and circumstance bonuses to AC from shields. It has a +4 status bonus to hit creatures wearing armor. Damage can\'t be reduced with Shield Block using a non-magical shield.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 1,
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: '1 action, 1/day. Strike vs observed or hidden foe. Ammo phases through non-magical barriers. Ignores cover, concealed, hidden, circ bonuses from shields. +4 status to hit armored targets. Non-magical Shield Block can\'t reduce damage.',
  },
  {
    id: 'eldritch-archer-fatal-shot',
    name: 'Fatal Shot',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You modify an arrow or bolt to bring death to your target in a single potent hit. Make a bow or crossbow Strike. On a hit, you deal an additional 10d10 precision damage. On a critical hit, the target must also succeed at a Fortitude saving throw against the higher of your class DC or spell DC or be immediately slain; this save has the death and incapacitation traits.',
    implemented: 'full',
    traits: ['Archetype', 'Magical'],
    actionCost: 3,
    prerequisites: ['Eldritch Archer Dedication'],
    mechanics: '3 actions, 1/day. Bow/crossbow Strike: +10d10 precision damage on hit. On crit: target Fort save vs higher of class DC or spell DC or slain (death, incapacitation traits).',
  },
  {
    id: 'eldritch-archer-master-spellcasting',
    name: 'Master Eldritch Archer Spellcasting',
    source: 'Eldritch Archer (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'You gain the master spellcasting benefits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Expert Eldritch Archer Spellcasting'],
    mechanics: 'Grants master spellcasting benefits (see archetype spellcasting rules).',
  },
];

// ──────────────────────────────────────────────────────────
// FAMILIAR MASTER (Player Core 2 pg. 200)
// ──────────────────────────────────────────────────────────

export const FAMILIAR_MASTER_FEATS: FeatEntry[] = [
  {
    id: 'familiar-master-dedication',
    name: 'Familiar Master Dedication',
    source: 'Familiar Master (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have forged a mystical bond with a creature. You gain a familiar. If you already have a familiar, you gain the Enhanced Familiar feat.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'Gain a familiar. If you already have one, gain Enhanced Familiar feat instead. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'familiar-master-familiar-conduit',
    name: 'Familiar Conduit',
    source: 'Familiar Master (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Under your tutelage, your familiar has grown attuned to the hidden currents of the world and can serve as a conduit for your magic. If the next action you use is to Cast a Spell that has a range, the spell uses the familiar as its origin point.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Familiar Master Dedication', 'Able to cast spells'],
    mechanics: '1 action (Spellshape). Requires line of effect to familiar. Next Cast a Spell with a range uses familiar as origin point.',
  },
  {
    id: 'familiar-master-familiar-mascot',
    name: 'Familiar Mascot',
    source: 'Familiar Master (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When selecting master abilities, you can choose an ally to benefit from any specific master ability. Each master ability can benefit only a single character, and you can select a specific master ability only once unless the ability says otherwise.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Familiar Master Dedication'],
    mechanics: 'Master abilities can be assigned to allies instead of yourself. Each ability benefits one character only.',
  },
  {
    id: 'familiar-master-improved-familiar',
    name: 'Improved Familiar',
    source: 'Familiar Master (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You find it easy to attract a powerful and unusual familiar to your side. The number of abilities required to make your familiar a specific familiar is two lower than normal.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Familiar Master Dedication'],
    mechanics: 'Specific familiar ability cost reduced by 2.',
  },
  {
    id: 'familiar-master-mutable-familiar',
    name: 'Mutable Familiar',
    source: 'Familiar Master (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your familiar\'s supernatural spirit has outgrown its corporeal body. You can conduct a special 10-minute exploration activity to reselect certain familiar abilities, switching one or more of the following abilities for other abilities on this list: amphibious, burrower, climber, darkvision, fast movement, manual dexterity, resistance, and scent. You can\'t remove an ability that is required for another ability your familiar has.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Familiar Master Dedication'],
    mechanics: '10-minute activity to swap familiar abilities (amphibious, burrower, climber, darkvision, fast movement, manual dexterity, resistance, scent). Can\'t remove abilities required by other abilities.',
  },
  {
    id: 'familiar-master-incredible-familiar',
    name: 'Incredible Familiar',
    source: 'Familiar Master (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'Your familiar is infused with even more magic than other familiars. You can select six familiar or master abilities each day, instead of four.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Enhanced Familiar'],
    mechanics: 'Select 6 familiar/master abilities per day instead of 4.',
  },
];

// ──────────────────────────────────────────────────────────
// GLADIATOR (Player Core 2 pg. 201)
// ──────────────────────────────────────────────────────────

export const GLADIATOR_FEATS: FeatEntry[] = [
  {
    id: 'gladiator-dedication',
    name: 'Gladiator Dedication',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You know how to turn combat into a form of entertainment. You gain the Additional Lore general feat for Gladiatorial Lore. At the start of a combat encounter, if you have spectators, you gain a number of temporary HP equal to your character level for 1 minute and you can roll Performance for your initiative.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Impressive Performance'],
    mechanics: 'Grants Gladiatorial Lore (Additional Lore). With spectators at combat start: gain temp HP = character level (1 min) and can use Performance for initiative. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'gladiator-fancy-moves',
    name: 'Fancy Moves',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You show off your fighting style to discourage your foes. You can use Performance to Demoralize.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Gladiator Dedication', 'Expert in Performance'],
    mechanics: 'Use Performance instead of Intimidation for Demoralize action.',
  },
  {
    id: 'gladiator-play-to-the-crowd',
    name: 'Play to the Crowd',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You show off for the crowd. Attempt a Performance check; the DC is determined by the GM but is typically the standard DC for your level or the DC to Make an Impression on the spectators, whichever is higher. On a success, choose one benefit; on a critical success, choose two: temp HP = character level (1 min); +1 circ bonus to AC until end of next turn; +1 circ bonus to next attack roll before end of next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Gladiator Dedication'],
    mechanics: 'Reaction. Trigger: reduce enemy to 0 HP with spectators. Performance check vs GM DC. Success: choose 1 benefit (crit success: choose 2): (1) temp HP = level for 1 min, (2) +1 circ AC until end of next turn, (3) +1 circ to next attack before end of next turn.',
  },
  {
    id: 'gladiator-stage-fighting',
    name: 'Stage Fighting',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You pull punches to give a better show. You don\'t take the usual -2 circumstance penalty when making a nonlethal attack with a weapon or unarmed attack that doesn\'t have the nonlethal trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Gladiator Dedication'],
    mechanics: 'No -2 circ penalty for nonlethal attacks with weapons/unarmed that lack the nonlethal trait.',
  },
  {
    id: 'gladiator-performative-weapons-training',
    name: 'Performative Weapons Training',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'re skilled with flashy weapons. You have familiarity with the bo staff, dueling cape, spiked chain, sword cane, trident, war flail, and whip. For proficiency, treat these as simple weapons. Whenever you get a critical hit with one of these weapons, you get its critical specialization effect.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Gladiator Dedication'],
    mechanics: 'Bo staff, dueling cape, spiked chain, sword cane, trident, war flail, whip treated as simple weapons for proficiency. Critical hits with these grant critical specialization effect.',
  },
  {
    id: 'gladiator-call-your-shot',
    name: 'Call Your Shot',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'When you successfully Play to the Crowd, add the following to the list of benefits you can choose from: a creature you can see within 30 feet becomes frightened 2. This effect has the emotion, fear, mental, and visual traits.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Play to the Crowd'],
    mechanics: 'Adds new Play to the Crowd benefit option: visible creature within 30 ft becomes frightened 2 (emotion, fear, mental, visual).',
  },
  {
    id: 'gladiator-living-for-the-applause',
    name: 'Living for the Applause',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Nothing can stop you as long as you have an audience cheering you on. The attention reinvigorates you and keeps you from being knocked out. You remain at 1 Hit Point, and your wounded condition increases by 1. In addition, attempt a Performance check; the DC is determined by the GM. On a success, the crowd erupts in applause, giving you a +1 circumstance bonus to AC until the end of your next turn. On a critical success, you don\'t expend your daily use.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Gladiator Dedication'],
    mechanics: 'Reaction, 1/day. Trigger: reduced to 0 HP (not killed) during combat with spectators. Remain at 1 HP, wounded +1. Performance check: success → +1 circ AC until end next turn; crit success → don\'t expend daily use. Legacy Firebrands content.',
  },
  {
    id: 'gladiator-big-debut',
    name: 'Big Debut',
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You strike a dramatic pose, deliver a snappy quip, or reveal a shocking new costume, captivating everyone who can see you. You don\'t roll initiative. Instead, you voluntarily go last. Enemies who can see you must attempt a Will saving throw against your class DC or spell DC, whichever is higher. On a failure, the enemy becomes stunned 1 (stunned 2 on a critical failure). As your first action, you can Interact to draw or stow a light Bulk item as a free action; if this is a small garment or accessory, you gain a +1 circumstance bonus on Charisma-based skill checks until the end of your turn.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Mental'],
    actionCost: 'free',
    prerequisites: ['Celebrity Dedication or Gladiator Dedication'],
    mechanics: 'Free action, 1/day. Trigger: about to roll initiative. Go last voluntarily. Enemies Will save vs higher of class/spell DC: fail → stunned 1 (crit fail → stunned 2). First action: free Interact for light accessory → +1 circ Cha skills until end of turn. Legacy Firebrands content.',
  },
  {
    id: 'gladiator-gladiators-roar',
    name: "Gladiator's Roar",
    source: 'Gladiator (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your roar can be heard twice as far as normal, and creatures within a 15-foot-cone take 6d10 sonic damage and must attempt a Fortitude save against your class DC or spell DC, whichever is higher. If your Gladiator\'s Roar triggers Play to the Crowd, you gain a +2 status bonus to your Performance check. Critical Success: unaffected. Success: half damage, frightened 1. Failure: full damage, frightened 2. Critical Failure: double damage, frightened 3, stunned 1.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Emotion', 'Fear', 'Mental', 'Sonic'],
    actionCost: 2,
    prerequisites: ['Gladiator Dedication'],
    mechanics: '2 actions, 1/day. 15-ft cone, 6d10 sonic, Fort save vs higher class/spell DC. Crit success: unaffected. Success: half damage + frightened 1. Failure: full damage + frightened 2. Crit failure: double damage + frightened 3 + stunned 1. If triggers Play to the Crowd: +2 status to Performance. Curtain Call content.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_DG: FeatEntry[] = [
  ...DUAL_WEAPON_WARRIOR_FEATS,
  ...DUELIST_FEATS,
  ...ELDRITCH_ARCHER_FEATS,
  ...FAMILIAR_MASTER_FEATS,
  ...GLADIATOR_FEATS,
];
