import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// STANDALONE ARCHETYPE FEATS — H through M
// Herbalist, Horizon Walker, Linguist, Loremaster,
// Marshal, Martial Artist, Mauler, Medic
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// HERBALIST (Player Core 2 pg. 202)
// ──────────────────────────────────────────────────────────

export const HERBALIST_FEATS: FeatEntry[] = [
  {
    id: 'herbalist-dedication',
    name: 'Herbalist Dedication',
    source: 'Herbalist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You can create natural remedies. You gain the advanced alchemy benefits, and you learn four common 1st-level alchemical formulas with the healing trait. You don\'t need a formula book for them. You become an expert in Nature and can use Nature instead of Crafting to Craft alchemical consumables with the healing trait. You don\'t need to be trained in Crafting to do so, and you can use healer\'s tools instead of alchemist\'s tools.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Natural Medicine', 'Trained in Nature'],
    mechanics: 'Grants advanced alchemy benefits. Learn 4 common 1st-level healing alchemical formulas (no formula book needed). Expert in Nature. Use Nature instead of Crafting for healing alchemical consumables; healer\'s tools replace alchemist\'s tools. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'herbalist-fresh-ingredients',
    name: 'Fresh Ingredients',
    source: 'Herbalist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'It is amazing the difference fresh herbs can make. When using Natural Medicine to Treat Wounds, you gain the +2 circumstance bonus from having fresh ingredients, even if not in the wilderness. If you do this in the wilderness, you gain a +4 circumstance bonus instead.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Herbalist Dedication'],
    mechanics: 'Natural Medicine Treat Wounds: always gain +2 circ bonus (fresh ingredients). In wilderness: +4 circ bonus instead.',
  },
  {
    id: 'herbalist-gravelands-herbalist',
    name: 'Gravelands Herbalist',
    source: 'Herbalist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your time with the Knights of Lastwall has taught you the secrets of creating and improving upon Lastwall soup. Add Lastwall soup to your list of herbal items. At 10th level, you can make an improved version that grants a +3 item bonus. At 18th level, you can make a greater version that grants a +4 item bonus and 10 temporary Hit Points for up to 10 minutes.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Herbalist Dedication', 'Trained in Religion'],
    mechanics: 'Add Lastwall soup to herbal items. 10th level: improved version (+3 item bonus). 18th level: greater version (+4 item bonus, 10 temp HP for 10 min). Legacy Knights of Lastwall content.',
  },
  {
    id: 'herbalist-poultice-preparation',
    name: 'Poultice Preparation',
    source: 'Herbalist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'When you create an elixir as an herbal item, you can prepare it as a poultice instead. A poultice gains the oil trait (but remains alchemical, not magical) and loses the elixir trait. You can apply a poultice by Interacting with one hand. When you apply a poultice, in addition to the item\'s normal effects, the recipient can attempt an immediate flat check to recover from a single source of persistent acid, bleed, or fire damage, with the DC reduction from appropriate assistance.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Herbalist Dedication'],
    mechanics: 'Elixir herbal items can be prepared as poultices (gains oil trait, loses elixir trait). Apply with 1-hand Interact. On application: recipient gets flat check vs persistent acid/bleed/fire with assistance DC reduction.',
  },
  {
    id: 'herbalist-advanced-herbalism',
    name: 'Advanced Herbalism',
    source: 'Herbalist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your herbalist talents continue to grow with use and you have become potent at making even more remedies from less. You can create up to 6 herbal items per day with advanced alchemy. At 10th level or higher, you can select this feat a second time to increase the number to 8.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Herbalist Dedication', 'Expert in Nature'],
    mechanics: 'Create up to 6 herbal items/day with advanced alchemy. Special: at 10th+ can take again to increase to 8.',
  },
  {
    id: 'herbalist-endemic-herbs',
    name: 'Endemic Herbs',
    source: 'Herbalist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'The herbal items you create use medicinal plants endemic to your location. When a creature consumes one of your herbal items, that creature gains a benefit matching the location where you created that item (lasts 1 minute unless stated). Aquatic: +1 circ Fort saves. Arctic: 1 hour, cold effects one step less severe. Desert: 1 hour, heat effects one step less severe. Forest: +2 circ vs disease and poison. Mountain: +1 circ Reflex saves. Plains: +1 circ Will saves. Swamp: remove one source persistent bleed. Underground: +1 circ Perception.',
    implemented: 'full',
    traits: ['Additive', 'Archetype'],
    actionCost: 'passive',
    prerequisites: ['Herbalist Dedication', 'Trained in Survival'],
    mechanics: 'Herbal items grant terrain-based bonus (1 min): Aquatic +1 Fort, Arctic cold↓, Desert heat↓, Forest +2 disease/poison, Mountain +1 Reflex, Plains +1 Will, Swamp remove bleed, Underground +1 Perception. PFS note: no Additive trait for PFS.',
  },
];

// ──────────────────────────────────────────────────────────
// HORIZON WALKER (Advanced Player\'s Guide pg. 177) — Legacy
// ──────────────────────────────────────────────────────────

export const HORIZON_WALKER_FEATS: FeatEntry[] = [
  {
    id: 'horizon-walker-dedication',
    name: 'Horizon Walker Dedication',
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve mastered travel within a specific type of terrain. You gain the Favored Terrain feat. When in your favored terrain, you gain a +10-foot circumstance bonus to your travel Speed. When other creatures Follow the Expert with you as a guide in your favored terrain, they gain both the ability to ignore non-magical difficult terrain for the purpose of their travel Speed and the bonus to travel Speed.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Survival'],
    mechanics: 'Grants Favored Terrain feat. In favored terrain: +10-ft circ bonus travel Speed. Follow the Expert allies in favored terrain: ignore non-magical difficult terrain + gain travel Speed bonus. Legacy content. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'horizon-walker-acclimatization',
    name: 'Acclimatization',
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Your time spent in the hostile parts of the world has inured you to extreme climates. In your favored terrain, you gain resistance equal to half your level to all environmental damage and are affected by temperature effects as though they were one step less severe. When other creatures Follow the Expert with you as a guide in your favored terrain, they too treat temperature effects as one step less severe.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Horizon Walker Dedication'],
    mechanics: 'In favored terrain: resistance = half level to environmental damage; temperature effects one step less severe. Follow the Expert allies also get temperature reduction. Legacy content.',
  },
  {
    id: 'horizon-walker-rebels-map',
    name: "Rebel's Map",
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Rebellions require an intricate knowledge of one\'s surroundings — because you might need to escape at any moment. You remember the locations of escape routes, ambush spots, and cover from a scouting expedition or a previous visit to the area. Roll a d20. At any point during the subsequent combat, you can substitute the result of this roll instead of rolling a d20 on one Deception check to Create a Diversion or on one Stealth check to Hide.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype'],
    actionCost: 'free',
    prerequisites: ['Horizon Walker Dedication or Scout Dedication'],
    mechanics: 'Free action. Trigger: roll initiative. Roll d20 and save result. During combat: substitute that roll for one Deception (Create a Diversion) or Stealth (Hide) check. Legacy Firebrands content.',
  },
  {
    id: 'horizon-walker-sure-foot',
    name: 'Sure Foot',
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You know the secrets of moving in your favored terrain. You gain a +2 circumstance bonus to skill checks to move within your favored terrain, such as Acrobatics checks to Balance on ice, Athletics checks to Swim in rough water, Acrobatics checks to Fly in windy conditions, and so forth.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Horizon Walker Dedication', 'Expert in Acrobatics and Athletics'],
    mechanics: '+2 circ bonus to skill checks for movement in favored terrain (Balance, Swim, Fly, etc.). Legacy content.',
  },
  {
    id: 'horizon-walker-perpetual-scout',
    name: 'Perpetual Scout',
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You spot anything out of place in the areas you know best. While in your favored terrain, you always gain the benefits of the Scout exploration activity, even if you are performing another exploration activity. If you\'re legendary in Survival, you gain these benefits in any terrain.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Horizon Walker Dedication'],
    mechanics: 'In favored terrain: always gain Scout exploration benefits even while doing other exploration activities. Legendary Survival: benefits in any terrain. Legacy content.',
  },
  {
    id: 'horizon-walker-magical-adaptation',
    name: 'Magical Adaptation',
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'When an obstacle bars your path, you pull a trick from your sleeve to overcome it. You can cast darkvision, spider climb, and 4th-level water breathing as innate primal spells, each once per day.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Horizon Walker Dedication'],
    mechanics: 'Innate primal spells 1/day each: darkvision, spider climb, water breathing (4th level). Legacy content.',
  },
  {
    id: 'horizon-walker-wild-strider',
    name: 'Wild Strider',
    source: 'Horizon Walker (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Natural obstacles pose no obstacle to you. You gain the ranger\'s wild stride class feature. This allows you to ignore the effects of all non-magical difficult terrain, treat greater difficult terrain as merely difficult terrain, and gives you an additional benefit from Favored Terrain based on the terrain.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Horizon Walker Dedication'],
    mechanics: 'Gain ranger wild stride: ignore non-magical difficult terrain, greater difficult → difficult, plus Favored Terrain bonus based on terrain type. Legacy content.',
  },
];

// ──────────────────────────────────────────────────────────
// LINGUIST (Player Core 2 pg. 203)
// ──────────────────────────────────────────────────────────

export const LINGUIST_FEATS: FeatEntry[] = [
  {
    id: 'linguist-dedication',
    name: 'Linguist Dedication',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have studied languages and their development. You become trained in Society; if you were already trained in Society, you instead become an expert in Society. You gain the Multilingual skill feat twice.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You speak at least 3 languages'],
    mechanics: 'Trained in Society (expert if already trained). Gain Multilingual feat twice. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'linguist-multilingual-cipher',
    name: 'Multilingual Cipher',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You use multiple languages to create and break codes. You gain a +1 circumstance bonus to Decipher Writing. If another creature attempts to Decipher Writing you encoded, they take a –2 circumstance penalty unless they speak all the languages you used when you created the writing.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Linguist Dedication', 'Expert in Society'],
    mechanics: '+1 circ bonus to Decipher Writing. Others take -2 circ penalty to Decipher your encoded writing unless they speak all languages used.',
  },
  {
    id: 'linguist-phonetic-training',
    name: 'Phonetic Training',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You can pronounce and repeat words with near-perfect accuracy even if you don\'t understand their meaning, and you can write them down in a phonetic script that allows you or another creature with Phonetic Training to read it later. Even if the words are in a language with sounds you can\'t pronounce, you can faithfully transcribe them. Memorizing long sequences of words remains just as difficult as it is normally.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Linguist Dedication', 'Expert in Society'],
    mechanics: 'Pronounce and repeat words with near-perfect accuracy regardless of understanding. Write phonetic transcriptions readable by anyone with Phonetic Training. Can transcribe unpronounceable sounds.',
  },
  {
    id: 'linguist-spot-translate',
    name: 'Spot Translate',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You bridge a language gap, repeating the message in a different language you know. Choose a language you understand to repeat the message in. The linguistic effect counts as both languages, rather than only the language the triggering creature is using, potentially allowing it to affect a wider range of creatures.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Linguistic'],
    actionCost: 'reaction',
    prerequisites: ['Linguist Dedication'],
    mechanics: 'Reaction. Trigger: creature within 60 ft uses linguistic effect in a language you understand. Repeat in another language you know. Effect counts as both languages, allowing wider targeting (e.g. Demoralize, command spells).',
  },
  {
    id: 'linguist-analyze-idiolect',
    name: 'Analyze Idiolect',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You break down a specific individual\'s idiolect, memorizing their speech mannerisms and habits. If you interact with someone for at least 10 minutes, when you later attempt to Impersonate that individual, you gain a +4 circumstance bonus to your Deception checks and DCs. Due to the intense character study required, if you Analyze Idiolect again, it replaces any previous idiolect you memorized.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Linguist Dedication', 'Expert in Deception and Society'],
    mechanics: 'Interact 10 min with person: +4 circ bonus to Deception for Impersonate that individual and Deception DCs. Replaces previous idiolect on reuse.',
  },
  {
    id: 'linguist-read-shibboleths',
    name: 'Read Shibboleths',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 7,
    description: 'All communication is filled with slight tells and signals. If you interact with someone for at least 10 minutes, their regional words, pronunciation changes, and nonverbal cues provide you with a minor fact about their social environment, such as their hometown or certain groups they might belong to. Deceptive targets attempt a secret Deception, Society, or Lore check vs your Society DC. Once you learn true minor facts, you gain +1 circumstance bonus to Diplomacy and Deception with them.',
    implemented: 'full',
    traits: ['Archetype', 'Linguistic', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Linguist Dedication or Venture-Gossip Dedication', 'Master in Society'],
    mechanics: 'Interact 10 min: learn minor social fact about person. Deceptive targets: secret Deception/Society/Lore vs your Society DC. After learning true facts: +1 circ Diplomacy and Deception with that person.',
  },
  {
    id: 'linguist-crude-communication',
    name: 'Crude Communication',
    source: 'Linguist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Even if you don\'t speak a creature\'s language, you can rely on inflection, root words, and body language to infer rudimentary meaning. If you interact with a creature for at least 10 minutes and that creature can speak a language, the GM rolls a secret Society check for you. On a success, you understand the gist and can communicate basic concepts back. On a failure, you are mistaken or communicate incorrect concepts. If you\'re legendary in Society, you can communicate instantly without a check.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Linguist Dedication or Venture-Gossip Dedication'],
    mechanics: 'Interact 10 min with language-speaking creature: secret Society check (DC by rarity) → success: understand gist + communicate basics. Legendary Society: instant communication, no check needed.',
  },
];

// ──────────────────────────────────────────────────────────
// LOREMASTER (Advanced Player\'s Guide pg. 179) — Legacy
// ──────────────────────────────────────────────────────────

export const LOREMASTER_FEATS: FeatEntry[] = [
  {
    id: 'loremaster-dedication',
    name: 'Loremaster Dedication',
    source: 'Loremaster (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve compiled a vast repository of information that touches on nearly every subject. You are trained in Loremaster Lore, a special Lore skill that can be used only to Recall Knowledge, but on any topic. If you have legendary proficiency in a skill used to Decipher Writing, you gain expert proficiency in Loremaster Lore. You can take feats in the loremaster\'s additional feats even without the enigma muse prerequisite. If you have Bardic Lore, you gain +1 circumstance bonus to checks with it.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in at least one skill to Decipher Writing'],
    mechanics: 'Trained in Loremaster Lore (Recall Knowledge on any topic). Legendary Decipher Writing skill → expert Loremaster Lore. Can take loremaster additional feats without enigma muse prereq. Bardic Lore: +1 circ bonus. Legacy content. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'loremaster-magical-edification',
    name: 'Magical Edification',
    source: 'Loremaster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned those tidbits of magic that are most conducive to furthering your acquisition and transmission of knowledge. You gain guidance, message, and sigil as innate occult cantrips.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Loremaster Dedication'],
    mechanics: 'Innate occult cantrips: guidance, message, sigil. Legacy content.',
  },
  {
    id: 'loremaster-orthographic-mastery',
    name: 'Orthographic Mastery',
    source: 'Loremaster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You understand the principles that underlie all written words, allowing you to read nearly any text. You can attempt to Decipher Writing using Loremaster Lore in place of the required skill.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Loremaster Dedication'],
    mechanics: 'Use Loremaster Lore instead of the required skill for Decipher Writing. Legacy content.',
  },
  {
    id: 'loremaster-quick-study',
    name: 'Quick Study',
    source: 'Loremaster (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'During your daily preparations, you can study a particular subject to gain the trained proficiency rank in one Lore skill of your choice. You must have interacted with that subject in some way on the previous day, whether by reading about it, talking to someone knowledgeable, or experiencing it yourself. Alternatively, you can reference your notes to choose a Lore skill you\'ve prepared before with Quick Study. This proficiency lasts until you prepare again and can\'t be used as a prerequisite.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Loremaster Dedication'],
    mechanics: 'Daily prep: gain trained proficiency in one Lore skill (must have interacted with subject previous day, or choose from notes). Temp proficiency — can\'t use as prereq. Legacy content.',
    subChoices: { label: 'Enter Lore skill (e.g. Vampire Lore, Sailing Lore)', options: [], freeText: true },
  },
  {
    id: 'loremaster-greater-magical-edification',
    name: 'Greater Magical Edification',
    source: 'Loremaster (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You\'ve continued to expand your compendium of tools to compile knowledge. You can cast comprehend language, mindlink, and secret page as innate occult spells, each once per day. When you cast secret page, it is automatically heightened to the same spell level as your cantrips from Magical Edification.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Magical Edification'],
    mechanics: 'Innate occult spells 1/day each: comprehend language, mindlink, secret page (auto-heightened to cantrip level). Legacy content.',
  },
];

// ──────────────────────────────────────────────────────────
// MARSHAL (Player Core 2 pg. 204)
// ──────────────────────────────────────────────────────────

export const MARSHAL_FEATS: FeatEntry[] = [
  {
    id: 'marshal-dedication',
    name: 'Marshal Dedication',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You\'ve combined your social skills and combat training to become a talented combat leader. Choose Diplomacy or Intimidation. You become trained in that skill or become an expert if you were already trained in it. In addition, while you\'re conscious, you\'re surrounded by a marshal\'s aura in a 15-foot emanation. Your aura has the emotion, mental, and visual traits and grants you and allies in the aura a +1 status bonus to saving throws against fear.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Diplomacy or Intimidation', 'Trained in martial weapons'],
    mechanics: 'Choose Diplomacy or Intimidation → trained (expert if already trained). 15-ft aura (emotion, mental, visual): you + allies get +1 status vs fear. Dedication-lock enforced by validateDedicationTaking().',
    subChoices: { label: 'Choose skill', options: [
      { id: 'diplomacy', name: 'Diplomacy' },
      { id: 'intimidation', name: 'Intimidation' },
    ] },
  },
  {
    id: 'marshal-devrins-cunning-stance',
    name: "Devrin's Cunning Stance",
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned Devrin Arlos\'s guileful ways. Attempt a Deception check vs standard DC of your level. Critical Success: aura→20-ft emanation, +1 status skill checks, crit Strike vs off-guard enemy denies reactions. Success: as critical but aura doesn\'t increase. Failure: fail to enter stance. Critical Failure: fail, can\'t retry 1 min.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Open', 'Stance'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication', 'Trained in Deception'],
    mechanics: '1 action, stance. Deception check vs standard DC. Success: aura grants +1 status to skill checks; allies\' Strikes vs off-guard enemies deny reactions. Crit success: also aura→20-ft. Failure: no stance. Crit fail: 1 min cooldown. Legacy Firebrands content.',
  },
  {
    id: 'marshal-dread-marshal-stance',
    name: 'Dread Marshal Stance',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Putting on a grim face for the battle ahead, you encourage your allies to strike fear into their foes with vicious attacks. Attempt an Intimidation check vs easy DC of your level. Success: aura grants +1 status bonus to damage rolls; crit hit with Strike in aura frightens enemy 1. If wielding weapon with multiple damage dice, status bonus = weapon dice count instead. Failure: fail to enter. Crit Failure: fail, 1 min cooldown.',
    implemented: 'full',
    traits: ['Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication', 'Trained in Intimidation'],
    mechanics: '1 action stance. Intimidation vs easy DC. Success: aura grants +1 status damage (or = weapon damage dice if >1). Crit Strikes in aura = frightened 1. Failure: no stance. Crit fail: 1 min cooldown.',
  },
  {
    id: 'marshal-inspiring-marshal-stance',
    name: 'Inspiring Marshal Stance',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You become a brilliant example of dedication and poise in battle, encouraging your allies to follow suit. Attempt a Diplomacy check vs easy DC of your level. Success: aura grants +1 status bonus to attack rolls and saves against mental effects. Failure: fail to enter. Crit Failure: fail, 1 min cooldown.',
    implemented: 'full',
    traits: ['Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication', 'Trained in Diplomacy'],
    mechanics: '1 action stance. Diplomacy vs easy DC. Success: aura grants +1 status to attack rolls and saves vs mental effects. Failure: no stance. Crit fail: 1 min cooldown.',
  },
  {
    id: 'marshal-push-back-the-dead',
    name: 'Push Back the Dead!',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You call to your ally and strengthen their resolve against the horrific tricks undead bring to bear. The ally gains a +2 circumstance bonus to saves against effects originating from undead. It also gains resistance to damage from Strikes made by undead creatures equal to half your Charisma modifier.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Auditory', 'Emotion', 'Stance'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication'],
    mechanics: '1 action. Target ally: +2 circ bonus saves vs undead effects, resistance to undead Strike damage = half your Cha modifier. Legacy Knights of Lastwall content.',
  },
  {
    id: 'marshal-snap-out-of-it',
    name: 'Snap Out of It!',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You give a quick shout, hoping to shake the fog clouding your ally\'s thoughts. Choose one target ally in your marshal\'s aura who is affected by a mental effect that allowed a Will save and has a duration of no longer than 1 minute. That ally can immediately attempt a Will save with a +1 circumstance bonus against the effect\'s DC, ending the effect on a success. This can\'t end the effect for any creatures other than your target ally. Regardless of the result, your ally is temporarily immune to Snap Out of It! for 10 minutes.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Emotion', 'Mental'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication'],
    mechanics: '1 action. Ally in aura affected by mental effect (Will save, ≤1 min duration): immediate Will save +1 circ bonus vs effect DC. Success: ends effect for that ally only. Temp immune to Snap Out of It! 10 min.',
  },
  {
    id: 'marshal-steel-yourself',
    name: 'Steel Yourself!',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You encourage an ally to toughen up, giving them a fighting chance. Choose one ally in your marshal\'s aura. The ally gains temporary Hit Points equal to your Charisma modifier and a +2 circumstance bonus to Fortitude saves. Both benefits last until the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Emotion', 'Mental'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication'],
    mechanics: '1 action. Ally in aura: temp HP = Cha modifier + +2 circ Fort saves. Lasts until start of your next turn.',
  },
  {
    id: 'marshal-strategist-stance',
    name: 'Strategist Stance',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You find the most strategic options for you and your allies. Attempt a Society or Warfare Lore check. Critical Success: aura→20-ft, +1 status Reflex saves; Recall Knowledge success makes target off-guard to next attack from you/ally in aura. Success: same but aura doesn\'t increase. Failure: fail to enter. Critical Failure: fail, 1 min cooldown.',
    implemented: 'full',
    traits: ['Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication', 'Trained in Lore or Society or Warfare Lore'],
    mechanics: '1 action stance. Society/Warfare Lore vs standard DC. Success: +1 status Reflex in aura; successful Recall Knowledge makes target off-guard to next attack in aura. Crit success: also aura→20-ft. Tian Xia Character Guide content.',
  },
  {
    id: 'marshal-cadence-call',
    name: 'Cadence Call',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You call out a quick cadence, guiding your allies into a more efficient rhythm. Each willing ally in your marshal\'s aura is quickened until the end of their next turn, and they can use the extra action only to Stride. If an ally uses this extra action, at the end of its turn that ally becomes slowed 1 until the end of its following turn.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication'],
    mechanics: '1 action, 1/minute. Allies in aura: quickened until end of next turn (extra action = Stride only). If used: slowed 1 after.',
  },
  {
    id: 'marshal-rallying-charge',
    name: 'Rallying Charge',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your fearless charge into battle reinvigorates your allies to carry on the fight. You Stride up to your Speed and make a melee Strike. If your Strike hits and damages an enemy, each ally within 60 feet who saw you hit gains temporary Hit Points equal to your Charisma modifier. These temporary Hit Points last until the start of your next turn.',
    implemented: 'full',
    traits: ['Archetype', 'Visual'],
    actionCost: 2,
    prerequisites: ['Marshal Dedication'],
    mechanics: '2 actions. Stride + melee Strike. On hit that deals damage: allies within 60 ft who saw gain temp HP = Cha modifier until start of your next turn.',
  },
  {
    id: 'marshal-back-to-back',
    name: 'Back to Back',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You excel at watching your allies\' backs and helping them watch yours. Any ally adjacent to you can\'t be off-guard due to flanking unless you\'re also flanked. Similarly, while you\'re adjacent to at least one ally, you can\'t be off-guard due to flanking unless at least one ally you\'re adjacent to is flanked as well.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Marshal Dedication'],
    mechanics: 'Adjacent allies can\'t be off-guard from flanking unless you\'re flanked. You can\'t be off-guard from flanking while adjacent to ally unless that ally is also flanked.',
  },
  {
    id: 'marshal-know-your-enemy',
    name: 'Know Your Enemy',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You aim to turn knowledge into power against your foes. Attempt a Recall Knowledge check against an enemy you\'re observing. Any ally within your aura who\'s trained in the skill you use to attempt the Recall Knowledge check can use their reaction to Aid you on the check without having prepared to help first.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication', 'Strategist Stance'],
    mechanics: '1 action. Requires Strategist Stance. Recall Knowledge vs observed enemy. Allies in aura trained in the skill can use reaction to Aid without prior preparation. Tian Xia Character Guide content.',
  },
  {
    id: 'marshal-to-battle',
    name: 'To Battle!',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'With a resounding cry, you rally your ally to take the offensive. Choose one ally in your marshal\'s aura who has a reaction available. If you spend 1 action, that ally can use their reaction to immediately Stride. If you spend 2 actions, that ally can use their reaction to immediately Strike.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Marshal Dedication'],
    mechanics: '1 or 2 actions. Ally in aura with reaction: 1 action → ally reacts to Stride; 2 actions → ally reacts to Strike.',
  },
  {
    id: 'marshal-form-up',
    name: 'Form Up!',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You\'ve trained in battle formations for a plethora of situations. Choose a formation. Allies within your aura can use their reaction to Stride up to their Speed and take a place in the chosen formation. Line: adjacent to you and each other in a straight line. Wedge: 15-foot cone from you. Cluster: 15-foot emanation around you.',
    implemented: 'full',
    traits: ['Archetype', 'Auditory', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Marshal Dedication'],
    mechanics: '2 actions. Choose formation: Line (straight adjacent), Wedge (15-ft cone), or Cluster (15-ft emanation). Allies in aura use reaction to Stride into formation. Tian Xia Character Guide content.',
  },
  {
    id: 'marshal-topple-foe',
    name: 'Topple Foe',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You take advantage of the opening created by your ally to tip your foe off their feet. Attempt an Athletics check to Trip the target of the triggering attack.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Marshal Dedication', 'Trained in Athletics'],
    mechanics: 'Reaction. Trigger: ally succeeds at melee Strike vs enemy you\'re both adjacent to. Athletics check to Trip that enemy.',
  },
  {
    id: 'marshal-coordinated-charge',
    name: 'Coordinated Charge',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You heroically dash into the fray, inspiring your allies to follow. You Stride up to your Speed and make a melee Strike. If your Strike hits, every ally within 60 feet who saw you hit can use a reaction to Stride, but they each must end their Stride closer to the creature you hit than where they started.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish', 'Visual'],
    actionCost: 2,
    prerequisites: ['Marshal Dedication'],
    mechanics: '2 actions. Stride + melee Strike. On hit: allies within 60 ft who saw use reaction to Stride (must end closer to target).',
  },
  {
    id: 'marshal-generals-gambit',
    name: "General's Gambit",
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You move strategically forward to draw the enemy\'s attention away from your allies. You Stride toward an enemy and Create a Diversion (use Society or Warfare Lore instead of Deception). On success: enemy also becomes fascinated with you until start of your next turn and can\'t use reactions against allies in aura. On critical success: fascinated until end of your next turn.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 3,
    prerequisites: ['Marshal Dedication', 'Five-breath Vanguard Dedication'],
    mechanics: '3 actions. Stride + Create a Diversion (Society/Warfare Lore instead of Deception). Success: diversion + fascinated until start of next turn, no reactions vs allies in aura. Crit: fascinated until end of next turn. Tian Xia Character Guide content.',
  },
  {
    id: 'marshal-tactical-cadence',
    name: 'Tactical Cadence',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'Your remarkable breath control and concise instructions allow you to coordinate your allies more effectively. When you grant allies the quickened condition using Cadence Call, they can use the extra action to either Stride or Strike, and they aren\'t slowed 1 on their following turn if they use the extra action.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Cadence Call', 'Marshal Dedication'],
    mechanics: 'Upgrades Cadence Call: quickened extra action can be Stride or Strike. No slowed 1 penalty afterward.',
  },
  {
    id: 'marshal-target-of-opportunity',
    name: 'Target of Opportunity',
    source: 'Marshal (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You capitalize on your ally\'s attack and use the opportunity to secure a blow of your own, adding to the oncoming barrage. Make a ranged Strike with a –2 penalty against the opponent targeted by the triggering attack. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike. If successful, combine damage with ally\'s for resistances and weaknesses.',
    implemented: 'full',
    traits: ['Archetype', 'Manipulate'],
    actionCost: 'reaction',
    prerequisites: ['Marshal Dedication'],
    mechanics: 'Reaction. Trigger: ally succeeds ranged Strike vs opponent in your first range increment. Requires ranged/thrown weapon. Ranged Strike at -2 penalty (no MAP interaction). On hit: combine damage with ally\'s for resistance/weakness.',
  },
];

// ──────────────────────────────────────────────────────────
// MARTIAL ARTIST (Player Core 2 pg. 206)
// ──────────────────────────────────────────────────────────

export const MARTIAL_ARTIST_FEATS: FeatEntry[] = [
  {
    id: 'martial-artist-dedication',
    name: 'Martial Artist Dedication',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You have trained to use your fists as deadly weapons. The damage die for your fist unarmed attacks becomes 1d6 instead of 1d4. You don\'t take the –2 circumstance penalty for making a lethal attack with your nonlethal unarmed attacks.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    mechanics: 'Fist damage die → 1d6 (from 1d4). No -2 circ penalty for lethal attacks with nonlethal unarmed. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'martial-artist-powder-punch-stance',
    name: 'Powder Punch Stance',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You infuse your handwraps with black powder. On your first melee Strike each round with an unarmed attack, you deal an additional 1 fire damage. If you critically succeed on an Athletics check to Shove while in this stance, the target is pushed back an additional 5 feet.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Stance'],
    actionCost: 1,
    prerequisites: ['Martial Artist Dedication'],
    mechanics: '1 action stance. First melee unarmed Strike/round: +1 fire damage. Crit Shove: extra 5 ft push. Requires Alkenstar/Mana Wastes access. Legacy content.',
  },
  {
    id: 'martial-artist-follow-up-strike',
    name: 'Follow-up Strike',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You have trained rigorously to use all parts of your body as a weapon, and when you miss with an attack, you can usually continue the attack with a different body part and still deal damage. Make another Strike with a melee unarmed attack, using the same multiple attack penalty as the missed Strike, if any.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Martial Artist Dedication'],
    mechanics: '1 action. Requires missed melee unarmed Strike as last action. Make another melee unarmed Strike at same MAP as the miss.',
  },
  {
    id: 'martial-artist-thunder-clap',
    name: 'Thunder Clap',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You slam your hands together to unleash a deafening blast. Creatures in a 15-foot cone take 3d6 sonic damage, with a basic Fortitude save against your class DC. Creatures that critically fail are also deafened for 1 minute. You can\'t use this again for 1d4 rounds. At 8th level and every 2 levels after, damage increases by 1d6.',
    implemented: 'full',
    traits: ['Archetype', 'Sonic'],
    actionCost: 2,
    prerequisites: ['Powder Punch Stance'],
    mechanics: '2 actions. Requires Powder Punch Stance. 15-ft cone, 3d6 sonic (+1d6 per 2 levels past 8th), basic Fort vs class DC. Crit fail: deafened 1 min. Cooldown: 1d4 rounds. Legacy content.',
  },
  {
    id: 'martial-artist-adamantine-body',
    name: 'Adamantine Body',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'With your strong will and even stronger body, you shrug off an otherwise devastating blow. You gain resistance equal to 2 + half your level against all damage from the triggering attack or effect.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Martial Artist Dedication'],
    mechanics: 'Reaction. Trigger: attack or effect would deal damage. Gain resistance = 2 + half level against all damage from the trigger. Tian Xia Character Guide content.',
  },
  {
    id: 'martial-artist-grievous-blow',
    name: 'Grievous Blow',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You know how to deliver focused, powerful blows that bypass your enemies\' resistances. Make an unarmed melee Strike. If this Strike hits, it deals two additional weapon damage dice and ignores an amount of resistance to physical damage (or to a specific physical damage type) equal to your level. This Strike counts as two attacks for MAP. At 18th level, increase to three extra dice.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Martial Artist Dedication'],
    mechanics: '2 actions. Unarmed melee Strike: +2 weapon damage dice (3 at 18th), ignores physical resistance = level. Counts as 2 attacks for MAP.',
  },
  {
    id: 'martial-artist-black-powder-flash',
    name: 'Black Powder Flash',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You ignite a pinch of black powder in a foe\'s face. Choose an adjacent creature. It must attempt a Fortitude save against your class DC. Critical Success: unaffected. Success: dazzled 1 round. Failure: blinded 1 round and dazzled 1 minute (Interact to end blind). Critical Failure: blinded 1 round and dazzled 1 hour.',
    implemented: 'full',
    traits: ['Archetype', 'Visual'],
    actionCost: 2,
    prerequisites: ['Powder Punch Stance'],
    mechanics: '2 actions. Requires Powder Punch Stance. Adjacent creature Fort vs class DC. Crit success: nothing. Success: dazzled 1 rd. Failure: blinded 1 rd + dazzled 1 min. Crit fail: blinded 1 rd + dazzled 1 hr. Legacy content.',
  },
  {
    id: 'martial-artist-path-of-iron',
    name: 'Path of Iron',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'With a burst of effort and speed, you weave a nimble path through your many enemies, striking each in turn as you move past them. You Stride; this movement doesn\'t trigger reactions. You can attempt a melee Strike up to three times at any point during your movement, each against a different enemy. Each attack counts toward your MAP, but MAP doesn\'t increase until you have made all your attacks.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 3,
    prerequisites: ['Martial Artist Dedication'],
    mechanics: '3 actions, 1/minute. Stride (no reactions triggered). Up to 3 melee Strikes vs different enemies during Stride. Each counts for MAP but penalty doesn\'t increase until all attacks made.',
  },
  {
    id: 'martial-artist-echoing-violence',
    name: 'Echoing Violence',
    source: 'Martial Artist (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'Your powerful attack causes damage that reverberates through your opponent\'s body, shaking muscle from bone. The creature takes 10d6 bludgeoning damage with a basic Fortitude save against your class DC. If it critically fails, it immediately dies as your blow tears apart its body internally.',
    implemented: 'full',
    traits: ['Archetype', 'Death', 'Incapacitation'],
    actionCost: 'free',
    prerequisites: ['Martial Artist Dedication'],
    mechanics: 'Free action, 1/minute. Trigger: crit success with unarmed Strike. Target takes 10d6 bludgeoning, basic Fort vs class DC. Crit fail Fort: immediate death. Tian Xia Character Guide content.',
  },
];

// ──────────────────────────────────────────────────────────
// MAULER (Player Core 2 pg. 207)
// ──────────────────────────────────────────────────────────

export const MAULER_FEATS: FeatEntry[] = [
  {
    id: 'mauler-dedication',
    name: 'Mauler Dedication',
    source: 'Mauler (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You specialize in melee weapons that require two hands. You have familiarity with all melee weapons that require two hands to wield or have the two-hand trait. For the purposes of proficiency, you treat any martial ones as simple weapons and advanced ones as martial weapons. If you are at least expert in such a weapon, you gain access to its critical specialization effect.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Strength +2'],
    mechanics: 'Two-hand/two-hand-trait melee weapons: martial→simple, advanced→martial for proficiency. Expert+ in such weapon: gain critical specialization effect. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'mauler-clear-the-way',
    name: 'Clear the Way',
    source: 'Mauler (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You put your body behind your massive weapon and swing, shoving enemies to clear a wide path. You attempt to Shove up to five creatures adjacent to you, rolling a separate Athletics check for each target and ignoring the requirement that you have a hand free. Then Stride up to half your Speed. This movement doesn\'t trigger reactions from any of the creatures you successfully Shoved. Each attack counts toward your MAP, but penalty doesn\'t increase until all attacks made.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 2,
    prerequisites: ['Mauler Dedication or Warrior of Legend Dedication'],
    mechanics: '2 actions. Requires wielding melee weapon in 2 hands. Shove up to 5 adjacent creatures (separate Athletics each, no free hand needed). Then Stride half Speed (no reactions from Shoved creatures). MAP shared but delayed.',
  },
  {
    id: 'mauler-shoving-sweep',
    name: 'Shoving Sweep',
    source: 'Mauler (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You swing your weapon at your foe, rebuffing them back. You attempt to Shove the triggering enemy, ignoring the requirement that you have a hand free. Unless you critically succeed, the creature continues its movement after the Shove.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Mauler Dedication', 'Expert in Athletics'],
    mechanics: 'Reaction. Trigger: enemy within reach leaves a square during move action. Requires wielding 2-hand melee. Shove vs trigger (no free hand needed). Unless crit success: enemy continues movement after Shove.',
  },
  {
    id: 'mauler-hammer-quake',
    name: 'Hammer Quake',
    source: 'Mauler (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You smash the ground with your weapon, knocking nearby creatures to the ground. Choose a square within your reach, including your own space. If there\'s an enemy in the chosen square, you can Strike that enemy with your two-handed weapon. Regardless of whether you attempted a Strike, you then attempt to Trip every enemy in the chosen square plus each square adjacent to that square, ignoring Trip\'s free hand requirement. Counts as 3 attacks for MAP but penalty doesn\'t increase until after all.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 3,
    prerequisites: ['Mauler Dedication'],
    mechanics: '3 actions. Requires non-finesse 2-hand melee. Choose square in reach: optional Strike + Trip all enemies in that square + adjacent squares (no free hand needed). Counts as 3 MAP but delayed.',
  },
  {
    id: 'mauler-avalanche-strike',
    name: 'Avalanche Strike',
    source: 'Mauler (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You attack all nearby adversaries. Make a melee Strike with your two-handed weapon against each enemy within its melee reach. Each attack counts toward your multiple attack penalty, but don\'t increase your penalty until you have made all your attacks.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 3,
    prerequisites: ['Mauler Dedication'],
    mechanics: '3 actions. Requires 2-hand melee weapon. Strike every enemy in reach. Each counts for MAP but penalty delayed until all attacks made.',
  },
];

// ──────────────────────────────────────────────────────────
// MEDIC (Player Core 2 pg. 208)
// ──────────────────────────────────────────────────────────

export const MEDIC_FEATS: FeatEntry[] = [
  {
    id: 'medic-dedication',
    name: 'Medic Dedication',
    source: 'Medic (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'You become an expert in Medicine. When you succeed with Battle Medicine, the target regains additional HP: 5 HP at DC 20, 10 HP at DC 30, or 15 HP at DC 40. Once per day, you can use Battle Medicine on a creature that\'s temporarily immune from it. If you\'re a master in Medicine, you can do so once per hour instead.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Battle Medicine', 'Trained in Medicine'],
    mechanics: 'Expert in Medicine. Battle Medicine success: +5 HP (DC 20), +10 HP (DC 30), +15 HP (DC 40). 1/day ignore Battle Medicine temp immunity (1/hr at master Medicine). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'medic-doctors-visitation',
    name: "Doctor's Visitation",
    source: 'Medic (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You move to provide immediate care to those who need it. You Stride, then use Battle Medicine or Treat Poison. If you spend 2 actions, you can instead Stride and then Administer First Aid or Treat Condition (if you have that feat).',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Medic Dedication'],
    mechanics: '1 action: Stride + Battle Medicine or Treat Poison. 2 actions: Stride + Administer First Aid or Treat Condition.',
  },
  {
    id: 'medic-treat-condition',
    name: 'Treat Condition',
    source: 'Medic (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You treat a creature\'s clumsy, drained, enfeebled, or sickened condition. Attempt a counteract check against the condition using your Medicine modifier. You can\'t treat conditions from artifacts or effects above 20th level unless you have Legendary Medic (DC +10 even then). Treating continually applied conditions has no effect while circumstances persist. Crit Success: reduce by 2. Success: reduce by 1. Crit Failure: increase by 1.',
    implemented: 'full',
    traits: ['Archetype', 'Healing', 'Manipulate', 'Skill'],
    actionCost: 2,
    prerequisites: ['Medic Dedication'],
    mechanics: '2 actions. Requires healer\'s tools or worn ones. Counteract check (Medicine modifier) vs condition (clumsy/drained/enfeebled/sickened). Crit success: -2. Success: -1. Crit fail: +1. Can\'t treat artifact/20th+ level sources (Legendary Medic: can, but DC+10).',
  },
  {
    id: 'medic-holistic-care',
    name: 'Holistic Care',
    source: 'Medic (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You provide emotional and spiritual care. Add frightened, stupefied, and stunned to the list of conditions you can reduce with Treat Condition.',
    implemented: 'full',
    traits: ['Archetype', 'Skill'],
    actionCost: 'passive',
    prerequisites: ['Treat Condition', 'Trained in Diplomacy'],
    mechanics: 'Treat Condition now also works on frightened, stupefied, and stunned conditions.',
  },
  {
    id: 'medic-preventative-treatment',
    name: 'Preventative Treatment',
    source: 'Medic (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You provide preventative remedies and care to help your patient fight off future maladies. You Treat a Condition the target doesn\'t yet have. The counteract check gains the secret trait. The next time within 1 minute the creature would be affected by that condition, your treatment immediately attempts to reduce the condition value. Lasts 1 minute, until used, or until you use it again, whichever comes first.',
    implemented: 'full',
    traits: ['Uncommon', 'Archetype', 'Secret'],
    actionCost: 'passive',
    prerequisites: ['Medic Dedication', 'Treat Condition'],
    mechanics: 'Treat Condition preemptively — name a condition target doesn\'t have. Secret counteract roll. Next time that condition would apply within 1 min: auto-attempt to reduce using the secret result. Lasts 1 min / until triggered / until reused. Legacy Knights of Lastwall content.',
  },
  {
    id: 'medic-resuscitate',
    name: 'Resuscitate',
    source: 'Medic (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'You attempt to revive a creature that died within the last 3 rounds whose body is mostly intact. If you succeed, the target returns to life with the effects of raise dead, except it still has the wounded condition it had before dying, increased by 1 (or wounded 1 if it wasn\'t wounded). Whether you succeed or fail, the target is temporarily immune to Resuscitate for 1 day.',
    implemented: 'full',
    traits: ['Archetype', 'Healing', 'Manipulate'],
    actionCost: 3,
    prerequisites: ['Medic Dedication', 'Legendary in Medicine'],
    mechanics: '3 actions. Requires healer\'s tools. Target: creature dead within 3 rounds, body mostly intact. Medicine check DC 40. Success: raise dead effects, wounded condition +1 from before death. Temp immune 1 day.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_HM: FeatEntry[] = [
  ...HERBALIST_FEATS,
  ...HORIZON_WALKER_FEATS,
  ...LINGUIST_FEATS,
  ...LOREMASTER_FEATS,
  ...MARSHAL_FEATS,
  ...MARTIAL_ARTIST_FEATS,
  ...MAULER_FEATS,
  ...MEDIC_FEATS,
];
