import { FeatEntry } from './featTypes';

// ══════════════════════════════════════════════════════════
// NON-CORE ARCHETYPE FEATS — B through W (creatures/battle)
// Bloodrager, Thlipit Contestant, Wild Mimic
// ══════════════════════════════════════════════════════════

// ──────────────────────────────────────────────────────────
// BLOODRAGER  (War of Immortals pg. 60–61)
// Category: Class Archetype (Barbarian) — Uncommon
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=283
// Must be a Barbarian with the Bloodrager instinct.
// ──────────────────────────────────────────────────────────

export const BLOODRAGER_FEATS: FeatEntry[] = [
  {
    id: 'bloodrager-dedication',
    name: 'Bloodrager Dedication',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Drinking powerful blood has awakened magical potential within you. You gain a spell repertoire with two cantrips of your choice, from either the arcane or divine spell list. At least one cantrip must require a spell attack roll. You\'re trained in spell attack modifier and spell DC. Your key spellcasting attribute for these spells is Charisma. Spells in your repertoire gain the rage trait while you are raging, and when you Cast a Spell from your repertoire, you become drained 1 (or increase by 1); you can reduce this only by Harvesting Blood. You become trained in Arcana (arcane) or Religion (divine). You also gain Harvest Blood.',
    implemented: 'full',
    traits: ['Archetype', 'Class', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Bloodrager instinct'],
    mechanics: 'Grants arcane or divine cantrip repertoire (CHA-based). Casting inflicts drained 1 (stacking). Harvest Blood [one-action]: after successful piercing/slashing melee Strike vs bleedable creature, reduce drained by 1, gain temp HP = CON mod, +1 circumstance to saves vs that creature\'s spells (1 min). Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'bloodrager-blood-calls-blood',
    name: 'Blood Calls Blood',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'The magical potency of your blood will not be denied. You finish Casting the Spell as though the disruption or flat check failure hadn\'t occurred.',
    implemented: 'full',
    traits: ['Archetype', 'Fortune'],
    actionCost: 'reaction',
    prerequisites: ['Bloodrager Dedication'],
    mechanics: 'Trigger: You fail a flat check to Cast a Spell or your spell would be disrupted by another creature\'s reaction. Fortune — completes the spell despite disruption.',
  },
  {
    id: 'bloodrager-rising-blood-magic',
    name: 'Rising Blood Magic',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'The power within your blood grows. You gain the basic spellcasting benefits. Each time you gain a spell slot of a new rank from the bloodrager archetype, add a common spell of the appropriate tradition and rank to your repertoire. In addition, when you Cast a Spell from your repertoire and you are at least drained 1, increase the extra damage dealt by that spell from Rage by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Bloodrager Dedication'],
    mechanics: 'Basic spellcasting benefits (spell slots up to half level, capped at rank 2). When drained 1+, spells deal +1 extra Rage damage.',
  },
  {
    id: 'bloodrager-siphon-magic',
    name: 'Siphon Magic',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You gorge upon the magical energies of your foe\'s blood. You regain one expended spell slot that must be of a lower rank than the highest rank spell you can cast. You become drained 1 or increase the value of your drained condition by 1.',
    implemented: 'full',
    traits: ['Archetype', 'Rage'],
    actionCost: 1,
    prerequisites: ['Bloodrager Dedication'],
    mechanics: 'Requires last action was Harvest Blood from a spellcaster. Regain one expended spell slot (lower rank than your max). Increases drained by 1. Rage trait (must be raging). PFS: cannot use on friendly allies or defeated opponents.',
  },
  {
    id: 'bloodrager-spelldrinker',
    name: 'Spelldrinker',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You temporarily add a 3rd-rank spell to your spell repertoire, as determined by the type of creature whose blood you just drank. If the creature has more than one listed trait, choose one. Aberration: vampiric feast. Animal/Beast: summon animal. Celestial: holy light. Dragon: blazing bolt (damage matches dragon breath type). Fey: wall of thorns. Fiend: chilling darkness. Giant: pummeling rubble. Humanoid: crisis of faith. Monitor: impending doom. The spell is removed after 24 hours, next Spelldrinker use, or daily preparations.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Rising Blood Magic'],
    mechanics: 'Requires last action was Harvest Blood. Gain a 3rd-rank spell based on creature type trait. Spell upgrades to 4th rank with Surging Blood Magic, 7th with Exultant Blood Magic. Removed after 24 hours or next use.',
  },
  {
    id: 'bloodrager-hematocritical',
    name: 'Hematocritical',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You bathe in the arterial fluids of your enemy, drinking deep of their freed essence to empower your magic. If your next action is to Cast a Spell that requires a spell attack roll, you roll the spell attack roll twice and use the better result (fortune). Alternatively, if the spell requires the damaged creature to attempt a save, they roll twice and take the lower result (misfortune).',
    implemented: 'full',
    traits: ['Archetype', 'Fortune', 'Rage'],
    actionCost: 'free',
    prerequisites: ['Bloodrager Dedication'],
    mechanics: 'Requires last action was a critical hit Strike vs bleedable creature. Next spell gets fortune on attack OR misfortune on save for the crit target. Rage trait.',
  },
  {
    id: 'bloodrager-surging-blood-magic',
    name: 'Surging Blood Magic',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'Your blood courses with magic. You gain the expert spellcasting benefits. In addition, when you Cast a Spell from your repertoire and you are at least drained 1, increase the extra damage dealt by that spell from Rage by 2.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Rising Blood Magic', 'Master in Arcana or Religion (chosen tradition)'],
    mechanics: 'Expert spellcasting benefits (higher-rank slots, up to rank 5). When drained 1+, spells deal +2 Rage damage (replaces +1 from Rising Blood Magic).',
  },
  {
    id: 'bloodrager-exultant-blood-magic',
    name: 'Exultant Blood Magic',
    source: 'Bloodrager (Archetype)',
    category: 'archetype',
    level: 18,
    description: 'The magic in your blood sings an exultant song of battle. You gain the master spellcasting benefits. Increase the spell slots you gain from the bloodrager archetype feats by 1 for each spell rank. In addition, when you Cast a Spell from your repertoire and you are at least drained 2, double the extra damage dealt by that spell from Rage instead.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Surging Blood Magic', 'Legendary in Arcana or Religion (chosen tradition)'],
    mechanics: 'Master spellcasting benefits (up to rank 8). +1 spell slot per rank. When drained 2+, double Rage damage bonus on spells.',
  },
];

// ──────────────────────────────────────────────────────────
// THLIPIT CONTESTANT  (Howl of the Wild pg. 74–75)
// Category: Profession — Common
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=224
// Requires a prehensile tongue, tail, or similar appendage.
// ──────────────────────────────────────────────────────────

export const THLIPIT_CONTESTANT_FEATS: FeatEntry[] = [
  {
    id: 'thlipit-contestant-dedication',
    name: 'Thlipit Contestant Dedication',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Grueling practice has strengthened your tongue or tail to the point where it\'s become a formidable weapon. You gain a lash melee unarmed attack that is in the flail weapon group, deals 1d4 bludgeoning damage, and has the grapple and reach traits. The attack can be performed with any appendages you used to qualify for this feat.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['You have a long prehensile tongue or a tail'],
    mechanics: 'Grants lash unarmed attack: 1d4 bludgeoning, flail group, grapple + reach traits. Uses tongue, tail, or tentacles. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'thlipit-contestant-fly-swat',
    name: 'Fly Swat',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You\'ve learned the secret of swatting away annoying pests and occasionally getting an easy meal out of it. Your lash strikes ignore an amount of swarms\' resistance to physical damage equal to your level.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: 'Lash strikes ignore swarm resistance to physical damage up to your level.',
  },
  {
    id: 'thlipit-contestant-lassoing-lash',
    name: 'Lassoing Lash',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You quickly wrap your lash around an opponent and pull them toward you. Attempt an Athletics check against the Fortitude DC of a target within your lash\'s reach. Critical Success: Pull target to any open adjacent space. Success: Pull target to nearest open adjacent space. Critical Failure: You fall prone.',
    implemented: 'full',
    traits: ['Archetype', 'Attack'],
    actionCost: 1,
    prerequisites: ['Thlipit Contestant Dedication', 'Trained in Athletics'],
    mechanics: 'Athletics vs Fortitude DC. Target can\'t be more than one size larger. Crit success: choose adjacent space. Success: nearest adjacent. Crit fail: fall prone. Titan Wrestler allows +1/+2 size larger.',
  },
  {
    id: 'thlipit-contestant-powerful-lash',
    name: 'Powerful Lash',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You\'ve learned to swing your lash ever faster and in wider arcs. The damage die of your lash increases to 1d6 instead of 1d4 and it gains the sweep trait.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'passive',
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: 'Upgrades lash to 1d6 damage and adds sweep trait.',
  },
  {
    id: 'thlipit-contestant-snap-falling-fruit',
    name: 'Snap Falling Fruit',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your lash whips around to intercept projectiles. The target gains a +2 circumstance bonus to AC against the triggering attack. If the attack misses, you knock it out of the air.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: 'Trigger: You or ally within lash reach is target of physical ranged attack. +2 circumstance AC vs the attack. If it misses, projectile is deflected.',
  },
  {
    id: 'thlipit-contestant-levered-swing',
    name: 'Levered Swing',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'You can wrap your lash around a tree branch or railing, then pull yourself where you need to go. Choose a solid anchor point within reach of your lash. You Fly up to your Speed as you pivot around the anchor, ending in an open space where the anchor is still within reach of your lash. If you don\'t end your turn in a space you could stand, you fall.',
    implemented: 'full',
    traits: ['Archetype', 'Move'],
    actionCost: 1,
    prerequisites: ['Thlipit Contestant Dedication', 'Master in Athletics'],
    mechanics: 'Fly up to your Speed by swinging around a solid anchor within lash reach. Must end within lash reach of anchor or fall.',
  },
  {
    id: 'thlipit-contestant-slurp-up',
    name: 'Slurp Up',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Your tongue darts out in search of refreshment. Choose a liquid container of up to light Bulk within reach of your lash. If unattended or held by willing ally, you Interact to drink the contents. If held by unwilling creature, you must succeed on a check using your unarmed attack modifier or Thievery modifier against the creature\'s Reflex DC.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Thlipit Contestant Dedication', 'Unarmed attack with your tongue'],
    mechanics: 'Drink a potion/elixir within lash reach using tongue. Free from willing sources; requires attack or Thievery vs Reflex DC from unwilling holders. Tongue-only feat.',
  },
  {
    id: 'thlipit-contestant-tail-guard',
    name: 'Tail Guard',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Enemies who attempt to stab you in the back will be unhappy to find your lashing tail on guard. Make a melee Strike against the triggering creature. If your attack is a critical hit, the movement is disrupted. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Thlipit Contestant Dedication', 'Unarmed attack with your tail'],
    mechanics: 'Trigger: A creature enters a square that would flank you. Melee Strike (no MAP interaction). Crit hit disrupts flanking movement. Tail-only feat.',
  },
  {
    id: 'thlipit-contestant-slingshot-maneuver',
    name: 'Slingshot Maneuver',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You spin your lash out for your ally to grab on to, giving them a boost to their movement. You move the ally 15 feet into a square of their choice that is within reach of your lash. If the ally has movement remaining, they can continue their movement after completing the Slingshot Maneuver.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: 'Trigger: A willing ally enters a space within your lash reach using a move action. Move ally 15 feet to a square within lash reach. Ally can continue moving afterward.',
  },
  {
    id: 'thlipit-contestant-reflexive-grapple',
    name: 'Reflexive Grapple',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You\'ve honed your reflexes so well that your lash can begin closing around a target as soon as it makes contact. Make a lash Strike; if the Strike hits, you can immediately attempt to Grapple the target. Both actions count toward your multiple attack penalty, but don\'t increase your penalty until you\'ve made both attacks.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 1,
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: '1-action Strike + Grapple combo with lash. If Strike hits, immediately Grapple. Both share same MAP bracket.',
  },
  {
    id: 'thlipit-contestant-spinning-release',
    name: 'Spinning Release',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You wind your lash around your opponent, then spin them rapidly to discombobulate them. You release your opponent, sending them wobbling 10 feet in a direction of your choice (forced movement). Fortitude save vs class DC. Failure: confused until end of their next turn (then immune to confused/sickened from this for 10 min). Critical Failure: as failure, plus sickened 1.',
    implemented: 'full',
    traits: ['Archetype', 'Mental'],
    actionCost: 3,
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: 'Requires creature grabbed/restrained with lash. Release + force-move 10 feet. Fort save: failure = confused (1 turn), crit fail = also sickened 1. 10-min immunity to confused/sickened from this.',
  },
  {
    id: 'thlipit-contestant-whirling-clobber',
    name: 'Whirling Clobber',
    source: 'Thlipit Contestant (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'After you\'ve grasped a creature with your lash, you swing them around like a whirling hammer, smashing them into all nearby enemies. Make a melee Strike against each enemy within your melee reach. Your last attack must be against the grabbed creature, and you gain a circumstance bonus to your attack roll equal to the number of enemies you slammed them into, to a maximum of +3. Each attack counts toward MAP but don\'t increase penalty until all attacks are made. After, you release the creature into an open square within lash reach.',
    implemented: 'full',
    traits: ['Archetype', 'Attack'],
    actionCost: 3,
    prerequisites: ['Thlipit Contestant Dedication'],
    mechanics: 'Requires creature grabbed/restrained with lash. Strike each enemy in melee reach; final Strike vs grabbed creature gets up to +3 circumstance bonus from number of enemies hit. All share MAP bracket. Releases creature after.',
  },
];

// ──────────────────────────────────────────────────────────
// WILD MIMIC  (Howl of the Wild pg. 80–81)
// Category: Mystical — Common (PFS: Limited)
// AoN: https://2e.aonprd.com/Archetypes.aspx?ID=226
// Mimics creature abilities you've witnessed or identified.
// ──────────────────────────────────────────────────────────

export const WILD_MIMIC_FEATS: FeatEntry[] = [
  {
    id: 'wild-mimic-dedication',
    name: 'Wild Mimic Dedication',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 2,
    description: 'Fighting in the wilds has honed your understanding of the unique abilities many creatures have. You\'re trained in Wild Mimic Lore, a special Lore skill that can be used only to Recall Knowledge about creatures to learn their abilities. If you have legendary proficiency in Nature, you gain expert proficiency in Wild Mimic Lore. When you succeed at Wild Mimic Lore to Recall Knowledge, you gain a +1 circumstance bonus to your saving throws against the next attack or ability the subject targets you with.',
    implemented: 'full',
    traits: ['Archetype', 'Dedication'],
    actionCost: 'passive',
    prerequisites: ['Trained in Nature'],
    mechanics: 'Grants Wild Mimic Lore (creature abilities only). Successful Recall Knowledge: +1 circumstance to saves vs that creature\'s next ability targeting you. Expert with legendary Nature. Dedication-lock enforced by validateDedicationTaking().',
  },
  {
    id: 'wild-mimic-ferocity-mimicry',
    name: 'Ferocity Mimicry',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'You have trained yourself to continue fighting even when your body is screaming for you to stop. You avoid being knocked out and remain at 1 Hit Point, and your wounded condition increases by 1.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 'reaction',
    prerequisites: ['Wild Mimic Dedication', 'Encountered or identified a creature with Ferocity or similar'],
    mechanics: 'Trigger: Reduced to 0 HP but not instantly killed. Frequency: once per day. Stay at 1 HP, wounded +1.',
  },
  {
    id: 'wild-mimic-rend-mimicry',
    name: 'Rend Mimicry',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 4,
    description: 'Taking advantage of the brutal efficiency of hacking away at a target with two slashing attacks, you\'ve mastered the art of punishing a foe caught between your slices. You deal 1d6 slashing damage to the target. This damage increases to 2d6 at 10th level and to 3d6 at 16th level.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Wild Mimic Dedication', 'Seen or identified a creature with Rend'],
    mechanics: 'Requires two consecutive slashing melee Strikes on same enemy. Bonus 1d6 slashing (2d6 at 10th, 3d6 at 16th). Flourish (1/turn).',
  },
  {
    id: 'wild-mimic-electrogenesis',
    name: 'Electrogenesis',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Some animals and beasts have electric organs in their body that they can use to jolt their prey. Make a melee unarmed Strike against a creature. If the Strike hits, it deals an additional 1d12 electricity damage, and the creature must make a Fortitude save against the higher of your class DC or spell DC. Critical Success: unaffected. Success: clumsy 1 for 1 round. Failure: clumsy 2 for 1 round. Critical Failure: clumsy 3 for 1 round.',
    implemented: 'full',
    traits: ['Archetype', 'Electricity', 'Primal'],
    actionCost: 2,
    prerequisites: ['Wild Mimic Dedication', 'Seen or identified creature with electric unarmed Strike'],
    mechanics: 'Frequency: once per 10 minutes. Unarmed Strike + 1d12 electricity + Fort save for clumsy 1-3.',
  },
  {
    id: 'wild-mimic-primal-proportions',
    name: 'Primal Proportions',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'You can mimic the sheer mass of the largest beasts. You can cast enlarge, targeting yourself once per 10 minutes as an innate 2nd-rank primal spell. At 12th level, the spell is heightened to 4th rank.',
    implemented: 'full',
    traits: ['Archetype', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Wild Mimic Dedication'],
    mechanics: 'Self-only innate enlarge (2nd rank, heightened to 4th at level 12). Once per 10 minutes.',
  },
  {
    id: 'wild-mimic-wild-speech',
    name: 'Wild Speech',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 6,
    description: 'Your connection to the denizens of the wilds grows ever stronger, and you find yourself able to speak with animals like you would in your native tongue. You can speak with all animals and beasts. If you have Animal Empathy, you gain a +1 circumstance bonus to checks to Make an Impression on animals.',
    implemented: 'full',
    traits: ['Archetype', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Wild Mimic Dedication', 'Animal Empathy or the ability to speak with a type of animal'],
    mechanics: 'Speak with all animals and beasts. +1 circumstance to Make an Impression on animals if you have Animal Empathy.',
  },
  {
    id: 'wild-mimic-environmental-adaptability',
    name: 'Environmental Adaptability',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 8,
    description: 'Having experienced the harshest environs that nature has to offer, your body is able to adapt to intense heat and cold. During your daily preparations, you can choose to become protected from the effects of severe cold or severe heat until the next time you make your daily preparations. Starting at 12th level, this activity also protects you from the effects of extreme cold or extreme heat.',
    implemented: 'full',
    traits: ['Archetype', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['Wild Mimic Dedication'],
    mechanics: 'Daily prep choice: protection from severe cold or heat. At 12th level, also covers extreme cold/heat.',
    subChoices: { label: 'Choose environmental protection', options: [
      { id: 'cold', name: 'Cold', description: 'Protection from severe (extreme at 12th) cold' },
      { id: 'heat', name: 'Heat', description: 'Protection from severe (extreme at 12th) heat' },
    ] },
  },
  {
    id: 'wild-mimic-petrifying-gaze-mimicry',
    name: 'Petrifying Gaze Mimicry',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You have learned to petrify those you lock eyes with. You stare at a creature you can see within 30 feet. The creature attempts a Fortitude save against the higher of your class DC or spell DC. Critical Success: unaffected, immune 24 hours. Success: slowed 1 for 1 round. Failure: slowed 1 for 1 round and immobilized until Escape. Critical Failure: slowed 2 for 1 round and immobilized until Escape.',
    implemented: 'full',
    traits: ['Archetype', 'Concentrate', 'Incapacitation', 'Primal', 'Visual'],
    actionCost: 2,
    prerequisites: ['Wild Mimic Dedication', 'Survived or identified creature with petrifying gaze'],
    mechanics: 'Fort save at 30 feet. Failure = slowed + immobilized. Cooldown: 1d4 rounds. Incapacitation reduces effectiveness on higher-level targets.',
  },
  {
    id: 'wild-mimic-trample-mimicry',
    name: 'Trample Mimicry',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 10,
    description: 'You Stride up to double your speed and can move through the spaces of creatures at least one size smaller, trampling each creature whose space you enter. You deal 3d12 bludgeoning damage to each trampled creature (basic Reflex save against the higher of your class DC or spell DC). This damage increases by 1d12 at levels 14 and 18.',
    implemented: 'full',
    traits: ['Archetype'],
    actionCost: 3,
    prerequisites: ['Wild Mimic Dedication', 'Seen or identified creature with Trample'],
    mechanics: 'Stride at double speed, trample smaller creatures for 3d12 bludgeoning (basic Reflex). +1d12 at 14th and 18th. One trample per creature per use.',
  },
  {
    id: 'wild-mimic-roar-mimicry',
    name: 'Roar Mimicry',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 12,
    description: 'You unleash a roar so loud that it\'s felt as deeply as it\'s heard. All creatures within a 15-foot emanation take 8d6 sonic damage and must attempt a Fortitude save against the higher of your class DC or spell DC. This damage increases by 2d6 at 14th level and every 2 levels thereafter. Critical Success: unaffected. Success: half damage. Failure: full damage, stunned 1, deafened 1 round if adjacent. Critical Failure: double damage, stunned 2, deafened 1 minute if adjacent.',
    implemented: 'full',
    traits: ['Archetype', 'Primal', 'Sonic'],
    actionCost: 2,
    prerequisites: ['Wild Mimic Dedication', 'Targeted by or identified creature with area auditory ability'],
    mechanics: 'Frequency: once per 10 minutes. 15-foot emanation, 8d6 sonic (scaling +2d6 every 2 levels from 14th). Fort save: failure = stunned 1 + deafened if adjacent; crit fail = stunned 2 + deafened 1 min if adjacent.',
  },
  {
    id: 'wild-mimic-pounce-mimicry',
    name: 'Pounce Mimicry',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 14,
    description: 'You have mastered the art of stalking your prey and striking when they are most vulnerable. You Stride and then Strike. If you began this action hidden, you remain hidden until after the Strike. You can use Pounce Mimicry while Burrowing, Climbing, Flying, or Swimming instead of Striding if you have the corresponding movement type.',
    implemented: 'full',
    traits: ['Archetype', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Wild Mimic Dedication', 'Seen or identified creature with Pounce-like ability'],
    mechanics: '1-action Stride + Strike. Stay hidden if started hidden. Works with Burrow/Climb/Fly/Swim. Flourish. Light armor or unarmored only.',
  },
  {
    id: 'wild-mimic-emergency-regeneration',
    name: 'Emergency Regeneration',
    source: 'Wild Mimic (Archetype)',
    category: 'archetype',
    level: 16,
    description: 'While your body doesn\'t regenerate all the time, it can happen in a pinch. You gain the effects of a 7th-rank regenerate spell. At 20th level, you gain the effects of a 9th-rank regenerate instead.',
    implemented: 'full',
    traits: ['Archetype', 'Healing', 'Primal', 'Vitality'],
    actionCost: 'reaction',
    prerequisites: ['Wild Mimic Dedication', 'Deactivated or identified creature with regeneration'],
    mechanics: 'Trigger: Reduced to 0 HP from non-acid/non-fire damage. Frequency: once per day. Gain 7th-rank regenerate (9th-rank at 20th). Must have encountered regeneration.',
  },
];

// ──────────────────────────────────────────────────────────
// COMBINED CATALOG
// ──────────────────────────────────────────────────────────

export const STANDALONE_ARCHETYPE_FEATS_NON_CORE_BW: FeatEntry[] = [
  ...BLOODRAGER_FEATS,
  ...THLIPIT_CONTESTANT_FEATS,
  ...WILD_MIMIC_FEATS,
];
