/**
 * Barbarian Class Features & Feats â€” PF2e Remastered (Player Core 2)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=57
 *
 * Key Attribute: STR | HP: 12 + CON
 * Perception: Expert â†’ Master (L17, Perception Mastery)
 * Fort: Expert â†’ Master (L7, Juggernaut, successâ†’crit) â†’ Legendary (L13, Greater Juggernaut, crit-failâ†’fail, half on fail)
 * Reflex: Trained â†’ Expert (L9, Reflex Expertise)
 * Will: Expert â†’ Master (L15, Indomitable Will, successâ†’crit)
 * Weapons: Trained simple+martial+unarmed â†’ Expert (L5, Brutality) â†’ Master (L13, Weapon Mastery) â†’ Legendary (L19, Devastator)
 * Armor: Trained light+medium+unarmored â†’ Expert (L13, Medium Armor Expertise) â†’ Master (L19, Armor Mastery)
 * Class DC: Trained â†’ Expert (L11, Mighty Rage) â†’ Master (L19, Devastator)
 *
 * Instincts: Animal, Dragon, Fury, Giant, Spirit, Superstition
 *
 * Class feats: 81 PC2 common feats (AoN trait ID 813)
 * Supplemental feats exist in Rage of Elements & Howl of the Wild (not included here)
 */

import type { FeatEntry } from './featTypes';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
  GREATER_WEAPON_SPECIALIZATION,
  JUGGERNAUT,
} from './sharedFeats';

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// BARBARIAN CLASS FEATURES (Automatically Granted)
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export const BARBARIAN_CLASS_FEATURES: FeatEntry[] = [
  // â”€â”€ Level 1 â”€â”€
  {
    id: 'barbarian-rage',
    name: 'Rage',
    source: 'Barbarian',
    category: 'class_feature',
    level: 1,
    description: 'You can channel your fury to enhance your combat abilities. You can Rage as a single action, gaining additional damage on melee Strikes and thrown weapons (+2 at 1st level, increasing with weapon specialization). While raging, you take a -1 penalty to AC and can\'t use actions with the concentrate trait unless they also have the rage trait. Your rage lasts for 1 minute, until there are no enemies you can perceive, or until you fall unconscious. You can\'t voluntarily stop raging. After you stop raging, you can\'t Rage again for 1 round.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Emotion', 'Mental'],
    actionCost: 1,
  },
  {
    id: 'barbarian-quick-tempered',
    name: 'Quick-Tempered',
    source: 'Barbarian',
    category: 'class_feature',
    level: 1,
    description: 'So long as you are able to move freely, your fury is instinctive and instantaneous. When you roll initiative, if you are not encumbered or wearing heavy armor, you Rage as a free action.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'free',
    mechanics: 'Trigger: Roll initiative. Req: Not encumbered or wearing heavy armor. You Rage. At L11 (Mighty Rage), first Strike on first turn deals additional Rage damage.',
  },
  {
    id: 'barbarian-instinct',
    name: 'Instinct',
    source: 'Barbarian',
    category: 'class_feature',
    level: 1,
    description: 'Your rage wells up from a dominant instinct â€” a connection to a powerful force or creature that shapes the nature of your fury. Choose an instinct from Animal, Dragon, Fury, Giant, Spirit, or Superstition. Your instinct grants you an instinct ability, determines the additional damage type you deal while raging, and gives you instinct-specific feats at higher levels. It also determines your anathema.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Builder must capture instinct choice. Instinct determines: rage damage type, instinct ability, anathema, and instinct-specific feats.',
    subChoices: { label: 'Choose an instinct', options: [
      { id: 'animal', name: 'Animal', description: 'Rage damage: extra damage with unarmed attacks (claw/jaws)' },
      { id: 'dragon', name: 'Dragon', description: 'Rage damage: chosen energy type (acid/cold/electricity/fire/poison)' },
      { id: 'fury', name: 'Fury', description: 'Rage damage: extra melee weapon damage, no anathema' },
      { id: 'giant', name: 'Giant', description: 'Rage damage: extra damage with larger weapons (Titan Mauler)' },
      { id: 'spirit', name: 'Spirit', description: 'Rage damage: vitality/void depending on target' },
      { id: 'superstition', name: 'Superstition', description: 'Rage damage: extra vs spellcasters, +2 saves vs magic' },
    ] },
  },
  // â”€â”€ Level 3 â”€â”€
  {
    id: 'barbarian-furious-footfalls',
    name: 'Furious Footfalls',
    source: 'Barbarian',
    category: 'class_feature',
    level: 3,
    description: 'Your speed increases by 5 feet. While raging, your speed increases by 10 feet instead.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: '+5 ft Speed always, +10 ft Speed while raging (replaces the +5).',
  },
  // â”€â”€ Level 5 â”€â”€
  {
    id: 'barbarian-brutality',
    name: 'Brutality',
    source: 'Barbarian',
    category: 'class_feature',
    level: 5,
    description: 'Your fury makes your weapons lethal. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  // â”€â”€ Level 7 â”€â”€
  createClassFeature(JUGGERNAUT, 'Barbarian', 7),
  createClassFeature(WEAPON_SPECIALIZATION, 'Barbarian', 7),
  // â”€â”€ Level 9 â”€â”€
  {
    id: 'barbarian-raging-resistance',
    name: 'Raging Resistance',
    source: 'Barbarian',
    category: 'class_feature',
    level: 9,
    description: 'While raging, you gain resistance to damage based on your instinct. The amount equals 3 + your Constitution modifier.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Resistance type determined by instinct (e.g., Animal = piercing/slashing, Dragon = element of breath, Fury = physical, Giant = bludgeoning, Spirit = void, Superstition = all magic). Amount = 3 + CON mod.',
  },
  {
    id: 'barbarian-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Barbarian',
    category: 'class_feature',
    level: 9,
    description: 'Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  // â”€â”€ Level 11 â”€â”€
  {
    id: 'barbarian-mighty-rage',
    name: 'Mighty Rage',
    source: 'Barbarian',
    category: 'class_feature',
    level: 11,
    description: 'Your rage intensifies. Your proficiency rank for your barbarian class DC increases to expert. The damage you deal on the Strike granted by Quick-Tempered increases.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Class DC â†’ expert. Quick-Tempered Strike bonus damage increases.',
  },
  // â”€â”€ Level 13 â”€â”€
  {
    id: 'barbarian-greater-juggernaut',
    name: 'Greater Juggernaut',
    source: 'Barbarian',
    category: 'class_feature',
    level: 13,
    description: 'Your Fortitude saves are truly incredible. Your proficiency rank for Fortitude saves increases to legendary. When you roll a critical failure on a Fortitude save, you get a failure instead. When you roll a failure on a Fortitude save against an effect that deals damage, you halve the damage you take.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  {
    id: 'barbarian-medium-armor-expertise',
    name: 'Medium Armor Expertise',
    source: 'Barbarian',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned to defend yourself better against attacks. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  {
    id: 'barbarian-weapon-mastery',
    name: 'Weapon Mastery',
    source: 'Barbarian',
    category: 'class_feature',
    level: 13,
    description: 'You fully unleash your rage through your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  // â”€â”€ Level 15 â”€â”€
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Barbarian', 15),
  {
    id: 'barbarian-indomitable-will',
    name: 'Indomitable Will',
    source: 'Barbarian',
    category: 'class_feature',
    level: 15,
    description: 'Your rage makes it difficult to control you. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  // â”€â”€ Level 17 â”€â”€
  {
    id: 'barbarian-perception-mastery',
    name: 'Perception Mastery',
    source: 'Barbarian',
    category: 'class_feature',
    level: 17,
    description: 'Your instinct sharpens all of your senses. Your proficiency rank for Perception increases to master.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  {
    id: 'barbarian-revitalizing-rage',
    name: 'Revitalizing Rage',
    source: 'Barbarian',
    category: 'class_feature',
    level: 17,
    description: 'Your rage sustains you more frequently, leaving you ready to jump into battle anew. Instead of needing to wait 1 minute before you can gain temporary Hit Points from Rage again, you need only to spend at least one full turn not in a Rage.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Reduces Rage cooldown from 1 minute to 1 full turn not raging.',
  },
  // â”€â”€ Level 19 â”€â”€
  {
    id: 'barbarian-armor-mastery',
    name: 'Armor Mastery',
    source: 'Barbarian',
    category: 'class_feature',
    level: 19,
    description: 'Your training and rage have made your armor feel like a second skin. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
  },
  {
    id: 'barbarian-devastator',
    name: 'Devastator',
    source: 'Barbarian',
    category: 'class_feature',
    level: 19,
    description: 'Your proficiency rank for your barbarian class DC increases to master. Your melee Strikes ignore the first 10 points of a creature\'s resistance to their physical damage. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to legendary.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Class DC â†’ master. Weapons â†’ legendary. Melee Strikes ignore first 10 points of physical resistance.',
  },
];

// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// BARBARIAN CLASS FEATS (Selectable at class feat levels)
// Source: PC2 pp. 77-86 (AoN trait ID 813)
// Total: 81 feats across levels 1-20
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export const BARBARIAN_CLASS_FEATS: FeatEntry[] = [
  // â”€â”€ Level 1 (7 feats) â”€â”€
  {
    id: 'barbarian-acute-vision',
    name: 'Acute Vision',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'When you are raging, your visual senses improve, granting you darkvision.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Grants darkvision while Rage is active.',
  },
  {
    id: 'barbarian-adrenaline-rush',
    name: 'Adrenaline Rush',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'In the heat of battle, you are capable of amazing feats of strength. While you are raging, increase your encumbered and maximum Bulk limits by 2; you also gain a +1 status bonus to Athletics checks to lift heavy objects, Escape, and Force Open.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    mechanics: 'While raging: +2 Bulk limits, +1 status bonus to Athletics for lift/Escape/Force Open.',
  },
  {
    id: 'barbarian-draconic-arrogance',
    name: 'Draconic Arrogance',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'Few can sway you from your goals while the fury of combat fills you. While raging, you gain a +2 status bonus to saving throws against emotion effects.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    prerequisites: ['dragon instinct'],
    mechanics: 'While raging: +2 status bonus to saves vs emotion effects.',
  },
  {
    id: 'barbarian-moment-of-clarity',
    name: 'Moment of Clarity',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'You push back your rage for a moment in order to think clearly. Until the end of this turn, you can use actions with the concentrate trait even while raging.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    mechanics: 'Allows concentrate-trait actions until end of turn while raging.',
  },
  {
    id: 'barbarian-raging-intimidation',
    name: 'Raging Intimidation',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'Your fury fills your foes with fear. You can use Intimidation actions (such as Demoralize) while raging, even though they normally have the concentrate trait; they gain the rage trait when you use them while raging. Additionally, you gain a +2 circumstance bonus to Demoralize checks while raging.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Allows Intimidation while raging (gains rage trait). +2 circumstance to Demoralize while raging.',
  },
  {
    id: 'barbarian-raging-thrower',
    name: 'Raging Thrower',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'Thrown weapons become especially deadly in your fury. You apply your additional damage from Rage to thrown weapon attacks. If you have the Brutal trait on a thrown weapon, you also add your weapon specialization damage.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Rage bonus damage applies to thrown weapon Strikes.',
  },
  {
    id: 'barbarian-sudden-charge',
    name: 'Sudden Charge',
    source: 'Barbarian',
    category: 'class',
    level: 1,
    description: 'With a quick sprint, you dash up to your foe and swing. Stride twice. If you end your movement within melee reach of at least one enemy, you can make a melee Strike against that enemy.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter', 'Flourish'],
    actionCost: 2,
    mechanics: 'Stride twice, then melee Strike if within reach. Shared with Fighter.',
  },
  // â”€â”€ Level 2 (7 feats) â”€â”€
  {
    id: 'barbarian-acute-scent',
    name: 'Acute Scent',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'When your anger is heightened, your sense of smell improves. When you are raging, you gain imprecise scent with a range of 30 feet.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Grants imprecise scent 30 ft while raging.',
  },
  {
    id: 'barbarian-bashing-charge',
    name: 'Bashing Charge',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'You smash, bust, and charge through solid obstacles without hesitation. You Stride, attempting to Force Open one door or obstacle along the way. On a success, you can continue to Stride to finish your movement. If you end your movement within melee reach of at least one enemy, you can make a melee Strike against that enemy.',
    implemented: 'full',
    traits: ['Barbarian', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Trained in Athletics'],
    mechanics: 'Stride + Force Open obstacle + continue Stride + Strike. Needs Athletics for Force Open.',
  },
  {
    id: 'barbarian-furious-finish',
    name: 'Furious Finish',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'Desperate to finish the fight, you pour all your rage into one final blow. Make a Strike. If it hits, you can maximize the Strike\'s damage dice (don\'t roll, use max values). Your Rage then immediately ends, and you are fatigued until you rest for 10 minutes.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 1,
    mechanics: 'Strike with maximized damage dice. Rage ends immediately. Fatigued until 10 min rest.',
  },
  {
    id: 'barbarian-intimidating-strike',
    name: 'Intimidating Strike',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'Your blow not only wounds creatures but also shatters their confidence. Make a melee Strike. If you hit and deal damage, the target is frightened 1, or frightened 2 on a critical hit.',
    implemented: 'full',
    traits: ['Barbarian', 'Emotion', 'Fear', 'Fighter', 'Mental'],
    actionCost: 2,
    mechanics: 'Melee Strike. On hit: target frightened 1 (frightened 2 on crit). Shared with Fighter.',
  },
  {
    id: 'barbarian-no-escape',
    name: 'No Escape',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'You keep pace with a retreating foe. You Stride up to your Speed, following the foe and keeping it within your reach throughout its movement until it stops moving or you\'ve moved your full Speed.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    mechanics: 'Trigger: enemy within reach moves away. Stride up to Speed following the enemy.',
  },
  {
    id: 'barbarian-second-wind',
    name: 'Second Wind',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'You can enter a second rage, but afterward you need to catch your breath. You can Rage a second time during an encounter without waiting 1 round after the previous Rage ends. After this second Rage ends, you are fatigued for 1 round.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Can Rage again immediately after first Rage ends. Fatigued 1 round after second Rage.',
  },
  {
    id: 'barbarian-shake-it-off',
    name: 'Shake It Off',
    source: 'Barbarian',
    category: 'class',
    level: 2,
    description: 'You concentrate on your rage, overcoming fear and fighting back sickness. Reduce your frightened condition value by 1. You can also attempt a Fortitude save against an ongoing sickened condition, using the sickened DC.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    mechanics: 'Reduce frightened by 1. Optionally attempt Fort save vs sickened DC.',
  },
  // â”€â”€ Level 4 (8 feats) â”€â”€
  {
    id: 'barbarian-barreling-charge',
    name: 'Barreling Charge',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'You rush forward, moving enemies aside to reach your foe. You Stride, attempting to move through your enemies\' spaces. Roll an Athletics check and compare the result to the Fortitude DC of each creature whose space you attempt to move through during your Stride, moving through its space on a success but ending your movement before entering its space on a failure. You can then Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Trained in Athletics'],
    mechanics: 'Stride through enemies (Athletics vs Fort DC each), then Strike. Shared with Fighter.',
  },
  {
    id: 'barbarian-oversized-throw',
    name: 'Oversized Throw',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'With a great heave, you seize a piece of your surroundings, such as a boulder, log, table, wagon, or chunk of earth, and hurl it at your foes. Make a ranged Strike against a creature within 30 feet. The improvised weapon deals 2d10 bludgeoning damage plus your Strength modifier.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 2,
    mechanics: 'Req: one or more hands free. Ranged Strike 30 ft, 2d10+STR bludgeoning.',
  },
  {
    id: 'barbarian-raging-athlete',
    name: 'Raging Athlete',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'Physical obstacles can\'t hold back your fury. While you are raging, you gain a climb Speed and swim Speed equal to your land Speed, and the DC of High Jumps and Long Jumps decreases by 10. You increase your distance on a successful Long Jump by 10 feet. Your vertical Leap distance increases to 5 feet, and your horizontal Leap increases to 15 feet (Speed 15+) or 20 feet (Speed 30+).',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    prerequisites: ['Expert in Athletics'],
    mechanics: 'While raging: climb/swim Speed = land Speed. Jump DC -10, Long Jump +10 ft. Leap: 5 ft vertical, 15/20 ft horizontal.',
  },
  {
    id: 'barbarian-scars-of-steel',
    name: 'Scars of Steel',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'When you are struck with the mightiest of blows, you can flex your muscles to turn aside some of the damage. You gain resistance to physical damage equal to your level against the triggering attack.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    prerequisites: ['fury instinct'],
    mechanics: 'Trigger: crit hit with physical damage. Freq: 1/day. Resist physical = level for that attack.',
  },
  {
    id: 'barbarian-spiritual-guides',
    name: 'Spiritual Guides',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'Though no one sees them and only you can hear them, the spirits around you constantly chatter, save when you are raging. You reroll the triggering check and use the better result.',
    implemented: 'full',
    traits: ['Barbarian', 'Fortune'],
    actionCost: 'reaction',
    prerequisites: ['spirit instinct'],
    mechanics: 'Trigger: fail (not crit fail) Perception or skill check. Freq: 1/day. Reroll and use better.',
  },
  {
    id: 'barbarian-supernatural-senses',
    name: 'Supernatural Senses',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'Your scent is preternaturally sharp, and you can always rely on your sense of smell to help guide you when your vision is compromised. When you target a concealed or hidden opponent while you are raging, you reduce the DC of the flat check to 3 for a concealed target or to 9 for a hidden one.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    prerequisites: ['Acute Scent or scent'],
    mechanics: 'While raging: flat check DC 3 for concealed, DC 9 for hidden targets.',
  },
  {
    id: 'barbarian-swipe',
    name: 'Swipe',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'You make a wide, arcing swing. Make a single melee Strike and compare the attack roll result to the ACs of up to two foes, each of whom must be within your melee reach and adjacent to each other. Roll damage only once and apply it to each creature you hit.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter', 'Flourish'],
    actionCost: 2,
    mechanics: 'Single melee Strike vs up to 2 adjacent foes in reach. One roll, damage to each hit. Shared with Fighter.',
  },
  {
    id: 'barbarian-wounded-rage',
    name: 'Wounded Rage',
    source: 'Barbarian',
    category: 'class',
    level: 4,
    description: 'You roar in pain, awakening the rage within you. You Rage.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: you take damage and are capable of entering a rage. You Rage.',
  },
  // â”€â”€ Level 6 (11 feats) â”€â”€
  {
    id: 'barbarian-animal-skin',
    name: 'Animal Skin',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'Your proficiency in unarmored defense increases to expert. When you are raging and unarmored, your skin transforms into a thick hide. You gain a +2 item bonus to AC (+3 if you have the greater juggernaut class feature). The thickness of your hide gives you a Dexterity modifier cap to your AC of +3. This item bonus is cumulative with armor potency runes on explorer\'s clothing, mystic armor, and bands of force.',
    implemented: 'full',
    traits: ['Barbarian', 'Morph', 'Primal'],
    actionCost: 'passive',
    prerequisites: ['animal instinct'],
    mechanics: 'Unarmored defense to expert. While raging + unarmored: +2 item AC (+3 with greater juggernaut), Dex cap +3.',
  },
  {
    id: 'barbarian-brutal-bully',
    name: 'Brutal Bully',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You push your foes around and leave bruises. While raging, when you successfully Disarm, Grapple, Shove, or Trip a foe, you deal your Strength modifier in bludgeoning damage to that foe.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    prerequisites: ['Expert in Athletics'],
    mechanics: 'While raging: successful Disarm/Grapple/Shove/Trip deals STR mod bludgeoning.',
  },
  {
    id: 'barbarian-cleave',
    name: 'Cleave',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You swing clear through one foe and into another. Make a melee Strike against the second foe, at the same multiple attack penalty as the first Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    mechanics: 'Trigger: melee Strike reduces enemy to 0 HP with another enemy adjacent. Strike adjacent foe at same MAP.',
  },
  {
    id: 'barbarian-dragons-rage-breath',
    name: 'Dragon\'s Rage Breath',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You breathe deeply and exhale powerful energy in a 30-foot cone, dealing 1d6 damage per level to each creature in the area with a basic Reflex save against your class DC. The damage type matches your dragon\'s breath type.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 2,
    prerequisites: ['dragon instinct'],
    mechanics: 'Freq: 1/10min. 30-ft cone, 1d6/level, basic Reflex vs class DC. Damage type from dragon instinct.',
  },
  {
    id: 'barbarian-giants-stature',
    name: 'Giant\'s Stature',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You grow to incredible size. You become Large, gaining a 10-foot reach and becoming clumsy 1. Your equipment grows with you.',
    implemented: 'full',
    traits: ['Barbarian', 'Polymorph', 'Primal', 'Rage'],
    actionCost: 1,
    prerequisites: ['Giant instinct'],
    mechanics: 'Req: Medium or smaller. Become Large, reach 10 ft, clumsy 1. Equipment grows.',
  },
  {
    id: 'barbarian-inner-strength',
    name: 'Inner Strength',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'Your strength is part of your rage. You gain temporary Hit Points equal to your level. They last until the end of your rage.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    prerequisites: ['spirit instinct'],
    mechanics: 'Gain temp HP = level. Lasts until rage ends.',
  },
  {
    id: 'barbarian-mage-hunter',
    name: 'Mage Hunter',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You use your hatred of magic to lash out at a known spellcaster. Stride up to your Speed toward the target and make a melee Strike against them.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 2,
    prerequisites: ['superstition instinct'],
    mechanics: 'Req: you\'ve seen target Cast a Spell. Stride toward target + melee Strike.',
  },
  {
    id: 'barbarian-nocturnal-senses',
    name: 'Nocturnal Senses',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'Your senses gain even greater clarity. While raging, if you have low-light vision you gain darkvision, and if you have scent the range of your imprecise scent doubles.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    prerequisites: ['low-light vision or scent'],
    mechanics: 'While raging: low-light vision becomes darkvision, imprecise scent range doubles.',
  },
  {
    id: 'barbarian-reactive-strike',
    name: 'Reactive Strike',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: creature within reach uses manipulate/move action, ranged attack, or leaves square. Melee Strike; disrupt manipulate on crit. Shared with Champion, Commander, Exemplar, Guardian, Magus, Swashbuckler.',
  },
  {
    id: 'barbarian-scouring-rage',
    name: 'Scouring Rage',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You emit a powerful surge of instinctual energy when you unleash your anger. Each creature in a 5-foot emanation takes damage equal to your Rage bonus damage, of the type determined by your instinct.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'free',
    prerequisites: ['An instinct that allows you to change your additional damage from Rage to a different damage type'],
    mechanics: 'Trigger: You Rage. 5-ft emanation, damage = Rage bonus damage, type from instinct.',
  },
  {
    id: 'barbarian-spirits-interference',
    name: 'Spirits\' Interference',
    source: 'Barbarian',
    category: 'class',
    level: 6,
    description: 'You call forth protective spirits to ward off ranged attacks. Until the start of your next turn, anyone making a ranged attack against you must succeed at a DC 5 flat check or the attack misses with no effect.',
    implemented: 'full',
    traits: ['Barbarian', 'Divine', 'Rage'],
    actionCost: 1,
    prerequisites: ['spirit instinct'],
    mechanics: 'Ranged attacks vs you require DC 5 flat check until start of next turn.',
  },
  // â”€â”€ Level 8 (11 feats) â”€â”€
  {
    id: 'barbarian-animalistic-brutality',
    name: 'Animalistic Brutality',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You deepen the connection into your animal instincts. Your unarmed attack from bestial rage gains one of the following traits until you stop raging: backswing, forceful, parry, razing, or sweep. You can\'t use this ability again until the next time you Rage. You can choose a different trait each time you use Animalistic Brutality.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Morph', 'Primal', 'Rage'],
    actionCost: 1,
    prerequisites: ['animal instinct'],
    mechanics: '1 action. Add weapon trait (backswing/forceful/parry/razing/sweep) to bestial rage unarmed attack until rage ends. Once per rage.',
    subChoices: { label: 'Choose weapon trait', options: [
      { id: 'backswing', name: 'Backswing', description: '+1 circumstance to attack after missing' },
      { id: 'forceful', name: 'Forceful', description: 'Add damage dice on successive attacks' },
      { id: 'parry', name: 'Parry', description: '+1 AC while wielding this weapon' },
      { id: 'razing', name: 'Razing', description: 'Ignore some Hardness on objects/constructs' },
      { id: 'sweep', name: 'Sweep', description: '+1 circumstance to attack after hitting a different target' },
    ] },
  },
  {
    id: 'barbarian-disarming-assault',
    name: 'Disarming Assault',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You attack to knock a weapon from a foe\'s hands. Make a melee Strike. If it hits and deals damage, you can attempt an Athletics check to Disarm the target as a free action.',
    implemented: 'full',
    traits: ['Barbarian', 'Flourish', 'Rage'],
    actionCost: 1,
    prerequisites: ['Trained in Athletics'],
    mechanics: 'Melee Strike; on hit + damage: free Disarm attempt via Athletics.',
  },
  {
    id: 'barbarian-follow-up-assault',
    name: 'Follow-up Assault',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You press the attack when a target evades your blow. Make another melee Strike against the same target, using the same multiple attack penalty as the missed Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 1,
    mechanics: 'Req: previous action was melee Strike that missed. Strike same target at same MAP.',
  },
  {
    id: 'barbarian-friendly-toss',
    name: 'Friendly Toss',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You toss a willing ally to a better position. You throw a willing adjacent ally up to 30 feet to an unoccupied space. They must land on a surface that can support them.',
    implemented: 'full',
    traits: ['Barbarian', 'Manipulate', 'Rage'],
    actionCost: 2,
    mechanics: 'Req: adjacent willing ally, free hand. Throw ally up to 30 ft.',
  },
  {
    id: 'barbarian-furious-bully',
    name: 'Furious Bully',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You bully foes across the battlefield. While raging, you gain a +2 circumstance bonus to Athletics checks for attack actions.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    prerequisites: ['Master in Athletics'],
    mechanics: 'While raging: +2 circumstance bonus to Athletics for attack actions (Grapple, Shove, Trip, Disarm).',
  },
  {
    id: 'barbarian-instinctive-strike',
    name: 'Instinctive Strike',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You use your preternatural senses to target hidden enemies. While raging, you don\'t need to succeed at a flat check to target a concealed creature you can detect with your scent.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    prerequisites: ['Acute Scent or scent'],
    mechanics: 'While raging: no flat check vs concealed creatures detected by scent.',
  },
  {
    id: 'barbarian-invulnerable-rager',
    name: 'Invulnerable Rager',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You are tougher than most while raging. While raging, you gain resistance 2 to all damage. At 12th level, this increases to resistance 4. At 16th level, resistance 6. At 20th level, resistance 8.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'While raging: resistance to all damage (2 at L8, 4 at L12, 6 at L16, 8 at L20).',
  },
  {
    id: 'barbarian-renewed-vigor',
    name: 'Renewed Vigor',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You pause to recover your momentum. You gain temporary Hit Points equal to half your level plus your Constitution modifier. These last until the end of your rage.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    mechanics: 'Gain temp HP = floor(level/2) + CON mod. Lasts until rage ends.',
  },
  {
    id: 'barbarian-share-rage',
    name: 'Share Rage',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You stoke an ally\'s fury. One willing ally within 30 feet gains your Rage additional damage bonus on melee Strikes until the start of your next turn.',
    implemented: 'full',
    traits: ['Auditory', 'Barbarian', 'Rage', 'Visual'],
    actionCost: 1,
    mechanics: 'Req: haven\'t used since last Raged. One ally in 30 ft gains Rage bonus melee damage until start of your next turn.',
  },
  {
    id: 'barbarian-sudden-leap',
    name: 'Sudden Leap',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You make an impressive leap and swing while you soar. You can Long Jump or High Jump and make a melee Strike at any point during your jump.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter'],
    actionCost: 2,
    mechanics: 'Long Jump or High Jump + melee Strike at any point during jump. Shared with Fighter.',
  },
  {
    id: 'barbarian-thrash',
    name: 'Thrash',
    source: 'Barbarian',
    category: 'class',
    level: 8,
    description: 'You thrash the grabbed enemy around. You deal your weapon damage plus your weapon specialization damage to the grabbed creature, who must attempt a basic Fortitude save against your class DC.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 1,
    mechanics: 'Req: creature grabbed or restrained. Weapon damage + specialization, basic Fort save vs class DC.',
  },
  // â”€â”€ Level 10 (10 feats) â”€â”€
  {
    id: 'barbarian-come-and-get-me',
    name: 'Come and Get Me',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You open yourself to attacks so you can retaliate in turn. You become off-guard. Whenever a creature hits you with a melee attack, that creature becomes off-guard to your melee attacks, and you gain temporary Hit Points equal to your Constitution modifier (doubled on a critical hit). These effects last until your rage ends.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    mechanics: 'Become off-guard. When hit by melee: attacker off-guard to you, gain temp HP = CON mod (Ã—2 on crit). Lasts until rage ends.',
  },
  {
    id: 'barbarian-furious-sprint',
    name: 'Furious Sprint',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You rush ahead in a straight line. Stride up to five times your Speed in a straight line. If you spend 3 actions, Stride up to eight times your Speed instead.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 2,
    mechanics: '2 actions: Stride up to 5Ã— Speed in straight line. 3 actions: up to 8Ã— Speed.',
  },
  {
    id: 'barbarian-great-cleave',
    name: 'Great Cleave',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'Your fury carries your weapon through multiple foes. Each time your Cleave Strike reduces a creature to 0 HP, you can continue to make melee Strikes against adjacent creatures until you miss or run out of adjacent targets.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    prerequisites: ['Cleave'],
    mechanics: 'Upgrades Cleave to chain through multiple adjacent targets on consecutive kills.',
  },
  {
    id: 'barbarian-impressive-landing',
    name: 'Impressive Landing',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You land on your feet and shake the ground. Treat the fall as 10 feet shorter. You create a 5-foot emanation of difficult terrain. Each creature in the area takes 5 bludgeoning damage and is off-guard until the start of your next turn.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: fall 10+ ft, land on solid surface. Reduce fall by 10 ft, 5-ft emanation: difficult terrain, 5 bludgeoning, off-guard.',
  },
  {
    id: 'barbarian-knockback',
    name: 'Knockback',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'The weight of your attack pushes the enemy back. You push the target 5 feet, as though you had successfully Shoved them. You can follow the target as normal for a successful Shove.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 1,
    mechanics: 'Req: last action was successful melee Strike. Push target 5 ft. Can follow.',
  },
  {
    id: 'barbarian-overpowering-charge',
    name: 'Overpowering Charge',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You trample foes as you charge past. When you use Barreling Charge, each creature whose space you move through takes damage equal to your Strength modifier.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter'],
    actionCost: 'passive',
    prerequisites: ['Barreling Charge'],
    mechanics: 'Barreling Charge upgrade: creatures passed through take STR mod damage. Shared with Fighter.',
  },
  {
    id: 'barbarian-resounding-blow',
    name: 'Resounding Blow',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You slam with thunderous force. Make a melee Strike with a bludgeoning weapon. On a hit, the target is deafened until the start of your next turn (1 minute on a critical hit).',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 2,
    mechanics: 'Req: melee weapon with bludgeoning. Strike; on hit: deafened 1 round (1 min on crit).',
  },
  {
    id: 'barbarian-silencing-strike',
    name: 'Silencing Strike',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You make a melee Strike that silences your target. If it hits, the target must attempt a Fortitude save against your class DC. Failure: stunned 1, and must succeed at a DC 11 flat check to use linguistic or spell actions. Critical Failure: stunned 3.',
    implemented: 'full',
    traits: ['Barbarian', 'Incapacitation', 'Rage'],
    actionCost: 1,
    mechanics: 'Melee Strike + Fort save vs class DC. F: stunned 1 + DC 11 flat check for linguistic/spells. CF: stunned 3.',
  },
  {
    id: 'barbarian-tangle-of-battle',
    name: 'Tangle of Battle',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You seize the opportunity of a powerful blow to grab your foe. You attempt to Grapple the triggering enemy.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    mechanics: 'Trigger: you critically hit an adjacent enemy with a melee Strike. Free Grapple attempt.',
  },
  {
    id: 'barbarian-terrifying-howl',
    name: 'Terrifying Howl',
    source: 'Barbarian',
    category: 'class',
    level: 10,
    description: 'You unleash a terrifying scream. Attempt Intimidation checks to Demoralize each enemy within 30 feet. You don\'t take the -4 penalty for not sharing a language. Each target is then temporarily immune for 1 minute.',
    implemented: 'full',
    traits: ['Auditory', 'Barbarian', 'Rage'],
    actionCost: 1,
    mechanics: 'Demoralize all enemies within 30 ft (no language penalty). Each target immune 1 min.',
  },
  // â”€â”€ Level 12 (8 feats) â”€â”€
  {
    id: 'barbarian-dragons-rage-wings',
    name: 'Dragon\'s Rage Wings',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You sprout dragon wings while raging. You gain a fly Speed equal to your land Speed while raging. When your rage ends, if you\'re still flying, you safely descend.',
    implemented: 'full',
    traits: ['Barbarian', 'Morph', 'Rage'],
    actionCost: 1,
    prerequisites: ['dragon instinct'],
    mechanics: 'Fly Speed = land Speed while raging. Safe descent when rage ends. Leads to Dragon Transformation.',
  },
  {
    id: 'barbarian-embrace-the-pain',
    name: 'Embrace the Pain',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You use the pain from an enemy\'s attack to fuel your retaliation. You attempt to Grapple or Disarm the triggering creature.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    mechanics: 'Trigger: creature within reach damages you with melee attack. Free Grapple or Disarm.',
  },
  {
    id: 'barbarian-furious-grab',
    name: 'Furious Grab',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You grab your target by the scruff. The enemy you hit becomes grabbed, as if you had succeeded at a Grapple against them.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 1,
    mechanics: 'Req: last action was successful melee Strike, free hand or grapple weapon. Target becomes grabbed.',
  },
  {
    id: 'barbarian-predators-pounce',
    name: 'Predator\'s Pounce',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You close the distance to your prey in a blur of motion. Stride up to your Speed and make a melee Strike at the end of your movement.',
    implemented: 'full',
    traits: ['Barbarian', 'Flourish', 'Rage'],
    actionCost: 1,
    prerequisites: ['animal instinct'],
    mechanics: 'Req: unarmored or light armor. Stride + Strike at end.',
  },
  {
    id: 'barbarian-spirits-wrath',
    name: 'Spirit\'s Wrath',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You call upon a spirit to attack an enemy. Make a ranged attack roll against a target within 120 feet. On a hit, the target takes 4d8 damage plus your Constitution modifier. The damage type is spirit. On a critical hit, double the damage and the target is frightened 1.',
    implemented: 'full',
    traits: ['Attack', 'Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    prerequisites: ['spirit instinct'],
    mechanics: 'Ranged attack 120 ft, 4d8+CON spirit damage. Crit: double + frightened 1.',
  },
  {
    id: 'barbarian-sunder-spell',
    name: 'Sunder Spell',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You draw upon your superstitious fury to destroy a spell. Make a melee Strike against a creature, object, or a spell manifestation. If the target has no AC listed, its AC is 10 (or as determined by GM). If your Strike hits, you can attempt to counteract a single spell or magical effect on the target. Your counteract rank equals half your level rounded up, and you use your attack roll for the counteract check. Whether or not you succeed, the target becomes temporarily immune to your Sunder Spell for 24 hours.',
    implemented: 'full',
    traits: ['Attack', 'Barbarian', 'Concentrate', 'Rage'],
    actionCost: 2,
    prerequisites: ['superstition instinct'],
    mechanics: 'Melee Strike + counteract. Counteract rank = ceil(level/2). Attack roll = counteract check. Target immune 24 hrs. Leads to Sunder Enchantment.',
  },
  {
    id: 'barbarian-titans-stature',
    name: 'Titan\'s Stature',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'When using Giant\'s Stature, you can choose to become Huge instead of Large. You gain a 15-foot reach if you were Medium or smaller before growing.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    prerequisites: ['Giant\'s Stature'],
    mechanics: 'Upgrades Giant\'s Stature: can become Huge. 15-ft reach if originally Medium or smaller.',
  },
  {
    id: 'barbarian-unbalancing-sweep',
    name: 'Unbalancing Sweep',
    source: 'Barbarian',
    category: 'class',
    level: 12,
    description: 'You sweep your weapon in a wide arc to throw multiple enemies off balance. Choose up to 3 enemies within your melee reach. Choose either Shove or Trip. Attempt separate Athletics checks against each target\'s Fortitude DC.',
    implemented: 'full',
    traits: ['Barbarian', 'Flourish'],
    actionCost: 3,
    mechanics: 'Choose Shove or Trip. Up to 3 enemies in reach. Separate Athletics vs each Fort DC.',
    subChoices: { label: 'Choose maneuver', options: [
      { id: 'shove', name: 'Shove', description: 'Push enemies away from you' },
      { id: 'trip', name: 'Trip', description: 'Knock enemies prone' },
    ] },
  },
  // â”€â”€ Level 14 (6 feats) â”€â”€
  {
    id: 'barbarian-awesome-blow',
    name: 'Awesome Blow',
    source: 'Barbarian',
    category: 'class',
    level: 14,
    description: 'When you use Knockback, you can attempt an Athletics check against the target\'s Fortitude DC. Critical Success: the target is pushed and knocked prone. Success: the target is pushed or knocked prone (your choice). Failure: the normal Knockback push applies.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 'passive',
    prerequisites: ['Knockback'],
    mechanics: 'Upgrades Knockback: Athletics vs Fort DC. CritS: push+prone. S: push or prone. F: normal push.',
  },
  {
    id: 'barbarian-giants-lunge',
    name: 'Giant\'s Lunge',
    source: 'Barbarian',
    category: 'class',
    level: 14,
    description: 'All your melee weapons and unarmed attacks gain reach 10 feet until your rage ends.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Rage'],
    actionCost: 1,
    prerequisites: ['Giant instinct'],
    mechanics: 'All melee weapons + unarmed gain reach 10 ft until rage ends.',
  },
  {
    id: 'barbarian-impaling-thrust',
    name: 'Impaling Thrust',
    source: 'Barbarian',
    category: 'class',
    level: 14,
    description: 'You impale your enemy with a piercing weapon. Make a melee Strike with a piercing weapon. If it hits, the target is grabbed by your weapon. When freed, the target takes persistent bleed damage equal to your weapon\'s number of damage dice.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 2,
    mechanics: 'Req: melee piercing weapon. Strike; on hit: target grabbed. When freed: persistent bleed = weapon dice count.',
  },
  {
    id: 'barbarian-sunder-enchantment',
    name: 'Sunder Enchantment',
    source: 'Barbarian',
    category: 'class',
    level: 14,
    description: 'You can focus your superstition to break the magic of an item, in addition to destroying freestanding spells and those active on creatures. When you Sunder a Spell, you can instead attempt to counteract either an unattended magic item or one of your target\'s magic items. If your counteract attempt succeeds, the item becomes a mundane item of its type for 10 minutes. If you target an artifact, an intelligent item, or a similarly particularly powerful item, your counteract attempt automatically fails.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    prerequisites: ['Sunder Spell'],
    mechanics: 'Upgrades Sunder Spell: can counteract magic items (mundane 10 min). Artifacts/intelligent items auto-fail.',
  },
  {
    id: 'barbarian-vengeful-strike',
    name: 'Vengeful Strike',
    source: 'Barbarian',
    category: 'class',
    level: 14,
    description: 'You retaliate when a foe hits you while your guard is lowered. Make a melee Strike against the triggering creature. If the triggering attack was a critical success, your Vengeful Strike is a free action instead of a reaction.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    prerequisites: ['Come and Get Me'],
    mechanics: 'Trigger: creature in reach succeeds at attack vs you. Req: Come and Get Me active. Melee Strike. Free action if trigger was crit success.',
  },
  {
    id: 'barbarian-whirlwind-strike',
    name: 'Whirlwind Strike',
    source: 'Barbarian',
    category: 'class',
    level: 14,
    description: 'You lash out in a blur of motion, attacking all nearby adversaries. Make a melee Strike against each enemy within your melee reach. Each attack counts toward your multiple attack penalty, but your multiple attack penalty doesn\'t increase until you\'ve made all your attacks.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter', 'Flourish'],
    actionCost: 3,
    mechanics: 'Melee Strike vs each enemy in reach. MAP applies to each but doesn\'t increment until all done. Shared with Fighter.',
  },
  // â”€â”€ Level 16 (6 feats) â”€â”€
  {
    id: 'barbarian-collateral-thrash',
    name: 'Collateral Thrash',
    source: 'Barbarian',
    category: 'class',
    level: 16,
    description: 'You smack the foe you\'re thrashing into someone else. When you successfully Thrash a grabbed creature, you also deal the Thrash damage to an adjacent creature of your choice, who must attempt a basic Reflex save against your class DC.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    prerequisites: ['Thrash'],
    mechanics: 'Upgrades Thrash: adjacent creature also takes Thrash damage, basic Reflex vs class DC. Leads to Whirlwind Toss.',
  },
  {
    id: 'barbarian-desperate-wrath',
    name: 'Desperate Wrath',
    source: 'Barbarian',
    category: 'class',
    level: 16,
    description: 'Your blood boils when you take a beating, and you throw caution to the wind to finish the fight. You gain a +2 circumstance bonus to attack rolls, but take a -1 penalty to AC and saving throws. These effects last until your rage ends or your HP go above half your maximum.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'free',
    mechanics: 'Trigger: your turn begins and HP â‰¤ half max. +2 circumstance to attacks, -1 AC, -1 saves. Until rage ends or HP > half. (Remastered version of Reckless Abandon)',
  },
  {
    id: 'barbarian-dragon-transformation',
    name: 'Dragon Transformation',
    source: 'Barbarian',
    category: 'class',
    level: 16,
    description: 'You transform into a ferocious Large dragon, gaining the effects of 6th-rank dragon form except that you use your own AC and attack modifier, you apply your extra damage from Rage, and the Dragon Breath action uses your class DC.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Polymorph', 'Primal', 'Rage'],
    actionCost: 1,
    prerequisites: ['Dragon\'s Rage Wings'],
    mechanics: 'Freq: 1/10min. Transform into Large dragon (6th-rank dragon form). Own AC/attack, Rage damage applies, class DC for breath.',
  },
  {
    id: 'barbarian-furious-vengeance',
    name: 'Furious Vengeance',
    source: 'Barbarian',
    category: 'class',
    level: 16,
    description: 'Your enemy\'s blow fuels your rage and provokes your immediate retaliation. Make a melee Strike against the triggering creature.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'reaction',
    prerequisites: ['fury instinct'],
    mechanics: 'Trigger: enemy within melee reach critically hits you with a melee Strike. Make melee Strike vs that enemy.',
  },
  {
    id: 'barbarian-penetrating-projectile',
    name: 'Penetrating Projectile',
    source: 'Barbarian',
    category: 'class',
    level: 16,
    description: 'Your projectiles are unhindered by flesh and bone. Make a ranged Strike. The projectile passes through the first target and continues in a 60-foot line, potentially hitting additional creatures behind the first target.',
    implemented: 'full',
    traits: ['Barbarian', 'Flourish', 'Rage'],
    actionCost: 2,
    mechanics: 'Req: ranged or thrown weapon dealing piercing damage. Strike passes through target, continues in line.',
  },
  {
    id: 'barbarian-shattering-blows',
    name: 'Shattering Blows',
    source: 'Barbarian',
    category: 'class',
    level: 16,
    description: 'Your forceful blows shatter objects with ease. While raging, your melee Strikes ignore the first 5 points of an object\'s Hardness. If you also have the Devastator class feature, you ignore the first 10 points instead.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 'passive',
    mechanics: 'While raging: ignore 5 Hardness (10 with Devastator).',
  },
  // â”€â”€ Level 18 (4 feats) â”€â”€
  {
    id: 'barbarian-brutal-critical',
    name: 'Brutal Critical',
    source: 'Barbarian',
    category: 'class',
    level: 18,
    description: 'Your critical hits are particularly devastating. On a critical hit with a melee Strike, you add one additional weapon damage die. The target also takes persistent bleed damage equal to two of your weapon damage dice.',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'On melee crit: +1 weapon die, target takes persistent bleed = 2 weapon dice.',
  },
  {
    id: 'barbarian-perfect-clarity',
    name: 'Perfect Clarity',
    source: 'Barbarian',
    category: 'class',
    level: 18,
    description: 'You burn out all your rage to ensure that your attack lands and your mind remains free. Reroll the triggering check with a +2 circumstance bonus and use the better result. Your rage then immediately ends.',
    implemented: 'full',
    traits: ['Barbarian', 'Concentrate', 'Fortune', 'Rage'],
    actionCost: 'reaction',
    mechanics: 'Trigger: fail or crit fail attack roll or Will save. Reroll with +2 circumstance, use better result. Rage ends.',
  },
  {
    id: 'barbarian-vicious-evisceration',
    name: 'Vicious Evisceration',
    source: 'Barbarian',
    category: 'class',
    level: 18,
    description: 'You make a vicious attack that maims your enemy. Make a melee Strike. If it hits and deals damage, the target must attempt a Fortitude save against your class DC. On a failure, the target is drained 1. On a critical failure, the target is drained 2. If your Strike was a critical hit, the target is drained 3 instead.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 2,
    mechanics: 'Melee Strike; on hit: Fort save vs class DC. F: drained 1, CF: drained 2, crit hit: drained 3.',
  },
  {
    id: 'barbarian-whirlwind-toss',
    name: 'Whirlwind Toss',
    source: 'Barbarian',
    category: 'class',
    level: 18,
    description: 'You whirl a foe to smash into all nearby creatures before throwing them far away. You Thrash a grabbed creature, applying the Thrash damage to all creatures adjacent to you. You then throw the grabbed creature up to 30 feet, and it takes additional damage equal to your Strength modifier upon landing.',
    implemented: 'full',
    traits: ['Barbarian', 'Rage'],
    actionCost: 2,
    prerequisites: ['Collateral Thrash'],
    mechanics: 'Thrash damage applies to ALL adjacent creatures. Then throw grabbed creature 30 ft with STR mod damage on landing.',
  },
  // â”€â”€ Level 20 (3 feats) â”€â”€
  {
    id: 'barbarian-contagious-rage',
    name: 'Contagious Rage',
    source: 'Barbarian',
    category: 'class',
    level: 20,
    description: 'You can share your rage with all allies nearby. When you use Share Rage, you can share it with all willing allies within 30 feet instead of just one. They also gain your instinct\'s specialization ability for the duration.',
    implemented: 'full',
    traits: ['Auditory', 'Barbarian', 'Rage', 'Visual'],
    actionCost: 'passive',
    prerequisites: ['Share Rage'],
    mechanics: 'Upgrades Share Rage: affects all willing allies in 30 ft. They gain instinct specialization ability.',
  },
  {
    id: 'barbarian-quaking-stomp',
    name: 'Quaking Stomp',
    source: 'Barbarian',
    category: 'class',
    level: 20,
    description: 'You stomp the ground with such force that it creates a minor earthquake, with the effects of the earthquake spell.',
    implemented: 'full',
    traits: ['Barbarian', 'Manipulate', 'Rage'],
    actionCost: 1,
    mechanics: 'Freq: 1/10min. Creates earthquake spell effect.',
  },
  {
    id: 'barbarian-unstoppable-juggernaut',
    name: 'Unstoppable Juggernaut',
    source: 'Barbarian',
    category: 'class',
    level: 20,
    description: 'You gain resistance equal to 3 + your Constitution modifier to all damage while raging, in addition to your raging resistance. When you would be reduced to 0 Hit Points while raging, you can use a reaction to remain at 1 HP instead, but you become wounded 2 (or increase your wounded value by 2).',
    implemented: 'full',
    traits: ['Barbarian'],
    actionCost: 'passive',
    mechanics: 'Resistance (3+CON mod) to all damage while raging. Reaction at 0 HP: stay at 1 HP, wounded 2.',
  },
];
