/**
 * Bard Class Features & Feats — PF2e Remastered (Player Core)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=32
 *
 * Key Attribute: CHA | HP: 8 + CON
 * Perception: Expert → Master (L11, Perception Mastery)
 * Fort: Trained → Expert (L9, Fortitude Expertise)
 * Reflex: Trained → Expert (L3, Reflex Expertise)
 * Will: Expert → Master (L9, Performer's Heart, success→crit) → Legendary (L17, Greater Performer's Heart, crit-fail→fail, half on fail)
 * Weapons: Trained simple+martial+unarmed → Expert (L11, Bard Weapon Expertise, crit spec while composition active)
 * Armor: Trained light+unarmored → Expert (L13, Light Armor Expertise)
 * Spellcasting: Occult spontaneous — Trained → Expert (L7) → Master (L15) → Legendary (L19)
 * Class DC: Trained
 *
 * Muses (Player Core):
 *   Enigma   — Bardic Lore feat, sure strike spell
 *   Maestro  — Lingering Composition feat, soothe spell
 *   Polymath — Versatile Performance feat, phantasmal minion spell
 *   Warrior  — Martial Performance feat, fear spell
 *
 * Class features: 18 (L1–L19)
 * Class feats: 69 PC common feats (AoN IDs 4573–4641)
 */

import type { FeatEntry } from './featTypes';
import { WEAPON_SPECIALIZATION, createClassFeature } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// BARD CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const BARD_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'bard-occult-spellcasting',
    name: 'Bard Spellcasting',
    source: 'Bard',
    category: 'class_feature',
    level: 1,
    description: 'You draw upon magic from esoteric knowledge. You can cast occult spells using the Cast a Spell activity, and you can supply material, somatic, and verbal components when casting spells. Because you\'re a bard, you can usually play an instrument for spells requiring somatic or material components, as long as it takes at least one of your hands to do so. Each day, you can cast a number of occult spells determined by your level. You must know spells to cast them, and you learn them via your spell repertoire. The number of spells you can cast each day is called your spell slots. Your proficiency rank for occult spell attack modifiers and spell DCs is trained.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-spell-repertoire',
    name: 'Spell Repertoire',
    source: 'Bard',
    category: 'class_feature',
    level: 1,
    description: 'The collection of spells you can cast is called your spell repertoire. At 1st level, you learn two 1st-rank occult spells and five occult cantrips of your choice. You choose these from the common spells on the occult spell list, or from other occult spells you gain access to. You add spells to your repertoire as you increase in level. Each time you gain a spell slot, you add a spell to your repertoire of the same rank.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-composition-spells',
    name: 'Composition Spells',
    source: 'Bard',
    category: 'class_feature',
    level: 1,
    description: 'You can infuse your performances with magic to create unique effects called compositions. Compositions are a special type of spell that often require you to use the Performance skill when casting them. Composition spells are a type of focus spell. It costs 1 Focus Point to cast a focus spell, and you start with a focus pool of 1 Focus Point. You refill your focus pool during your daily preparations, and you can regain 1 Focus Point by spending 10 minutes using the Refocus activity to perform, write a new score, or otherwise engage your muse. You learn the counter performance composition spell, which lets you use your musical talent to disrupt effects that rely on sound or sight.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-composition-cantrips',
    name: 'Composition Cantrips',
    source: 'Bard',
    category: 'class_feature',
    level: 1,
    description: 'Composition cantrips are special composition spells that don\'t cost Focus Points, so you can use them as often as you like. Composition cantrips are in addition to the cantrips you choose from the occult list. Generally, only one composition cantrip can be active at a time. You learn the courageous anthem composition cantrip, which boosts your allies\' attacks, damage, and saves against fear.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-muse',
    name: 'Muse',
    source: 'Bard',
    category: 'class_feature',
    level: 1,
    description: 'As a bard, you have a muse that inspires your art and grants you additional abilities. Select one muse at 1st level. Your muse leads you to certain feats and spells. Enigma: Bardic Lore feat, sure strike spell. Maestro: Lingering Composition feat, soothe spell. Polymath: Versatile Performance feat, phantasmal minion spell. Warrior: Martial Performance feat, fear spell.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    subChoices: { label: 'Choose a muse', options: [
      { id: 'enigma', name: 'Enigma', description: 'Bardic Lore feat + sure strike spell' },
      { id: 'maestro', name: 'Maestro', description: 'Lingering Composition feat + soothe spell' },
      { id: 'polymath', name: 'Polymath', description: 'Versatile Performance feat + phantasmal minion spell' },
      { id: 'warrior', name: 'Warrior', description: 'Martial Performance feat + fear spell' },
    ] },
  },
  // ── Level 3 ──
  {
    id: 'bard-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Bard',
    category: 'class_feature',
    level: 3,
    description: 'You\'ve developed a knack for dodging danger. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-signature-spells',
    name: 'Signature Spells',
    source: 'Bard',
    category: 'class_feature',
    level: 3,
    description: 'Experience enables you to cast some spells more flexibly. For each spell rank you have access to, choose one spell of that rank to be a signature spell. You don\'t need to learn heightened versions of signature spells separately; instead, you can heighten these spells freely.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  // ── Level 7 ──
  {
    id: 'bard-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Bard',
    category: 'class_feature',
    level: 7,
    description: 'Your magical techniques grow stronger. Your proficiency ranks for occult spell attack modifiers and spell DCs increase to expert.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  // ── Level 9 ──
  {
    id: 'bard-fortitude-expertise',
    name: 'Fortitude Expertise',
    source: 'Bard',
    category: 'class_feature',
    level: 9,
    description: 'Your physique has grown hardy from your adventures. Your proficiency rank for Fortitude saves increases to expert.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-performers-heart',
    name: 'Performer\'s Heart',
    source: 'Bard',
    category: 'class_feature',
    level: 9,
    description: 'The greatest performances require an understanding of your own mind and flawless concentration. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    mechanics: 'Will saves: expert → master. Success on Will saves → critical success.',
  },
  // ── Level 11 ──
  {
    id: 'bard-weapon-expertise',
    name: 'Bard Weapon Expertise',
    source: 'Bard',
    category: 'class_feature',
    level: 11,
    description: 'You have become thoroughly adept with your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert. When you critically succeed at an attack roll while one of your composition spells is active, you apply the critical specialization effect for that weapon or unarmed attack.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    mechanics: 'Weapons: trained → expert. Critical specialization effects apply while a composition is active.',
  },
  {
    id: 'bard-perception-mastery',
    name: 'Perception Mastery',
    source: 'Bard',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve developed keen awareness and attention to detail. Your proficiency rank for Perception increases to master.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  // ── Level 13 ──
  {
    id: 'bard-light-armor-expertise',
    name: 'Light Armor Expertise',
    source: 'Bard',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned how to dodge while wearing light or no armor. Your proficiency ranks for light armor and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Bard', 13),
  // ── Level 15 ──
  {
    id: 'bard-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Bard',
    category: 'class_feature',
    level: 15,
    description: 'You pluck the threads of magic like the strings of a harp. Your proficiency ranks for occult spell attack modifiers and spell DCs increase to master.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  // ── Level 17 ──
  {
    id: 'bard-greater-performers-heart',
    name: 'Greater Performer\'s Heart',
    source: 'Bard',
    category: 'class_feature',
    level: 17,
    description: 'Your proficiency rank for Will saves increases to legendary. When you roll a critical failure on a Will save, you get a failure instead. When you fail a Will save against an effect that deals damage, you take half damage.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    mechanics: 'Will saves: master → legendary. Crit failure → failure. Half damage on failed Will saves.',
  },
  // ── Level 19 ──
  {
    id: 'bard-legendary-spellcaster',
    name: 'Legendary Spellcaster',
    source: 'Bard',
    category: 'class_feature',
    level: 19,
    description: 'Your command of occult magic is the stuff of legends. Your proficiency ranks for occult spell attack modifiers and spell DCs increase to legendary.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-magnum-opus',
    name: 'Magnum Opus',
    source: 'Bard',
    category: 'class_feature',
    level: 19,
    description: 'You have tuned your spellcasting to the highest caliber. Add two common 10th-rank occult spells to your repertoire. You gain a single 10th-rank spell slot you can use to cast one of those two spells using bard spellcasting. Unlike other spell slots, you don\'t gain more 10th-rank spells as you level up, though you can take the Perfect Encore feat to gain another.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
];

// ──────────────────────────────────────────────────────────
// BARD CLASS FEATS (Selectable at Class Feat Levels)
// 69 feats, Player Core (AoN IDs 4573–4641)
// ──────────────────────────────────────────────────────────

export const BARD_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 Feats (7) ──
  {
    id: 'bard-bardic-lore',
    name: 'Bardic Lore',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'Your studies make you informed on every subject. You are trained in Bardic Lore, a special Lore skill that can be used only to Recall Knowledge, but on any topic. If you have legendary proficiency in Occultism, you gain expert proficiency in Bardic Lore, but you can\'t increase your proficiency rank in Bardic Lore by any other means.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse'],
  },
  {
    id: 'bard-hymn-of-healing',
    name: 'Hymn of Healing',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'You learn the hymn of healing composition spell, which imbues your music with rich melodies that help your allies recover from harm.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-lingering-composition',
    name: 'Lingering Composition',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'By adding a flourish, you make your compositions last longer. You learn the lingering composition focus spell.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Maestro muse'],
  },
  {
    id: 'bard-martial-performance',
    name: 'Martial Performance',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'Your muse has taught you how to handle a wider variety of weapons than most bards, empowering you to effortlessly blend your performance into combat tools. When you have a courageous anthem composition cantrip active, and you damage an enemy with a Strike, the spell\'s duration is extended by 1 round. You can extend an individual casting only once in this way. If you gain the rallying anthem or song of strength composition cantrips, you can apply this benefit to those cantrips as well.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Warrior muse'],
  },
  {
    id: 'bard-reach-spell',
    name: 'Reach Spell',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'You can extend the range of your spells. If the next action you use is to Cast a Spell that has a range, increase that spell\'s range by 30 feet. As is standard for increasing spell ranges, if the spell normally has a range of touch, you extend its range to 30 feet.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Concentrate', 'Druid', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  {
    id: 'bard-versatile-performance',
    name: 'Versatile Performance',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'You can rely on the grandeur of your performances rather than ordinary social skills. You can use Performance instead of Diplomacy to Make an Impression and instead of Intimidation to Demoralize. You can also use an acting Performance instead of Deception to Impersonate. In addition, you can use your proficiency rank in Performance to meet the prerequisites of skill feats that require a particular proficiency rank in Deception, Diplomacy, or Intimidation.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Polymath muse'],
  },
  {
    id: 'bard-well-versed',
    name: 'Well-Versed',
    source: 'Bard',
    category: 'class',
    level: 1,
    description: 'You\'re resilient to performative influences that aren\'t your own. You gain a +1 circumstance bonus to saving throws against effects with the auditory, illusion, linguistic, sonic, or visual traits.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  // ── Level 2 Feats (8) ──
  {
    id: 'bard-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'Dedicated study allows you to prepare a wider range of simple spells. You can prepare two additional cantrips each day.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-directed-audience',
    name: 'Directed Audience',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'You can shape the area of your composition spells. Whenever you cast a composition spell whose area is an emanation, you can change the spell\'s area to a cone 10 feet larger, to a maximum of twice the original area. For example, you could modify a composition spell that affects a 30-foot emanation to affect a 40-foot cone, but a 5-foot emanation could only become a 10-foot cone.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-emotional-push',
    name: 'Emotional Push',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'You prepare to take advantage of your enemy\'s sudden change in emotions. The target is off-guard against your next attack before the end of your next turn.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An enemy you\'re aware of fails its save against an emotion spell. Target becomes off-guard against your next attack before end of next turn.',
  },
  {
    id: 'bard-esoteric-polymath',
    name: 'Esoteric Polymath',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'You keep a book of occult spells, similar to a wizard\'s spellbook, and can use its spells to supplement your spell repertoire. Add all the spells in your repertoire to this book for free. You can use the Occultism skill to Learn Spells and add them to your spellbook by paying the appropriate cost. During your daily preparations, choose any one spell from your book of occult spells. If that spell is already in your spell repertoire, you can treat it as an additional signature spell that day. If it isn\'t in your repertoire, treat it as though it were until your next daily preparations.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Polymath muse'],
  },
  {
    id: 'bard-loremasters-etude',
    name: 'Loremaster\'s Etude',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'You magically unlock memories, making them easier to recall. You learn the loremaster\'s etude composition spell.',
    implemented: 'full',
    traits: ['Bard', 'Fortune'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse'],
  },
  {
    id: 'bard-multifarious-muse',
    name: 'Multifarious Muse',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'Your muse doesn\'t fall into a single label. Choose a type of muse other than that of your own. You gain a 1st-level feat that requires that muse, and your muse is now also a muse of that type, allowing you to take feats with the other muse as a prerequisite. You don\'t gain any of the other effects of the muse you chose. Special: You can take this feat multiple times. Each time you do, you must choose a different type of muse other than that of your own.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    subChoices: { label: 'Choose a muse', options: [
      { id: 'enigma', name: 'Enigma', description: 'Bardic Lore feat' },
      { id: 'maestro', name: 'Maestro', description: 'Lingering Composition feat' },
      { id: 'polymath', name: 'Polymath', description: 'Versatile Performance feat' },
      { id: 'warrior', name: 'Warrior', description: 'Martial Performance feat' },
    ] },
  },
  {
    id: 'bard-song-of-strength',
    name: 'Song of Strength',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'Your performances inspire strength in your allies to aid them at physical tasks. You learn the song of strength composition cantrip.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Warrior muse'],
  },
  {
    id: 'bard-uplifting-overture',
    name: 'Uplifting Overture',
    source: 'Bard',
    category: 'class',
    level: 2,
    description: 'You learn the uplifting overture composition cantrip, which aids your allies\' skills with the inspiring nature of your performance.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Maestro muse'],
  },
  // ── Level 4 Feats (8) ──
  {
    id: 'bard-combat-reading',
    name: 'Combat Reading',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'You use a performer\'s cold reading techniques, aura reading, and other tricks to discover your foe\'s strengths and weaknesses. The GM rolls a secret Occultism check for you against the Deception or Stealth DC (whichever is higher) of an enemy of your choice who is not concealed from you, hidden from you, or undetected by you, and who is engaged in combat. The enemy is then temporarily immune to your Combat Reading for 1 day. Critical Success: The GM chooses and tells you two of the following pieces of information: which of the enemy\'s weaknesses is highest, which saving throw has the lowest modifier, one immunity, or which resistance is highest. Success: The GM tells you one piece of information from the list. Critical Failure: The GM gives you false information.',
    implemented: 'full',
    traits: ['Bard', 'Secret'],
    actionCost: 1,
  },
  {
    id: 'bard-courageous-advance',
    name: 'Courageous Advance',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'With a rousing call, you exhort an ally to advance. If your next action is to cast the courageous anthem composition cantrip, one ally of your choice who gains a status bonus from the spell can immediately use their reaction to Stride.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Warrior muse'],
  },
  {
    id: 'bard-in-tune',
    name: 'In Tune',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'You attune your great skill in performing to another, granting them a small measure of your skill as though anyone could do it. If your next action is casting a composition spell with an emanation area, its area spreads from a willing ally of your choice within 60 feet instead of you. If you have Directed Audience, you can have that cone originate from the ally instead.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Maestro muse'],
  },
  {
    id: 'bard-melodious-spell',
    name: 'Melodious Spell',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'You subtly weave your spellcasting into a performance. If the next action you use is to Cast a Spell, the spell gains the subtle trait, hiding the shining runes, sparks of magic, and other manifestations that would usually give away your spellcasting. The trait hides only the spell\'s spellcasting actions and manifestations, not its effects, so an observer might still see a ray streak out from you or see you vanish into thin air. As part of using Melodious Spell, you can choose to Create a Diversion, Demoralize, Perform, or Request. If you do so, the spell you cast must have the auditory, emotion, sonic, or visual trait to gain the benefit.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
  },
  {
    id: 'bard-rallying-anthem',
    name: 'Rallying Anthem',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'You learn the rallying anthem composition cantrip, which bolsters your allies\' defenses against harm.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-ritual-researcher',
    name: 'Ritual Researcher',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'Careful research into the art of rituals has made you better at performing them. You gain a +2 circumstance bonus to all primary and secondary checks you attempt as part of casting a ritual.',
    implemented: 'full',
    traits: ['Uncommon', 'Bard'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse', 'Expert in Occultism'],
  },
  {
    id: 'bard-triple-time',
    name: 'Triple Time',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'You learn the triple time composition cantrip, which speeds up you and your allies for a round.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-versatile-signature',
    name: 'Versatile Signature',
    source: 'Bard',
    category: 'class',
    level: 4,
    description: 'While most bards are known for certain signature performances and spells, you\'re always tweaking your available repertoire. When you make your daily preparations, you can change one of your signature spells to a different spell of that rank from your repertoire.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Polymath muse'],
  },
  // ── Level 6 Feats (7) ──
  {
    id: 'bard-assured-knowledge',
    name: 'Assured Knowledge',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'You can procure information with confidence. Whenever you Recall Knowledge using any skill (including Bardic Lore), you can forgo rolling your check to instead receive a result of 10 + your proficiency bonus (don\'t apply any other bonuses, penalties, or modifiers). As long as you are an expert in a skill, you meet the prerequisites for the Automatic Knowledge skill feat for that skill, even if you don\'t have the Assurance feat for that skill.',
    implemented: 'full',
    traits: ['Bard', 'Fortune'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse'],
  },
  {
    id: 'bard-defensive-coordination',
    name: 'Defensive Coordination',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'Like the storied heroes who persist in the face of overwhelming odds, you and your allies will hold the line. If your next action is to cast the rallying anthem composition cantrip, you can Raise a Shield, and one ally of your choice who gains a status bonus from the spell can immediately use their reaction to Raise a Shield.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Warrior muse', 'Rallying Anthem'],
  },
  {
    id: 'bard-dirge-of-doom',
    name: 'Dirge of Doom',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'You learn the dirge of doom composition cantrip, which frightens your enemies and keeps them from fully recovering from their fear.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-educate-allies',
    name: 'Educate Allies',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'You tweak the properties of your composition spell to convey a bit of your defensive knowledge. All allies affected by your composition spell gain your +1 circumstance bonus from Well-Versed until the start of your next turn. Teaching your allies also bolsters your own skills; your personal circumstance bonus from Well-Versed also increases to +2 until the start of your next turn.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Well-Versed'],
    mechanics: 'Trigger: An ally benefiting from one of your composition spells is subject to an effect with the auditory, illusion, linguistic, sonic, or visual trait.',
  },
  {
    id: 'bard-harmonize',
    name: 'Harmonize',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'You can perform multiple compositions simultaneously, typically by performing in multiple ways at the same time, using special vocal techniques to double your voice, or creating occult magic that replicates your song or speech. If your next action is to cast a composition, it becomes a harmonized composition. Unlike a normal composition, a harmonized composition doesn\'t end if you cast another composition, and you can cast another composition on the same turn as a harmonized one. Casting another harmonized composition ends any harmonized composition you already have in effect.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Manipulate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Maestro muse'],
  },
  {
    id: 'bard-song-of-marching',
    name: 'Song of Marching',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'You learn the song of marching composition cantrip, which enables you and your allies to cross vast distances without strain.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Bard',
    category: 'class',
    level: 6,
    description: 'You don\'t lose spells easily. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn\'t disrupted.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Druid', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
  },
  // ── Level 8 Feats (7) ──
  {
    id: 'bard-accompany',
    name: 'Accompany',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'You use your performance to supplement an ally\'s spellcasting, providing magical energy for their spell in their stead. Attempt a Performance check, using a very high DC for the ally\'s level, and either spend a Focus Point (if the triggering spell is a focus spell) or expend a spell slot at least 1 rank higher than the triggering spell. If you succeed at your Performance check, your ally\'s spell doesn\'t cost the Focus Point or spell slot that ally would normally need to spend.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Manipulate'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An ally within 30 feet Casts a Spell. You attempt a Performance check (very high DC for ally\'s level) and expend a Focus Point or spell slot (1+ rank higher). On success, the ally\'s spell doesn\'t cost them a FP or slot.',
  },
  {
    id: 'bard-call-and-response',
    name: 'Call and Response',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'Your composition takes the form of a call-and-response chant that lets your allies continue the effect without you. If your next action is to cast a composition cantrip with a duration of 1 round, it becomes a call. While the spell is active, one ally of your choice affected by the spell can respond to your call as a single action that has the auditory and concentrate traits to extend the spell\'s duration by 1 round. Only one ally can respond to a given call, and responding to the ally\'s response has no additional effect.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
  },
  {
    id: 'bard-eclectic-skill',
    name: 'Eclectic Skill',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'Your broad experiences translate to a range of skills. Your proficiency bonus to untrained skill checks is equal to your level. You can attempt any skill check that normally requires you to be trained, even if you are untrained. If you have legendary proficiency in Occultism, you can attempt any skill check that normally requires you to have expert proficiency, even if untrained or trained.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Polymath muse', 'Master in Occultism'],
  },
  {
    id: 'bard-fortissimo-composition',
    name: 'Fortissimo Composition',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'Your anthems grow louder and more potent, bolstered by your muse\'s power. You learn the fortissimo composition spellshape focus spell.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Maestro muse'],
  },
  {
    id: 'bard-know-it-all',
    name: 'Know-It-All',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'When you succeed at a check to Recall Knowledge, you gain additional information or context. When you critically succeed at a check to Recall Knowledge, you get additional information or context or can ask an additional follow-up question (the GM chooses which).',
    implemented: 'full',
    traits: ['Bard', 'Thaumaturge'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse'],
  },
  {
    id: 'bard-reflexive-courage',
    name: 'Reflexive Courage',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'You bellow a ferocious call to arms, inspiring yourself to lash out at a foe. Make a melee Strike against the triggering creature. If the attack is a critical hit and the trigger was a manipulate action, the action is disrupted.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Warrior muse'],
    mechanics: 'Trigger: A creature within your reach uses an auditory effect, manipulate action, or move action; makes a ranged attack; or leaves a square during its move action. Requirements: You are affected by courageous anthem.',
  },
  {
    id: 'bard-soulsight',
    name: 'Soulsight',
    source: 'Bard',
    category: 'class',
    level: 8,
    description: 'Your muse has opened your senses to the world beyond. You gain spiritsense as an imprecise sense with a range of 60 feet. Spiritsense enables you to sense the spirits of creatures, including living creatures, most non-mindless undead, and haunts within the listed range. As with your hearing and other imprecise senses, you still need to Seek to locate an undetected creature. As spiritsense detects spiritual essence, not physical bodies, it can detect spirits projected by spells such as project image or possessing otherwise soulless objects. It can\'t detect soulless bodies, constructs, or objects, and like most senses, it doesn\'t penetrate through solid objects.',
    implemented: 'full',
    traits: ['Bard', 'Sorcerer'],
    actionCost: 'passive',
  },
  // ── Level 10 Feats (7) ──
  {
    id: 'bard-annotate-composition',
    name: 'Annotate Composition',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'By putting composition to paper, you can create a source of stirring words or song that others can read and understand. You spend 10 minutes and 1 Focus Point to transpose a composition spell on a special scroll that you or another creature can later activate. This composition spell must take a single action to cast. If the chosen composition spell requires a Performance check as part of the casting, the GM rolls this check as a secret check when you annotate your score. If you have fortissimo composition or lingering composition, you can also use one of those spells to modify the annotated composition, provided the annotated composition can benefit from the modification. The GM rolls the secret Performance check. If you do, you spend an additional Focus Point, even if the secret check fails. Any creature that can read the language you used when annotating your composition can Activate the Item by spending a single action, which has the concentrate trait. This produces the effects of the composition as though the activating creature had Cast the Spell. A composition you create this way loses its power the next time you make your daily preparations. While the composition is in your possession, you can render it inert using a single action that has the concentrate trait. You can\'t regain the Focus Points you spent to create the annotated composition until it is activated or loses its magic.',
    implemented: 'full',
    traits: ['Bard', 'Exploration', 'Linguistic'],
    actionCost: 'passive',
    mechanics: 'Exploration activity (10 minutes). Costs 1 FP (or 2 if adding fortissimo/lingering). Creates a scroll others can activate. FPs locked until scroll is used or expires.',
  },
  {
    id: 'bard-courageous-assault',
    name: 'Courageous Assault',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'With a mighty shout, you can stir an ally to attack. If your next action is to cast the courageous anthem composition cantrip, one ally of your choice who gains a status bonus from the spell can immediately use their reaction to make a melee Strike.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Warrior muse'],
  },
  {
    id: 'bard-house-of-imaginary-walls',
    name: 'House of Imaginary Walls',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'You erect an imaginary barrier others believe to be real. You learn the house of imaginary walls composition cantrip.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-ode-to-ouroboros',
    name: 'Ode to Ouroboros',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'You learn the ode to ouroboros composition spell, which enables you to temporarily spare your allies from death.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-quickened-casting',
    name: 'Quickened Casting',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'If your next action is to cast a cantrip or a spell that is at least 2 ranks lower than the highest-rank spell slot you have, reduce the number of actions to cast it by 1 (minimum 1 action).',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Frequency: once per day.',
  },
  {
    id: 'bard-symphony-of-the-unfettered-heart',
    name: 'Symphony of the Unfettered Heart',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'You learn the symphony of the unfettered heart composition spell, which enables you to protect an ally against incapacitating conditions.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-unusual-composition',
    name: 'Unusual Composition',
    source: 'Bard',
    category: 'class',
    level: 10,
    description: 'You can translate the emotion and power of a composition to other mediums. If your next action is to cast a composition spell that is auditory or visual, you can have it affect creatures who can witness it with any sense, not just those the traits indicate, even including special senses like tremorsense. You can choose to exclude any senses you choose.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Manipulate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Polymath muse'],
  },
  // ── Level 12 Feats (5) ──
  {
    id: 'bard-eclectic-polymath',
    name: 'Eclectic Polymath',
    source: 'Bard',
    category: 'class',
    level: 12,
    description: 'Your flexible mind can quickly shift from one spell to another. If you add a spell to your repertoire during your daily preparations using Esoteric Polymath, when you prepare again, you can choose to keep the new spell from Esoteric Polymath in your repertoire and instead lose access to another spell of the same rank in your repertoire.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Esoteric Polymath'],
  },
  {
    id: 'bard-enigmas-knowledge',
    name: 'Enigma\'s Knowledge',
    source: 'Bard',
    category: 'class',
    level: 12,
    description: 'Your muse whispers knowledge to you at all the right times. You gain the benefits of the Automatic Knowledge skill feat with any skill you can use to Recall Knowledge. As per the special clause in the Automatic Knowledge feat, you can still only use Automatic Knowledge once per round.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Assured Knowledge'],
  },
  {
    id: 'bard-inspirational-focus',
    name: 'Inspirational Focus',
    source: 'Bard',
    category: 'class',
    level: 12,
    description: 'Your connection to your muse has granted you unusual focus. Whenever you Refocus, completely refill your focus pool.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-reverberate',
    name: 'Reverberate',
    source: 'Bard',
    category: 'class',
    level: 12,
    description: 'You can manipulate the acoustics around you to deflect sonic damage back at its source. Attempt a Performance check against the Will DC of the creature or Fortitude DC of a hazard. If the damage came from a spell, use the creature\'s spell DC if it\'s lower. Critical Success: You reduce the triggering damage by an amount up to four times your level. The caster takes sonic damage equal to the amount you reduced. Success: As critical success, but you reduce by an amount up to twice your level. Critical Failure: You misdirect the sonic waves at yourself, taking twice the triggering damage.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature or hazard would deal sonic damage to you.',
  },
  {
    id: 'bard-shared-assault',
    name: 'Shared Assault',
    source: 'Bard',
    category: 'class',
    level: 12,
    description: 'In the triumph of battle, you can share the glory with another ally. When the ally you chose for Courageous Assault critically succeeds at the Strike granted by that action, another ally affected by your courageous anthem composition spell can immediately use a reaction to make a melee Strike. This effect doesn\'t continue to a third ally, even if the second ally also critically succeeds.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Courageous Assault'],
  },
  // ── Level 14 Feats (6) ──
  {
    id: 'bard-allegro',
    name: 'Allegro',
    source: 'Bard',
    category: 'class',
    level: 14,
    description: 'You can quicken your allies with a fast-paced performance. You learn the allegro composition cantrip.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-earworm',
    name: 'Earworm',
    source: 'Bard',
    category: 'class',
    level: 14,
    description: 'By endlessly repeating a motif, you implant a memorable song that repeats over and over again in your allies\' heads, preparing them to respond to it later. Choose a composition cantrip and spend 10 minutes performing. Any ally that heard you perform can use a free action with the concentrate trait to activate the earworm, producing the effect of the composition cantrip as if you had cast it. The ally must attempt a Performance check using your Performance modifier. The earworm lasts until your next daily preparations.',
    implemented: 'full',
    traits: ['Bard', 'Exploration'],
    actionCost: 'passive',
    mechanics: 'Exploration activity (10 minutes). Choose a composition cantrip. Allies who heard can later activate it as a free action using your Performance modifier.',
    subChoices: { label: 'Choose a composition cantrip', options: [
      { id: 'courageous-anthem', name: 'Courageous Anthem', description: '+1 status to attack rolls, damage rolls, and saves vs fear' },
      { id: 'dirge-of-doom', name: 'Dirge of Doom', description: 'Enemies in emanation are frightened 1' },
      { id: 'house-of-imaginary-walls', name: 'House of Imaginary Walls', description: 'Create an immovable invisible wall section' },
      { id: 'rallying-anthem', name: 'Rallying Anthem', description: 'Grant allies temporary HP' },
      { id: 'silver-s-refrain', name: "Silver's Refrain", description: 'Weapons count as silver for weakness/resistance' },
      { id: 'triple-time', name: 'Triple Time', description: '+10-foot status bonus to Speed' },
    ] },
  },
  {
    id: 'bard-soothing-ballad',
    name: 'Soothing Ballad',
    source: 'Bard',
    category: 'class',
    level: 14,
    description: 'You soothe your allies\' wounds with the power of performance. You learn the soothing ballad composition spell.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-triumphant-inspiration',
    name: 'Triumphant Inspiration',
    source: 'Bard',
    category: 'class',
    level: 14,
    description: 'With a triumphant shout, you inspire your allies. You cast a composition cantrip you know that normally takes a single action to cast.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'free',
    prerequisites: ['Warrior muse'],
    mechanics: 'Trigger: You critically hit a foe with a melee weapon Strike or a melee unarmed attack.',
  },
  {
    id: 'bard-true-hypercognition',
    name: 'True Hypercognition',
    source: 'Bard',
    category: 'class',
    level: 14,
    description: 'Your mind works at an incredible pace. You instantly use up to five Recall Knowledge actions. If you have any special abilities or free actions that would normally be triggered when you Recall Knowledge, you can\'t use them for these actions.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 1,
    prerequisites: ['Enigma muse'],
  },
  {
    id: 'bard-vigorous-anthem',
    name: 'Vigorous Anthem',
    source: 'Bard',
    category: 'class',
    level: 14,
    description: 'If your next action is to cast courageous anthem, you and all affected allies gain temporary Hit Points equal to 3 + your Charisma modifier for 1 minute.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
  },
  // ── Level 16 Feats (4) ──
  {
    id: 'bard-courageous-onslaught',
    name: 'Courageous Onslaught',
    source: 'Bard',
    category: 'class',
    level: 16,
    description: 'You use your performance to orchestrate an onslaught against your enemies. If your next action is to cast the courageous anthem composition cantrip, one ally of your choice who gains a status bonus from the spell can immediately use their reaction to Stride and then make a melee Strike.',
    implemented: 'full',
    traits: ['Auditory', 'Bard', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Courageous Advance', 'Courageous Assault'],
  },
  {
    id: 'bard-effortless-concentration',
    name: 'Effortless Concentration',
    source: 'Bard',
    category: 'class',
    level: 16,
    description: 'You can maintain a spell with barely a thought. At the start of each of your turns, you automatically gain the benefit of the Sustain a Spell action for one spell, even though you didn\'t use an action. You still must meet any requirements for Sustain a Spell.',
    implemented: 'full',
    traits: ['Bard', 'Druid', 'Sorcerer', 'Summoner', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Trigger: Your turn begins.',
  },
  {
    id: 'bard-resounding-finale',
    name: 'Resounding Finale',
    source: 'Bard',
    category: 'class',
    level: 16,
    description: 'You end an active composition with a thunderous performance that deals sonic damage to enemies. When you dismiss or end a composition spell, enemies in the area take sonic damage.',
    implemented: 'full',
    traits: ['Bard', 'Concentrate'],
    actionCost: 'reaction',
    prerequisites: ['Maestro muse'],
    mechanics: 'Trigger: An enemy within your composition area would deal sonic damage.',
  },
  {
    id: 'bard-studious-capacity',
    name: 'Studious Capacity',
    source: 'Bard',
    category: 'class',
    level: 16,
    description: 'Your continued study of occult magic has increased your magical capacity, allowing you to cast spells even when it seems impossible. You can cast one spell each day even after you\'ve run out of spell slots of the appropriate spell rank, but you can\'t use this ability to cast a spell of your highest spell rank.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse', 'Legendary in Occultism'],
  },
  // ── Level 18 Feats (5) ──
  {
    id: 'bard-all-in-my-head',
    name: 'All in my Head',
    source: 'Bard',
    category: 'class',
    level: 18,
    description: 'You convince yourself that any damage you are about to take is an illusion. The damage changes to mental damage and gains the nonlethal trait. You can\'t use this ability if you are immune to mental effects.',
    implemented: 'full',
    traits: ['Bard', 'Illusion', 'Mental'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You would take damage from a Strike or spell. Incoming damage becomes mental and nonlethal. Unusable if immune to mental.',
  },
  {
    id: 'bard-deep-lore',
    name: 'Deep Lore',
    source: 'Bard',
    category: 'class',
    level: 18,
    description: 'Your repertoire is vast, containing far more spells than usual. Add one spell to your repertoire of each spell rank you can cast.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Enigma muse', 'Legendary in Occultism'],
  },
  {
    id: 'bard-discordant-voice',
    name: 'Discordant Voice',
    source: 'Bard',
    category: 'class',
    level: 18,
    description: 'While your allies are affected by your courageous anthem, their weapon Strikes and unarmed attacks deal an additional 1d6 sonic damage.',
    implemented: 'full',
    traits: ['Bard', 'Sonic'],
    actionCost: 'passive',
    prerequisites: ['Courageous Anthem (composition cantrip)'],
  },
  {
    id: 'bard-eternal-composition',
    name: 'Eternal Composition',
    source: 'Bard',
    category: 'class',
    level: 18,
    description: 'The world is a stage upon which you are always playing. You are permanently quickened; you can use your extra action only to cast a composition cantrip that requires 1 action to cast. While in exploration mode, you can declare that you are performing an eligible composition cantrip while using any exploration tactic. Even before your first turn in a combat encounter, that cantrip is active as if you had cast it on your previous turn.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Maestro muse'],
  },
  {
    id: 'bard-impossible-polymath',
    name: 'Impossible Polymath',
    source: 'Bard',
    category: 'class',
    level: 18,
    description: 'Your esoteric formulas are so unusual that they allow you to dabble in magic from diverse traditions that other bards don\'t understand. As long as you\'re trained in Arcana, you can add arcane spells to your book from Esoteric Polymath; as long as you\'re trained in Nature, you can add primal spells to your book; and as long as you are trained in Religion, you can add divine spells to your book. Like your other spells in your book, you can add one of these spells from another tradition to your repertoire as an occult spell each day using Esoteric Polymath, but you can\'t retain any spells from another tradition when you prepare again, even if you have Eclectic Polymath.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Trained in Arcana, Nature, or Religion', 'Esoteric Polymath'],
  },
  // ── Level 20 Feats (5) ──
  {
    id: 'bard-fatal-aria',
    name: 'Fatal Aria',
    source: 'Bard',
    category: 'class',
    level: 20,
    description: 'Your songs overwhelm the target with unbearable emotion, potentially striking them dead on the spot. You learn the fatal aria composition spell.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-perfect-encore',
    name: 'Perfect Encore',
    source: 'Bard',
    category: 'class',
    level: 20,
    description: 'You develop another incredible creation. You gain an additional 10th-rank spell slot.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Magnum Opus'],
  },
  {
    id: 'bard-pied-piping',
    name: 'Pied Piping',
    source: 'Bard',
    category: 'class',
    level: 20,
    description: 'You learn the pied piping composition spell, which enables you to control the actions of weak-minded individuals.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
  },
  {
    id: 'bard-symphony-of-the-muse',
    name: 'Symphony of the Muse',
    source: 'Bard',
    category: 'class',
    level: 20,
    description: 'You have learned how to weave countless performances together into a solo symphony with multitudinous effects. You are no longer limited to a single composition each turn or a single composition at a time; when you use a new composition, all previous compositions\' effects continue for their remaining duration.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Harmonize'],
  },
  {
    id: 'bard-ultimate-polymath',
    name: 'Ultimate Polymath',
    source: 'Bard',
    category: 'class',
    level: 20,
    description: 'You can flexibly cast all of your spells, granting a dizzying array of possible options. All of the spells in your repertoire are signature spells for you.',
    implemented: 'full',
    traits: ['Bard'],
    actionCost: 'passive',
    prerequisites: ['Polymath muse'],
  },
];
