/**
 * Champion Class Features & Feats — PF2e Remastered (Player Core 2)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=58
 *
 * Key Attribute: STR or DEX | HP: 10 + CON
 * Perception: Trained → Expert (L11, Perception Expertise)
 * Fort: Expert → Master (L9, Sacred Body, success→crit)
 * Reflex: Trained → Expert (L9, Reflex Expertise)
 * Will: Expert → Master (L11, Divine Will, success→crit)
 * Weapons: Trained simple+martial+unarmed → Expert (L5) → Master (L13)
 * Armor: Trained all+unarmored → Expert (L7, armor spec medium/heavy) → Master (L13) → Legendary (L17)
 * Spellcasting: Trained (devotion spells only — divine focus spells)
 * Class DC: Trained → Expert (L9) → Master (L17)
 *
 * Causes (Player Core 2):
 *   Holy: Grandeur (Flash of Grandeur), Justice (Retributive Strike),
 *         Liberation (Liberating Step), Redemption (Glimpse of Redemption)
 *   Unholy (Uncommon): Desecration (Selfish Shield), Iniquity (Destructive Vengeance),
 *         Obedience (Iron Command)
 *
 * Blessings of the Devoted (L3):
 *   Blessed Armament — property rune on weapon/handwraps, crit spec
 *   Blessed Shield — reinforcing rune scaling
 *   Blessed Swiftness — +5 status bonus to Speed, +2 to defenses vs reactions
 *
 * Class features: 19 (L1–L19)
 * Class feats: 57 PC2 feats (AoN IDs 5881–5933 + shared 5832, 4807, 4816)
 */

import type { FeatEntry } from './featTypes';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
  GREATER_WEAPON_SPECIALIZATION,
  SHIELD_BLOCK,
} from './sharedFeats';

// ──────────────────────────────────────────────────────────
// CHAMPION CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const CHAMPION_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'champion-deity',
    name: 'Deity',
    source: 'Champion',
    category: 'class_feature',
    level: 1,
    description: 'As a champion, you are a warrior in the name of a deity you revere above all others. You become trained in the divine skill listed for your deity. Your deity determines your sanctification options (holy, unholy, or none), access to their favored weapon (deific weapon), and your champion\'s aura.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    subChoices: { label: 'Choose a deity', options: [
      { id: 'abadar', name: 'Abadar', description: 'LN — Cities, Law, Merchants, Wealth' },
      { id: 'calistria', name: 'Calistria', description: 'CN — Lust, Revenge, Trickery' },
      { id: 'cayden-cailean', name: 'Cayden Cailean', description: 'CG — Ale, Bravery, Freedom' },
      { id: 'desna', name: 'Desna', description: 'CG — Dreams, Luck, Stars, Travel' },
      { id: 'erastil', name: 'Erastil', description: 'LG — Family, Farming, Hunting' },
      { id: 'gorum', name: 'Gorum', description: 'CN — Battle, Strength, Weapons' },
      { id: 'gozreh', name: 'Gozreh', description: 'N — Nature, Sea, Weather' },
      { id: 'iomedae', name: 'Iomedae', description: 'LG — Honor, Justice, Valor' },
      { id: 'irori', name: 'Irori', description: 'LN — Knowledge, Perfection, Self-Improvement' },
      { id: 'lamashtu', name: 'Lamashtu', description: 'CE — Madness, Monsters, Nightmares' },
      { id: 'nethys', name: 'Nethys', description: 'N — Magic' },
      { id: 'norgorber', name: 'Norgorber', description: 'NE — Greed, Murder, Poison, Secrets' },
      { id: 'pharasma', name: 'Pharasma', description: 'N — Birth, Death, Fate, Prophecy' },
      { id: 'rovagug', name: 'Rovagug', description: 'CE — Destruction, Disaster, Wrath' },
      { id: 'sarenrae', name: 'Sarenrae', description: 'NG — Healing, Honesty, Redemption, Sun' },
      { id: 'shelyn', name: 'Shelyn', description: 'NG — Art, Beauty, Love, Music' },
      { id: 'torag', name: 'Torag', description: 'LG — Forge, Protection, Strategy' },
      { id: 'urgathoa', name: 'Urgathoa', description: 'NE — Disease, Gluttony, Undeath' },
      { id: 'zon-kuthon', name: 'Zon-Kuthon', description: 'LE — Darkness, Envy, Loss, Pain' },
      { id: 'other', name: 'Other Deity', description: 'A deity not listed above' },
    ] },
  },
  {
    id: 'champion-deific-weapon',
    name: 'Deific Weapon',
    source: 'Champion',
    category: 'class_feature',
    level: 1,
    description: 'You zealously bear your deity\'s favored weapon. If it\'s an unarmed attack with a d4 damage die or a simple weapon, increase the damage die by one step (d4 to d6, d6 to d8, d8 to d10, d10 to d12). If the weapon is uncommon, you gain access to it, and if it\'s an advanced weapon, you treat it as a martial weapon for the purposes of proficiency.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-champions-aura',
    name: 'Champion\'s Aura',
    source: 'Champion',
    category: 'class_feature',
    level: 1,
    description: 'You\'re surrounded by an aura in a 15-foot emanation. It has the aura and divine traits. Any follower of your deity within the aura immediately knows you\'re a champion of your deity. This aura is used as the range for your champion\'s reaction and for various other effects. You can suppress or resume the aura as a single action, which has the concentrate trait, and it ends if you fall unconscious.',
    implemented: 'full',
    traits: ['Champion', 'Aura', 'Divine'],
    actionCost: 'passive',
  },
  {
    id: 'champion-cause',
    name: 'Cause',
    source: 'Champion',
    category: 'class_feature',
    level: 1,
    description: 'You devote yourself to a specific cause in your deity\'s name. Some causes are limited to certain sanctifications. Your cause adds to your edicts and anathema and grants you a special protective reaction called your champion\'s reaction. Holy causes: Grandeur (Flash of Grandeur), Justice (Retributive Strike), Liberation (Liberating Step), Redemption (Glimpse of Redemption). Unholy causes (Uncommon): Desecration (Selfish Shield), Iniquity (Destructive Vengeance), Obedience (Iron Command).',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Cause determines champion\'s reaction, additional tenets, relentless reaction (L9), and exalted reaction (L11).',
    subChoices: { label: 'Choose a cause', options: [
      { id: 'grandeur', name: 'Grandeur (Holy)', description: 'Reaction: Glimpse of Grandeur — dazzle foe' },
      { id: 'justice', name: 'Justice (Holy)', description: 'Reaction: Retributive Strike — counter-attack triggering foe' },
      { id: 'liberation', name: 'Liberation (Holy)', description: 'Reaction: Liberating Step — free ally from restraint' },
      { id: 'redemption', name: 'Redemption (Holy)', description: 'Reaction: Glimpse of Redemption — reduce damage and deter foe' },
      { id: 'desecration', name: 'Desecration (Unholy)', description: 'Reaction: Selfish Shield — absorb ally damage as HP' },
      { id: 'iniquity', name: 'Iniquity (Unholy)', description: 'Reaction: Iron Command — force foe to kneel' },
      { id: 'obedience', name: 'Obedience (Unholy)', description: 'Reaction: Destructive Vengeance — deal damage when harmed' },
    ] },
  },
  {
    id: 'champion-devotion-spells',
    name: 'Devotion Spells',
    source: 'Champion',
    category: 'class_feature',
    level: 1,
    description: 'Your deity\'s power grants you special divine spells called devotion spells, which are a type of focus spell. Choose either shields of the spirit or a spell based on your deity\'s divine font (lay on hands if your deity allows heal, touch of the void if your deity allows harm). It costs 1 Focus Point to cast a focus spell. When you gain your first devotion spell, you also gain a focus pool of 1 Focus Point. You refill your focus pool during your daily preparations, and you regain 1 Focus Point by spending 10 minutes using the Refocus activity to pray to your deity or do service toward their causes. Your devotion spells are divine spells. Your spellcasting attribute is Charisma. Focus spells are automatically heightened to half your level rounded up.',
    implemented: 'full',
    traits: ['Champion', 'Divine'],
    actionCost: 'passive',
    mechanics: 'Focus pool: 1 FP. Max FP = number of focus spells known (max 3). Choose lay on hands, touch of the void, or shields of the spirit.',
    subChoices: { label: 'Choose devotion spell', options: [
      { id: 'lay-on-hands', name: 'Lay on Hands', description: 'Healing focus spell' },
      { id: 'touch-of-the-void', name: 'Touch of the Void', description: 'Void damage focus spell' },
      { id: 'shields-of-the-spirit', name: 'Shields of the Spirit', description: 'Protective focus spell' },
    ] },
  },
  // Shield Block (L1). Uses shared template.
  createClassFeature(SHIELD_BLOCK, 'Champion', 1),
  // ── Level 3 ──
  {
    id: 'champion-blessing-of-the-devoted',
    name: 'Blessing of the Devoted',
    source: 'Champion',
    category: 'class_feature',
    level: 3,
    description: 'Your deity blesses your service with a boon. Choose one blessing: Blessed Armament — select one weapon or handwraps of mighty blows; you gain that armament\'s critical specialization effect, and you grant it a property rune (fearsome, ghost touch, returning, shifting, or vitalizing) that scales with level. Blessed Shield — in your hands, a shield gains the minor reinforcing rune, scaling to lesser (L7), moderate (L10), greater (L13), major (L16), supreme (L19); if it already has the appropriate rune, its Hardness increases by 1. Blessed Swiftness — you gain a +5-foot status bonus to Speed (mount gains it instead if mounted); when an ally\'s movement triggers a reaction while in your aura, the ally gains a +2 status bonus to all defenses against that reaction.',
    implemented: 'full',
    traits: ['Champion', 'Divine'],
    actionCost: 'passive',
    mechanics: 'Choose Blessed Armament, Blessed Shield, or Blessed Swiftness. Runes and effects scale with level.',
    subChoices: { label: 'Choose a blessing', options: [
      { id: 'blessed-armament', name: 'Blessed Armament', description: 'Gain critical specialization + scaling property rune on a weapon' },
      { id: 'blessed-shield', name: 'Blessed Shield', description: 'Shield gains scaling reinforcing rune (+1 Hardness if already runed)' },
      { id: 'blessed-swiftness', name: 'Blessed Swiftness', description: '+5-foot status bonus to Speed; allies get +2 vs triggered reactions' },
    ] },
  },
  // ── Level 5 ──
  {
    id: 'champion-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Champion',
    category: 'class_feature',
    level: 5,
    description: 'You\'ve dedicated yourself to learning the intricacies of your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // ── Level 7 ──
  {
    id: 'champion-armor-expertise',
    name: 'Armor Expertise',
    source: 'Champion',
    category: 'class_feature',
    level: 7,
    description: 'You have spent so much time in armor that you know how to make the most of its protection. Your proficiency ranks for light, medium, and heavy armor, as well as for unarmored defense, increase to expert. You gain the armor specialization effects of medium and heavy armor.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // Weapon Specialization (L7). Uses shared template.
  createClassFeature(WEAPON_SPECIALIZATION, 'Champion', 7),
  // ── Level 9 ──
  {
    id: 'champion-champion-expertise',
    name: 'Champion Expertise',
    source: 'Champion',
    category: 'class_feature',
    level: 9,
    description: 'Prayers strengthen your divine power. Your proficiency ranks for your champion class DC, spell attack modifier, and spell DC increase to expert.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Champion',
    category: 'class_feature',
    level: 9,
    description: 'You\'ve developed a knack for dodging danger. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-relentless-reaction',
    name: 'Relentless Reaction',
    source: 'Champion',
    category: 'class_feature',
    level: 9,
    description: 'Your champion\'s reaction improves, typically to punish the attacker with spiritual backlash. It gains the relentless reaction benefit listed in your cause below your champion\'s reaction.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Effect depends on cause. Holy causes typically add persistent spirit damage or increased resistance; unholy causes add persistent damage or other debuffs.',
  },
  {
    id: 'champion-sacred-body',
    name: 'Sacred Body',
    source: 'Champion',
    category: 'class_feature',
    level: 9,
    description: 'The power of your deity keeps your body safe from harm, as true an edifice of the faith as a great temple. Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Fort: expert → master. Success on Fort saves → crit success.',
  },
  // ── Level 11 ──
  {
    id: 'champion-divine-will',
    name: 'Divine Will',
    source: 'Champion',
    category: 'class_feature',
    level: 11,
    description: 'Your faith grants mastery of your will. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Will: expert → master. Success on Will saves → crit success.',
  },
  {
    id: 'champion-exalted-reaction',
    name: 'Exalted Reaction',
    source: 'Champion',
    category: 'class_feature',
    level: 11,
    description: 'Your champion\'s reaction exalts nearby allies, allowing them to benefit as well. When you use your champion\'s reaction, you also get the effect listed for its exalted reaction.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Effect depends on cause. Typically extends resistance, bonus, or penalty to all allies in aura.',
  },
  {
    id: 'champion-perception-expertise',
    name: 'Perception Expertise',
    source: 'Champion',
    category: 'class_feature',
    level: 11,
    description: 'You remain alert to threats around you. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // ── Level 13 ──
  {
    id: 'champion-armor-mastery',
    name: 'Armor Mastery',
    source: 'Champion',
    category: 'class_feature',
    level: 13,
    description: 'Your skill with armor improves, helping you avoid more blows. Your proficiency ranks for light, medium, and heavy armor, as well as for unarmored defense, increase to master.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-weapon-mastery',
    name: 'Weapon Mastery',
    source: 'Champion',
    category: 'class_feature',
    level: 13,
    description: 'You fully understand your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // ── Level 15 ──
  // Greater Weapon Specialization (L15). Uses shared template.
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Champion', 15),
  // ── Level 17 ──
  {
    id: 'champion-champion-mastery',
    name: 'Champion Mastery',
    source: 'Champion',
    category: 'class_feature',
    level: 17,
    description: 'You\'ve mastered your champion techniques and divine spells. Your proficiency ranks for your champion class DC, spell attack modifier, and spell DC increase to master.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-legendary-armor',
    name: 'Legendary Armor',
    source: 'Champion',
    category: 'class_feature',
    level: 17,
    description: 'You shield yourself with steel as easily as with faith. Your proficiency ranks for light, medium, and heavy armor, as well as for unarmored defense, increase to legendary.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // ── Level 19 ──
  {
    id: 'champion-heros-defiance',
    name: 'Hero\'s Defiance',
    source: 'Champion',
    category: 'class_feature',
    level: 19,
    description: 'You can defy even the most grievous injuries. You gain the hero\'s defiance devotion spell.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Grants hero\'s defiance focus spell.',
  },
];

// ──────────────────────────────────────────────────────────
// CHAMPION CLASS FEATS (Selectable at Class Feat Levels)
// 57 feats, Player Core 2 (AoN IDs 5881–5933 + shared 5832, 4807, 4816)
// ──────────────────────────────────────────────────────────

export const CHAMPION_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 Feats (11) ──
  {
    id: 'champion-brilliant-flash',
    name: 'Brilliant Flash',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'Your light cleanses souls of fear. When you use Flash of Grandeur, the attacker is also off-guard for 1 round.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Grandeur cause'],
  },
  {
    id: 'champion-defensive-advance',
    name: 'Defensive Advance',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'With the protection of your shield, you dive into battle! You Raise your Shield and Stride. If you end your movement within melee reach of at least one enemy, you can make a melee Strike against that enemy. If your Speed is at least 10 feet, increase your shield\'s circumstance bonus to AC by 1 for the remainder of the current turn.',
    implemented: 'full',
    traits: ['Champion', 'Flourish', 'Guardian'],
    actionCost: 2,
  },
  {
    id: 'champion-domain-initiate',
    name: 'Domain Initiate',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'You have a domain, a connection to a particular facet of divinity, granting you a special domain spell related to that domain. Select one domain from your deity\'s domains. You gain an initial domain spell for that domain, a focus spell.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    subChoices: { label: 'Choose a domain', options: [
      { id: 'ambition', name: 'Ambition' },
      { id: 'change', name: 'Change' },
      { id: 'cities', name: 'Cities' },
      { id: 'confidence', name: 'Confidence' },
      { id: 'creation', name: 'Creation' },
      { id: 'darkness', name: 'Darkness' },
      { id: 'death', name: 'Death' },
      { id: 'decay', name: 'Decay' },
      { id: 'destruction', name: 'Destruction' },
      { id: 'dreams', name: 'Dreams' },
      { id: 'duty', name: 'Duty' },
      { id: 'earth', name: 'Earth' },
      { id: 'family', name: 'Family' },
      { id: 'fate', name: 'Fate' },
      { id: 'fire', name: 'Fire' },
      { id: 'freedom', name: 'Freedom' },
      { id: 'glyph', name: 'Glyph' },
      { id: 'healing', name: 'Healing' },
      { id: 'indulgence', name: 'Indulgence' },
      { id: 'knowledge', name: 'Knowledge' },
      { id: 'lightning', name: 'Lightning' },
      { id: 'luck', name: 'Luck' },
      { id: 'magic', name: 'Magic' },
      { id: 'might', name: 'Might' },
      { id: 'moon', name: 'Moon' },
      { id: 'nature', name: 'Nature' },
      { id: 'nightmares', name: 'Nightmares' },
      { id: 'pain', name: 'Pain' },
      { id: 'passion', name: 'Passion' },
      { id: 'perfection', name: 'Perfection' },
      { id: 'protection', name: 'Protection' },
      { id: 'secrecy', name: 'Secrecy' },
      { id: 'sorrow', name: 'Sorrow' },
      { id: 'soul', name: 'Soul' },
      { id: 'sun', name: 'Sun' },
      { id: 'swarm', name: 'Swarm' },
      { id: 'time', name: 'Time' },
      { id: 'travel', name: 'Travel' },
      { id: 'trickery', name: 'Trickery' },
      { id: 'truth', name: 'Truth' },
      { id: 'tyranny', name: 'Tyranny' },
      { id: 'undeath', name: 'Undeath' },
      { id: 'vigil', name: 'Vigil' },
      { id: 'void', name: 'Void' },
      { id: 'war', name: 'War' },
      { id: 'water', name: 'Water' },
      { id: 'wealth', name: 'Wealth' },
      { id: 'wyrmkin', name: 'Wyrmkin' },
      { id: 'zeal', name: 'Zeal' },
    ] },
  },
  {
    id: 'champion-desperate-prayer',
    name: 'Desperate Prayer',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'You call out to your deity in a plea for their aid. You instantly recover 1 Focus Point. The Focus Point must be spent by the end of your turn or it is lost.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'free',
    mechanics: 'Frequency: once per day. Trigger: You begin your turn and have no Focus Points.',
  },
  {
    id: 'champion-faithful-steed',
    name: 'Faithful Steed',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'You gain a young animal companion as a mount. When you choose the animal companion, consider the animal\'s suitability as a mount. You can select abilities that require the mount special ability as if your companion has that ability, and your companion gains the mount special ability automatically when it becomes a mature animal companion.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-iron-repercussions',
    name: 'Iron Repercussions',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'Disobeying your Iron Command has lasting consequences. When you use Iron Command, the persistent mental damage can be persistent spirit damage instead (your choice each time you use Iron Command).',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Obedience cause'],
  },
  {
    id: 'champion-nimble-reprisal',
    name: 'Nimble Reprisal',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'You can use Retributive Strike at greater distance. If the enemy that triggered Retributive Strike is within your reach but not adjacent to you, you can Step to become adjacent to the triggering enemy and make your Strike against that enemy with a –5 penalty instead of the normal –2. If the triggering enemy is within 15 feet but not within your reach, you can first Step toward the triggering enemy and then make a melee Strike against them with a –5 penalty.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Justice cause'],
  },
  {
    id: 'champion-ongoing-selfishness',
    name: 'Ongoing Selfishness',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'Your powerful personality and incredible ego demand that you protect yourself above all else. After you use Selfish Shield, you gain resistance to all further damage dealt by the triggering enemy equal to half the resistance from Selfish Shield until the end of the current turn.',
    implemented: 'full',
    traits: ['Uncommon', 'Champion'],
    actionCost: 'passive',
    prerequisites: ['Desecration cause'],
  },
  {
    id: 'champion-unimpeded-step',
    name: 'Unimpeded Step',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'With a burst of divine liberation, your ally\'s movement from your Liberating Step is unaffected by difficult terrain, greater difficult terrain, narrow surfaces, and uneven ground.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Liberation cause'],
  },
  {
    id: 'champion-vicious-vengeance',
    name: 'Vicious Vengeance',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'While your vengeance is painful for both you and your foe, none can doubt that your enemies suffer more. You gain a circumstance bonus to your Destructive Vengeance damage equal to the number of damage dice.',
    implemented: 'full',
    traits: ['Uncommon', 'Champion'],
    actionCost: 'passive',
    prerequisites: ['Iniquity cause'],
  },
  {
    id: 'champion-weight-of-guilt',
    name: 'Weight of Guilt',
    source: 'Champion',
    category: 'class',
    level: 1,
    description: 'Guilt clouds the minds of those who ignore your Glimpse of Redemption. When a foe refuses your Glimpse of Redemption, you can choose to make them stupefied 2 instead of enfeebled 2.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Redemption cause'],
  },
  // ── Level 2 Feats (2) ──
  {
    id: 'champion-divine-grace',
    name: 'Divine Grace',
    source: 'Champion',
    category: 'class',
    level: 2,
    description: 'You call upon your deity\'s grace, gaining a +2 circumstance bonus to the save.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You attempt a saving throw against a spell.',
  },
  {
    id: 'champion-divine-health',
    name: 'Divine Health',
    source: 'Champion',
    category: 'class',
    level: 2,
    description: 'Your faith makes you resistant to ailments. You gain a +2 status bonus to saves against diseases and poisons. Allies in your champion\'s aura gain a +1 status bonus to saves against diseases and poisons. If you roll a success on a saving throw against a disease or poison, you get a critical success instead.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // ── Level 4 Feats (5) ──
  {
    id: 'champion-aura-of-courage',
    name: 'Aura of Courage',
    source: 'Champion',
    category: 'class',
    level: 4,
    description: 'You stand strong in the face of danger and inspire your allies to do the same. You reduce your frightened condition value by 1 (to a minimum of 0) at the start of your turn instead of at the end. Allies in your champion\'s aura reduce their frightened condition value by 1 at the end of your turn.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s aura', 'Holy'],
  },
  {
    id: 'champion-aura-of-despair',
    name: 'Aura of Despair',
    source: 'Champion',
    category: 'class',
    level: 4,
    description: 'Your dark presence crushes the hope of others. When an enemy in your champion\'s aura would attempt a saving throw against a fear effect, it takes a –1 circumstance penalty to the saving throw. An enemy that is frightened can\'t reduce its frightened condition below 1 while it\'s in your aura.',
    implemented: 'full',
    traits: ['Uncommon', 'Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s aura', 'Unholy'],
  },
  {
    id: 'champion-cruelty',
    name: 'Cruelty',
    source: 'Champion',
    category: 'class',
    level: 4,
    description: 'The harm you deal with your corrupting touch saps the strength from your enemy\'s body. When you cast touch of the void using 2 actions, on a failed save the target also becomes enfeebled 1 for 1 minute. On a critical failure, the target is enfeebled 2 for 1 minute instead.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Touch of the void'],
  },
  {
    id: 'champion-mercy',
    name: 'Mercy',
    source: 'Champion',
    category: 'class',
    level: 4,
    description: 'Your touch relieves fear and restores movement. When you cast lay on hands, you can instead attempt to counteract a fear effect or an effect imposing the paralyzed condition on the target.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Lay on hands'],
    subChoices: { label: 'Choose a mercy type', options: [
      { id: 'body', name: 'Body', description: 'Counteract blinded, deafened, or sickened' },
      { id: 'grace', name: 'Grace', description: 'Counteract clumsy or enfeebled' },
      { id: 'mind', name: 'Mind', description: 'Counteract confused, frightened, or stupefied' },
    ] },
  },
  {
    id: 'champion-security',
    name: 'Security',
    source: 'Champion',
    category: 'class',
    level: 4,
    description: 'Those you shield can benefit from your lasting protection. When you cast shields of the spirit using 2 actions, choose an ally in your champion\'s aura. That ally gains a companion shield for 1 minute: a +1 circumstance bonus to AC while the shield is raised. The ally can use a Shield Block reaction as though they were wielding the shield.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Shields of the spirit'],
  },
  // ── Level 6 Feats (5, including 2 shared) ──
  {
    id: 'champion-expand-aura',
    name: 'Expand Aura',
    source: 'Champion',
    category: 'class',
    level: 6,
    description: 'You focus your divine power to extend your influence and protection. You expand the radius of your champion\'s aura to 30 feet until the start of your next turn. At 10th level, the duration becomes 1 minute instead. At 16th level, you can dismiss it as a free action.',
    implemented: 'full',
    traits: ['Champion', 'Concentrate'],
    actionCost: 1,
    prerequisites: ['Champion\'s aura'],
  },
  {
    id: 'champion-loyal-warhorse',
    name: 'Loyal Warhorse',
    source: 'Champion',
    category: 'class',
    level: 6,
    description: 'Your steed grows into a mighty companion. The mount you gained through Faithful Steed becomes a mature animal companion, granting it additional capabilities. It can never be induced to attack you, even by magical compulsion.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Faithful Steed'],
  },
  {
    id: 'champion-smite',
    name: 'Smite',
    source: 'Champion',
    category: 'class',
    level: 6,
    description: 'You designate your foe as the target of your wrath. Choose an enemy you can see. Your Strikes against that enemy gain a +3 status bonus to damage (+4 if your proficiency with your weapon is master). If you are holy, your Strikes against that enemy deal +4/+6 status bonus damage if the enemy is unholy. If you are unholy, your Strikes gain the same bonus against holy enemies. The smite effect extends beyond 1 round if the target takes hostile actions against you or your allies.',
    implemented: 'full',
    traits: ['Champion', 'Concentrate'],
    actionCost: 1,
  },
  {
    id: 'champion-reactive-strike',
    name: 'Reactive Strike',
    source: 'Champion',
    category: 'class',
    level: 6,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Champion', 'Commander', 'Exemplar', 'Guardian', 'Magus', 'Swashbuckler'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature within your reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it\'s using.',
  },
  {
    id: 'champion-shield-warden',
    name: 'Shield Warden',
    source: 'Champion',
    category: 'class',
    level: 6,
    description: 'When you have a shield raised, you can use your Shield Block reaction when an attack is made against an ally adjacent to you. If you do, the shield prevents that ally from taking damage instead of preventing you from taking damage, following the normal rules for Shield Block.',
    implemented: 'full',
    traits: ['Champion', 'Commander', 'Fighter'],
    actionCost: 'passive',
    prerequisites: ['Shield Block'],
  },
  // ── Level 8 Feats (7, including 1 shared) ──
  {
    id: 'champion-advanced-deitys-domain',
    name: 'Advanced Deity\'s Domain',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'Through your conviction, you have glimpsed the deeper secrets of your deity\'s domain. You gain the advanced domain spell for the domain you chose with Deity\'s Domain as a devotion spell.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Deity\'s Domain'],
  },
  {
    id: 'champion-greater-cruelty',
    name: 'Greater Cruelty',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'The extent of your corruption devastates your foes\' minds and reflexes. When using Cruelty, you can choose to make the target clumsy or stupefied instead of enfeebled. The value and duration remain the same.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Cruelty'],
  },
  {
    id: 'champion-greater-mercy',
    name: 'Greater Mercy',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'Your faith enhances your ability to remove conditions. You add the following conditions to those you can counteract with Mercy: drained, slowed, immobilized, paralyzed, and persistent damage. If you attempt to counteract persistent damage, choose one type of persistent damage affecting the target.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Mercy'],
  },
  {
    id: 'champion-greater-security',
    name: 'Greater Security',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'The ally with a companion shield from your Security uses your shield\'s AC bonus when they Raise the companion shield. You can use Shield Block for the ally as if you were the one wielding the companion shield.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Security'],
  },
  {
    id: 'champion-heal-mount',
    name: 'Heal Mount',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'When you use lay on hands on your mount, it restores 10 additional Hit Points, plus 10 for each heightened rank of lay on hands.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Faithful Steed', 'Lay on hands'],
  },
  {
    id: 'champion-second-blessing',
    name: 'Second Blessing',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'Choose a second blessing of the devoted option to gain in addition to your first.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Blessing of the devoted'],
    subChoices: { label: 'Choose a second blessing', options: [
      { id: 'blessed-armament', name: 'Blessed Armament', description: 'Gain critical specialization + scaling property rune on a weapon' },
      { id: 'blessed-shield', name: 'Blessed Shield', description: 'Shield gains scaling reinforcing rune' },
      { id: 'blessed-swiftness', name: 'Blessed Swiftness', description: '+5-foot status bonus to Speed' },
    ] },
  },
  {
    id: 'champion-quick-shield-block',
    name: 'Quick Shield Block',
    source: 'Champion',
    category: 'class',
    level: 8,
    description: 'You can bring your shield into place with hardly a thought. At the start of each of your turns, you gain an additional reaction that you can use only to Shield Block.',
    implemented: 'full',
    traits: ['Champion', 'Fighter'],
    actionCost: 'passive',
    prerequisites: ['Shield Block'],
  },
  // ── Level 10 Feats (4) ──
  {
    id: 'champion-imposing-destrier',
    name: 'Imposing Destrier',
    source: 'Champion',
    category: 'class',
    level: 10,
    description: 'Under your care, your mount has grown to become a particularly large and powerful specimen. Your mount becomes a nimble or savage animal companion (your choice). During an encounter, even if you don\'t use the Command an Animal action, your mount can still use 1 action on your turn that round to Stride or Step.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Loyal Warhorse'],
  },
  {
    id: 'champion-radiant-armament',
    name: 'Radiant Armament',
    source: 'Champion',
    category: 'class',
    level: 10,
    description: 'Add astral and brilliant to the list of property runes you can choose for your blessed armament. If you are holy, add holy to the list. If you are unholy, add unholy. You can swap your blessed armament\'s property rune as a 10-minute activity that has the concentrate and divine traits.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Blessed armament'],
  },
  {
    id: 'champion-shield-of-reckoning',
    name: 'Shield of Reckoning',
    source: 'Champion',
    category: 'class',
    level: 10,
    description: 'When an enemy attacks an ally within your champion\'s aura, you combine your Shield Block and your champion\'s reaction to protect them. Use Shield Block for the ally and apply effects of your champion\'s reaction simultaneously.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'reaction',
    prerequisites: ['Shield Warden', 'Blessed shield', 'Champion\'s reaction'],
    mechanics: 'Frequency: once per round.',
  },
  {
    id: 'champion-spectral-advance',
    name: 'Spectral Advance',
    source: 'Champion',
    category: 'class',
    level: 10,
    description: 'You gain the spectral advance devotion spell. This focus spell allows you to teleport a short distance, passing through obstacles, appearing in an unoccupied space.',
    implemented: 'full',
    traits: ['Champion', 'Concentrate', 'Divine', 'Teleportation'],
    actionCost: 'passive',
    prerequisites: ['Blessed swiftness'],
  },
  // ── Level 12 Feats (7) ──
  {
    id: 'champion-affliction-mercy',
    name: 'Affliction Mercy',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'Add the mercy of recuperation to your mercy types. When you select this mercy type, you can attempt to counteract a curse, disease, or poison affecting the target.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Mercy'],
  },
  {
    id: 'champion-aura-of-faith',
    name: 'Aura of Faith',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'Willing allies in your aura add holy (if you are holy) or unholy (if you are unholy) to their Strikes.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Holy or unholy'],
  },
  {
    id: 'champion-blessed-counterstrike',
    name: 'Blessed Counterstrike',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'You call upon divine power and make a weapon or unarmed Strike against the enemy who triggered your champion\'s reaction. On a hit, this Strike deals an extra damage die; the target also gains weakness to all Strikes from you and your allies until the start of your next turn.',
    implemented: 'full',
    traits: ['Champion', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Champion\'s reaction that grants an ally resistance to an enemy\'s damage (grandeur, justice, liberation, or redemption causes)'],
    mechanics: 'Requirements: An enemy triggered your champion\'s reaction since the end of your last turn.',
  },
  {
    id: 'champion-champions-sacrifice',
    name: 'Champion\'s Sacrifice',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'You form a link with an ally, allowing you to take harm in their stead. You gain the champion\'s sacrifice devotion spell.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Not unholy'],
  },
  {
    id: 'champion-devoted-focus',
    name: 'Devoted Focus',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'When you Refocus, you completely refill your focus pool (instead of recovering just 1 Focus Point).',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Devotion spells'],
  },
  {
    id: 'champion-divine-wall',
    name: 'Divine Wall',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'The squares adjacent to you are difficult terrain for enemies.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    mechanics: 'Requirements: You are wielding a shield.',
  },
  {
    id: 'champion-gruesome-strike',
    name: 'Gruesome Strike',
    source: 'Champion',
    category: 'class',
    level: 12,
    description: 'Make a Strike against the creature that triggered your champion\'s reaction. If the Strike hits, the extra damage from your champion\'s reaction is doubled. The target must also attempt a Fortitude save or become drained 1.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 1,
    prerequisites: ['Champion\'s reaction that grants extra damage with your Strikes (desecration, iniquity, or obedience causes)'],
    mechanics: 'Requirements: Your Strikes currently deal extra damage from your champion\'s reaction.',
  },
  // ── Level 14 Feats (4) ──
  {
    id: 'champion-aura-of-determination',
    name: 'Aura of Determination',
    source: 'Champion',
    category: 'class',
    level: 14,
    description: 'Your aura protects against powers that would twist the mind and body. You and all allies in your champion\'s aura gain a +1 status bonus to saving throws against mental, morph, and polymorph effects.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s aura'],
  },
  {
    id: 'champion-aura-of-life',
    name: 'Aura of Life',
    source: 'Champion',
    category: 'class',
    level: 14,
    description: 'Your aura protects against the power of the Void. You and all allies in your champion\'s aura gain resistance 5 to void damage and a +1 status bonus to saves against void effects.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s aura'],
  },
  {
    id: 'champion-aura-of-righteousness',
    name: 'Aura of Righteousness',
    source: 'Champion',
    category: 'class',
    level: 14,
    description: 'Your righteous aura dampens evil\'s might and prevents the unholy from escaping you. You and all allies in your champion\'s aura gain resistance 5 to unholy spells, unholy Strikes, and other unholy effects. If a teleportation spell or effect would teleport an unholy creature out of your champion\'s aura, your aura attempts to counteract it, using the spell rank and DC of your devotion spells.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s aura', 'Holy'],
  },
  {
    id: 'champion-divine-reflexes',
    name: 'Divine Reflexes',
    source: 'Champion',
    category: 'class',
    level: 14,
    description: 'At the start of each of your turns, you gain an additional reaction that you can use only for your champion\'s reaction.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  // ── Level 16 Feats (4) ──
  {
    id: 'champion-auspicious-mount',
    name: 'Auspicious Mount',
    source: 'Champion',
    category: 'class',
    level: 16,
    description: 'Guided by your ongoing care, your steed has developed incredible intelligence and skill. The mount you gained with Faithful Steed is now a specialized animal companion. You can select one of the usual specializations or the auspice specialization, which grants: celestial, fiend, or monitor trait (matching your deity\'s servitors), plus holy or unholy; Intelligence +2, Wisdom +1; Religion proficiency to expert; speaks servitor language; max HP +20 (25 at 18th, 30 at 20th) with subtype bonuses; and wings granting a fly Speed equal to land Speed.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Imposing Destrier'],
  },
  {
    id: 'champion-instrument-of-slaughter',
    name: 'Instrument of Slaughter',
    source: 'Champion',
    category: 'class',
    level: 16,
    description: 'Your blessed armament thirsts for the blood of your foes. Whenever you critically hit an enemy with a Strike that has the extra damage from your champion\'s reaction, the target also takes persistent bleed damage equal to two of the weapon\'s damage dice.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s reaction that grants extra damage with your Strikes (desecration, iniquity, or obedience causes)'],
  },
  {
    id: 'champion-instrument-of-zeal',
    name: 'Instrument of Zeal',
    source: 'Champion',
    category: 'class',
    level: 16,
    description: 'Divine energy fills your weapon. Whenever you critically hit an enemy with Blessed Counterstrike or Retributive Strike, your attack deals an extra weapon damage die, and the target is slowed 1 on its next turn.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Blessed Counterstrike or Retributive Strike', 'Champion\'s reaction that grants an ally resistance (grandeur, justice, liberation, or redemption causes)'],
  },
  {
    id: 'champion-shield-of-grace',
    name: 'Shield of Grace',
    source: 'Champion',
    category: 'class',
    level: 16,
    description: 'You protect an ally with both your shield and your body. Whenever you use the Shield Block reaction to prevent damage to an ally, you can evenly split the remaining damage after the Shield Block between the ally and yourself.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Shield Warden'],
  },
  // ── Level 18 Feats (3) ──
  {
    id: 'champion-rejuvenating-touch',
    name: 'Rejuvenating Touch',
    source: 'Champion',
    category: 'class',
    level: 18,
    description: 'Your healing energies linger after you cast, providing continual benefits. An ally that recovers Hit Points from your lay on hands gains 10 temporary Hit Points immediately and at the start of their turn during each of the next 10 rounds. These temporary HP last until the start of the creature\'s next turn. This effect ends if the ally is knocked unconscious.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Lay on hands'],
  },
  {
    id: 'champion-swift-retribution',
    name: 'Swift Retribution',
    source: 'Champion',
    category: 'class',
    level: 18,
    description: 'The transgressions of your enemies fuel you to retaliate with divine speed. When an enemy triggers your champion\'s reaction, you are quickened on your next turn. You can use the extra action to move closer to that enemy or to Strike that enemy.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Champion\'s reaction'],
  },
  {
    id: 'champion-ultimate-mercy',
    name: 'Ultimate Mercy',
    source: 'Champion',
    category: 'class',
    level: 18,
    description: 'Your mercy transcends the bounds of life and death. Add ultimate mercy to the types of mercy you can provide. When you use Mercy, you can target a creature that died since your last turn to return it to life. The target returns to life with 1 Hit Point and becomes wounded 1. You can\'t return the target to life if it died from disintegrate or a death effect. The creature gains the other benefits of lay on hands after it returns to life.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Mercy'],
  },
  // ── Level 20 Feats (4) ──
  {
    id: 'champion-armament-paragon',
    name: 'Armament Paragon',
    source: 'Champion',
    category: 'class',
    level: 20,
    description: 'Add the following property runes to the list you can choose for your blessed armament: animated, greater fearsome, grievous, keen, and greater vitalizing. If you have the Radiant Armament feat, add greater astral and greater brilliant to the list as well. In addition, you can change the rune you\'ve selected for the day to a different rune from your list as a single action that has the concentrate and divine traits. Changing the rune doesn\'t restore abilities that can be used only a limited number of times.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Blessed armament'],
  },
  {
    id: 'champion-sacred-defender',
    name: 'Sacred Defender',
    source: 'Champion',
    category: 'class',
    level: 20,
    description: 'You are a great warrior that can stand strong against the fiercest opponents to your cause. You gain resistance 5 to bludgeoning, piercing, and slashing damage. If you\'re holy, this resistance increases to 10 against unholy creatures, and if you\'re unholy it increases to 10 against holy creatures. In addition, creatures and effects that roll a natural 20 on an attack roll against you don\'t improve their result by one degree of success.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
  },
  {
    id: 'champion-shield-paragon',
    name: 'Shield Paragon',
    source: 'Champion',
    category: 'class',
    level: 20,
    description: 'Your shield is a vessel of divine protection. When you\'re wielding your chosen shield, it is always raised, even without you using the Raise a Shield action. If the shield would be destroyed, it vanishes to your deity\'s realm instead, where a servitor of your deity repairs it. During your next daily preparations, the shield returns to you fully repaired. While the shield is gone, you can spend 1 minute to infuse a different shield with your blessed shield benefit until your true shield returns.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Blessed shield'],
  },
  {
    id: 'champion-swift-paragon',
    name: 'Swift Paragon',
    source: 'Champion',
    category: 'class',
    level: 20,
    description: 'The movement of you and your allies is swift and decisive as the judgment of your deity. If your ally starts a move action in your champion\'s aura, their movement during that action doesn\'t trigger reactions. In addition, you\'re permanently quickened. You can use your extra action only to Step or Stride. If you have a fly Speed, add Fly to this list. If you have an animal companion and are mounted on it at the start of your turn, you can have your mount be quickened that turn instead of you.',
    implemented: 'full',
    traits: ['Champion'],
    actionCost: 'passive',
    prerequisites: ['Blessed swiftness'],
  },
];
