/**
 * Cleric Class Features & Feats — PF2e Remastered (Player Core)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=5
 *
 * Key Attribute: WIS | HP: 8 + CON
 * Perception: Trained → Expert (L5, Perception Expertise)
 * Fort: Trained
 * Reflex: Trained → Expert (L11, Reflex Expertise)
 * Will: Expert → Master (L9, Resolute Faith, success→crit)
 * Weapons: Trained simple weapons + deity's favored weapon
 * Armor: Trained unarmored (Warpriest: Trained light/medium)
 * Spellcasting: Divine prepared — Trained spell attack/DC
 *
 * Doctrines (Player Core):
 *   Cloistered Cleric — scholarly divine magic focus
 *   Warpriest — martial prowess + divine power
 *
 * Divine Font: 4 additional spell slots at highest rank (heal or harm).
 *   5 slots at L5, 6 slots at L15.
 *
 * Class features: 10 (L1–L19)
 * Class feats: 69 PC feats (AoN IDs 4642–4707 + shared 4577, 4580, 4602)
 */

import type { FeatEntry } from './featTypes';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
} from './sharedFeats';

// ──────────────────────────────────────────────────────────
// CLERIC CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const CLERIC_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'cleric-deity',
    name: 'Deity',
    source: 'Cleric',
    category: 'class_feature',
    level: 1,
    description: 'As a cleric, you are a mortal conduit for your deity\'s power. Choose a deity to worship. Your deity grants you a trained divine skill, determines your divine font (heal or harm), sanctions your holy or unholy trait (if any), and provides domains and an anathema you must uphold. You become trained in your deity\'s favored weapon; if it is an uncommon weapon, you also gain access to it. You also become trained in Religion.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Determines favored weapon, divine skill, domains, sanctification (holy/unholy/none), divine font (heal or harm), and anathema.',
    subChoices: { label: 'Choose a deity', options: [
      { id: 'abadar', name: 'Abadar', description: 'LN — Cities, Law, Merchants, Wealth' },
      { id: 'calistria', name: 'Calistria', description: 'CN — Lust, Revenge, Trickery' },
      { id: 'cayden-cailean', name: 'Cayden Cailean', description: 'CG — Ale, Bravery, Freedom' },
      { id: 'desna', name: 'Desna', description: 'CG — Dreams, Luck, Stars, Travel' },
      { id: 'erastil', name: 'Erastil', description: 'LG — Family, Farming, Hunting' },
      { id: 'gorum', name: 'Gorum', description: 'CN — Battle, Strength, Weapons' },
      { id: 'gozreh', name: 'Gozreh', description: 'N — Nature, Sea, Weather' },
      { id: 'iomedae', name: 'Iomedae', description: 'LG — Honor, Justice, Valor' },
      { id: 'irori', name: 'Irori', description: 'LN — Knowledge, Perfection, Self-Improvement' },
      { id: 'lamashtu', name: 'Lamashtu', description: 'CE — Madness, Monsters, Nightmares' },
      { id: 'nethys', name: 'Nethys', description: 'N — Magic' },
      { id: 'norgorber', name: 'Norgorber', description: 'NE — Greed, Murder, Poison, Secrets' },
      { id: 'pharasma', name: 'Pharasma', description: 'N — Birth, Death, Fate, Prophecy' },
      { id: 'rovagug', name: 'Rovagug', description: 'CE — Destruction, Disaster, Wrath' },
      { id: 'sarenrae', name: 'Sarenrae', description: 'NG — Healing, Honesty, Redemption, Sun' },
      { id: 'shelyn', name: 'Shelyn', description: 'NG — Art, Beauty, Love, Music' },
      { id: 'torag', name: 'Torag', description: 'LG — Forge, Protection, Strategy' },
      { id: 'urgathoa', name: 'Urgathoa', description: 'NE — Disease, Gluttony, Undeath' },
      { id: 'zon-kuthon', name: 'Zon-Kuthon', description: 'LE — Darkness, Envy, Loss, Pain' },
      { id: 'other', name: 'Other Deity', description: 'A deity not listed above' },
    ] },
  },
  {
    id: 'cleric-divine-spellcasting',
    name: 'Cleric Spellcasting',
    source: 'Cleric',
    category: 'class_feature',
    level: 1,
    description: 'Through your deity\'s blessing, you can cast divine spells using the Cast a Spell activity. As a prepared divine spellcaster, you must prepare spells each morning from the divine spell list. At 1st level, you can prepare two 1st-rank spells and five cantrips each morning. As your level increases, so do the number of spells per day and the highest rank of spell you can cast. Your spellcasting attribute is Wisdom.',
    implemented: 'full',
    traits: ['Cleric', 'Divine'],
    actionCost: 'passive',
    mechanics: 'Divine prepared spellcaster. Key attribute: WIS. Trained spell attack / spell DC.',
  },
  {
    id: 'cleric-divine-font',
    name: 'Divine Font',
    source: 'Cleric',
    category: 'class_feature',
    level: 1,
    description: 'Through your deity\'s blessing, you gain additional spell slots that can be used only to cast heal or harm spells. You gain a healing font (extra heal slots) or harming font (extra harm slots), determined by your deity. You gain 4 additional spell slots each day at your highest rank of cleric spell slots. At 5th level, the number of additional slots increases to 5, and at 15th level, the total number of additional slots increases to 6.',
    implemented: 'full',
    traits: ['Cleric', 'Divine'],
    actionCost: 'passive',
    mechanics: 'Gain 4 extra spell slots (heal or harm only) at highest spell rank. 5 slots at L5, 6 slots at L15.',
    subChoices: { label: 'Choose a divine font', options: [
      { id: 'healing-font', name: 'Healing Font', description: 'Extra heal spell slots (determined by deity)' },
      { id: 'harming-font', name: 'Harming Font', description: 'Extra harm spell slots (determined by deity)' },
    ] },
  },
  {
    id: 'cleric-doctrine',
    name: 'Doctrine',
    source: 'Cleric',
    category: 'class_feature',
    level: 1,
    description: 'You follow a particular doctrine that determines the manner of your devotion. Choose a doctrine at 1st level: Cloistered Cleric (focused on divine spellcasting and spiritual knowledge) or Warpriest (combining martial prowess with divine power). Your doctrine grants additional benefits at 1st, 3rd, 7th, 11th, 15th, and 19th levels, affecting your proficiency progression in weapons, armor, fortitude saves, and spellcasting.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Builder must capture doctrine choice. Cloistered Cleric: faster spell DC/attack progression. Warpriest: better weapon/armor/Fort progression. Sub-features at L1, L3, L7, L11, L15, L19.',
    subChoices: { label: 'Choose a doctrine', options: [
      { id: 'cloistered-cleric', name: 'Cloistered Cleric', description: 'Focus on divine spellcasting and spiritual knowledge' },
      { id: 'warpriest', name: 'Warpriest', description: 'Combine martial prowess with divine power' },
    ] },
  },
  // ── Level 5 ──
  {
    id: 'cleric-perception-expertise',
    name: 'Perception Expertise',
    source: 'Cleric',
    category: 'class_feature',
    level: 5,
    description: 'You remain alert to threats around you. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
  },
  // ── Level 9 ──
  {
    id: 'cleric-resolute-faith',
    name: 'Resolute Faith',
    source: 'Cleric',
    category: 'class_feature',
    level: 9,
    description: 'You\'ve steeled your mind with incredible resolve. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Will → master. Success on Will saves becomes critical success.',
  },
  // ── Level 11 ──
  {
    id: 'cleric-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Cleric',
    category: 'class_feature',
    level: 11,
    description: 'Your reflexes are lightning fast, granting you better defenses against area effects. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
  },
  // ── Level 13 ──
  {
    id: 'cleric-divine-defense',
    name: 'Divine Defense',
    source: 'Cleric',
    category: 'class_feature',
    level: 13,
    description: 'Your training and target deity grant you additional defenses. Your proficiency rank for unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Unarmored defense → expert. Warpriest doctrine may grant additional armor proficiency increases.',
  },
  // Weapon Specialization (L13). Uses shared template.
  createClassFeature(WEAPON_SPECIALIZATION, 'Cleric', 13),
  // ── Level 19 ──
  {
    id: 'cleric-miraculous-spell',
    name: 'Miraculous Spell',
    source: 'Cleric',
    category: 'class_feature',
    level: 19,
    description: 'You are exalted by your deity and can channel truly miraculous spells. You gain a single 10th-rank spell slot and can prepare a spell in that slot using your divine spellcasting. You don\'t gain more 10th-rank spells as you level up, though you can take the Maker of Miracles feat to gain a second slot.',
    implemented: 'full',
    traits: ['Cleric', 'Divine'],
    actionCost: 'passive',
    mechanics: 'Gain a single 10th-rank spell slot. Prepare any divine spell in it during daily preparations.',
  },
];

// ──────────────────────────────────────────────────────────
// CLERIC CLASS FEATS (Selectable)
// 69 feats: 66 Cleric-exclusive + 3 shared (Reach Spell, Cantrip Expansion, Steady Spellcasting)
// ──────────────────────────────────────────────────────────

export const CLERIC_CLASS_FEATS: FeatEntry[] = [
  // ════════════════════════════════════════════════════════
  // ── Level 1 Feats (7) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-reach-spell',
    name: 'Reach Spell',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'You can extend the range of your spells. If the next action you use is to Cast a Spell that has a range, increase that spell\'s range by 30 feet. As is standard for increasing spell ranges, if the spell normally has a range of touch, you extend its range to 30 feet.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Concentrate', 'Druid', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  {
    id: 'cleric-deadly-simplicity',
    name: 'Deadly Simplicity',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'Your deity\'s weapon is especially dangerous in your hands. When you are wielding your deity\'s favored weapon, increase the damage die of that weapon by one step. If your deity\'s favored weapon is an unarmed attack (such as a fist) and its damage die is smaller than d6, instead increase its damage die to d6.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Increase deity favored weapon damage die by one step. Unarmed with die < d6 becomes d6.',
  },
  {
    id: 'cleric-divine-castigation',
    name: 'Divine Castigation',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'You extend the dominion of your faith with each spell you cast. When you damage a creature that has the opposing trait to your holy or unholy trait with a harm or heal spell, the target also takes 1 spirit damage per spell rank.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['holy or unholy trait'],
    mechanics: 'When damaging a creature with the opposing trait via harm/heal, deal +1 spirit damage per spell rank.',
  },
  {
    id: 'cleric-domain-initiate',
    name: 'Domain Initiate',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'Your deity bestows a special spell related to their powers. Select one domain offered by your deity. You gain an initial domain spell for that domain, a type of focus spell. It costs 1 Focus Point to cast a focus spell. Your focus pool increases by 1 Focus Point.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Select one deity domain → gain initial domain spell (focus spell). Focus pool +1. Can select multiple times for different domains.',
    subChoices: { label: 'Choose a domain', options: [
      { id: 'ambition', name: 'Ambition' },
      { id: 'change', name: 'Change' },
      { id: 'cities', name: 'Cities' },
      { id: 'confidence', name: 'Confidence' },
      { id: 'creation', name: 'Creation' },
      { id: 'darkness', name: 'Darkness' },
      { id: 'death', name: 'Death' },
      { id: 'destruction', name: 'Destruction' },
      { id: 'dreams', name: 'Dreams' },
      { id: 'duty', name: 'Duty' },
      { id: 'earth', name: 'Earth' },
      { id: 'family', name: 'Family' },
      { id: 'fate', name: 'Fate' },
      { id: 'fire', name: 'Fire' },
      { id: 'freedom', name: 'Freedom' },
      { id: 'healing', name: 'Healing' },
      { id: 'indulgence', name: 'Indulgence' },
      { id: 'knowledge', name: 'Knowledge' },
      { id: 'luck', name: 'Luck' },
      { id: 'magic', name: 'Magic' },
      { id: 'might', name: 'Might' },
      { id: 'moon', name: 'Moon' },
      { id: 'nature', name: 'Nature' },
      { id: 'nightmares', name: 'Nightmares' },
      { id: 'pain', name: 'Pain' },
      { id: 'passion', name: 'Passion' },
      { id: 'perfection', name: 'Perfection' },
      { id: 'protection', name: 'Protection' },
      { id: 'secrecy', name: 'Secrecy' },
      { id: 'sun', name: 'Sun' },
      { id: 'travel', name: 'Travel' },
      { id: 'trickery', name: 'Trickery' },
      { id: 'truth', name: 'Truth' },
      { id: 'undeath', name: 'Undeath' },
      { id: 'war', name: 'War' },
      { id: 'water', name: 'Water' },
      { id: 'wealth', name: 'Wealth' },
      { id: 'zeal', name: 'Zeal' },
    ] },
  },
  {
    id: 'cleric-harming-hands',
    name: 'Harming Hands',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'The divine energy you channel is especially harmful. When you cast harm, you roll d10s instead of d8s.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['harming font'],
    mechanics: 'When casting harm, roll d10s instead of d8s.',
  },
  {
    id: 'cleric-healing-hands',
    name: 'Healing Hands',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'Your healing is especially potent. When you cast heal, you roll d10s instead of d8s.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['healing font'],
    mechanics: 'When casting heal, roll d10s instead of d8s.',
  },
  {
    id: 'cleric-premonition-of-avoidance',
    name: 'Premonition of Avoidance',
    source: 'Cleric',
    category: 'class',
    level: 1,
    description: 'Your deity grants you advance warning of danger. You gain a +2 circumstance bonus to Perception and to saving throws against hazards.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: '+2 circumstance bonus to Perception and saves vs hazards.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 2 Feats (8) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'A greater understanding of your magic broadens your range of simple spells. You can prepare two additional cantrips each day.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Prepare 2 additional cantrips each day.',
  },
  {
    id: 'cleric-communal-healing',
    name: 'Communal Healing',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'You\'re a conduit for vitality, and as you channel it through you, it heals you as well. When you cast the heal spell to heal a single creature other than yourself, you regain Hit Points equal to the spell\'s rank.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['healing font'],
    mechanics: 'When casting heal on a single creature (not yourself), you regain HP equal to spell rank.',
  },
  {
    id: 'cleric-emblazon-armament',
    name: 'Emblazon Armament',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'Carefully etching a symbol of your deity onto a shield or weapon (an Exploration activity taking 10 minutes), you create a religious emblem. You can have up to four items emblazoned at a time. If you exceed this limit, the symbol on the oldest item fades. Choose one of the following benefits: Shield — The shield\'s Hardness increases by 1 (this doesn\'t increase the shield\'s HP or BT). Weapon — The wielder gains a +1 status bonus to damage rolls.',
    implemented: 'full',
    traits: ['Cleric', 'Exploration'],
    actionCost: 'passive',
    mechanics: 'Exploration activity (10 min). Up to 4 items. Shield: Hardness +1. Weapon: +1 status to damage.',
    subChoices: { label: 'Choose emblazon benefit', options: [
      { id: 'shield', name: 'Shield', description: 'Hardness +1' },
      { id: 'weapon', name: 'Weapon', description: '+1 status bonus to damage' },
    ] },
  },
  {
    id: 'cleric-panic-the-dead',
    name: 'Panic the Dead',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'Undead ones tremble at the sight of your faith. You can use your divine font to Panic the Dead. When you present your religious symbol and expend one use of your divine font, each undead creature within a 30-foot emanation must attempt a Will save against your spell DC. Critical Success: The creature is unaffected. Success: The creature is frightened 1. Failure: The creature is frightened 2. Critical Failure: The creature is frightened 3 and fleeing for 1 round.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Expend divine font slot. 30-ft emanation. Undead Will save: Success=frightened 1, Failure=frightened 2, Crit Fail=frightened 3 + fleeing 1 round.',
  },
  {
    id: 'cleric-rapid-response',
    name: 'Rapid Response',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'You channel your divine power with unusual speed, throwing out healing or harm in situations where doing so at full power isn\'t possible. When you cast a 2-action heal or harm spell, you can reduce the number of actions to 1. If you do, the spell is 2 ranks lower than normal (minimum 1st rank).',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Reduce 2-action heal/harm to 1 action at –2 spell rank (minimum 1st rank).',
  },
  {
    id: 'cleric-sap-life',
    name: 'Sap Life',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'You draw the life force from creatures you harm. When you cast a harm spell and damage at least one living creature, you regain Hit Points equal to the spell\'s rank.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['harming font'],
    mechanics: 'When harm damages a living creature, regain HP equal to spell rank.',
  },
  {
    id: 'cleric-versatile-font',
    name: 'Versatile Font',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'As you are equally devout and devoted, you can access your healing or harming power in both forms. You can prepare some of your extra slots from your divine font with heal spells and some with harm spells, as you choose. This doesn\'t change the number of extra spell slots from your divine font.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['harmful font or healing font'],
    mechanics: 'Mix heal and harm in divine font slots. Total slot count unchanged.',
  },
  {
    id: 'cleric-warpriests-armor',
    name: 'Warpriest\'s Armor',
    source: 'Cleric',
    category: 'class',
    level: 2,
    description: 'Your training has improved your use of armor. You gain the armor specialization effects of medium armor. If you have expert proficiency in any weapon or unarmed attacks, you also gain access to the critical specialization effect for those weapons and unarmed attacks.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['warpriest doctrine'],
    mechanics: 'Gain medium armor specialization effects. Expert weapon/unarmed proficiency → crit specialization access.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 4 Feats (6) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-channel-smite',
    name: 'Channel Smite',
    source: 'Cleric',
    category: 'class',
    level: 4,
    description: 'You siphon the destructive energies of positive or negative energy through a melee attack. Make a melee Strike. On a hit, the Strike deals an additional amount of vitality or void damage equal to 1d8 per rank of your highest-rank spell slot, and the target must attempt a basic Fortitude save against your spell DC with this damage. On a critical hit, the target\'s save result is one degree worse.',
    implemented: 'full',
    traits: ['Cleric', 'Divine'],
    actionCost: 2,
    prerequisites: ['harmful font or healing font'],
    mechanics: '2 actions. Melee Strike + 1d8 per highest spell rank vitality/void damage. Target basic Fort save. Crit hit → save degree worse.',
  },
  {
    id: 'cleric-directed-channel',
    name: 'Directed Channel',
    source: 'Cleric',
    category: 'class',
    level: 4,
    description: 'You can shape the directed power of your channeled energy. When you cast a harmful or healing version of a 2-action harm or heal that has an area, you can change the area to a 60-foot cone instead of a 30-foot emanation.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: '2-action harm/heal area → 60-foot cone instead of 30-foot emanation.',
  },
  {
    id: 'cleric-divine-infusion',
    name: 'Divine Infusion',
    source: 'Cleric',
    category: 'class',
    level: 4,
    description: 'You carry the blessing of your deity, infusing your actions with their authority. You can cast the infuse vitality or infuse void spell (whichever matches your divine font) as a divine innate spell. The rank of the spell is half your level, rounded up.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Cast infuse vitality or infuse void (matching font) as divine innate spell at rank = half level (rounded up).',
  },
  {
    id: 'cleric-raise-symbol',
    name: 'Raise Symbol',
    source: 'Cleric',
    category: 'class',
    level: 4,
    description: 'You hold up your religious symbol in a defiant gesture. You raise your religious symbol, which has the same effects as Raising a Shield (giving you a +1 circumstance bonus to AC until the start of your next turn) except that you must be holding your religious symbol rather than a shield. The religious symbol has Hardness 4, HP 16, and BT 8 while raised (its actual physical HP doesn\'t change). If your religious symbol is a shield, you can use Raise a Shield instead.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 1,
    mechanics: '1 action. Raise religious symbol like a shield: +1 circumstance AC. Symbol has Hardness 4, HP 16, BT 8 while raised.',
  },
  {
    id: 'cleric-restorative-strike',
    name: 'Restorative Strike',
    source: 'Cleric',
    category: 'class',
    level: 4,
    description: 'You balance both sides of the scales, restoring yourself while striking a foe. Cast a 1-action harm or heal spell to heal yourself, expending the spell normally. It loses the manipulate trait when cast this way. Then make a melee Strike. If you make this Strike with your deity\'s favored weapon, you gain a +1 status bonus to the attack roll. If the Strike hits, you can target a second willing creature to heal the same amount from the spell. This creature can be outside of the spell\'s range, provided it\'s adjacent to the enemy you hit.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 2,
    mechanics: '2 actions. Cast 1-action harm/heal on self (loses manipulate) + melee Strike. Deity weapon: +1 status to attack. On hit: can heal adjacent ally same amount.',
  },
  {
    id: 'cleric-sacred-ground',
    name: 'Sacred Ground',
    source: 'Cleric',
    category: 'class',
    level: 4,
    description: 'Your faith can consecrate an entire area against your enemies\' ideology. You gain the sacred ground focus spell. Increase the number of Focus Points in your pool by 1.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Gain sacred ground focus spell. Focus pool +1.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 6 Feats (6) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Cleric',
    category: 'class',
    level: 6,
    description: 'You don\'t lose spells easily. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn\'t disrupted.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Druid', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'DC 15 flat check to avoid disruption from reactions during spellcasting.',
  },
  {
    id: 'cleric-cast-down',
    name: 'Cast Down',
    source: 'Cleric',
    category: 'class',
    level: 6,
    description: 'The weight of your deity\'s displeasure forces sinners to bow before you. If the next action you use is to cast harm targeting one creature, the target is also knocked prone on a failure or critical failure against the save (in addition to the normal effects of the spell).',
    implemented: 'full',
    traits: ['Cleric', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['harmful font'],
    mechanics: '1-action Spellshape. Next harm (single target) also knocks target prone on failure/crit failure.',
  },
  {
    id: 'cleric-divine-rebuttal',
    name: 'Divine Rebuttal',
    source: 'Cleric',
    category: 'class',
    level: 6,
    description: 'You call upon your deity to shatter the divine power protecting your enemy\'s spell. Attempt to counteract the triggering spell using your spell attack modifier or spell DC – 10.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'reaction',
    mechanics: 'Reaction. Trigger: An enemy within 60 feet casts a divine spell. Counteract using spell attack modifier or spell DC – 10.',
  },
  {
    id: 'cleric-divine-weapon',
    name: 'Divine Weapon',
    source: 'Cleric',
    category: 'class',
    level: 6,
    description: 'Your arsenal of faith extends to sanctified weaponry. If you worship a deity, the weapon gains the effect of a striking rune. When wielding your deity\'s favored weapon and you have dealt damage with that weapon on this turn, you gain a +1 status bonus to AC until the start of your next turn.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Deity favored weapon gains striking rune effect. After dealing damage with it this turn: +1 status AC until next turn.',
  },
  {
    id: 'cleric-magic-hands',
    name: 'Magic Hands',
    source: 'Cleric',
    category: 'class',
    level: 6,
    description: 'The blessing of your deity heightens your healing ability, integrating magical healing with the mundane. When you succeed at a Medicine check to Treat Wounds, you can roll d10s instead of d8s for the healing and add a status bonus to the healing equal to your level.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Healing Hands'],
    mechanics: 'Treat Wounds: d10s instead of d8s + status bonus to healing equal to level.',
  },
  {
    id: 'cleric-selective-energy',
    name: 'Selective Energy',
    source: 'Cleric',
    category: 'class',
    level: 6,
    description: 'As you call down divine power, you can prevent some enemies from benefiting or some allies from being hurt. When you cast a version of harm or heal that has an area, you can designate up to 5 creatures in the area. They are not targeted by the spell.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'When casting area harm/heal, exclude up to 5 creatures from the target list.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 8 Feats (9) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-advanced-domain',
    name: 'Advanced Domain',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'Your prayers have unlocked deeper secrets of your deity\'s domain. You gain an advanced domain spell from one of your domains for which you have an initial domain spell.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Domain Initiate'],
    mechanics: 'Gain advanced domain spell from one domain with initial spell. Can select multiple times for different domains.',
    subChoices: { label: 'Choose domain', options: [
      { id: 'air', name: 'Air' }, { id: 'ambition', name: 'Ambition' },
      { id: 'change', name: 'Change' }, { id: 'cities', name: 'Cities' },
      { id: 'confidence', name: 'Confidence' }, { id: 'creation', name: 'Creation' },
      { id: 'darkness', name: 'Darkness' }, { id: 'death', name: 'Death' },
      { id: 'destruction', name: 'Destruction' }, { id: 'dreams', name: 'Dreams' },
      { id: 'earth', name: 'Earth' }, { id: 'family', name: 'Family' },
      { id: 'fate', name: 'Fate' }, { id: 'fire', name: 'Fire' },
      { id: 'freedom', name: 'Freedom' }, { id: 'healing', name: 'Healing' },
      { id: 'indulgence', name: 'Indulgence' }, { id: 'knowledge', name: 'Knowledge' },
      { id: 'lightning', name: 'Lightning' }, { id: 'luck', name: 'Luck' },
      { id: 'magic', name: 'Magic' }, { id: 'might', name: 'Might' },
      { id: 'moon', name: 'Moon' }, { id: 'nature', name: 'Nature' },
      { id: 'nightmares', name: 'Nightmares' }, { id: 'pain', name: 'Pain' },
      { id: 'passion', name: 'Passion' }, { id: 'perfection', name: 'Perfection' },
      { id: 'protection', name: 'Protection' }, { id: 'secrecy', name: 'Secrecy' },
      { id: 'sun', name: 'Sun' }, { id: 'travel', name: 'Travel' },
      { id: 'trickery', name: 'Trickery' }, { id: 'truth', name: 'Truth' },
      { id: 'tyranny', name: 'Tyranny' }, { id: 'undeath', name: 'Undeath' },
      { id: 'vigil', name: 'Vigil' }, { id: 'void', name: 'Void' },
      { id: 'water', name: 'Water' }, { id: 'wealth', name: 'Wealth' },
      { id: 'wyrmkin', name: 'Wyrmkin' }, { id: 'zeal', name: 'Zeal' },
    ] },
  },
  {
    id: 'cleric-cremate-undead',
    name: 'Cremate Undead',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'Your overwhelming vitality sets undead alight. When you use a heal spell to damage undead, each undead that takes damage also takes persistent fire damage equal to the spell\'s rank.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'When heal damages undead, each damaged undead takes persistent fire damage equal to spell rank.',
  },
  {
    id: 'cleric-emblazon-energy',
    name: 'Emblazon Energy',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'With elemental forces, you make your emblazoned symbols more potent. When you Emblazon an Armament, you can choose from the following effects instead of the effects listed in that feat. Shield: Choose acid, cold, electricity, fire, or sonic. The wielder gains the shield\'s circumstance bonus to saving throws against that damage type and can use Shield Block against damage of that type. The shield also gains resistance to that damage type equal to half your level if you have a domain spell with a trait matching that type. Weapon: Choose acid, cold, electricity, fire, or sonic. The weapon deals an extra 1d4 damage of that type. Increase this extra damage to 1d6 if you have a domain spell with a trait matching that type.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Emblazon Armament'],
    mechanics: 'Emblazon Armament alternate effects. Shield: circumstance bonus to saves vs chosen energy type + Shield Block vs it + resistance if matching domain. Weapon: +1d4 chosen energy damage (+1d6 with matching domain).',
    subChoices: { label: 'Choose an energy type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'sonic', name: 'Sonic' },
    ] },
  },
  {
    id: 'cleric-martyr',
    name: 'Martyr',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'You go to extreme lengths to support your allies, even when it means bringing harm to yourself. If your next action is to cast harm or heal to restore Hit Points to a single ally, you can channel your own vitality along with the spell. You lose 1d8 Hit Points per rank of the spell, which can\'t be reduced or mitigated in any way, and your ally regains an equal number of Hit Points.',
    implemented: 'full',
    traits: ['Cleric', 'Spellshape'],
    actionCost: 1,
    mechanics: '1-action Spellshape. Lose 1d8 HP per spell rank (unpreventable). Ally regains equal HP on top of spell healing.',
  },
  {
    id: 'cleric-restorative-channel',
    name: 'Restorative Channel',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'You can remove conditions with divine grace. You can sacrifice one heal spell you\'ve prepared in your extra slots from your healing font to cast one of the following spells instead: cleanse affliction, clear mind, sound body, or sure footing. The spell is heightened to the same rank as the spell you sacrificed.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['healing font'],
    mechanics: 'Sacrifice a healing font heal slot → cast cleanse affliction, clear mind, sound body, or sure footing at same rank.',
  },
  {
    id: 'cleric-sanctify-armament',
    name: 'Sanctify Armament',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'You touch a weapon and bring it into concordance with your deity. For 1 round, that weapon gains your holy or unholy trait. It also deals an additional 2d6 spirit damage to creatures of the opposed trait. If you use Sanctify Armament again, any previous use of it expires.',
    implemented: 'full',
    traits: ['Cleric', 'Divine'],
    actionCost: 1,
    prerequisites: ['holy or unholy trait'],
    mechanics: '1 action. Touched weapon gains holy/unholy trait for 1 round + 2d6 spirit damage vs opposed trait creatures.',
  },
  {
    id: 'cleric-surging-focus',
    name: 'Surging Focus',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'You draw upon your reserves to channel more divine energy. If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Spent 2+ FP since last Refocus → recover 2 FP on Refocus.',
  },
  {
    id: 'cleric-void-siphon',
    name: 'Void Siphon',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'The raw energy of the Void saps the essence of the living. Any living creature that critically fails its save against a harm spell you cast is drained 1.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Living creatures that crit fail vs your harm are drained 1.',
  },
  {
    id: 'cleric-zealous-rush',
    name: 'Zealous Rush',
    source: 'Cleric',
    category: 'class',
    level: 8,
    description: 'You bless yourself on the move. Stride up to 10 feet. If the spell took 2 or more actions, you can Stride up to your full Speed instead.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'reaction',
    mechanics: 'Reaction. Trigger: You cast a divine spell (1+ actions) that affects only you/your equipment. Stride up to 10 ft (or full Speed if spell was 2+ actions).',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 10 Feats (5) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-castigating-weapon',
    name: 'Castigating Weapon',
    source: 'Cleric',
    category: 'class',
    level: 10,
    description: 'The force of your deity\'s castigation strengthens your body so you can strike down the enemy and its allies. After you deal spirit damage due to Divine Castigation, your weapon or unarmed Strikes gain your holy or unholy trait and deal additional spirit damage until the end of your turn. The spirit damage is equal to the rank of harm or heal you dealt spirit damage with, and is in addition to any spirit damage the weapon already deals (such as from a holy rune).',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Divine Castigation'],
    mechanics: 'After dealing spirit damage via Divine Castigation, Strikes gain holy/unholy + bonus spirit damage equal to spell rank until end of turn.',
  },
  {
    id: 'cleric-heroic-recovery',
    name: 'Heroic Recovery',
    source: 'Cleric',
    category: 'class',
    level: 10,
    description: 'The restorative power of your healing invigorates the recipient. If the next action you use is to cast heal targeting a single living creature and the target regains Hit Points from the spell, the target also gains three bonuses until the end of its next turn: a +5-foot status bonus to its Speed, a +1 status bonus to attack rolls, and a +1 status bonus to damage rolls. In addition, if the target is prone, it can immediately Stand as a free action that doesn\'t trigger reactions.',
    implemented: 'full',
    traits: ['Cleric', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['healing font'],
    mechanics: '1-action Spellshape. Next single-target heal: target gains +5 ft Speed, +1 attack, +1 damage until end of next turn. If prone, free Stand.',
  },
  {
    id: 'cleric-replenishment-of-war',
    name: 'Replenishment of War',
    source: 'Cleric',
    category: 'class',
    level: 10,
    description: 'Throwing yourself into battle renews your divine connection. When you damage a creature with a Strike using your deity\'s favored weapon, you regain 1 Focus Point. You can gain no more than 1 Focus Point per 10 minutes this way.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Damage with deity favored weapon → regain 1 FP. Max 1 FP per 10 minutes.',
  },
  {
    id: 'cleric-shared-avoidance',
    name: 'Shared Avoidance',
    source: 'Cleric',
    category: 'class',
    level: 10,
    description: 'You can project your premonitions of danger to your allies. When you use Premonition of Avoidance, allies within 20 feet of you who are rolling the same saving throw against the same hazard also gain a +2 circumstance bonus to their saving throws.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Premonition of Avoidance'],
    mechanics: 'Allies within 20 ft also gain +2 circumstance bonus to saves vs same hazard.',
  },
  {
    id: 'cleric-shield-of-faith',
    name: 'Shield of Faith',
    source: 'Cleric',
    category: 'class',
    level: 10,
    description: 'Your deity protects you with a blazing shield of divine energy. You gain the shield of faith focus spell. Increase the number of Focus Points in your pool by 1.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Gain shield of faith focus spell. Focus pool +1.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 12 Feats (6) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-defensive-recovery',
    name: 'Defensive Recovery',
    source: 'Cleric',
    category: 'class',
    level: 12,
    description: 'Your healing spells bolster the target\'s defenses. If the next action you use is to cast harm or heal on a single target and the target regains Hit Points from the spell, it also gains a +2 status bonus to AC and saving throws for 1 round.',
    implemented: 'full',
    traits: ['Cleric', 'Concentrate', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['harmful font or healing font'],
    mechanics: '1-action Spellshape. Next single-target harm/heal: target gains +2 status AC and saves for 1 round.',
  },
  {
    id: 'cleric-domain-focus',
    name: 'Domain Focus',
    source: 'Cleric',
    category: 'class',
    level: 12,
    description: 'Your devotion to your deity\'s domains grows even further. If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Domain Initiate'],
    mechanics: 'Spent 2+ FP since last Refocus → recover 2 FP on Refocus.',
  },
  {
    id: 'cleric-emblazon-antimagic',
    name: 'Emblazon Antimagic',
    source: 'Cleric',
    category: 'class',
    level: 12,
    description: 'Your deity\'s symbol protects against offensive magic. When you Emblazon an Armament, you can choose from the following effects instead of the effects listed in that feat. Shield: When the wielder has the shield raised, they gain the shield\'s circumstance bonus to saving throws against magic, and they can use Shield Block against damage from their enemies\' spells. Weapon: When the weapon\'s wielder critically hits with the weapon, they can attempt to counteract a spell on their target, using half their level, rounded up, as the counteract rank. After the attempt, the emblazoned symbol immediately disappears.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Emblazon Armament'],
    mechanics: 'Emblazon alternate. Shield: circumstance bonus to saves vs magic + Shield Block vs spell damage. Weapon: crit hit → counteract a spell on target (rank = half level), then symbol disappears.',
  },
  {
    id: 'cleric-fortunate-relief',
    name: 'Fortunate Relief',
    source: 'Cleric',
    category: 'class',
    level: 12,
    description: 'Your god favors your attempts to remove afflictions and conditions. When you cast a healing spell that attempts to counteract an effect, you can roll the counteract check twice and take the higher value.',
    implemented: 'full',
    traits: ['Cleric', 'Fortune'],
    actionCost: 'passive',
    mechanics: 'Fortune. Roll counteract checks from healing spells twice, take higher.',
  },
  {
    id: 'cleric-sapping-symbol',
    name: 'Sapping Symbol',
    source: 'Cleric',
    category: 'class',
    level: 12,
    description: 'Your religious symbol glows with sacred energy, turning the attacker\'s strength to weakness. Attempt a Religion check against the triggering creature\'s Will DC. Regardless of the result, the creature is temporarily immune for 1 minute. Critical Success: The creature is enfeebled 2 until it spends at least 1 action moving away from you. Success: As critical success, but enfeebled 1.',
    implemented: 'full',
    traits: ['Cleric', 'Divine'],
    actionCost: 'reaction',
    prerequisites: ['Raise Symbol'],
    mechanics: 'Reaction. Trigger: While symbol is raised, you are about to take melee attack damage. Religion vs Will DC. Crit Success: enfeebled 2 (until moves away). Success: enfeebled 1. Immune 1 min.',
  },
  {
    id: 'cleric-shared-replenishment',
    name: 'Shared Replenishment',
    source: 'Cleric',
    category: 'class',
    level: 12,
    description: 'When your deity\'s weapon feeds your fervor, you share that divine spark with a nearby ally. When you use Replenishment of War to regain a Focus Point, a willing ally within 30 feet of you who has a focus pool also regains 1 Focus Point, up to their usual maximum.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Replenishment of War'],
    mechanics: 'When Replenishment of War triggers, an ally within 30 ft with a focus pool also regains 1 FP.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 14 Feats (7) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-channeling-block',
    name: 'Channeling Block',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'You pour divine energy into a desperate block. When you use Shield Block with your religious symbol, you can sacrifice a prepared harm or heal spell slot. If you do, the shield gains additional temporary Hardness equal to 2 × the spell rank for the Shield Block.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'reaction',
    prerequisites: ['Shield Block'],
    mechanics: 'Reaction on Shield Block with religious symbol. Sacrifice harm/heal slot → shield gains temporary Hardness = 2 × spell rank.',
  },
  {
    id: 'cleric-deitys-protection',
    name: 'Deity\'s Protection',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'Your deity grants your domain powers additional protection. You gain resistance equal to your Charisma modifier (minimum 1) against the damage types associated with your domains\' traits (fire for the Fire domain, etc.). When you cast a focus spell from one of your domains, this resistance increases to 2 + your Charisma modifier until the start of your next turn.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Advanced Domain'],
    mechanics: 'Resistance = CHA mod (min 1) vs domain-trait damage type. Casting domain focus spell → resistance = 2 + CHA mod until next turn.',
  },
  {
    id: 'cleric-ebb-and-flow',
    name: 'Ebb and Flow',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'You simultaneously channel your divine font to harm and to heal. You cast both a harm and heal spell, each 2 ranks lower than your highest spell rank (minimum 1st). Choose one of these spells to target a living creature and the other to target an undead creature within range of both spells. You can\'t apply spellshape or other alterations to either spell.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 2,
    prerequisites: ['harmful font and healing font; or Versatile Font'],
    mechanics: '2 actions. Cast harm + heal simultaneously (each 2 ranks lower, min 1st). One targets living, one targets undead. No spellshape allowed.',
  },
  {
    id: 'cleric-fast-channel',
    name: 'Fast Channel',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'Divine energy flows from you faster than normal. When you cast harm or heal, you reduce the number of actions needed to cast the spell by 1 (minimum 1 action).',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['harmful font or healing font'],
    mechanics: 'Reduce harm/heal action cost by 1 (minimum 1 action).',
  },
  {
    id: 'cleric-lasting-armament',
    name: 'Lasting Armament',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'Your sacred armaments last far longer. The duration of Sanctify Armament increases to 1 minute.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Sanctify Armament'],
    mechanics: 'Sanctify Armament duration → 1 minute (from 1 round).',
  },
  {
    id: 'cleric-premonition-of-clarity',
    name: 'Premonition of Clarity',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'Your ability to perceive and avoid danger extends beyond hazards. The +2 circumstance bonus from Premonition of Avoidance also applies to saving throws against traps and to your AC against attacks made by hazards.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Premonition of Avoidance'],
    mechanics: 'Premonition of Avoidance bonus extends to saves vs traps and AC vs hazard attacks.',
  },
  {
    id: 'cleric-swift-banishment',
    name: 'Swift Banishment',
    source: 'Cleric',
    category: 'class',
    level: 14,
    description: 'The force of your blow sends your victim back to where it came from. You attempt to cast a 5th-rank banishment on the target (using any spell DC). The creature takes a –2 circumstance penalty to the save if it is undead or a fiend.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'reaction',
    mechanics: 'Reaction. Trigger: You critically hit a creature not on its home plane. Cast 5th-rank banishment. Undead/fiends take –2 penalty to save.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 16 Feats (5) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-eternal-bane',
    name: 'Eternal Bane',
    source: 'Cleric',
    category: 'class',
    level: 16,
    description: 'Your deity\'s negative energy constantly pervades your body and everything around you. You and undead creatures within a 15-foot emanation gain a +2 status bonus to damage with melee Strikes and spell damage rolls against living creatures.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'You and undead within 15-ft emanation: +2 status to melee Strike and spell damage vs living.',
  },
  {
    id: 'cleric-eternal-blessing',
    name: 'Eternal Blessing',
    source: 'Cleric',
    category: 'class',
    level: 16,
    description: 'Your deity\'s vital energy constantly pervades your body and everything around you. You and living creatures within a 15-foot emanation gain a +2 status bonus to damage with melee Strikes and spell damage rolls against undead.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'You and living within 15-ft emanation: +2 status to melee Strike and spell damage vs undead.',
  },
  {
    id: 'cleric-rebounding-smite',
    name: 'Rebounding Smite',
    source: 'Cleric',
    category: 'class',
    level: 16,
    description: 'When your divine smite punishes the guilty, some of the energy rebounds to heal you. When you use Channel Smite and deal the additional damage, you regain Hit Points equal to half the additional damage dealt.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'On Channel Smite extra damage dealt, regain HP equal to half the additional damage.',
  },
  {
    id: 'cleric-remediate',
    name: 'Remediate',
    source: 'Cleric',
    category: 'class',
    level: 16,
    description: 'Your healing spells absorb afflictions of all kinds. When you cast a spell from your divine font that restores Hit Points to a target, you can also attempt to counteract one affliction or condition affecting the target. Your counteract rank is equal to half your level, rounded up, and you use your spell attack modifier or your spell DC – 10 as the counteract modifier.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Divine font heal → also counteract 1 affliction/condition. Counteract rank = half level (rounded up). Uses spell attack or DC – 10.',
  },
  {
    id: 'cleric-resurrectionist',
    name: 'Resurrectionist',
    source: 'Cleric',
    category: 'class',
    level: 16,
    description: 'You can bring the dead back to life with your channeled energy. You can cast resurrect as a divine innate spell once per day without a material cost, but the target must have died within the last 3 rounds. The target returns at 1 HP.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Once per day: cast resurrect (no material cost, divine innate). Target must have died within 3 rounds. Returns at 1 HP.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 18 Feats (6) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-divine-apex',
    name: 'Divine Apex',
    source: 'Cleric',
    category: 'class',
    level: 18,
    description: 'You have achieved the pinnacle of divine favor. You gain a +1 status bonus to your spell attack modifier and spell DC. When you critically succeed at a spell attack roll, the target is also stunned 1.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: '+1 status to spell attack and spell DC. Crit success on spell attack → target stunned 1.',
  },
  {
    id: 'cleric-echoing-channel',
    name: 'Echoing Channel',
    source: 'Cleric',
    category: 'class',
    level: 18,
    description: 'When you energize your allies with channeled energy, some of your power lingers. When you cast heal or harm from your divine font and heal or damage at least one creature, you can choose one of the creatures to gain residual energy. At the start of your next turn, the creature regains Hit Points (or takes damage, if it was harmed) equal to half the amount from the original spell.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'After font heal/harm: choose 1 creature. Start of next turn: they regain HP / take damage = half original spell.',
  },
  {
    id: 'cleric-improved-swift-banishment',
    name: 'Improved Swift Banishment',
    source: 'Cleric',
    category: 'class',
    level: 18,
    description: 'Your banishing strikes are even more powerful. When using Swift Banishment, the spell rank increases to 9th, and the target takes a –4 circumstance penalty to the save instead of –2.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Swift Banishment'],
    mechanics: 'Swift Banishment → 9th-rank banishment. Target penalty increases to –4.',
  },
  {
    id: 'cleric-inviolable',
    name: 'Inviolable',
    source: 'Cleric',
    category: 'class',
    level: 18,
    description: 'Your divine power is so strong that it prevents enemies from sapping your strength. You gain a +2 status bonus to saving throws against effects that would affect your magic (such as dispel magic). If you roll a success on such a save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: '+2 status to saves vs effects targeting your magic. Success → crit success.',
  },
  {
    id: 'cleric-miraculous-possibility',
    name: 'Miraculous Possibility',
    source: 'Cleric',
    category: 'class',
    level: 18,
    description: 'Your connection to your deity allows you to perform a miracle when it\'s most needed. Once per day during your daily preparations, you can choose a divine spell of 7th rank or lower. Until your next daily preparations, you can cast that spell as though it were one of your prepared spells, using a spell slot of its rank.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'During daily prep, choose a divine spell ≤ 7th rank → cast it once that day using a slot of its rank.',
  },
  {
    id: 'cleric-shared-clarity',
    name: 'Shared Clarity',
    source: 'Cleric',
    category: 'class',
    level: 18,
    description: 'When you are granted a premonition of danger, you can share this insight with your allies. The benefits of Premonition of Clarity extend to all allies within 20 feet of you.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['Premonition of Clarity'],
    mechanics: 'Premonition of Clarity benefits → all allies within 20 ft.',
  },

  // ════════════════════════════════════════════════════════
  // ── Level 20 Feats (4) ──
  // ════════════════════════════════════════════════════════
  {
    id: 'cleric-avatars-audience',
    name: 'Avatar\'s Audience',
    source: 'Cleric',
    category: 'class',
    level: 20,
    description: 'Your deity has deemed you worthy of their personal attention. You can cast a 10th-rank avatar spell once per day as a divine innate spell, but the spell has a casting time of 10 minutes rather than 2 actions. While in avatar form, you can perceive through your deity\'s senses, gaining greater darkvision and a +4 status bonus to Perception checks.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    mechanics: 'Once per day: cast 10th-rank avatar (10 min casting). Greater darkvision + +4 status Perception in avatar form.',
  },
  {
    id: 'cleric-avatars-protection',
    name: 'Avatar\'s Protection',
    source: 'Cleric',
    category: 'class',
    level: 20,
    description: 'You cast avatar from your spell slots. The triggering critical hit is reduced to a normal hit, and its damage is applied after gaining the avatar spell\'s temporary Hit Points.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'reaction',
    prerequisites: ['avatar spell prepared'],
    mechanics: 'Reaction. Trigger: You are critically hit. Cast avatar → crit becomes normal hit, damage applied after avatar temp HP.',
  },
  {
    id: 'cleric-maker-of-miracles',
    name: 'Maker of Miracles',
    source: 'Cleric',
    category: 'class',
    level: 20,
    description: 'You are capable of performing more miracles than other clerics. You gain an additional 10th-rank spell slot.',
    implemented: 'full',
    traits: ['Cleric'],
    actionCost: 'passive',
    prerequisites: ['miraculous spell class feature'],
    mechanics: 'Gain a second 10th-rank spell slot.',
  },
  {
    id: 'cleric-spellshape-channel',
    name: 'Spellshape Channel',
    source: 'Cleric',
    category: 'class',
    level: 20,
    description: 'You combine your mastery of channeled energy with spellshaping. Use one spellshape action you can perform that normally takes 1 action and can be applied to the harm or heal spell. That spellshape applies to all harm or heal spells you cast from your divine font until the end of your turn.',
    implemented: 'full',
    traits: ['Cleric', 'Concentrate'],
    actionCost: 'free',
    mechanics: 'Free action. Apply a 1-action spellshape to ALL font harm/heal spells for the rest of your turn.',
  },
];
