/**
 * Commander Class Features & Feats — PF2e Remastered (Battlecry!)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=66
 *
 * Key Attribute: INT | HP: 8 + CON
 * Perception: Expert
 * Fort: Trained → Expert (L9, Fortitude Expertise)
 * Reflex: Expert → Master (L15, Battlefield Intuition, success→crit)
 * Will: Expert → Master (L11, Commanding Will, success→crit)
 * Weapons: Trained simple+martial+unarmed → Expert (L5, Military Expertise) → Master (L13, Weapon Mastery)
 * Armor: Trained all+unarmored → Expert (L11, Armor Expertise, spec medium/heavy) → Master (L17, Armor Mastery)
 * Class DC: Trained → Expert (L7) → Master (L15) → Legendary (L19)
 * Skills: Society + Warfare Lore + 2 + INT
 *
 * Commander's Banner: 30-ft emanation, +1 status to Will saves and DCs vs fear.
 *   Can affix to weapon, shield, companion, or plant in ground.
 * Tactics: Start with 5 in folio, prepare 3 daily. Squadmates = 2 + INT mod.
 * Drilled Reactions: 1/round when using tactic, grant one ally extra reaction.
 *
 * Class features: 17 (L1–L19)
 * Class feats: 43 (39 Battlecry! + 4 shared: Combat Assessment, Reactive Strike, Shield Warden, Reactive Interference)
 */

import type { FeatEntry } from './featTypes';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
  GREATER_WEAPON_SPECIALIZATION,
  SHIELD_BLOCK,
} from './sharedFeats';

// ──────────────────────────────────────────────────────────
// COMMANDER CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const COMMANDER_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'commander-commanders-banner',
    name: 'Commander\'s Banner',
    source: 'Commander',
    category: 'class_feature',
    level: 1,
    description: 'You carry a banner that inspires and guides your allies in battle. Your banner creates a 30-foot emanation around you. Allies within this aura gain a +1 status bonus to Will saves and DCs against fear effects. You can affix your banner to a one-handed weapon, a shield, or an animal companion, or you can hold it in one hand. While your banner is displayed, you can use visual signals to communicate with your squadmates. If you are unable to display your banner, the aura deactivates until you display it again.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-tactics',
    name: 'Tactics',
    source: 'Commander',
    category: 'class_feature',
    level: 1,
    description: 'You have a folio of tactics — battlefield stratagems you drill into your squadmates and use to coordinate their actions. You start with 5 tactics in your folio and prepare 3 each day during daily preparations. Your squadmates are allies you designate during daily preparations, up to a maximum of 2 + your Intelligence modifier. Each tactic has a minimum proficiency rank in your class DC required to use it. When you use a tactic, you signal your squadmates using your banner (visual) or voice (auditory). Squadmates must be able to perceive your signal and must have a reaction available to respond to certain tactics.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-drilled-reactions',
    name: 'Drilled Reactions',
    source: 'Commander',
    category: 'class_feature',
    level: 1,
    description: 'Once per round when you use a tactic, you can grant one of your squadmates an additional reaction that can be used only to respond to that tactic. The squadmate must be able to perceive your signal.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  createClassFeature(SHIELD_BLOCK, 'Commander', 1),
  {
    id: 'commander-commander-feat-1',
    name: 'Commander Feat (Level 1)',
    source: 'Commander',
    category: 'class_feature',
    level: 1,
    description: 'You gain a commander class feat.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 3 ──
  {
    id: 'commander-warfare-expertise',
    name: 'Warfare Expertise',
    source: 'Commander',
    category: 'class_feature',
    level: 3,
    description: 'You become an expert in Warfare Lore. You can use Warfare Lore to roll initiative and to Recall Knowledge about creatures when in combat.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 5 ──
  {
    id: 'commander-military-expertise',
    name: 'Military Expertise',
    source: 'Commander',
    category: 'class_feature',
    level: 5,
    description: 'Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert. You gain access to the critical specialization effects of all weapons and unarmed attacks for which you have expert proficiency.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 7 ──
  {
    id: 'commander-expert-tactician',
    name: 'Expert Tactician',
    source: 'Commander',
    category: 'class_feature',
    level: 7,
    description: 'Your proficiency rank for your commander class DC increases to expert. The number of tactics in your folio increases by 2, and the number of tactics you can have prepared increases to 4. Your proficiency rank in Warfare Lore increases to master.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Commander', 7),
  // ── Level 9 ──
  {
    id: 'commander-fortitude-expertise',
    name: 'Fortitude Expertise',
    source: 'Commander',
    category: 'class_feature',
    level: 9,
    description: 'Your proficiency rank for Fortitude saves increases to expert.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 11 ──
  {
    id: 'commander-armor-expertise',
    name: 'Armor Expertise',
    source: 'Commander',
    category: 'class_feature',
    level: 11,
    description: 'Your proficiency ranks for light armor, medium armor, heavy armor, and unarmored defense increase to expert. You gain the armor specialization effects of medium and heavy armor.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-commanding-will',
    name: 'Commanding Will',
    source: 'Commander',
    category: 'class_feature',
    level: 11,
    description: 'Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 13 ──
  {
    id: 'commander-perception-mastery',
    name: 'Perception Mastery',
    source: 'Commander',
    category: 'class_feature',
    level: 13,
    description: 'Your proficiency rank for Perception increases to master.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-weapon-mastery',
    name: 'Weapon Mastery',
    source: 'Commander',
    category: 'class_feature',
    level: 13,
    description: 'Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 15 ──
  {
    id: 'commander-battlefield-intuition',
    name: 'Battlefield Intuition',
    source: 'Commander',
    category: 'class_feature',
    level: 15,
    description: 'Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Commander', 15),
  {
    id: 'commander-master-tactician',
    name: 'Master Tactician',
    source: 'Commander',
    category: 'class_feature',
    level: 15,
    description: 'Your proficiency rank for your commander class DC increases to master. The number of tactics in your folio increases by 2, and the number of tactics you can have prepared increases to 5. Your proficiency rank in Warfare Lore increases to legendary.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 17 ──
  {
    id: 'commander-armor-mastery',
    name: 'Armor Mastery',
    source: 'Commander',
    category: 'class_feature',
    level: 17,
    description: 'Your proficiency ranks for light armor, medium armor, heavy armor, and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 19 ──
  {
    id: 'commander-legendary-tactician',
    name: 'Legendary Tactician',
    source: 'Commander',
    category: 'class_feature',
    level: 19,
    description: 'Your proficiency rank for your commander class DC increases to legendary. The number of tactics in your folio increases by 2, and the number of tactics you can have prepared increases to 6.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
];

// ──────────────────────────────────────────────────────────
// COMMANDER CLASS FEATS (Selected at Even Levels)
// ──────────────────────────────────────────────────────────

export const COMMANDER_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 Feats (6) ──
  {
    id: 'commander-armor-regiment-training',
    name: 'Armor Regiment Training',
    source: 'Commander',
    category: 'class',
    level: 1,
    description: 'You drill your allies in the arts of wearing and leveraging heavy armor in combat and at camp. You treat heavy armor you wear as 1 less Bulk. When you rest in any armor, you still recover as if in light or no armor. Your allies ignore any Speed penalties imposed by their armor when using Exploration activities for overland travel.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-combat-assessment',
    name: 'Combat Assessment',
    source: 'Commander',
    category: 'class',
    level: 1,
    description: 'You make a telegraphed attack to learn about your foe. Make a melee Strike. On a hit, you can immediately attempt a check to Recall Knowledge about the target. On a critical hit, you gain a +2 circumstance bonus to the check to Recall Knowledge. The target is temporarily immune to Combat Assessment for 1 day.',
    implemented: 'full',
    traits: ['Commander', 'Fighter'],
    actionCost: 1,
  },
  {
    id: 'commander-commanders-companion',
    name: 'Commander\'s Companion',
    source: 'Commander',
    category: 'class',
    level: 1,
    description: 'You gain a young animal companion that serves as your regiment\'s mascot and helps carry your banner into battle. You can affix your banner to your animal companion. Your animal companion always counts as one of your squadmates. When you use Command an Animal as part of your turn, your animal companion gains a reaction it can use to respond to your tactics, in addition to the actions you grant it.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-deceptive-tactics',
    name: 'Deceptive Tactics',
    source: 'Commander',
    category: 'class',
    level: 1,
    description: 'You\'ve developed a number of underhanded feints and cunning tricks. You can use Warfare Lore for Deception checks to Create a Diversion or Feint against anyone you are observing. You gain the Lengthy Diversion skill feat.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Can prepare 3+ tactics'],
  },
  {
    id: 'commander-officers-medical-training',
    name: 'Officer\'s Medical Training',
    source: 'Commander',
    category: 'class',
    level: 1,
    description: 'You\'ve trained in treating the wounded soldiers in your care and can deftly apply bandages, stitches, and salves under pressure. You become trained in Medicine and can use your Intelligence modifier for Medicine checks instead of your Wisdom modifier. You gain the Battle Medicine skill feat.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Can prepare 3+ tactics'],
  },
  {
    id: 'commander-plant-banner',
    name: 'Plant Banner',
    source: 'Commander',
    category: 'class',
    level: 1,
    description: 'You slam the base of your banner into the ground, planting it in a corner of your square. Allies within a 30-foot burst of your planted banner gain 4 temporary Hit Points, plus 4 for every 4 levels you have. These temporary Hit Points are renewed at the start of each of the ally\'s turns while they remain in the burst. While planted, your banner signals become auditory only (your shouts or horn blasts rather than visual displays). The emanation of your banner becomes a burst and increases by 10 feet. Your planted banner gains Hardness equal to your level + your Intelligence modifier. If the banner is destroyed, you can repair it during daily preparations.',
    implemented: 'full',
    traits: ['Commander', 'Manipulate'],
    actionCost: 1,
  },
  // ── Level 2 Feats (6) ──
  {
    id: 'commander-adaptive-stratagem',
    name: 'Adaptive Stratagem',
    source: 'Commander',
    category: 'class',
    level: 2,
    description: 'When the first moments of combat reveal a potential problem, you quickly adapt your plans to the situation. When you roll initiative, you can replace one of your currently prepared tactics with another tactic from your folio.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'free',
    mechanics: 'Trigger: You roll initiative.',
  },
  {
    id: 'commander-defensive-swap',
    name: 'Defensive Swap',
    source: 'Commander',
    category: 'class',
    level: 2,
    description: 'You see the trajectory of an attack and quickly swap positions with a nearby ally to protect them — or to put them in harm\'s way to protect yourself. You and an adjacent willing ally swap positions. The creature that was not the original target of the triggering attack becomes the target instead.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You or an adjacent willing ally is targeted by an attack.',
  },
  {
    id: 'commander-guiding-shot',
    name: 'Guiding Shot',
    source: 'Commander',
    category: 'class',
    level: 2,
    description: 'You fire a shot that directs your allies\' attacks. Make a ranged Strike. On a hit, the next ally to make an attack roll against the same target before the start of your next turn gains a +1 circumstance bonus to the attack roll. On a critical hit, the circumstance bonus is +2 instead.',
    implemented: 'full',
    traits: ['Commander', 'Flourish'],
    actionCost: 1,
    prerequisites: ['Wielding a ranged weapon'],
  },
  {
    id: 'commander-rapid-assessment',
    name: 'Rapid Assessment',
    source: 'Commander',
    category: 'class',
    level: 2,
    description: 'You glance across the battlefield, instantly identifying key threats. When you roll initiative, you can attempt a check to Recall Knowledge against one creature you are observing.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'free',
    mechanics: 'Trigger: You roll initiative.',
  },
  {
    id: 'commander-set-up-strike',
    name: 'Set-up Strike',
    source: 'Commander',
    category: 'class',
    level: 2,
    description: 'You strike an enemy in a way that exposes openings for your allies. Make a melee Strike. On a hit, the target is off-guard against the next attack made against it by a creature other than you before the start of your next turn.',
    implemented: 'full',
    traits: ['Commander', 'Flourish'],
    actionCost: 1,
  },
  {
    id: 'commander-tactical-expansion',
    name: 'Tactical Expansion',
    source: 'Commander',
    category: 'class',
    level: 2,
    description: 'You\'ve committed additional tactics to your folio. Add 2 tactics to your tactics folio. You can take this feat multiple times, adding 2 additional tactics to your folio each time.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  // ── Level 4 Feats (5) ──
  {
    id: 'commander-banner-twirl',
    name: 'Banner Twirl',
    source: 'Commander',
    category: 'class',
    level: 4,
    description: 'You rapidly spin your banner around you, creating a distracting blur. You and all adjacent allies have concealment against ranged attacks until the start of your next turn.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Manipulate'],
    actionCost: 1,
  },
  {
    id: 'commander-banners-inspiration',
    name: 'Banner\'s Inspiration',
    source: 'Commander',
    category: 'class',
    level: 4,
    description: 'You hold your banner high, its inspiring sight steeling the nerves of your allies. Each ally within the aura of your commander\'s banner reduces the value of their frightened condition by 1. Additionally, each such ally can attempt a new saving throw against one mental effect currently affecting them. On a success, the effect ends. After being affected by Banner\'s Inspiration, a creature is temporarily immune for 10 minutes.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Emotion', 'Flourish', 'Mental', 'Visual'],
    actionCost: 1,
  },
  {
    id: 'commander-observational-analysis',
    name: 'Observational Analysis',
    source: 'Commander',
    category: 'class',
    level: 4,
    description: 'You work with your allies to analyze opponents mid-battle. You gain a +2 circumstance bonus to Recall Knowledge checks when using Combat Assessment against a target that has been hit by you or an ally since the start of your last turn. On a critical hit with Combat Assessment, the circumstance bonus is +4 instead.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Combat Assessment'],
  },
  {
    id: 'commander-shielded-recovery',
    name: 'Shielded Recovery',
    source: 'Commander',
    category: 'class',
    level: 4,
    description: 'You can use the hand holding a shield to administer medical aid. You can use your shield hand for the manipulate components of Treat Wounds or Battle Medicine. When you use Battle Medicine on an ally while holding or wielding a shield, the ally also gains a +1 circumstance bonus to AC and Reflex saves until the start of your next turn or until they are no longer adjacent to you, whichever comes first.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Officer\'s Medical Training'],
  },
  {
    id: 'commander-unsteadying-strike',
    name: 'Unsteadying Strike',
    source: 'Commander',
    category: 'class',
    level: 4,
    description: 'You focus your attack on disrupting an opponent\'s balance. Make a melee Strike. On a hit, the enemy takes a –2 circumstance penalty to its Fortitude DC against Grapple, Reposition, and Shove, and a –2 circumstance penalty to its Reflex DC against Disarm, until the start of your next turn.',
    implemented: 'full',
    traits: ['Commander', 'Flourish'],
    actionCost: 1,
  },
  // ── Level 6 Feats (5, including 2 shared) ──
  {
    id: 'commander-battle-tested-companion',
    name: 'Battle-Tested Companion',
    source: 'Commander',
    category: 'class',
    level: 6,
    description: 'Your animal companion has grown alongside you and is now a mature animal companion. When your banner is affixed to your companion, the aura of your banner increases by 10 feet.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Commander\'s Companion'],
  },
  {
    id: 'commander-claim-the-field',
    name: 'Claim the Field',
    source: 'Commander',
    category: 'class',
    level: 6,
    description: 'You hurl your banner forward with precision, claiming the battlefield for yourself and your allies. You Plant the Banner, but you can place it at any corner within the required weapon\'s first range increment, rather than the corner of your square. The calculated confidence of this brash maneuver unnerves your enemies; any enemy who attempts to damage or remove your banner while it is planted in this way must succeed at a Will save against your class DC or the attempt fails. On a critical failure, the enemy is fleeing for 1 round. This is an incapacitation and mental effect.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Plant Banner'],
    mechanics: 'Requirements: Your banner is attached to a thrown weapon.',
  },
  {
    id: 'commander-efficient-preparation',
    name: 'Efficient Preparation',
    source: 'Commander',
    category: 'class',
    level: 6,
    description: 'You\'ve developed techniques for drilling your allies on multiple tactics in a succinct and efficient manner. Increase the number of tactics you can have prepared by 1.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-reactive-strike',
    name: 'Reactive Strike',
    source: 'Commander',
    category: 'class',
    level: 6,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Champion', 'Commander', 'Exemplar', 'Guardian', 'Magus', 'Swashbuckler'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature within your reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it\'s using.',
  },
  {
    id: 'commander-shield-warden',
    name: 'Shield Warden',
    source: 'Commander',
    category: 'class',
    level: 6,
    description: 'When you have a shield raised, you can use your Shield Block reaction when an attack is made against an ally adjacent to you. If you do, the shield prevents that ally from taking damage instead of preventing you from taking damage, following the normal rules for Shield Block.',
    implemented: 'full',
    traits: ['Champion', 'Commander', 'Fighter'],
    actionCost: 'passive',
    prerequisites: ['Shield Block'],
  },
  // ── Level 8 Feats (4) ──
  {
    id: 'commander-defiant-banner',
    name: 'Defiant Banner',
    source: 'Commander',
    category: 'class',
    level: 8,
    description: 'You vigorously wave your banner to remind yourself and your allies that you can and must endure. You and all allies within the aura of your commander\'s banner when you use this action gain resistance to bludgeoning, piercing, and slashing damage equal to your Intelligence modifier until the start of your next turn.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Flourish', 'Manipulate', 'Visual'],
    actionCost: 1,
  },
  {
    id: 'commander-officers-education',
    name: 'Officer\'s Education',
    source: 'Commander',
    category: 'class',
    level: 8,
    description: 'You know that a broad knowledge base is critical for a competent commander. You become trained in two skills you are not already trained in, become an expert in one skill you are currently trained in, learn one common language you do not already know, and gain any one general feat that you meet the prerequisites for. You can take this feat twice, gaining its benefits each time.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-rallying-banner',
    name: 'Rallying Banner',
    source: 'Commander',
    category: 'class',
    level: 8,
    description: 'Your banner waves high, reminding your allies that the fight can still be won. You restore 4d6 Hit Points to each ally within the aura of your commander\'s banner. This healing increases by an additional 1d6 at 10th level and every 2 levels thereafter. Since this healing relies on drawing from your allies\' morale and adrenaline, the healing it grants is halved when used outside of combat.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Emotion', 'Healing', 'Mental', 'Visual'],
    actionCost: 1,
    mechanics: 'Frequency: once per 10 minutes.',
  },
  {
    id: 'commander-unrivaled-analysis',
    name: 'Unrivaled Analysis',
    source: 'Commander',
    category: 'class',
    level: 8,
    description: 'Your experience allows you to derive even more information about your opponents from a mere glance. When you use Rapid Assessment, you can attempt up to four checks to Recall Knowledge about creatures you are observing.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Rapid Assessment'],
  },
  // ── Level 10 Feats (4) ──
  {
    id: 'commander-battle-hardened-companion',
    name: 'Battle-Hardened Companion',
    source: 'Commander',
    category: 'class',
    level: 10,
    description: 'Accompanying you across countless battlefields has allowed your companion to unleash its full potential. The companion you gained with Commander\'s Companion is now a nimble or savage animal companion. Your animal companion is more readily responsive to your will. During an encounter, even if you don\'t use the Command an Animal action, your animal companion can still use 1 action that round on your turn to Stride or Strike. If it does, it also gains a reaction it can use to respond to your tactics, but that\'s all the actions it gets that round — you can\'t Command it later.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Battle-Tested Companion'],
  },
  {
    id: 'commander-drilled-reflexes',
    name: 'Drilled Reflexes',
    source: 'Commander',
    category: 'class',
    level: 10,
    description: 'You leave a lasting impression on your squadmates that makes them particularly adept at following your commands. When you use your drilled reactions ability, you can give an extra reaction to up to two allies instead of only one.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-standard-bearers-sacrifice',
    name: 'Standard-Bearer\'s Sacrifice',
    source: 'Commander',
    category: 'class',
    level: 10,
    description: 'Seeing an enemy take aim at your ally, you bravely flourish your banner to redirect their attention to you. The triggering opponent must attempt a Will save against your class DC. Success: The opponent completes its attack against your ally. Failure: The opponent targets you with the triggering attack instead. Critical Failure: As failure, and you gain a +2 circumstance bonus to your AC against the triggering attack.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Manipulate', 'Visual'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An opponent targets an ally with a ranged attack, you are observing both of them, and you are also in range of the attack. Requirements: You are holding or wielding your banner.',
  },
  {
    id: 'commander-targeting-strike',
    name: 'Targeting Strike',
    source: 'Commander',
    category: 'class',
    level: 10,
    description: 'Your attack creates an opening in your target\'s defenses for your allies to capitalize on. When you successfully damage an opponent with either Guiding Shot or Set-Up Strike, the next creature other than you to attack the same target before the start of your next turn deals an amount of additional precision damage equal to your Intelligence modifier.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Guiding Shot', 'Set-up Strike'],
  },
  // ── Level 12 Feats (3, including 1 shared) ──
  {
    id: 'commander-fortunate-blow',
    name: 'Fortunate Blow',
    source: 'Commander',
    category: 'class',
    level: 12,
    description: 'You set an enemy up for a devastating follow-through from your allies. When you successfully damage an opponent with either Guiding Shot or Set-Up Strike, the next creature other than you to attack the same target before the start of your next turn rolls twice on their attack roll and takes the higher result.',
    implemented: 'full',
    traits: ['Commander', 'Fortune'],
    actionCost: 'passive',
    prerequisites: ['Guiding Shot or Set-up Strike'],
  },
  {
    id: 'commander-perfected-evaluations',
    name: 'Perfected Evaluations',
    source: 'Commander',
    category: 'class',
    level: 12,
    description: 'You instantly assess the strengths and weaknesses of the enemy forces. When you use Rapid Assessment, you can attempt up to six Recall Knowledge checks against enemies you are observing.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Unrivaled Analysis'],
  },
  {
    id: 'commander-reactive-interference',
    name: 'Reactive Interference',
    source: 'Commander',
    category: 'class',
    level: 12,
    description: 'Grabbing a sleeve, swiping with your weapon, or creating another obstruction, you reflexively foil an enemy\'s response. If the triggering creature\'s level is equal to or lower than yours, you disrupt the triggering reaction. If the triggering creature\'s level is higher than yours, you must make an attack roll against its AC. On a success, you disrupt the reaction.',
    implemented: 'full',
    traits: ['Commander', 'Rogue'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An adjacent enemy begins to use a reaction.',
  },
  // ── Level 14 Feats (3) ──
  {
    id: 'commander-contact-with-the-enemy',
    name: 'Contact with the Enemy',
    source: 'Commander',
    category: 'class',
    level: 14,
    description: 'You know that even the best-laid plans rarely survive contact with the enemy, and you have prepared your allies to adapt with a wide array of contingencies. When you use Adaptive Stratagem, you can replace any master tactics or legendary tactics you have prepared with any other tactics in your folio.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Adaptive Stratagem'],
  },
  {
    id: 'commander-desperate-resuscitation',
    name: 'Desperate Resuscitation',
    source: 'Commander',
    category: 'class',
    level: 14,
    description: 'You can use your training in combat medicine to revive the recently deceased. Attempt a DC 40 Medicine check to revive a dead creature that has been dead for no more than 3 rounds. If you succeed, the target returns to life with the effects of raise dead, except it still has the wounded condition it had before dying, increased by 1 (or wounded 1 if it wasn\'t wounded before dying). Whether you succeed or fail, the target is temporarily immune to Desperate Resuscitation for 1 day.',
    implemented: 'full',
    traits: ['Commander', 'Healing', 'Manipulate'],
    actionCost: 3,
    prerequisites: ['Officer\'s Medical Training', 'Master in Medicine'],
    mechanics: 'Requirements: You are holding a healer\'s toolkit or are wearing one and have a free hand; the target\'s body is mostly intact; the target was not killed by a death effect.',
  },
  {
    id: 'commander-quickening-banner',
    name: 'Quickening Banner',
    source: 'Commander',
    category: 'class',
    level: 14,
    description: 'The sight of your banner urges your allies to strike now. Each ally within the aura of your commander\'s banner is quickened for 1 round and can use this extra action to Strike or Stride.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Visual'],
    actionCost: 1,
    mechanics: 'Frequency: once per 10 minutes.',
  },
  // ── Level 16 Feats (2) ──
  {
    id: 'commander-confusing-commands',
    name: 'Confusing Commands',
    source: 'Commander',
    category: 'class',
    level: 16,
    description: 'You shout out bewildering but authoritative commands while imitating the voices, linguistic quirks, and speech patterns of your opponents. Each enemy within the aura of your commander\'s banner must succeed at a Will save against your class DC or become confused for 1 round (2 rounds on a critical failure). Targets who succeed at their saving throw are temporarily immune to Confusing Commands for 1 day.',
    implemented: 'full',
    traits: ['Auditory', 'Commander', 'Mental'],
    actionCost: 2,
    prerequisites: ['Deceptive Tactics'],
  },
  {
    id: 'commander-peerless-mascot-companion',
    name: 'Peerless Mascot Companion',
    source: 'Commander',
    category: 'class',
    level: 16,
    description: 'As veterans of countless battles, you and your companion share an indomitable strength. The companion you gained with Commander\'s Companion is now a specialized animal companion. You can select one of the usual specializations or the peerless mascot specialization. A commander\'s companion with the peerless mascot specialization gains the following benefits: it gains a 30-foot aura that grants the same benefits as your banner, effectively acting as a second banner (if your actual banner is affixed to it, the aura is a single 60-foot aura; if you later gain Glorious Banner, the aura is 100 feet while affixed to your peerless mascot companion); it gains the beast trait; its Intelligence modifier increases by 2 and its Wisdom modifier increases by 1; it is an expert in Warfare Lore and can speak one language you also speak; its maximum Hit Points increase by 20 (25 at 18th level, 30 at 20th level); and it gains a climb Speed and swim Speed equal to its land Speed (or its highest Speed if another Speed is greater).',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Battle-Hardened Companion'],
  },
  // ── Level 18 Feats (3) ──
  {
    id: 'commander-demand-surrender',
    name: 'Demand Surrender',
    source: 'Commander',
    category: 'class',
    level: 18,
    description: 'Confident in your victory, you command your opponent\'s surrender. Choose one opponent you are observing. You command that opponent to surrender in a strong voice. They must attempt a Will save against your class DC. Critical Success: The creature is unaffected. Success: The creature cannot take any hostile actions that include you as a target for 1 round. Failure: As success, and the target is fleeing for 1 round. Critical Failure: The creature drops any weapons or items it is holding, lies prone on the ground, and does not take any hostile actions against you or your allies for 1 minute, or until you or one of your allies attacks it.',
    implemented: 'full',
    traits: ['Auditory', 'Commander', 'Incapacitation', 'Mental'],
    actionCost: 2,
    mechanics: 'Requirements: You and your allies currently outnumber enemies on the battlefield, and you or an ally has either restrained an opponent or reduced an opponent to 0 Hit Points since the start of your last turn.',
  },
  {
    id: 'commander-mercenary-reversal',
    name: 'Mercenary Reversal',
    source: 'Commander',
    category: 'class',
    level: 18,
    description: 'Even though the fight seems to be surging against you and your compatriots, you know that a key ally can always turn the tide. Choose a target you are currently observing. You assail it with a list of reasons why it should join you and why its defeat if it does not is surely inevitable. The target attempts a Will save against your class DC. Critical Success: The target is uninterested in joining you and is temporarily immune to further uses of this ability for 24 hours. Success: The target is stunned 1 as it is forced to consider the merits of your offer. Failure: The target swaps sides and joins you for the duration of the battle. It gains the controlled condition, but it can attempt a Will save whenever it takes damage or whenever you direct it to take an action that goes against its nature. On a success, the effect ends and it rejoins its former allies. Critical Failure: As a failure, but the target is so impressed by your leadership that it thanks you for the privilege of fighting alongside you; if it is still alive at the end of combat, it turns over any coins, wealth, or other monetary possessions it has as tribute.',
    implemented: 'full',
    traits: ['Auditory', 'Commander', 'Concentrate', 'Incapacitation', 'Mental'],
    actionCost: 'passive',
    mechanics: 'Requirements: You and your allies are currently outnumbered by enemies on the battlefield.',
  },
  {
    id: 'commander-practiced-reflexes',
    name: 'Practiced Reflexes',
    source: 'Commander',
    category: 'class',
    level: 18,
    description: 'You snap out a quick series of signals or commands that urge your allies to act with alacrity. When you use your drilled reactions ability, you can give an extra reaction to up to four allies.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
    prerequisites: ['Drilled Reflexes'],
  },
  // ── Level 20 Feats (2) ──
  {
    id: 'commander-glorious-banner',
    name: 'Glorious Banner',
    source: 'Commander',
    category: 'class',
    level: 20,
    description: 'Your banner is an awesome sight to behold. Your commander\'s banner now affects a 60-foot emanation (or an 80-foot burst if you are using Plant Banner); the status bonus to Will saves and DCs against fear effects granted to your allies increases to +2; and you and affected allies gain a +1 status bonus to AC, Fortitude saves, and Reflex saves. Enemies within the aura of your commander\'s banner take a –2 status penalty to Will saves as long as they can see your banner.',
    implemented: 'full',
    traits: ['Commander'],
    actionCost: 'passive',
  },
  {
    id: 'commander-pennant-of-victory',
    name: 'Pennant of Victory',
    source: 'Commander',
    category: 'class',
    level: 20,
    description: 'You wave your banner in victory, signaling to your allies that the fight is won. You and all allies within the aura of your commander\'s banner gain a +4 status bonus to attack and damage rolls, a +10-foot status bonus to all your Speeds, and 40 temporary Hit Points. These benefits last until the start of your next turn.',
    implemented: 'full',
    traits: ['Brandish', 'Commander', 'Visual'],
    actionCost: 1,
    mechanics: 'Frequency: once per 10 minutes.',
  },
];
