/**
 * Exemplar Class Features & Feats — PF2e Remastered (War of Immortals)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=65
 *
 * Key Attribute: STR or DEX | HP: 10 + CON
 * Perception: Trained → Expert (L9) → Master (L17)
 * Fort: Expert → Master (L15, Mortality Reforged, success→crit)
 * Reflex: Trained → Expert (L9, Divine Premonition)
 * Will: Expert → Master (L7, Unassailable Soul, success→crit) → Legendary (L13, Greater Unassailable Soul, crit fail→fail, fail→half dmg)
 * Weapons: Trained simple+martial+unarmed → Expert (L5, Weapon Expertise) → Master (L13, Divine Weapon Mastery)
 * Armor: Trained light+medium+unarmored → Expert (L13, Burnished Armor Expertise) → Master (L19, Burnished Armor Mastery)
 * Class DC: Trained → Expert (L9, Godly Expertise) → Master (L17, Deific Mastery)
 * Skills: Religion + 3 + INT
 *
 * Divine Spark & Ikons: Three ikons (body, worn, weapon). Shift Immanence (1-action) places
 *   spark in one ikon for passive immanence effects. Spark Transcendence activates powerful
 *   ability then ejects spark to another ikon.
 * Humble Strikes: Simple weapons +1 die step (L1).
 * Shield Block: Free feat (L1).
 * Spirit Striking: +2 spirit damage w/ expert weapons (L7), +3 master, +4 legendary.
 *   Greater (L15): +4/+6/+8.
 * Epithets: Root (L3), Dominion (L7), Sovereignty (L15).
 *
 * Class features: 22 (L1–L19)
 * Class feats: 49 (L1–L20, including 5 Uncommon from PF #217 + 1 shared Fighter feat)
 */

import type { FeatEntry } from './featTypes';
import { createClassFeature } from './sharedFeats';

// ── Exemplar Class Features ──────────────────────────────

export const EXEMPLAR_CLASS_FEATURES: FeatEntry[] = [
  {
    id: 'exemplar-divine-spark-and-ikons',
    name: 'Divine Spark and Ikons',
    source: 'Exemplar',
    category: 'class_feature',
    level: 1,
    description: 'Within your soul is a tiny spark of divine power that belongs not to a deity, but is something you\'ve claimed all your own. You can focus this divine power through special items known as ikons. Ikons are items or bodily features intrinsically linked to you — sacred vessels forged from your divinity that are capable of conducting its power. Select three ikons. By placing your divine spark into one of your ikons, you empower that ikon to accomplish deeds beyond what it could in mortal hands. Each ikon has both a passive immanence effect and an active transcendence effect. Both of these effects require your divine spark to be in the item. You can place your spark into an ikon by using the Shift Immanence action.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-shift-immanence',
    name: 'Shift Immanence',
    source: 'Exemplar',
    category: 'class_feature',
    level: 1,
    description: 'You shift your power, filling one of your ikons with your divine spark. That ikon softly glows with radiant light, emits subtle chimes as it moves, or is otherwise obviously empowered in a way that matches your growing divinity, granting the ikon the divine trait and granting you that ikon\'s immanence effects for as long as your divine spark is empowering it. Your spark is indivisible, so it can empower only one ikon at a time. You can also Shift Immanence to return your spark to the depths of your soul, leaving none of your ikons empowered. Special: In addition to the above usage, you can also Shift Immanence as a free action triggered when you roll initiative.',
    implemented: 'full',
    traits: ['Divine', 'Exemplar'],
    actionCost: 1,
  },
  {
    id: 'exemplar-spark-transcendence',
    name: 'Spark Transcendence',
    source: 'Exemplar',
    category: 'class_feature',
    level: 1,
    description: 'While your spark dwells within an ikon, you get that ikon\'s immanence effect continually. However, you can also Spark Transcendence in a mighty deed, channeling your divinity through the ikon — though when you Spark Transcendence, the force of the act temporarily casts your divine spark out of the ikon. Each ikon\'s transcendence action appears in its stat block, and the transcendence trait is described in the Key Terms sidebar.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-humble-strikes',
    name: 'Humble Strikes',
    source: 'Exemplar',
    category: 'class_feature',
    level: 1,
    description: 'Even the most unassuming weapons can accomplish great deeds. When you are wielding a simple weapon, increase the damage die size of that weapon by one step.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-shield-block',
    name: 'Shield Block',
    source: 'Exemplar',
    category: 'class_feature',
    level: 1,
    description: 'You gain the Shield Block general feat, a reaction that lets you reduce damage with your shield.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-root-epithet',
    name: 'Root Epithet',
    source: 'Exemplar',
    category: 'class_feature',
    level: 3,
    description: 'As your story unfolds, your personality and deeds begin to shape the potential of your divine spark. You come to bear an epithet — a word or phrase that seems to always stick in the mind of those describing you. Your epithets grant you additional abilities, especially when your divine spark is brought to the surface. You first gain a root epithet to describe an aspect of your personality. This grants you a skill, as well as a special effect that occurs when you Spark Transcendence. If you are already trained in the granted skill, you become trained in a different skill of your choice, as normal. An effect that occurs after you Spark Transcendence happens immediately after your transcendence action is completely resolved. Choose one Root Epithet.',
    implemented: 'full',
    traits: ['Exemplar'],
    subChoices: { label: 'Choose a root epithet', options: [
      { id: 'the-brave', name: 'The Brave', description: 'Trained in Intimidation; spark effect: frighten foes' },
      { id: 'the-charismatic', name: 'The Charismatic', description: 'Trained in Diplomacy; spark effect: bolster allies' },
      { id: 'the-cunning', name: 'The Cunning', description: 'Trained in Deception; spark effect: confuse enemies' },
      { id: 'the-daring', name: 'The Daring', description: 'Trained in Acrobatics; spark effect: nimble movement' },
      { id: 'the-empathetic', name: 'The Empathetic', description: 'Trained in Medicine; spark effect: healing touch' },
      { id: 'the-foolish', name: 'The Foolish', description: 'Trained in Performance; spark effect: unpredictable' },
      { id: 'the-grand', name: 'The Grand', description: 'Trained in Society; spark effect: imposing presence' },
      { id: 'the-intrepid', name: 'The Intrepid', description: 'Trained in Survival; spark effect: endurance' },
      { id: 'the-just', name: 'The Just', description: 'Trained in Society; spark effect: righteous judgment' },
      { id: 'the-keen', name: 'The Keen', description: 'Trained in Perception; spark effect: keen senses' },
      { id: 'the-learned', name: 'The Learned', description: 'Trained in Arcana; spark effect: magical insight' },
      { id: 'the-restless', name: 'The Restless', description: 'Trained in Athletics; spark effect: relentless pursuit' },
      { id: 'the-sagacious', name: 'The Sagacious', description: 'Trained in Nature; spark effect: natural wisdom' },
      { id: 'the-serene', name: 'The Serene', description: 'Trained in Religion; spark effect: calming aura' },
      { id: 'the-stalwart', name: 'The Stalwart', description: 'Trained in Crafting; spark effect: fortified defense' },
      { id: 'the-tenacious', name: 'The Tenacious', description: 'Trained in Athletics; spark effect: unyielding grip' },
      { id: 'the-willful', name: 'The Willful', description: 'Trained in Occultism; spark effect: force of will' },
    ] },
  },
  {
    id: 'exemplar-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Exemplar',
    category: 'class_feature',
    level: 5,
    description: 'You\'ve dedicated yourself to learning the intricacies of your weapons. Your proficiency ranks for unarmed attacks, simple weapons, and martial weapons increase to expert.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-dominion-epithet',
    name: 'Dominion Epithet',
    source: 'Exemplar',
    category: 'class_feature',
    level: 7,
    description: 'Your divinity has grown in power along with your deeds, allowing you to begin claiming dominion over aspects of creation. Choose one Dominion Epithet. Each one grants a critical specialization ability you can use instead of any others you might have access to, and an ability you can use when you Spark Transcendence. You can benefit from no more than one epithet ability each time you Spark Transcendence. Some epithets grant additional benefits, such as feats.',
    implemented: 'full',
    traits: ['Exemplar'],
    subChoices: { label: 'Choose a dominion epithet', options: [
      { id: 'of-beasts', name: 'Of Beasts', description: 'Beast critical specialization; animal powers' },
      { id: 'of-fates', name: 'Of Fates', description: 'Fate manipulation; fortune/misfortune' },
      { id: 'of-feasts', name: 'Of Feasts', description: 'Sustenance and celebration' },
      { id: 'of-fortune', name: 'Of Fortune', description: 'Luck manipulation' },
      { id: 'of-the-hunt', name: 'Of the Hunt', description: 'Tracking and pursuit' },
      { id: 'of-knowledge', name: 'Of Knowledge', description: 'Information and recall' },
      { id: 'of-legions', name: 'Of Legions', description: 'Leadership and allies' },
      { id: 'of-might', name: 'Of Might', description: 'Raw physical power' },
      { id: 'of-night', name: 'Of Night', description: 'Darkness and stealth' },
      { id: 'of-sails', name: 'Of Sails', description: 'Travel and exploration' },
      { id: 'of-songs', name: 'Of Songs', description: 'Music and performance' },
      { id: 'of-storms', name: 'Of Storms', description: 'Lightning and thunder' },
      { id: 'of-sunlight', name: 'Of Sunlight', description: 'Radiance and illumination' },
      { id: 'of-the-craft', name: 'Of the Craft', description: 'Crafting and creation' },
      { id: 'of-the-deep', name: 'Of the Deep', description: 'Water and ocean depths' },
      { id: 'of-the-forge', name: 'Of the Forge', description: 'Fire and smithing' },
      { id: 'of-the-sky', name: 'Of the Sky', description: 'Air and flight' },
      { id: 'of-the-wilds', name: 'Of the Wilds', description: 'Nature and wilderness' },
      { id: 'of-undeath', name: 'Of Undeath', description: 'Death and undead power' },
    ] },
  },
  {
    id: 'exemplar-spirit-striking',
    name: 'Spirit Striking',
    source: 'Exemplar',
    category: 'class_feature',
    level: 7,
    description: 'Your divine power can\'t be contained, escaping in flits and embers as you wreak violence. You deal 2 additional spirit damage with weapons and unarmed attacks in which you are an expert. This damage increases to 3 if you\'re a master, and 4 if you\'re legendary.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-unassailable-soul',
    name: 'Unassailable Soul',
    source: 'Exemplar',
    category: 'class_feature',
    level: 7,
    description: 'A firm knowledge of (or foolish pride in) yourself and your ability girds your mind against doubt and intrusion. Your proficiency rank for Will saves increases to master. When you roll a success at a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-divine-premonition',
    name: 'Divine Premonition',
    source: 'Exemplar',
    category: 'class_feature',
    level: 9,
    description: 'A sense of the flow of fate allows you to respond to danger with uncanny alacrity. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-godly-expertise',
    name: 'Godly Expertise',
    source: 'Exemplar',
    category: 'class_feature',
    level: 9,
    description: 'Your divine power increases in might. Your proficiency rank for your exemplar class DC increases to expert.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-perception-expertise',
    name: 'Perception Expertise',
    source: 'Exemplar',
    category: 'class_feature',
    level: 9,
    description: 'You remain alert to threats around you. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-divine-weapon-mastery',
    name: 'Divine Weapon Mastery',
    source: 'Exemplar',
    category: 'class_feature',
    level: 13,
    description: 'Your skill with weapons is divinely inspired. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-greater-unassailable-soul',
    name: 'Greater Unassailable Soul',
    source: 'Exemplar',
    category: 'class_feature',
    level: 13,
    description: 'A wall of confidence blunts every arrow seeking to pierce your mind. Your proficiency rank for Will saves increases to legendary. When you roll a success at a Will save, you get a critical success. When you roll a critical failure at a Will save, you get a failure instead. When you fail a Will save against a damaging effect, you take half damage.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-burnished-armor-expertise',
    name: 'Burnished Armor Expertise',
    source: 'Exemplar',
    category: 'class_feature',
    level: 13,
    description: 'Exposure to your divine spark has reinforced your armor. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-greater-spirit-striking',
    name: 'Greater Spirit Striking',
    source: 'Exemplar',
    category: 'class_feature',
    level: 15,
    description: 'Your additional damage from spirit striking increases to 4 with weapons and unarmed attacks in which you\'re an expert, 6 if you\'re a master, and 8 if you\'re legendary.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-mortality-reforged',
    name: 'Mortality Reforged',
    source: 'Exemplar',
    category: 'class_feature',
    level: 15,
    description: 'Inner fire has burned away the frailty of a mortal body. Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-sovereignty-epithet',
    name: 'Sovereignty Epithet',
    source: 'Exemplar',
    category: 'class_feature',
    level: 15,
    description: 'The litany of heroic deeds left in your wake has caused your divine spark to blaze bright enough that it now illuminates your legacy. Choose one Sovereignty Epithet, which grants you an ability you can use when you Spark Transcendence. You can benefit from no more than one epithet ability each time you Spark Transcendence.',
    implemented: 'full',
    traits: ['Exemplar'],
    subChoices: { label: 'Choose a sovereignty epithet', options: [
      { id: 'the-indomitable', name: 'The Indomitable', description: 'Resist conditions and effects' },
      { id: 'the-inspired', name: 'The Inspired', description: 'Inspire allies with greatness' },
      { id: 'the-invincible', name: 'The Invincible', description: 'Unbreakable defense' },
      { id: 'the-luminous', name: 'The Luminous', description: 'Radiant divine light' },
      { id: 'the-merciful', name: 'The Merciful', description: 'Healing and mercy' },
      { id: 'the-resplendent', name: 'The Resplendent', description: 'Overwhelming divine presence' },
      { id: 'the-tireless', name: 'The Tireless', description: 'Endless stamina and action' },
      { id: 'the-unyielding', name: 'The Unyielding', description: 'Immovable resolve' },
      { id: 'the-whirlwind', name: 'The Whirlwind', description: 'Speed and devastating strikes' },
    ] },
  },
  {
    id: 'exemplar-deific-mastery',
    name: 'Deific Mastery',
    source: 'Exemplar',
    category: 'class_feature',
    level: 17,
    description: 'You have achieved full mastery over your divine spark as its power flows through your body and ikons. Your proficiency rank for your exemplar class DC increases to master.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-perception-mastery',
    name: 'Perception Mastery',
    source: 'Exemplar',
    category: 'class_feature',
    level: 17,
    description: 'Through your adventures, you\'ve developed keen awareness and attention to detail, the better to watch over your wards and keep an eye out for monsters and other threats. Your proficiency rank for Perception increases to master.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
  {
    id: 'exemplar-burnished-armor-mastery',
    name: 'Burnished Armor Mastery',
    source: 'Exemplar',
    category: 'class_feature',
    level: 19,
    description: 'Your armor shines with divine light, flawless and unyielding. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Exemplar'],
  },
];

// ── Exemplar Class Feats ─────────────────────────────────

export const EXEMPLAR_CLASS_FEATS: FeatEntry[] = [
  // ──── Level 1 ────
  {
    id: 'exemplar-elemental-imbuement',
    name: 'Elemental Imbuement',
    source: 'Exemplar',
    category: 'class',
    level: 1,
    description: 'Your ikon resonates with elemental energy. Choose an energy type. Your ikon abilities that deal spirit damage can instead deal damage of the chosen type.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'passive',
    subChoices: { label: 'Choose an energy type', options: [
      { id: 'air', name: 'Air (slashing)' },
      { id: 'cold', name: 'Cold' },
      { id: 'earth', name: 'Earth (bludgeoning)' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'metal', name: 'Metal (slashing)' },
      { id: 'poison', name: 'Poison' },
      { id: 'sonic', name: 'Sonic' },
      { id: 'vitality', name: 'Vitality' },
      { id: 'void', name: 'Void' },
      { id: 'water', name: 'Water (bludgeoning)' },
    ] },
  },
  {
    id: 'exemplar-sanctified-soul',
    name: 'Sanctified Soul',
    source: 'Exemplar',
    category: 'class',
    level: 1,
    description: 'You\'ve drawn a line in the sand in the cosmic struggle between good and evil and chosen a side. You gain either the holy trait or the unholy trait. All your exemplar abilities that deal spirit damage gain the sanctified trait, allowing you to apply your holy or unholy trait to them to better affect your chosen enemies.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'passive',
    subChoices: { label: 'Choose sanctification', options: [
      { id: 'holy', name: 'Holy', description: 'Gain the holy trait; spirit damage is holy' },
      { id: 'unholy', name: 'Unholy', description: 'Gain the unholy trait; spirit damage is unholy' },
    ] },
  },
  {
    id: 'exemplar-twin-stars',
    name: 'Twin Stars',
    source: 'Exemplar',
    category: 'class',
    level: 1,
    description: 'Your divine spark embodies a primordial duality, and your ikon splits itself accordingly into two corresponding halves. You can use an Interact action to split the imbued ikon into two copies of itself, which both gain the twin trait; these copies are identical except for one mirrored feature, such as a sun motif on one and a moon motif on another. You can use this ability again to fuse the two halves back into their original form. As these are both manifestations of the same object, your divine spark empowers the two halves as if they were a single ikon.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 'passive',
    mechanics: 'Usage: imbued into a one-handed weapon ikon.',
  },
  {
    id: 'exemplar-vow-of-mortal-defiance',
    name: 'Vow of Mortal Defiance',
    source: 'Exemplar',
    category: 'class',
    level: 1,
    description: 'Having seen the wreckage left by the gods and their servitors as they play in their great war of good and evil, you\'ve come to the only reasonable conclusion: they all must be cut from their silken thrones. You swear a vow to defeat one creature within 60 feet that has the holy or unholy trait. The first time each round that you deal damage to that creature, you deal an additional 1d6 spirit damage. You can\'t use Vow of Mortal Defiance again until you or the target is defeated, flees, or the encounter ends. Special: If you take this feat, you can\'t become sanctified with the holy or unholy trait. Retraining out of this feat typically requires a major change of philosophy.',
    implemented: 'full',
    traits: ['Auditory', 'Concentrate', 'Exemplar', 'Linguistic', 'Mental'],
    actionCost: 1,
    prerequisites: ['You are not sanctified with the holy or unholy trait.'],
  },

  // ──── Level 2 ────
  {
    id: 'exemplar-hurl-at-the-horizon',
    name: 'Hurl at the Horizon',
    source: 'Exemplar',
    category: 'class',
    level: 2,
    description: 'Your weapon flies from your hand as if propelled under its own power. The imbued ikon gains the following ability. Immanence: Your weapon gains the thrown 15 feet trait, or increases its thrown distance by 10 feet if it already has the thrown trait.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 'passive',
    mechanics: 'Usage: imbued into a thrown or melee weapon ikon. Immanence: gains thrown 15 feet or +10 feet thrown distance.',
  },
  {
    id: 'exemplar-leap-the-falls',
    name: 'Leap the Falls',
    source: 'Exemplar',
    category: 'class',
    level: 2,
    description: 'Reinforcing your legs with divine energy, you can leap the battlefield as powerfully as a salmon clearing a waterfall. The imbued ikon gains the following ability. Immanence: You gain the Powerful Leap and Quick Jump skill feats, allowing you to jump further and faster, even if you do not meet the prerequisites for them.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 'passive',
    mechanics: 'Usage: imbued into a body ikon. Immanence: grants Powerful Leap and Quick Jump skill feats.',
  },
  {
    id: 'exemplar-lightning-swap',
    name: 'Lightning Swap',
    source: 'Exemplar',
    category: 'class',
    level: 2,
    description: 'You have practiced quickly switching between combat styles and the equipment needed for them. You Interact to stow any number of items from your hands, then draw up to two weapons or a shield and a weapon.',
    implemented: 'full',
    traits: ['Exemplar', 'Fighter', 'Flourish'],
    actionCost: 1,
  },
  {
    id: 'exemplar-red-gold-mortality',
    name: 'Red-Gold Mortality',
    source: 'Exemplar',
    category: 'class',
    level: 2,
    description: 'By channeling your divinity into a creature along with a strike, you can disrupt their ability to recover. The imbued ikon gains the following ability. Immanence: When you successfully damage an enemy with the ikon, a marking appears around the wound, painted in the red of mortal blood and the gold of divine ichor. When the target would regain Hit Points, such as from a healing effect or an ability like fast healing or regeneration, it must attempt a Will save against your class DC to determine the effects, and then the marking fades. The marking otherwise fades after 1 minute. Success: The creature regains the full number of Hit Points that would be healed. Failure: The creature regains only half the number of Hit Points as the contradictory energies swirl within it. Critical Failure: The creature doesn\'t regain any Hit Points.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon', 'Void'],
    actionCost: 'passive',
    mechanics: 'Usage: imbued into a weapon ikon. Immanence: marks target on hit; target must Will save to heal (success full, failure half, crit failure none). Mark fades after 1 minute.',
  },

  // ──── Level 4 ────
  {
    id: 'exemplar-follow-the-threads-of-fate',
    name: 'Follow the Threads of Fate',
    source: 'Exemplar',
    category: 'class',
    level: 4,
    description: 'A norn\'s thread — spun from fate itself — runs through or wraps around your ikon. Transcendence (1-action; fortune, transcendence): You pluck a single thread from your ikon, which ties itself in three loops about your wrist, where it remains for the next minute. If you fail an attack roll or skill check, and a +1 status bonus would change your failure into a success or your success into a critical success, you gain a +1 status bonus to this check retroactively, changing the outcome appropriately as the thread pulls you to the future you desire. The thread then falls from your wrist. You can have only one thread in existence at a time.',
    implemented: 'full',
    traits: ['Uncommon', 'Exemplar', 'Fortune', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a worn ikon made of cloth or a weapon ikon with a tassel, wrapping, or similar feature. Transcendence: retroactive +1 status bonus if it changes failure to success.',
  },
  {
    id: 'exemplar-only-the-worthy',
    name: 'Only the Worthy',
    source: 'Exemplar',
    category: 'class',
    level: 4,
    description: 'You can designate your ikons as movable by only your own hand, leaving them fixed in place as surely as if they were lodged in stone. Whenever you Release an ikon, you can spend an action to command it to remain motionless. While motionless, the ikon can be moved only if 8,000 pounds of pressure are applied to it or if a creature uses Athletics to Force Open the ikon with a DC equal to your class DC. You can Release your ikon over an adjacent prone enemy to hold them down with the ikon\'s motionlessness — while so Released, you can\'t use the ikon, but the enemy must succeed at the Athletics check to Stand or to move. The ikon automatically flies back to your hand when the effect is broken or if you spend an Interact action to hold out a hand and draw it back.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 'passive',
  },
  {
    id: 'exemplar-steel-on-steel',
    name: 'Steel on Steel',
    source: 'Exemplar',
    category: 'class',
    level: 4,
    description: 'The ring of divinely empowered steel assails your enemies. Transcendence — Ringing Challenge (2-actions; sonic, spirit, transcendence): You clang your ikon against a weapon, shield, or the ground, emitting a shock wave that deals 1d4 spirit damage and 1d4 sonic damage to all creatures in a 30-foot cone or 15-foot emanation (basic Fortitude save). A creature that critically fails its saving throw is deafened for 1 minute. At 6th level and every 2 levels thereafter, the damage increases by 1d4 spirit damage and 1d4 sonic damage.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a melee weapon ikon or worn ikon made of metal, stone, or a similarly hard material. Transcendence: 30-ft cone or 15-ft emanation, 1d4 spirit + 1d4 sonic (basic Fort), crit fail = deafened 1 min. +1d4+1d4 per 2 levels after 4th.',
  },
  {
    id: 'exemplar-through-the-needles-eye',
    name: 'Through the Needle\'s Eye',
    source: 'Exemplar',
    category: 'class',
    level: 4,
    description: 'Your weapon strikes with the perfection your will demands. Transcendence — Blinding of the Needle (2-actions; transcendence): You aim your weapon in a superficial cut above your opponent\'s eye. Make a Strike with the imbued ikon. If that Strike is successful, the target must succeed at a Fortitude save against your class DC or become blinded for 1 round or until it uses an Interact action to clear the blood from its vision.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a weapon ikon. Transcendence: Strike + Fortitude save or blinded for 1 round (Interact to clear).',
  },
  {
    id: 'exemplar-topple-the-titans',
    name: 'Topple the Titans',
    source: 'Exemplar',
    category: 'class',
    level: 4,
    description: 'Even the greatest titans of the world are easier to kill when they\'re lying on the ground. You\'ve made it your mission to topple such giants and can make others fall with a force that shakes the very earth. The triggering creature\'s toppling body shakes the ground, emitting a quake in a 10-foot emanation from their space. Apply the result of your triggering Athletics check against the Reflex DC of each creature in the emanation to Trip them as well. You do not need to have a hand free, and you do not lose your balance if any of your attempts to Trip are a critical failure.',
    implemented: 'full',
    traits: ['Uncommon', 'Exemplar'],
    actionCost: 1,
    mechanics: 'Frequency: once per minute. Requirements: Your previous action was a successful or critically successful Trip against a creature at least one size larger than you, and the enemy became prone.',
  },

  // ──── Level 6 ────
  {
    id: 'exemplar-binding-serpents-celestial-arrow',
    name: 'Binding Serpents Celestial Arrow',
    source: 'Exemplar',
    category: 'class',
    level: 6,
    description: 'As you prepare to shoot your weapon, you invoke divine serpents that bind your enemies. The imbued ikon gains the following ability. Transcendence — Coiling Serpents (2-actions; transcendence): Make a ranged Strike with your ikon. If the Strike hits, the target must succeed at a Reflex save against your class DC or the arrow transforms into a multitude of ethereal snakes that coil around the target, immobilizing it until it succeeds at an Escape attempt against your class DC.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a ranged weapon ikon, or a melee weapon ikon with the thrown trait. Transcendence: ranged Strike, Reflex save or immobilized (Escape to end).',
  },
  {
    id: 'exemplar-flow-of-war',
    name: 'Flow of War',
    source: 'Exemplar',
    category: 'class',
    level: 6,
    description: 'Divine battle instincts take over your body, letting you move and lash out with instinctive speed. You become quickened until the end of your turn and can use the extra action only to Strike or Stride.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'free',
    mechanics: 'Trigger: Your turn begins. Frequency: once per hour.',
  },
  {
    id: 'exemplar-motionless-cutter',
    name: 'Motionless Cutter',
    source: 'Exemplar',
    category: 'class',
    level: 6,
    description: 'Your weapon is so sharp even an insect alighting upon its still blade would be severed. Your weapon ikon gains the following ability. Transcendence — Sever Four Dragonfly Wings (3-actions; transcendence): Make a Strike that deals slashing damage with your weapon ikon. If that Strike is successful, you can immediately make an additional Strike against a different target within your reach. You can continue making Strikes in this manner, each against a different target, until you have made a total of four Strikes or you miss with a Strike, whichever comes first. Each attack counts toward your multiple attack penalty, but you do not increase your penalty until you have made all your attacks.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 3,
    mechanics: 'Usage: imbued into a melee weapon ikon that deals slashing damage. Transcendence: up to 4 Strikes against different targets, MAP doesn\'t increase until all attacks made.',
  },
  {
    id: 'exemplar-reactive-strike',
    name: 'Reactive Strike',
    source: 'Exemplar',
    category: 'class',
    level: 6,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Champion', 'Commander', 'Exemplar', 'Guardian', 'Magus', 'Swashbuckler'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature within your reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it\'s using.',
  },
  {
    id: 'exemplar-riddle-the-sphinx',
    name: 'Riddle the Sphinx',
    source: 'Exemplar',
    category: 'class',
    level: 6,
    description: 'You\'ve learned the secrets of the sphinx\'s riddles and empowered your ikon with them. You can voice these mysteries, forcing others to overcome them as you did. Transcendence — Tangle in Riddle (1-action; auditory, mental, transcendence): You speak a bizarre koan that transcends language and is understood by only one creature within 30 feet. The target must attempt a Will save against your class DC. It\'s then immune to this ability for 1 hour. Critical Success: The target is unaffected. Success: The target is stupefied 1 for 1 round. Failure: The target is stupefied 1 for 1d4 rounds. Critical Failure: The target is stupefied 1 and confused for 1d4 rounds.',
    implemented: 'full',
    traits: ['Uncommon', 'Exemplar', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a body ikon. Transcendence: Will save or stupefied 1 (1 round on success, 1d4 rounds on failure, stupefied 1 + confused 1d4 rounds on crit fail). Immune 1 hour.',
  },
  {
    id: 'exemplar-shield-of-stone',
    name: 'Shield of Stone',
    source: 'Exemplar',
    category: 'class',
    level: 6,
    description: 'You stole a gorgon\'s gaze and trapped it in your ikon. You\'ve learned how to brandish it for your advantage, subduing the rage of the trapped gaze by turning it on your enemies. Transcendence — Brandish the Gorgon\'s Gaze (1-action; earth, transcendence, visual): You Raise your mirrored aegis, though it seems to lose some of its usual luster in favor of the dull sheen of stone. If you Shield Block a melee attack with the mirrored aegis before the beginning of your next turn, the gorgon\'s eyes upon it flash at the triggering creature, who must attempt a Fortitude save against your class DC. On a failure, they are slowed 1 for 1 minute as their body partially petrifies. Regardless of the outcome, that creature is temporarily immune to this effect for 24 hours.',
    implemented: 'full',
    traits: ['Uncommon', 'Exemplar', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into the mirrored aegis. Transcendence: Raise shield, if you Shield Block melee attack the attacker must Fort save or be slowed 1 for 1 min. Immune 24 hrs.',
  },

  // ──── Level 8 ────
  {
    id: 'exemplar-additional-ikon',
    name: 'Additional Ikon',
    source: 'Exemplar',
    category: 'class',
    level: 8,
    description: 'Your story has grown rich enough that three ikons can\'t contain its full complexity. You gain a fourth ikon, which can be of any type.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'passive',
  },
  {
    id: 'exemplar-as-a-thousand-soldiers',
    name: 'As a Thousand Soldiers',
    source: 'Exemplar',
    category: 'class',
    level: 8,
    description: 'Though you may have stolen from the hive, you\'ve nothing but respect for the armies guarding it, and you borrow their strength to overwhelm your foes. Your body transforms into a swarm of bees. You Fly up to twice your Speed; during this movement you can pass through any space that would be small enough for a single insect, and your movement does not trigger reactions. If you pass through an enemy\'s space, you can inflict a storm of stings that deals 3d4 piercing damage and 3d4 poison damage, with a basic Reflex save against your class DC. At the end of your movement, you return to your original form. At 10th level and every two levels thereafter, the damage increases by 1d4 piercing damage and 1d4 poison damage.',
    implemented: 'full',
    traits: ['Uncommon', 'Concentrate', 'Divine', 'Exemplar', 'Polymorph'],
    actionCost: 2,
    prerequisites: ['plunderer of the hive\'s riches'],
    mechanics: 'Frequency: once per hour. Fly 2x Speed through tiny spaces, no reactions triggered, 3d4 piercing + 3d4 poison to enemies passed through (basic Reflex). +1d4+1d4 per 2 levels after 8th.',
  },
  {
    id: 'exemplar-battle-hymn-to-the-lost',
    name: 'Battle Hymn to the Lost',
    source: 'Exemplar',
    category: 'class',
    level: 8,
    description: 'Your movements in combat are an artistic dirge to those spirits who could not fight to see another day. You make a Strike. Regardless of whether the Strike succeeds, spirits of warriors who died gloriously in battle surge out to attack with you. They appear in a 30-foot cone if you make a melee Strike or in a 10-foot emanation around your target if you made a ranged Strike. Each enemy in the area takes 2d10 damage with a basic Reflex save against your class DC; you choose whether the damage is bludgeoning, piercing, or slashing. At 12th level and every 4 levels thereafter, the damage increases by 1d10. As they join the battle, the spirits call your fallen allies back to the fight. Any of your allies in the area who are dying regain Hit Points equal to the damage you rolled. This is a divine, healing, vitality effect.',
    implemented: 'full',
    traits: ['Concentrate', 'Divine', 'Exemplar'],
    actionCost: 2,
    prerequisites: ['of verse unbroken or peerless under heaven'],
    mechanics: 'Frequency: once per hour. Strike + 2d10 B/P/S in 30-ft cone (melee) or 10-ft emanation (ranged), basic Reflex. +1d10 per 4 levels after 8th. Dying allies in area regain HP equal to damage rolled.',
  },
  {
    id: 'exemplar-forward-gaze-into-life',
    name: 'Forward Gaze into Life',
    source: 'Exemplar',
    category: 'class',
    level: 8,
    description: 'Despite the constant cold of death at your back, you keep your gaze forward into the realm of life. You release two 15-foot cones, aimed exactly opposite each other, one ahead of you that deals 5d10 vitality damage and one behind you that deals 5d10 void damage, each with a basic Reflex save against your class DC. Creatures that critically fail also take 5 persistent damage, of the same damage type dealt.',
    implemented: 'full',
    traits: ['Uncommon', 'Concentrate', 'Divine', 'Exemplar', 'Vitality', 'Void'],
    actionCost: 2,
    prerequisites: ['trespasser in death\'s realm'],
    mechanics: 'Frequency: once per hour. Two opposed 15-ft cones: forward 5d10 vitality, backward 5d10 void (basic Reflex). Crit fail: 5 persistent damage.',
  },
  {
    id: 'exemplar-raise-island',
    name: 'Raise Island',
    source: 'Exemplar',
    category: 'class',
    level: 8,
    description: 'You churn the sea and fish up stone so your enemies together can receive their punishment. Each enemy in a 30-foot emanation must succeed at a Fortitude save against your class DC or be swept up to 15 feet to another location of your choice within the affected area and become off-guard until the start of your next turn. Then, if you\'re on a surface, a pillar of earth rises underneath you and lasts for 1 minute. The pillar is 10 feet tall, and its surface includes your space and a 5-foot emanation around you. After the pillar rises, you can attempt a melee Strike against one enemy in reach.',
    implemented: 'full',
    traits: ['Concentrate', 'Divine', 'Exemplar'],
    actionCost: 3,
    prerequisites: ['born of the bones of the earth or restless as the tides'],
    mechanics: 'Frequency: once per hour. 30-ft emanation, Fort save or swept 15 ft + off-guard. Creates 10-ft tall pillar under you for 1 min. Free melee Strike after.',
  },
  {
    id: 'exemplar-rejoice-in-solstice-storm',
    name: 'Rejoice in Solstice Storm',
    source: 'Exemplar',
    category: 'class',
    level: 8,
    description: 'You hold your arms out, and the fury of the seasons comes to your jubilant embrace. A storm spirals out from you, dealing 5d8 damage to each creature in a 30-foot emanation, with a basic Reflex save against your class DC. At 10th level and every 2 levels thereafter, the damage increases by 1d8. The emanation is quartered into four non-overlapping cones, each of a different season, which must be arranged clockwise from spring, to summer, to fall, to winter. Each cone has different traits, damage type, and a different effect to a creature that critically fails its saving throw; a creature large enough to be in multiple seasons can choose which it is affected by. Spring (electricity): Spring lightning deals electricity damage. Creatures who critically fail are left numb, becoming clumsy 2 until the end of their next turn. Summer (water): A summer monsoon deals bludgeoning damage. Creatures who critically fail are knocked prone by hurricane winds. Fall (emotion, mental, wood): Falling leaves deal slashing damage. Creatures who critically fail are gripped by melancholy, becoming off-guard until the end of their next turn. Winter (cold): A blizzard deals cold damage. Creatures who critically fail are stupefied 2 until the end of their next turn as the cold numbs their senses.',
    implemented: 'full',
    traits: ['Concentrate', 'Divine', 'Exemplar', 'Manipulate'],
    actionCost: 2,
    prerequisites: ['whose cry is thunder or dancer in the seasons'],
    mechanics: 'Frequency: once per hour. 30-ft emanation quartered by season: spring (electricity, clumsy 2), summer (bludgeoning, prone), fall (slashing, off-guard), winter (cold, stupefied 2). 5d8 basic Reflex, +1d8 per 2 levels after 8th.',
  },

  // ──── Level 10 ────
  {
    id: 'exemplar-breath-of-vital-ash',
    name: 'Breath of Vital Ash',
    source: 'Exemplar',
    category: 'class',
    level: 10,
    description: 'Reddish ash stains your ikon, impossible to clean off. Every time you exhale, a tinge of red and a scent of spiced smoke float upon your breath. The imbued ikon gains the following ability. Transcendence — Mark the Center (1-action; transcendence): You hold a hand to your lips and exhale, releasing enchanted red ash in a 15-foot cone. The ash clings to the vital areas of each enemy in the area for 1 minute. When a creature marked by the ash is hit and dealt damage by a Strike, it takes an additional 4d6 precision or vitality damage, then its mark ends. The damage type is whichever is worse for the creature, as determined by the GM. At 13th level and every 3 levels thereafter, the damage increases by 1d6.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a body ikon. Transcendence: 15-ft cone, marks enemies for 1 min. First Strike deals +4d6 precision or vitality, +1d6 per 3 levels after 10th.',
  },
  {
    id: 'exemplar-exult-in-violence',
    name: 'Exult in Violence',
    source: 'Exemplar',
    category: 'class',
    level: 10,
    description: 'You let out a war cry as your blow lands true, and judgment descends on an enemy. A pillar of light deals 4d6 spirit damage with a basic Reflex save against your class DC to a different enemy selected at random within 30 feet of the target struck. This damage increases to 7d6 if you are 12th level and 10d6 if you are 17th level.',
    implemented: 'full',
    traits: ['Concentrate', 'Divine', 'Exemplar', 'Light', 'Spirit'],
    actionCost: 1,
    mechanics: 'Requirements: You critically hit an enemy this turn. Random enemy within 30 ft takes 4d6 spirit (basic Reflex), 7d6 at L12, 10d6 at L17.',
  },
  {
    id: 'exemplar-fish-from-the-falls-edge',
    name: 'Fish from the Falls\' Edge',
    source: 'Exemplar',
    category: 'class',
    level: 10,
    description: 'Seeing your ally fall, you let out a cry, sending your divine spark to them temporarily to keep them from tumbling down the River of Souls. You prevent the triggering creature from dying and restore 5d8 Hit Points to them. The ally is invigorated by the touch of your divine power, gaining a +1 status bonus to their saving throws and AC for 1 round. Your divine spark remains with your ally, preventing you from gaining any of your ikons\' immanence effects until the start of your next turn, when it returns to an ikon of your choice.',
    implemented: 'full',
    traits: ['Divine', 'Exemplar', 'Healing', 'Vitality'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A living creature within 30 feet would die. Frequency: once per day. Requirements: Your divine spark is empowering one of your ikons. Restores 5d8 HP, +1 status to saves and AC for 1 round. Spark leaves your ikons until next turn.',
  },
  {
    id: 'exemplar-journey-of-the-sky-chariot',
    name: 'Journey of the Sky Chariot',
    source: 'Exemplar',
    category: 'class',
    level: 10,
    description: 'Small wings, flaming wheels, or another signifier of flight sprout from your ikon as it gains the power to lift you from the ground. Your ikon gains the following effects. Immanence: Your ikon keeps you hovering even without conscious effort. You can remain in the air at the end of this turn, even if you didn\'t use a Fly action. Transcendence — Race the Skies (1-action; concentrate, transcendence): You take your place among the heavens. For 1 minute, you gain a fly Speed equal to your Speed or 20 feet, whichever is greater.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a body ikon or worn ikon. Immanence: hover without Fly action. Transcendence: gain fly Speed (your Speed or 20 ft, whichever is greater) for 1 min.',
  },
  {
    id: 'exemplar-mated-birds-in-paired-flight',
    name: 'Mated Birds in Paired Flight',
    source: 'Exemplar',
    category: 'class',
    level: 10,
    description: 'Your ikons bond like a pair of one-winged birds. This feat can be imbued in either a single ikon with multiple copies, such as one produced by the shadow sheath or with the Twin Stars feat, or two separate ikons (bypassing the normal limit per ikon feat). Immanence: As long as you hold one ikon, the other will return to find its partner. Both ikons gain the returning rune. Transcendence — Rejoin in Flight (2-actions; transcendence): You throw your weapon ikons to either side of a creature, and they seek each other out, converging on the target. Make two thrown Strikes against a target within the first range increment of both your weapon ikons. This counts as two attacks toward your multiple attack penalty, but the penalty doesn\'t increase until after you\'ve made both attacks. The target is flanked for both attacks (typically making it off-guard against both attacks). If both Strikes hit, the target also takes an additional die of weapon damage. The weapons then return to your hand.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued in one or two weapon ikons that both have the thrown trait. Immanence: both ikons gain returning rune. Transcendence: 2 thrown Strikes, target flanked, +1 weapon die if both hit, MAP doesn\'t increase until both attacks made.',
  },

  // ──── Level 12 ────
  {
    id: 'exemplar-compliant-gold',
    name: 'Compliant Gold',
    source: 'Exemplar',
    category: 'class',
    level: 12,
    description: 'You can command your weapon to shrink or grow, for convenience or power. Even when your ikon is not empowered, you can shrink it to a miniature size (with negligible Bulk) and keep it tucked behind an ear, in your hair, or in a similar discreet location. You can shrink your weapon or regrow it to its normal size as part of drawing it, putting it away, swapping it, or picking it up. Immanence: Your ikon gains the reach trait. If it already had the reach trait, it instead increases your reach by an additional 10 feet, instead of the usual additional 5 feet. Transcendence — Topple the Pillar of Heaven (2-actions; transcendence): Your ikon extends to an impossible length, striking all in its way. You deal 6d8 damage to all creatures in a 60-foot line, with a basic Reflex save against your class DC. The damage type matches that of your weapon. At 14th level and every two levels thereafter, the damage increases by 1d8.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a melee weapon ikon. Immanence: gains reach (+10 ft if already reach). Transcendence: 60-ft line, 6d8 weapon damage (basic Reflex), +1d8 per 2 levels after 12th.',
  },
  {
    id: 'exemplar-extract-vow-of-nonviolence',
    name: 'Extract Vow of Nonviolence',
    source: 'Exemplar',
    category: 'class',
    level: 12,
    description: 'You entice or threaten a weapon, making it swear not to harm you. Attempt a Diplomacy check to Request or an Intimidation check to Demoralize against one weapon within 60 feet — even though most weapons are inanimate and mindless, your words somehow still can affect it as if it were living and you shared a language. The DC for this check is the Will DC of the creature wielding the weapon or a moderate DC for the weapon\'s level if it\'s unattended. If the weapon is an intelligent item, use its Will DC. Regardless of the result of the save, the weapon is then temporarily immune to Extract Vow of Nonviolence for 1 day. Critical Success: The object swears not to hurt you. You gain resistance to all damage dealt by that specific weapon as the weapon attempts to mitigate harm to you. The resistance is equal to half your level and lasts for 10 minutes. Success: As critical success, but the remaining duration decreases by 1 minute each time the weapon hits you (even if it deals no damage). Special: When you gain this feat, choose cold iron, duskwood, dawnsilver, or silver. For some reason — perhaps because you underestimate this material, or because you think it a friend — you are forever unable to use Extract Vow of Nonviolence on objects composed of the chosen material.',
    implemented: 'full',
    traits: ['Auditory', 'Concentrate', 'Exemplar'],
    actionCost: 2,
  },
  {
    id: 'exemplar-rapid-spark',
    name: 'Rapid Spark',
    source: 'Exemplar',
    category: 'class',
    level: 12,
    description: 'Your spark shifts to where it needs to be. You Shift Immanence.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'free',
    mechanics: 'Trigger: Your turn begins. Frequency: once per day.',
  },
  {
    id: 'exemplar-warped-by-rage',
    name: 'Warped by Rage',
    source: 'Exemplar',
    category: 'class',
    level: 12,
    description: 'Rage courses through your body, transforming you into a beast of battle. The imbued ikon gains the following abilities. Immanence: You\'re affected by a 4th-rank enlarge spell. You can choose to forgo this effect when your body ikon becomes empowered. Transcendence — Spasm of the Berserker (1-action; transcendence): Your body warps beyond recognition into a powerful, one-eyed form. You\'re affected by a 4th-rank enlarge spell and a 6th-rank moon frenzy spell, which both last until the end of your next turn. You can\'t attempt to end the moon frenzy early. If this ikon becomes empowered again, you can extend Spasm of the Berserker\'s duration until the end of your next turn. While you\'re already affected by Spasm of the Berserker, the transcend action becomes a free action to extend its duration until the end of your next turn.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon', 'Morph'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a body or worn ikon. Immanence: 4th-rank enlarge (optional). Transcendence: 4th-rank enlarge + 6th-rank moon frenzy until end of next turn, can extend as free action.',
  },

  // ──── Level 14 ────
  {
    id: 'exemplar-complete-the-heros-journey',
    name: 'Complete the Hero\'s Journey',
    source: 'Exemplar',
    category: 'class',
    level: 14,
    description: 'As your divine spark travels through each of your ikons in turn, it gains power, culminating its journey when it enters your third ikon. You Spark Transcendence of your final ikon, but instead of its normal effect, the item casts the 3-action version of harm or heal heightened to half your level rounded up.',
    implemented: 'full',
    traits: ['Exemplar', 'Healing', 'Transcendence'],
    actionCost: 1,
    mechanics: 'Frequency: once per 10 minutes. Requirements: You have Sparked Transcendence of at least two different ikons in the last 10 minutes, and your divine spark currently dwells in a third ikon.',
  },
  {
    id: 'exemplar-destined-victory',
    name: 'Destined Victory',
    source: 'Exemplar',
    category: 'class',
    level: 14,
    description: 'You demand a battle against your chosen enemy. The imbued ikon gains the following abilities. Immanence: Whenever an enemy successfully Strikes you with a melee weapon, you gain a +2 status bonus to your AC against the next attack from that enemy before the start of your next turn. Transcendence — Only You and I (1-action; concentrate, transcendence): You draw your foe into a fated conflict — one you know you\'ll win. Choose an enemy within your reach. Until the end of your next turn, that enemy gains a +2 circumstance bonus to attack rolls it makes against you, but it must attempt a Will save against your class DC whenever it tries to move away from you, Strike a target other than you, or Cast a Spell that doesn\'t include you as a target. On a failure, the action or actions related to the failed attempt is disrupted. Whenever the enemy misses you with a Strike while this effect is active, you heal 1d8+5 Hit Points.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a worn ikon. Immanence: +2 status AC vs next attack from enemy that hit you. Transcendence: force enemy to fight only you (Will save to take other actions), heal 1d8+5 on enemy miss.',
  },
  {
    id: 'exemplar-infinite-blades-celestial-arrow',
    name: 'Infinite Blades Celestial Arrow',
    source: 'Exemplar',
    category: 'class',
    level: 14,
    description: 'Each shot you launch multiplies itself with spiritual blades, rings, and other missiles that shower upon your foes. Your weapon ikon gains the following abilities. Immanence: Whenever you successfully Strike an enemy with your weapon ikon, up to two enemies adjacent to the target take spirit damage equal to your weapon ikon\'s damage dice as they are struck by duplicated missiles. Transcendence — Heaven Rains an Ending (3-actions; transcendence): You shoot an arrow that multiplies into a dense cloud of weapons. Make one ranged Strike with a -2 penalty against each enemy you are aware of within a cone as long as your weapon\'s first range increment. Roll the damage only once for all targets, and all the Strike\'s damage is spirit damage instead of its normal type. Each attack counts toward your multiple attack penalty, the penalty doesn\'t increase until you have made all your attacks.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 3,
    mechanics: 'Usage: imbued into a ranged weapon ikon. Immanence: adjacent enemies take spirit damage equal to weapon dice on hit. Transcendence: Strike every aware enemy in weapon range cone at -2, spirit damage, MAP doesn\'t increase until all attacks made.',
  },

  // ──── Level 16 ────
  {
    id: 'exemplar-crown-of-rule',
    name: 'Crown of Rule',
    source: 'Exemplar',
    category: 'class',
    level: 16,
    description: 'This badge of office proclaims your sovereignty. The imbued ikon gains the following ability. Transcendence — Heavy is the Crown (2-actions; concentrate, mental, spirit, transcendence): The weight of authority falls heavily upon you, as well as nearby creatures. All enemies in a 15-foot burst within 60 feet take spirit damage equal to your level with a basic Will save against your class DC. Any enemy that fails its save must immediately kneel, dropping prone as a free action.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a worn ikon or a body ikon. Transcendence: 15-ft burst within 60 ft, spirit damage = level (basic Will), failure = prone.',
  },
  {
    id: 'exemplar-gift-of-the-immortal-herb',
    name: 'Gift of the Immortal Herb',
    source: 'Exemplar',
    category: 'class',
    level: 16,
    description: 'Your blood turns a divine gold, shining in moments it\'s spilled and begetting new life. The imbued ikon gains the following effects. Immanence: If your divine spark remains in your body ikon for 10 continuous minutes, you regrow one damaged or ruined limb or organ. Transcendence — Shed the Mortal Skin (1-action; healing, light, transcendence, vitality): Like the serpent, that most ancient of immortals, you shed your skin, revealing a glowing divine form. If you are currently taking persistent fire or acid damage, you immediately end the effect. Until the beginning of your next turn, you shed bright light in a 20-foot radius (and dim light for the next 20 feet) like a torch. The next time you are dealt damage by an enemy before the beginning of your next turn, you shed glowing ichor in a square adjacent to you, and where it hits the earth, a glowing, thorned herb grows. A creature other than you can pluck and consume the herb with an Interact action to regain a number of Hit Points equal to half of the damage you were dealt by the attack that sprouted the herb.',
    implemented: 'full',
    traits: ['Exemplar', 'Healing', 'Ikon', 'Light', 'Vitality'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a body ikon. Immanence: regrow limb/organ after 10 min. Transcendence: end persistent fire/acid, shed light, next damage creates herb that heals ally for half damage taken.',
  },
  {
    id: 'exemplar-mark-of-the-sage',
    name: 'Mark of the Sage',
    source: 'Exemplar',
    category: 'class',
    level: 16,
    description: 'Your ikon gains a pin, stripe, or similar marking showing you as a master of your craft. The imbued ikon gains the following ability. Transcendence — A Challenge for Heroes (2-actions; concentrate, mental, spirit, transcendence): You declare an enemy within 60 feet to be a heroic test. For 1 minute, that enemy deals an additional 10 spirit damage to you with each successful Strike or spell it targets you with. Whenever that enemy deals spirit damage to you, each ally who has the enemy in melee reach can attempt a Reactive Strike against it, even if the ally doesn\'t normally have that reaction. If an ally successfully slays the enemy with a Reactive Strike due to this effect, that ally immediately gains temporary Hit Points equal to your level, which persist for 1 minute.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a worn ikon. Transcendence: enemy deals +10 spirit damage to you, but allies get free Reactive Strikes. Ally that slays enemy gains temp HP = your level for 1 min.',
  },
  {
    id: 'exemplar-shroud-of-ghosts',
    name: 'Shroud of Ghosts',
    source: 'Exemplar',
    category: 'class',
    level: 16,
    description: 'Your ikon is connected to the world of the spirits, allowing you to partially fade into their realm. The imbued ikon gains the following ability. Transcendence — Skirt the Underworld (2-actions; concentrate, illusion, incapacitation, transcendence): You skirt into the world of the dead, becoming invisible for 1 round, then Fly up to your Speed. Each enemy adjacent to you at any point during this movement must succeed at a Fortitude save against your class DC or become blinded for 1 minute (or permanently on a critical failure). For each creature blinded by this effect, the duration of the granted invisibility extends by 1 round. Undead and other creatures with strong ties to the world of the dead, such as psychopomps, are immune to this effect.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a worn ikon. Transcendence: invisible 1 round then Fly your Speed, adjacent enemies Fort save or blinded 1 min (permanent on crit fail). +1 round invisibility per blinded creature.',
  },
  {
    id: 'exemplar-strike-rivers-seize-winds',
    name: 'Strike Rivers, Seize Winds',
    source: 'Exemplar',
    category: 'class',
    level: 16,
    description: 'Through sheer physical force, you can wrestle a river, lasso the winds, punch a hole to the molten center of the planet, or create other environmental disturbances via nothing but your own strength. You can create each of the following spell effects at the listed rank, but you can\'t create effects more than once per hour and you can\'t perform a given effect more than once per day: 4th hydraulic torrent, 5th control water, 6th howling blizzard, 7th volcanic eruption, 8th punishing winds. Creating the effects requires the same type and number of actions as Casting the Spell, and they use the higher of your class DC or spell DC when appropriate. Because you are creating these effects with your godly might rather than Casting a Spell, they can\'t be dispelled or counteracted.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'passive',
    mechanics: 'Frequency: once per hour (can\'t repeat a given effect more than once per day). Spell effects: 4th hydraulic torrent, 5th control water, 6th howling blizzard, 7th volcanic eruption, 8th punishing winds. Can\'t be dispelled or counteracted.',
  },

  // ──── Level 18 ────
  {
    id: 'exemplar-branched-tree-of-pain',
    name: 'Branched Tree of Pain',
    source: 'Exemplar',
    category: 'class',
    level: 18,
    description: 'The blade of your ikon takes one or more notches, capable of dealing mortal pain to your foes. Immanence: When you Strike with the ikon, you critically succeed if you roll a 19 on the die as long as that result would be a success. This has no effect on a 19 if the result would be a failure. Transcendence — Plant Thirty Barbs (1-action; death, transcendence): You snap off a fragment of your ikon within your opponent\'s body, which threatens to burst into numerous barbs. Make a Strike with your ikon. If successful, barbs fill the target, dealing two dice of weapon damage the first time the creature uses a move action on each of its turns; the barbs are made out of the same material as your weapon ikon and bypass resistances and such accordingly (for instance, a cold iron spear would create cold iron barbs). The barbs last for 1d4 rounds. If the target dies while the barbs are still in their body, the barbs burst forth in a forest of thorns covering the creature\'s space, which are greater difficult terrain and deal piercing damage equal to half your level for each square that is moved into.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 1,
    mechanics: 'Usage: imbued into a weapon ikon that deals piercing or slashing damage. Immanence: crit on natural 19 if it would be a success. Transcendence: Strike + barbs deal 2 weapon dice on move for 1d4 rounds. On death, creates greater difficult terrain.',
  },
  {
    id: 'exemplar-eternity-incinerating-blaze',
    name: 'Eternity-Incinerating Blaze',
    source: 'Exemplar',
    category: 'class',
    level: 18,
    description: 'The blaze of your divine spark is hot enough that it burns in not just the present, but the past and future as well. Whenever you score a critical hit with the imbued ikon, the target becomes doomed 1 or increases its doomed condition by 1. If the target\'s maximum dying value is reduced to 0 by this ability, it immediately dies in a flash of spiritual fire that reduces its body to ash. This effect applies even when the ikon is not empowered. The ikon also gains the following transcendence ability. Transcendence — Burn out of Time (2-actions; spirit, transcendence, void): An impossible amount of energy blazes in a sphere above you before compressing itself into your weapon. Strike one creature. The Strike deals an additional 3d8 spirit damage and 3d8 void damage. If the creature is reduced to 0 Hit Points, it\'s immediately killed and reduced to ash, not in the present, but in the recent past, erasing the consequences of their recent actions. If a creature died within the last round as a result of the incinerated target\'s actions, that creature is returned to life with 5d8 Hit Points at the location that it died as its death is retroactively undone.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon', 'Void'],
    actionCost: 2,
    mechanics: 'Usage: imbued into a weapon ikon. Crit hit = doomed 1 (even not empowered). Transcendence: Strike + 3d8 spirit + 3d8 void. Kill = retroactive death, can undo ally death from last round (revive with 5d8 HP).',
  },
  {
    id: 'exemplar-seven-colored-cosmic-bridge',
    name: 'Seven-Colored Cosmic Bridge',
    source: 'Exemplar',
    category: 'class',
    level: 18,
    description: 'Your divine spark shines in a riot of shimmering colors, capable of carrying you through the world as fast as light itself. The imbued ikon gains the following abilities. Immanence (light, teleportation): Your weapon scatters rainbow-colored light across nearby surroundings, each a possible destination. When you successfully Strike an enemy, you can choose to teleport to an unoccupied location within 10 feet as a free action. Transcendence — Fleeting Arc through Heaven and Earth (3-actions; light, spirit, teleportation, transcendence): You swing your weapon in a wide arc, releasing a blazing rainbow that deals 9d6 spirit damage and 9d6 damage of the same type as your weapon to all enemies in a 60-foot cone, with a basic Fortitude save against your class DC. As the rainbow ripples out, you use it as a bridge to teleport to any location within the effect\'s area.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 3,
    mechanics: 'Usage: imbued into a melee weapon ikon. Immanence: teleport 10 ft on successful Strike (free action). Transcendence: 60-ft cone, 9d6 spirit + 9d6 weapon damage (basic Fort), teleport anywhere in area.',
  },
  {
    id: 'exemplar-sunwrecker',
    name: 'Sunwrecker',
    source: 'Exemplar',
    category: 'class',
    level: 18,
    description: 'Your weapon has the might of legends, capable of shooting or striking any light out of the sky. The imbued ikon gains the following abilities. Immanence (darkness): On a successful critical hit with the weapon, the weapon casts 2nd-rank darkness centered on the target of the attack. Transcendence — Break the Sun\'s Legs (2-actions; cold, concentrate, darkness, transcendence): You make a slashing motion over the brightest source of light, whether it\'s a torch or the sun in the sky. A gash appears over the light source, visible to all, and devours the light. The entire area within a 120-foot burst around you is affected by a 9th-rank darkness spell for 1 minute. The stolen light is channeled to your eyes, granting you greater darkvision for the duration of the effect.',
    implemented: 'full',
    traits: ['Exemplar', 'Ikon'],
    actionCost: 2,
    mechanics: 'Usage: imbued into any weapon ikon. Immanence: crit hit casts 2nd-rank darkness on target. Transcendence: 120-ft burst 9th-rank darkness for 1 min, you gain greater darkvision.',
  },

  // ──── Level 20 ────
  {
    id: 'exemplar-cutting-without-blade',
    name: 'Cutting Without Blade',
    source: 'Exemplar',
    category: 'class',
    level: 20,
    description: 'While tales of your divine ikons have spread far and wide, you\'ve realized that, as they are all manifestations of your soul, the object itself is unnecessary. Your ikons disintegrate into golden light. Any ikon feats you\'ve taken now apply to any applicable ikon you have, not just one, and you can immediately retrain any ikon feats you selected more than once. Each day during your daily preparations, you can select one ikon feat of 16th level or lower and gain it temporarily for that day. You can place your divine spark into any object in your possession, even a nonthreatening object like a single strand of grass, to transform it into a fully functional copy of your ikon made out of pure divine radiance. You can do this as a free action immediately before or after Striking with or otherwise using the ikon.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'passive',
    subChoices: { label: 'Choose daily ikon feat', options: [
      { id: 'exemplar-twin-stars', name: 'Twin Stars (1st)' },
      { id: 'exemplar-hurl-at-the-horizon', name: 'Hurl at the Horizon (2nd)' },
      { id: 'exemplar-leap-the-falls', name: 'Leap the Falls (2nd)' },
      { id: 'exemplar-red-gold-mortality', name: 'Red-Gold Mortality (2nd)' },
      { id: 'exemplar-follow-the-threads-of-fate', name: 'Follow the Threads of Fate (4th)' },
      { id: 'exemplar-only-the-worthy', name: 'Only the Worthy (4th)' },
      { id: 'exemplar-steel-on-steel', name: 'Steel on Steel (4th)' },
      { id: 'exemplar-through-the-needles-eye', name: "Through the Needle's Eye (4th)" },
      { id: 'exemplar-binding-serpents-celestial-arrow', name: 'Binding Serpents Celestial Arrow (6th)' },
      { id: 'exemplar-motionless-cutter', name: 'Motionless Cutter (6th)' },
      { id: 'exemplar-riddle-the-sphinx', name: 'Riddle the Sphinx (6th)' },
      { id: 'exemplar-shield-of-stone', name: 'Shield of Stone (6th)' },
      { id: 'exemplar-breath-of-vital-ash', name: 'Breath of Vital Ash (10th)' },
      { id: 'exemplar-journey-of-the-sky-chariot', name: 'Journey of the Sky Chariot (10th)' },
      { id: 'exemplar-mated-birds-in-paired-flight', name: 'Mated Birds in Paired Flight (10th)' },
      { id: 'exemplar-compliant-gold', name: 'Compliant Gold (12th)' },
      { id: 'exemplar-warped-by-rage', name: 'Warped by Rage (12th)' },
      { id: 'exemplar-destined-victory', name: 'Destined Victory (14th)' },
      { id: 'exemplar-infinite-blades-celestial-arrow', name: 'Infinite Blades Celestial Arrow (14th)' },
      { id: 'exemplar-crown-of-rule', name: 'Crown of Rule (16th)' },
      { id: 'exemplar-gift-of-the-immortal-herb', name: 'Gift of the Immortal Herb (16th)' },
      { id: 'exemplar-mark-of-the-sage', name: 'Mark of the Sage (16th)' },
      { id: 'exemplar-shroud-of-ghosts', name: 'Shroud of Ghosts (16th)' },
    ] },
  },
  {
    id: 'exemplar-reach-for-immortality',
    name: 'Reach for Immortality',
    source: 'Exemplar',
    category: 'class',
    level: 20,
    description: 'Your divine spark is now a bonfire in your soul, bringing you to the very cusp of undying immortality. You cease aging. When you would die for any reason, you can Spark Transcendence as a free action that can be taken at any time, regardless of your current condition. You reach for your divine spark and seize it in your hand to survive at 0 Hit Points, purging yourself of any negative conditions. Invigorated by this return to life, you then heal yourself for half of your total Hit Points, Stand, instantly summon any held ikons to your hand, and Shift your Immanence to any of your ikons.',
    implemented: 'full',
    traits: ['Exemplar'],
    actionCost: 'passive',
    mechanics: 'Frequency: once per day. On death: free Spark Transcendence, survive at 0 HP, purge negative conditions, heal half total HP, Stand, summon ikons, Shift Immanence.',
  },
  {
    id: 'exemplar-remake-the-world',
    name: 'Remake the World',
    source: 'Exemplar',
    category: 'class',
    level: 20,
    description: 'For the briefest of moments, you can reach into the realm of true gods, gaining the power to shape reality to your will. Once per day, you can create the effects of a divine spell of 8th level or lower. The spell must be common or one to which you otherwise have access, and it costs as many actions as it would typically take to cast. Use your class DC in place of any necessary spell DC and your class DC - 10 in place of any necessary counteract modifier or spell attack modifier. Because you are creating these effects with your godly might rather than Casting a Spell, they can\'t be dispelled or counteracted.',
    implemented: 'full',
    traits: ['Divine', 'Exemplar'],
    actionCost: 'passive',
    prerequisites: ['Strike Rivers, Seize Winds'],
    mechanics: 'Frequency: once per day. Create effects of any common divine spell of 8th level or lower. Uses class DC for spell DC. Can\'t be dispelled or counteracted.',
  },
];
