/**
 * Fighter Class Features & Feats — PF2e Remastered (Player Core)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=35
 *
 * Key Attribute: STR or DEX | HP: 10 + CON
 * Perception: Expert → Master (L7, Battlefield Surveyor, +2 circ to initiative)
 * Fort: Expert → Master (L9, Battle Hardened, success→crit)
 * Reflex: Expert → Master (L15, Tempered Reflexes, success→crit)
 * Will: Trained → Expert (L3, Bravery, reduce frightened +1, success→crit vs fear)
 * Weapons: Expert simple+martial+unarmed → Master chosen group (L5, Fighter Weapon Mastery)
 *          → Master all / Legendary chosen group (L13, Weapon Legend)
 *          → Legendary all simple+martial+unarmed, Master advanced (L19, Versatile Legend)
 *   Advanced: Trained → Expert chosen group (L5) → Expert all (L13) → Master all (L19)
 * Armor: Trained all → Expert (L11, Armor Expertise) → Master (L17, Armor Mastery)
 * Class DC: Trained → Expert (L11, Fighter Expertise) → Master (L19, Versatile Legend)
 * Skills: Trained in chosen skills + INT
 *
 * Reactive Strike: Free reaction at L1 — triggers on manipulate, move, or ranged attack.
 * Shield Block: Free general feat (L1).
 * Combat Flexibility: Daily swap of fighter feats (L9); Improved Flexibility (L15) grants two.
 * Weapon Specialization: +2/+3/+4 damage by proficiency (L7); Greater (L15): +4/+6/+8.
 *
 * Class features: 16 (L1-L19)
 * Class feats: 82 (L1-L20, including feats from War of Immortals)
 */

import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION, SHIELD_BLOCK } from './sharedFeats';

// ── Fighter Class Features ──────────────────────────────

export const FIGHTER_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'fighter-reactive-strike',
    name: 'Reactive Strike',
    source: 'Player Core',
    category: 'class_feature',
    level: 1,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature within your reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it\'s using. On critical hit vs manipulate action, the action is disrupted.',
  },
  createClassFeature(SHIELD_BLOCK, 'Fighter', 1, {
    idOverride: 'fighter-shield-block',
    traits: ['General'],
  }),

  // ── Level 3 ──────────────────────────────────────────
  {
    id: 'fighter-bravery',
    name: 'Bravery',
    source: 'Player Core',
    category: 'class_feature',
    level: 3,
    description: 'Having faced countless foes and the chaos of battle, you have learned to stand strong in the face of fear and keep on fighting. Your proficiency rank for Will saves increases to expert. When you roll a success on a Will save against a fear effect, you get a critical success instead. In addition, anytime you gain the frightened condition, reduce its value by 1.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.will → expert. Frightened condition value reduced by 1 when gained. Success on Will vs fear → critical success.',
  },

  // ── Level 5 ──────────────────────────────────────────
  {
    id: 'fighter-weapon-mastery',
    name: 'Fighter Weapon Mastery',
    source: 'Player Core',
    category: 'class_feature',
    level: 5,
    description: 'Hours spent training with your preferred weapons, learning and developing new combat techniques, have made you particularly effective with your weapons of choice. Choose one weapon group. Your proficiency rank increases to master with the simple weapons, martial weapons, and unarmed attacks in that group, and to expert with the advanced weapons in that group. You gain access to the critical specialization effects of all weapons and unarmed attacks for which you have master proficiency.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'Choose one weapon group. Proficiency: simple+martial+unarmed in group → master, advanced in group → expert. Unlocks critical specialization effects for master-proficiency weapons.',
    subChoices: { label: 'Choose a weapon group', options: [
      { id: 'axe', name: 'Axe' },
      { id: 'bomb', name: 'Bomb' },
      { id: 'bow', name: 'Bow' },
      { id: 'brawling', name: 'Brawling' },
      { id: 'club', name: 'Club' },
      { id: 'crossbow', name: 'Crossbow' },
      { id: 'dart', name: 'Dart' },
      { id: 'firearm', name: 'Firearm' },
      { id: 'flail', name: 'Flail' },
      { id: 'hammer', name: 'Hammer' },
      { id: 'knife', name: 'Knife' },
      { id: 'pick', name: 'Pick' },
      { id: 'polearm', name: 'Polearm' },
      { id: 'shield', name: 'Shield' },
      { id: 'sling', name: 'Sling' },
      { id: 'spear', name: 'Spear' },
      { id: 'sword', name: 'Sword' },
    ] },
  },

  // ── Level 7 ──────────────────────────────────────────
  {
    id: 'fighter-battlefield-surveyor',
    name: 'Battlefield Surveyor',
    source: 'Player Core',
    category: 'class_feature',
    level: 7,
    description: 'Whether taking stock of an enemy army or simply standing guard, you excel at observing your foes. Your proficiency rank for Perception increases to master. In addition, you gain a +2 circumstance bonus to Perception checks for initiative, making you faster to react during combat.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.perception → master. +2 circumstance bonus to Perception checks for initiative.',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Fighter', 7, {
    idOverride: 'fighter-weapon-specialization',
  }),

  // ── Level 9 ──────────────────────────────────────────
  {
    id: 'fighter-battle-hardened',
    name: 'Battle Hardened',
    source: 'Player Core',
    category: 'class_feature',
    level: 9,
    description: 'Your experience in battle helps protect you against magic and toxins alike. Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.fortitude → master. Success on Fortitude save → critical success.',
  },
  {
    id: 'fighter-combat-flexibility',
    name: 'Combat Flexibility',
    source: 'Player Core',
    category: 'class_feature',
    level: 9,
    description: 'Through your experience in battle, you can prepare your tactics to suit different situations. When you make your daily preparations, you gain one fighter feat of 8th level or lower that you meet the prerequisites for and don\'t already have. You can use that feat until your next daily preparations. You must meet all of the feat\'s other prerequisites.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'Daily preparations: gain 1 temporary fighter feat of level 8 or lower. Must meet prerequisites. Lasts until next daily preparations.',
    subChoices: { label: 'Choose temporary fighter feat', options: [
      { id: 'fighter-combat-assessment', name: 'Combat Assessment (1st)' },
      { id: 'fighter-double-slice', name: 'Double Slice (1st)' },
      { id: 'fighter-exacting-strike', name: 'Exacting Strike (1st)' },
      { id: 'fighter-point-blank-stance', name: 'Point-Blank Stance (1st)' },
      { id: 'fighter-reactive-shield', name: 'Reactive Shield (1st)' },
      { id: 'fighter-snagging-strike', name: 'Snagging Strike (1st)' },
      { id: 'fighter-sudden-charge', name: 'Sudden Charge (1st)' },
      { id: 'fighter-vicious-swing', name: 'Vicious Swing (1st)' },
      { id: 'fighter-aggressive-block', name: 'Aggressive Block (2nd)' },
      { id: 'fighter-assisting-shot', name: 'Assisting Shot (2nd)' },
      { id: 'fighter-blade-brake', name: 'Blade Brake (2nd)' },
      { id: 'fighter-brutish-shove', name: 'Brutish Shove (2nd)' },
      { id: 'fighter-combat-grab', name: 'Combat Grab (2nd)' },
      { id: 'fighter-dueling-parry', name: 'Dueling Parry (2nd)' },
      { id: 'fighter-intimidating-strike', name: 'Intimidating Strike (2nd)' },
      { id: 'fighter-lightning-swap', name: 'Lightning Swap (2nd)' },
      { id: 'fighter-lunge', name: 'Lunge (2nd)' },
      { id: 'fighter-rebounding-toss', name: 'Rebounding Toss (2nd)' },
      { id: 'fighter-sleek-reposition', name: 'Sleek Reposition (2nd)' },
      { id: 'fighter-barreling-charge', name: 'Barreling Charge (4th)' },
      { id: 'fighter-double-shot', name: 'Double Shot (4th)' },
      { id: 'fighter-dual-handed-assault', name: 'Dual-Handed Assault (4th)' },
      { id: 'fighter-haft-striker-stance', name: 'Haft Striker Stance (4th)' },
      { id: 'fighter-parting-shot', name: 'Parting Shot (4th)' },
      { id: 'fighter-powerful-shove', name: 'Powerful Shove (4th)' },
      { id: 'fighter-quick-reversal', name: 'Quick Reversal (4th)' },
      { id: 'fighter-shielded-stride', name: 'Shielded Stride (4th)' },
      { id: 'fighter-slam-down', name: 'Slam Down (4th)' },
      { id: 'fighter-swipe', name: 'Swipe (4th)' },
      { id: 'fighter-twin-parry', name: 'Twin Parry (4th)' },
      { id: 'fighter-advanced-weapon-training', name: 'Advanced Weapon Training (6th)' },
      { id: 'fighter-advantageous-assault', name: 'Advantageous Assault (6th)' },
      { id: 'fighter-dazing-blow', name: 'Dazing Blow (6th)' },
      { id: 'fighter-disarming-stance', name: 'Disarming Stance (6th)' },
      { id: 'fighter-furious-focus', name: 'Furious Focus (6th)' },
      { id: 'fighter-guardians-deflection', name: "Guardian's Deflection (6th)" },
      { id: 'fighter-reflexive-shield', name: 'Reflexive Shield (6th)' },
      { id: 'fighter-revealing-stab', name: 'Revealing Stab (6th)' },
      { id: 'fighter-ricochet-stance', name: 'Ricochet Stance (6th)' },
      { id: 'fighter-shatter-defenses', name: 'Shatter Defenses (6th)' },
      { id: 'fighter-triple-shot', name: 'Triple Shot (6th)' },
      { id: 'fighter-blind-fight', name: 'Blind-Fight (8th)' },
      { id: 'fighter-disorienting-opening', name: 'Disorienting Opening (8th)' },
      { id: 'fighter-dueling-riposte', name: 'Dueling Riposte (8th)' },
      { id: 'fighter-felling-strike', name: 'Felling Strike (8th)' },
      { id: 'fighter-incredible-aim', name: 'Incredible Aim (8th)' },
      { id: 'fighter-positioning-assault', name: 'Positioning Assault (8th)' },
      { id: 'fighter-resounding-bravery', name: 'Resounding Bravery (8th)' },
      { id: 'fighter-sudden-leap', name: 'Sudden Leap (8th)' },
    ] },
  },

  // ── Level 11 ─────────────────────────────────────────
  {
    id: 'fighter-armor-expertise',
    name: 'Armor Expertise',
    source: 'Player Core',
    category: 'class_feature',
    level: 11,
    description: 'You have spent so much time wearing armor that you know how to make the most of its protection. Your proficiency rank for light armor, medium armor, heavy armor, and unarmored defense increases to expert. You gain the armor specialization effects of medium and heavy armor.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.unarmored/lightArmor/mediumArmor/heavyArmor → expert. Gain armor specialization effects for medium and heavy armor.',
  },
  {
    id: 'fighter-expertise',
    name: 'Fighter Expertise',
    source: 'Player Core',
    category: 'class_feature',
    level: 11,
    description: 'Your practiced techniques are hard for opponents to counter. Your proficiency rank for your fighter class DC increases to expert.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC → expert.',
  },

  // ── Level 13 ─────────────────────────────────────────
  {
    id: 'fighter-weapon-legend',
    name: 'Weapon Legend',
    source: 'Player Core',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned fighting techniques that apply to all armaments, and you\'ve developed unparalleled skill with your favorite weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master. Your proficiency rank for advanced weapons increases to expert. You can select one weapon group and increase your proficiency ranks to legendary for all simple weapons, martial weapons, and unarmed attacks in that weapon group, and to master for all advanced weapons in that weapon group.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies: simple+martial+unarmed → master, advanced → expert. Chosen weapon group: simple+martial+unarmed → legendary, advanced → master.',
    subChoices: { label: 'Choose a weapon group', options: [
      { id: 'axe', name: 'Axe' },
      { id: 'bomb', name: 'Bomb' },
      { id: 'bow', name: 'Bow' },
      { id: 'brawling', name: 'Brawling' },
      { id: 'club', name: 'Club' },
      { id: 'crossbow', name: 'Crossbow' },
      { id: 'dart', name: 'Dart' },
      { id: 'firearm', name: 'Firearm' },
      { id: 'flail', name: 'Flail' },
      { id: 'hammer', name: 'Hammer' },
      { id: 'knife', name: 'Knife' },
      { id: 'pick', name: 'Pick' },
      { id: 'polearm', name: 'Polearm' },
      { id: 'shield', name: 'Shield' },
      { id: 'sling', name: 'Sling' },
      { id: 'spear', name: 'Spear' },
      { id: 'sword', name: 'Sword' },
    ] },
  },

  // ── Level 15 ─────────────────────────────────────────
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Fighter', 15, {
    idOverride: 'fighter-greater-weapon-specialization',
  }),
  {
    id: 'fighter-improved-flexibility',
    name: 'Improved Flexibility',
    source: 'Player Core',
    category: 'class_feature',
    level: 15,
    description: 'Your extensive experience gives you even greater ability to adapt to each day\'s challenges. When you use combat flexibility, you can gain two fighter feats instead of one. While the first feat must still be 8th level or lower, the second feat can be up to 14th level, and you can use the first feat to meet the prerequisites of the second feat. You must meet all of the feats\' prerequisites.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'Combat Flexibility now grants 2 temporary feats: first level 8 or lower, second level 14 or lower. First feat can serve as prerequisite for second.',
    subChoices: { label: 'Choose second temporary feat (≤14th)', options: [
      { id: 'fighter-agile-grace', name: 'Agile Grace (10th)' },
      { id: 'fighter-certain-strike', name: 'Certain Strike (10th)' },
      { id: 'fighter-crashing-slam', name: 'Crashing Slam (10th)' },
      { id: 'fighter-cut-from-the-air', name: 'Cut from the Air (10th)' },
      { id: 'fighter-debilitating-shot', name: 'Debilitating Shot (10th)' },
      { id: 'fighter-disruptive-stance', name: 'Disruptive Stance (10th)' },
      { id: 'fighter-fearsome-brute', name: 'Fearsome Brute (10th)' },
      { id: 'fighter-mirror-shield', name: 'Mirror Shield (10th)' },
      { id: 'fighter-tactical-reflexes', name: 'Tactical Reflexes (10th)' },
      { id: 'fighter-twin-riposte', name: 'Twin Riposte (10th)' },
      { id: 'fighter-dueling-dance', name: 'Dueling Dance (12th)' },
      { id: 'fighter-flinging-shove', name: 'Flinging Shove (12th)' },
      { id: 'fighter-improved-dueling-riposte', name: 'Improved Dueling Riposte (12th)' },
      { id: 'fighter-incredible-ricochet', name: 'Incredible Ricochet (12th)' },
      { id: 'fighter-lunging-stance', name: 'Lunging Stance (12th)' },
      { id: 'fighter-spring-attack', name: 'Spring Attack (12th)' },
      { id: 'fighter-determination', name: 'Determination (14th)' },
      { id: 'fighter-guiding-finish', name: 'Guiding Finish (14th)' },
      { id: 'fighter-guiding-riposte', name: 'Guiding Riposte (14th)' },
      { id: 'fighter-improved-twin-riposte', name: 'Improved Twin Riposte (14th)' },
      { id: 'fighter-opening-stance', name: 'Opening Stance (14th)' },
    ] },
  },
  {
    id: 'fighter-tempered-reflexes',
    name: 'Tempered Reflexes',
    source: 'Player Core',
    category: 'class_feature',
    level: 15,
    description: 'Practiced reflexes let you find safety even in the face of cataclysmic explosions. Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.reflex → master. Success on Reflex save → critical success.',
  },

  // ── Level 17 ─────────────────────────────────────────
  {
    id: 'fighter-armor-mastery',
    name: 'Armor Mastery',
    source: 'Player Core',
    category: 'class_feature',
    level: 17,
    description: 'Your skill with armor improves, helping you avoid more blows. Your proficiency rank for light armor, medium armor, heavy armor, and unarmored defense increases to master.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies.unarmored/lightArmor/mediumArmor/heavyArmor → master.',
  },

  // ── Level 19 ─────────────────────────────────────────
  {
    id: 'fighter-versatile-legend',
    name: 'Versatile Legend',
    source: 'Player Core',
    category: 'class_feature',
    level: 19,
    description: 'You are nigh-unmatched with any weapon. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to legendary, and your proficiency rank for advanced weapons increases to master. Your proficiency rank for your fighter class DC increases to master.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'proficiencies: simple+martial+unarmed → legendary, advanced → master, classDC → master.',
  },
];

// ── Fighter Selectable Feats — PF2e Remastered (Player Core + War of Immortals)
// ─────────────────────────────────────────────────────────

export const FIGHTER_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'fighter-combat-assessment',
    name: 'Combat Assessment',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You make a telegraphed attack to learn about your foe. Make a melee Strike against a creature. If you hit, you can attempt a Recall Knowledge check against that creature as a free action. On a critical hit on the Strike, you gain a +2 circumstance bonus to the Recall Knowledge check. Whether you succeed or fail at the Recall Knowledge check, the target is temporarily immune to Combat Assessment for 1 day.',
    implemented: 'full',
    traits: ['Commander', 'Fighter'],
    actionCost: 1,
  },
  {
    id: 'fighter-double-slice',
    name: 'Double Slice',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You lash out at your foe with both weapons. Make two Strikes against the same target, one with each of your two melee weapons, each using your current multiple attack penalty. Both Strikes must have the same target. If the second Strike is made with a weapon that doesn\'t have the agile trait, it takes a -2 penalty. If both attacks hit, combine their damage, and then add any other applicable enhancements from both weapons. You add any precision damage only once, to the attack of your choice. Combine the damage from both Strikes and apply resistances and weaknesses only once. This counts as two attacks when calculating your multiple attack penalty.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 2,
  },
  {
    id: 'fighter-exacting-strike',
    name: 'Exacting Strike',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You make a controlled attack, fully accounting for your momentum. Make a Strike. The Strike gains the following failure effect. Failure: This attack does not count toward your multiple attack penalty.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-point-blank-stance',
    name: 'Point-Blank Stance',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You take aim to pick off nearby enemies quickly. You enter a stance optimized for close-quarters ranged combat. While in this stance, you don\'t take the -2 penalty from the volley trait, and you gain a +2 circumstance bonus to damage rolls on ranged Strikes against targets within your weapon\'s first range increment.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
  },
  {
    id: 'fighter-reactive-shield',
    name: 'Reactive Shield',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You can snap your shield into place just as you would be hit, gaining its bonus to AC. You immediately use the Raise a Shield action and gain your shield\'s bonus to AC. The circumstance bonus from the shield applies to your AC when determining the outcome of the triggering attack.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An enemy hits you with a melee Strike. Requirements: You are wielding a shield.',
  },
  {
    id: 'fighter-snagging-strike',
    name: 'Snagging Strike',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You combine an attack with quick grappling moves to throw your enemy off balance as long as it stays in your reach. Make a Strike while keeping one hand free. If this Strike hits, the target is off-guard until the start of your next turn or until it is no longer within your reach, whichever comes first.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 1,
  },
  {
    id: 'fighter-sudden-charge',
    name: 'Sudden Charge',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'With a quick sprint, you dash up to your foe and swing. Stride twice. If you end your movement within melee reach of at least one enemy, you can make a melee Strike against that enemy. You can use Burrow, Climb, Fly, or Swim instead of Stride if you have the corresponding movement type.',
    implemented: 'full',
    traits: ['Barbarian', 'Fighter', 'Flourish'],
    actionCost: 2,
  },
  {
    id: 'fighter-vicious-swing',
    name: 'Vicious Swing',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You unleash a particularly damaging attack that digs into your foe. Make a melee Strike. This counts as two attacks when calculating your multiple attack penalty. If this Strike hits, you deal an extra die of weapon damage. If you\'re at least 10th level, increase this to two extra dice, and if you\'re at least 18th level, increase it to three extra dice.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
  },

  // ── Level 2 ──────────────────────────────────────────
  {
    id: 'fighter-aggressive-block',
    name: 'Aggressive Block',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You push back as you block the attack, knocking your foe away or off balance. When you use the Shield Block reaction, you can choose to either push the attacker 5 feet away from you or cause them to become off-guard until the start of your next turn. If the creature is pushed, it must be moved to a space that is adjacent to you. The creature can choose to allow themselves to be moved or be off-guard.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'free',
    mechanics: 'Trigger: You use the Shield Block reaction. Push attacker 5 ft or make them off-guard until start of your next turn.',
  },
  {
    id: 'fighter-assisting-shot',
    name: 'Assisting Shot',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'With a well-placed shot, you interfere with a foe in combat. Make a ranged Strike against a creature within your first range increment. If it hits, the next creature other than you to attack that target before the start of your next turn gains a +1 circumstance bonus to their attack roll, or a +2 circumstance bonus if your Strike was a critical hit.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-blade-brake',
    name: 'Blade Brake',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You plow your weapon into the floor, a wall, or another sturdy surface, anchoring yourself in place. As long as you remain in your current space and don\'t use this weapon to Strike, you gain a +2 circumstance bonus to your Fortitude or Reflex DC against attempts to Shove or Trip you. This benefit ends if you move from your current space, make a Strike with the anchored weapon, or use Blade Brake again.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 1,
  },
  {
    id: 'fighter-brutish-shove',
    name: 'Brutish Shove',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'Throwing your weight behind your attack, you hit your opponent hard enough to make it stumble back. Make a Strike with a two-handed melee weapon. If you hit a target that is your size or smaller, that creature is off-guard until the end of your current turn, and you can automatically Shove the target 5 feet, with the effects of a successful Shove. If you move to follow the target, this movement doesn\'t trigger reactions. This Strike has the following failure effect. Failure: The target becomes off-guard until the end of your current turn.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-combat-grab',
    name: 'Combat Grab',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You swipe at your opponent and grab at them. Make a melee Strike while keeping one hand free. If the Strike hits, you grab the target using your free hand. The creature remains grabbed until the end of your next turn or until it Escapes, whichever comes first.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-dueling-parry',
    name: 'Dueling Parry',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You can parry attacks against you with your one-handed weapon. You gain a +2 circumstance bonus to AC until the start of your next turn as long as you continue to meet the requirements.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding only a single one-handed melee weapon and have your other hand or hands free. +2 circumstance bonus to AC until start of next turn.',
  },
  {
    id: 'fighter-intimidating-strike',
    name: 'Intimidating Strike',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'Your blow not only wounds creatures but also shatters their confidence. Make a melee Strike. If you hit and deal damage, the target is frightened 1, or frightened 2 on a critical hit.',
    implemented: 'full',
    traits: ['Fighter', 'Emotion', 'Fear', 'Mental'],
    actionCost: 2,
  },
  {
    id: 'fighter-lightning-swap',
    name: 'Lightning Swap',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You Interact to stow any number of items, then draw up to two weapons or a shield and a weapon.',
    implemented: 'full',
    traits: ['Exemplar', 'Fighter', 'Flourish'],
    actionCost: 1,
  },
  {
    id: 'fighter-lunge',
    name: 'Lunge',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'Extending your body to its limits, you attack an enemy that would normally be beyond your reach. Make a melee Strike with a one-handed melee weapon, increasing your reach by 5 feet for that Strike. If the attack hits, you can automatically Shove the target 5 feet away from you.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 1,
  },
  {
    id: 'fighter-rebounding-toss',
    name: 'Rebounding Toss',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You bounce your weapon off one foe to strike another. Make a thrown ranged Strike. If it hits, the weapon rebounds toward a second target within 10 feet of the first target. Make an additional thrown ranged Strike against the second target. Both attacks count toward your multiple attack penalty, but the penalty doesn\'t increase until after both attacks. The weapon returns to your hand after both Strikes.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 1,
  },
  {
    id: 'fighter-sleek-reposition',
    name: 'Sleek Reposition',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'While your opponent is recovering from your prior attack, you move them where you want. Make a melee Strike. If it hits a creature that is your size or smaller, you can move the target 5 feet to any space within your reach. This movement doesn\'t trigger reactions.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },

  // ── Level 4 ──────────────────────────────────────────
  {
    id: 'fighter-barreling-charge',
    name: 'Barreling Charge',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You rush forward, pushing enemies aside to reach your target. Stride up to your Speed; you can move through enemies\' spaces during this movement, and each time you enter a creature\'s space you can attempt an Athletics check to Shove that creature. If you fail the Shove, your movement ends. Make a melee Strike at the end of your movement.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Trained in Athletics'],
  },
  {
    id: 'fighter-double-shot',
    name: 'Double Shot',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You shoot twice in blindingly fast succession. Make two ranged Strikes, each against a different target and each using the current multiple attack penalty. Both Strikes count toward your multiple attack penalty, but the penalty doesn\'t increase until after both attacks.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
  },
  {
    id: 'fighter-dual-handed-assault',
    name: 'Dual-Handed Assault',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You snap your free hand over to grip your weapon just long enough to add momentum and deliver a more powerful blow to your opponent. Make a Strike with a one-handed melee weapon you\'re wielding in one hand; you use two hands to make the Strike, temporarily changing the weapon\'s damage die to the value of the two-hand trait.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 1,
  },
  {
    id: 'fighter-haft-striker-stance',
    name: 'Haft Striker Stance',
    source: 'War of Immortals',
    category: 'class',
    level: 4,
    description: 'You treat the haft of your weapon as a simple melee weapon that deals 1d4 bludgeoning damage and belongs to the club weapon group. It has the agile and finesse traits, and it shares any fundamental runes with the weapon to which it\'s attached. You can use feats meant for use with two weapons, treating the haft of your weapon as the second weapon (or treating the two-handed weapon as the second weapon if you would prefer). You can\'t use abilities that require you to wield the two-handed weapon in two hands, such as those that have the two-hand trait.',
    implemented: 'full',
    traits: ['Fighter', 'Ranger', 'Rogue', 'Stance'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding a two-handed weapon in the hammer, spear, or polearm group. Haft: 1d4 B, club group, agile+finesse, shares fundamental runes.',
  },
  {
    id: 'fighter-parting-shot',
    name: 'Parting Shot',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You jump back and make a quick shot that catches your opponent off guard. Step, then make a ranged Strike against a target within your first range increment. Your target is off-guard against the attack.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 2,
  },
  {
    id: 'fighter-powerful-shove',
    name: 'Powerful Shove',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You can push larger foes around with your attack. You can use Aggressive Block and Brutish Shove against creatures up to two sizes larger than you, and the target\'s movement from Aggressive Block or Brutish Shove can be up to 10 feet.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Aggressive Block or Brutish Shove'],
  },
  {
    id: 'fighter-quick-reversal',
    name: 'Quick Reversal',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You turn your foes\' flanking against them with a quick reverse attack. Make a melee Strike against one of the flanking creatures and then make a second melee Strike with the same weapon or unarmed attack against a different flanking creature. This second Strike has the same multiple attack penalty as the initial attack and doesn\'t count toward your multiple attack penalty.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-shielded-stride',
    name: 'Shielded Stride',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'When your shield is up, your enemies\' blows can\'t touch you. While you have your shield raised, you can Stride up to half your Speed without triggering reactions that are triggered by your movement.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-slam-down',
    name: 'Slam Down',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You make an attack to knock a foe off balance, then follow up immediately with a sweep to topple them. Make a melee Strike. If it hits and deals damage, you can attempt an Athletics check to Trip the target. Both the Strike and the Trip count toward your multiple attack penalty, but the penalty doesn\'t increase until after both attacks.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
    prerequisites: ['Trained in Athletics'],
  },
  {
    id: 'fighter-swipe',
    name: 'Swipe',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You make a wide, arcing swing. Make a single melee Strike and compare the attack roll result to the AC of up to two foes, each of whom must be within your reach and adjacent to each other. Roll damage only once and apply it to each creature you hit. A Swipe counts as two attacks for your multiple attack penalty.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
  },
  {
    id: 'fighter-twin-parry',
    name: 'Twin Parry',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You use your two weapons to parry attacks. You gain a +1 circumstance bonus to AC until the start of your next turn, or a +2 circumstance bonus if either weapon has the parry trait. You lose this circumstance bonus if you no longer meet this feat\'s requirements.',
    implemented: 'full',
    traits: ['Fighter', 'Ranger'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding two melee weapons, one in each hand. +1 circ to AC (+2 if either weapon has parry trait) until start of next turn.',
  },

  // ── Level 6 ──────────────────────────────────────────
  {
    id: 'fighter-advanced-weapon-training',
    name: 'Advanced Weapon Training',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You\'ve studied the art of wielding an advanced weapon. You treat martial weapons as simple weapons and advanced weapons as martial weapons for the purpose of proficiency.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-advantageous-assault',
    name: 'Advantageous Assault',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'When an enemy has been weakened by your allies, you deliver a devastating blow. Make a Strike against a creature that is grabbed, prone, or restrained. You gain a circumstance bonus to damage on this Strike equal to the number of weapon damage dice, or 2 + the number of weapon damage dice if you have master proficiency with the weapon. If the creature is both grabbed and prone or restrained, the bonus is doubled.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-dazing-blow',
    name: 'Dazing Blow',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You pummel a held foe, stunning them. Make a melee Strike against a creature that is grabbed or restrained by you. If you hit, the creature must attempt a Fortitude save against your class DC. Success: The creature is unaffected. Failure: The creature is stunned 1. Critical Failure: The creature is stunned 3.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-disarming-stance',
    name: 'Disarming Stance',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You adopt a fencing stance that improves your control over your weapon. While you are in this stance, you gain a +1 circumstance bonus to Athletics checks to Disarm and a +2 circumstance bonus to your Reflex DC when defending against checks to Disarm you. In addition, you can attempt to Disarm creatures up to two sizes larger than you.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
    prerequisites: ['Trained in Athletics'],
  },
  {
    id: 'fighter-furious-focus',
    name: 'Furious Focus',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You\'ve learned to maintain your balance even when swinging furiously. When you make a Vicious Swing, the Strike doesn\'t count toward your multiple attack penalty as two attacks; instead, it counts only as one attack for this purpose.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Vicious Swing'],
  },
  {
    id: 'fighter-guardians-deflection',
    name: 'Guardian\'s Deflection',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You use your weapon to deflect an attack against an ally adjacent to you, granting a +2 circumstance bonus to their AC against the triggering attack. You must be wielding a melee weapon or have a hand free to use this reaction.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An ally adjacent to you is hit by an attack. +2 circumstance bonus to the ally\'s AC against the triggering attack.',
  },
  {
    id: 'fighter-reflexive-shield',
    name: 'Reflexive Shield',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You can use your shield to fend off the worst of area effects and targeted spells. When you have your shield raised, you can apply your shield\'s circumstance bonus to AC to Reflex saves against area effects that deal damage, as well as to AC against spells that target you. If you take damage from an area effect while you have your shield raised, you can use your Shield Block reaction on that damage.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-revealing-stab',
    name: 'Revealing Stab',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You drive your weapon into a hidden foe, revealing its location to all. Make a melee Strike with a piercing weapon against a concealed or hidden creature in your reach. If the Strike deals damage, the target is no longer hidden from any creature, and it\'s no longer concealed from you. The Pierce persists as long as the weapon remains stuck in the target, and the target can use an Interact action to attempt a DC 10 flat check to remove the weapon.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 2,
  },
  {
    id: 'fighter-ricochet-stance',
    name: 'Ricochet Stance',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You adopt a stance optimized for thrown weapon combat. While in this stance, each time you make a thrown ranged Strike with a weapon that has the thrown trait, the weapon rebounds back to your hand after the Strike is complete, whether or not it hit.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
  },
  {
    id: 'fighter-shatter-defenses',
    name: 'Shatter Defenses',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'Your offense exploits your foe\'s fear. Make a melee Strike against a frightened creature. If you hit, the creature is off-guard until the end of your next turn, in addition to any other effects of the Strike. If you used this action as your first attack during your turn, the Strike doesn\'t count toward your multiple attack penalty.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-triple-shot',
    name: 'Triple Shot',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You can quickly fire three shots with a single action. You can use Double Shot to make three ranged Strikes instead of two. If you do, all three Strikes take a -2 penalty to the attack roll. All three Strikes count toward your multiple attack penalty, but the penalty doesn\'t increase until after all three attacks.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Double Shot'],
  },

  // ── Level 8 ──────────────────────────────────────────
  {
    id: 'fighter-blind-fight',
    name: 'Blind-Fight',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'Your battle instincts make you more aware of concealed and invisible opponents. You don\'t need to succeed at a flat check to target concealed creatures. You\'re not off-guard to creatures that are hidden from you (unless you\'re off-guard to them for reasons other than them being hidden), and you need only a successful DC 5 flat check to target a hidden creature. While you\'re adjacent to an undetected creature of your level or lower, it is instead only hidden from you.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Master in Perception'],
  },
  {
    id: 'fighter-disorienting-opening',
    name: 'Disorienting Opening',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You use your foe\'s stumble as an opening to throw them off balance. When you hit with a Reactive Strike, the target also becomes off-guard until the start of your next turn.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Reactive Strike'],
  },
  {
    id: 'fighter-dueling-riposte',
    name: 'Dueling Riposte',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You riposte against your flailing enemy. Make a melee Strike against the triggering creature or attempt to Disarm it.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'reaction',
    prerequisites: ['Dueling Parry'],
    mechanics: 'Trigger: A creature within your reach critically fails a Strike against you. Requirements: You are benefiting from Dueling Parry.',
  },
  {
    id: 'fighter-felling-strike',
    name: 'Felling Strike',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'Your attack knocks foes out of the air. Make a melee Strike. If it hits and deals damage to a flying target, the target falls up to 120 feet. The fall is gradual enough that if it causes the target to hit the ground, the target takes no damage from the fall. If the attack is a critical hit, the target can\'t Fly, Levitate, or otherwise leave the ground for 1 round.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 2,
  },
  {
    id: 'fighter-incredible-aim',
    name: 'Incredible Aim',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'By spending a moment to focus, you can aim carefully to hit even evasive foes. Make a ranged Strike. You gain a +2 circumstance bonus to this Strike\'s attack roll, and you ignore the target\'s concealed condition.',
    implemented: 'full',
    traits: ['Fighter', 'Concentrate'],
    actionCost: 2,
  },
  {
    id: 'fighter-positioning-assault',
    name: 'Positioning Assault',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'With a well-placed attack, you force an enemy to where you want them. Make a Strike with a two-handed melee weapon. If the Strike hits, you can move the target up to 5 feet to a space in your reach. This movement is forced movement. On a critical hit, you can move the target up to 10 feet.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
  },
  {
    id: 'fighter-resounding-bravery',
    name: 'Resounding Bravery',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'Even your fears serve as fuel for your fighting spirit. When you critically succeed at a Will save against a foe\'s ability, you gain a +1 status bonus to saves and a number of temporary Hit Points equal to half your level for 1 minute. These benefits are doubled if you critically succeed against a fear effect.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Bravery'],
  },
  {
    id: 'fighter-sudden-leap',
    name: 'Sudden Leap',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You make an impressive leap and use the momentum to empower your attack. Make a Leap, a High Jump, or a Long Jump. You must succeed at any required Athletics check. You can make a melee Strike at any point during the jump. Immediately after the Strike, you finish the jump.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 2,
  },

  // ── Level 10 ─────────────────────────────────────────
  {
    id: 'fighter-agile-grace',
    name: 'Agile Grace',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'Your graceful moves with agile weapons are beyond compare. Your multiple attack penalty with agile weapons and agile unarmed attacks becomes -3 for your second attack and -6 for subsequent attacks (rather than -4 and -8).',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-certain-strike',
    name: 'Certain Strike',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'Even when you don\'t hit squarely, you can still deal damage. Make a melee Strike. It gains the following failure effect. Failure: Your attack deals the minimum damage it would have dealt on a hit - this typically means you deal damage equal to the number of weapon damage dice plus your bonuses to damage, but with a result of 1 on each damage die.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-crashing-slam',
    name: 'Crashing Slam',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You can dash your foe to the ground with a single blow. When you use Slam Down, instead of making a Strike followed by a Trip, you can attempt a single Strike. If the Strike you make with Slam Down hits, you can automatically get a critical success on your Trip instead of rolling a check. Both the Strike and Trip still count toward your multiple attack penalty. If you used a two-handed melee weapon for the Strike, you can use the weapon\'s damage die size instead of the regular die size for the damage from a critical Trip.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Slam Down'],
  },
  {
    id: 'fighter-cut-from-the-air',
    name: 'Cut from the Air',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You can knock aside ranged attacks. You gain a +4 circumstance bonus to AC against the triggering attack. If the attack misses, you have cut it from the air or deflected it.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You are the target of a physical ranged Strike. Requirements: You are aware of the attack, not off-guard against it, and have a hand free or are wielding a melee weapon.',
  },
  {
    id: 'fighter-debilitating-shot',
    name: 'Debilitating Shot',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'Aiming for a vulnerable area, you cripple your foe. Make a ranged Strike. If the Strike hits, the target is slowed 1 until the end of your next turn.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 2,
  },
  {
    id: 'fighter-disruptive-stance',
    name: 'Disruptive Stance',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You adopt a stance that allows you to punish foes that let their guard down. While in this stance, you can use Reactive Strike against a creature that uses a concentrate action, in addition to the normal triggers of Reactive Strike. In addition, you can use Reactive Strike against a creature within your reach that casts a spell.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
  },
  {
    id: 'fighter-fearsome-brute',
    name: 'Fearsome Brute',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'Opponents find your physical might extremely frightening. Whenever you deal damage with a melee Strike to a frightened creature, you deal additional damage equal to double the creature\'s frightened value. If you have master proficiency in Intimidation, you instead deal additional damage equal to triple the creature\'s frightened value.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-mirror-shield',
    name: 'Mirror Shield',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You reflect the spell back against the caster. Make a ranged attack roll against the triggering creature using your highest proficiency with a ranged weapon. If you can cast spells, compare the result of your spell attack roll to the result the caster rolled with their spell attack roll and use the higher. If you succeed, the caster takes the same effects of the spell as if they had critically failed the save or you had critically succeeded.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An opponent casting a spell that targets you critically fails a spell attack roll against your AC. Requirements: You have a shield raised.',
  },
  {
    id: 'fighter-tactical-reflexes',
    name: 'Tactical Reflexes',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You are always prepared to react to threats. You gain an additional reaction at the start of each of your turns that you can use only to make a Reactive Strike.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-twin-riposte',
    name: 'Twin Riposte',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'A clever riposte against a foe who left an opening. Make a melee Strike or attempt to Disarm the triggering opponent.',
    implemented: 'full',
    traits: ['Fighter', 'Ranger'],
    actionCost: 'reaction',
    prerequisites: ['Twin Parry'],
    mechanics: 'Trigger: A creature within your reach critically fails a Strike against you. Requirements: You are benefiting from Twin Parry.',
  },

  // ── Level 12 ─────────────────────────────────────────
  {
    id: 'fighter-dueling-dance',
    name: 'Dueling Dance',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'You constantly parry while weaving your weapon in and out in a flowing dance. While you are in this stance, you constantly benefit from Dueling Parry.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
    prerequisites: ['Dueling Parry'],
    mechanics: 'Requirements: You are wielding only a single one-handed melee weapon and have your other hand or hands free. Persistent Dueling Parry (+2 circ to AC) while in stance.',
  },
  {
    id: 'fighter-flinging-shove',
    name: 'Flinging Shove',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'When you hit hard enough, you can send an enemy flying. When you successfully use Aggressive Block or Brutish Shove, you can push the target up to 10 feet instead of 5 feet. On a critical success with Brutish Shove, you can push the target up to 20 feet instead of 10 feet.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Aggressive Block or Brutish Shove'],
  },
  {
    id: 'fighter-improved-dueling-riposte',
    name: 'Improved Dueling Riposte',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'Your ripostes come lightning fast. You can use Dueling Riposte even if you aren\'t benefiting from Dueling Parry, as long as you are wielding only a single one-handed melee weapon and have your other hand or hands free. At the start of each of your turns, you gain an additional reaction that you can use only to make a Dueling Riposte.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Dueling Riposte'],
  },
  {
    id: 'fighter-incredible-ricochet',
    name: 'Incredible Ricochet',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'Your thrown weapon attacks can bounce unpredictably to catch foes off guard. When you make a thrown ranged Strike and miss, you can redirect the weapon toward a different target within 10 feet of the original target. Make a thrown weapon Strike against the other target at a -2 penalty. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Fighter', 'Concentrate', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-lunging-stance',
    name: 'Lunging Stance',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'Your steady stance lets you attack at an extended reach indefinitely. While in this stance, you can use the reach benefit from Lunge for all melee Strikes you make, increasing your reach by 5 feet.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
    prerequisites: ['Lunge'],
  },
  {
    id: 'fighter-spring-attack',
    name: 'Spring Attack',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'Springing away from one foe, you Strike at another. Stride up to your Speed. During this movement, you can make one melee Strike at any point along your path. Unlike normal, this movement doesn\'t trigger reactions from the target of your Strike.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 1,
  },

  // ── Level 14 ─────────────────────────────────────────
  {
    id: 'fighter-determination',
    name: 'Determination',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'Your training allows you to shrug off effects that would incapacitate most. Choose one nonpermanent spell or condition that is affecting you. If you chose a condition, attempt a counteract check against it using your fighter class DC - 10 as the counteract modifier. If you chose a spell, attempt a counteract check against it. Your counteract level is equal to half your level rounded up. If you succeed, the spell or condition is removed.',
    implemented: 'full',
    traits: ['Fighter', 'Concentrate'],
    actionCost: 1,
  },
  {
    id: 'fighter-guiding-finish',
    name: 'Guiding Finish',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'Using your weapon as a lever, you force your foe to the position you want. Make a melee Strike. If the Strike hits, you can move the target up to 10 feet into a space in your reach. You can move the target through your own space during this movement. The target must end this movement in a space that is adjacent to you. This movement is forced movement. On a critical hit, you can move the target up to 20 feet.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 1,
  },
  {
    id: 'fighter-guiding-riposte',
    name: 'Guiding Riposte',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'When your riposte hits, you can direct your foe to a more advantageous position. When you use Dueling Riposte to make a melee Strike and you hit, you can move the target up to 10 feet into a space in your reach. This movement is forced movement.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Dueling Riposte'],
  },
  {
    id: 'fighter-improved-twin-riposte',
    name: 'Improved Twin Riposte',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'You can use Twin Riposte even if you aren\'t benefiting from Twin Parry, as long as you are wielding two melee weapons. At the start of each of your turns, you gain an additional reaction that you can use only to make a Twin Riposte.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Twin Riposte'],
  },
  {
    id: 'fighter-opening-stance',
    name: 'Opening Stance',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'At the first sign of trouble, often before you consciously realize the danger, you drop into a stance with a mere thought. Use an action that has the stance trait.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'free',
    mechanics: 'Trigger: You roll initiative. Immediately use a stance action as a free action.',
  },

  // ── Level 16 ─────────────────────────────────────────
  {
    id: 'fighter-graceful-poise',
    name: 'Graceful Poise',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'With the finesse of a dual-weapon master, you fight with elegance and precision. While in this stance, when you make your second Strike from Double Slice, your multiple attack penalty is -3 with an agile weapon (or -4 without the agile trait), rather than the normal -4 (or -5).',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
    prerequisites: ['Double Slice'],
    mechanics: 'Requirements: You are wielding two melee weapons one in each hand. Reduces MAP on second Double Slice Strike: agile -4 → -3, non-agile -5 → -4.',
  },
  {
    id: 'fighter-multishot-stance',
    name: 'Multishot Stance',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'You adopt a stance optimized for firing multiple projectiles at great speed. While in this stance, you can use Double Shot and Triple Shot as though they had one fewer action (minimum 1 action), and you don\'t take the -2 penalty from Triple Shot.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
    prerequisites: ['Triple Shot'],
  },
  {
    id: 'fighter-needle-in-the-gods-eyes',
    name: 'Needle in the God\'s Eyes',
    source: 'War of Immortals',
    category: 'class',
    level: 16,
    description: 'You make a tremendous leap and deliver devastating strikes in mid-air. Leap up to your total Speed horizontally or vertically, then Strike twice at any point during the Leap. Both attacks count toward your multiple attack penalty, but the penalty doesn\'t increase until both attacks have been made.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 2,
  },
  {
    id: 'fighter-overwhelming-blow',
    name: 'Overwhelming Blow',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'You throw your weight into a powerful attack that leaves you vulnerable. Make a melee Strike. This counts as three attacks when calculating your multiple attack penalty. If this Strike hits, you get a critical hit. If you roll a critical hit, your weapon or unarmed attack also gains the deadly d12 trait (this replaces any deadly trait it already has). Whether or not you hit, you become stunned 1 and are off-guard until the start of your next turn.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 3,
  },
  {
    id: 'fighter-twinned-defense',
    name: 'Twinned Defense',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'Your dual weapons form an impenetrable defense. While in this stance, you constantly gain the benefits of Twin Parry, getting a +1 circumstance bonus to AC (+2 if either weapon has the parry trait) without needing to use the Twin Parry action.',
    implemented: 'full',
    traits: ['Fighter', 'Stance'],
    actionCost: 1,
    prerequisites: ['Twin Parry'],
    mechanics: 'Requirements: You are wielding two melee weapons, one in each hand. Persistent Twin Parry while in stance.',
  },

  // ── Level 18 ─────────────────────────────────────────
  {
    id: 'fighter-brutal-finish',
    name: 'Brutal Finish',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'You pour all remaining power into a final devastating attack. Make a melee Strike. You gain a circumstance bonus to damage equal to the number of dice your weapon normally rolls on a hit (such as +2 for 2d6). If you already made melee Strikes this turn, you instead gain the circumstance bonus to damage equal to twice that number of dice.',
    implemented: 'full',
    traits: ['Fighter', 'Press'],
    actionCost: 1,
  },
  {
    id: 'fighter-impossible-volley',
    name: 'Impossible Volley',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'You fire a volley at all foes in an area. Make one ranged Strike with a weapon that has the volley trait against each enemy within a 10-foot-radius burst centered at or beyond your weapon\'s volley range. Roll the damage only once for all targets. Each attack counts toward your multiple attack penalty, but do not increase your penalty until you have made all your attacks.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish'],
    actionCost: 3,
  },
  {
    id: 'fighter-savage-critical',
    name: 'Savage Critical',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'The wounds you inflict are extremely grievous. When you Strike with a weapon or unarmed attack for which you have legendary proficiency, you critically succeed on a 19 on the die as long as that result is a success. This has no effect on a 19 if the result is a failure.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-smash-from-the-air',
    name: 'Smash from the Air',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'Your expertise enables you to knock away spells. You can use Cut from the Air against ranged spell attacks in addition to physical ranged Strikes.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Cut from the Air'],
  },

  // ── Level 20 ─────────────────────────────────────────
  {
    id: 'fighter-boundless-reprisals',
    name: 'Boundless Reprisals',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'You can react to any occasion. At the start of each enemy\'s turn, you gain a reaction you can use only during that turn. You can use these reactions only to make Reactive Strikes, and you can\'t use more than one on a single triggering action.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
  },
  {
    id: 'fighter-ultimate-flexibility',
    name: 'Ultimate Flexibility',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'Your combat training has reached the pinnacle of adaptability. When you use combat flexibility, you can gain three fighter feats instead of two. The first feat must still be 8th level or lower, the second 14th level or lower, and the third can be 18th level or lower. You can use each of the lower-level feats to meet the prerequisites of feats of a higher level. You can also retrain these feats at any time by spending 1 hour in practice.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    prerequisites: ['Improved Flexibility'],
    mechanics: 'Combat Flexibility now grants 3 temporary feats: first level 8 or lower, second level 14 or lower, third level 18 or lower. Can chain prerequisites. 1-hour retrain.',
  },
  {
    id: 'fighter-weapon-supremacy',
    name: 'Weapon Supremacy',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'Your weapons are extensions of your being. You are permanently quickened, and you can use the extra action only to make a Strike. When you gain this feat, choose one weapon group in which you have legendary proficiency. Your Strikes with weapons in that group gain a +4 status bonus to damage.',
    implemented: 'full',
    traits: ['Fighter'],
    actionCost: 'passive',
    mechanics: 'Permanently quickened (extra action only for Strikes). +4 status bonus to damage with chosen legendary-proficiency weapon group.',
    subChoices: { label: 'Choose a weapon group', options: [
      { id: 'axe', name: 'Axe' },
      { id: 'bomb', name: 'Bomb' },
      { id: 'bow', name: 'Bow' },
      { id: 'brawling', name: 'Brawling' },
      { id: 'club', name: 'Club' },
      { id: 'crossbow', name: 'Crossbow' },
      { id: 'dart', name: 'Dart' },
      { id: 'firearm', name: 'Firearm' },
      { id: 'flail', name: 'Flail' },
      { id: 'hammer', name: 'Hammer' },
      { id: 'knife', name: 'Knife' },
      { id: 'pick', name: 'Pick' },
      { id: 'polearm', name: 'Polearm' },
      { id: 'shield', name: 'Shield' },
      { id: 'sling', name: 'Sling' },
      { id: 'spear', name: 'Spear' },
      { id: 'sword', name: 'Sword' },
    ] },
  },
];
