/**
 * Guardian Class Features & Feats — PF2e Remastered (Battlecry!)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=67
 *
 * Key Attribute: STR | HP: 12 + CON
 * Perception: Trained -> Expert (L7, Reaction Time)
 * Fort: Expert -> Master (L9, Battle Hardened, success->crit)
 * Reflex: Trained -> Expert (L7, Reflex Expertise)
 * Will: Expert -> Master (L17, Unyielding Resolve, success->crit)
 * Weapons: Trained simple+martial+unarmed -> Expert (L5, Weapon Expertise)
 *          -> Master (L13, Weapon Mastery)
 * Armor: All Trained -> Medium/Heavy Expert (L5, Unbreakable Expertise)
 *        -> Medium/Heavy Master (L11, Unbreakable Mastery), Light/Unarmored Expert (L11)
 *        -> Medium/Heavy Legendary (L15, Unbreakable Legend), Light/Unarmored Master (L15)
 * Class DC: Trained -> Expert (L9, Guardian Expertise) -> Master (L19, Guardian Mastery)
 * Skills: Athletics + 3 + INT
 *
 * Guardian's Armor: Resistance to physical damage = 1 + half level while wearing medium/heavy.
 * Shield Block: Free general feat (L1).
 * Taunt: 1-action to impose -1 penalty when taunted enemy targets allies not you.
 * Guardian's Techniques: Ever Ready (extra reaction on initiative) + Intercept Attack
 *   (reaction to take physical damage instead of ally within 10 ft, 15 ft vs taunted).
 * Weapon Specialization: +2/+3/+4 damage (L11); Greater (L17): +4/+6/+8.
 *
 * Class features: 18 (L1-L19)
 * Class feats: 65 (L1-L20)
 */

import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION, SHIELD_BLOCK } from './sharedFeats';

// ── Guardian Class Features ──────────────────────────────

export const GUARDIAN_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'guardian-guardians-armor',
    name: 'Guardian\'s Armor',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 1,
    description: 'Even when you are struck, your armor protects you from some harm. While wearing medium or heavy armor, you gain resistance to physical damage equal to 1 + half your level. In addition, you can rest normally while wearing medium and heavy armor.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'Physical damage resistance = 1 + floor(level / 2) while wearing medium or heavy armor. Normal rest in medium/heavy armor.',
  },
  createClassFeature(SHIELD_BLOCK, 'Guardian', 1, {
    idOverride: 'guardian-shield-block',
    traits: ['General'],
  }),
  {
    id: 'guardian-taunt',
    name: 'Taunt',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 1,
    description: 'With an attention-grabbing gesture, noise, cutting remark, or threatening shout, you attempt to draw an enemy to you instead of your allies. Taunt gains the auditory trait, visual trait, or both, depending on how you draw the target\'s attention. Even mindless creatures are drawn to your taunts. Choose an enemy within 30 feet to be your taunted enemy. If your taunted enemy takes a hostile action that includes at least one of your allies but doesn\'t include you, they take a -1 circumstance penalty to their attack rolls and DCs for that action, and they also become off-guard until the start of their next turn. Your enemy remains taunted until the start of your next turn, and you can have only one Taunt in effect at a time. Taunting a new enemy ends this effect on any current target.',
    implemented: 'full',
    traits: ['Guardian', 'Concentrate'],
    actionCost: 1,
    mechanics: 'Choose enemy within 30 ft. Taunted enemy takes -1 circ penalty to attacks/DCs when targeting allies without you, becomes off-guard. Lasts until start of next turn. One target at a time.',
  },
  {
    id: 'guardian-techniques',
    name: 'Guardian\'s Techniques',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 1,
    description: 'As a guardian, you have learned certain techniques to help keep your allies safe. You gain Ever Ready: you always gain a reaction whenever you roll initiative for combat, but you can use it only for reactions from guardian feats or class features. The GM might still rule that you can use other reactions before your first turn based on the situation, as normal. You also gain the Intercept Attack reaction.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'Ever Ready: Gain a reaction on initiative for guardian feat/feature reactions (including Shield Block). Also grants Intercept Attack reaction.',
  },
  {
    id: 'guardian-intercept-attack',
    name: 'Intercept Attack',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 1,
    description: 'You fling yourself in the way of oncoming harm to protect an ally. You can Step, but you must end your movement adjacent to the triggering ally. You take the damage instead of the triggering ally. Apply your own immunities, weaknesses, and resistances to the damage, not the ally\'s. You can extend this ability to an ally within 15 feet of you if the damage comes from your taunted enemy. If this ally is farther than you can Step to reach, you can Stride instead of Stepping; you still must end the movement adjacent to your ally.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An ally within 10 feet of you takes physical damage. Step adjacent to ally, take the damage instead. Extended to 15 ft range vs taunted enemy (can Stride instead of Step).',
  },

  // ── Level 3 ──────────────────────────────────────────
  {
    id: 'guardian-tough-to-kill',
    name: 'Tough to Kill',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 3,
    description: 'The protectiveness of your armor ensures that even if you fall, you take longer to die. You gain the Diehard general feat. If you already have the Diehard feat, you can retrain it when you get tough to kill. Additionally, the first time each day you\'d be reduced to dying 3 or higher, you stay at dying 2 instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'Grants Diehard feat. First time each day reduced to dying 3+, stay at dying 2 instead.',
  },

  // ── Level 5 ──────────────────────────────────────────
  {
    id: 'guardian-unbreakable-expertise',
    name: 'Unbreakable Expertise',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 5,
    description: 'With training, you understand how to best block hits with your armor. Your proficiency rank with medium armor and heavy armor increases to expert.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.mediumArmor/heavyArmor -> expert.',
  },
  {
    id: 'guardian-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 5,
    description: 'Sometimes, the best defense is a good offense. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.simpleWeapons/martialWeapons/unarmed -> expert.',
  },

  // ── Level 7 ──────────────────────────────────────────
  {
    id: 'guardian-reaction-time',
    name: 'Reaction Time',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 7,
    description: 'You\'re always on the lookout for danger and can react to it in an instant. Your proficiency rank for Perception increases to expert. At the start of each of your turns, you gain an additional reaction that you can use only for reactions from guardian feats or class features (including Shield Block). If you have the ever ready class feature, you also gain this additional reaction when you roll initiative for combat.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.perception -> expert. Extra reaction each turn for guardian feat/feature reactions. Ever Ready also grants this extra reaction on initiative.',
  },
  {
    id: 'guardian-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 7,
    description: 'Even in the heaviest of armors, you can brace yourself against widespread effects. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.reflex -> expert.',
  },

  // ── Level 9 ──────────────────────────────────────────
  {
    id: 'guardian-battle-hardened',
    name: 'Battle Hardened',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 9,
    description: 'Your experience in battle helps protect you against magic and toxins alike. Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.fortitude -> master. Success on Fortitude save -> critical success.',
  },
  {
    id: 'guardian-expertise',
    name: 'Guardian Expertise',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 9,
    description: 'Your armored form is more imposing. Your proficiency rank for your guardian class DC increases to expert.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC -> expert.',
  },

  // ── Level 11 ─────────────────────────────────────────
  {
    id: 'guardian-unbreakable-mastery',
    name: 'Unbreakable Mastery',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 11,
    description: 'When clad in steel, you fend off most attacks. Your proficiency rank with medium armor and heavy armor increases to master. Your proficiency rank with light armor and unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies: mediumArmor/heavyArmor -> master, lightArmor/unarmored -> expert.',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Guardian', 11, {
    idOverride: 'guardian-weapon-specialization',
  }),

  // ── Level 13 ─────────────────────────────────────────
  {
    id: 'guardian-weapon-mastery',
    name: 'Weapon Mastery',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 13,
    description: 'Your hours of battlefield experience grant you greater prowess. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.simpleWeapons/martialWeapons/unarmed -> master.',
  },

  // ── Level 15 ─────────────────────────────────────────
  {
    id: 'guardian-unbreakable-legend',
    name: 'Unbreakable Legend',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 15,
    description: 'You have become an almost-impenetrable bulwark. Your proficiency ranks for medium and heavy armor increase to legendary. Your proficiency ranks for light armor and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies: mediumArmor/heavyArmor -> legendary, lightArmor/unarmored -> master.',
  },

  // ── Level 17 ─────────────────────────────────────────
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Guardian', 17, {
    idOverride: 'guardian-greater-weapon-specialization',
  }),
  {
    id: 'guardian-unyielding-resolve',
    name: 'Unyielding Resolve',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 17,
    description: 'Stalwart as your armor, you refuse to break. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.will -> master. Success on Will save -> critical success.',
  },

  // ── Level 19 ─────────────────────────────────────────
  {
    id: 'guardian-mastery',
    name: 'Guardian Mastery',
    source: 'Battlecry!',
    category: 'class_feature',
    level: 19,
    description: 'You are known for your suit of armor more than the person inside. Your proficiency rank for your guardian class DC increases to master. While wearing armor, when you attempt a Reflex save to avoid a damaging effect, such as a fireball, you can add your armor\'s item bonus to AC instead of your Dexterity modifier; if your armor has the bulwark trait, increase this bonus by 1. If you get a success when you do this, you get a critical success instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC -> master. While armored, Reflex saves vs damage: use armor item bonus instead of Dex; bulwark +1. Success -> critical success.',
  },
];

// ── Guardian Selectable Feats — PF2e Remastered (Battlecry! + Player Core)
// ─────────────────────────────────────────────────────────

export const GUARDIAN_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'guardian-bodyguard',
    name: 'Bodyguard',
    source: 'Battlecry!',
    category: 'class',
    level: 1,
    description: 'You swear a vow to protect one of your allies at all costs, regardless of the risk this might pose to you. During your daily preparations, choose one of your allies as your charge. When you Taunt, the penalty your taunted enemy takes increases to -2 against your charge. You can take 10 minutes to change who your charge is before your next daily preparations.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'Daily preparations: choose one ally as charge. Taunt penalty increases to -2 against that charge. 10-minute swap.',
  },
  {
    id: 'guardian-defensive-advance',
    name: 'Defensive Advance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'With the protection of your shield, you dive into battle! You Raise your Shield and Stride.',
    implemented: 'full',
    traits: ['Champion', 'Flourish', 'Guardian'],
    actionCost: 2,
  },
  {
    id: 'guardian-larger-than-life',
    name: 'Larger than Life',
    source: 'Battlecry!',
    category: 'class',
    level: 1,
    description: 'When you\'re clad in the heaviest of armors, you have an outsized presence. Though you don\'t get any larger, you\'re treated as one size larger for the purposes of affecting other creatures with actions like Disarm, Grapple, Reposition, Shove, and Trip while wearing heavy armor. Similarly, you\'re treated as one size larger for the purposes of creatures affecting you with those same actions, as well as with Swallow Whole and similar actions, while wearing heavy armor.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'While wearing heavy armor, treated as one size larger for Disarm, Grapple, Reposition, Shove, Trip (both ways), and Swallow Whole defense.',
  },
  {
    id: 'guardian-long-distance-taunt',
    name: 'Long-distance Taunt',
    source: 'Battlecry!',
    category: 'class',
    level: 1,
    description: 'You can draw the wrath of your foes even at a great distance. When you use Taunt, you can choose a target within 120 feet.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-punishing-shove',
    name: 'Punishing Shove',
    source: 'Battlecry!',
    category: 'class',
    level: 1,
    description: 'When you push a foe away, you put the entire force of your armored form into it. When you successfully Shove a creature, that creature takes an amount of bludgeoning damage equal to your Strength modifier (or double that amount on a critical success). This damage increases by 2 when you become an expert in Athletics, 6 when you become a master, and 12 when you become legendary.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    prerequisites: ['Trained in Athletics'],
  },
  {
    id: 'guardian-reactive-shield',
    name: 'Reactive Shield',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You can snap your shield into place just as you would be hit, gaining its bonus to AC. You immediately use the Raise a Shield action and gain your shield\'s bonus to AC. The circumstance bonus from the shield applies to your AC when determining the outcome of the triggering attack.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An enemy hits you with a melee Strike. Requirements: You are wielding a shield.',
  },
  {
    id: 'guardian-shield-warfare',
    name: 'Shield Warfare',
    source: 'Battlecry!',
    category: 'class',
    level: 1,
    description: 'You know how to use shields offensively far better than most. Increase the weapon damage die of any shield bash, shield boss, or shield spikes you wield by one step.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-shoulder-check',
    name: 'Shoulder Check',
    source: 'Battlecry!',
    category: 'class',
    level: 1,
    description: 'You hit a foe with your armor to throw them off balance. Make a fist Strike even if you don\'t have a hand free; if you\'re wielding a gauntlet or spiked gauntlet, you can make a Strike with one of those weapons instead. The Strike gains the following additional results. Critical Success: The target is off-guard against melee attacks you attempt against it until the end of your next turn. Success: The target is off-guard against the next melee attack you attempt against it before the end of your current turn. Critical Failure: You are off-guard against melee attacks the target attempts against you until the end of your next turn.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 1,
  },

  // ── Level 2 ──────────────────────────────────────────
  {
    id: 'guardian-aggressive-block',
    name: 'Aggressive Block',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You push back as you block the attack, knocking your foe away or off balance. When you use the Shield Block reaction, you can choose to either push the attacker 5 feet away from you or cause them to become off-guard until the start of your next turn. If the creature is pushed, it must be moved to a space that is adjacent to you. The creature can choose to allow themselves to be moved or be off-guard.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'free',
    mechanics: 'Trigger: You use Shield Block. Push attacker 5 ft or make them off-guard until start of your next turn.',
    subChoices: { label: 'Choose block effect', options: [
      { id: 'push', name: 'Push 5 ft', description: 'Push the attacker 5 feet away from you' },
      { id: 'off-guard', name: 'Off-Guard', description: 'Attacker becomes off-guard until start of your next turn' },
    ] },
  },
  {
    id: 'guardian-covering-stance',
    name: 'Covering Stance',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'Your very presence on the field of battle protects nearby allies from harm. At the end of each of your turns while you\'re in this stance, choose one ally adjacent to you to gain lesser cover until the start of your next turn. That ally loses this benefit if they move to a space that is no longer adjacent to you at any point during their move. If you Intercept an Attack that would harm the ally you\'re covering, that ally can Step as a free action after your reaction is complete.',
    implemented: 'full',
    traits: ['Guardian', 'Stance'],
    actionCost: 1,
  },
  {
    id: 'guardian-hampering-stance',
    name: 'Hampering Stance',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'You make it difficult for enemies to move past you. While you are in this stance, squares in a 5-foot emanation are difficult terrain for your enemies.',
    implemented: 'full',
    traits: ['Aura', 'Guardian', 'Stance'],
    actionCost: 1,
  },
  {
    id: 'guardian-phalanx-formation',
    name: 'Phalanx Formation',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'You know how to clear a line of fire for your allies. You don\'t provide lesser cover to enemies against your allies\' attacks.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-raise-haft',
    name: 'Raise Haft',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'You know how to use the haft of larger weapons to block your enemies\' attacks. Two-handed weapons you wield gain the parry trait. If the weapon already has the parry trait, you increase the circumstance bonus to AC it provides to +2.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-shield-your-eyes',
    name: 'Shield your Eyes',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'You reflexively place your shield between your eyes and visual dangers. While your shield is raised, you gain a +2 circumstance bonus to all defenses against effects with the light or visual trait. If you critically fail your save against such an effect while your shield is raised, you fail instead. Likewise, if such an effect critically succeeds against your DC, it\'s a success instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-shielding-taunt',
    name: 'Shielding Taunt',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'By banging loudly on your shield, you get the attention of even the most stubborn of foes. Raise a Shield, and then Taunt a creature. Your Taunt gains the auditory trait.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding a shield. Raise a Shield then Taunt. Taunt gains auditory trait.',
  },
  {
    id: 'guardian-taunting-strike',
    name: 'Taunting Strike',
    source: 'Battlecry!',
    category: 'class',
    level: 2,
    description: 'The force of your blow causes your enemy to focus their attention on you. Make a Strike. Regardless of whether the Strike hits, you Taunt the target. Your Taunt gains the visual trait.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 1,
  },

  // ── Level 4 ──────────────────────────────────────────
  {
    id: 'guardian-area-armor',
    name: 'Area Armor',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'The armor you wear protects you and shelters your allies against explosions and other large-scale assaults. While you\'re wearing medium or heavy armor, allies adjacent to you gain a +1 circumstance bonus to Reflex saves against area effects. If you\'re a master in the armor, the bonus is +2 instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-armored-courage',
    name: 'Armored Courage',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'You take comfort in the safety of your armor. You gain a number of temporary Hit Points equal to your level that last for 1 minute, and you reduce your frightened condition value by 1 (to a minimum of 0).',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 1,
    mechanics: 'Frequency: Once per hour. Requirements: You are wearing medium or heavy armor. Temp HP = level for 1 minute. Reduce frightened by 1.',
  },
  {
    id: 'guardian-energy-interceptor',
    name: 'Energy Interceptor',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'Though other guardians understand how to anticipate the flow of martial combat, you predict blasts of magical lightning, blazing trap runes, and more. You can use Intercept Attack when an ally would take acid, cold, electricity, fire, or sonic damage, not only when they would take physical damage.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    prerequisites: ['Intercept Attack'],
  },
  {
    id: 'guardian-flying-tackle',
    name: 'Flying Tackle',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'You barrel forward, gathering enough momentum to take down a threatening foe. Stride and then Leap, or attempt to High Jump or Long Jump. If you end your movement adjacent to a foe, you can attempt to Trip that foe. If you succeed at the Athletics check to Trip, you get a critical success instead. You can use Flying Tackle while Burrowing, Climbing, Flying, or Swimming instead of Striding if you have the corresponding movement type.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 2,
    prerequisites: ['Trained in Athletics'],
  },
  {
    id: 'guardian-not-so-fast',
    name: 'Not so Fast!',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'You lash out when foes try to get past you, possibly stopping them in their tracks. Make a melee Strike against the triggering creature. The Strike gains the following additional results. Critical Success: The target\'s movement is disrupted. Success: The target takes a -10-foot circumstance penalty to its Speed for the rest of its triggering movement. This penalty might cause the triggering creature\'s movement to end immediately based on its affected Speed. Failure: As success, but the target instead takes a -5-foot circumstance penalty to its Speed. Critical Failure: The target is unaffected.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'reaction',
    prerequisites: ['Hampering Stance'],
    mechanics: 'Trigger: A creature within your reach leaves a square during a move action it\'s using. Requirements: You are in Hampering Stance.',
  },
  {
    id: 'guardian-proud-nail',
    name: 'Proud Nail',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'When a foe ignores your taunts, you make them pay. Make a melee Strike against your taunted enemy. If this Strike hits, you deal an extra die of weapon damage. If you\'re at least 10th level, increase this to two extra dice, and if you\'re at least 18th level, increase it to three extra dice.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 1,
    mechanics: 'Requirements: Your taunted enemy is off-guard because it didn\'t target you or include you in an area effect. Extra weapon die; +1 die at 10th, +2 dice at 18th.',
  },
  {
    id: 'guardian-shielded-attrition',
    name: 'Shielded Attrition',
    source: 'Battlecry!',
    category: 'class',
    level: 4,
    description: 'You provoke attacks from foes that might otherwise stop your allies from moving. Raise your Shield, then choose whether to Stride up to half your Speed. This movement triggers enemies\' reactions as normal. Each enemy who could have reacted to your movement is unable to react to your allies\' movement until the start of your next turn (regardless of whether it chose to react to your movement).',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding a shield. Raise Shield + optional half-Speed Stride. Enemies who could react to your movement can\'t react to allies\' movement until next turn.',
  },

  // ── Level 6 ──────────────────────────────────────────
  {
    id: 'guardian-disarming-intercept',
    name: 'Disarming Intercept',
    source: 'Battlecry!',
    category: 'class',
    level: 6,
    description: 'When you catch a weapon in your armor, you can move your body to wrench it from your foe\'s grasp. After Intercepting the Attack, attempt to Disarm the weapon used for that attack. You don\'t need to have a hand free to do so. You gain an item bonus to the Athletics check equal to the value of your armor\'s potency rune.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'free',
    prerequisites: ['Intercept Attack'],
    mechanics: 'Trigger: You Intercept an Attack that was made with a melee weapon by a creature you\'re adjacent to. Free Disarm attempt with armor potency rune bonus.',
  },
  {
    id: 'guardian-guarded-advance',
    name: 'Guarded Advance',
    source: 'Battlecry!',
    category: 'class',
    level: 6,
    description: 'You slowly advance on the battlefield, taking utmost caution. You Raise a Shield and Step twice, in any order.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 1,
  },
  {
    id: 'guardian-lock-down',
    name: 'Lock Down',
    source: 'Battlecry!',
    category: 'class',
    level: 6,
    description: 'You attack an enemy to ensure they can\'t move beyond your reach. Strike an enemy within your reach. If you hit and deal damage, that enemy can\'t use move actions to move beyond the reach of the weapon or unarmed attack you used for the Strike. The enemy can still move to other squares within reach of that weapon or unarmed attack. This effect lasts until the beginning of your next turn, until you move, or until you use that weapon or unarmed attack to make another attack, whichever comes first.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 1,
    prerequisites: ['Hampering Stance'],
    mechanics: 'Requirements: You are in Hampering Stance. Target can\'t leave your weapon reach until start of next turn, you move, or you attack with that weapon again.',
  },
  {
    id: 'guardian-reactive-strike',
    name: 'Reactive Strike',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Champion', 'Commander', 'Exemplar', 'Guardian', 'Magus', 'Swashbuckler'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature within your reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it\'s using.',
  },
  {
    id: 'guardian-reflexive-shield',
    name: 'Reflexive Shield',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You can use your shield to fend off the worst of area effects and targeted spells. When you have your shield raised, you can apply your shield\'s circumstance bonus to AC to Reflex saves against area effects that deal damage, as well as to AC against spells that target you. If you take damage from an area effect while you have your shield raised, you can use your Shield Block reaction on that damage.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-retaliating-rescue',
    name: 'Retaliating Rescue',
    source: 'Battlecry!',
    category: 'class',
    level: 6,
    description: 'When an ally is in danger, you can hustle to reach them and punish the foe threatening them. Stride up to your Speed. You must end this movement adjacent to an ally who is within an enemy\'s reach. Then, you push your ally up to 5 feet (as normal for forced movement, this movement doesn\'t trigger reactions) and make a melee Strike against an enemy within your reach. If your ally was in that enemy\'s reach and your push moved them out of it, you gain a +2 circumstance bonus to your attack roll.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
  },
  {
    id: 'guardian-ring-their-bell',
    name: 'Ring their Bell',
    source: 'Battlecry!',
    category: 'class',
    level: 6,
    description: 'Using your armor, you pummel a foe that isn\'t focused on you in the head or face to stagger them. Make a fist Strike against your taunted enemy even if you don\'t have a hand free; if you\'re wielding a gauntlet or spiked gauntlet, you can make a Strike with one of those weapons instead. If the Strike hits and deals damage, the creature must attempt a Fortitude save against your class DC; this is an incapacitation effect. Critical Success: The creature is unaffected. Success: The creature is stunned 1. Failure: The creature is stunned 2. Critical Failure: The creature is stunned 3.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 1,
    mechanics: 'Requirements: You are wearing medium or heavy armor, and your taunted enemy is off-guard because it didn\'t target you or include you in an area effect. Incapacitation effect.',
  },
  {
    id: 'guardian-stomp-ground',
    name: 'Stomp Ground',
    source: 'Battlecry!',
    category: 'class',
    level: 6,
    description: 'You bring your booted foot down on the ground with enough force to rattle your foes. Each creature in a 5-foot emanation must attempt a Reflex saving throw against your class DC. Critical Success: The creature is unaffected. Success: The creature is off-guard until the end of your turn. Failure: The creature is knocked prone. Critical Failure: The creature is knocked prone and takes 1d6 bludgeoning damage from the fall.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
  },

  // ── Level 8 ──────────────────────────────────────────
  {
    id: 'guardian-group-taunt',
    name: 'Group Taunt',
    source: 'Battlecry!',
    category: 'class',
    level: 8,
    description: 'Your taunts draw the attention of multiple enemies at once. When you use Taunt, you can choose up to three targets within range, and you can have up to three taunted enemies at a time. Each time you Taunt, you can choose which enemies remain taunted and which the effect ends for. You must remain at or below this limit.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-juggernaut-charge',
    name: 'Juggernaut Charge',
    source: 'Battlecry!',
    category: 'class',
    level: 8,
    description: 'As you move forward in a rush, you put the weight of your armor behind an attack that can drag a foe with you. You Stride. If you end your movement within melee reach of at least one enemy, you can make a melee Strike against that enemy, then Stride again. If your Strike hit and dealt damage, that enemy is pulled with you and is moved the same direction and distance as your second Stride.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 2,
  },
  {
    id: 'guardian-mighty-bulwark',
    name: 'Mighty Bulwark',
    source: 'Battlecry!',
    category: 'class',
    level: 8,
    description: 'Thanks to the incredible connection you have forged with your armor, you can use it to shrug off an extensive array of dangers. When you have bulwark armor, the bonus it provides to Reflex saves increases to +4. If it already provides a +4 bonus, you can treat the result of your Reflex saving throws as one degree of success better.',
    implemented: 'full',
    traits: ['Archetype', 'Guardian'],
    actionCost: 'passive',
    prerequisites: ['Sentinel Dedication'],
  },
  {
    id: 'guardian-repositioning-block',
    name: 'Repositioning Block',
    source: 'Battlecry!',
    category: 'class',
    level: 8,
    description: 'As you absorb a blow from an enemy, you can use their attack\'s momentum against them. Attempt to Reposition the creature whose attack you used Shield Block against. You don\'t need to have a hand free to do so. You gain a +1 item bonus to the Athletics check if your shield is at least 4th level, a +2 item bonus if your shield is at least 10th level, and a +3 item bonus if your shield is at least 16th level.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'free',
    prerequisites: ['Shield Block'],
    mechanics: 'Trigger: You used Shield Block to prevent damage from an adjacent creature\'s attack. Free Reposition attempt with item bonus based on shield level.',
  },
  {
    id: 'guardian-shield-from-arrows',
    name: 'Shield from Arrows',
    source: 'Battlecry!',
    category: 'class',
    level: 8,
    description: 'You place your shield in the path of an oncoming projectile. Your adjacent ally gains a +4 circumstance bonus to AC against the triggering attack. If the attack misses, you have deflected it with your shield.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An adjacent ally is the target of a physical ranged Strike. Requirements: You can see the attacker, you are not off-guard, and you have Raised your Shield.',
  },
  {
    id: 'guardian-shield-wallop',
    name: 'Shield Wallop',
    source: 'Battlecry!',
    category: 'class',
    level: 8,
    description: 'Attacks with your shield knock the sense out of your foes. Make a shield bash, shield boss, or shield spikes Strike. If you hit and deal damage, the target is stupefied 1 until the start of your next turn (stupefied 2 on a critical hit). If your shield is a tower shield, fortress shield, or another shield that grants a higher circumstance bonus to AC when you Take Cover behind it, the creature is instead stupefied 2 if you hit and deal damage to it (stupefied 3 on a critical hit).',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding a shield. Tower/fortress shield: stupefied 2 (3 on crit).',
  },

  // ── Level 10 ─────────────────────────────────────────
  {
    id: 'guardian-belly-flop',
    name: 'Belly Flop',
    source: 'Battlecry!',
    category: 'class',
    level: 10,
    description: 'You crush an enemy under the enormous weight of your armor. You drop prone and make a fist Strike against the prone enemy. You don\'t take the penalty from being prone to this Strike\'s attack roll, nor do you need to have a free hand to make it. If you\'re wielding a gauntlet or spiked gauntlet, you can Strike with one of those weapons instead of your fist. If you hit, you immobilize the target, and you can add your armor\'s item bonus to your Athletics for the Escape DC. The immobilization ends automatically if you Stand or otherwise move from the spot where you dropped prone.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 1,
    mechanics: 'Requirements: You are wearing medium or heavy armor and are standing adjacent to a prone enemy. Immobilizes on hit; Escape DC includes armor item bonus.',
  },
  {
    id: 'guardian-get-behind-me',
    name: 'Get Behind Me!',
    source: 'Battlecry!',
    category: 'class',
    level: 10,
    description: 'When saving your allies from harm, you push them behind you to better protect them. When you use Intercept Attack to protect an ally, you can move that ally up to 10 feet if they\'re willing. You can\'t move the ally to a position outside your reach, you can\'t move them into or through obstacles, and you must move them farther away from the source of the attack if possible. This movement doesn\'t trigger reactions.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    prerequisites: ['Intercept Attack'],
  },
  {
    id: 'guardian-momentum-strike',
    name: 'Momentum Strike',
    source: 'Battlecry!',
    category: 'class',
    level: 10,
    description: 'Putting your weight behind your weapon\'s swing, you can push one enemy into another. Make a melee Strike against an enemy of your size or smaller. If you hit and deal damage, you can move the enemy up to 5 feet (up to 10 feet on a critical hit) in a direction of your choice. It must remain within your reach during this movement, and you can\'t move it into or through obstacles. You can move the target into another creature\'s space. If you do, the second creature takes bludgeoning damage equal to double your Strength modifier and is pushed away from the target until it\'s no longer in the same space. If there\'s no room for the second creature to move, you can\'t move the target into it.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 2,
  },
  {
    id: 'guardian-shield-salvation',
    name: 'Shield Salvation',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You can save your shield from total destruction, even after a devastating attack. The shield remains at 1 Hit Point instead of being destroyed. The shield still has the broken condition.',
    implemented: 'full',
    traits: ['Archetype', 'Guardian'],
    actionCost: 'reaction',
    prerequisites: ['Bastion Dedication'],
    mechanics: 'Trigger: Your shield would be destroyed (such as by reducing to 0 HP from Shield Block). Shield stays at 1 HP instead, gains broken condition.',
  },
  {
    id: 'guardian-sure-footed',
    name: 'Sure-Footed',
    source: 'Battlecry!',
    category: 'class',
    level: 10,
    description: 'Even if you\'re knocked off balance, your armor continues to protect you. You don\'t take a penalty to AC from the clumsy condition if you\'re wearing medium or heavy armor. Your clumsy condition still applies to other Dexterity-based checks and DCs, and this benefit is negated if the armor is broken.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-tough-cookie',
    name: 'Tough Cookie',
    source: 'Battlecry!',
    category: 'class',
    level: 10,
    description: 'Though you\'ve taken a lot of punishment, you aren\'t easily brought down. You gain a number of temporary Hit Points equal to half your maximum Hit Points that last for 1 minute.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
    mechanics: 'Frequency: Once per day. Requirements: Your current Hit Points are at half your maximum or less. Temp HP = half max HP for 1 minute.',
  },

  // ── Level 12 ─────────────────────────────────────────
  {
    id: 'guardian-armor-break',
    name: 'Armor Break',
    source: 'Battlecry!',
    category: 'class',
    level: 12,
    description: 'You flex your muscles to crack your damaged armor, blasting jagged shards into nearby enemies. Each enemy in a 10-foot emanation takes 11d6 piercing damage with a Reflex save against your class DC. You can push any enemy that fails its save 5 feet away from you (or up to 10 feet on a critical failure). The damage increases by 1d6 per level beyond 14th. Your armor gains the broken condition. While your armor remains broken due to Armor Break, you don\'t take its penalty to Speed. In addition, if the broken armor has the bulwark trait, you retain its bonus to Reflex saves, but the bonus is reduced by 1.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
    mechanics: 'Requirements: You are wearing medium or heavy armor that doesn\'t have the broken condition, and your current Hit Points are at half your maximum or lower. 11d6 piercing, +1d6 per level beyond 14th.',
  },
  {
    id: 'guardian-armored-counterattack',
    name: 'Armored Counterattack',
    source: 'Battlecry!',
    category: 'class',
    level: 12,
    description: 'With the might of your armor behind you, you hit back at a foe who would dare try to hurt your allies. After Intercepting the Attack, make your own Strike against the triggering enemy. If your Strike hits, you Taunt the target; this Taunt gains the visual trait.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'free',
    prerequisites: ['Intercept Attack'],
    mechanics: 'Trigger: You use Intercept Attack. Free Strike against the triggering enemy, auto-Taunt on hit.',
  },
  {
    id: 'guardian-devastating-shield-wallop',
    name: 'Devastating Shield Wallop',
    source: 'Battlecry!',
    category: 'class',
    level: 12,
    description: 'The impact of your shield sends foes tumbling to the ground. When you use Shield Wallop, after its other effects, the target attempts a Fortitude saving throw against your class DC. If your shield is a tower shield, fortress shield, or another shield that grants a higher circumstance bonus to AC when you Take Cover behind it, the target takes a -2 circumstance penalty to this saving throw. Critical Success: The target takes no additional effect. Success: The target is off-guard to you until the end of the current turn. Failure: The target is knocked prone. Critical Failure: The target is knocked prone and stunned 1.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 'passive',
    prerequisites: ['Shield Wallop'],
  },
  {
    id: 'guardian-paragons-guard',
    name: 'Paragon\'s Guard',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'Once you\'ve had a moment to set your stance, you always have your shield ready without a thought. While you are in this stance, you constantly have your shield raised as if you\'d used the Raise a Shield action, as long as you meet that action\'s requirements.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian', 'Stance'],
    actionCost: 1,
    mechanics: 'Requirements: You are wielding a shield. Persistent Raise a Shield while in stance.',
  },
  {
    id: 'guardian-right-where-you-want-them',
    name: 'Right Where You Want Them',
    source: 'Battlecry!',
    category: 'class',
    level: 12,
    description: 'Whether with a weapon or your bare hands, you keep your opponents in their place. Increase the maximum distance you can Reposition or Shove an opponent to 10 feet on a success or 15 feet on a critical success.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    prerequisites: ['Master in Athletics'],
  },
  {
    id: 'guardian-scattering-charge',
    name: 'Scattering Charge',
    source: 'Battlecry!',
    category: 'class',
    level: 12,
    description: 'You charge into a group of enemies to send them flying. Stride up to your Speed. At the end of your movement, you can Shove up to three creatures within your reach. You don\'t need a hand free to do so. You attempt a separate Athletics check for each one; each attempt counts toward your multiple attack penalty, but the penalty doesn\'t increase until after you\'ve made all the attempts. Regardless of your results, you can\'t Stride to follow any of the targets.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 3,
    mechanics: 'Requirements: You are wearing medium or heavy armor. Stride then Shove up to 3 creatures.',
  },
  {
    id: 'guardian-weakening-assault',
    name: 'Weakening Assault',
    source: 'Battlecry!',
    category: 'class',
    level: 12,
    description: 'With a barrage of blows, you diminish an enemy\'s strength. Strike an enemy affected by your Taunt twice. If either Strike hits, the target is enfeebled 1 until the beginning of your next turn. If both Strikes hit, the target is enfeebled 3 instead.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
  },

  // ── Level 14 ─────────────────────────────────────────
  {
    id: 'guardian-blanket-defense',
    name: 'Blanket Defense',
    source: 'Battlecry!',
    category: 'class',
    level: 14,
    description: 'Raise a Shield. Until the start of your next turn or until you no longer have your shield raised, each ally that ends their turn adjacent to you gains the benefits of your raised shield. You can Shield Block a hit against any adjacent ally (each one costs you a reaction as normal). If you are wielding a tower shield, fortress shield, or another shield that grants a higher circumstance bonus to AC when you Take Cover behind it, any adjacent ally can Take Cover behind your shield to gain the increased bonus to AC.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 3,
  },
  {
    id: 'guardian-bloody-denial',
    name: 'Bloody Denial',
    source: 'Battlecry!',
    category: 'class',
    level: 14,
    description: 'Make a Strike. If you hit, the target must attempt a Fortitude saving throw against your class DC. If your Strike was a critical hit, the result of the save is one degree worse. Critical Success: The target is unaffected. Success: Choose an ally. Until the start of your next turn, the creature can\'t use reactions against that ally. Failure: The creature can\'t use reactions until the start of your next turn. Critical Failure: As failure, plus the creature is stunned 1.',
    implemented: 'full',
    traits: ['Flourish', 'Guardian'],
    actionCost: 2,
  },
  {
    id: 'guardian-keep-up-the-good-fight',
    name: 'Keep up the Good Fight',
    source: 'Battlecry!',
    category: 'class',
    level: 14,
    description: 'Instead of being knocked out, you\'re reduced to 1 HP. You increase your wounded value by 1 and gain temporary HP equal to your level that last for 1 round.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'reaction',
    mechanics: 'Frequency: Once per hour. Trigger: An enemy reduces you to 0 Hit Points but doesn\'t kill you. Stay at 1 HP, wounded +1, temp HP = level for 1 round.',
  },
  {
    id: 'guardian-opening-stance',
    name: 'Opening Stance',
    source: 'Battlecry!',
    category: 'class',
    level: 14,
    description: 'At the first sign of trouble, often before you consciously realize the danger, you drop into a stance with a mere thought. Use an action that has the stance trait.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'free',
    mechanics: 'Trigger: You roll initiative. Immediately use a stance action as a free action.',
  },

  // ── Level 16 ─────────────────────────────────────────
  {
    id: 'guardian-clang',
    name: 'Clang!',
    source: 'Battlecry!',
    category: 'class',
    level: 16,
    description: 'Either Strike the triggering enemy or Stride up to your Speed toward the triggering enemy. If you Stride and end your movement adjacent to the triggering enemy, it\'s off-guard until the end of your next turn.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An enemy critically misses a Strike or spell attack roll against your AC. Strike or Stride toward them; if Stride ends adjacent, target is off-guard.',
  },
  {
    id: 'guardian-clobber',
    name: 'Clobber',
    source: 'Battlecry!',
    category: 'class',
    level: 16,
    description: 'With a mighty blow, you send an enemy flying backward and onto the ground. Make a melee Strike. If you hit and deal damage, the target must attempt a Fortitude save against your class DC. Critical Success: The creature is unaffected. Success: The creature is pushed 5 feet. Failure: The creature is pushed 10 feet and knocked prone. Critical Failure: The creature is pushed 20 feet and knocked prone.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
    mechanics: 'Requirements: You are wearing medium or heavy armor.',
  },
  {
    id: 'guardian-improved-reflexive-shield',
    name: 'Improved Reflexive Shield',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'When you use Shield Block against damage from a Reflex save, adjacent allies who would take damage from Reflex saves against the same effect also benefit from the damage reduction.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'passive',
    prerequisites: ['Reflexive Shield'],
  },
  {
    id: 'guardian-never',
    name: 'Never!',
    source: 'Battlecry!',
    category: 'class',
    level: 16,
    description: 'Each time you would attack an ally due to being confused or controlled, you can attempt another saving throw against the effect with a +4 circumstance bonus. If you succeed, you don\'t make the attack (though you still expend the actions). If your save ends the confused or controlled condition, you can take remaining actions normally. Failing this additional save doesn\'t worsen the effect.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },

  // ── Level 18 ─────────────────────────────────────────
  {
    id: 'guardian-demolish-defenses',
    name: 'Demolish Defenses',
    source: 'Battlecry!',
    category: 'class',
    level: 18,
    description: 'Make a melee Strike dealing +1 additional weapon die of damage (+2 dice against your taunted enemy). This counts as two attacks for your multiple attack penalty. If you hit and deal damage, the target attempts a Fortitude save against your class DC. Critical Success: No additional effect. Success: The target is off-guard until the end of your next turn. Failure: The target is clumsy 2 until the end of your next turn. Once clumsy ends, the target is off-guard for 1 round. Critical Failure: As failure, but clumsy 3.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 2,
  },
  {
    id: 'guardian-perfect-protection',
    name: 'Perfect Protection',
    source: 'Battlecry!',
    category: 'class',
    level: 18,
    description: 'Each time you\'re critically hit while wearing medium or heavy armor, attempt a DC 14 flat check. On a success, it becomes a normal hit. If your armor has a fortification rune, roll only one flat check but the DC is 12 (or DC 10 with greater fortification).',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-quick-vengeance',
    name: 'Quick Vengeance',
    source: 'Battlecry!',
    category: 'class',
    level: 18,
    description: 'When you use Intercept Attack or Shield Block, you are quickened on your next turn. You can use the extra action only to Stride closer to the triggering enemy or to Strike that enemy.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    prerequisites: ['Intercept Attack'],
  },
  {
    id: 'guardian-shield-from-spells',
    name: 'Shield from Spells',
    source: 'Battlecry!',
    category: 'class',
    level: 18,
    description: 'You can use Shield from Arrows against ranged spell attacks and other ranged attacks, not just physical ranged Strikes.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    prerequisites: ['Shield from Arrows'],
  },

  // ── Level 20 ─────────────────────────────────────────
  {
    id: 'guardian-boundless-reprisals',
    name: 'Boundless Reprisals',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'At the start of each enemy\'s turn, you gain a reaction you can use only during that turn for any reaction from a class feat or class feature from the class that granted you this feat.',
    implemented: 'full',
    traits: ['Fighter', 'Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-great-shield-mastery',
    name: 'Great Shield Mastery',
    source: 'Battlecry!',
    category: 'class',
    level: 20,
    description: 'You continually benefit from Take Cover without needing to spend an action, as long as you have a shield raised and it\'s a tower shield, fortress shield, or other shield that grants a higher circumstance bonus to AC when you Take Cover behind it. This benefit ends only if you cease having the shield raised, not from the normal conditions that end Take Cover.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
  },
  {
    id: 'guardian-unyielding-force',
    name: 'Unyielding Force',
    source: 'Battlecry!',
    category: 'class',
    level: 20,
    description: 'While wearing medium or heavy armor, the resistance you receive from Guardian\'s Armor increases to 6 + half your level.',
    implemented: 'full',
    traits: ['Guardian'],
    actionCost: 'passive',
    mechanics: 'Guardian\'s Armor resistance becomes 6 + floor(level / 2) instead of 1 + floor(level / 2).',
  },
];
