/**
 * Gunslinger Class Features & Feats — PF2e Remastered (Guns & Gears)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=20
 *
 * Key Attribute: DEX | HP: 8 + CON
 * Uncommon class (access: Ustalav, Shackles, Alkenstar, Tian Xia, Arcadia)
 * Perception: Expert -> Master (L7) -> Legendary (L19)
 * Fort: Expert -> Master (L17, Lead Constitution, success->crit)
 * Reflex: Expert -> Master (L11, Blast Dodger, success->crit)
 * Will: Trained -> Expert (L3, Stubborn)
 * Firearms/Crossbows: Expert simple+martial -> Master (L5) -> Legendary (L13)
 *   Advanced: Trained -> Expert (L5) -> Master (L13)
 * Other Weapons: Trained simple+martial+unarmed -> Expert (L5) -> Master (L13)
 * Armor: Trained light+medium+unarmored -> Expert (L13) -> Master (L19)
 * Class DC: Trained -> Expert (L9) -> Master (L17)
 * Skills: Way skill + 3 + INT
 *
 * Gunslinger's Way: Choose a way (Drifter, Pistolero, Sniper, Vanguard, Triggerbrand)
 *   Grants initial deed, slinger's reload, and way skill.
 * Slinger's Precision: +2 precision (crossbow, non-repeating), +1d4 precision (firearm,
 *   non-repeating). Upgrades to +3/+1d6 with Gunslinging Legend.
 * Weapon Specialization: +2/+3/+4 damage (L7); Greater (L15): +4/+6/+8.
 *
 * Class features: 16 (L1-L19)
 * Class feats: 74 (L1-L20)
 */

import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION } from './sharedFeats';

// ── Gunslinger Class Features ────────────────────────────

export const GUNSLINGER_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'gunslinger-way',
    name: 'Gunslinger\'s Way',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 1,
    description: 'All gunslingers have a particular way they follow, a combination of philosophy and combat style that defines both how they fight and the weapons they excel with. At 1st level, your way grants you an initial deed, a unique reload action called a slinger\'s reload, and proficiency with a particular skill. You also gain advanced and greater deeds at later levels, as well as access to way-specific feats. Ways include: Way of the Drifter (Acrobatics, Reloading Strike, Into the Fray), Way of the Pistolero (Deception or Intimidation, Raconteur\'s Reload, Ten Paces), Way of the Sniper (Stealth, Covered Reload, One Shot One Kill), Way of the Vanguard (Athletics, Clear a Path, Living Fortification), and Way of the Triggerbrand (Thievery, Touch and Go, Spring the Trap).',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'Choose a way. Grants initial deed (free action on initiative), slinger\'s reload (1-action reload + benefit), way skill, and later advanced (L9) and greater (L15) deeds.',
    subChoices: { label: 'Choose a way', options: [
      { id: 'drifter', name: 'Way of the Drifter', description: 'Melee + ranged combo; Into the Fray deed, Reloading Strike' },
      { id: 'pistolero', name: 'Way of the Pistolero', description: 'One-handed firearms; Ten Paces deed, Raconteur\'s Reload' },
      { id: 'sniper', name: 'Way of the Sniper', description: 'Long-range precision; One Shot One Kill deed, Covered Reload' },
      { id: 'triggerbrand', name: 'Way of the Triggerbrand', description: 'Combination weapons; Initial Flourish deed, Triggered Brand' },
      { id: 'vanguard', name: 'Way of the Vanguard', description: 'Scatter weapons; Living Fortification deed, Clear a Path' },
    ] },
  },
  {
    id: 'gunslinger-slingers-precision',
    name: 'Slinger\'s Precision',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 1,
    description: 'You have steady precision with guns and crossbows and can use weapons that incorporate them effectively. You deal an extra +2 precision damage with Strikes made using crossbows that don\'t have the repeating trait, and deal an extra 1d4 precision damage on Strikes with firearms that don\'t have the repeating trait. If you have gunslinging legend, you instead deal +3 additional precision damage with Strikes using crossbows that aren\'t repeating, and you deal an additional 1d6 precision damage with non-repeating firearm Strikes. If you are using a combination weapon whose ranged form is a firearm or crossbow, you use your proficiency with firearms and crossbows for attacks made with the melee portion of that weapon.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'Non-repeating crossbow: +2 precision damage (+3 with Gunslinging Legend). Non-repeating firearm: +1d4 precision (+1d6 with Gunslinging Legend). Combination weapons: use firearm/crossbow proficiency for melee portion.',
  },

  // ── Level 3 ──────────────────────────────────────────
  {
    id: 'gunslinger-stubborn',
    name: 'Stubborn',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 3,
    description: 'You don\'t like being told what to do, and you don\'t give up. Your proficiency rank for Will saves increases to expert. When you fail, but don\'t critically fail, a Will save against an effect that would give you the controlled condition, you can attempt a second save against the effect at the start of your next turn. On a successful second save, the controlled condition ends, though any other effects remain. As normal, failing this second save doesn\'t allow you to attempt a third save on the subsequent turn.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.will -> expert. On failing (not crit failing) Will vs controlled: second save at start of next turn.',
  },

  // ── Level 5 ──────────────────────────────────────────
  {
    id: 'gunslinger-weapon-mastery',
    name: 'Gunslinger Weapon Mastery',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 5,
    description: 'You fully understand the best way to utilize your unique weapons. Your proficiency rank increases to master with simple and martial firearms and crossbows. Your proficiency rank for advanced firearms and crossbows, simple weapons, martial weapons, and unarmed attacks increases to expert. You gain access to the critical specialization effects for firearms and crossbows.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies: simple+martial firearms/crossbows -> master, advanced firearms/crossbows + simple+martial weapons + unarmed -> expert. Critical specialization for firearms/crossbows.',
  },

  // ── Level 7 ──────────────────────────────────────────
  {
    id: 'gunslinger-perception-mastery',
    name: 'Perception Mastery',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 7,
    description: 'Through your adventures, you\'ve developed keen awareness and attention to detail. Your proficiency rank for Perception increases to master.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.perception -> master.',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Gunslinger', 7, {
    idOverride: 'gunslinger-weapon-specialization',
  }),

  // ── Level 9 ──────────────────────────────────────────
  {
    id: 'gunslinger-advanced-deed',
    name: 'Advanced Deed',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 9,
    description: 'You\'ve learned a powerful new technique of your chosen way. You gain the advanced deed ability of the way you chose at 1st level. Drifter: Finish the Job. Pistolero: Pistolero\'s Retort. Sniper: Vital Shot. Vanguard: Spinning Crush. Triggerbrand: Wind them Up.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'Gain advanced deed from your chosen way.',
  },
  {
    id: 'gunslinger-expertise',
    name: 'Gunslinger Expertise',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 9,
    description: 'Your special shots become harder for opponents to predict or resist. Your proficiency rank for your gunslinger class DC increases to expert.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC -> expert.',
  },

  // ── Level 11 ─────────────────────────────────────────
  {
    id: 'gunslinger-blast-dodger',
    name: 'Blast Dodger',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve learned to move quickly to avoid explosions, dragon\'s breath, and worse. Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.reflex -> master. Success on Reflex save -> critical success.',
  },

  // ── Level 13 ─────────────────────────────────────────
  {
    id: 'gunslinger-gunslinging-legend',
    name: 'Gunslinging Legend',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned unique techniques for wielding firearms and crossbows that give you unmatched skill in their use. Your proficiency rank increases to legendary with simple and martial firearms and crossbows and to master with advanced firearms and crossbows. Your proficiency rank for simple weapons, martial weapons, and unarmed attacks increases to master.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies: simple+martial firearms/crossbows -> legendary, advanced firearms/crossbows -> master, simple+martial weapons + unarmed -> master. Upgrades Slinger\'s Precision to +3/+1d6.',
  },
  {
    id: 'gunslinger-medium-armor-expertise',
    name: 'Medium Armor Expertise',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned to defend yourself better against attacks. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies: lightArmor/mediumArmor/unarmored -> expert.',
  },

  // ── Level 15 ─────────────────────────────────────────
  {
    id: 'gunslinger-greater-deed',
    name: 'Greater Deed',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 15,
    description: 'You\'ve mastered the pinnacle technique of your chosen way. You gain the greater deed ability of the way you chose at 1st level. Drifter: Drifter\'s Wake. Pistolero: Grim Swagger. Sniper: Ghost Shot. Vanguard: Siegebreaker. Triggerbrand: Break Them Down.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'Gain greater deed from your chosen way.',
  },
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Gunslinger', 15, {
    idOverride: 'gunslinger-greater-weapon-specialization',
  }),

  // ── Level 17 ─────────────────────────────────────────
  {
    id: 'gunslinger-lead-constitution',
    name: 'Lead Constitution',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 17,
    description: 'Your body has become accustomed to physical hazards and resistant to ailments. Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.fortitude -> master. Success on Fortitude save -> critical success.',
  },
  {
    id: 'gunslinger-shootists-edge',
    name: 'Shootist\'s Edge',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 17,
    description: 'You make shots others find impossible. Your proficiency rank for your gunslinger class DC increases to master. When using a ranged weapon in which you have master or greater proficiency, you ignore the penalty for attacking within the weapon\'s second and third range increments.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC -> master. Ignore 2nd and 3rd range increment penalties with master+ ranged weapons.',
  },

  // ── Level 19 ─────────────────────────────────────────
  {
    id: 'gunslinger-medium-armor-mastery',
    name: 'Medium Armor Mastery',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 19,
    description: 'Your skill with light and medium armor improves, increasing your ability to dodge or absorb blows. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies: lightArmor/mediumArmor/unarmored -> master.',
  },
  {
    id: 'gunslinger-perception-legend',
    name: 'Perception Legend',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 19,
    description: 'You notice things that most people can\'t detect. Your proficiency rank for Perception increases to legendary.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'proficiencies.perception -> legendary.',
  },
];

// ── Gunslinger Selectable Feats — PF2e Remastered (Guns & Gears + Impossible Lands + Firebrands)
// ─────────────────────────────────────────────────────────

export const GUNSLINGER_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'gunslinger-blast-lock',
    name: 'Blast Lock',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'Sometimes taking the shortest distance between two points involves removing an obstacle or two. You shoot your firearm at a lock within 10 feet. Make an attack roll against the DC required to Pick the Lock. Critical Success: You open the lock, or you achieve two successes toward opening a complex lock. Success: You open the lock, or you achieve one success toward opening a complex lock. Failure: You fail to open the lock, and your shot makes it harder to open. Future attempts to Pick the Lock or Blast the Lock take a -2 circumstance penalty. Critical Failure: As failure, but the penalty is -4.',
    implemented: 'full',
    traits: ['Attack', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a loaded firearm. Attack roll vs Pick Lock DC.',
  },
  {
    id: 'gunslinger-cover-fire',
    name: 'Cover Fire',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You lay down suppressive fire to protect allies by forcing foes to take cover from your wild attacks. Make a firearm or crossbow Strike; the target must decide before you roll your attack whether it will duck out of the way. If the target ducks, it gains a +2 circumstance bonus to AC against your attack, or a +4 circumstance bonus to AC if it has cover. It also takes a -2 circumstance penalty to ranged attack rolls until the end of its next turn. If the target chooses not to duck, you gain a +1 circumstance bonus to your attack roll for that Strike.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 1,
    mechanics: 'Frequency: Once per round. Requirements: You\'re wielding a loaded firearm or crossbow. Target chooses: duck (-2 ranged penalty) or stand (+1 to your attack).',
  },
  {
    id: 'gunslinger-crossbow-crack-shot',
    name: 'Crossbow Crack Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You\'re exceptionally skilled with the crossbow. The first time each round that you Interact to reload a crossbow you are wielding, including Interact actions as part of your slinger\'s reload and similar effects, you increase the range increment for your next Strike with that weapon by 10 feet and deal 1 additional precision damage per weapon damage die with that Strike. If your crossbow has the backstabber trait and you are attacking an off-guard target, backstabber instead deals 2 additional precision damage per weapon damage die in place of its normal effects.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
  {
    id: 'gunslinger-dual-weapon-reload',
    name: 'Dual-Weapon Reload',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You carry your ammunition in a way that allows you to reload while holding two weapons. While you\'re wielding two one-handed weapons, each in a different hand, you don\'t need a free hand to reload a one-handed ranged weapon you\'re wielding.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'Requirements: You are wielding two one-handed weapons, each in a different hand, one of which is a ranged weapon.',
  },
  {
    id: 'gunslinger-hit-the-dirt',
    name: 'Hit the Dirt!',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You fling yourself out of harm\'s way. You Leap. Your movement gives you a +2 circumstance bonus to AC against the triggering attack. Regardless of whether or not the triggering attack hits, you land prone after completing your Leap.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature you can see attempts a ranged Strike against you. Leap + prone, +2 AC vs triggering attack.',
  },
  {
    id: 'gunslinger-munitions-crafter',
    name: 'Munitions Crafter',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'Bullets and bombs can be scarce in some parts, so you\'ve learned to make your own. You become trained in Crafting and gain the advanced alchemy benefits. You can use the advanced alchemy benefits to create a number of daily consumables equal to 4 + half your level (rounded up); these consumables must be bombs or alchemical ammunition. You gain a formula book that includes the formula for black powder and four 1st-level types of common or uncommon alchemical ammunition or bombs of your choice. When crafting alchemical ammunition using advanced alchemy, you create the ammunition in batches of 4.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    mechanics: 'Trained in Crafting. Advanced alchemy: 4 + floor(level/2) daily consumables (bombs or alchemical ammo only, batches of 4).',
  },
  {
    id: 'gunslinger-sword-and-pistol',
    name: 'Sword and Pistol',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You\'re comfortable wielding a firearm or crossbow in one hand and a melee weapon in the other, combining melee attacks with shots from the firearm. When you make a successful ranged Strike against an enemy within your reach with your one-handed firearm or one-handed crossbow, that enemy is off-guard against your next melee attack with a one-handed melee weapon. When you make a successful melee Strike against an enemy with your one-handed melee weapon, the next ranged Strike you make against that enemy with a one-handed firearm or one-handed crossbow doesn\'t trigger reactions that would trigger on a ranged attack but not a melee attack, such as Reactive Strike. Either of these benefits is lost if not used by the end of your next turn.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },

  // ── Level 2 ──────────────────────────────────────────
  {
    id: 'gunslinger-defensive-armaments',
    name: 'Defensive Armaments',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'You use bulky firearms or crossbows to shield your body from your foes\' attacks. Any two-handed firearms and two-handed crossbows you wield gain the parry trait. If an appropriate weapon already has the parry trait, increase the circumstance bonus to AC it grants when used to parry from +1 to +2. While parrying with your weapon, you are immune to splash damage.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
  {
    id: 'gunslinger-fake-out',
    name: 'Fake Out',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'With a skilled flourish of your weapon, you force an enemy to acknowledge you as a threat. Make an attack roll to Aid the triggering attack. If you dealt damage to that enemy with the same weapon since the start of your last turn, you gain a +1 circumstance bonus to this roll.',
    implemented: 'full',
    traits: ['Gunslinger', 'Visual'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An ally is about to use an action that requires an attack roll, targeting a creature within your weapon\'s first range increment. Requirements: You\'re wielding a loaded firearm or crossbow.',
  },
  {
    id: 'gunslinger-pistol-twirl',
    name: 'Pistol Twirl',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'Your quick gestures and flair for performance distract your opponent, leaving it vulnerable to your follow-up attacks. You Feint against an opponent within the required weapon\'s first range increment, rather than an opponent within melee reach. If you succeed, the foe is off-guard against your melee and ranged attacks, rather than only your melee attacks. On a critical failure, you\'re off-guard against the target\'s melee and ranged attacks, rather than only its melee attacks.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 1,
    prerequisites: ['Trained in Deception'],
    mechanics: 'Requirements: You\'re wielding a loaded one-handed ranged weapon. Feint at range.',
  },
  {
    id: 'gunslinger-quick-draw',
    name: 'Quick Draw',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You draw your weapon and attack with the same motion. You Interact to draw a weapon, then Strike with that weapon.',
    implemented: 'full',
    traits: ['Gunslinger', 'Ranger', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'gunslinger-risky-reload',
    name: 'Risky Reload',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'You\'ve practiced a technique for rapidly reloading your firearm, but attempting to use this technique is a dangerous gamble with your firearm\'s functionality. Interact to reload a firearm, then make a Strike with that firearm. If the Strike fails, the firearm misfires.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a firearm. Reload + Strike; misfire on failure.',
  },
  {
    id: 'gunslinger-warning-shot',
    name: 'Warning Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'Who needs words when the roar of a gun is so much more succinct? You attempt to Demoralize a foe by firing your weapon into the air, using the firearm\'s maximum range rather than the usual range of 30 feet. This check doesn\'t take the -4 circumstance penalty if the target doesn\'t share a language with you.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 1,
    prerequisites: ['Trained in Intimidation'],
    mechanics: 'Requirements: You\'re wielding a loaded firearm. Demoralize at firearm range, no language penalty.',
  },

  // ── Level 4 ──────────────────────────────────────────
  {
    id: 'gunslinger-alchemical-shot',
    name: 'Alchemical Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'You\'ve practiced a technique for mixing alchemical bombs with your loaded shot. You Interact to retrieve the bomb (if it\'s not already in your hand) and pour its contents onto your ammunition, consuming the bomb, then resume your grip on the required weapon. Next, Strike with your firearm. The Strike deals damage of the same type as the bomb (for instance, fire damage for alchemist\'s fire), and it deals an additional 1d6 persistent damage of the same type as the bomb. If the Strike is a failure, you take 1d6 damage of the same type as the bomb you used, and the firearm misfires. The persistent damage increases to 2d6 if the bomb is 11th level or higher, or 3d6 if it\'s 17th level or higher.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You have an alchemical bomb worn or in one hand, and are wielding a firearm or crossbow. Pour bomb onto ammo, Strike. Converts damage type + persistent.',
  },
  {
    id: 'gunslinger-black-powder-boost',
    name: 'Black Powder Boost',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'You fire your weapon as you jump, using the kickback to go farther. You Leap and discharge your firearm to add a +10-foot status bonus to the distance traveled. If you spend 2 actions for Black Powder Boost, you High Jump or Long Jump instead. Special: An ability that allows you to High Jump or Long Jump as a single action (like the Quick Jump skill feat) lets you use Black Powder Boost as a single action for those jumps as well.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a loaded firearm. 1 action: Leap +10 ft. 2 actions: High/Long Jump +10 ft.',
  },
  {
    id: 'gunslinger-greenwatch-initiate',
    name: 'Greenwatch Initiate',
    source: 'Impossible Lands',
    category: 'class',
    level: 4,
    description: 'You\'ve received the basic training developed for all Greenwatch recruits. You become an expert in Survival and gain the Experienced Tracker and Survey Wildlife skill feats.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Trained in Survival'],
  },
  {
    id: 'gunslinger-instant-backup',
    name: 'Instant Backup',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'Even as your firearm misfires, you quickly draw a backup weapon. Release the misfired weapon and Interact to draw a different weapon that requires the same number of hands or fewer.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'reaction',
    mechanics: 'Trigger: Your attack with a firearm misfires.',
  },
  {
    id: 'gunslinger-ostentatious-reload',
    name: 'Ostentatious Reload',
    source: 'Firebrands',
    category: 'class',
    level: 4,
    description: 'Every good Firebrand knows that style can be as important as substance—so long as you don\'t screw up the delivery. Make a Performance check against an easy DC for your level as you spin your guns around and juggle ammunition to reload them. Critical Success: You Interact to reload up to two firearms you are currently wielding. Success: You Interact to reload a single firearm you are currently wielding. Failure: You drop one of the required firearms and a round of ammunition on the ground in your space. Critical Failure: You drop both firearms and two rounds on the ground in your space.',
    implemented: 'full',
    traits: ['Uncommon', 'Gunslinger'],
    actionCost: 1,
    prerequisites: ['Trained in Performance'],
    mechanics: 'Requirements: You\'re wielding two one-handed firearms. Performance check to reload.',
  },
  {
    id: 'gunslinger-paired-shots',
    name: 'Paired Shots',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'Your shots hit simultaneously. Make two Strikes, one with each of your two ranged weapons, each using your current multiple attack penalty. Both Strikes must have the same target. If both attacks hit, combine their damage and then add any applicable effects from both weapons. You add any precision damage only once, to the attack of your choice. Combine the damage from both Strikes and apply resistances and weaknesses only once. This counts as two attacks when calculating your multiple attack penalty.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding two weapons, each of which can be either a loaded one-handed firearm or loaded one-handed crossbow.',
  },
  {
    id: 'gunslinger-running-reload',
    name: 'Running Reload',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You can reload your weapon on the move. You Stride, Step, or Sneak, then Interact to reload.',
    implemented: 'full',
    traits: ['Gunslinger', 'Ranger'],
    actionCost: 1,
  },

  // ── Level 6 ──────────────────────────────────────────
  {
    id: 'gunslinger-advanced-shooter',
    name: 'Advanced Shooter',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You\'ve dedicated your training to mastering even the most complex and weird firearms and crossbows from across the world. You gain proficiency with all advanced firearms as if they were martial firearms and with all advanced crossbows as if they were martial crossbows.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
  {
    id: 'gunslinger-cauterize',
    name: 'Cauterize',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You use the smoking barrel of your firearm to sear shut a bleeding wound. Make a Strike with your firearm. You then press the heated barrel to the wounds of you or an ally within reach that is taking persistent bleed damage, giving an immediate flat check to end the bleed with the lower DC for particularly effective assistance.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a loaded firearm and you or an adjacent ally are taking persistent bleed damage.',
  },
  {
    id: 'gunslinger-defy-fey',
    name: 'Defy Fey',
    source: 'Impossible Lands',
    category: 'class',
    level: 6,
    description: 'You are keen to the wiles of the fey and can usually shake off their magic. Whenever you fail, but don\'t critically fail, a save against a spell with a duration of at least 1 round cast by a fey creature, you can attempt a second save against the original DC at the start of your next turn to end any lingering effects the spell might have. This can end persistent damage caused by a spell but can\'t reverse any effects that have been resolved already.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Greenwatch Initiate'],
  },
  {
    id: 'gunslinger-drifters-juke',
    name: 'Drifter\'s Juke',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You move in and out of range to complement your attacks. You Step, make a Strike, Step, and make another Strike. One Strike must be a ranged Strike using your firearm or crossbow, and the other must be a melee Strike using your melee weapon or unarmed attack. You can choose not to take one or both Steps.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 2,
    prerequisites: ['Way of the Drifter'],
    mechanics: 'Requirements: You\'re wielding a firearm or crossbow in one hand, and your other hand is either wielding a melee weapon or is empty.',
  },
  {
    id: 'gunslinger-fey-tracker',
    name: 'Fey Tracker',
    source: 'Impossible Lands',
    category: 'class',
    level: 6,
    description: 'You are exceptionally skilled at noticing the subtle techniques fey use to avoid notice. You gain a +2 circumstance bonus to Survival checks to Track fey creatures, to Perception checks to Seek for hidden fey, and to your Perception DC to resist a fey creature\'s attempt to Create a Diversion.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Greenwatch Initiate'],
  },
  {
    id: 'gunslinger-munitions-machinist',
    name: 'Munitions Machinist',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You\'re particularly adept at crafting ammunition and bombs. You gain the Quick Alchemy benefits, creating up to 4 versatile vials during your daily preparations. You can use Quick Alchemy only to create bombs or alchemical ammunition. Using Quick Alchemy to create alchemical ammunition also counts as 1 action toward activating that ammunition.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Munitions Crafter', 'Expert in Crafting'],
  },
  {
    id: 'gunslinger-nightwave-springing-reload',
    name: 'Nightwave Springing Reload',
    source: 'Firebrands',
    category: 'class',
    level: 6,
    description: 'Training with the crew of the Nightwave has taught you their technique for reloading while leaping to board another ship. You Leap and then Interact to reload, or Interact to reload and then Leap. You can perform this ability as a 2-action activity to use your Leap to High Jump or Long Jump without needing to Stride at least 10 feet first.',
    implemented: 'full',
    traits: ['Uncommon', 'Gunslinger'],
    actionCost: 1,
  },
  {
    id: 'gunslinger-phalanx-breaker',
    name: 'Phalanx Breaker',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You know that to take out an enemy formation, you must punch a hole through its center. Make a ranged Strike with the required weapon against a target within the weapon\'s first range increment. The target is pushed directly back 10 feet (20 feet on a critical hit), and if this pushes the target into an obstacle, the target takes bludgeoning damage equal to half your level.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    prerequisites: ['Way of the Vanguard'],
    mechanics: 'Requirements: You\'re wielding a two-handed firearm or a two-handed crossbow.',
  },
  {
    id: 'gunslinger-pistoleros-challenge',
    name: 'Pistolero\'s Challenge',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'With a stern call, carefully chosen barb, or some other challenging declaration, you demand your foe\'s attention in a duel. Choose an opponent within 30 feet who you can perceive and can hear you, and make your choice of a Deception or Intimidation check against the target\'s Will DC. No matter the result of the check, the foe is temporarily immune to your Pistolero\'s Challenge until noon the next day. Success: Both you and the opponent gain a +2 status bonus to damage rolls with Strikes made against each other. If you\'re a master in the skill you used for the check, the status bonus increases to +3, and if you\'re legendary, it increases to +4. You can have only one challenge in effect at a time; challenging a new opponent ends this effect on any current target. The effect lasts until one of you is defeated, flees, or the encounter ends. Critical Failure: You become frightened 1 and can\'t use this ability again for 1 minute.',
    implemented: 'full',
    traits: ['Auditory', 'Flourish', 'Gunslinger', 'Linguistic', 'Mental'],
    actionCost: 1,
    prerequisites: ['Way of the Pistolero'],
  },
  {
    id: 'gunslinger-scatter-blast',
    name: 'Scatter Blast',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You pack your weapon with additional shot and powder, creating a risky but devastating wave of destruction. Make a ranged Strike with the firearm. The firearm\'s range increment increases by 20 feet and the radius of its scatter increases by 20 feet. The Strike gains the following failure conditions. Failure: The firearm misfires, but it doesn\'t cause the other critical failure effects. Critical Failure: The firearm misfires and also explodes. It becomes broken, and it deals its normal weapon damage to all creatures in a 20-foot burst centered on the firearm, with a basic Reflex save against your class DC.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding a loaded firearm that has the scatter trait.',
  },
  {
    id: 'gunslinger-snipers-aim',
    name: 'Sniper\'s Aim',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You take an extra moment to carefully sync your aim and breathing, then fire a shot with great accuracy. Make a ranged weapon Strike. You gain a +2 circumstance bonus to this Strike\'s attack roll and ignore the target\'s concealment. If you\'re using a kickback firearm, you don\'t take the normal circumstance penalty on this Strike for not having the required Strength score or firing without using a stabilizer.',
    implemented: 'full',
    traits: ['Concentrate', 'Gunslinger'],
    actionCost: 2,
    prerequisites: ['Way of the Sniper'],
  },
  {
    id: 'gunslinger-triggerbrand-salvo',
    name: 'Triggerbrand Salvo',
    source: 'Impossible Lands',
    category: 'class',
    level: 6,
    description: 'You slice, stab, or batter your opponent with the melee portion of your combination weapon before pulling the trigger at point-blank range. Make a melee Strike with your combination weapon. If the Strike is successful, you can immediately make a ranged Strike against the same target with that combination weapon, and you get a +2 circumstance bonus to the attack roll. This counts as two attacks toward your multiple attack penalty, but you don\'t apply the multiple attack penalty until after making both attacks.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 1,
    prerequisites: ['Way of the Triggerbrand'],
    mechanics: 'Requirements: You\'re wielding a combination weapon.',
  },

  // ── Level 8 ──────────────────────────────────────────
  {
    id: 'gunslinger-bullet-split',
    name: 'Bullet Split',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You carefully align your weapon with the edge of your blade, splitting the projectile in two as you fire to attack two different targets. Make two Strikes, one each against two separate targets. The targets must be adjacent to each other and within your weapon\'s maximum range. Each of these attacks takes a -2 penalty to the attack roll, but the two count as only one attack when calculating your multiple attack penalty.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a firearm or crossbow in one hand and a slashing (or versatile S) melee weapon in the other.',
  },
  {
    id: 'gunslinger-greenwatch-veteran',
    name: 'Greenwatch Veteran',
    source: 'Impossible Lands',
    category: 'class',
    level: 8,
    description: 'Your time spent tracking your target allows you to quickly identify its weaknesses and relay them to your allies. Attempt a Recall Knowledge check against the creature you were Tracking. On a success, you always know the creature\'s greatest weakness and highest resistance or immunity, in addition to any other information the check would typically provide. You immediately use a quick series of hand gestures to signal this information to any allies who can see you.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'free',
    mechanics: 'Trigger: Your turn starts, and you\'re in combat against a creature you spent at least 10 minutes Tracking.',
  },
  {
    id: 'gunslinger-grit-and-tenacity',
    name: 'Grit and Tenacity',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You call upon deep reserves of toughness and mental fortitude to power through an otherwise debilitating effect. Reroll the triggering save with a +2 circumstance bonus; you must use the second result.',
    implemented: 'full',
    traits: ['Fortune', 'Gunslinger'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You fail a Fortitude or Will save. Frequency: Once per hour.',
  },
  {
    id: 'gunslinger-leap-and-fire',
    name: 'Leap and Fire',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You\'re quick enough to line up a shot even while diving to the ground. When you use your Hit the Dirt! reaction, at any point during your Leap you can also make a ranged Strike with a loaded firearm or crossbow, targeting the creature whose attack triggered the reaction.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Hit the Dirt!'],
  },
  {
    id: 'gunslinger-smoke-curtain',
    name: 'Smoke Curtain',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You load an extra dose of powder into your shot, causing it to belch a cloud of smoke. You make a Strike with your firearm and create a cloud of smoke in a 20-foot emanation centered on your location. Creatures are concealed while within the smoke, and creatures outside the area are concealed to creatures within the smoke. The smoke dissipates at the start of your next turn. If your Strike is a critical failure, your firearm misfires.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding a loaded firearm and are wearing or holding a dose of black powder.',
  },
  {
    id: 'gunslinger-stab-and-blast',
    name: 'Stab and Blast',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You slice or smash your opponent with the melee portion of your weapon before pulling the trigger at point-blank range. Make a melee Strike with the required weapon. If the Strike is successful, you can immediately make a ranged Strike against the same target with a +2 circumstance bonus to the attack roll. This counts as two attacks toward your multiple attack penalty, but you don\'t apply the multiple attack penalty until after making both attacks.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a firearm with an attached bayonet or reinforced stock, a fire lance, or a combination weapon.',
  },
  {
    id: 'gunslinger-unseen-passage',
    name: 'Unseen Passage',
    source: 'Impossible Lands',
    category: 'class',
    level: 8,
    description: 'You have mastered a magical technique for moving through dangerous woodlands unseen. You can cast pass without trace as an innate primal spell heightened to a spell rank equal to half your level rounded up.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    mechanics: 'Frequency: Once per day. Innate primal spell: pass without trace.',
  },

  // ── Level 10 ─────────────────────────────────────────
  {
    id: 'gunslinger-called-shot',
    name: 'Called Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You target a specific area of your foe\'s anatomy to debilitating effect. Declare a part of your foe\'s anatomy to target and make a ranged weapon Strike. If you hit and deal damage, the target takes one of the following effects: Arms: enfeebled 2 until end of your next turn (crit: also enfeebled 1 for 1 minute). Head: stupefied 2 until end of your next turn (crit: also stupefied 1 for 1 minute). Legs: -10-foot status penalty to Speeds until end of your next turn (crit: also -5-foot for 1 minute). Wings: if flying, falls 20 feet (40 feet on crit), gradual enough to take no fall damage.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 2,
    subChoices: { label: 'Choose body part', options: [
      { id: 'arms', name: 'Arms', description: 'Enfeebled 2 (crit: enfeebled 1 for 1 min)' },
      { id: 'head', name: 'Head', description: 'Stupefied 2 (crit: stupefied 1 for 1 min)' },
      { id: 'legs', name: 'Legs', description: '-10 ft Speeds (crit: -5 ft for 1 min)' },
      { id: 'wings', name: 'Wings', description: 'Falls 20 ft (crit: 40 ft), no fall damage' },
    ] },
  },
  {
    id: 'gunslinger-deflecting-shot',
    name: 'Deflecting Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You\'re always ready to take a quick shot to deflect a weapon or distract a foe enough to render them off target. The ally gains a +2 circumstance bonus to their AC against the triggering attack. You use this reaction after the result of the attack roll is revealed, so you know whether the +2 will make a sufficient difference.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An ally within the first range increment of your firearm or crossbow is hit by an attack, and you can see the attacker. Requirements: You\'re wielding a loaded firearm or crossbow.',
  },
  {
    id: 'gunslinger-greenwatcher',
    name: 'Greenwatcher',
    source: 'Impossible Lands',
    category: 'class',
    level: 10,
    description: 'Your experience fighting against and alongside fey creatures is nearly unrivaled. Any weapon you wield or unarmed attack you make against a fey creature is treated as cold iron. Whenever you critically fail a save against a spell cast by a fey creature, it\'s instead treated as a normal failure. Whenever you critically succeed on a Strike against a fey creature, the target is immediately subject to the effects of a faerie fire spell (innate 2nd-level primal for counteracting).',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Defy Fey'],
  },
  {
    id: 'gunslinger-penetrating-fire',
    name: 'Penetrating Fire',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You blast a bullet through one foe and into another. Choose two targets, one of which would give the other lesser cover against your ranged attacks. Make a single ranged Strike with the required weapon against both targets. This attack ignores any lesser cover the nearer target provides the other. Roll damage only once and apply it to each creature you hit. Penetrating Fire counts as two attacks for your multiple attack penalty.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding a loaded firearm or crossbow.',
  },
  {
    id: 'gunslinger-precious-munitions',
    name: 'Precious Munitions',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You mix flecks of precious materials you\'ve gathered on your journeys into your custom bullets to bring out those properties in your temporary ammunition. You can use advanced alchemy to create standard-grade adamantine, cold iron, or silver ammunition, spending 1 batch of reagents per piece of ammunition. At 15th level, you can create high-grade adamantine, cold iron, or silver ammunition.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Munitions Machinist'],
  },
  {
    id: 'gunslinger-rebounding-assault',
    name: 'Rebounding Assault',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You hurl your melee weapon at an opponent, then fire a bullet into the weapon\'s hilt, making it deal additional damage and bounce back to your grasp. Make a thrown ranged Strike with the melee weapon, then a ranged Strike with your firearm. Both Strikes use your current multiple attack penalty and this counts as two attacks. If the melee weapon doesn\'t already have the thrown trait, it gains thrown 10 feet during this activity. If both attacks are successful, the bullet hits the thrown weapon instead of the target, combining damage (using thrown weapon\'s type) and adding 1d6 precision damage. The weapon rebounds to your hand. Otherwise, carry out Strikes normally and the weapon stays in the target\'s space.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding a loaded firearm or crossbow in one hand and a bludgeoning or slashing melee weapon in the other.',
  },
  {
    id: 'gunslinger-redirecting-shot',
    name: 'Redirecting Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'Seeing your ally\'s attack about to go astray, you fire your weapon to right its course. Discharge your firearm and roll a d20. Your ally uses this roll instead of their own, and the attack ignores bonuses the target would gain against the attack from lesser or standard cover.',
    implemented: 'full',
    traits: ['Fortune', 'Gunslinger'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An ally misses with a ranged attack that uses a thrown weapon or ammunition. The ally must be willing, you must see the target, and the target must be within your weapon\'s first range increment. Requirements: You\'re wielding a loaded firearm or crossbow.',
  },
  {
    id: 'gunslinger-trick-shot',
    name: 'Trick Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You shoot not at your foe but at an object nearby. Make a Strike with your firearm against an AC equal to an easy DC for your level. On a success, instead of hitting your foe, your attack hits an object behind or to the side of your target, creating one of the following effects. Dislodge Object: Your attack knocks an unattended object of no more than 2 Bulk out of position, moving it up to 10 feet in a direction of your choice. Explosive Barrel: The object explodes in a 20-foot burst; creatures take 6d6 damage with a basic Reflex save against your class DC. The damage type is chosen by the GM. Increase the damage by 1d6 for every 2 levels you have above 10th.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding a loaded crossbow or firearm.',
    subChoices: { label: 'Choose trick shot effect', options: [
      { id: 'dislodge-object', name: 'Dislodge Object', description: 'Knock unattended object (≤2 Bulk) up to 10 ft' },
      { id: 'explosive-barrel', name: 'Explosive Barrel', description: '20-ft burst, 6d6 damage (basic Reflex, +1d6 per 2 levels above 10th)' },
    ] },
  },
  {
    id: 'gunslinger-twin-shot-knockdown',
    name: 'Twin Shot Knockdown',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You fire at an enemy while targeting a part of its anatomy that will disrupt its balance. Make two Strikes against the same target, one with each of the required weapons. If both Strikes are successful, the target is also knocked prone.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    mechanics: 'Requirements: You\'re wielding a loaded crossbow or loaded firearm in each hand.',
  },

  // ── Level 12 ─────────────────────────────────────────
  {
    id: 'gunslinger-blood-in-the-air',
    name: 'Blood in the Air',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'Once you\'ve locked on to a target, little can obscure your aim. Make a ranged weapon Strike against the required target. This Strike ignores the target\'s concealed condition and reduces the flat check for the hidden condition from 11 to 5.',
    implemented: 'full',
    traits: ['Concentrate', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: An enemy you\'ve damaged with a ranged weapon during the last minute is concealed or hidden from you.',
  },
  {
    id: 'gunslinger-deadeye',
    name: 'Deadeye',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You relax your eyes, taking in the smallest movements of objects, stirring of grass and leaves, and other signs of the presence of hidden things, granting you the ability to locate invisible creatures. Until the start of your next turn, you can see invisible creatures and objects as silhouettes defined by the movement of air, slight depressions in the ground, and other tells that less-keen eyes would overlook, which makes them merely concealed from you.',
    implemented: 'full',
    traits: ['Concentrate', 'Gunslinger'],
    actionCost: 1,
  },
  {
    id: 'gunslinger-flesh-wound',
    name: 'Flesh Wound',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You fire to ensure that even if your shot doesn\'t land cleanly, it still lands close enough to deal some damage. Make a ranged Strike. It gains the following effect on a failure (though not a critical failure). Failure: Though your attack misses, it still deals one die of damage plus any damage from your weapon specialization class feature. This uses your weapon\'s normal damage die and damage type. This attack doesn\'t add extra damage from any other sources or abilities.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 1,
  },
  {
    id: 'gunslinger-ricochet-shot',
    name: 'Ricochet Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You bounce your shot off a nearby surface to strike your opponent from an unexpected angle. Attempt a Strike with a firearm or crossbow. When determining whether a target has cover from this Strike, you can choose one solid surface within your weapon\'s first range increment to ricochet your shot off of. If you do, you determine the target\'s cover from the point where you ricochet your shot instead of from you.',
    implemented: 'full',
    traits: ['Concentrate', 'Gunslinger'],
    actionCost: 1,
  },
  {
    id: 'gunslinger-shattering-shot',
    name: 'Shattering Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You fling a bomb into the air and then shoot it with your gun before it falls, raining destruction down over a wide area. If necessary, you Interact to draw the bomb and regrip your weapon. You throw your bomb to the corner of a square within your firearm\'s first range increment and shoot it with your firearm. All creatures in a 15-foot burst of the bomb take the bomb\'s normal damage with a basic Reflex save against your class DC. They don\'t take any splash or persistent damage the bomb would deal normally.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding a loaded firearm or loaded crossbow and are wearing or holding an alchemical bomb.',
  },
  {
    id: 'gunslinger-shooters-camouflage',
    name: 'Shooter\'s Camouflage',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You specialize in blending into a particular type of environment, able to disappear after taking your shot. Choose either natural or urban terrain. In the chosen terrain, you can Hide and Sneak even without cover or being concealed.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Master in Stealth'],
    subChoices: { label: 'Choose terrain type', options: [
      { id: 'natural', name: 'Natural Terrain', description: 'Hide and Sneak without cover in natural environments' },
      { id: 'urban', name: 'Urban Terrain', description: 'Hide and Sneak without cover in urban environments' },
    ] },
  },
  {
    id: 'gunslinger-unshakable-grit',
    name: 'Unshakable Grit',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You\'ve become hardened by conflict after everything you\'ve faced, and you possess a certain intractable stubbornness. If the reroll granted to you by your Grit and Tenacity reaction is a success, you get a critical success instead; if it\'s a critical failure, you get a failure instead.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Grit and Tenacity'],
  },

  // ── Level 14 ─────────────────────────────────────────
  {
    id: 'gunslinger-blast-tackle',
    name: 'Blast Tackle',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'You throw yourself at an enemy, bracing your weapon against it and pulling it close before releasing a destructive shot. Attempt to Grapple; if you\'re wielding your weapon in both hands, you Release one hand to do so. If your Grapple succeeds, you can immediately Strike the target of the Grapple with the required weapon, even if it\'s a two-handed weapon you\'re holding in one hand. This Strike deals an additional 3d6 precision damage. As long as the creature remains grabbed or restrained, you can use just one hand to reload the weapon and Strike that creature with it.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 2,
    prerequisites: ['Way of the Vanguard'],
    mechanics: 'Requirements: You\'re wielding a two-handed crossbow or a firearm that has the kickback or scatter trait.',
  },
  {
    id: 'gunslinger-come-at-me',
    name: 'Come at Me!',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'You\'re a legendary duelist, welcoming all challengers, enabling you to challenge many foes even while other challenges are active. There is no longer a limit to the number of Pistolero\'s Challenges you can have in effect at one time.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Pistolero\'s Challenge'],
  },
  {
    id: 'gunslinger-dance-of-thunder',
    name: 'Dance of Thunder',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'Your steps echo with the thunderous retort of exploding black powder as you dance a dance of death. Take any of the following actions you choose in any order: Step, Strike against a target within your firearm\'s first range increment, and Interact to reload. If you attempted a Strike and it succeeded, you can repeat these three actions again in any order. If you attempted a Strike in the second set and succeeded, you can repeat the actions one last time. After using Dance of Thunder, you become fatigued for 1 minute.',
    implemented: 'full',
    traits: ['Concentrate', 'Gunslinger'],
    actionCost: 3,
    mechanics: 'Frequency: Once per minute. Requirements: You\'re wielding a loaded firearm or crossbow and are not fatigued. Up to 3 rounds of Step/Strike/Reload on consecutive hits.',
  },
  {
    id: 'gunslinger-disruptive-blur',
    name: 'Disruptive Blur',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'You use cacophonous blasts from your gun or distracting shots from your crossbow to cause momentary diversions, letting you move about the battlefield with impunity. After you make a Strike with a firearm or crossbow, creatures can\'t take reactions that would be triggered by your movement for the rest of your turn.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Way of the Drifter'],
  },
  {
    id: 'gunslinger-headshot',
    name: 'Headshot',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'You attempt to finish your target with a final, well-placed shot. Make a crossbow or firearm Strike. If you\'ve damaged the target within the last minute with the same weapon and you get a critical success on your attack roll, the target must succeed at a Fortitude save against your class DC or die; this is a death and incapacitation effect. A creature that survives is temporarily immune for 1 day. Creatures with no head (such as dullahans or oozes) are immune to this ability, and creatures with redundant heads (such as ettins) might survive the destruction of a head.',
    implemented: 'full',
    traits: ['Concentrate', 'Gunslinger'],
    actionCost: 2,
    prerequisites: ['Way of the Sniper'],
    mechanics: 'Requirements: You\'re wielding a loaded firearm or crossbow. Death + Incapacitation effect on critical hit.',
  },
  {
    id: 'gunslinger-showstopper',
    name: 'Showstopper',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'Your twirling weapons create a grand distraction that\'s difficult to look away from. When using Pistol Twirl to Feint, you can target all enemies within your weapon\'s first range increment who you can perceive and who can see you. You roll one Deception check and compare it against each target\'s Perception DC.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Pistol Twirl', 'Master in Deception'],
  },
  {
    id: 'gunslinger-triggerbrand-blitz',
    name: 'Triggerbrand Blitz',
    source: 'Impossible Lands',
    category: 'class',
    level: 14,
    description: 'You dance through your foes, stabbing and shooting. You Stride, making up to three Strikes with your combination weapon at any point during your movement, each against a different target. You can make any combination of melee and ranged attacks without needing to change modes to do so, though typically you can\'t make more than one ranged attack because of the need to reload. This counts as three attacks toward your multiple attack penalty, but you don\'t apply the penalty until after making all three attacks. After using Triggerbrand Blitz, you become fatigued for 1 minute.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 3,
    prerequisites: ['Way of the Triggerbrand'],
    mechanics: 'Frequency: Once per minute. Requirements: You\'re wielding a combination weapon.',
  },
  {
    id: 'gunslinger-two-weapon-fusillade',
    name: 'Two-Weapon Fusillade',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'You attack with both your weapons in a furious barrage. Strike twice, once with each weapon.',
    implemented: 'full',
    traits: ['Flourish', 'Gunslinger'],
    actionCost: 1,
    mechanics: 'Requirements: You\'re wielding two weapons, each in a different hand. At least one must be a loaded firearm or loaded crossbow.',
  },

  // ── Level 16 ─────────────────────────────────────────
  {
    id: 'gunslinger-fatal-bullet',
    name: 'Fatal Bullet',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'You\'re especially talented at striking your enemies in their most vulnerable areas. When you critically hit with a fatal firearm, you deal an additional die of the appropriate size and damage type for the fatal trait after doubling the weapon\'s damage. For example, after getting a critical hit with a fatal d12 weapon, you add an additional 1d12 damage to the attack after doubling its damage.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
  {
    id: 'gunslinger-hair-trigger',
    name: 'Hair Trigger',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'No one can react faster than you can pull your trigger. When using your initial deed, instead of Interacting to draw a weapon, you can Strike with a firearm or crossbow you\'re already wielding. If this Strike hits, the target is also off-guard until the end of your first turn of the encounter. Special: If your initial deed allows you to Interact to draw a weapon more than once, this feat allows you to replace one of these Interact actions and use the other one to draw a weapon. You can\'t replace both Interact actions with Strikes, but you can draw a loaded firearm or crossbow with one of the actions and immediately shoot it with the other.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Initial deed that allows you to Interact to draw a weapon'],
  },
  {
    id: 'gunslinger-instant-return',
    name: 'Instant Return',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'With a single fluid gesture, you catch a projectile out of the air, load it in your weapon, and shoot it back at the attacker. Interact to load the projectile into your weapon, then make a Strike with the required weapon against the triggering opponent. Since you\'re using the foe\'s ammunition, this Strike applies any special effects that ammunition would have (for instance, if it was explosive ammunition, it would explode in a burst of fire if your Strike hits).',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An enemy misses you with a ranged attack using appropriate ammunition. Requirements: You\'re wielding an unloaded firearm or crossbow.',
  },
  {
    id: 'gunslinger-ricochet-master',
    name: 'Ricochet Master',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'You have an eye for angles and can find shots that others believe are impossible. When using Ricochet Shot, you can bounce your bullet off up to two solid surfaces within your weapon\'s first range increment instead of just one. In addition, a creature is off-guard the first time you attack it with a Ricochet Shot during an encounter.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Ricochet Shot'],
  },

  // ── Level 18 ─────────────────────────────────────────
  {
    id: 'gunslinger-final-shot',
    name: 'Final Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'You jam a triple charge of black powder into your weapon to unleash a devastating but risky and inaccurate attack. Interact to reload, expending three doses of black powder in addition to your normal black powder or ammunition, then Strike with your firearm against a creature within the weapon\'s first range increment. If you roll a success, the attack is instead a critical success, but if you roll a failure, the weapon misfires. Regardless of your roll, after the attack you\'re off-guard until the start of your next turn and stunned 1.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 3,
    mechanics: 'Requirements: You\'re wielding an unloaded firearm. Triple charge: success -> crit success, failure -> misfire. Off-guard + stunned 1 after.',
  },
  {
    id: 'gunslinger-piercing-critical',
    name: 'Piercing Critical',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'Your attacks with your preferred weapons deal especially devastating wounds. When you Strike with a firearm or crossbow for which you have legendary proficiency, you critically succeed if you roll a 19 on the die, as long as that result is a success.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
  {
    id: 'gunslinger-reach-for-the-stars',
    name: 'Reach for the Stars',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'The sky\'s the limit, as long as you\'ve got enough black powder. When you use Black Powder Boost, you can expend additional black powder or ammunition to boost yourself farther. For each dose of black powder or piece of firearm ammunition you spend in addition to your shot, you add another 10 feet to the height or distance of your Leap, to a maximum of 5 boosts (a +50-foot status bonus). You must be wearing a dose of black powder or piece of ammunition, or have it in hand, to detonate it for a boost. You can choose at which points in your Leap you detonate each boost, allowing you to change direction each time. You must then move in a straight line until you boost again or end your Leap.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Black Powder Boost'],
  },
  {
    id: 'gunslinger-unerring-shot',
    name: 'Unerring Shot',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'Your senses are finely tuned to the slightest variations in the air, so much that you can place your shot exactly where you intend to aim it from any range possible with your weapon. When attacking with a ranged weapon in which you have master or greater proficiency, ignore the penalty from its range increment. The weapon\'s maximum range is unchanged. In addition, if your target has cover against your attack with such a weapon, it doesn\'t gain the bonus to AC if it has lesser cover, gets only the bonus of lesser cover if it has standard cover, or gains only the bonus of standard cover if it has greater cover.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },

  // ── Level 20 ─────────────────────────────────────────
  {
    id: 'gunslinger-perfect-readiness',
    name: 'Perfect Readiness',
    source: 'Guns & Gears',
    category: 'class',
    level: 20,
    description: 'You prepare to fire with an instinctive speed and muscle memory that go beyond your conscious thoughts. You\'re permanently quickened. You can use your extra action only to Step or Interact to reload.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
  {
    id: 'gunslinger-ricochet-legend',
    name: 'Ricochet Legend',
    source: 'Guns & Gears',
    category: 'class',
    level: 20,
    description: 'The more obstacles between you and your target, the deadlier your shots become, as you ricochet off multiple surfaces to hit them. When using Ricochet Shot, your shot can bounce off of any surface within your weapon\'s first three range increments and the target can\'t benefit from cover unless they have total cover on all sides. In addition, a creature must attempt a Will save against your class DC the first time in an encounter you attack it with a Ricochet Shot. If it fails, it\'s stunned 2 and is unable to determine where your shot originated.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
    prerequisites: ['Ricochet Master'],
  },
  {
    id: 'gunslinger-slingers-reflexes',
    name: 'Slinger\'s Reflexes',
    source: 'Guns & Gears',
    category: 'class',
    level: 20,
    description: 'Your ability to react to unexpected circumstances is preternaturally sharp. At the start of each creature\'s turn, you gain an additional reaction you can use on only that turn to use a gunslinger reaction.',
    implemented: 'full',
    traits: ['Gunslinger'],
    actionCost: 'passive',
  },
];
