/**
 * Investigator Class Features & Feats — PF2e Remastered (Player Core 2)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=13 (internal ID 59)
 *
 * Key Attribute: INT | HP: 8 + CON
 * Perception: Expert → Master (L7, Vigilant Senses) → Legendary (L13, Incredible Senses)
 * Fort: Trained → Expert (L9, Fortitude Expertise)
 * Reflex: Expert → Master (L15, Savvy Reflexes, success→crit)
 * Will: Expert → Master (L11, Dogged Will, success→crit) → Legendary (L17, Greater Dogged Will, crit fail→fail)
 * Weapons: Trained simple+martial+unarmed → Expert (L5) → Master (L13)
 * Armor: Light trained + unarmored → Expert (L13) → Master (L19)
 * Class DC: Trained → Expert (L9) → Master (L19)
 * Skills: Society + methodology skill + 4 + INT
 * Strategic Strike: 1d6 (L1) → 2d6 (L5) → 3d6 (L9) → 4d6 (L13) → 5d6 (L17)
 *
 * Methodologies: Alchemical Sciences, Empiricism, Esoterica (Divine Mysteries),
 *   Forensic Medicine, Interrogation
 *
 * Class features: 21 (L1–L19) — 19 inline + 2 createClassFeature
 * Class feats: 56 (L1–L20)
 */

import type { FeatEntry } from './featTypes';
import { SKILL_OPTIONS } from './subChoiceOptions';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
  GREATER_WEAPON_SPECIALIZATION,
} from './sharedFeats';

// ── Investigator Class Features ──────────────────────────

export const INVESTIGATOR_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'investigator-on-the-case',
    name: 'On the Case',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 1,
    description: 'As an investigator, you think of your adventures as cases waiting to be solved. You gain one activity and one reaction you can use to investigate cases: Pursue a Lead and Clue In.\n\nPursue a Lead [Concentrate] [Exploration] [Investigator]: You name one detail you\'ve identified that you think is part of a larger mystery, then spend 1 minute examining it. After the minute passes, the GM either confirms there\'s a larger mystery or tells you there\'s nothing more to learn. If there is a larger mystery, you can\'t Pursue a Lead again for 10 minutes, but you can open an investigation by defining the question at its heart. Investigation Bonus: Whenever you attempt a Perception check or skill check to attempt to get closer to answering the question of an active investigation, you gain a +1 circumstance bonus. You can maintain two active investigations at a time. If you answer the question, the GM tells you, and you keep the bonus until you close the investigation.\n\nClue In [Reaction] [Concentrate] [Investigator]: Frequency once per 10 minutes. Trigger: Another creature attempts a check that could help get you closer to answering the question at the heart of one of your active investigations. You share information with the triggering creature. They gain a circumstance bonus to their check equal to your investigation bonus from Pursue a Lead.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Pursue a Lead: 1-minute exploration activity, +1 circumstance to investigation checks, 2 active investigations max. Clue In: reaction 1/10 min, share investigation bonus with ally.',
  },
  {
    id: 'investigator-devise-a-stratagem',
    name: 'Devise a Stratagem',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 1,
    description: 'You assess a foe\'s weaknesses in combat and use them to formulate a plan of attack. Frequency: once per round. Choose a creature you can see. You can Devise a Stratagem as a free action if you\'re aware that creature could help answer the question at the heart of one of your active investigations. Roll a d20, then decide on an attack stratagem or skill stratagem.\n\nAttack Stratagem: If you Strike the chosen creature before the start of your next turn, you must use the result of the d20 roll for your Strike\'s attack roll instead of rolling. You make this substitution only for the first Strike you make against the creature this round. When you make this substitution, you can add your Intelligence modifier to your attack roll instead of your Strength or Dexterity modifier, provided you Strike with an agile or finesse melee weapon, an agile or finesse unarmed attack, a ranged weapon (which must be agile or finesse if it\'s a melee weapon with the thrown trait), or a sap.\n\nSkill Stratagem: You can\'t attempt to Strike the target until the start of your next turn. You gain a +1 circumstance bonus to your next Intelligence-, Wisdom-, or Charisma-based skill check or Perception check involving the target before the start of your next turn. If you would gain your Pursue a Lead investigation bonus to such a check, that bonus increases by 1 instead.',
    implemented: 'full',
    traits: ['Investigator', 'Concentrate', 'Fortune'],
    actionCost: 1,
    mechanics: '1/round. Free action if target is tied to active investigation. Roll d20, choose attack or skill stratagem. Attack: substitute d20 for attack roll, use INT instead of STR/DEX with eligible weapons. Skill: +1 circumstance to next INT/WIS/CHA check vs target.',
  },
  {
    id: 'investigator-methodology',
    name: 'Methodology',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 1,
    description: 'Your studies have made you savvy in a broad spectrum of areas, but one particular investigative process drew your intense—even obsessive—interest. Choose a methodology: Alchemical Sciences (Crafting, Alchemical Crafting, versatile vials, Quick Tincture), Empiricism (INT skill, That\'s Odd feat, Expeditious Inspection free action), Esoterica (Occultism or Religion, Quick Identification, two cantrips from divine and occult lists), Forensic Medicine (Medicine, Forensic Acumen and Battle Medicine feats with enhanced healing), or Interrogation (Diplomacy, No Cause for Alarm feat, Pursue a Lead during Make an Impression, Pointed Question action).',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Choose methodology at L1. Determines bonus skill training, special abilities, and method-specific feats.',
    subChoices: { label: 'Choose a methodology', options: [
      { id: 'alchemical-sciences', name: 'Alchemical Sciences', description: 'Crafting, Alchemical Crafting, versatile vials, Quick Tincture' },
      { id: 'empiricism', name: 'Empiricism', description: 'INT skill, That\'s Odd feat, Expeditious Inspection' },
      { id: 'esoterica', name: 'Esoterica', description: 'Occultism/Religion, Quick Identification, two divine/occult cantrips' },
      { id: 'forensic-medicine', name: 'Forensic Medicine', description: 'Medicine, Forensic Acumen, Battle Medicine with enhanced healing' },
      { id: 'interrogation', name: 'Interrogation', description: 'Diplomacy, No Cause for Alarm, Pointed Question action' },
    ] },
  },
  {
    id: 'investigator-strategic-strike',
    name: 'Strategic Strike',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 1,
    description: 'When you strike carefully and with forethought, you deal a telling blow. When making a Strike that adds your Intelligence modifier to your attack roll due to Devising a Stratagem, you deal an additional 1d6 precision damage. As your investigator level increases, so too does the deadliness of your strategic strike. Increase the number of dice by one at 5th, 9th, 13th, and 17th levels.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Precision damage on Stratagem Strikes: 1d6 (L1), 2d6 (L5), 3d6 (L9), 4d6 (L13), 5d6 (L17).',
  },
  // ── Level 3 ──────────────────────────────────────────
  {
    id: 'investigator-keen-recollection',
    name: 'Keen Recollection',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 3,
    description: 'You can recall pertinent facts on topics that aren\'t your specialty. Your proficiency bonus to untrained skill checks to Recall Knowledge is equal to your level instead of +0.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Untrained Recall Knowledge uses full level as proficiency bonus instead of +0.',
  },
  {
    id: 'investigator-skillful-lessons',
    name: 'Skillful Lessons',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 3,
    description: 'At 3rd level and every odd-numbered level thereafter, you gain a skill feat. This feat must be for an Intelligence-, Wisdom-, or Charisma-based skill, or for the skill you gained from your methodology.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Extra skill feat at L3, L5, L7, L9, L11, L13, L15, L17, L19. Must be INT/WIS/CHA-based or methodology skill.',
  },
  // ── Level 5 ──────────────────────────────────────────
  {
    id: 'investigator-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 5,
    description: 'You\'ve dedicated yourself to learning the intricacies of your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  // ── Level 7 ──────────────────────────────────────────
  {
    id: 'investigator-vigilant-senses',
    name: 'Vigilant Senses',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 7,
    description: 'Through your adventures, you\'ve developed keen awareness and attention to detail. Your proficiency rank in Perception increases to master.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Investigator', 7),
  // ── Level 9 ──────────────────────────────────────────
  {
    id: 'investigator-fortitude-expertise',
    name: 'Fortitude Expertise',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 9,
    description: 'Your physique has grown hardy in your adventures. Your proficiency rank for Fortitude saves increases to expert.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  {
    id: 'investigator-investigator-expertise',
    name: 'Investigator Expertise',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 9,
    description: 'You\'ve refined your investigative techniques to an exceptional degree. Your circumstance bonus from Pursue a Lead increases to +2. Your proficiency rank for your investigator class DC increases to expert.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Pursue a Lead bonus increases to +2. Class DC proficiency → expert.',
  },
  // ── Level 11 ─────────────────────────────────────────
  {
    id: 'investigator-deductive-improvisation',
    name: 'Deductive Improvisation',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 11,
    description: 'You use your skills at deduction to perform whatever task is necessary to solve the case. You can attempt any check that requires you to be trained in a skill, even if you\'re untrained in it; you can attempt any check that requires you to have expert proficiency in a skill so long as you\'re trained in it; and you can attempt any check that requires you to have master proficiency in a skill as long as you have expert proficiency in it.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Reduce skill proficiency prerequisites by one step for skill checks.',
  },
  {
    id: 'investigator-dogged-will',
    name: 'Dogged Will',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 11,
    description: 'In your pursuit of truth and knowledge, you won\'t be dissuaded. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Will → master. Success on Will save → critical success.',
  },
  // ── Level 13 ─────────────────────────────────────────
  {
    id: 'investigator-incredible-senses',
    name: 'Incredible Senses',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 13,
    description: 'You notice things that are almost impossible for an ordinary person to detect. Your proficiency rank for Perception increases to legendary.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  {
    id: 'investigator-light-armor-expertise',
    name: 'Light Armor Expertise',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned how to dodge while wearing light or no armor. Your proficiency ranks for light armor and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  {
    id: 'investigator-weapon-mastery',
    name: 'Weapon Mastery',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 13,
    description: 'You fully understand your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  // ── Level 15 ─────────────────────────────────────────
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Investigator', 15),
  {
    id: 'investigator-savvy-reflexes',
    name: 'Savvy Reflexes',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 15,
    description: 'With an eye for incoming danger, you masterfully keep yourself out of harm\'s way. Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Reflex → master. Success on Reflex save → critical success.',
  },
  // ── Level 17 ─────────────────────────────────────────
  {
    id: 'investigator-greater-dogged-will',
    name: 'Greater Dogged Will',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 17,
    description: 'Your willpower becomes truly unbreakable. Your proficiency rank for Will saves increases to legendary. When you roll a success on a Will save, you get a critical success. When you roll a critical failure on a Will save, you get a failure instead. When you fail a Will save against a damaging effect, you take half damage.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Will → legendary. Success → crit success. Crit failure → failure. Failed Will vs damage → half damage.',
  },
  // ── Level 19 ─────────────────────────────────────────
  {
    id: 'investigator-light-armor-mastery',
    name: 'Light Armor Mastery',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 19,
    description: 'Your skill with light armor improves, increasing your ability to dodge blows. Your proficiency ranks for light armor and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  {
    id: 'investigator-master-detective',
    name: 'Master Detective',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 19,
    description: 'As a master detective, you can solve any case and find all the clues available. Your reputation precedes you, and even the most skilled criminals and deceivers fear you. Your proficiency rank for your investigator class DC increases to master. In addition, if you enter a new location that includes another clue toward answering the question at the heart of one of your active investigations, the GM informs you of the existence of the clue and its type: an object, person, spell effect, or the like. When you find the clue, the GM informs you that you\'ve done so. If there is more than one clue in the location, the GM chooses one to inform you about. When you find any of the clues in that location, the GM informs you that you\'ve done so, even if it wasn\'t the clue they\'d chosen or there are other clues you haven\'t found.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Class DC → master. GM reveals clue existence and type when entering locations relevant to active investigations.',
  },
];

// ── Investigator Class Feats ─────────────────────────────

export const INVESTIGATOR_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 Feats ────────────────────────────────────
  {
    id: 'investigator-eliminate-red-herrings',
    name: 'Eliminate Red Herrings',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You have a keen sense for avoiding spurious lines of inquiry. When you roll a critical failure on a skill check to Recall Knowledge related to a question about one of your active investigations, you get a failure instead.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
  },
  {
    id: 'investigator-flexible-studies',
    name: 'Flexible Studies',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You\'ve collected a cross-section of information on various disciplines you can refer to when preparing for various tasks. During your daily preparations, you can cram on a certain subject to become temporarily trained in one skill of your choice. This proficiency lasts until you prepare again. As this proficiency is temporary, you can\'t use it as a prerequisite for a permanent character option like a skill increase or a feat.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'During daily preparations, become temporarily trained in one skill of your choice.',
    subChoices: { label: 'Choose skill to train', options: SKILL_OPTIONS },
  },
  {
    id: 'investigator-known-weaknesses',
    name: 'Known Weaknesses',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'Whenever you Devise a Stratagem, you can also attempt a check to Recall Knowledge as part of that action before rolling the d20. If you critically succeed at the Recall Knowledge check, you notice a weakness and can convey the information to allies to grant each of them a +1 circumstance bonus to their next attack roll against the subject, as long as their attack is made before the beginning of your next turn. If you choose an attack stratagem, this bonus applies to that attack roll too.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Recall Knowledge as part of Devise a Stratagem. Crit success: +1 circumstance to allies\' attacks vs target until next turn.',
  },
  {
    id: 'investigator-takedown-expert',
    name: 'Takedown Expert',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You\'ve mastered combat practices that let you get up close and bring down perpetrators alive. You can use your Intelligence modifier on attack rolls for an attack stratagem if you\'re using a weapon of the club group in one hand (like a club or staff), in addition to the usual weapons, and those Strikes qualify for your strategic strike. Additionally, you can make any of your Strikes nonlethal without taking the normal \u20132 penalty.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Club group weapons qualify for INT-based attack stratagems. All Strikes can be nonlethal without penalty.',
  },
  {
    id: 'investigator-thats-odd',
    name: "That's Odd",
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'When you enter a new location, such as a room or corridor, you immediately notice one thing out of the ordinary. The GM determines what it is, or whether there\'s nothing reasonable to pick up, skipping obvious clues that can be easily noticed without a check or specifically looking for them. You learn only that an area or object is suspicious, but not why it\'s suspicious. For example, if you entered a study with a large bloodstain on the ground, the bloodstain is so obviously suspicious it\'s evident to you already, so the GM might note that there\'s something suspicious about the desk drawer instead. You would then need to investigate the drawer further to find out what specifically is out of the ordinary. If you wish, you can Pursue a Lead concerning this detail even if you have Pursued a Lead less than 10 minutes ago. That\'s Odd doesn\'t reveal whether creatures are suspicious. You don\'t typically get any benefit when you leave and come back to a place, though if a major change has happened there and time has passed, the GM might determine that you do.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Auto-notice one out-of-ordinary detail when entering a new location. Can Pursue a Lead on it immediately.',
  },
  {
    id: 'investigator-trap-finder',
    name: 'Trap Finder',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You have an intuitive sense that alerts you to the presence of traps. You gain a +1 circumstance bonus to Perception checks to find traps, to AC against attacks made by traps, and to saves against traps. Even if you aren\'t Searching, you get a check to find traps that normally require you to be Searching. You still need to meet any other requirements to find the trap. You can disable traps that require a proficiency rank of master in Thievery. If you have master proficiency in Thievery, you can disable traps that require a proficiency rank of legendary instead, and your circumstance bonuses against traps increase to +2.',
    implemented: 'full',
    traits: ['Investigator', 'Rogue'],
    actionCost: 'passive',
    mechanics: '+1 circumstance to find traps, AC vs traps, saves vs traps. Auto-check even without Searching. Can disable master-rank traps (legendary if master Thievery; bonuses increase to +2).',
  },
  {
    id: 'investigator-undead-spotter',
    name: 'Undead Spotter',
    source: 'Wake the Dead #4',
    category: 'class',
    level: 1,
    description: 'Your studies of the undead have taught you telltale signs of a disguised undead creature. When you Pursue a Lead that involves a corpse or creature within your reach, you can touch that corpse or creature to immediately determine if it is undead. You gain a +1 circumstance bonus to Recall Knowledge checks about undead creatures and to determine if a creature is undead.',
    implemented: 'full',
    traits: ['Uncommon', 'Investigator'],
    actionCost: 'passive',
    mechanics: 'Touch to detect undead when Pursuing a Lead. +1 circumstance to Recall Knowledge about undead.',
  },
  {
    id: 'investigator-underworld-investigator',
    name: 'Underworld Investigator',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'Your work as an investigator makes you familiar with the criminal element. You might be a criminal yourself, or you might have gained an understanding of how they operate from the outside. You become trained in Underworld Lore, and you gain your Pursue a Lead investigation bonus to Thievery checks to investigate a case (such as checks to Steal a clue from a suspect or Pick a Lock to open a safe with damning documents).',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Trained in Underworld Lore. Pursue a Lead bonus applies to Thievery checks for investigations.',
  },
  // ── Level 2 Feats ────────────────────────────────────
  {
    id: 'investigator-athletic-strategist',
    name: 'Athletic Strategist',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'You know how to calculatedly manipulate joints and body weight. In addition to using an attack stratagem\'s roll substitution for a Strike, you can use it to modify a Disarm, Grapple, Reposition, Shove, or Trip attempt, substituting your Devise a Stratagem roll for the Athletics check. You must apply the substitution to the first eligible attack you make, whether it\'s a Strike or one of the Athletics actions. You can also use your Intelligence modifier instead of Strength for the Athletics check when you substitute your Devise a Stratagem roll, unless you\'re using a weapon for the maneuver and the weapon doesn\'t fit the restrictions for using Intelligence with a stratagem.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['trained in Athletics'],
    mechanics: 'Devise a Stratagem roll substitutes for Athletics checks (Disarm, Grapple, Reposition, Shove, Trip). Can use INT instead of STR.',
  },
  {
    id: 'investigator-certain-stratagem',
    name: 'Certain Stratagem',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'You know exactly where to strike a foe to target their weak spots. When you make a Strike that you\'re adding your Intelligence modifier to due to Devising a Stratagem and miss, you deal half of your strategic strike damage to the target. This damage type is that of the weapon or unarmed attack you used for the Strike.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'On a miss with a Stratagem Strike, deal half strategic strike damage.',
  },
  {
    id: 'investigator-exploit-blunder',
    name: 'Exploit Blunder',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'By watching your foes closely, you can make the most out of their mistakes. You Step.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature you Devised a Stratagem against on your most recent turn fails or critically fails a Strike against you. You Step.',
  },
  {
    id: 'investigator-person-of-interest',
    name: 'Person of Interest',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'Sometimes, you need to follow the leads as they come in the middle of an investigation. Choose a creature that you can see who isn\'t, to your knowledge, tied to any of your current investigations. For the next minute, you can Devise a Stratagem against that creature as a free action.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 1,
    mechanics: 'Frequency: once per 10 minutes. Choose visible creature not tied to investigations. Devise a Stratagem against it as free action for 1 minute.',
  },
  {
    id: 'investigator-shared-stratagem',
    name: 'Shared Stratagem',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'The plans you make include your allies as well as yourself. When you hit a creature with an attack on which you substituted your attack roll due to Devising a Stratagem, designate one ally. The creature you hit is off-guard to that ally on the next attack that ally makes against that creature before the start of your next turn.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'On Stratagem hit, designate one ally. Target is off-guard to that ally\'s next attack before your next turn.',
  },
  {
    id: 'investigator-solid-lead',
    name: 'Solid Lead',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'Sometimes your case splinters into smaller mysteries, but you never lose sight of the big picture. Once per day when you give up on the subject of a lead due to using Pursue a Lead again, you can designate the lead you stopped pursuing as your solid lead for the day. Even though you stopped following the solid lead, you can change back to your solid lead any number of times by using a single action, which has the concentrate trait. Doing so ends one of your current leads as normal. During your next daily preparations, you can maintain your solid lead or you can remove it; removing it allows you to designate a new solid lead later that day.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: '1/day designate a dropped lead as solid lead. Switch back to it with 1 action (concentrate) any number of times.',
  },
  // ── Level 4 Feats ────────────────────────────────────
  {
    id: 'investigator-alchemical-discoveries',
    name: 'Alchemical Discoveries',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You\'ve devoted extra time in the lab to improve your knowledge of alchemy. You learn the formulas for two alchemical items each time you level up instead of one; these must still be elixirs or tools. The number of versatile vials you can create each day increases by one if you\'re an expert in Crafting, two if you\'re a master, or three if you\'re legendary.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['alchemical sciences methodology'],
    mechanics: '2 formulas per level instead of 1 (elixirs or tools). Extra versatile vials: +1 (expert), +2 (master), +3 (legendary) Crafting.',
  },
  {
    id: 'investigator-detectives-readiness',
    name: "Detective's Readiness",
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'When you\'re on a case, you stay watchful and resolute to avoid tricks your suspect might pull. You gain your investigation bonus from Pursue a Lead on saving throws (and their DCs, as normal) against creatures or effects that are related to the question at the heart of an open investigation, and you can use Clue In to assist an ally\'s saving throw against that creature or effect.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Pursue a Lead bonus applies to saves vs investigation-related creatures/effects. Clue In works on ally saves.',
  },
  {
    id: 'investigator-greenwatch-initiate',
    name: 'Greenwatch Initiate',
    source: 'Impossible Lands',
    category: 'class',
    level: 4,
    description: 'You\'ve received the basic training developed for all Greenwatch recruits. You become an expert in Survival and gain the Experienced Tracker and Survey Wildlife skill feats.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['trained in Survival'],
    mechanics: 'Expert in Survival. Gain Experienced Tracker and Survey Wildlife.',
  },
  {
    id: 'investigator-lie-detector',
    name: 'Lie Detector',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You\'re adept at noticing the tells of a liar—sweat, flushing, a quavering voice, a quickening pulse. You gain a +1 circumstance bonus to Perception checks to Sense Motive and to Perception DCs against attempts to Lie to you. When you determine someone is lying to you, you can use their deceit to your advantage to gain a +1 circumstance bonus to the next Deception, Diplomacy, Intimidation, or Performance check you attempt against that creature within the next minute. If you would gain your Pursue a Lead investigation bonus to any of the above checks, that bonus increases by 1 instead of you gaining the +1 bonus listed.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['empiricism or interrogation methodology'],
    mechanics: '+1 circumstance to Sense Motive and Perception DC vs Lie. When catching a lie, +1 to next social check vs that creature within 1 min.',
  },
  {
    id: 'investigator-ongoing-investigation',
    name: 'Ongoing Investigation',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You\'re always investigating what\'s around you, even as you perform other activities. You can move at full Speed while using the Investigate exploration activity, and you can use another exploration activity while Investigating.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Full Speed while Investigating. Can use another exploration activity simultaneously.',
  },
  {
    id: 'investigator-scalpels-point',
    name: "Scalpel's Point",
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'Your stratagems benefit from your precise knowledge of anatomy. When you critically hit with an attack on which you substituted your attack roll due to Devising a Stratagem, if your attack dealt piercing or slashing damage, you also deal 1d6 persistent bleed damage to your target.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['forensic medicine methodology'],
    mechanics: 'Crit with Stratagem Strike dealing piercing/slashing: +1d6 persistent bleed.',
  },
  {
    id: 'investigator-strategic-assessment',
    name: 'Strategic Assessment',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You learn your foes\' strengths and weaknesses by watching them move. When you hit a creature with a Strike on which you substituted your attack roll due to Devising a Stratagem, the GM chooses one of the following pieces of information about the enemy to tell you: which of the enemy\'s weaknesses is highest, which of the enemy\'s resistances is highest, which of the enemy\'s saving throws is lowest, or one immunity the enemy has. The GM can choose deliberately or at random, but they can\'t choose information that doesn\'t apply (such as choosing an immunity for an enemy that has no immunities). This applies only the first time you hit a given creature.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'On first Stratagem hit vs a creature, GM reveals one stat: highest weakness, highest resistance, lowest save, or an immunity.',
  },
  {
    id: 'investigator-strategic-repose',
    name: 'Strategic Repose',
    source: 'Wake the Dead #4',
    category: 'class',
    level: 4,
    description: 'You\'ve trained extensively in fighting the undead and have learned to infuse a small amount of positive energy into your weapon. When you deal precision damage with strategic strike, you may choose for that damage to be positive damage instead.',
    implemented: 'full',
    traits: ['Uncommon', 'Investigator', 'Positive'],
    actionCost: 'passive',
    mechanics: 'Strategic strike precision damage can be positive damage instead.',
  },
  // ── Level 6 Feats ────────────────────────────────────
  {
    id: 'investigator-connect-the-dots',
    name: 'Connect the Dots',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'Ephemeral connections between people, places, and concepts are invisible to most, but seeing them is your stock and trade. Choose an ally and a non-allied creature. You must be able to see both of them. You briefly study the way they both move and attempt a Perception check against the higher of the non-allied creature\'s Deception DC or Will DC. Both targets are then temporarily immune to Connect the Dots for 10 minutes. Critical Success: You spot a way for your ally to take advantage of the other target\'s flaws and let them know about it. Your ally gains your Pursue a Lead investigation bonus as a circumstance bonus to all its Strikes or skill checks against the creature until the start of your next turn. Success: As critical success, but your ally gains the bonus only for their next Strike or skill check against the creature. Failure: You fail to make a connection. Critical Failure: You misconstrue a vital piece of information, which temporarily disconcerts you. You are stupefied 1 until the end of your next turn.',
    implemented: 'full',
    traits: ['Auditory', 'Concentrate', 'Investigator', 'Linguistic'],
    actionCost: 2,
    mechanics: 'Perception vs higher of Deception DC or Will DC. Crit: ally gets investigation bonus to all Strikes/skills vs target. Success: bonus to next Strike/skill only.',
  },
  {
    id: 'investigator-defy-fey',
    name: 'Defy Fey',
    source: 'Impossible Lands',
    category: 'class',
    level: 6,
    description: 'You are keen to the wiles of the fey and can usually shake off their magic. Whenever you fail, but don\'t critically fail, a save against a spell with a duration of at least 1 round cast by a fey creature, you can attempt a second save against the original DC at the start of your next turn to end any lingering effects the spell might have. This can end persistent damage caused by a spell but can\'t reverse any effects that have been resolved already (such as damage dealt when the spell was cast).',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Greenwatch Initiate'],
    mechanics: 'On failed (not crit failed) save vs fey spell with duration ≥1 round, retry save at start of next turn.',
  },
  {
    id: 'investigator-fey-tracker',
    name: 'Fey Tracker',
    source: 'Impossible Lands',
    category: 'class',
    level: 6,
    description: 'You are exceptionally skilled at noticing the subtle techniques fey use to avoid notice. You gain a +2 circumstance bonus to Survival checks to Track fey creatures, to Perception checks to Seek for hidden fey, and to your Perception DC to resist a fey creature\'s attempt to Create a Diversion.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Greenwatch Initiate'],
    mechanics: '+2 circumstance to Track fey, Seek fey, and Perception DC vs fey Create a Diversion.',
  },
  {
    id: 'investigator-predictive-purchase',
    name: 'Predictive Purchase',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You have just the thing for the situation. You gain the Prescient Planner and Prescient Consumable feats. When using Prescient Planner, you can pull out the item as a 2-action activity to remove your backpack (or a similar container) and draw the item, rather than taking 1 minute.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Gain Prescient Planner and Prescient Consumable. Prescient Planner as 2-action activity instead of 1 minute.',
  },
  {
    id: 'investigator-read-the-dust',
    name: 'Read the Dust',
    source: 'Wake the Dead #4',
    category: 'class',
    level: 6,
    description: 'You watch the creature or hazard as it collapses, careful for any sign it may return. You immediately learn if the creature or hazard has an ability that will restore it, like rejuvenation or a haunt\'s reset. If it can return, you also learn the time span before its return and how to prevent that return in broad terms, such as "lay its body to rest" or "destroy its armor." If this requires any people or objects that aren\'t already present, you also learn the direction towards each missing piece from the dust\'s movement.',
    implemented: 'full',
    traits: ['Uncommon', 'Investigator'],
    actionCost: 'reaction',
    mechanics: 'Trigger: An undead creature is reduced to 0 HP or a haunt is disabled within 60 feet. Learn if it can return, timeframe, and how to prevent it.',
  },
  {
    id: 'investigator-thorough-research',
    name: 'Thorough Research',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You have comprehensive knowledge in your fields of interest. When you succeed at a Recall Knowledge check, you gain additional information or context. When you critically succeed at a check to Recall Knowledge, you get additional information or context or can ask an additional follow-up question (the GM chooses which).',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Success on Recall Knowledge: extra info. Crit success: extra info or additional follow-up question.',
  },
  // ── Level 8 Feats ────────────────────────────────────
  {
    id: 'investigator-blind-fight',
    name: 'Blind-Fight',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'Your battle instincts make you more aware of concealed and invisible opponents. You don\'t need to succeed at a flat check to target concealed creatures. You\'re not off-guard to creatures that are hidden from you (unless you\'re off-guard to them for reasons other than the hidden condition), and you need only a successful DC 5 flat check to target a hidden creature. While you\'re adjacent to an undetected creature of your level or lower, it is instead only hidden from you.',
    implemented: 'full',
    traits: ['Fighter', 'Investigator', 'Ranger', 'Rogue'],
    actionCost: 'passive',
    prerequisites: ['master in Perception'],
    mechanics: 'No flat check vs concealed. Not off-guard vs hidden. DC 5 flat check vs hidden. Adjacent undetected creatures of your level or lower become hidden.',
  },
  {
    id: 'investigator-clue-them-all-in',
    name: 'Clue Them All In',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You can clue in all your allies at once. When you use the Clue In reaction, any of your allies who are attempting the same check to investigate one of your active investigations receive the circumstance bonus from Clue In. If you use this ability during an encounter, they must attempt their check within 1 round of when you Clued them In.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Clue In applies to all allies attempting the same investigation check. In encounters, they must check within 1 round.',
  },
  {
    id: 'investigator-defensive-stratagem',
    name: 'Defensive Stratagem',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'By scrutinizing a foe, you learn how to better avoid its attacks. When you use Devise a Stratagem, you can choose a defensive stratagem instead of an attack or skill stratagem after you roll a d20. Defensive Stratagem: You can\'t attempt to Strike the target until the start of your next turn. You gain a +1 circumstance bonus to all your defenses against effects caused by the target until the start of your next turn.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'New Devise a Stratagem option: defensive stratagem. +1 circumstance to all defenses vs target until next turn.',
  },
  {
    id: 'investigator-greenwatch-veteran',
    name: 'Greenwatch Veteran',
    source: 'Impossible Lands',
    category: 'class',
    level: 8,
    description: 'Your time spent tracking your target allows you to quickly identify its weaknesses and relay them to your allies. Attempt a Recall Knowledge check against the creature you were Tracking. On a success, you always know the creature\'s greatest weakness and highest resistance or immunity, in addition to any other information the check would typically provide. You immediately use a quick series of hand gestures to signal this information to any allies who can see you.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'free',
    mechanics: 'Trigger: Your turn starts and you\'re in combat against a creature you spent at least 10 minutes Tracking. Recall Knowledge; on success, learn greatest weakness and highest resistance/immunity, signal allies.',
  },
  {
    id: 'investigator-unseen-passage',
    name: 'Unseen Passage',
    source: 'Impossible Lands',
    category: 'class',
    level: 8,
    description: 'You have mastered a magical technique for moving through dangerous woodlands unseen. You can cast pass without trace as an innate primal spell heightened to a spell level equal to half your level rounded up.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    mechanics: 'Once per day. Innate primal pass without trace, heightened to half level rounded up.',
  },
  {
    id: 'investigator-whodunnit',
    name: 'Whodunnit?',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You carefully consider your case and narrow down some of the details. When you Pursue a Lead and learn there\'s a larger mystery, you can ask two questions related to your investigation when you open it. The GM must answer truthfully with "yes" or "no," though if the answer would be misleading or have no practical application to your investigation, the GM can answer "immaterial." You can\'t use Whodunnit? more than once for the same lead, even across different days. Your questions must come from the following list, applying to the detail that spurred your investigation: Was this clue left by a [creature trait]? (Choose a creature trait such as humanoid, undead, or dwarf; this trait must be accurate as of the time the clue was left.) Was this clue left within the last hour? Was this clue left within the last day? Was the creature that left this clue in a heightened emotional state when it left the clue? Did anyone attempt to conceal this clue?',
    implemented: 'full',
    traits: ['Uncommon', 'Investigator'],
    actionCost: 'passive',
    mechanics: '1/day. When opening an investigation via Pursue a Lead, ask 2 yes/no questions from a set list about the clue.',
  },
  // ── Level 10 Feats ───────────────────────────────────
  {
    id: 'investigator-greenwatcher',
    name: 'Greenwatcher',
    source: 'Impossible Lands',
    category: 'class',
    level: 10,
    description: 'Your experience fighting against and alongside fey creatures is nearly unrivaled. Any weapon you wield or unarmed attack you make against a fey creature is treated as cold iron. Whenever you critically fail a save against a spell cast by a fey creature, it\'s instead treated as a normal failure. Whenever you critically succeed on a Strike against a fey creature, the target is immediately subject to the effects of a faerie fire spell. For the purposes of counteracting this effect, it\'s an innate 2nd-level primal spell.',
    implemented: 'full',
    traits: ['Rare', 'Gunslinger', 'Investigator', 'Ranger'],
    actionCost: 'passive',
    prerequisites: ['Defy Fey'],
    mechanics: 'Weapons count as cold iron vs fey. Crit fail saves vs fey spells → failure. Crit success Strikes vs fey → faerie fire (2nd-level primal).',
  },
  {
    id: 'investigator-just-one-more-thing',
    name: 'Just One More Thing',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'After your attempt to influence someone goes poorly, you add another bit of information or ask a pointed question, possibly salvaging your previous attempt. Reroll the failed check and use the new result. If the target of the failed check is involved with one of your active investigations, double your investigation bonus from Pursue a Lead on the rerolled check. That creature is temporarily immune to Just One More Thing for 1 day. You can also use this action if you failed, but didn\'t critically fail, at a check to Lie, Gather Information, Make an Impression, or Coerce. In this case, rather than spending 1 action, adding Just One More Thing takes you half the amount of time you initially spent on the check, to a minimum of 1 more round.',
    implemented: 'full',
    traits: ['Fortune', 'Investigator'],
    actionCost: 1,
    mechanics: 'Requirements: Most recent action was Demoralize, Feint, or Request and you failed (not crit fail). Reroll the failed check. Double investigation bonus on reroll if target is in active investigation. Also works on failed Lie, Gather Information, Make an Impression, or Coerce (takes half the original time). Target immune 1 day.',
  },
  {
    id: 'investigator-ongoing-strategy',
    name: 'Ongoing Strategy',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You\'re constantly studying small aspects of everyone\'s movements, even if you don\'t have a stratagem in place ahead of time. On any Strike for which you didn\'t Devise a Stratagem, you still deal precision damage equal to your number of strategic strike damage dice so long as the weapon or unarmed attack you used is one that would have let you use your Intelligence modifier had you Devised a Stratagem.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['strategic strike'],
    mechanics: 'Strikes without Devise a Stratagem still deal flat precision damage equal to number of strategic strike dice (e.g., 3 at L9).',
  },
  {
    id: 'investigator-suspect-of-opportunity',
    name: 'Suspect of Opportunity',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'Sometimes something intrudes upon your case unexpectedly, such as an ambush sent to bring your investigation to a close. You use Person of Interest against the triggering creature. This doesn\'t allow you to use Person of Interest more frequently than normal.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'reaction',
    prerequisites: ['Person of Interest'],
    mechanics: 'Trigger: A creature not tied to your active investigations takes a hostile action against you in combat. Use Person of Interest against it (doesn\'t bypass frequency).',
  },
  // ── Level 12 Feats ───────────────────────────────────
  {
    id: 'investigator-empiricists-eye',
    name: "Empiricist's Eye",
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'Your ongoing observation of allies and their interactions with the enemy benefits the whole group. When you Point Out a creature, the indication doesn\'t have the auditory trait. In addition, any creature you Point Out is also off-guard to your allies, not just you, until the start of your next turn. Special: If you also have Blind-Fight, your allies gain the benefit of your Blind-Fight against any creature that\'s off-guard to them from this feat.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['empiricism methodology'],
    mechanics: 'Point Out loses auditory trait. Pointed Out creatures are off-guard to your allies until next turn. With Blind-Fight: allies gain Blind-Fight benefits vs those creatures.',
  },
  {
    id: 'investigator-foresee-danger',
    name: 'Foresee Danger',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You perceive every possible way your foe\'s attack could land and attempt to avoid them all. The triggering attack targets your Perception DC instead of your AC. Though this appearance of Perception DC is higher than your AC, this feat doesn\'t remove any conditions or other effects that are reducing your AC; your Perception DC might still be lower than your AC with all penalties taken into account.',
    implemented: 'full',
    traits: ['Concentrate', 'Investigator'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature targets you with an attack and you can see the attacker. The attack targets your Perception DC instead of your AC.',
  },
  {
    id: 'investigator-just-as-planned',
    name: 'Just As Planned',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'In the blink of an eye, you calculate your enemy\'s movements and know exactly where to aim your next blow. You always have contingencies in place. If your next action is to Devise a Stratagem, roll your d20 twice and use the higher result.',
    implemented: 'full',
    traits: ['Fortune', 'Investigator'],
    actionCost: 'free',
    mechanics: 'Frequency: once per hour. If next action is Devise a Stratagem, roll d20 twice and use higher.',
  },
  {
    id: 'investigator-make-em-sweat',
    name: "Make 'em Sweat",
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'Your line of questioning lets a suspect know you can see right through them, shaking them to the core. Physical and psychological intimidation are your trademark techniques during questioning. When you succeed at your Pointed Question, the target is also frightened 1, or frightened 2 on a critical success. This is an emotion and fear effect.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['interrogation methodology'],
    mechanics: 'Pointed Question success: target also frightened 1. Crit success: frightened 2. Emotion and fear effect.',
  },
  {
    id: 'investigator-reason-rapidly',
    name: 'Reason Rapidly',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'Your mind works through clues at an unbelievable speed. You instantly use up to five Recall Knowledge actions. You can\'t use any special abilities that would be triggered or extendable through the use of the applicable Recall Knowledge skill or that normally take additional actions to complete, such as the ones provided by Thorough Research.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 1,
    mechanics: 'Instantly perform up to 5 Recall Knowledge checks. Cannot trigger special abilities from those checks (e.g., Thorough Research).',
  },
  {
    id: 'investigator-share-tincture',
    name: 'Share Tincture',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You brew up a quick alchemical tincture to share with a friend in need. You use Quick Tincture, and the created item remains potent until the start of your next turn. You then Interact to pass the item to an adjacent ally, at which point the item becomes a normal infused item that lasts until the start of your next turn. If your ally doesn\'t use the item before then, it\'s wasted. If you throw the item to the ally rather than handing it to the ally, the throw automatically succeeds with no check. You must have a versatile vial to use this ability.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 1,
    prerequisites: ['alchemical sciences methodology'],
    mechanics: 'Use Quick Tincture, item lasts until start of next turn. Pass to adjacent ally (or throw automatically). Costs 1 versatile vial.',
  },
  {
    id: 'investigator-surgical-shock',
    name: 'Surgical Shock',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'With a few well-placed jabs with your fist or weapon, you render your opponent disoriented or ungainly. Make a Medicine check against the foe\'s Fortitude DC. Critical Success: The foe is clumsy 3 or stupefied 3 (your choice) until the end of your next turn. It then becomes immune for 1 hour. Success: The foe is clumsy 2 or stupefied 2 (your choice) until the end of your next turn. Failure: You gain a +1 circumstance bonus to your next attack roll against the foe before the end of your next turn. Critical Failure: You leave yourself open to the enemy. This action has the manipulate trait and triggers reactions as normal for a manipulate action.',
    implemented: 'full',
    traits: ['Attack', 'Investigator'],
    actionCost: 1,
    prerequisites: ['forensic medicine methodology'],
    mechanics: 'Medicine vs Fortitude DC. Crit: clumsy 3 or stupefied 3 until end of next turn (immune 1 hour). Success: clumsy 2 or stupefied 2. Failure: +1 to next attack. Crit fail: triggers manipulate reactions.',
  },
  // ── Level 14 Feats ───────────────────────────────────
  {
    id: 'investigator-plot-the-future',
    name: 'Plot the Future',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You spend 10 minutes in contemplation to uncannily predict how events will play out. Choose a particular goal or activity you plan to engage in within 1 week, or an event you expect might happen within 1 week. You do anything from reflecting on possibilities to consulting the stars, and you gain a vague sense of how things will go. The GM rolls a secret check, which they can use either Perception or a relevant skill for. The result gives you a pointed piece of advice in the form of "highly likely," "somewhat likely," "somewhat unlikely," or "highly unlikely" regarding the expected outcome, and also informs you of one piece of advice about a course of action that might alter the expected outcome.',
    implemented: 'full',
    traits: ['Uncommon', 'Concentrate', 'Investigator', 'Prediction'],
    actionCost: 'passive',
    mechanics: '10-minute activity. GM makes secret check. Learn likelihood of an event within 1 week plus one piece of advice to alter the outcome.',
  },
  {
    id: 'investigator-sense-the-unseen',
    name: 'Sense the Unseen',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'When you look for foes, you can catch even the slightest cues, such as their minute movements or the shifting of air currents on your skin. Even though you failed at the triggering check, you automatically sense any undetected creatures in the area where you\'re Seeking, making them merely hidden to you.',
    implemented: 'full',
    traits: ['Investigator', 'Ranger', 'Rogue'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You fail a check to Seek. Automatically sense undetected creatures in the Seek area, making them hidden instead.',
  },
  {
    id: 'investigator-strategic-bypass',
    name: 'Strategic Bypass',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You have identified and studied the weaknesses of your enemies, and you know how to exploit them. When you hit with a Strike and used Devise a Stratagem to substitute your d20 result for your attack roll, you ignore an amount of resistance the target has equal to your Intelligence modifier per applicable type of resistance.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'On Stratagem hit, ignore resistance equal to INT modifier per type.',
  },
  // ── Level 16 Feats ───────────────────────────────────
  {
    id: 'investigator-didactic-strike',
    name: 'Didactic Strike',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'When you find a glaring weakness, you can set your allies up to annihilate your foe. Your battle insight is so strong that you can convey your knowledge to every ally at once. When you use Shared Stratagem, instead of designating a single ally, you designate up to 10 allies. The foe is off-guard against the first attack made by each designated ally before your next turn. In addition, the first time each designated ally hits the target of your Shared Stratagem before your next turn, that Strike deals an extra 2d6 precision damage.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['Shared Stratagem'],
    mechanics: 'Shared Stratagem affects up to 10 allies. Each ally\'s first hit deals +2d6 precision damage.',
  },
  {
    id: 'investigator-implausible-purchase',
    name: 'Implausible Purchase',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'It seems impossible, but you\'ve analyzed every angle and are able to just keep pulling out exactly the item you need, even in far-flung locations. You can use Prescient Planner even if you\'ve already used it after your last time purchasing goods, and you can use it as a single action (which has the Interact trait) instead of a 2-action activity. In addition, five times per day, you can pull out a common consumable item up to 6 levels lower than your level.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['Predictive Purchase'],
    mechanics: 'Prescient Planner: no purchase cooldown, 1-action (Interact). 5/day pull out a common consumable up to 6 levels lower.',
  },
  {
    id: 'investigator-reconstruct-the-scene',
    name: 'Reconstruct the Scene',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'You spend 1 minute surveying a small location (such as a single room) to get an impression of events that occurred there in the last day. This involves moving about the area and studying footprints, spilled drinks or blood, and so forth. You get an indistinct mental impression of significant events that happened there. This gives you clues and details of the past, including the overall events and their time frame, but it\'s not a perfect record. This also isn\'t enough to identify who was involved in these events if you weren\'t already aware the person was there. As determined by the GM, you also pick out various seemingly small details that could serve as important clues, like a memorable weapon someone used for a murder or the type of cloak someone wore when passing through.',
    implemented: 'full',
    traits: ['Concentrate', 'Investigator', 'Rogue'],
    actionCost: 'passive',
    mechanics: '1-minute activity. Survey a room to gain mental impressions of significant events in the last day, plus small but important clue details.',
  },
  // ── Level 18 Feats ───────────────────────────────────
  {
    id: 'investigator-lead-investigator',
    name: 'Lead Investigator',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'You spend 1 minute briefing up to four allies about one of your active investigations, spending 1 minute explaining details and leads. Allies gain the same circumstance bonus from Pursue a Lead as you do. This lasts until you stop pursuing the lead or for 1 day, whichever comes first. This doesn\'t confer any other benefits of pursuing the lead, such as the bonus to saving throws from Detective\'s Readiness.',
    implemented: 'full',
    traits: ['Exploration', 'Investigator'],
    actionCost: 'passive',
    prerequisites: ['Clue Them All In'],
    mechanics: '1-minute exploration activity. Up to 4 allies gain your Pursue a Lead circumstance bonus for 1 day or until lead ends. No other lead benefits.',
  },
  {
    id: 'investigator-tricksters-ace',
    name: "Trickster's Ace",
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'Whether from jury-rigged magic items, deduction from the study of magical interactions, or other means, you have a contingency in your back pocket for desperate situations. When you make your daily preparations, you must specify a trigger for this reaction using the same restrictions as the triggers for the Ready action. You also choose a single spell from the arcane, divine, occult, or primal list of 4th level or lower. The spell can\'t have a cost, nor can its casting time be more than 10 minutes. The spell must be able to target a single creature, and you must be a valid target for it. When the trigger occurs, you cause the spell to come into effect. The spell targets only you, no matter how many creatures it would affect normally. If you define particularly complicated conditions, as determined by the GM, the trigger might fail. Once the contingency is triggered, the spell is expended until your next daily preparations.',
    implemented: 'full',
    traits: ['Concentrate', 'Investigator'],
    actionCost: 'reaction',
    mechanics: 'During daily preparations, set a trigger and choose a spell (any tradition, 4th level or lower, single target, no cost, ≤10 min cast). When trigger occurs, spell activates targeting only you. Expended until next preparations.',
  },
  // ── Level 20 Feats ───────────────────────────────────
  {
    id: 'investigator-everyones-a-suspect',
    name: "Everyone's a Suspect",
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'You are so suspicious of everyone you meet that you keep mental notes on how to defeat them all—even your own allies. After interacting with a creature for at least 1 minute, you automatically Pursue a Lead with that creature as the subject. You can have any number of such leads at any given time, and when you Pursue a Lead again, you don\'t give up any of these automatic subjects.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    mechanics: 'Auto Pursue a Lead on any creature after 1 minute of interaction. Unlimited automatic leads that persist independently.',
  },
  {
    id: 'investigator-just-the-facts',
    name: 'Just the Facts',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'You fundamentally understand everything to the point where your research can\'t possibly be wrong. You are permanently quickened and can use the extra action to Recall Knowledge. In addition, you gain the following benefits with Recall Knowledge: Your checks to Recall Knowledge are no longer secret. When you Recall Knowledge, you use the outcome for one degree of success better than the result of your check. If an effect (such as Dubious Knowledge) would give you inaccurate information from your Recall Knowledge check, you know which information is inaccurate. When one of your allies Recalls Knowledge and gains false information, you also know that information is inaccurate if they share it with you.',
    implemented: 'full',
    traits: ['Investigator'],
    actionCost: 'passive',
    prerequisites: ['Thorough Research'],
    mechanics: 'Permanently quickened (extra action for Recall Knowledge only). Recall Knowledge: not secret, +1 degree of success, detect inaccurate info from yourself and allies.',
  },
  {
    id: 'investigator-all-the-time-in-the-world',
    name: 'All the Time in the World',
    source: 'Fists of the Ruby Phoenix',
    category: 'class',
    level: 20,
    description: 'Your firsthand experience of the subjective nature of time and space has given you new observational insights. Your mind processes information so quickly that time appears to stop for all creatures but you. You can take up to 9 actions in 3 sets of up to 3 actions each. During this time, you can use purely mental and observational abilities such as Recall Knowledge, Seek, and Devise a Stratagem, and you can use an action to move a mental projection of yourself to a location within a 60-foot radius to observe objects more closely and from different angles, though you can\'t affect your surroundings in any way (for instance, you could move your mental projection more closely to a distant door to read a minute inscription on its handle, but you could not open it to observe the other side). When the duration elapses, time resumes its normal flow.',
    implemented: 'full',
    traits: ['Uncommon', 'Investigator'],
    actionCost: 3,
    mechanics: 'Frequency: once per hour. Take up to 9 actions (3 sets of 3) while time is frozen. Mental/observational only (Recall Knowledge, Seek, Devise a Stratagem). Can project to 60 ft to observe. Cannot affect surroundings.',
  },
];
