/**
 * Inventor Class Features & Feats — PF2e Remastered (Guns & Gears + Tian Xia)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=19
 *
 * Key Attribute: INT | HP: 8 + CON
 * Uncommon class
 * Perception: Trained -> Expert (L13, Alertness)
 * Fort: Expert -> Master (L17, Juggernaut, success->crit)
 * Reflex: Trained -> Expert (L7, Lightning Reflexes)
 * Will: Expert -> Master (L11, Resolve, success->crit)
 * Weapons: Trained simple+martial+unarmed -> Expert (L5) -> Master (L13)
 * Armor: Trained light+medium+unarmored -> Expert (L11) -> Master (L19)
 * Class DC: Trained -> Expert (L9) -> Master (L17)
 * Skills: Crafting + 3 + INT
 *
 * Innovation: Choose Armor, Construct, or Weapon innovation at L1.
 *   Grants initial modification, breakthrough modification (L7), revolutionary (L15).
 * Overdrive: Crafting check to add INT-based damage to Strikes.
 *   Expert (L3), Master (L7), Legendary (L15).
 * Explode: 2-action unstable emanation dealing fire (scaling 2d6+).
 * Unstable trait: DC 15 flat check after use; failure = innovation malfunctions.
 *
 * Class features: 26 (L1-L19) — 20 inline + 6 createClassFeature
 * Class feats: 54 (L1-L20)
 */

import type { FeatEntry } from './featTypes';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
  GREATER_WEAPON_SPECIALIZATION,
  RESOLVE,
  JUGGERNAUT,
  ALERTNESS,
  SHIELD_BLOCK,
} from './sharedFeats';

// ── Inventor Class Features ─────────────────────────────

export const INVENTOR_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'inventor-overdrive',
    name: 'Overdrive',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 1,
    description: 'Frequency: once per round. Temporarily cranking the gizmos on your body into overdrive, you try to add greater power to your attacks. Attempt a Crafting check that has a standard DC for your level. Critical Success: Your gizmos go into a state of incredible efficiency called critical overdrive, adding great power to your attacks. Your Strikes deal additional damage equal to your Intelligence modifier for 1 minute. After the Overdrive ends, you can\'t use Overdrive again for 1 minute as your possibly extradimensional gizmos are possibly on fire. Success: Your gizmos go into overdrive, adding power to your attacks. As critical success, except the additional damage equals half your Intelligence modifier. Critical Failure: You take fire damage equal to half your level (minimum 1). You can\'t use Overdrive again for 1d4 rounds as your possibly extradimensional gizmos are possibly on fire. Also, you can attempt Overdrive while already in overdrive in order to increase an extant overdrive to critical overdrive. On a failure, the overdrive status is unchanged; on a critical failure, the overdrive ends.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 1,
    mechanics: 'Crafting check vs standard DC. Crit success: +INT damage 1 min. Success: +half INT damage 1 min. Failure while overdriving: 1 fire damage. Crit fail: fire damage + can\'t use for 1d4 rounds.',
  },
  {
    id: 'inventor-innovation',
    name: 'Innovation',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 1,
    description: 'You bear a brilliant innovation with you everywhere you go, the source of your power and the living proof of your skill. Choose one of the following innovation types: armor (a suit of medium armor you\'ve designed), construct (a construct companion), or weapon (a weapon of your own devising). Your innovation\'s level is equal to your level. If your innovation is destroyed, you can spend 1 day of downtime and attempt a Crafting check with a high DC for your level to rebuild it; on a failure, you can try again. You also choose one initial modification for your innovation from the modifications available for your innovation type.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Choose Armor, Construct, or Weapon innovation. Grants initial modification. Innovation level = your level.',
    subChoices: { label: 'Choose an innovation type', options: [
      { id: 'armor', name: 'Armor Innovation', description: 'Apply modifications to your armor, gaining special abilities' },
      { id: 'construct', name: 'Construct Innovation', description: 'Build a construct companion with unique modifications' },
      { id: 'weapon', name: 'Weapon Innovation', description: 'Modify a weapon with unique enhancements' },
    ] },
  },
  {
    id: 'inventor-explode',
    name: 'Explode',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 1,
    description: 'Your innovation is a deck of gizmos and machines, and you can turn it into a bomb. You cause your innovation to explode in a 5-foot emanation, dealing 2d6 fire damage with a basic Reflex save against your class DC. You take no damage from the explosion. The damage increases by 1d6 at 3rd level and every level thereafter. With breakthrough innovation, you can choose a 5-foot or 10-foot emanation. With revolutionary innovation, you can choose 5-foot, 10-foot, or 15-foot.',
    implemented: 'full',
    traits: ['Fire', 'Inventor', 'Manipulate', 'Unstable'],
    actionCost: 2,
    mechanics: '5-foot emanation, 2d6 fire (basic Reflex), +1d6 per level after 3rd. Breakthrough: 5 or 10 ft. Revolutionary: 5, 10, or 15 ft. If innovation is minion, it can take this action.',
  },
  {
    id: 'inventor-peerless-inventor',
    name: 'Peerless Inventor',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 1,
    description: 'You are constantly inventing, and your skill at crafting is unmatched. You gain the Inventor skill feat, even if you don\'t meet its prerequisites.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Gain Inventor skill feat (ignore prerequisites).',
  },
  createClassFeature(SHIELD_BLOCK, 'Inventor', 1, {
    idOverride: 'inventor-shield-block',
  }),

  // ── Level 3 ──────────────────────────────────────────
  {
    id: 'inventor-expert-overdrive',
    name: 'Expert Overdrive',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 3,
    description: 'You\'ve increased your skill in crafting, and you can put your gadgets into overdrive with even greater ease. You become an expert in Crafting. When you Overdrive successfully, the additional damage from Overdrive increases by 1.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies.crafting -> expert. Overdrive additional damage +1.',
  },
  {
    id: 'inventor-reconfigure',
    name: 'Reconfigure',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 3,
    description: 'You\'ve become more familiar with the possibilities of your innovation, and you can reconfigure it for maximum effectiveness in any situation. You can spend 1 day of downtime to swap one modification for another of the same kind (initial for initial, breakthrough for breakthrough, or revolutionary for revolutionary). You can also retrain modification feats in the same way.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: '1 day downtime + Crafting check (high DC) to swap one modification for another of the same kind.',
  },

  // ── Level 5 ──────────────────────────────────────────
  {
    id: 'inventor-weapon-expertise',
    name: 'Inventor Weapon Expertise',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 5,
    description: 'You\'ve dedicated yourself to learning the intricacies of your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert. If you have a weapon innovation, you gain access to the critical specialization effect with your innovation.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies: simple+martial weapons + unarmed -> expert. Weapon innovation: critical specialization.',
  },

  // ── Level 7 ──────────────────────────────────────────
  {
    id: 'inventor-breakthrough-innovation',
    name: 'Breakthrough Innovation',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 7,
    description: 'You\'ve made a breakthrough in your field of study and discovered a powerful new way to enhance your innovation. Choose a breakthrough modification for your innovation, or choose an initial modification if you prefer.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Gain a breakthrough modification (or initial modification) for your innovation type.',
    subChoices: { label: 'Choose a breakthrough modification', options: [
      { id: 'aerodynamic-construction', name: 'Aerodynamic Construction', description: 'Armor: +10 ft Speed when unencumbered' },
      { id: 'dense-plating', name: 'Dense Plating', description: 'Armor: resistance to slashing/piercing/bludgeoning' },
      { id: 'enhanced-resistance', name: 'Enhanced Resistance', description: 'Armor/Construct: increase energy resistance' },
      { id: 'heavy-construction', name: 'Heavy Construction', description: 'Construct: increased HP and size' },
      { id: 'hyper-boosters', name: 'Hyper Boosters', description: 'Construct: increased Speed' },
      { id: 'incredible-damage', name: 'Incredible Damage', description: 'Weapon: extra damage dice' },
      { id: 'miraculous-mobility', name: 'Miraculous Mobility', description: 'Armor: remove Speed penalty' },
      { id: 'antimagic-plating', name: 'Antimagic Plating', description: 'Armor: bonus to saves vs magic' },
      { id: 'turret-configuration', name: 'Turret Configuration', description: 'Weapon: ranged configuration' },
    ] },
  },
  {
    id: 'inventor-lightning-reflexes',
    name: 'Lightning Reflexes',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 7,
    description: 'Your reflexes are lightning fast, helped along by your innovations. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies.reflex -> expert.',
  },
  {
    id: 'inventor-master-overdrive',
    name: 'Master Overdrive',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 7,
    description: 'Your skill with crafting is unmatched. You become a master in Crafting. When you successfully Overdrive, the additional damage increases by a total of 2, replacing expert overdrive\'s bonus.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies.crafting -> master. Overdrive additional damage +2 total (replaces expert).',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Inventor', 7, {
    idOverride: 'inventor-weapon-specialization',
  }),

  // ── Level 9 ──────────────────────────────────────────
  {
    id: 'inventor-inventive-expertise',
    name: 'Inventive Expertise',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 9,
    description: 'Through innovation and experimentation, you\'ve made your way of inventing into a true discipline. Your proficiency rank for your inventor class DC increases to expert.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC -> expert.',
  },
  {
    id: 'inventor-offensive-boost',
    name: 'Offensive Boost',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 9,
    description: 'You\'ve made additions to your innovation\'s design to deal additional damage. Your innovation\'s Strikes deal an additional 1d6 damage of a type you choose: acid (appearance: vitriol), bludgeoning (appearance: momentum), cold (appearance: chill), electricity (appearance: jolt), fire (appearance: ignition), piercing (appearance: spike), or slashing (appearance: saws). The type applies to: armor innovation\'s melee unarmed attacks plus one chosen melee weapon; construct innovation\'s companion Strikes; weapon innovation\'s Strikes with the innovation.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Choose damage type. Innovation Strikes deal +1d6 of that type. Options: acid, bludgeoning, cold, electricity, fire, piercing, slashing.',
    subChoices: { label: 'Choose damage type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'bludgeoning', name: 'Bludgeoning' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'piercing', name: 'Piercing' },
      { id: 'slashing', name: 'Slashing' },
    ] },
  },

  // ── Level 11 ─────────────────────────────────────────
  {
    id: 'inventor-medium-armor-expertise',
    name: 'Medium Armor Expertise',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve learned to better defend yourself against attacks. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert. If you have a medium or heavy armor innovation, you gain its critical specialization effect.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies: lightArmor/mediumArmor/unarmored -> expert. Medium/heavy armor innovation: critical specialization.',
  },
  createClassFeature(RESOLVE, 'Inventor', 11, {
    idOverride: 'inventor-resolve',
  }),

  // ── Level 13 ─────────────────────────────────────────
  createClassFeature(ALERTNESS, 'Inventor', 13, {
    idOverride: 'inventor-alertness',
  }),
  {
    id: 'inventor-complete-reconfiguration',
    name: 'Complete Reconfiguration',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 13,
    description: 'When it comes to your innovation, you\'ve learned it\'s best to go back to the drawing board rather than try to patching an old design. When you use your Reconfigure downtime activity and succeed at the Crafting check, you can swap any number of modifications, your offensive boost, or retrain any number of modification feats. The same-kind restriction still applies (initial for initial, etc.).',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Reconfigure: swap any number of modifications/offensive boost/modification feats (same-kind restriction).',
  },
  {
    id: 'inventor-weapon-mastery',
    name: 'Inventor Weapon Mastery',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 13,
    description: 'You fully understand your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies: simple+martial weapons + unarmed -> master.',
  },

  // ── Level 15 ─────────────────────────────────────────
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Inventor', 15, {
    idOverride: 'inventor-greater-weapon-specialization',
  }),
  {
    id: 'inventor-legendary-overdrive',
    name: 'Legendary Overdrive',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 15,
    description: 'Your mastery of Crafting is total, and you can create things others would believe to be impossible. You become legendary in Crafting. When you successfully Overdrive, the additional damage increases by a total of 3, replacing master overdrive\'s bonus.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies.crafting -> legendary. Overdrive additional damage +3 total (replaces master).',
  },
  {
    id: 'inventor-revolutionary-innovation',
    name: 'Revolutionary Innovation',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 15,
    description: 'You are an unparalleled genius and have made a revolutionary discovery in your field. Choose a revolutionary modification for your innovation, or choose an initial or breakthrough modification if you prefer.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Gain a revolutionary modification (or initial/breakthrough) for your innovation type.',
    subChoices: { label: 'Choose a revolutionary modification', options: [
      { id: 'electrify-armor', name: 'Electrify Armor', description: 'Armor: electricity damage to attackers' },
      { id: 'flight-chassis', name: 'Flight Chassis', description: 'Armor: fly Speed' },
      { id: 'perfect-fortification', name: 'Perfect Fortification', description: 'Armor: immune to crits' },
      { id: 'genius-form', name: 'Genius Form', description: 'Construct: increased intelligence' },
      { id: 'masterwork-upgrade', name: 'Masterwork Upgrade', description: 'Construct: major enhancement' },
      { id: 'attack-refinery', name: 'Attack Refinery', description: 'Weapon: enhanced attack bonus' },
      { id: 'devastating-weaponry', name: 'Devastating Weaponry', description: 'Weapon: massive damage boost' },
      { id: 'phlogistonic-regulator', name: 'Phlogistonic Regulator', description: 'Weapon: energy type flexibility' },
    ] },
  },

  // ── Level 17 ─────────────────────────────────────────
  {
    id: 'inventor-inventive-mastery',
    name: 'Inventive Mastery',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 17,
    description: 'Your inventions are incredibly effective. Your proficiency rank for your inventor class DC increases to master.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies.classDC -> master.',
  },
  createClassFeature(JUGGERNAUT, 'Inventor', 17, {
    idOverride: 'inventor-juggernaut',
  }),

  // ── Level 19 ─────────────────────────────────────────
  {
    id: 'inventor-infinite-invention',
    name: 'Infinite Invention',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 19,
    description: 'Your innovation is part of you now, and you can always find the time and resources to rebuild and modify it as needed. During your daily preparations, your innovation automatically works as if it were fixed if it was destroyed or broken. You can also change your innovation type and all your modifications and your offensive boost during your daily preparations. If you change your innovation type, you can retrain any of your feats that have an innovation type prerequisite in 1 day of downtime instead of 1 week.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Daily preparations: auto-fix innovation. Can change innovation type + all modifications/offensive boost. Retrain prereq feats in 1 day.',
  },
  {
    id: 'inventor-medium-armor-mastery',
    name: 'Medium Armor Mastery',
    source: 'Guns & Gears',
    category: 'class_feature',
    level: 19,
    description: 'Your skill with light and medium armor improves, increasing your ability to avoid blows. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to master.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'proficiencies: lightArmor/mediumArmor/unarmored -> master.',
  },
];

// ── Inventor Selectable Feats — PF2e (Guns & Gears + Tian Xia Character Guide)
// ─────────────────────────────────────────────────────────

export const INVENTOR_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'inventor-built-in-tools',
    name: 'Built-In Tools',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You\'ve built tools into your innovation so you can access and use them easily. When you take this feat, choose up to two sets of tools you own, such as thieves\' tools or healer\'s tools, that weigh a total of 2 Bulk or less. These tools become part of your innovation. The innovation\'s Bulk doesn\'t increase from this addition. As long as you are wielding, wearing, or adjacent to your innovation, you have the same quick access to these tools as the tools you are wearing, and they don\'t count against the usual limit of tools you can wear.',
    implemented: 'full',
    traits: ['Inventor', 'Modification'],
    actionCost: 'passive',
  },
  {
    id: 'inventor-explosive-leap',
    name: 'Explosive Leap',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You aim an explosion from your innovation downward to launch yourself into the air. You jump up to 30 feet in any direction without touching the ground. You must land on a space of solid ground, or else you fall after using your next action. As normal for effects where you fall after using your next action, you still fall at the end of your turn, even if you don\'t use any further actions that turn. Special: If your innovation is a minion, it can take this action rather than you.',
    implemented: 'full',
    traits: ['Fire', 'Inventor', 'Move', 'Unstable'],
    actionCost: 1,
  },
  {
    id: 'inventor-haphazard-repair',
    name: 'Haphazard Repair',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You quickly fix your innovation, at the cost of its stability. You Repair your innovation almost immediately. You don\'t have to place the innovation on a flat surface, but you do need to be adjacent to it (including holding or wearing it), as well as having a repair kit as normal.',
    implemented: 'full',
    traits: ['Inventor', 'Unstable'],
    actionCost: 1,
  },
  {
    id: 'inventor-no-no-i-created-you',
    name: 'No! No! I Created You!',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You appeal to your construct companion\'s bond with its creator to have it break free of a controlling effect. Attempt to counteract the effect that confused or controlled your construct companion, using your Crafting modifier for the counteract check and half your level rounded up for the counteract level.',
    implemented: 'full',
    traits: ['Auditory', 'Concentrate', 'Inventor'],
    actionCost: 'reaction',
    prerequisites: ['Construct companion'],
    mechanics: 'Trigger: Your construct companion would become confused or controlled. Frequency: Once per minute. Counteract with Crafting modifier.',
  },
  {
    id: 'inventor-prototype-companion',
    name: 'Prototype Companion',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You have created a construct companion, and while it might not be an innovation, it serves as a trustworthy minion. You gain a prototype construct companion.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
  },
  {
    id: 'inventor-tamper',
    name: 'Tamper',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You tamper with a foe\'s weapon or armor, using a free hand. Choose either a weapon held by an enemy in your reach or a suit of armor worn by an enemy in your reach. Attempt a Crafting check against the enemy\'s Reflex DC. Critical Success: Your tampering is incredibly effective. If you tampered with a weapon, the enemy takes a -2 circumstance penalty to attack rolls and damage rolls with that weapon. If you tampered with armor, the armor hampers the enemy\'s movement, making the enemy off-guard and inflicting a -10-foot penalty to its Speeds. The effect lasts until the enemy Interacts to remove it, regardless of which one you used. Success: Your tampering is temporarily effective. As critical success, but the effect ends at the start of your next turn, even if the enemy doesn\'t Interact to end it. Critical Failure: Your tampering backfires dramatically, creating a small explosion from your own tools or gear. You take fire damage equal to your level.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 1,
    mechanics: 'Requirements: Free hand. Crafting vs Reflex DC. Tamper weapon (-2 attack/damage) or armor (off-guard + -10 Speed).',
    subChoices: { label: 'Choose target', options: [
      { id: 'weapon', name: 'Weapon', description: '-2 circumstance to attack and damage rolls' },
      { id: 'armor', name: 'Armor', description: 'Target becomes off-guard, -10 ft Speeds' },
    ] },
  },
  {
    id: 'inventor-variable-core',
    name: 'Variable Core',
    source: 'Guns & Gears',
    category: 'class',
    level: 1,
    description: 'You adjust your innovation\'s core, changing the way it explodes. When you choose this feat, select acid, cold, or electricity. Your innovation\'s core runs on that power source. When using the Explode action, or any time your innovation explodes on a critical failure and damages you, change the damage type from fire damage to the type you chose. If you have the offensive boost class feature and retrain Variable Core to a different damage type, you can also switch to a different offensive boost that deals the same damage type if you wish.',
    implemented: 'full',
    traits: ['Inventor', 'Modification'],
    actionCost: 'passive',
    subChoices: { label: 'Choose energy type', options: [
      { id: 'acid', name: 'Acid', description: 'Explode deals acid damage' },
      { id: 'cold', name: 'Cold', description: 'Explode deals cold damage' },
      { id: 'electricity', name: 'Electricity', description: 'Explode deals electricity damage' },
    ] },
  },

  // ── Level 2 ──────────────────────────────────────────
  {
    id: 'inventor-collapse-armor',
    name: 'Collapse Armor',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'You\'ve modified your armor innovation to collapse into a more compact form so you can don or remove it in an instant. If you\'re wearing your innovation when you Collapse your Armor, you remove it instantly, and it compresses into its compact form, after which it latches onto your body, typically by attaching to a belt, bandoleer, or other convenient carrying surface as a nondescript satchel. If your armor is stowed and carried on your person in its compact form when you take this action, it unfolds back into its armor form onto your body. In compact form, your armor innovation is easier to carry, with a Bulk 1 lower than the Bulk listed for it, to a minimum of light Bulk.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate', 'Modification'],
    actionCost: 1,
    prerequisites: ['Armor innovation'],
  },
  {
    id: 'inventor-collapse-construct',
    name: 'Collapse Construct',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'You\'ve modified your construct companion and built it out of light materials, enabling you to collapse it into a carrying case or other compact and innocuous form. Either your construct or you (if you\'re adjacent to it) can Collapse your Construct to turn it into its compact form or back into its normal form. In compact form, your construct can\'t act but is easily carried, with a Bulk of 2 if it\'s Small, 4 if it\'s Medium, or 8 if it\'s Large. The compact form has wheels, so you can easily drag it behind you at half your Speed (rather than the usual slower Speed for dragging).',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate', 'Modification'],
    actionCost: 1,
    prerequisites: ['Construct innovation'],
  },
  {
    id: 'inventor-reverse-engineer',
    name: 'Reverse Engineer',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'You are incredibly skilled at reverse engineering items to learn their formulas or disassembling them just to disable them. If you are using the Critical Crafting alternate rules and you get a critical success on your Crafting check to reverse engineer an item, you can reassemble the original item with one of the critical success crafting benefits (as determined by your GM). Furthermore, you can use Crafting instead of Thievery to Disable a Device or Pick a Lock.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Trained in Crafting'],
  },
  {
    id: 'inventor-searing-restoration',
    name: 'Searing Restoration',
    source: 'Guns & Gears',
    category: 'class',
    level: 2,
    description: 'They told you there was no way that explosions could heal people, but they were fools… Fools who didn\'t understand your brilliance! You create a minor explosion from your innovation, altering the combustion to cauterize wounds using vaporized medicinal herbs. You or a living creature adjacent to you regains 1d10 Hit Points. In addition, the creature you heal can attempt an immediate flat check to recover from a single source of persistent bleed damage, with the DC reduction from appropriate assistance. At 3rd level, and every 2 levels thereafter, increase the healing by 1d10. Special: If your innovation is a minion, it can take this action rather than you, though because it\'s not a living creature, it can\'t use the ability on itself.',
    implemented: 'full',
    traits: ['Fire', 'Healing', 'Inventor', 'Manipulate', 'Unstable'],
    actionCost: 1,
    mechanics: 'Heal 1d10 (+1d10 every 2 levels after 3rd). Flat check to end persistent bleed.',
    subChoices: { label: 'Choose an energy type', options: [
      { id: 'fire', name: 'Fire', description: 'Searing heat restoration' },
      { id: 'acid', name: 'Acid', description: 'Corrosive restoration' },
      { id: 'electricity', name: 'Electricity', description: 'Electric restoration' },
    ] },
  },
  {
    id: 'inventor-oil-fire',
    name: 'Oil Fire',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 2,
    description: 'Your armor includes flame-resistant gauntlets with oil-filled finger joints. These joints can split apart, dousing your opponent in flammable oil and then igniting it. The opponent must attempt a Reflex save against your class DC. Critical Success: The grab ends. Success: The grab ends, and the target takes 1 persistent fire damage. Failure: The target takes persistent fire damage equal to half your level. Critical Failure: The target takes persistent fire damage equal to your level.',
    implemented: 'full',
    traits: ['Fire', 'Inventor', 'Manipulate', 'Unstable'],
    actionCost: 1,
    prerequisites: ['Armor innovation'],
    mechanics: 'Requirements: You have a foe grabbed. Reflex save vs class DC for persistent fire damage.',
  },
  {
    id: 'inventor-wukong-extension',
    name: 'Wukong Extension',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 2,
    description: 'Invoking the name of Sun Wukong\'s extending cudgel, Ruyi Bang, you activate hidden levers and cranks in your innovation, making it swiftly extend outward like a battering ram. Make a melee Strike with your weapon innovation; your reach for that Strike is 30 feet.',
    implemented: 'full',
    traits: ['Uncommon', 'Inventor', 'Manipulate', 'Unstable'],
    actionCost: 1,
    prerequisites: ['Weapon innovation'],
    mechanics: 'Access: Tian Xia origin or worshipper of Sun Wukong.',
  },

  // ── Level 4 ──────────────────────────────────────────
  {
    id: 'inventor-advanced-construct-companion',
    name: 'Advanced Construct Companion',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'You\'ve upgraded your construct companion\'s power and decision-making ability. It becomes an advanced construct companion. During an encounter, even if you don\'t use the Command a Construct action, your construct companion can still use 1 action on your turn that round to Stride or Strike.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Construct companion'],
  },
  {
    id: 'inventor-diving-armor',
    name: 'Diving Armor',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'You\'ve modified your armor with fins, rotors, and other devices to make it easy for you to move through the water, plus mechanical gills that can help you extract breathable air from water. While wearing your armor innovation, you can breathe underwater and gain a swim Speed equal to your land Speed.',
    implemented: 'full',
    traits: ['Inventor', 'Modification'],
    actionCost: 'passive',
    prerequisites: ['Armor innovation'],
  },
  {
    id: 'inventor-dual-form-weapon',
    name: 'Dual-Form Weapon',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'You\'ve built your innovation with replaceable interlocking pieces that you can use to transform it into another type of weapon entirely. When you select this feat, choose a level 0 or 1st-level simple or martial weapon. It must be either a common weapon or another to which you have access. This weapon becomes your innovation\'s second configuration. Select a new set of weapon modifications for this new configuration. You can spend two Interact actions to switch your weapon innovation between the two configurations. These actions don\'t need to be taken consecutively, but if you\'ve provided the first and not the second, the weapon is non-functional as it is stranded between states. Your weapon\'s Bulk is always the greater Bulk of the two configurations. Any runes on your weapon innovation affect the second weapon configuration as long as it would normally qualify for them.',
    implemented: 'full',
    traits: ['Inventor', 'Modification'],
    actionCost: 'passive',
    prerequisites: ['Weapon innovation', 'Expert Overdrive'],
  },
  {
    id: 'inventor-gadget-specialist',
    name: 'Gadget Specialist',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'Rather than just using your gadgets for various boosts and tweaks, you also craft a few specific temporary consumable gadgets each day. You gain the formulas for three common or uncommon gadgets. Each day during your daily preparations, you can create two temporary gadgets from your formula book. Gadgets prepared in this way don\'t cost you any resources to Craft and don\'t have any sale value. They are temporary items and fall apart the next time you make your daily preparations if you haven\'t already used them. If you\'re a master in Crafting, you can create three gadgets per day, and you gain three additional common or uncommon gadget formulas. If you\'re legendary in Crafting, you can create four gadgets per day, and you gain another additional three common or uncommon gadget formulas, for a total of nine.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Expert in Crafting'],
  },
  {
    id: 'inventor-megaton-strike',
    name: 'Megaton Strike',
    source: 'Guns & Gears',
    category: 'class',
    level: 4,
    description: 'You activate gears, explosives, and other hidden mechanisms in your innovation to make a powerful attack. You make a Strike, dealing an extra die of weapon damage. If you\'re at least 10th level, increase this to two extra dice, and if you\'re at least 18th level, increase it to three extra dice. The type of Strike depends on your innovation: Armor — melee unarmed or prepared melee weapon; Construct — minion innovation Strikes; Weapon — Strike with weapon innovation. Unstable Function: You put even more force into the Strike, though you risk stress fractures to your innovation. Add the unstable trait. The Strike deals another extra damage die, for a total of two extra dice at 4th level, three at 10th level, and four at 18th level. Special: If your innovation is a minion, it can take this action rather than you.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 2,
    prerequisites: ['Armor, construct, or weapon innovation'],
    mechanics: '+1 die (L4), +2 dice (L10), +3 dice (L18). Unstable: +1 additional die.',
  },
  {
    id: 'inventor-duo-dragon-kick',
    name: 'Duo Dragon Kick',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 4,
    description: 'You\'ve practiced an impressive spin technique with your construct, automatically attacking in tandem as you launch each other through the air. You Command your construct companion to fight alongside you, after which you both Leap in the same direction, making an unarmed Strike at the start or end of the Leap; this uses your companion\'s actions for the turn. If the Strikes both hit the same creature, combine their damage for the purposes of resistances and weaknesses. Unstable Function: You spin farther and higher, though the extreme movement risks discombobulating your innovation. Add the unstable trait. Increase the distance of your Leaps by 10 feet if horizontal or 5 feet if vertical.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 2,
    prerequisites: ['Construct innovation'],
    mechanics: 'Requirements: Your construct innovation is adjacent to you.',
  },

  // ── Level 6 ──────────────────────────────────────────
  {
    id: 'inventor-clockwork-celerity',
    name: 'Clockwork Celerity',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You can use unstable clockwork devices in your innovation to push your invention to act more quickly. You are quickened for this turn. How you can use the extra action depends on your innovation. Armor: You can use the extra action to Step, Stride, or use another movement action granted by your innovation (such as Swim if you have the Diving Armor feat). Construct: You can use the extra action to Command your construct innovation (or to provide 1 of the actions if you spend 2 actions to Command your construct). Weapon: You can use the extra action to Strike with your innovation or Reload your innovation.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate', 'Unstable'],
    actionCost: 'free',
    prerequisites: ['Armor, construct, or weapon innovation'],
    mechanics: 'Trigger: Your turn begins. Quickened for this turn (action depends on innovation type).',
  },
  {
    id: 'inventor-construct-shell',
    name: 'Construct Shell',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You\'ve adjusted your construct innovation so that when you ride it, special plates, hollows, or similar form partial barriers around you to add additional protection. You have lesser cover from all attacks when mounted on your construct innovation, not just from attacks where the construct would be in the way. Additionally, if your construct uses an emanation while you\'re riding on it, such as Explode, you can choose not to be affected by the emanation.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Construct innovation'],
  },
  {
    id: 'inventor-megavolt',
    name: 'Megavolt',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You bleed off some electric power from your innovation in the shape of a damaging bolt. Creatures in a 20-foot line from your innovation take 3d4 electricity damage, with a basic Reflex save against your class DC. The electricity damage increases by 1d4 at 8th level and every 2 levels thereafter. Unstable Function: You overload and supercharge the voltage even higher. Add the unstable trait. The area increases to a 60-foot line and the damage increases from d4s to d12s. With breakthrough innovation, choose a 60-foot or 90-foot line; with revolutionary innovation, choose 60-foot, 90-foot, or 120-foot line. Special: If your innovation is a minion, it can take this action rather than you.',
    implemented: 'full',
    traits: ['Electricity', 'Inventor', 'Manipulate'],
    actionCost: 2,
    mechanics: '20-foot line, 3d4 electricity (basic Reflex), +1d4 every 2 levels after 8th. Unstable: 60-ft line, d4s->d12s.',
  },
  {
    id: 'inventor-visual-fidelity',
    name: 'Visual Fidelity',
    source: 'Guns & Gears',
    category: 'class',
    level: 6,
    description: 'You\'ve found a way to use a hodgepodge combination of devices to enhance your visual abilities in every situation. You gain darkvision and low-light vision, and you can see invisible creatures and objects as translucent shapes, though these shapes are indistinct enough to be concealed to you. If an effect would give you the blinded condition, the effect must attempt a counteract check against your class DC, with your counteract level equaling half your level, rounded up. On a failed counteract check, you aren\'t blinded—your various devices are able to compensate.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
  },
  {
    id: 'inventor-silk-bracelet',
    name: 'Silk Bracelet',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 6,
    description: 'Taking inspiration from Desna\'s image as a giant silk moth in Tian Xia, you\'ve attached a bracelet to your innovation that generates ultra-strong silk strands mixed with venom. You can unleash this substance as part of an attack. Make a melee Strike. If it hits, the target takes damage from the Strike as normal and must attempt a Fortitude save against your class DC. Critical Success: The target is unaffected. Success: The silk imposes a -10 foot status penalty to all the target\'s Speeds for 1 round. Failure: As success, and the target takes an additional 1d4 persistent poison damage. The poison damage increases to 2d4 at 12th level and 3d4 at 18th level. Critical Failure: As failure, and the target is immobilized until the end of their next turn.',
    implemented: 'full',
    traits: ['Uncommon', 'Inventor', 'Manipulate'],
    actionCost: 2,
    prerequisites: ['Armor, construct, or weapon innovation'],
    mechanics: 'Access: Tian Xia origin. Melee Strike + Fortitude save for Speed penalty / persistent poison.',
  },
  {
    id: 'inventor-xidao-sea-mine-drop',
    name: 'Xidao Sea Mine Drop',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 6,
    description: 'You\'ve rigged your armor innovation with a gizmo that can safely synthesize two sea mines a day, holding them in a protected compartment. You must be submerged in water to use this action, and the mines only detonate if they\'re underwater. You off-load a mine onto an unoccupied square within your reach. The mine detonates when a Small or larger creature moves into its square, or when you Interact to Activate your gizmo\'s remote detonation button (up to 50 feet away). You can hide a mine as a 1-minute activity; creatures detect it as a trap using your Crafting DC as the Stealth DC. Any creature in a 5-foot emanation when it detonates takes 3d4 bludgeoning damage and 1d4 piercing damage, with a basic Reflex save against your class DC. The bludgeoning damage increases by 1d4 at 8th level and every 2 levels thereafter. Undetonated mines become inert during daily preparations. Unstable Function: Add the unstable trait. You create up to 3 additional sea mines that you can immediately deploy in different unoccupied spaces up to 30 feet away.',
    implemented: 'full',
    traits: ['Uncommon', 'Inventor'],
    actionCost: 2,
    prerequisites: ['Diving Armor'],
    mechanics: 'Access: Tian Xia origin. Requirements: Submerged in water. 2 mines/day, deployable traps.',
  },

  // ── Level 8 ──────────────────────────────────────────
  {
    id: 'inventor-gigaton-strike',
    name: 'Gigaton Strike',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'When you use a full-power Megaton Strike, you can knock your foe back. When you succeed at your Strike while using an unstable Megaton Strike, your target must attempt a Fortitude save against your class DC. Critical Success: The creature is unaffected. Success: The creature is pushed back 5 feet. Failure: The creature is pushed back 10 feet. Critical Failure: The creature is pushed back 20 feet. Special: If your innovation is a minion, this benefit applies on its unstable Megaton Strikes.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Megaton Strike'],
  },
  {
    id: 'inventor-incredible-construct-companion',
    name: 'Incredible Construct Companion',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'Thanks to your continual tinkering, your construct companion has advanced to an astounding new stage of engineering, enhancing all its attributes. Your construct companion becomes an incredible construct companion.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Advanced Construct Companion'],
  },
  {
    id: 'inventor-manifold-modifications',
    name: 'Manifold Modifications',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You\'ve modified your innovation using clever workarounds, so you can include another initial modification without compromising its structure. Your innovation gains an additional initial modification from the list for innovations of its type.',
    implemented: 'full',
    traits: ['Inventor', 'Modification'],
    actionCost: 'passive',
    prerequisites: ['Initial modification'],
  },
  {
    id: 'inventor-overdrive-ally',
    name: 'Overdrive Ally',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'You quickly fling some of your powered-up mechanisms to an ally, sharing your benefits with them briefly. Choose an ally within 30 feet. Until the end of their next turn, that ally\'s Strikes deal additional damage equal to half your Intelligence modifier, or your full Intelligence modifier if you were in critical overdrive. The ally doesn\'t gain the increased damage from expert, master, or legendary overdrive.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 1,
    prerequisites: ['Overdrive'],
    mechanics: 'Requirements: You are currently in overdrive.',
  },
  {
    id: 'inventor-ubiquitous-gadgets',
    name: 'Ubiquitous Gadgets',
    source: 'Guns & Gears',
    category: 'class',
    level: 8,
    description: 'They thought you had used up all your devices, but they thought wrong! You have a few more gadgets up your sleeve than others expect. Increase the number of temporary gadgets you can create each day by 2. Special: You can select this feat a second time if you are 14th level or higher.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Gadget Specialist'],
  },
  {
    id: 'inventor-guardian-lion-roar',
    name: 'Guardian Lion Roar',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 8,
    description: 'Your innovation is augmented with plates shaped to resemble the gaping maws of guardian lions, which you can energize to expel a stream of sonic energy reminiscent of a lion\'s powerful roar. All creatures in a 20-foot line from your innovation take 2d8 sonic damage with a basic Fortitude save against your class DC. Creatures that fail this save become off-guard for 1 round. The damage increases by 1d8 at 10th level and every 2 levels thereafter. Unstable Function: You press concealed switches in the guardian lions\' plates, extending their reach and power. Add the unstable trait. The range increases to a 60-foot line. Creatures that succeed (but not critically succeed) at their save also become off-guard for 1 round. On a critical failure when attempting the flat check for this unstable action, you take sonic damage equal to your level instead of fire damage. Special: If your innovation is a minion, it can take this action rather than you.',
    implemented: 'full',
    traits: ['Auditory', 'Inventor', 'Sonic'],
    actionCost: 2,
    prerequisites: ['Armor, construct, or weapon innovation'],
    mechanics: '20-foot line, 2d8 sonic (basic Fort), +1d8 every 2 levels after 10th. Failed save: off-guard 1 round.',
  },

  // ── Level 10 ─────────────────────────────────────────
  {
    id: 'inventor-distracting-explosion',
    name: 'Distracting Explosion',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'Your enemies think they can concentrate on something else while you\'re nearby? Oh, you\'ll give them a distraction, all right! Make a melee Strike against the triggering creature with a weapon or unarmed attack that is benefiting from your offensive boost. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike. Unstable Function: You pull out all the stops to create an explosive distraction. Add the unstable trait. If the attack hits, you disrupt the triggering concentrate action. Special: If your innovation is a minion, it can take this reaction instead of you, even though minions can\'t normally take reactions or act when it\'s not their turn. It uses your reaction for the turn to do so.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 'reaction',
    prerequisites: ['Offensive boost'],
    mechanics: 'Trigger: A creature within your reach uses a concentrate action. Free Strike; unstable: disrupt the action.',
  },
  {
    id: 'inventor-electrify-armor',
    name: 'Electrify Armor',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You electrify your armor to punish foes who dare to attack you. For 1 round, any creature that touches you, or that hits you with a melee unarmed attack or a non-reach melee weapon attack, takes 1d4 electricity damage. The effect ends if you cease wearing your armor innovation. If you have the revolutionary innovation class feature, the damage increases to 2d4. Unstable Function: You create an unstable chain reaction, sending countless sparks dancing across your armor. Add the unstable trait. The effects last for 1 minute instead of 1 round, and the damage dice increase from d4s to d12s.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 1,
    prerequisites: ['Armor innovation'],
    mechanics: 'Requirements: You are wearing your armor innovation. 1d4 electricity to melee attackers for 1 round (2d4 with revolutionary). Unstable: 1 minute, d12s.',
  },
  {
    id: 'inventor-helpful-tinkering',
    name: 'Helpful Tinkering',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'You don\'t just tinker with your own innovation, you fiddle with your allies\' weapons as well (for their benefit, of course). Choose an ally in your reach and one of their weapons. Attempt a Crafting check against a high DC for your level. Success: For 1 minute, the chosen ally\'s Strikes with the chosen weapon gain the same offensive boost your innovation has. Critical Failure: Your ally takes damage of the type and amount that your offensive boost normally deals on a successful Strike.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 1,
    prerequisites: ['Offensive boost'],
    mechanics: 'Frequency: Once per 10 minutes. Crafting check (high DC) to grant offensive boost to ally weapon.',
  },
  {
    id: 'inventor-lock-on',
    name: 'Lock On',
    source: 'Guns & Gears',
    category: 'class',
    level: 10,
    description: 'Aha! You lock on to your enemy\'s weak point to assist your construct companion in destroying it. When you Lock On, designate an enemy you can see. If your next action is to Command your construct, the construct gains a +2 circumstance bonus to attack rolls against the designated enemy until the end of the turn. If you use 2 actions for the Command, the bonus is instead a +3 circumstance bonus, or a +4 circumstance bonus if you\'re legendary in Crafting.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 1,
    prerequisites: ['Construct innovation'],
  },
  {
    id: 'inventor-geobukseon-retaliation',
    name: 'Geobukseon Retaliation',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 10,
    description: 'Your armor has a retractable spike-covered shell reminiscent of Hwanggot\'s heavily armored geobukseon, or "turtle ships." The shell unfolds across your body, giving you a +4 circumstance bonus to AC and resistance 2 to bludgeoning, piercing, and slashing damage until the end of your next turn. Spiked chains propelled by small bursts of black powder also erupt from the shell, dealing 3d4 piercing damage plus 2 persistent fire damage (basic Reflex save against your class DC) to all creatures in a 5-foot emanation.',
    implemented: 'full',
    traits: ['Uncommon', 'Fire', 'Inventor', 'Modification', 'Unstable'],
    actionCost: 'reaction',
    prerequisites: ['Armor innovation'],
    mechanics: 'Access: Tian Xia origin. Trigger: You would take damage. +4 AC, resistance 2 B/P/S, 3d4 piercing + 2 persistent fire in 5-ft emanation.',
  },

  // ── Level 12 ─────────────────────────────────────────
  {
    id: 'inventor-boost-modulation',
    name: 'Boost Modulation',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You aren\'t satisfied with keeping to just one kind of boost from your constant tinkering, so you\'ve learned to modulate between several possibilities at once. Choose two additional offensive boosts. You can use an Interact action to change the offensive boost currently affecting your weapon, choosing between the one you chose for the class feature and the two you chose for this modification. If your weapon has the modular trait, you can swap the offensive boost as part of the Interact action you take to use that trait.',
    implemented: 'full',
    traits: ['Inventor', 'Manipulate'],
    actionCost: 'passive',
    prerequisites: ['Offensive boost'],
    subChoices: { label: 'Choose two offensive boosts', options: [
      { id: 'antimagic', name: 'Antimagic', description: 'Disrupts spells on hit' },
      { id: 'chill', name: 'Chill', description: 'Cold damage boost' },
      { id: 'electric', name: 'Electric', description: 'Electricity damage boost' },
      { id: 'flame', name: 'Flame', description: 'Fire damage boost' },
      { id: 'gravitational', name: 'Gravitational', description: 'Force damage boost' },
      { id: 'kinetic', name: 'Kinetic', description: 'Extra physical damage boost' },
      { id: 'venom', name: 'Venom', description: 'Poison damage boost' },
    ] },
  },
  {
    id: 'inventor-contingency-gadgets',
    name: 'Contingency Gadgets',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You are too brilliant to be caught off guard, and you always have just the right gadget for the situation. When you prepare your gadgets during your daily preparations, you can choose to leave one of them as a contingency gadget that you keep ready for just this situation, rather than declaring which gadget you\'re making. You can pull the contingency gadget out using an Interact action, at which point you must choose which gadget you had prepared as a contingency. If you\'re legendary in Crafting, you can leave two contingency gadgets during your daily preparations, instead of just one.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Gadget Specialist'],
  },
  {
    id: 'inventor-deep-freeze',
    name: 'Deep Freeze',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You vent a jet of supercooled fluid from your innovation, damaging a foe and slowing it down. Target one creature within 60 feet. That creature takes cold damage equal to your level, with effects depending on its Reflex save. Critical Success: The target is unaffected. Success: The target takes half damage and takes a -5-foot status penalty to its Speeds for 1 round. Failure: The target takes full damage and takes a -10-foot status penalty to its Speeds for 1 round. Critical Failure: The target takes double damage, is slowed 1 for 1 round, and takes a -15-foot status penalty to its Speeds for 1 round. Unstable Function: Your innovation discharges an enormous cone of supercooled fluid, potentially causing cascading failures. Add the unstable trait. The ability affects all creatures within a 60-foot cone instead of a single target, and it deals cold damage equal to double your level. With revolutionary innovation, you can choose a 60-foot or 90-foot cone. Special: If your innovation is a minion, it can take this action rather than you.',
    implemented: 'full',
    traits: ['Cold', 'Inventor', 'Manipulate'],
    actionCost: 2,
    mechanics: '60 ft range, cold damage = level (Reflex save). Unstable: 60-ft cone, double level damage.',
  },
  {
    id: 'inventor-gigavolt',
    name: 'Gigavolt',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'When you unleash electricity from your innovation, you can bounce it off obstacles, creating a field of electric death. When you use Megavolt, each time your line of electricity hits a solid barrier, such as a wall, it bounces off at an angle of your choice and continues until you have reached the full length of the line. Even if a creature is in the area from multiple bounces, it takes the damage only once.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Megavolt'],
  },
  {
    id: 'inventor-shared-overdrive',
    name: 'Shared Overdrive',
    source: 'Guns & Gears',
    category: 'class',
    level: 12,
    description: 'You\'ve experimented enough on your teammates to transfer a substantial number of powered-up gizmos to them, enabling one of your allies to benefit from the full effects and duration of your Overdrive. The first time you use Overdrive Ally during a given Overdrive, the effect lasts for the remainder of the duration of your Overdrive, instead of just until the end of the target\'s next turn. Any further uses of Overdrive Ally during the same Overdrive have their normal duration, per Overdrive Ally.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Overdrive Ally'],
  },
  {
    id: 'inventor-celestial-cacophony',
    name: 'Celestial Cacophony',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 12,
    description: 'Your weapon contains a detonation chamber that launches fireworks, sparklers, and black powder pellets that sizzle, twist, and scatter on the ground in a cacophonous manner liable to annoy the entire Celestial Court. All creatures in a 15-foot cone extending from your innovation take 3d4 fire damage and 3d4 sonic damage with a basic Fortitude save against your class DC; both the fire and sonic damage increase by 1d4 at 14th level and every 2 levels thereafter. The area affected by the cone becomes difficult terrain until the start of your next turn. Creatures moving through this area must succeed at a Reflex save against your class DC or take 2d4 persistent fire damage. Unstable Function: You rattle your weapon violently to make it belch out even more pyrotechnics. Add the unstable trait. The area increases to a 30-foot cone, and all damage dice increase from d4s to d8s.',
    implemented: 'full',
    traits: ['Uncommon', 'Fire', 'Inventor', 'Manipulate', 'Sonic', 'Visual'],
    actionCost: 3,
    prerequisites: ['Weapon innovation'],
    mechanics: 'Access: Tian Xia origin. 15-ft cone, 3d4 fire + 3d4 sonic (basic Fort), difficult terrain. Unstable: 30-ft cone, d4s->d8s.',
  },

  // ── Level 14 ─────────────────────────────────────────
  {
    id: 'inventor-explosive-maneuver',
    name: 'Explosive Maneuver',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'Thanks to a hidden experimental feature you built into your weapon, your weapon explosively deploys levers, tangling hooks, or similar mechanisms to provide significant assistance when you perform a combat maneuver. When you use Explosive Maneuver, choose Grapple, Shove, or Trip. Your weapon innovation must have a weapon trait that matches the action you chose (for instance, to choose Grapple, your weapon must have the grapple trait). You take the chosen action against the same foe as your previous successful Strike, using the same multiple attack penalty as your previous successful Strike. You still increase your multiple attack penalty after the Grapple, Shove, or Trip, as normal.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 1,
    prerequisites: ['Weapon innovation'],
    mechanics: 'Requirements: Your last action was a successful Strike with your weapon innovation. Choose Grapple, Shove, or Trip at same MAP.',
    subChoices: { label: 'Choose a maneuver', options: [
      { id: 'grapple', name: 'Grapple' },
      { id: 'shove', name: 'Shove' },
      { id: 'trip', name: 'Trip' },
    ] },
  },
  {
    id: 'inventor-paragon-companion',
    name: 'Paragon Companion',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'Your construct companion has reached the pinnacle of form and function. Your construct companion becomes a paragon construct companion.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Incredible Construct Companion'],
  },
  {
    id: 'inventor-soaring-armor',
    name: 'Soaring Armor',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'Whether through a release of jets of flame, propeller blades, sonic bursts, streamlined aerodynamic structure, electromagnetic fields, or some combination of the above, you\'ve managed to free your innovation from the bonds of gravity! While wearing your innovation, you gain a fly Speed equal to your land Speed.',
    implemented: 'full',
    traits: ['Inventor', 'Modification'],
    actionCost: 'passive',
    prerequisites: ['Armor innovation'],
  },
  {
    id: 'inventor-unstable-redundancies',
    name: 'Unstable Redundancies',
    source: 'Guns & Gears',
    category: 'class',
    level: 14,
    description: 'You\'ve built triple redundancies into your innovation and added all sorts of buffers to protect it from the harm of your unstable experiments. You automatically succeed at the triggering flat check. You can\'t rely on your Unstable Redundancies again until you spend 10 minutes setting them back up. If you spend 10 minutes retuning your innovation so you can use unstable actions again, you can set up your Unstable Redundancies during the same time.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'free',
    mechanics: 'Trigger: You would attempt the flat check for an unstable action, but you haven\'t rolled yet. Auto-succeed. Recharge: 10 minutes.',
  },

  // ── Level 16 ─────────────────────────────────────────
  {
    id: 'inventor-just-the-thing',
    name: 'Just the Thing!',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'Need to balance on a razor\'s edge, force open an iron door, or persuade a dragon to negotiate? Never fear! No matter the situation, you always have just the thing. You attempt a skill action that takes 1 minute or less to complete, using the same number of actions or amount of time as normal. However, as you take the action, describe a device you pull out and use to accomplish the skill. The specifics of how you accomplish this are up to you, but they should fit the challenge at hand. Using an invention in this way lets you alter how you calculate the skill check used in the action. Instead of the normal skill modifier associated with that skill action, you use your Crafting modifier.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    mechanics: 'Frequency: Once per hour. Use Crafting modifier in place of any skill for an action (1 minute or less).',
  },
  {
    id: 'inventor-persistent-boost',
    name: 'Persistent Boost',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'Your innovation sets foes on fire, covers them in acid, leaves barbed thorns behind, or otherwise deals persistent damage to your foes that sticks around long after you deliver your boosted attack. When you or your construct innovation damage a foe with offensive boost, that foe also takes 1d8 persistent damage of the same damage type as the offensive boost damage.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Offensive boost'],
  },
  {
    id: 'inventor-you-failed-to-account-for-this',
    name: 'You Failed to Account for… This!',
    source: 'Guns & Gears',
    category: 'class',
    level: 16,
    description: 'When your foes try to attack you, you always seem to have some outlandish invention you can pull out at the last second to protect you from whatever attack they throw at you. Describe a device you\'re attempting to use to protect yourself from the foe\'s attack. Using an invention to defend in this way means that the attack roll for the triggering attack targets your Crafting DC instead of your AC. Since you\'re using your Crafting DC instead of your AC, any penalties to your AC don\'t apply, but this doesn\'t remove any conditions or other effects that are causing you such penalties. For instance, if you were off-guard and used an invention to defend against a sneak attack, you\'d still take the extra precision damage if you were hit, even though the -2 penalty to AC from being off-guard wouldn\'t apply to your Crafting DC.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature you can see targets you with an attack against your AC. Attack targets Crafting DC instead of AC.',
  },

  // ── Level 18 ─────────────────────────────────────────
  {
    id: 'inventor-devastating-weaponry',
    name: 'Devastating Weaponry',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'You release a volley of projectiles from your weapon, or power it to fly in every direction across the battlefield and Strike multiple creatures. Make a Strike with your weapon innovation against each foe within 30 feet of you. Don\'t increase your multiple attack penalty until after making all the attacks. If your innovation is a melee weapon and any of the attacks are outside your reach, you Release the weapon before the Strikes, and it returns to your grasp after all of them. If your hands are full when the weapon returns, it falls to the ground in your space. As normal, if your weapon innovation requires one or more actions to reload between Strikes, you can\'t use it to make multiple attacks with Devastating Weaponry.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 3,
    prerequisites: ['Weapon innovation'],
  },
  {
    id: 'inventor-engine-of-destruction',
    name: 'Engine of Destruction',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'Your construct unleashes a broad swath of devastation by separating its limbs, deploying hidden armaments, or using a similar technique to wreak havoc. You Command your innovation. Instead of its normal actions, it Strides once, then makes a Strike against each foe within 30 feet of it with a +2 circumstance bonus to its attack rolls. The multiple attack penalty doesn\'t increase until after the construct makes all the attacks.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 3,
    prerequisites: ['Construct innovation'],
  },
  {
    id: 'inventor-negate-damage',
    name: 'Negate Damage',
    source: 'Guns & Gears',
    category: 'class',
    level: 18,
    description: 'Your armor innovation activates various devices you prepared ahead of time, and you use one of them to reduce the damage you would take by 15. Unstable Function: You activate all the precautions at once, violently repelling the incoming attack to blunt its force. Add the unstable trait to Negate Damage and reduce the damage you would take by 50.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'reaction',
    prerequisites: ['Armor innovation'],
    mechanics: 'Trigger: You would take damage. Reduce damage by 15. Unstable: reduce by 50.',
  },

  // ── Level 20 ─────────────────────────────────────────
  {
    id: 'inventor-full-automation',
    name: 'Full Automation',
    source: 'Guns & Gears',
    category: 'class',
    level: 20,
    description: 'You become so entwined with your innovations that you can use them without a second thought. You\'re permanently quickened. How you can use the extra action depends on your innovation. Armor: Your armor responds to the most subtle stimuli to move you in the right direction as long as you are wearing it. You can use the extra action to Stride, Step, or use a form of movement provided by your innovation (such as Fly or Swim). Construct: Your ability to command your construct becomes instinctive. You can use the extra action to Command your construct innovation (or to provide 1 of the actions if you choose to spend 2 actions to Command your construct). Weapon: Your weapon becomes easier to wield with deadly efficacy, almost as if it is an extension of your body. It speeds effortlessly toward whatever target you choose as long as you are holding it. You can use the extra action to Strike with your innovation.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Armor, construct, or weapon innovation'],
    mechanics: 'Permanently quickened. Extra action depends on innovation type: Armor (move), Construct (Command), Weapon (Strike).',
  },
  {
    id: 'inventor-ubiquitous-overdrive',
    name: 'Ubiquitous Overdrive',
    source: 'Guns & Gears',
    category: 'class',
    level: 20,
    description: 'You prepare a variety of incredible gizmos on each of your allies, linking them together through careful modification to enable you to power them up all at once. During your daily preparations, select up to six willing allies. Whenever you Overdrive, you grant the benefits of your overdrive to any of these allies you choose who are within 30 feet of you. The allies don\'t gain the increased damage from expert, master, or legendary overdrive.',
    implemented: 'full',
    traits: ['Inventor'],
    actionCost: 'passive',
    prerequisites: ['Shared Overdrive'],
  },
];
