import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION, ALERTNESS, RESOLVE, JUGGERNAUT } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// MAGUS  –  Secrets of Magic pp. 35–49
// Key: STR or DEX  |  HP: 8 + CON
// Tradition: Arcane (prepared bounded caster, spellbook)
// Hybrid Studies: Inexorable Iron, Laughing Shadow, Sparkling Targe, Starlit Span, Twisting Tree
// ──────────────────────────────────────────────────────────

// ── Class Features (automatically granted) ────────────────
export const MAGUS_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────────
  {
    id: 'magus-arcane-spellcasting',
    name: 'Arcane Spellcasting',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 1,
    description: 'You study spells so you can combine them with your attacks or solve problems that strength of arms alone can\'t handle. You can cast arcane spells using the Cast a Spell activity, and you can supply material, somatic, and verbal components when casting spells. Because you\'re a magus, you can draw replacement sigils with the tip of your weapon or your free hand for spells requiring material components, replacing them with somatic components instead of needing a material component pouch.\n\nAt 1st level, you can prepare one 1st-level spell and five cantrips each morning from the spells in your spellbook. Prepared spells remain available to you until you cast them or until you prepare your spells again. As you increase in level, your number of spell slots and the highest rank of spells you can cast increase. Because you split your focus between physical training and magical scholarship, you have no more than two spell slots of your highest rank and two spell slots of 1 rank lower than your highest spell rank.\n\nSome of your spells require you to attempt a spell attack roll to see how effective they are, or have your enemies roll against your spell DC. Your spell attack rolls and spell DCs use your Intelligence modifier.\n\nYou start with a spellbook containing your choice of eight arcane cantrips and four 1st-level arcane spells. Each time you gain a level, you add two more arcane spells to your spellbook, of any rank you can cast.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Prepared bounded arcane casting. Max 2 slots at highest level, 2 at highest−1. Spellbook: 8 cantrips + 4 L1 spells, +2/level. Intelligence for spell attacks/DCs. Can replace material with somatic components.',
  },
  {
    id: 'magus-spellstrike',
    name: 'Spellstrike',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 1,
    description: 'You channel a spell into a punch or sword thrust to deliver a combined attack. You Cast a Spell that takes 1 or 2 actions to cast and requires either a spell attack roll or a saving throw. You imbue its effects into an attack instead of executing the spell normally. Make a melee Strike with a weapon or unarmed attack. This counts as two attacks for your multiple attack penalty, but you don\'t apply the penalty until after you\'ve completed the Spellstrike. The infusion of spell energy grants your Strike the arcane trait, making it magical.\n\nIf the spell required a spell attack roll, use your Strike\'s results to determine the effects of both the Strike and the spell. If it required a save, the target of the Strike rolls its saving throw normally, though if your Strike was a critical failure, the target is unaffected.\n\nAfter you use Spellstrike, you can\'t do so again until you recharge your Spellstrike as a single action (concentrate trait). You also recharge your Spellstrike when you cast a conflux spell that takes at least 1 action to cast.\n\nSpellstrike Specifics:\n• One Target: The spell targets only the target of your Strike, even if it normally allows more targets, including area spells.\n• Reach: The coupled spell affects the target using the reach of the weapon or unarmed attack.\n• Ancillary Effects: Non-targeted effects still apply normally. The spell takes effect after the Strike deals damage.\n• Multiple Defenses: Additional rolls after the initial spell attack still happen normally.\n• Invalid or Immune Target: If the target wouldn\'t be valid for the spell, the spell is expended but doesn\'t affect the target.\n• Variable Actions: Choose the 1- or 2-action version of the spell.\n• Spellshape: Typically can\'t be used with Spellstrike.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 2,
    mechanics: 'Cast a Spell (1–2 actions, attack roll or save) + melee Strike combined. Counts as 2 attacks for MAP, but MAP not applied until after. Strike gains arcane trait. Must recharge (1 action, concentrate) before reuse. Conflux spells also recharge Spellstrike.',
  },
  {
    id: 'magus-arcane-cascade',
    name: 'Arcane Cascade',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 1,
    description: 'After you wield magic, you can enter a special stance to make your attacks more effective. You divert a portion of the spell\'s magical power and keep it cycling through your body and weapon using specialized forms, breathing, or footwork. While you\'re in the stance, your melee Strikes deal 1 extra force damage. This damage increases to 2 if you have weapon specialization and 3 if you have greater weapon specialization. Any Strike that benefits from this damage gains the arcane trait, making it magical.\n\nIf your most recent spell before entering the stance was one that can deal damage, the damage from the stance is instead the same type that spell could deal (or one type of your choice if the spell could deal multiple types of damage).',
    implemented: 'full',
    traits: ['Concentrate', 'Magus', 'Stance'],
    actionCost: 1,
    prerequisites: ['You used your most recent action this turn to Cast a Spell or make a Spellstrike'],
    mechanics: 'Stance: melee Strikes deal +1 force (or spell damage type). Scales to +2 with weapon specialization, +3 with greater weapon specialization. Strikes gain arcane trait.',
  },
  {
    id: 'magus-hybrid-study',
    name: 'Hybrid Study',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 1,
    description: 'Your extensive physical training and carefully chosen magic combine to form a unique and dangerous fighting style. You choose one field of hybrid study. Your hybrid study gives you a special ability, usually tied to Spellstrike or Arcane Cascade, and it determines your initial conflux spell.\n\nInexorable Iron: When you enter Arcane Cascade and at the start of each turn while in the stance, if wielding a melee weapon in two hands, you gain temporary HP equal to half your level (minimum 1). Conflux Spell: Thunderous Strike. Studious Spells: enlarge (7th), earthbind (11th), planar tether (13th).\n\nLaughing Shadow: While in Arcane Cascade, you gain +5-ft status bonus to Speeds (+10 ft if unarmored). If you have a free hand and attack an off-guard creature, increase extra damage to 3 (5 with weapon specialization, 7 with greater). Conflux Spell: Dimensional Assault. Studious Spells: blur (7th), shift blame (11th), translocate (13th).\n\nSparkling Targe: You gain Shield Block. While in Arcane Cascade with shield raised, your shield\'s circumstance bonus to AC also applies to saves against spells/magical effects. Damage from spells/magical effects can trigger Shield Block. Increase shield Hardness by Arcane Cascade extra damage. Conflux Spell: Shielding Strike. Studious Spells: resist energy (7th), warding aggression (11th), mountain resilience (13th).\n\nStarlit Span: When you use Spellstrike, you can make a ranged weapon or ranged unarmed Strike within the first range increment. You can deliver the spell even if its range is shorter. Conflux Spell: Shooting Star. Studious Spells: darkvision (7th), wall of wind (11th), unfettered movement (13th).\n\nTwisting Tree: While wielding a staff in one hand, it gains agile and its damage die increases to 1d6. In both hands, it gains parry, reach, and trip. While in Arcane Cascade, you can change grip as a free action when you Strike with your staff. Conflux Spell: Spinning Staff. Studious Spells: embed message (7th), slow (11th), flicker (13th).',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Choose one hybrid study at creation. Each grants a conflux spell, a special ability, and studious spell selections at 7th/11th/13th.',
    subChoices: { label: 'Choose a hybrid study', options: [
      { id: 'inexorable-iron', name: 'Inexorable Iron', description: 'Two-handed weapons; Thunderous Strike conflux spell' },
      { id: 'laughing-shadow', name: 'Laughing Shadow', description: 'Light weapons + mobility; Dimensional Assault conflux spell' },
      { id: 'sparkling-targe', name: 'Sparkling Targe', description: 'Shield + defense; Shielding Strike conflux spell' },
      { id: 'starlit-span', name: 'Starlit Span', description: 'Ranged Spellstrike; Shooting Star conflux spell' },
      { id: 'twisting-tree', name: 'Twisting Tree', description: 'Staff weapons; Spinning Staff conflux spell' },
    ] },
  },
  {
    id: 'magus-conflux-spells',
    name: 'Conflux Spells',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 1,
    description: 'You learn a conflux spell from your hybrid study. Conflux spells are magus-specific focus spells created for combat. It costs 1 Focus Point to cast a focus spell, and you start with a focus pool of 1 Focus Point. You refill your focus pool during your daily preparations, and you can regain 1 Focus Point by spending 10 minutes using the Refocus activity to both study your spellbook and perform a physical regimen.\n\nFocus spells are automatically heightened to half your level rounded up. Focus spells don\'t require spell slots, nor can you cast them using spell slots. Taking feats can give you more focus spells and increase the size of your focus pool, though your focus pool can never hold more than 3 points.\n\nCasting a conflux spell that takes at least 1 action also recharges your Spellstrike.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Focus pool: 1 FP. Refocus: 10 min (study spellbook + physical regimen). Max 3 FP. Conflux spells auto-heighten to half level. Casting a conflux spell recharges Spellstrike.',
  },
  // ── Level 5 ──────────────────────────────────────────────
  {
    id: 'magus-lightning-reflexes',
    name: 'Lightning Reflexes',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 5,
    description: 'Your reflexes are lightning fast. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Reflex saves: trained → expert.',
  },
  {
    id: 'magus-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 5,
    description: 'You\'ve dedicated yourself to learning the intricacies of your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to expert.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Simple/martial/unarmed: trained → expert.',
  },
  // ── Level 7 ──────────────────────────────────────────────
  {
    id: 'magus-studious-spells',
    name: 'Studious Spells',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 7,
    description: 'Your hybrid study grants you additional spells that can enhance your power in combat. You gain two special 2nd-level studious spell slots, which can be used to prepare gecko grip, sure strike, water breathing, and an additional spell depending on your hybrid study. You add any spells from this feature to your spellbook.\n\nAt 11th level, the extra slots increase to 3rd level and you add haste and an additional spell depending on your hybrid study.\nAt 13th level, the extra slots increase to 4th level and you add fly and an additional spell depending on your hybrid study.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Two special spell slots: 2nd-level at L7 (gecko grip, sure strike, water breathing + study spell), 3rd-level at L11 (haste + study spell), 4th-level at L13 (fly + study spell).',
  },
  // Weapon Specialization — shared template (Magus L7)
  createClassFeature(WEAPON_SPECIALIZATION, 'Magus', 7),
  // ── Level 9 ──────────────────────────────────────────────
  // Alertness — shared template (Magus L9)
  createClassFeature(ALERTNESS, 'Magus', 9),
  {
    id: 'magus-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 9,
    description: 'Your fundamental understanding of magic improves, making your spells harder to resist. Your proficiency ranks for arcane spell attack rolls and spell DCs increase to expert.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Arcane spell attacks/DCs: trained → expert.',
  },
  // Resolve — shared template (Magus L9)
  createClassFeature(RESOLVE, 'Magus', 9),
  // ── Level 11 ─────────────────────────────────────────────
  {
    id: 'magus-medium-armor-expertise',
    name: 'Medium Armor Expertise',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve learned to defend yourself better against incoming attacks. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Light/medium armor + unarmored: trained → expert.',
  },
  // ── Level 13 ─────────────────────────────────────────────
  {
    id: 'magus-weapon-mastery',
    name: 'Weapon Mastery',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 13,
    description: 'You fully understand your weapons. Your proficiency ranks for simple weapons, martial weapons, and unarmed attacks increase to master.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Simple/martial/unarmed: expert → master.',
  },
  // ── Level 15 ─────────────────────────────────────────────
  // Greater Weapon Specialization — shared template (Magus L15)
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Magus', 15),
  // Juggernaut — shared template (Magus L15)
  createClassFeature(JUGGERNAUT, 'Magus', 15),
  // ── Level 17 ─────────────────────────────────────────────
  {
    id: 'magus-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 17,
    description: 'You fortify your spells with masterful prowess. Your proficiency ranks for arcane spell attack rolls and spell DCs increase to master.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Arcane spell attacks/DCs: expert → master.',
  },
  {
    id: 'magus-medium-armor-mastery',
    name: 'Medium Armor Mastery',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 17,
    description: 'Your skill with light and medium armor improves, increasing your ability to avoid blows. Your proficiency ranks for light and medium armor, as well as for unarmored defense, increase to master.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Light/medium armor + unarmored: expert → master.',
  },
  // ── Level 19 ─────────────────────────────────────────────
  {
    id: 'magus-double-spellstrike',
    name: 'Double Spellstrike',
    source: 'Secrets of Magic',
    category: 'class_feature',
    level: 19,
    description: 'You can extend the magic of spells you store with Spellstrike. After you make a Spellstrike with a spell cast from a spell slot, you retain an echo of the spell, stored in your body. The next time you Spellstrike, you can cast the same spell again without expending a spell slot.\n\nIf you choose to cast a different spell with Spellstrike, or you go 1 minute without using the stored spell, the stored spell dissipates harmlessly.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'After Spellstrike with a spell slot, retain an echo. Next Spellstrike can reuse same spell free (no slot). Lost if different spell chosen or 1 minute passes.',
  },
];

// ──────────────────────────────────────────────────────────
// MAGUS SELECTABLE FEATS — PF2e Remaster (Secrets of Magic / Player Core 2)
// Sources: Secrets of Magic, Player Core, Player Core 2,
//          Tian Xia Character Guide, Rival Academies, Absalom City of Lost Omens
// ──────────────────────────────────────────────────────────

export const MAGUS_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 Feats ────────────────────────────────────
  {
    id: 'magus-arcane-fists',
    name: 'Arcane Fists',
    source: 'Secrets of Magic',
    category: 'class',
    level: 1,
    description: 'Your physical training encompasses unarmed combat forms. The damage die for your fist changes to 1d6 instead of 1d4. You don\'t take the normal –2 circumstance penalty when making a lethal attack with your fist or any other unarmed attacks. Your unarmed attacks gain the arcane trait, making them magical. At 5th level, you also gain the critical specialization effects of unarmed attacks in the brawling group and weapons in the brawling group, and the critical specialization effect uses your spell DC instead of your class DC.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'Fist damage die → 1d6. No –2 penalty for lethal unarmed. Unarmed gains arcane trait. L5: brawling critical specialization (uses spell DC).',
  },
  {
    id: 'magus-familiar',
    name: 'Familiar',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You make a pact with a creature that serves you and assists your spellcasting. You gain a familiar.',
    implemented: 'full',
    traits: ['Magus', 'Sorcerer', 'Thaumaturge', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Gain a familiar with standard familiar/master abilities.',
  },
  {
    id: 'magus-maguss-analysis',
    name: "Magus's Analysis",
    source: 'Secrets of Magic',
    category: 'class',
    level: 1,
    description: 'You make an assessment informed by your knowledge of how a creature fights. Attempt a check to Recall Knowledge about a creature. You gain a +1 circumstance bonus to your check if you previously hit the creature with a Strike this turn. If your check is successful, recharge your Spellstrike. The subject of your check is temporarily immune to Magus\'s Analysis for 1 day.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 1,
    prerequisites: ['Spellstrike'],
    mechanics: '1 action: Recall Knowledge (+1 if hit this turn). Success → recharge Spellstrike. Target immune 1 day.',
  },
  {
    id: 'magus-raise-a-tome',
    name: 'Raise a Tome',
    source: 'Secrets of Magic',
    category: 'class',
    level: 1,
    description: 'You raise up the book you\'re holding and flip it open to defend yourself and expedite your studies. The book remains raised until the start of your next turn. While you have a book raised, you gain a +2 circumstance bonus to AC and a +1 circumstance bonus to Recall Knowledge to identify creatures using a skill related to the subject of the book (Arcana if you\'re using your spellbook). This bonus is in addition to any item bonus the book normally gives to the check.\n\nIf you have Shield Block, you can use the tome for that feat (Hardness 3, HP 12, BT 6) as though it were a shield. Whenever you use an ability that allows you to Raise a Shield, such as Emergency Targe, you can Raise a Tome instead, changing any requirements that normally require a shield to apply to your book.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 1,
    mechanics: '+2 circumstance AC, +1 Recall Knowledge. If Shield Block: H3/12HP/BT6. Can substitute for Raise a Shield.',
  },
  // ── Level 2 Feats ────────────────────────────────────
  {
    id: 'magus-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'Study broadens your range of simple spells. You can prepare two additional cantrips each day.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: '+2 cantrip slots per day.',
  },
  {
    id: 'magus-convergent-tides',
    name: 'Convergent Tides',
    source: 'Rival Academies',
    category: 'class',
    level: 2,
    description: 'Your footwork is like the convergence of tides, granting your body supernatural power and fluidity. While you\'re in Arcane Cascade stance, you ignore difficult terrain caused by water, such as walking along a flooded path or swimming in rough water.',
    implemented: 'full',
    traits: ['Magus', 'Uncommon', 'Water'],
    actionCost: 'passive',
    prerequisites: ['Arcane Cascade'],
    mechanics: 'In Arcane Cascade: ignore water-caused difficult terrain.',
  },
  {
    id: 'magus-enhanced-familiar',
    name: 'Enhanced Familiar',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You infuse your familiar with additional primal energy, increasing its abilities. You can select four familiar or master abilities each day, instead of two.',
    implemented: 'full',
    traits: ['Animist', 'Druid', 'Magus', 'Sorcerer', 'Thaumaturge', 'Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['a familiar'],
    mechanics: 'Familiar/master abilities: 2 → 4 per day.',
  },
  {
    id: 'magus-expansive-spellstrike',
    name: 'Expansive Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 2,
    description: 'You can blast the energy of a spell out around the target of your attack. When you Spellstrike with a spell that has an area of a burst, cone, or line, the spell creates an area instead of affecting only the target. The target must be in the area. A burst is centered on a corner of the target\'s square; if the target is Large or larger, the burst uses the square corner closest to the center of the target. A cone or line emits from you and must include the target. The spell affects all creatures in the area as normal, but the Strike still targets only one creature.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Spellstrike'],
    mechanics: 'Spellstrike with burst/cone/line spells creates area around target instead of single-target only.',
  },
  {
    id: 'magus-force-fang',
    name: 'Force Fang',
    source: 'Secrets of Magic',
    category: 'class',
    level: 2,
    description: 'You can turn your attack into an unerring blur of force. You learn the force fang conflux spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['focus pool'],
    mechanics: 'Learn force fang conflux spell. +1 max Focus Points.',
  },
  {
    id: 'magus-spell-parry',
    name: 'Spell Parry',
    source: 'Secrets of Magic',
    category: 'class',
    level: 2,
    description: 'You infuse magical power into your body or armaments to parry both physical and magical assaults. You raise your guard, gaining a +1 circumstance bonus to AC and to saving throws against spells that target you until the start of your next turn, as long as you continue to meet the requirements.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 1,
    prerequisites: ['one or more hands free'],
    mechanics: '+1 circumstance AC and +1 saves vs spells until start of next turn. Requires free hand.',
  },
  {
    id: 'magus-spirit-sheath',
    name: 'Spirit Sheath',
    source: 'Secrets of Magic',
    category: 'class',
    level: 2,
    description: 'You\'ve magically constructed an extradimensional sheath for your weapon that you access through your clothing. This sheath is hard to notice, granting a +2 circumstance bonus to your Stealth checks to Conceal an Item within it. A spirit sheath can hold only one weapon at a time, and the weapon must be 1 Bulk or less.\n\nDuring a Spellstrike, you can Interact to draw the weapon before you Cast the Spell. You can draw or return a weapon in a spirit sheath as an Interact action. A dispel magic spell or similar effect can be used against the spirit sheath to expel the weapon (counteract check vs your spell DC, counteract level 1). The weapon is also expelled if you become unconscious.',
    implemented: 'full',
    traits: ['Arcane', 'Conjuration', 'Extradimensional', 'Magus'],
    actionCost: 'passive',
    mechanics: 'Extradimensional weapon sheath (1 weapon, ≤1 Bulk). +2 Stealth to Conceal. Draw during Spellstrike. Counteract level 1.',
  },
  // ── Level 4 Feats ────────────────────────────────────
  {
    id: 'magus-devastating-spellstrike',
    name: 'Devastating Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'Your Spellstrike sweeps are so wide and devastating, they splash onto nearby foes. Make a Spellstrike. Foes adjacent to the target take splash damage equal to 2 + the extra damage from Arcane Cascade. The damage type is the same as Arcane Cascade; if the spell already deals splash damage of the same type, combine the damage together before applying weaknesses or resistances.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 2,
    prerequisites: ['Arcane Cascade', 'inexorable iron hybrid study', 'Spellstrike'],
    mechanics: 'Spellstrike + splash to adjacent foes: 2 + Arcane Cascade extra damage, same type as Arcane Cascade.',
  },
  {
    id: 'magus-distant-waterbirds-poise',
    name: "Distant Waterbird's Poise",
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 4,
    description: 'You flow around your foe, using the magic of your attack to carry you away. You Leap, High Jump, or Long Jump, and this movement doesn\'t trigger reactions from the creature you hit. If you High Jump or Long Jump, you don\'t have to perform the initial Stride (nor do you fall if you don\'t Stride 10 feet). The lightness of your steps persists after the jump, granting you the ability to land on or walk on the surface of water or other liquids until the end of your next turn.',
    implemented: 'full',
    traits: ['Arcane', 'Magus'],
    actionCost: 'reaction',
    prerequisites: ['aloof firmament hybrid study', 'Spellstrike'],
    mechanics: 'Trigger: hit with Spellstrike. Leap/High Jump/Long Jump without reactions. No initial Stride needed. Walk on water until end of next turn.',
  },
  {
    id: 'magus-distracting-spellstrike',
    name: 'Distracting Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'You weave distracting magic with one hand to enhance your Spellstrike. Make a Spellstrike and Feint against the target of your Strike. Do this immediately before making the Strike, but after choosing your target. The Feint gains the arcane, illusion, and visual traits, and it always has the basic effects of a Feint, rather than applying any adjustments or alternate effects from other feats or abilities.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 2,
    prerequisites: ['laughing shadow hybrid study', 'Spellstrike'],
    mechanics: 'Spellstrike + Feint (arcane, illusion, visual). Requires Arcane Cascade stance and free hand.',
  },
  {
    id: 'magus-emergency-targe',
    name: 'Emergency Targe',
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'You immediately Raise a Shield or cast shield. The circumstance bonus applies to your defenses when determining the outcome of the triggering attack or spell.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'reaction',
    prerequisites: ['sparkling targe hybrid study'],
    mechanics: 'Trigger: enemy hits with melee Strike/spell attack, or you fail a save vs spell. Raise Shield or cast shield retroactively.',
  },
  {
    id: 'magus-heaven-earth-encompassing-sleeves',
    name: 'Heaven-Earth Encompassing Sleeves',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 4,
    description: 'Your magic extends to your garments. During your daily preparations, you can weave magic into a single suit of fine or high-fashioned fine clothing with long sleeves or a train, such as a robe or cloak. This clothing becomes a set of sleeves of storage, allowing you to store items in either the sleeves or the train (you choose which during daily preparations). This treatment also makes the clothing more durable; its Hardness increases by an amount equal to your level, and its Hit Points increase by an amount equal to twice your level. These benefits end if you prepare a new set of clothing, if someone else attempts to wear the clothing, or if you lose ownership of the clothing.\n\nAt 9th level, the clothing becomes greater sleeves of storage instead.',
    implemented: 'full',
    traits: ['Arcane', 'Extradimensional', 'Magus'],
    actionCost: 'passive',
    prerequisites: ['unfurling brocade hybrid study'],
    mechanics: 'Clothing → sleeves of storage. Hardness +level, HP +2×level. L9: greater sleeves of storage.',
    subChoices: { label: 'Choose storage location', options: [
      { id: 'sleeves', name: 'Sleeves', description: 'Store items in sleeves' },
      { id: 'train', name: 'Train', description: 'Store items in the train' },
    ] },
  },
  {
    id: 'magus-irezoko-tattoo',
    name: 'Irezoko Tattoo',
    source: 'Absalom, City of Lost Omens',
    category: 'class',
    level: 4,
    description: 'Your face bears an intricate magical tattoo known as the irezoko, a badge of your understanding of your chosen field of magic and a recognition of your advancement within Absalom\'s College of Mysteries. Choose a class that you are a member of that grants you access to a focus pool. Once per day, you may concentrate upon the pattern of your irezoko to recover 1 Focus Point as a three-action activity.',
    implemented: 'full',
    traits: ['Bard', 'Champion', 'Cleric', 'Druid', 'Magus', 'Monk', 'Oracle', 'Psychic', 'Ranger', 'Sorcerer', 'Summoner', 'Uncommon', 'Witch', 'Wizard'],
    actionCost: 3,
    prerequisites: ['Expert in Arcana or Expert in Occultism'],
    mechanics: 'Once per day: 3 actions to recover 1 Focus Point. Requires College of Mysteries membership.',
    subChoices: { label: 'Choose a class with focus pool', options: [
      { id: 'bard', name: 'Bard' }, { id: 'champion', name: 'Champion' }, { id: 'cleric', name: 'Cleric' },
      { id: 'druid', name: 'Druid' }, { id: 'magus', name: 'Magus' }, { id: 'monk', name: 'Monk' },
      { id: 'oracle', name: 'Oracle' }, { id: 'psychic', name: 'Psychic' }, { id: 'ranger', name: 'Ranger' },
      { id: 'sorcerer', name: 'Sorcerer' }, { id: 'summoner', name: 'Summoner' }, { id: 'witch', name: 'Witch' },
      { id: 'wizard', name: 'Wizard' },
    ] },
  },
  {
    id: 'magus-shattering-spellstrike',
    name: 'Shattering Spellstrike',
    source: 'Rival Academies',
    category: 'class',
    level: 4,
    description: 'You intentionally channel a rampaging cascade of magic through your weapon, breaking it to deal more damage. Make a Spellstrike against a target with your improvised weapon. If the attack hits, it deals an additional 2d6 force damage as your improvised weapon breaks. If the spell used with the Spellstrike wasn\'t a cantrip or focus spell, increase this additional damage by the spell\'s rank. If the item has a Hardness greater than your level, or if it\'s an artifact, cursed item, or other item that\'s difficult to break or destroy, it doesn\'t break and you don\'t deal additional damage.',
    implemented: 'full',
    traits: ['Force', 'Magus', 'Uncommon'],
    actionCost: 2,
    prerequisites: ['Resurgent Maelstrom hybrid study', 'Spellstrike'],
    mechanics: 'Spellstrike with improvised weapon. Hit: +2d6 force (+ spell rank if slotted spell). Weapon destroyed.',
  },
  {
    id: 'magus-starlit-eyes',
    name: 'Starlit Eyes',
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'Starlight shines in your sight, enhancing your perception and range. When you make a ranged Strike while in Arcane Cascade stance, you lower the DC of your flat check to target a creature that\'s concealed or hidden from you. The DC is reduced to 3 instead of 5 against a concealed creature and to 9 instead of 11 against a hidden one. When you cast shooting star and target a hidden creature, you don\'t have to attempt the flat check for targeting a hidden creature with a ranged Strike.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Arcane Cascade', 'starlit span hybrid study'],
    mechanics: 'In Arcane Cascade: concealed flat check DC 3 (not 5), hidden DC 9 (not 11). Shooting star vs hidden: no flat check.',
  },
  {
    id: 'magus-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'Confident in your technique, you don\'t easily lose your concentration when you Cast a Spell. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn\'t disrupted.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    mechanics: 'DC 15 flat check to avoid disruption from reactions while casting.',
  },
  {
    id: 'magus-strikers-scroll',
    name: "Striker's Scroll",
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'You can attach a scroll to your weapon or handwraps of mighty blows to blend its spell into an attack, carefully folding it around a part of the weapon or sealing it to the weapon\'s surface. Attaching a scroll requires using the Affix a Talisman action. You can have only one scroll affixed to a weapon at a time, and you can\'t have both a talisman and scroll attached. You can Cast the Spell from the scroll as part of a Spellstrike, assuming the spell is one you could normally use with Spellstrike. You can\'t Cast the Spell in any other way while it\'s affixed, though you can use Affix a Talisman again to remove the scroll and use it normally.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Spellstrike'],
    mechanics: 'Affix a scroll to weapon (Affix a Talisman). Cast from scroll during Spellstrike. One scroll per weapon, no talisman + scroll.',
  },
  {
    id: 'magus-student-of-the-staff',
    name: 'Student of the Staff',
    source: 'Secrets of Magic',
    category: 'class',
    level: 4,
    description: 'You\'ve studied the staff extensively to learn the hidden capabilities of your chosen weapon. When you critically succeed at an attack roll using a staff, you apply the critical specialization effect of the club group. While you\'re in Arcane Cascade stance, your staff gains the deadly d6 trait, with the damage from the deadly die being the same damage type as the extra damage from Arcane Cascade.\n\nIn addition, you can place property runes into a magic staff you prepare, even though a magic staff can\'t typically hold property runes. You must first inscribe the property runes into your spellbook, using the same process as transferring a rune. The rune takes the form of a specialized diagram in your spellbook, occupying one page. You can\'t inscribe runes that can\'t be placed on a non-magical staff, nor can you inscribe the shifting rune. When you prepare a staff, you can impart any number of property runes from your spellbook into the staff, up to the limit imposed by the staff\'s weapon potency rune.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Arcane Cascade', 'twisting tree hybrid study'],
    mechanics: 'Staff crit: club group specialization. In Arcane Cascade: staff gains deadly d6 (cascade type). Can inscribe property runes into spellbook → impart into magic staff.',
  },
  // ── Level 6 Feats ────────────────────────────────────
  {
    id: 'magus-cascade-countermeasure',
    name: 'Cascade Countermeasure',
    source: 'Secrets of Magic',
    category: 'class',
    level: 6,
    description: 'When in Arcane Cascade, you can make yourself resistant to magic. You learn the cascade countermeasure conflux spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Arcane Cascade', 'focus pool'],
    mechanics: 'Learn cascade countermeasure conflux spell. +1 max Focus Points.',
  },
  {
    id: 'magus-reactive-strike',
    name: 'Reactive Strike',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You lash out at a foe that leaves an opening. Make a melee Strike against the triggering creature. If your attack is a critical hit and the trigger was a manipulate action, you disrupt that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Barbarian', 'Champion', 'Commander', 'Exemplar', 'Guardian', 'Magus', 'Swashbuckler'],
    actionCost: 'reaction',
    mechanics: 'Trigger: creature within reach uses manipulate/move action, ranged attack, or leaves square. Melee Strike; disrupt manipulate on crit.',
  },
  {
    id: 'magus-shielded-tome',
    name: 'Shielded Tome',
    source: 'Secrets of Magic',
    category: 'class',
    level: 6,
    description: 'During your daily preparations, you can magically fuse a shield into your favorite book, where it appears as an elaborate bookmark. While the two are fused, the book shares the Hardness, Hit Points, and Broken Threshold of the shield, and it can be used to Shield Block if you have that reaction, with a requirement of "You have Raised the Tome" instead of the usual requirements. You can switch the fused item\'s form from a book to a shield with a book-shaped motif as a single action (concentrate). When the item is in book form, you can read the book and Raise the Tome, and when it\'s in shield form, you can Raise the Shield, Activate it, and gain any other benefits the shield grants. The fusion lasts until your next daily preparations.',
    implemented: 'full',
    traits: ['Arcane', 'Magus', 'Transmutation'],
    actionCost: 'passive',
    prerequisites: ['Raise a Tome'],
    mechanics: 'Fuse shield into book at daily prep. Book uses shield H/HP/BT. 1 action to switch form. Fusion lasts until next prep.',
  },
  {
    id: 'magus-surface-tension',
    name: 'Surface Tension',
    source: 'Rival Academies',
    category: 'class',
    level: 6,
    description: 'You encase the pieces of your broken weapon together with water you pull from the surrounding environment. The weapon\'s broken condition is temporarily suppressed, and the weapon deals an additional amount of bludgeoning damage equal to twice the number of weapon damage dice; this damage can\'t be changed to any other type. The weapon also gains the deadly d8 trait; if the weapon already had the deadly trait, the damage die increases by one step or to d8, whichever is higher. The first time you use this weapon to Spellstrike or get a critical success on an attack with it, the weapon is completely destroyed. If the weapon has a Hardness greater than your level, or if it\'s an artifact or cursed item, it is not destroyed, and this ability only lasts until the end of your turn.',
    implemented: 'full',
    traits: ['Magus', 'Uncommon', 'Water'],
    actionCost: 1,
    prerequisites: ['Resurgent Maelstrom hybrid study'],
    mechanics: 'Suppress broken on weapon. +2×weapon damage dice bludgeoning. Gains deadly d8. Destroyed on first Spellstrike/crit.',
  },
  // ── Level 8 Feats ────────────────────────────────────
  {
    id: 'magus-capture-magic',
    name: 'Capture Magic',
    source: 'Secrets of Magic',
    category: 'class',
    level: 8,
    description: 'When you resist a spell, you capture some of its magic for your own use. You enter your Arcane Cascade stance, using the triggering spell to determine what damage type your Arcane Cascade deals. Alternatively, if you\'re already in Arcane Cascade, you can instead amplify its effects temporarily. Until the end of your next turn, you gain a +2 status bonus to the damage from your Arcane Cascade.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'reaction',
    prerequisites: ['Arcane Cascade'],
    mechanics: 'Trigger: succeed at save vs harmful spell, or foe fails spell attack vs you. Enter Arcane Cascade (with spell\'s damage type) or +2 status to Arcane Cascade damage until end of next turn.',
  },
  {
    id: 'magus-crosscurrent-counter',
    name: 'Crosscurrent Counter',
    source: 'Rival Academies',
    category: 'class',
    level: 8,
    description: 'You counter the creature with the power of elemental water, a tendril of it encasing your limb or weapon. You attempt an Athletics check to Grapple the triggering creature, even if it\'s outside your reach or you don\'t have a free hand. If you succeed, you also remove the triggering condition, and the tendril of water pulls the creature adjacent to you before dissipating.',
    implemented: 'full',
    traits: ['Magus', 'Uncommon', 'Water'],
    actionCost: 'reaction',
    mechanics: 'Trigger: become grabbed/restrained. Grapple ignoring reach/free hand. Success: remove grab/restrain + pull adjacent.',
  },
  {
    id: 'magus-fused-staff',
    name: 'Fused Staff',
    source: 'Secrets of Magic',
    category: 'class',
    level: 8,
    description: 'When you prepare a staff, you can hold it up to a weapon to merge the two items. You can switch the fused item\'s form from the weapon to the staff or vice versa as a single action (concentrate). When the item is in staff form, you can Cast the Spells from the staff and benefit from any other abilities the staff grants. The staff and the weapon share their fundamental runes, using whichever weapon potency and whichever striking rune is higher level. They don\'t share any other runes or specific abilities.\n\nYou can Cast Spells from the staff as part of a Spellstrike even when the staff is in weapon form. Otherwise, you can\'t cast the staff\'s spells while it\'s in weapon form. The fusion lasts until your next daily preparations, though you can spend 10 minutes to separate the two items and meld the staff into a different weapon.',
    implemented: 'full',
    traits: ['Arcane', 'Magus', 'Transmutation'],
    actionCost: 'passive',
    prerequisites: ['Spellstrike'],
    mechanics: 'Merge staff + weapon at daily prep. 1 action to switch form. Share fundamental runes (higher wins). Staff spells usable in Spellstrike even in weapon form.',
  },
  {
    id: 'magus-knowledge-is-power',
    name: 'Knowledge is Power',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'Your academic knowledge about a creature allows you to subtly alter your magic to defeat them. When you critically succeed at a Recall Knowledge check about a creature, you can invoke your knowledge to make the creature take a –1 circumstance penalty to either AC and saves against the next attack you make against it, or the next spell you cast that it needs to defend against. The creature takes the same penalty to its attack or DC the next time it attacks against you or causes you to attempt a save against one of its effects. If you share this information with your allies, they gain the benefits as well. If not used, the bonuses end after 1 minute.',
    implemented: 'full',
    traits: ['Magus', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'On crit Recall Knowledge: target –1 circumstance AC/saves vs your next attack/spell. Also –1 to its next attack/DC vs you. Sharable. 1-minute expiry.',
  },
  {
    id: 'magus-runic-impression',
    name: 'Runic Impression',
    source: 'Secrets of Magic',
    category: 'class',
    level: 8,
    description: 'You can temporarily replicate the effects of a property rune for your weapon or unarmed attacks. You learn the runic impression conflux spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['focus pool'],
    mechanics: 'Learn runic impression conflux spell. +1 max Focus Points.',
  },
  {
    id: 'magus-spell-swipe',
    name: 'Spell Swipe',
    source: 'Secrets of Magic',
    category: 'class',
    level: 8,
    description: 'You attack in an arc and enact your spell against everyone you hit. Make a Spellstrike, but roll separate Strikes to attack two creatures, each of whom must be within your melee reach and adjacent to each other. If your spell could affect two or more targets, your spell affects whichever foes you hit, not just the first target; otherwise, choose one target to affect with the spell. A Spell Swipe counts as two attacks for your multiple attack penalty, but the penalty doesn\'t increase until after you make both attacks.\n\nIf you\'re using a weapon that has the sweep trait, its circumstance bonus applies against both targets. You can use this activity with only melee Strikes, even if you have the starlit span hybrid study.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 3,
    prerequisites: ['Spellstrike'],
    mechanics: 'Spellstrike vs 2 adjacent targets in melee reach. Counts as 2 attacks for MAP (applied after). Sweep applies to both.',
  },
  {
    id: 'magus-standby-spell',
    name: 'Standby Spell',
    source: 'Secrets of Magic',
    category: 'class',
    level: 8,
    description: 'You\'ve honed one spell as your favored combat technique, and you\'ve practiced it enough that you no longer need to prepare it to cast it. Choose a spell in your spellbook that you could use with Spellstrike and that has a level no higher than the highest-level magus spell slot you have. You can Cast this Spell without having it prepared ahead of time by expending a spell slot of a sufficient level to cast your chosen spell. You can change this spell whenever you add new spells to your spellbook, or by studying your spellbook for 1 hour.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Spellstrike'],
    mechanics: 'Designate one spellbook spell for Spellstrike. Cast without preparing by expending a slot. Change with 1 hour study.',
  },
  {
    id: 'magus-whirlpools-pull',
    name: "Whirlpool's Pull",
    source: 'Rival Academies',
    category: 'class',
    level: 8,
    description: 'You briefly conjure a tendril of water that allows you to grab an improvised weapon and then subsume that water to power your magic. You Interact to pick up an unattended object within 15 feet you could use as an improvised weapon and then Cast a Spell that is a cantrip or conflux spell that takes 1 action to cast.',
    implemented: 'full',
    traits: ['Concentrate', 'Magus', 'Uncommon'],
    actionCost: 1,
    prerequisites: ['Resurgent Maelstrom hybrid study'],
    mechanics: 'Interact: pick up unattended object within 15 ft as improvised weapon + cast 1-action cantrip/conflux spell.',
  },
  // ── Level 10 Feats ───────────────────────────────────
  {
    id: 'magus-cascading-ray',
    name: 'Cascading Ray',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'Magical energy spills out to extend beyond the creature you struck. The flowing energy forms a ray with a range of 60 feet from the creature you damaged. You can\'t target any of the creatures you damaged with your Spellstrike with the ray. Make a spell attack roll against the new target\'s AC, at the same multiple attack penalty as the Strike. On a hit, the target of the ray takes 1d4 damage per spell rank of the same type of energy damage the spell deals (double damage on a critical hit). If you cast the spell in your Spellstrike from a spell slot, the damage from Cascading Ray increases to 1d8 damage per spell rank. If the spell deals more than one type of energy damage, you choose only one for the ray.',
    implemented: 'full',
    traits: ['Attack', 'Magus'],
    actionCost: 1,
    prerequisites: ['Spellstrike'],
    mechanics: 'Requires: last action was successful Spellstrike dealing energy damage. 60-ft ray from target. Spell attack at same MAP. 1d4/spell rank (1d8 if from slot). Energy type matches spell.',
  },
  {
    id: 'magus-dazzling-block',
    name: 'Dazzling Block',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'When you use Shield Block, you can create a flash of brilliant, multicolored light in a 15-foot cone. Each creature in the area must attempt a Fortitude save.\n\nCritical Success: Unaffected.\nSuccess: Dazzled for 1 round.\nFailure: Blinded for 1 round and dazzled for 1 minute. Interact to rub eyes ends the blinded condition.\nCritical Failure: Blinded for 1 round and dazzled for 1 hour.',
    implemented: 'full',
    traits: ['Evocation', 'Light', 'Magus', 'Visual'],
    actionCost: 'passive',
    prerequisites: ['Arcane Cascade', 'sparkling targe hybrid study'],
    mechanics: 'On Shield Block: 15-ft cone Fort save. Fail: blinded 1 round + dazzled 1 min. Requires Arcane Cascade stance.',
  },
  {
    id: 'magus-dimensional-disappearance',
    name: 'Dimensional Disappearance',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'You take advantage of teleportation to better hide your position. When you cast dimensional assault, you\'re affected by an invisibility spell at the end of the teleport. You can choose not to make the Strike that is normally part of dimensional assault. If you do make the Strike, your invisibility ends after the Strike, as normal for invisibility.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['dimensional assault focus spell', 'laughing shadow hybrid study'],
    mechanics: 'Dimensional assault grants invisibility after teleport. Optional Strike (invisibility ends if you Strike).',
  },
  {
    id: 'magus-lunging-spellstrike',
    name: 'Lunging Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'Your spell unwinds the structure of your staff to make it exceptionally long, or even separate it into shards held together by magical power. Make a Spellstrike with a staff, with a spell that isn\'t a cantrip or focus spell. Increase the staff\'s reach by 5 feet × the spell\'s rank.',
    implemented: 'full',
    traits: ['Arcane', 'Magus', 'Transmutation'],
    actionCost: 2,
    prerequisites: ['Spellstrike', 'twisting tree hybrid study'],
    mechanics: 'Spellstrike with staff (non-cantrip/non-focus). Staff reach +5 ft × spell rank. Requires wielding a staff.',
  },
  {
    id: 'magus-maelstrom-flow',
    name: 'Maelstrom Flow',
    source: 'Rival Academies',
    category: 'class',
    level: 10,
    description: 'You pour energy into an improvised weapon, speeding its destruction to grant it power. The overloaded energy grants your improvised weapon the effect of the astral, corrosive, extending, or frost rune for 1 minute, after which the item is destroyed. If the item has a Hardness greater than your level, or if it\'s an artifact, cursed item, or other item that\'s difficult to break or destroy, it is not destroyed, and this ability only lasts until the end of your turn. This effect doesn\'t count against the number of property runes a weapon can have based on its potency rune, but a given weapon can only have one application of Maelstrom Flow at a time.',
    implemented: 'full',
    traits: ['Magus', 'Uncommon'],
    actionCost: 1,
    prerequisites: ['Resurgent Maelstrom hybrid study'],
    mechanics: 'Once per hour: improvised weapon gains astral/corrosive/extending/frost rune for 1 min then destroyed. Requires wielding improvised weapon.',
  },
  {
    id: 'magus-meteoric-spellstrike',
    name: 'Meteoric Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'A trail of energy flows from your target back to you. Make a Spellstrike with a ranged weapon or ranged unarmed attack against a target within the first range increment. The spell you cast for the Spellstrike can\'t be a cantrip or focus spell. Each creature in a line between you and the target, excluding you and the target, takes damage equal to double the spell\'s rank. Determine the damage type as described in Arcane Cascade.',
    implemented: 'full',
    traits: ['Arcane', 'Evocation', 'Magus'],
    actionCost: 2,
    prerequisites: ['Spellstrike', 'starlit span hybrid study'],
    mechanics: 'Ranged Spellstrike (non-cantrip/non-focus). Line between you and target: 2×spell rank damage (Arcane Cascade type).',
  },
  {
    id: 'magus-rapid-recharge',
    name: 'Rapid Recharge',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'You tap into an arcane trick to recover your ability to meld spells and attacks. You recharge your Spellstrike.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'free',
    prerequisites: ['Spellstrike'],
    mechanics: 'Once per day: free action to recharge Spellstrike.',
  },
  {
    id: 'magus-sustaining-steel',
    name: 'Sustaining Steel',
    source: 'Secrets of Magic',
    category: 'class',
    level: 10,
    description: 'You pull magic into your weapon, using its substance to transform the magic into restorative energy. You regain Hit Points equal to double the spell\'s rank and roll to end any persistent negative damage you have. If the spell has the void trait, any persistent negative damage you have ends automatically, and you can change the damage type from Arcane Cascade to vitality if you wish.',
    implemented: 'full',
    traits: ['Arcane', 'Healing', 'Magus', 'Necromancy', 'Positive', 'Vitality'],
    actionCost: 'free',
    prerequisites: ['Arcane Cascade', 'inexorable iron hybrid study'],
    mechanics: 'Trigger: Cast a Spell using a spell slot while in Arcane Cascade. Heal 2×spell rank HP. Roll to end persistent negative damage (auto-end if necromancy spell).',
  },
  {
    id: 'magus-unsheathing-the-sword-light',
    name: 'Unsheathing the Sword-Light',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 10,
    description: 'Honed through 10,000 battles, your sword\'s mere light can shatter ambitions and break armies. Make a melee Spellstrike with a sword, with a spell that isn\'t a cantrip or focus spell. Countless copies of your sword, made of light, fall around you, dealing damage equal to double the spell\'s rank to each creature within a 10-foot emanation of the target, excluding you and the target of the Spellstrike. The damage is of the same type dealt by your sword Strike and is treated as cold iron and silver.',
    implemented: 'full',
    traits: ['Arcane', 'Light', 'Magus'],
    actionCost: 2,
    prerequisites: ['aloof firmament hybrid study', 'Spellstrike'],
    mechanics: 'Melee Spellstrike with sword (non-cantrip/focus). 10-ft emanation: 2×spell rank damage (sword type, cold iron/silver). Requires Spellstrike charged + sword group weapon.',
  },
  {
    id: 'magus-vermilion-threads',
    name: 'Vermilion Threads',
    source: 'Tian Xia Character Guide',
    category: 'class',
    level: 10,
    description: 'Your Arcane Cascade sends threads to the four directions, creating a web of strings dyed by your skill and your enemies\' blood. The web fills a 15-foot burst centered on you and is difficult terrain. You can ignore the difficult terrain, and the strings can support your weight, allowing you to walk on them as though you were benefiting from fly. The web lasts for 1 minute but ends early if your Arcane Cascade ends or you leave the web. If you Cast a Spell from a spell slot while in the web, the strings glow red until the beginning of your next turn, dealing damage equal to the spell\'s rank to any creature other than you that moves through the web. The damage occurs at the end of the creature\'s movement, with a basic Reflex save against your spell DC.',
    implemented: 'full',
    traits: ['Arcane', 'Magus'],
    actionCost: 'reaction',
    prerequisites: ['Arcane Cascade', 'unfurling brocade hybrid study'],
    mechanics: 'Trigger: you use Arcane Cascade. 15-ft burst: difficult terrain + walk on air. 1 min. Casting from slot: web deals spell rank damage (basic Reflex) to movers.',
  },
  // ── Level 12 Feats ───────────────────────────────────
  {
    id: 'magus-conflux-focus',
    name: 'Conflux Focus',
    source: 'Secrets of Magic',
    category: 'class',
    level: 12,
    description: 'You imagine how you\'ll weave magic and combat into future battles, improving your focus. If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['conflux spells'],
    mechanics: 'Refocus recovers 2 FP if you spent ≥2 FP since last Refocus.',
  },
  {
    id: 'magus-magic-sense',
    name: 'Magic Sense',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'You have a literal sixth sense for ambient magic in your vicinity. You can sense the presence of magic auras as though you were always using a 1st-rank detect magic spell. This detects magic in your field of vision only. When you Seek, you gain the benefits of a 3rd-rank detect magic spell on things you see (in addition to the normal benefits of Seeking). You can turn this sense off and on with a free action at the start or the end of your turn.',
    implemented: 'full',
    traits: ['Arcane', 'Detection', 'Magus', 'Oracle', 'Sorcerer', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Constant 1st-rank detect magic (field of vision). Seek → 3rd-rank detect magic. Free action toggle.',
  },
  {
    id: 'magus-overwhelming-spellstrike',
    name: 'Overwhelming Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 12,
    description: 'You pierce through your foe\'s resistance. Make a Spellstrike. The spell you cast as part of the Spellstrike ignores an amount of the target\'s resistance to acid, cold, electricity, fire, or sonic damage equal to your level. This applies to all damage the spell deals, including persistent damage and damage caused by an ongoing effect of the spell. A creature\'s immunities are unaffected.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 2,
    prerequisites: ['Spellstrike'],
    mechanics: 'Spellstrike ignores resistance (acid/cold/electricity/fire/sonic) equal to your level. Applies to all spell damage including persistent.',
  },
  // ── Level 14 Feats ───────────────────────────────────
  {
    id: 'magus-arcane-shroud',
    name: 'Arcane Shroud',
    source: 'Secrets of Magic',
    category: 'class',
    level: 14,
    description: 'Your magic has a powerful aftereffect, briefly granting you a certain spell. When you take this feat, choose three of false vitality, fire shield, fleet step, flicker, invisibility, mountain resilience, and see the unseen. You use Arcane Cascade and are subject to an additional aftereffect spell of your choice from the three you selected. This aftereffect spell\'s duration lasts until the end of your next turn or its normal duration, whichever is shorter. Using Arcane Shroud again ends any existing spell you gained from Arcane Shroud.',
    implemented: 'full',
    traits: ['Concentrate', 'Magus'],
    actionCost: 1,
    prerequisites: ['Arcane Cascade', 'Spellstrike'],
    mechanics: 'Once per turn. Requires: just Cast from slot or Spellstrike from slot. Enter Arcane Cascade + gain 1 of 3 chosen aftereffect spells (duration ≤ end of next turn).',
    subChoices: { label: 'Choose a primary aftereffect spell', options: [
      { id: 'false-vitality', name: 'False Vitality', description: 'Gain temporary hit points' },
      { id: 'fire-shield', name: 'Fire Shield', description: 'Fiery aura damages attackers' },
      { id: 'fleet-step', name: 'Fleet Step', description: 'Increase your Speed' },
      { id: 'flicker', name: 'Flicker', description: 'Become concealed intermittently' },
      { id: 'invisibility', name: 'Invisibility', description: 'Become invisible' },
      { id: 'mountain-resilience', name: 'Mountain Resilience', description: 'Gain resistance to physical damage' },
      { id: 'see-the-unseen', name: 'See the Unseen', description: 'See invisible creatures' },
    ] },
  },
  {
    id: 'magus-hasted-assault',
    name: 'Hasted Assault',
    source: 'Secrets of Magic',
    category: 'class',
    level: 14,
    description: 'You can speed yourself up to move and attack more swiftly. You learn the hasted assault conflux spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['focus pool'],
    mechanics: 'Learn hasted assault conflux spell. +1 max Focus Points.',
  },
  {
    id: 'magus-preternatural-parry',
    name: 'Preternatural Parry',
    source: 'Secrets of Magic',
    category: 'class',
    level: 14,
    description: 'You snap your weapon or limb into place to ward off harm at the last second. You gain a +2 circumstance bonus to AC and saving throws against the triggering effect until the start of your next turn.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'reaction',
    prerequisites: ['Spell Parry'],
    mechanics: 'Trigger: targeted by Strike/spell attack, or about to roll save vs spell. +2 circumstance AC and saves vs triggering effect. Requires free hand.',
  },
  // ── Level 16 Feats ───────────────────────────────────
  {
    id: 'magus-dispelling-spellstrike',
    name: 'Dispelling Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 16,
    description: 'The spell you deliver tries to force out magic affecting your enemy. Make a Spellstrike. If it hits, you also attempt to counteract a single spell (of your choice) active on the target. The counteract level is half your level rounded up, and the counteract check modifier is the standard modifier for counteracting with a spell (your Intelligence modifier plus your spellcasting proficiency bonus, plus any bonuses or penalties that specifically apply to counteract checks).',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 3,
    prerequisites: ['Spellstrike'],
    mechanics: 'Spellstrike + counteract one active spell on target. Counteract level = half level (rounded up). Uses INT + spell proficiency.',
  },
  {
    id: 'magus-resounding-cascade',
    name: 'Resounding Cascade',
    source: 'Secrets of Magic',
    category: 'class',
    level: 16,
    description: 'When you enter your Arcane Cascade, you disperse the magical reinforcement to nearby allies. You grant the extra damage of Arcane Cascade in an aura affecting all allies in a 5-foot emanation. This uses only the base damage of the stance, based on the ally\'s weapon specialization; it doesn\'t use any increase you get from bonuses, the laughing shadow hybrid study, or the like. As normal for duplicate effects, multiple Arcane Cascades affecting the same creature aren\'t cumulative.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'free',
    prerequisites: ['Arcane Cascade'],
    mechanics: 'Trigger: you use Arcane Cascade. Allies in 5-ft emanation gain base Arcane Cascade damage (based on their weapon specialization). Not stackable.',
  },
  // ── Level 18 Feats ───────────────────────────────────
  {
    id: 'magus-conflux-wellspring',
    name: 'Conflux Wellspring',
    source: 'Secrets of Magic',
    category: 'class',
    level: 18,
    description: 'You\'ve achieved perfect magical and physical balance, allowing magic to flow into and through you more easily. You can recover 3 Focus Points when you Refocus instead of 1 if you have spent at least 3 Focus Points since the last time you Refocused.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Conflux Focus'],
    mechanics: 'Refocus recovers 3 FP if you spent ≥3 FP since last Refocus.',
  },
  {
    id: 'magus-versatile-spellstrike',
    name: 'Versatile Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 18,
    description: 'You can channel the entire realm of possibilities of your spellbook into an attack. Once during your daily preparations, you can use a spell slot to hold that infinite potential, rather than using it to prepare a spell. When you make a Spellstrike, you can expend this special spell slot to immediately prepare and cast a spell from your spellbook at 2 levels lower than the slot\'s level. (As normal for preparing spells, you can use a spell of an even-lower level, heightening it accordingly.) You don\'t have any spell prepared in that slot until you cast from that slot.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Spellstrike'],
    mechanics: 'Daily prep: reserve 1 spell slot. On Spellstrike: spontaneously pick any spellbook spell at slot level −2.',
  },
  // ── Level 20 Feats ───────────────────────────────────
  {
    id: 'magus-supreme-spellstrike',
    name: 'Supreme Spellstrike',
    source: 'Secrets of Magic',
    category: 'class',
    level: 20,
    description: 'You\'ve made it almost effortless to combine spells and attacks. You\'re permanently quickened. You can use your extra action only to Strike or to recharge Spellstrike.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 'passive',
    prerequisites: ['Spellstrike'],
    mechanics: 'Permanently quickened (Strike or recharge Spellstrike only).',
  },
  {
    id: 'magus-whirlwind-spell',
    name: 'Whirlwind Spell',
    source: 'Secrets of Magic',
    category: 'class',
    level: 20,
    description: 'You combine the might of a multitarget spell with a whirling flurry of attacks. You use Spellstrike, making a melee Strike against each enemy within your reach instead of against one enemy. If your spell can affect multiple targets, your spell affects all foes you hit, not just the first target, up to the spell\'s normal maximum targets. If you Strike more foes than the spell could target, choose which foes are affected by the spell. Each attack counts toward your multiple attack penalty but doesn\'t increase your penalty until you\'ve made all your attacks.\n\nIf you use Expansive Spellstrike to Spellstrike with an area spell, apply the area as described in Expansive Spellstrike, choosing one of the creatures you Strike to determine the area. If you use Expansive Spellstrike with a targeted spell, each creature you critically fail to Strike is unaffected by the spell. You can use this activity with only melee Strikes, even if you have the starlit span hybrid study.',
    implemented: 'full',
    traits: ['Magus'],
    actionCost: 3,
    prerequisites: ['Spellstrike'],
    mechanics: 'Spellstrike vs every enemy in melee reach. Spell affects all hit targets (up to max). MAP increments after all attacks. Melee only.',
  },
];
