import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION, ALERTNESS } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// MONK  –  Player Core 2 pp. 114–128
// Key: STR or DEX  |  HP: 10 + CON
// Perception: Trained → Expert (L5)
// Saves: Expert Fort / Expert Ref / Expert Will → Paths to Perfection
// Skills: 4 + INT
// Attacks: Trained simple + unarmed → Expert (L5) → Master (L13)
// Defense: Expert unarmored (no armor) → Master (L13) → Legendary (L17)
// Class DC: Trained → Expert (L9) → Master (L17)
// Qi Spells: optional focus spells (divine or occult, WIS key)
// ──────────────────────────────────────────────────────────

// ── Class Features (automatically granted) ────────────────
export const MONK_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────────
  {
    id: 'monk-flurry-of-blows',
    name: 'Flurry of Blows',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 1,
    description: 'You can attack rapidly with the Flurry of Blows action. Make two unarmed Strikes. If both hit the same creature, combine their damage for the purpose of resistances and weaknesses. Apply your multiple attack penalty to the Strikes normally. As a flourish ability, you can use Flurry of Blows only once per turn.',
    implemented: 'full',
    traits: ['Flourish', 'Monk'],
    actionCost: 1,
    mechanics: 'Two unarmed Strikes for 1 action (flourish, once per turn). Combine damage for resistances/weaknesses if both hit same target. MAP applies normally.',
  },
  {
    id: 'monk-powerful-fist',
    name: 'Powerful Fist',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 1,
    description: 'Your fists are deadly weapons. The damage die for your fist increases to 1d6 instead of 1d4. You don\'t take the normal –2 circumstance penalty when making a lethal attack with your fist or any other unarmed attacks.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Fist damage 1d4 → 1d6. No –2 penalty for lethal unarmed attacks.',
  },
  // ── Level 3 ──────────────────────────────────────────────
  {
    id: 'monk-incredible-movement',
    name: 'Incredible Movement',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 3,
    description: 'You move like the wind. You gain a +10-foot status bonus to your Speed whenever you\'re not wearing armor. The bonus increases by 5 feet for every 4 levels you have beyond 3rd.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Status bonus to Speed (no armor): +10 (L3), +15 (L7), +20 (L11), +25 (L15), +30 (L19).',
  },
  {
    id: 'monk-mystic-strikes',
    name: 'Mystic Strikes',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 3,
    description: 'Focusing your will into your physical attacks imbues them with mystical energy. Your unarmed attacks become magical, allowing them to get past resistances to non-magical attacks. However, you still need an item such as handwraps of mighty blows to gain an item bonus to attack rolls or increase your attacks\' weapon damage dice.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed attacks count as magical for overcoming resistances. Does not grant item bonuses.',
  },
  // ── Level 5 ──────────────────────────────────────────────
  // Perception Expertise — Perception to expert (L5). Uses shared ALERTNESS template.
  createClassFeature(ALERTNESS, 'Monk', 5),
  {
    id: 'monk-expert-strikes',
    name: 'Expert Strikes',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 5,
    description: 'You\'ve practiced martial arts and have now surpassed your former skill. Your proficiency ranks for unarmed attacks and simple weapons increase to expert. When you get a critical hit with an unarmed attack in the brawling group, you get its critical specialization effect.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed + simple → expert. Brawling crit spec on crits: target Fort save vs class DC or slowed 1 until end of your next turn.',
  },
  // ── Level 7 ──────────────────────────────────────────────
  {
    id: 'monk-path-to-perfection',
    name: 'Path to Perfection',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 7,
    description: 'You have progressed along your own path to enlightenment. Choose your Fortitude, Reflex, or Will saving throw. Your proficiency rank for the chosen saving throw increases to master. When you roll a success on the chosen saving throw, you get a critical success instead.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Choose one save → master. Success → critical success on that save.',
    subChoices: { label: 'Choose a saving throw', options: [
      { id: 'fortitude', name: 'Fortitude', description: 'Fortitude save increases to master' },
      { id: 'reflex', name: 'Reflex', description: 'Reflex save increases to master' },
      { id: 'will', name: 'Will', description: 'Will save increases to master' },
    ] },
  },
  // Weapon Specialization (L7). Uses shared template.
  createClassFeature(WEAPON_SPECIALIZATION, 'Monk', 7),
  // ── Level 9 ──────────────────────────────────────────────
  {
    id: 'monk-metal-strikes',
    name: 'Metal Strikes',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 9,
    description: 'You can adjust your body to strike with the mystic energy of rare metals. Your unarmed attacks are treated as cold iron and silver. This allows you to deal more damage to a variety of supernatural creatures, such as demons, devils, and fey.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed attacks count as cold iron and silver for bypassing weaknesses/resistances.',
  },
  {
    id: 'monk-monk-expertise',
    name: 'Monk Expertise',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 9,
    description: 'Your proficiency rank for your monk class DC increases to expert. If you have qi spells, your proficiency rank for spell attacks and spell DCs increases to expert.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Class DC → expert. Qi spell attacks/DCs → expert (if applicable).',
  },
  // ── Level 11 ─────────────────────────────────────────────
  {
    id: 'monk-second-path-to-perfection',
    name: 'Second Path to Perfection',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve learned to find perfection in every success. Choose a different saving throw than the one you chose for your path to perfection. Your proficiency rank for the chosen saving throw increases to master. If you roll a success with the chosen saving throw, you instead critically succeed.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Choose a second save (different from Path to Perfection) → master. Success → crit success on that save.',
    subChoices: { label: 'Choose saving throw', options: [
      { id: 'fortitude', name: 'Fortitude' },
      { id: 'reflex', name: 'Reflex' },
      { id: 'will', name: 'Will' },
    ] },
  },
  // ── Level 13 ─────────────────────────────────────────────
  {
    id: 'monk-graceful-mastery',
    name: 'Graceful Mastery',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 13,
    description: 'You move with perpetual grace, turning aside blows. Your proficiency rank for unarmored defense increases to master.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmored defense → master.',
  },
  {
    id: 'monk-master-strikes',
    name: 'Master Strikes',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve honed your body into an even deadlier weapon. Your proficiency ranks for unarmed attacks and simple weapons increase to master.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed + simple → master.',
  },
  // ── Level 15 ─────────────────────────────────────────────
  {
    id: 'monk-third-path-to-perfection',
    name: 'Third Path to Perfection',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 15,
    description: 'You have made great progress in your personal studies of enlightenment. Choose one of the saving throws you selected for path to perfection or second path to perfection. Your proficiency rank for the chosen type of save increases to legendary. When you roll a critical failure on the chosen type of save, you get a failure instead. When you roll a failure on the chosen type of save against an effect that deals damage, you take half damage.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Upgrade one previously-chosen save → legendary. Crit failure → failure. Failure vs damage → half damage.',
    subChoices: { label: 'Choose a saving throw to upgrade', options: [
      { id: 'fortitude', name: 'Fortitude', description: 'Fortitude save increases to legendary' },
      { id: 'reflex', name: 'Reflex', description: 'Reflex save increases to legendary' },
      { id: 'will', name: 'Will', description: 'Will save increases to legendary' },
    ] },
  },
  // Greater Weapon Specialization (L15). Uses shared template.
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Monk', 15),
  // ── Level 17 ─────────────────────────────────────────────
  {
    id: 'monk-adamantine-strikes',
    name: 'Adamantine Strikes',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 17,
    description: 'When you focus your will into your limbs, your blows are as unyielding as the hardest of metals. Your unarmed attacks are treated as adamantine.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed attacks count as adamantine. Stacks with cold iron + silver from Metal Strikes.',
  },
  {
    id: 'monk-graceful-legend',
    name: 'Graceful Legend',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 17,
    description: 'Your sublime movement grants you unparalleled protection and offense. Your proficiency rank for unarmored defense increases to legendary, and your proficiency rank for your monk class DC increases to master. If you have qi spells, your proficiency rank for spell attack modifiers and spell DCs increases to master.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmored defense → legendary. Class DC → master. Qi spell attacks/DCs → master (if applicable).',
  },
  // ── Level 19 ─────────────────────────────────────────────
  {
    id: 'monk-perfected-form',
    name: 'Perfected Form',
    source: 'Player Core 2',
    category: 'class_feature',
    level: 19,
    description: 'You have purged incompetence from your techniques. On your first Strike of your turn, if you roll lower than 10, you can treat the attack roll as a 10. This is a fortune effect.',
    implemented: 'full',
    traits: ['Fortune', 'Monk'],
    actionCost: 'passive',
    mechanics: 'First Strike each turn: minimum roll of 10. Fortune effect (doesn\'t stack with other fortune effects).',
  },
];

// ── Class Feats (selectable choices) ──────────────────────
export const MONK_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────────
  {
    id: 'crane-stance',
    name: 'Crane Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'Your arms flutter like a crane\'s wings. You gain a +1 circumstance bonus to AC, but the only Strikes you can make are crane wing attacks. These deal 1d6 bludgeoning damage; are in the brawling group; and have the agile, finesse, nonlethal, and unarmed traits. While in Crane Stance, reduce the DC for High Jump and Long Jump by 5, and when you Leap, you can move an additional 5 feet horizontally or 2 feet vertically.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance. +1 circumstance AC. Only crane wing attacks: 1d6 B, brawling, agile/finesse/nonlethal/unarmed. High/Long Jump DC –5, Leap +5 ft horizontal or +2 ft vertical.',
  },
  {
    id: 'dragon-stance',
    name: 'Dragon Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You enter the stance of a dragon and make powerful leg strikes like a lashing dragon\'s tail. You can make dragon tail attacks that deal 1d10 bludgeoning damage. They are in the brawling group and have the backswing, nonlethal, and unarmed traits. While in Dragon Stance, you can ignore the first square of difficult terrain while Striding.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance. Dragon tail attacks: 1d10 B, brawling, backswing/nonlethal/unarmed. Ignore first square of difficult terrain while Striding.',
  },
  {
    id: 'monastic-archer-stance',
    name: 'Monastic Archer Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You enter a specialized stance for a unique martial art centered around the use of a bow. While in this stance, the only Strikes you can make are those using longbows, shortbows, or bows with the monk trait. You can use Flurry of Blows with these bows. You can use your other monk feats or monk abilities that normally require unarmed attacks with these bows when attacking within half the first range increment (normally 50 feet for a longbow and 30 feet for a shortbow), so long as the feat or ability doesn\'t require a single, specific Strike.\n\nWhen you select this feat, you become trained in the longbow, shortbow, and any simple and martial bows with the monk trait. If you gain the expert strikes class feature, your proficiency rank for these weapons increases to expert, and if you gain the master strikes class feature, your proficiency rank for these weapons increases to master.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance. Bow-only Strikes (longbow, shortbow, monk bows). Flurry of Blows works with bows. Monk feats apply within half first range increment. Grants trained in longbow/shortbow/monk bows, scales with Expert/Master Strikes.',
  },
  {
    id: 'monastic-weaponry',
    name: 'Monastic Weaponry',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You have trained with the weaponry of your monastery or school. You gain access to uncommon weapons with the monk trait and become trained in simple and martial monk weapons. When your proficiency for unarmed attacks increases to expert or master, your proficiency rank for these weapons increases to expert or master as well. If you have familiarity with an agile or finesse weapon (such as from the Catfolk Weapon Familiarity feat), that weapon also gains the monk trait for you. You can use melee monk weapons with any of your monk feats or monk abilities that normally require unarmed attacks, though not if the feat or ability requires you to use a single specific type of attack, such as Crane Stance. If you gain the critical specialization benefit for unarmed attacks—with the expert strikes class feature, for example—you also gain it with monk weapons.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Access uncommon monk weapons, trained in simple/martial monk weapons. Proficiency scales with unarmed. Melee monk weapons count as unarmed for monk feats. Familiar agile/finesse weapons gain monk trait. Crit spec transfers to monk weapons.',
  },
  {
    id: 'mountain-stance',
    name: 'Mountain Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You enter the stance of an implacable mountain—a technique created by dwarven monks—allowing you to strike with the weight of an avalanche and block blows with your garments. The only Strikes you can make are falling stone unarmed attacks. These deal 1d8 bludgeoning damage; are in the brawling group; and have the forceful, nonlethal, and unarmed traits. While in Mountain Stance, you gain a +4 item bonus to AC and a +2 circumstance bonus to any defenses against Reposition, Shove, Trip, and other forced movement effects. You have a Dexterity modifier cap to your AC of +0, meaning you don\'t add your Dexterity to your AC, and your Speeds are all reduced by 5 feet. The item bonus to AC from Mountain Stance is cumulative with armor potency runes on your explorer\'s clothing, mystic armor, and bands of force.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance (req: unarmored, touching ground). Falling stone: 1d8 B, brawling, forceful/nonlethal/unarmed. +4 item AC, +2 circumstance vs forced movement. DEX cap +0, Speeds –5 ft. Item AC stacks with armor potency runes.',
  },
  {
    id: 'qi-spells',
    name: 'Qi Spells',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You have cultivated your qi to produce magical effects. You gain inner upheaval, qi rush, or another 1st-rank monk qi spell you have access to.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Gain 1 qi spell (inner upheaval, qi rush, or other 1st-rank). Focus pool 1 FP. Choose divine or occult tradition, trained in spell attacks/DCs (WIS key).',
    subChoices: { label: 'Choose a spell tradition', options: [
      { id: 'divine', name: 'Divine', description: 'Qi spells use the divine tradition' },
      { id: 'occult', name: 'Occult', description: 'Qi spells use the occult tradition' },
    ] },
  },
  {
    id: 'stumbling-stance',
    name: 'Stumbling Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You enter a seemingly unfocused stance that mimics the movements of the inebriated—bobbing, weaving, leaving false openings, and distracting your enemies from your true movements. While in this stance, you gain a +1 circumstance bonus to Deception checks to Feint. The only Strikes you can make are stumbling swing unarmed attacks. These deal 1d8 bludgeoning damage; are in the brawling group; and have the agile, backstabber, finesse, nonlethal, and unarmed traits. If an enemy hits you with a melee Strike while in this stance, it becomes off-guard against the next stumbling swing Strike you make against it before the end of your next turn.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    prerequisites: ['Trained in Deception'],
    mechanics: 'Stance. +1 circumstance to Feint. Stumbling swing: 1d8 B, brawling, agile/backstabber/finesse/nonlethal/unarmed. Enemy that hits you with melee becomes off-guard vs your next stumbling swing.',
  },
  {
    id: 'tiger-stance',
    name: 'Tiger Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You enter the stance of a tiger and can make tiger claw attacks. These deal 1d8 slashing damage; are in the brawling group; and have the agile, finesse, nonlethal, and unarmed traits. On a critical success with your tiger claws, if you deal damage, the target takes 1d4 persistent bleed damage. As long as your Speed is at least 20 feet while in Tiger Stance, you can Step 10 feet.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance (req: unarmored). Tiger claw: 1d8 S, brawling, agile/finesse/nonlethal/unarmed. Crit: 1d4 persistent bleed. Step 10 ft if Speed ≥ 20.',
  },
  {
    id: 'wolf-stance',
    name: 'Wolf Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You enter the stance of a wolf, low to the ground with your hands held like fangs. You can make wolf jaw unarmed attacks. These deal 1d8 piercing damage; are in the brawling group; and have the agile, backstabber, finesse, nonlethal, and unarmed traits. If you\'re flanking a target while in Wolf Stance, your wolf jaw unarmed attacks also gain the trip trait.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance (req: unarmored). Wolf jaw: 1d8 P, brawling, agile/backstabber/finesse/nonlethal/unarmed. Gain trip trait when flanking.',
  },
  // ── Level 2 ──────────────────────────────────────────────
  {
    id: 'crushing-grab',
    name: 'Crushing Grab',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'Like a powerful constrictor, you crush targets in your unyielding grasp. When you successfully Grapple a creature, you can deal bludgeoning damage to that creature equal to your Strength modifier. You can make this attack nonlethal with no penalty.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'On successful Grapple, deal bludgeoning damage equal to STR mod. Can be nonlethal.',
  },
  {
    id: 'dancing-leaf',
    name: 'Dancing Leaf',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'You are as light as a leaf on the breeze. When you Leap or succeed at a High Jump or Long Jump, increase the distance you jump by 5 feet. When calculating the damage you take from falling, don\'t count any distance fallen while you are adjacent to a wall.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Leap/Jump distance +5 ft. Ignore fall distance adjacent to a wall.',
  },
  {
    id: 'elemental-fist',
    name: 'Elemental Fist',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'You can color your qi in bright elemental energy. When you cast inner upheaval, in addition to the damage types normally available, you can deliver the extra damage with elemental magic, adding the element\'s trait and changing the damage type to the listed one: air electricity (sparking gust), earth bludgeoning (chunk of stone), fire fire (flickering flame), metal slashing (flying metal shards), water cold (wave of frigid water), or wood bludgeoning (pummeling pine cones).',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Inner Upheaval'],
    mechanics: 'When casting inner upheaval, may choose elemental damage type: air→electricity, earth→bludgeoning, fire→fire, metal→slashing, water→cold, wood→bludgeoning.',
    subChoices: { label: 'Choose an element', options: [
      { id: 'air', name: 'Air', description: 'Electricity damage' },
      { id: 'earth', name: 'Earth', description: 'Bludgeoning damage' },
      { id: 'fire', name: 'Fire', description: 'Fire damage' },
      { id: 'metal', name: 'Metal', description: 'Slashing damage' },
      { id: 'water', name: 'Water', description: 'Cold damage' },
      { id: 'wood', name: 'Wood', description: 'Bludgeoning damage' },
    ] },
  },
  {
    id: 'shooting-stars-stance',
    name: 'Shooting Stars Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'You enter a stance that lets you throw shuriken with lightning speed. While in this stance, you can use your monk feats or monk abilities that normally require unarmed attacks with shuriken instead.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    prerequisites: ['Monastic Weaponry'],
    mechanics: 'Stance. Monk feats/abilities that require unarmed attacks work with shuriken.',
  },
  {
    id: 'stunning-blows',
    name: 'Stunning Blows',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'The focused power of your flurry threatens to overwhelm your opponent. When you target the same creature with two Strikes from your Flurry of Blows, you can try to stun the creature. If either Strike hits and deals damage, the target must succeed at a Fortitude save against your class DC or be stunned 1 (or stunned 3 on a critical failure). This is an incapacitation effect.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Flurry of Blows'],
    mechanics: 'When both Flurry Strikes target same creature and either hits: target Fort save vs class DC or stunned 1 (crit fail: stunned 3). Incapacitation.',
  },
  // ── Level 4 ──────────────────────────────────────────────
  {
    id: 'cobra-stance',
    name: 'Cobra Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You enter a tightly coiled stance, with your hands poised as venomous fangs. While in this stance, the only Strikes you can make are cobra fang unarmed attacks. These deal 1d4 piercing damage; are in the brawling group; and have the agile, deadly d10, finesse, unarmed, and venomous traits. While in Cobra Stance, you gain a +1 circumstance bonus to Fortitude saves and your Fortitude DC, and you gain poison resistance equal to half your level.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance. Cobra fang: 1d4 P, brawling, agile/deadly d10/finesse/unarmed/venomous (1 persistent poison per hit). +1 circumstance Fort saves/DC, poison resistance = half level.',
  },
  {
    id: 'deflect-projectile',
    name: 'Deflect Projectile',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You gain a +4 circumstance bonus to AC against the triggering attack. If the attack misses, you have deflected it. You cannot use this feat to deflect unusually massive ranged projectiles (such as boulders or ballista bolts).',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    mechanics: 'Reaction (trigger: targeted by physical ranged attack, aware, not off-guard, free hand). +4 circumstance AC vs the attack. Cannot deflect massive projectiles.',
  },
  {
    id: 'flurry-of-maneuvers',
    name: 'Flurry of Maneuvers',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'Your flurry is a combination of maneuvers. You can replace one or both of your attacks during a Flurry of Blows with Grapples, Repositions, Shoves, or Trips.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Expert in Athletics'],
    mechanics: 'Flurry of Blows Strikes may be replaced with Grapple, Reposition, Shove, or Trip.',
  },
  {
    id: 'flying-kick',
    name: 'Flying Kick',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You launch yourself at a foe. Make a Leap or attempt a High Jump or Long Jump. At the end of the jump, if you\'re adjacent to a foe, you can immediately Strike that foe with an unarmed attack, even if the foe is in midair. You fall to the ground after the Strike. If the distance you fall is no more than the height of your jump, you land upright and take no damage.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    mechanics: 'Leap/High Jump/Long Jump + unarmed Strike if adjacent to foe at end. Fall after Strike; land upright if fall ≤ jump height.',
  },
  {
    id: 'guarded-movement',
    name: 'Guarded Movement',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'Your guard is up, even while moving. You gain a +4 circumstance bonus to AC against reactions triggered by your movement.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: '+4 circumstance AC vs reactions triggered by your movement.',
  },
  {
    id: 'harmonize-self',
    name: 'Harmonize Self',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You can restore your health by tapping into your qi. You gain the harmonize self qi spell.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain harmonize self qi spell (focus spell for self-healing).',
  },
  {
    id: 'stand-still',
    name: 'Stand Still',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You strike out when your foe tries to flee. Make a melee Strike against the triggering creature. If the attack is a critical hit and the trigger was a move action, you disrupt that action.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    mechanics: 'Reaction (trigger: creature within reach uses move action or leaves a square during one). Melee Strike vs triggering creature. Crit hit + move trigger = disrupt the action.',
  },
  // ── Level 6 ──────────────────────────────────────────────
  {
    id: 'advanced-monastic-weaponry',
    name: 'Advanced Monastic Weaponry',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'Your rigorous training regimen allows you to wield complex weaponry with ease. For the purposes of proficiency, you treat advanced monk weapons as if they were martial monk weapons.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Monastic Weaponry'],
    mechanics: 'Advanced monk weapons treated as martial for proficiency.',
  },
  {
    id: 'advanced-qi-spells',
    name: 'Advanced Qi Spells',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'Your talent at controlling your qi has reached new heights. You gain qi blast, shrink the span, or another 3rd-rank qi spell you have access to.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain 1 qi spell: qi blast, shrink the span, or other 3rd-rank monk qi spell.',
  },
  {
    id: 'align-qi',
    name: 'Align Qi',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'The power of your qi soothes your wounds and energizes you for battle. You regain Hit Points equal to your level plus your Wisdom modifier.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    prerequisites: ['Qi Spells'],
    mechanics: 'Reaction (trigger: you Cast a Spell with the monk trait, 1/hour). Heal HP = level + WIS mod.',
  },
  {
    id: 'crane-flutter',
    name: 'Crane Flutter',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You interpose your arm between yourself and your opponent. Your circumstance bonus to AC from Crane Stance increases to +3 against the triggering attack. If the attack misses you and the attacker is within your reach, you can immediately make a crane wing Strike against the attacker at a –2 penalty.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    prerequisites: ['Crane Stance'],
    mechanics: 'Reaction (trigger: targeted by observed attacker, req: in Crane Stance). AC bonus → +3 vs triggering attack. If miss and attacker in reach: crane wing Strike at –2.',
  },
  {
    id: 'dragon-roar',
    name: 'Dragon Roar',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You bellow, instilling fear in your enemies. Enemies within a 15-foot emanation must succeed at a Will save against your Intimidation DC or be frightened 1 (frightened 2 on a critical failure). When a creature frightened by the roar begins its turn adjacent to you, it can\'t reduce its frightened value below 1 on that turn. Your first attack that hits a frightened creature after you roar and before the end of your next turn gains a +4 circumstance bonus to damage. After you use Dragon Roar, you can\'t use it again for 1d4 rounds. Its effects end immediately if you leave Dragon Stance. Creatures in the area are then temporarily immune for 1 minute.',
    implemented: 'full',
    traits: ['Auditory', 'Emotion', 'Fear', 'Mental', 'Monk'],
    actionCost: 1,
    prerequisites: ['Dragon Stance'],
    mechanics: 'Req: in Dragon Stance. 15-ft emanation: enemies Will vs Intimidation DC or frightened 1 (crit fail: 2). Frightened can\'t drop below 1 if adjacent. +4 damage on first hit vs frightened. Cooldown 1d4 rounds. 1-min immunity.',
  },
  {
    id: 'mountain-stronghold',
    name: 'Mountain Stronghold',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You focus on your connection to the earth and call upon the mountain to block attacks against you. You gain a +2 circumstance bonus to AC until the beginning of your next turn.\n\nSpecial: If you have this feat, the Dexterity modifier cap to your AC while you\'re in Mountain Stance increases from +0 to +1.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 1,
    prerequisites: ['Mountain Stance'],
    mechanics: 'Req: in Mountain Stance. +2 circumstance AC until start of next turn. Special: Mountain Stance DEX cap +0 → +1.',
  },
  {
    id: 'one-inch-punch',
    name: 'One-Inch Punch',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You put all your force into a single mighty, carefully controlled blow. Make an unarmed Strike. If you spend two actions and this Strike hits, you deal an extra die of weapon damage. You can instead spend 3 actions to perform an even more powerful attack, dealing a second additional die of weapon damage on a hit. If you\'re at least 10th level, the number of additional dice you add from this feat doubles, for a total of 2 additional dice if you spend 2 actions or 4 additional dice if you spend 3 actions. If you\'re at least 18th level, the number of additional dice you add from this feat triples, for a total of 3 additional dice if you spend 2 actions or 6 additional dice if you spend 3 actions.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    prerequisites: ['Expert Strikes'],
    mechanics: '2 actions: +1 weapon die. 3 actions: +2 weapon dice. Scales: L10 doubles (2/4), L18 triples (3/6).',
  },
  {
    id: 'return-fire',
    name: 'Return Fire',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'Snatching an arrow out of the air, you instantly put it to your bow and return fire. When you successfully Deflect a Projectile that\'s an arrow, as part of that reaction you can immediately make a ranged bow Strike from your own bow by firing the arrow you deflected.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Deflect Projectile', 'Monastic Archer Stance'],
    mechanics: 'Req: in Monastic Archer Stance, wielding bow, free hand. When Deflect Projectile succeeds on an arrow, immediately make a ranged bow Strike with the deflected arrow.',
  },
  {
    id: 'stumbling-feint',
    name: 'Stumbling Feint',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You lash out confusingly, with what seems to be a weak move, but instead allows you to unleash a dangerous flurry of blows upon your unsuspecting foe. When you use Flurry of Blows, you can attempt a check to Feint as a free action just before the first Strike. On a success, instead of making the target off-guard against your next attack, they become off-guard against both attacks from the Flurry of Blows.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Stumbling Stance', 'Expert in Deception'],
    mechanics: 'Req: in Stumbling Stance. Free Feint before Flurry of Blows. On success: target off-guard vs both Flurry Strikes.',
  },
  {
    id: 'tiger-slash',
    name: 'Tiger Slash',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You make a fierce swipe with both hands. Make a tiger claw Strike. It deals two extra weapon damage dice (three extra dice if you\'re 14th level or higher), and you can push the target 5 feet away as if you had successfully Shoved them. If the attack is a critical success and deals damage, add your Strength modifier to the persistent bleed damage from your tiger claw.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    prerequisites: ['Tiger Stance'],
    mechanics: 'Req: in Tiger Stance. Tiger claw Strike +2 weapon dice (+3 at L14). Shove target 5 ft. Crit: add STR to persistent bleed.',
  },
  {
    id: 'water-step',
    name: 'Water Step',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You can Stride across liquid and surfaces that don\'t support your weight. This benefit lasts only during your movement. If you end your movement on a surface that can\'t support you, you fall in or it collapses as normal.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Stride across liquids/unsupportive surfaces during movement. Fall if ending on such a surface.',
  },
  {
    id: 'whirling-throw',
    name: 'Whirling Throw',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You propel your enemy away. Attempt an Athletics check against the foe\'s Fortitude DC. You take a –2 circumstance penalty to your check if the target is one size larger than you and a –4 circumstance penalty if it\'s larger than that. You gain a +2 circumstance bonus to your check if the target is one size smaller than you and a +4 circumstance bonus if it\'s smaller than that. Critical Success: You throw the creature any distance up to 10 feet, plus 5 feet × your Strength modifier. It takes bludgeoning damage equal to your Strength modifier plus 1d6 per 10 feet you threw it. If you threw the target at least 10 feet and into a solid obstacle, use the maximum distance to calculate damage. The creature falls prone. Success: As critical success, but the creature doesn\'t fall prone. Failure: You don\'t throw the creature. Critical Failure: You don\'t throw the creature, and it\'s no longer grabbed or restrained by you.',
    implemented: 'full',
    traits: ['Attack', 'Monk'],
    actionCost: 1,
    mechanics: 'Req: creature grabbed/restrained. Athletics vs Fort DC (size modifiers). Crit: throw 10+5×STR ft, STR+1d6/10ft damage, prone. Success: same but no prone. Fail: nothing. Crit fail: lose grab.',
  },
  {
    id: 'wolf-drag',
    name: 'Wolf Drag',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You rip your enemy off their feet. Make a wolf jaw Strike. Your wolf jaw gains the fatal d12 trait for this Strike, and if the attack succeeds, you knock the target prone.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    prerequisites: ['Wolf Stance'],
    mechanics: 'Req: in Wolf Stance. Wolf jaw Strike with fatal d12. On success: target falls prone.',
  },
  // ── Level 8 ──────────────────────────────────────────────
  {
    id: 'clinging-shadows-initiate',
    name: 'Clinging Shadows Initiate',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You learn a mystical stance that transforms your qi into sticky smoke that shrouds your limbs. You gain the clinging shadows stance qi spell. While entering the stance is a qi spell, the shadow grasp attacks it grants are not, so you can use them as often as you like while in the stance.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain clinging shadows stance qi spell (focus spell). Shadow grasp attacks are free to use while in the stance.',
  },
  {
    id: 'ironblood-stance',
    name: 'Ironblood Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You enter the stance of impenetrable iron, refusing to yield to any blow. You can make iron sweep unarmed attacks. These deal 1d8 bludgeoning damage; are in the brawling group; and have the nonlethal, parry, sweep, and unarmed traits. While in Ironblood Stance, you gain resistance 2 to all damage. The resistance increases to 3 at 12th level, to 4 at 16th level, and to 5 at 20th level.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance (req: unarmored). Iron sweep: 1d8 B, brawling, nonlethal/parry/sweep/unarmed. Resistance to all damage: 2 (L8), 3 (L12), 4 (L16), 5 (L20).',
  },
  {
    id: 'mixed-maneuver',
    name: 'Mixed Maneuver',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You leverage your knowledge of martial arts to mix different maneuvers together into a single flowing combination. Choose any two of Grapple, Reposition, Shove, and Trip. Attempt both of the attacks you chose against the same or different creatures, but don\'t apply the multiple attack penalty until after resolving both attacks.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    prerequisites: ['Master in Athletics'],
    mechanics: 'Choose 2 of Grapple/Reposition/Shove/Trip. Attempt both vs same or different targets. MAP not applied until after both resolve.',
    subChoices: { label: 'Choose two maneuvers', options: [
      { id: 'grapple-reposition', name: 'Grapple + Reposition' },
      { id: 'grapple-shove', name: 'Grapple + Shove' },
      { id: 'grapple-trip', name: 'Grapple + Trip' },
      { id: 'reposition-shove', name: 'Reposition + Shove' },
      { id: 'reposition-trip', name: 'Reposition + Trip' },
      { id: 'shove-trip', name: 'Shove + Trip' },
    ] },
  },
  {
    id: 'pinning-fire',
    name: 'Pinning Fire',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You target your opponent\'s clothing, equipment, or loose flesh with a series of piercing projectiles to pin them to the ground or a nearby surface. If both your attacks hit, the target must succeed at a Reflex save against your class DC or become immobilized until it or an adjacent creature succeeds at a DC 10 Athletics check to remove the pinning projectiles. The creature doesn\'t become stuck if it is incorporeal, is liquid (like a water elemental or some oozes), or could otherwise escape without effort.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    mechanics: 'Reaction (trigger: Flurry of Blows with 2 ranged piercing Strikes vs same target). If both hit: target Reflex vs class DC or immobilized (DC 10 Athletics to free).',
  },
  {
    id: 'projectile-snatching',
    name: 'Projectile Snatching',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You pluck missiles from the air and hurl them back at their source. When you successfully deflect an attack with Deflect Projectile, as part of that same reaction, you can then immediately make a ranged Strike against the attacker using the projectile you deflected. This is a thrown weapon with the same range increment and effect on a hit as the triggering attack.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Deflect Projectile'],
    mechanics: 'When Deflect Projectile succeeds, make a ranged Strike vs attacker with the caught projectile (same range/effect as original).',
  },
  {
    id: 'tangled-forest-stance',
    name: 'Tangled Forest Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You extend your arms like gnarled branches to interfere with your foes\' movements. You can make lashing branch unarmed attacks. These deal 1d8 slashing damage; are in the brawling group; and have the agile, finesse, nonlethal, and unarmed traits. While you\'re in Tangled Forest Stance and can act, every enemy in your reach that tries to move away from you must succeed at a Reflex save, Acrobatics check, or Athletics check against your class DC or be immobilized for that action. If you prefer, you can allow the enemy to move.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance (req: unarmored). Lashing branch: 1d8 S, brawling, agile/finesse/nonlethal/unarmed. Enemies moving away must Reflex/Acrobatics/Athletics vs class DC or immobilized.',
  },
  {
    id: 'wall-run',
    name: 'Wall Run',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You defy gravity, traversing vertical planes as easily as the ground. Stride up to your Speed. You must start your movement on a horizontal surface. During this movement, you can run up vertical surfaces, like walls, at your full Speed. If you end the Stride off the ground, you fall after taking your next action or when your turn ends, whichever comes first (though you can Grab an Edge, if applicable). If you have Water Step or a similar ability, Wall Run lets you run along flimsy vertical surfaces, as well as vertical liquids, such as a waterfall.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 1,
    mechanics: 'Stride up to Speed on vertical surfaces. Must start on horizontal. Fall after next action or turn end if off ground. Water Step combo: flimsy vertical surfaces + vertical liquids.',
  },
  {
    id: 'wild-winds-initiate',
    name: 'Wild Winds Initiate',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You learn a stance that lets you attack from a distance. You gain the wild winds stance qi spell. Though entering the stance is a qi spell, the wind crash Strikes the stance grants are not, so you can use them as often as you like while in the stance.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain wild winds stance qi spell (focus spell). Wind crash Strikes are free to use while in the stance.',
  },
  // ── Level 10 ─────────────────────────────────────────────
  {
    id: 'cobra-envenom',
    name: 'Cobra Envenom',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You slightly dislocate your joints to lash out with devious intent and the power to envenom your foe. Make a cobra fang Strike. Your reach with this Strike is 5 feet greater than normal. If this Strike hits, the persistent poison damage from your venomous trait increases to 1d4 persistent poison damage per weapon damage die.\n\nSpecial: If you have this feat, the circumstance bonus to Fortitude saves and Fortitude DC granted by Cobra Stance increases from +1 to +2.',
    implemented: 'full',
    traits: ['Monk', 'Poison'],
    actionCost: 1,
    prerequisites: ['Cobra Stance', 'Expert in unarmed attacks'],
    mechanics: 'Req: in Cobra Stance. 1/min. Cobra fang Strike with +5 ft reach. Persistent poison → 1d4/weapon die. Special: Cobra Stance Fort bonus +1 → +2.',
  },
  {
    id: 'knockback-strike',
    name: 'Knockback Strike',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You focus your strength into a blow powerful enough to push an enemy away from you. Make an unarmed Strike. If you hit, attempt an Athletics check to Shove the target. This attack uses the same multiple attack penalty as your Strike, and doesn\'t count toward your multiple attack penalty.',
    implemented: 'full',
    traits: ['Concentrate', 'Monk'],
    actionCost: 2,
    mechanics: 'Unarmed Strike + free Shove attempt on hit. Shove uses same MAP as Strike, doesn\'t increase MAP.',
  },
  {
    id: 'prevailing-position',
    name: 'Prevailing Position',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'Your flexibility with stances lets you sacrifice their benefits to better protect yourself. You leave the stance you were in, gaining a +4 circumstance bonus to the triggering saving throw or to your AC against the triggering attack.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    mechanics: 'Reaction (trigger: targeted by attack or Reflex save vs damage, req: in a stance). Leave stance → +4 circumstance to AC or save.',
  },
  {
    id: 'sleeper-hold',
    name: 'Sleeper Hold',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You pinch crucial points of your target\'s nervous system, impeding its ability to function. Attempt an Athletics check to Grapple the creature, with the following success and critical success effects instead of the usual effects. Critical Success: The target falls unconscious for 1 minute, though it remains standing and doesn\'t drop what it holds. Success: The target is clumsy 1 until the end of its next turn.',
    implemented: 'full',
    traits: ['Incapacitation', 'Monk'],
    actionCost: 1,
    mechanics: 'Req: creature grabbed/restrained. Athletics to Grapple. Crit: target unconscious 1 min (standing). Success: clumsy 1 until end of its next turn.',
  },
  {
    id: 'wind-jump',
    name: 'Wind Jump',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You gather the wind beneath you, allowing you to soar as you jump. You gain the wind jump qi spell.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain wind jump qi spell (focus spell for enhanced jumping/flight).',
  },
  {
    id: 'winding-flow',
    name: 'Winding Flow',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'Any journey consists of more than simply reaching your destination. You use two of the following actions in any order: Stand, Step, and Stride. You can\'t use the same action twice.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 1,
    mechanics: '1/round. Choose 2 different actions from Stand/Step/Stride.',
    subChoices: { label: 'Choose two actions', options: [
      { id: 'stand-step', name: 'Stand + Step' },
      { id: 'stand-stride', name: 'Stand + Stride' },
      { id: 'step-stride', name: 'Step + Stride' },
    ] },
  },
  // ── Level 12 ─────────────────────────────────────────────
  {
    id: 'disrupt-qi',
    name: 'Disrupt Qi',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You carefully target a creature\'s pressure points to block its inner life force. Make an unarmed Strike. If it deals damage to a living creature, that creature takes 2d6 persistent void damage and is enfeebled 1 until the persistent damage ends. If you\'re 18th level or higher, the persistent void damage increases to 3d6.',
    implemented: 'full',
    traits: ['Monk', 'Void'],
    actionCost: 2,
    mechanics: 'Unarmed Strike vs living creature. On damage: 2d6 persistent void (3d6 at L18) + enfeebled 1 until persistent ends.',
  },
  {
    id: 'dodging-roll',
    name: 'Dodging Roll',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You throw yourself to the side to avoid the worst of the area effect. You Step and gain resistance to all damage equal to your level against the triggering effect. If your Step moves you out of the triggering effect\'s area, this resistance is instead equal to your level plus your Dexterity modifier.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'reaction',
    prerequisites: ['Master in Acrobatics'],
    mechanics: 'Reaction (trigger: take damage from area effect allowing Reflex save). Step + resistance = level (or level + DEX if Step exits the area).',
  },
  {
    id: 'focused-shot',
    name: 'Focused Shot',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'Make a ranged weapon Strike against a target within your weapon\'s first range increment. This Strike ignores the target\'s concealed condition and all cover.',
    implemented: 'full',
    traits: ['Concentrate', 'Monk'],
    actionCost: 1,
    prerequisites: ['Monastic Archer Stance'],
    mechanics: 'Req: in Monastic Archer Stance. Ranged Strike within 1st range increment. Ignores concealed and all cover.',
  },
  {
    id: 'improved-knockback',
    name: 'Improved Knockback',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'When you successfully Shove a creature, increase both the distance you can push the creature and the distance you can move to follow along with the target by 5 feet on a success or 10 feet on a critical success. If you push the target into another creature or obstacle, they both take 1d6 bludgeoning damage per 5 feet of movement that was prevented.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Knockback Strike'],
    mechanics: 'Shove distance +5 ft (success) or +10 ft (crit). Collision: 1d6 B per 5 ft prevented to both.',
  },
  {
    id: 'meditative-focus',
    name: 'Meditative Focus',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'When you Refocus, you regain all your Focus Points instead of 1.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Refocus restores all Focus Points (not just 1).',
  },
  {
    id: 'overwhelming-breath',
    name: 'Overwhelming Breath',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'If you use your next action to Cast a Spell that has the monk trait and no duration, the spell and any Strikes you make as a result of casting it ignore an amount of the target\'s resistance to physical damage equal to your level.',
    implemented: 'full',
    traits: ['Concentrate', 'Monk', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Qi Spells'],
    mechanics: 'Spellshape: next monk spell (no duration) + its Strikes ignore physical resistance up to your level.',
  },
  {
    id: 'reflexive-stance',
    name: 'Reflexive Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'Use an action that has the stance trait.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'free',
    mechanics: 'Free action (trigger: you roll initiative). Enter any stance.',
  },
  {
    id: 'sense-ki',
    name: 'Sense Ki',
    source: 'Fists of the Ruby Phoenix',
    category: 'class',
    level: 12,
    description: 'You can read the presence of ki in your area. You gain imprecise lifesense out to a range of 30 feet.',
    implemented: 'full',
    traits: ['Uncommon', 'Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Imprecise lifesense 30 ft.',
  },
  // ── Level 14 ─────────────────────────────────────────────
  {
    id: 'form-lock',
    name: 'Form Lock',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'Attempt an Athletics check to counteract a polymorph effect currently affecting your target. If the target is somehow under the effect of multiple polymorph effects, you can choose which one to attempt to counteract; otherwise, the GM chooses randomly. If you succeed, the target reverts to its normal form and can\'t transform for the rest of the encounter. The counteract rank is half your level rounded up, and the counteract check modifier is your Athletics modifier. The target is then temporarily immune for 1 day.',
    implemented: 'full',
    traits: ['Attack', 'Monk'],
    actionCost: 1,
    mechanics: 'Req: foe grabbed/restrained. Athletics to counteract polymorph (rank = half level rounded up). Success: target reverts to normal, can\'t transform for encounter. 1-day immunity.',
  },
  {
    id: 'ironblood-surge',
    name: 'Ironblood Surge',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You gain the benefits of your iron sweep\'s parry trait (a +1 circumstance bonus to AC until the start of your next turn) and your resistance from Ironblood Stance increases to your Strength modifier (if it\'s higher) for the same duration.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 1,
    prerequisites: ['Ironblood Stance'],
    mechanics: 'Req: in Ironblood Stance. +1 circumstance AC (parry) + resistance increases to STR mod (if higher) until start of next turn.',
  },
  {
    id: 'mountain-quake',
    name: 'Mountain Quake',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You stomp, shaking the nearby ground. Creatures on the ground within a 20-foot emanation take damage equal to your Strength modifier (minimum 0), with a basic Fortitude save against your class DC. On a failure, they also fall prone. After you use this action, you can\'t use it again for 1d4 rounds.\n\nSpecial: If you have this feat, the Dexterity modifier cap to your AC while using Mountain Stance increases from +1 to +2.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 1,
    prerequisites: ['Mountain Stronghold'],
    mechanics: 'Req: in Mountain Stance. 20-ft emanation: STR mod damage, basic Fort. Fail: prone. Cooldown 1d4 rounds. Special: Mountain Stance DEX cap +1 → +2.',
  },
  {
    id: 'peerless-form',
    name: 'Peerless Form',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You cease aging, though you still die when your time is up. In addition, you gain a +2 status bonus to Fortitude and Will saving throws.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Stop aging. +2 status bonus to Fort and Will saves.',
  },
  {
    id: 'shadows-web',
    name: 'Shadow\'s Web',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You can launch a wave of shadowy qi outward from your body, damaging your opponents and potentially binding them in place. You gain the shadow\'s web qi spell.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Clinging Shadows Initiate'],
    mechanics: 'Gain shadow\'s web qi spell (focus spell, AoE shadow damage + immobilize).',
  },
  {
    id: 'tangled-forest-rake',
    name: 'Tangled Forest Rake',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'Make a lashing branch Strike. If you hit and deal damage, you can Reposition the target up to 10 feet. You can move the target through your space during this movement.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 1,
    prerequisites: ['Tangled Forest Stance'],
    mechanics: 'Req: in Tangled Forest Stance. Lashing branch Strike + Reposition 10 ft on hit (can move through your space).',
  },
  {
    id: 'whirling-blade-stance',
    name: 'Whirling Blade Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'All melee monk weapons you wield with the finesse trait gain the thrown 10 feet trait (unless they already have the thrown trait with a greater range). Once you\'ve made a thrown Strike with such a weapon, you can use the precision of your throw to make additional strikes with it, even from a distance. Start from the space of the previous Strike\'s target to determine the range increment and whether the new target has cover. At the end of your turn, the thrown weapon flies directly back to you in a straight line. If a solid barrier blocks its path, it falls to the ground after hitting the barrier.',
    implemented: 'full',
    traits: ['Monk', 'Stance'],
    actionCost: 1,
    prerequisites: ['Monastic Weaponry'],
    mechanics: 'Stance. Finesse monk weapons gain thrown 10 ft. Subsequent thrown Strikes measure range from previous target\'s space. Weapon returns at end of turn (unless blocked).',
  },
  {
    id: 'wild-winds-gust',
    name: 'Wild Winds Gust',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You build air pressure with repeated motions, before releasing an enormous crescent of rushing wind strikes. Make a wind crash Strike against each creature in your choice of a 30-foot cone or a 60-foot line. These attacks all count toward your multiple attack penalty, but the penalty doesn\'t increase until after you make all the attacks.',
    implemented: 'full',
    traits: ['Air', 'Concentrate', 'Manipulate', 'Monk'],
    actionCost: 2,
    prerequisites: ['Wild Winds Initiate'],
    mechanics: 'Req: in Wild Winds Stance. Wind crash Strike vs each creature in 30-ft cone or 60-ft line. MAP doesn\'t increase until after all attacks.',
  },
  {
    id: 'explosive-death-drop',
    name: 'Explosive Death Drop',
    source: 'PFS Guide',
    category: 'class',
    level: 14,
    description: 'You lift your enemy into the air before bringing them crashing down with a fiery detonation. Roll an Athletics check against your target\'s Fortitude DC. You take a –1 circumstance penalty to your check if the target is one size larger than you and a –3 circumstance penalty if it\'s larger than that. You gain a +1 circumstance bonus to your check if the target is one size smaller than you and a +3 circumstance bonus if it\'s smaller than that. Critical Success: The target takes 12d6 fire damage and falls prone in an unoccupied adjacent square of your choice. The target is no longer grabbed. The target and any creature adjacent to it also each take 1d6 persistent fire damage. Success: As critical success, but the target takes 6d6 fire damage instead of 12d6, and creatures don\'t take persistent fire damage. Failure: The target is no longer grabbed. Critical Failure: As failure, but you fall prone.',
    implemented: 'full',
    traits: ['Fire', 'Monk'],
    actionCost: 1,
    prerequisites: ['Blazing Talon Surge'],
    mechanics: 'Req: in Rain of Embers Stance, target grabbed/restrained. Athletics vs Fort DC (size penalties). Crit: 12d6 fire + prone + 1d6 persistent fire to adjacent. Success: 6d6 fire + prone.',
  },
  // ── Level 16 ─────────────────────────────────────────────
  {
    id: 'fuse-stance',
    name: 'Fuse Stance',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'Choose two stances you know and combine them into a single fused stance. Give your new fused stance a unique name. When you enter your fused stance, you gain all the effects of both stances, including the requirements and restrictions. If the stances both grant special attacks, you gain all those attacks. If a stance restricts you to one particular attack, you must abide by that restriction. If the fused stances have incompatible restrictions, the GM determines which apply, or determines you can\'t fuse those stances at all.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['At least two stances'],
    mechanics: 'Combine 2 known stances into one. Gain effects, attacks, and restrictions of both. GM adjudicates incompatible restrictions.',
    subChoices: { label: 'Choose a primary stance to fuse', options: [
      { id: 'crane-stance', name: 'Crane Stance' },
      { id: 'dragon-stance', name: 'Dragon Stance' },
      { id: 'gorilla-stance', name: 'Gorilla Stance' },
      { id: 'mountain-stance', name: 'Mountain Stance' },
      { id: 'stumbling-stance', name: 'Stumbling Stance' },
      { id: 'tiger-stance', name: 'Tiger Stance' },
      { id: 'wolf-stance', name: 'Wolf Stance' },
    ] },
  },
  {
    id: 'master-of-many-styles',
    name: 'Master of Many Styles',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'You use an action with the stance trait.',
    implemented: 'full',
    traits: ['Fighter', 'Monk'],
    actionCost: 'free',
    prerequisites: ['Reflexive Stance'],
    mechanics: 'Free action (trigger: your turn begins). Enter any stance.',
  },
  {
    id: 'master-qi-spells',
    name: 'Master Qi Spells',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'You gain medusa\'s wrath, touch of death, or another 8th-rank qi spell you have access to.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain 1 qi spell: medusa\'s wrath, touch of death, or other 8th-rank monk qi spell.',
  },
  {
    id: 'one-millimeter-punch',
    name: 'One-Millimeter Punch',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'When you damage a target using One-Inch Punch, you can focus your qi to send the foe flying. If you do, the target must attempt a Fortitude save against your class DC. Critical Success: The target is unaffected. Success: The target is pushed back 5 feet. Failure: The target is pushed back 10 feet. Critical Failure: The target is pushed back 10 feet for each action you spent on One-Inch Punch.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['One-Inch Punch'],
    mechanics: 'On One-Inch Punch damage: target Fort vs class DC. Success: push 5 ft. Fail: push 10 ft. Crit fail: push 10 ft per action spent.',
  },
  {
    id: 'shattering-strike',
    name: 'Shattering Strike',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'Make an unarmed Strike. It bypasses the target\'s resistances. If the target has Hardness, the Strike treats the Hardness as if it were half its value.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    mechanics: 'Unarmed Strike that bypasses all resistances. Hardness treated as half value.',
  },
  {
    id: 'flinging-blow',
    name: 'Flinging Blow',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 16,
    description: 'You take a moment to center yourself, then unleash a powerful blow that sends your target tumbling away. Make an unarmed Strike. If you hit, the target must succeed at a Fortitude save against your class DC or be pushed up to 10 feet directly away from you (or 20 feet, on a critical failure) and fall prone. If another creature or physical object would prevent this movement, both your target and the blocking creature or object take 1d6 bludgeoning damage per 5 feet of movement that was prevented.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 2,
    mechanics: 'Unarmed Strike. On hit: target Fort vs class DC or pushed 10 ft (20 ft on crit fail) + prone. Collision: 1d6 B per 5 ft prevented.',
  },
  {
    id: 'electric-counter',
    name: 'Electric Counter',
    source: 'Fists of the Ruby Phoenix',
    category: 'class',
    level: 16,
    description: 'You gain resistance to electricity equal to your level until the start of your next turn. If the triggering damage was electricity, this resistance applies to it. If the triggering damage was from a melee attack, the attacker takes 3d6 electricity damage.',
    implemented: 'full',
    traits: ['Uncommon', 'Electricity', 'Evocation', 'Monk'],
    actionCost: 'reaction',
    prerequisites: ['Wild Winds Initiate'],
    mechanics: 'Reaction (trigger: you would take damage, req: in Wild Winds Stance). Electricity resistance = level until next turn. If melee attack: attacker takes 3d6 electricity.',
  },
  // ── Level 18 ─────────────────────────────────────────────
  {
    id: 'diamond-fists',
    name: 'Diamond Fists',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'Your unarmed attacks gain the forceful and deadly d10 traits. Any that already had one or both of these traits increase their weapon damage dice by one step.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed attacks gain forceful + deadly d10. If already had either: weapon damage dice +1 step.',
  },
  {
    id: 'grandmaster-qi-spells',
    name: 'Grandmaster Qi Spells',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'You gain embrace nothingness, qi form, or another 9th-rank qi spell you have access to.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain 1 qi spell: embrace nothingness, qi form, or other 9th-rank monk qi spell.',
  },
  {
    id: 'qi-center',
    name: 'Qi Center',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'You cast a single action qi spell with the stance trait, without spending a Focus Point.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'free',
    prerequisites: ['Master of Many Styles', 'Qi Spells'],
    mechanics: 'Free action (1/min). Cast a 1-action qi stance spell without spending a Focus Point.',
  },
  {
    id: 'swift-river',
    name: 'Swift River',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'End one status penalty to your Speed, or end one immobilized or slowed condition affecting you.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'free',
    mechanics: 'Free action (trigger: your turn ends and you have status penalty to Speed or are immobilized/slowed). End one such effect.',
  },
  {
    id: 'triangle-shot',
    name: 'Triangle Shot',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'Make three ranged Strikes against a single target with the required weapon, each using your current multiple attack penalty, and you take an additional –2 penalty. This counts as two attacks when calculating your multiple attack penalty, and you combine the attacks\' damage for the purpose of resistances and weaknesses. Your Stunning Blows benefit applies to Triangle Shot, even though it isn\'t a Flurry of Blows. If all three Strikes hit, the target takes 3d6 persistent bleed damage.',
    implemented: 'full',
    traits: ['Concentrate', 'Fortune', 'Monk'],
    actionCost: 2,
    prerequisites: ['Monastic Archer Stance', 'Stunning Blows'],
    mechanics: 'Req: in Monastic Archer Stance with bow. 3 ranged Strikes vs 1 target at current MAP –2. Counts as 2 attacks for MAP. Combine damage for res/weak. Stunning Blows applies. All 3 hit: 3d6 persistent bleed.',
  },
  {
    id: 'ki-form',
    name: 'Ki Form',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 18,
    description: 'You have mastered a potent technique for using your ki to reinforce your physical form and propel yourself through the air. You gain the ki form ki spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Qi Spells'],
    mechanics: 'Gain ki form qi spell. +1 Focus Point to pool.',
  },
  {
    id: 'effortless-reach',
    name: 'Effortless Reach',
    source: 'Fists of the Ruby Phoenix',
    category: 'class',
    level: 18,
    description: 'Focusing the powers of your ki to augment your blows, you stretch and lengthen your body in ways that defy logic. Your unarmed attacks gain the reach trait.',
    implemented: 'full',
    traits: ['Uncommon', 'Monk'],
    actionCost: 'passive',
    mechanics: 'All unarmed attacks gain reach trait.',
  },
  // ── Level 20 ─────────────────────────────────────────────
  {
    id: 'enduring-quickness',
    name: 'Enduring Quickness',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'You\'re permanently quickened. You can use your extra action to Stride or Leap, or to provide one of the actions needed for a High Jump or Long Jump.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Permanently quickened. Extra action: Stride, Leap, or part of High/Long Jump.',
  },
  {
    id: 'godbreaker',
    name: 'Godbreaker',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'You hurl the creature 20 feet into the air, following behind it with a powerful jump, and then make an unarmed Strike. If successful, repeat up to two more times (20 feet up each time). If you miss any Strike, Godbreaker and the grab end, and both you and the opponent fall, taking falling damage. If all three Strikes are successful, you grab the creature and bring it crashing down, dealing your unarmed Strike damage plus falling damage. You land on your feet adjacent to the creature, take no falling damage, and the creature remains grabbed or restrained.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 3,
    prerequisites: ['Crushing Grab', 'Whirling Throw'],
    mechanics: 'Req: creature grabbed/restrained. Hurl 20 ft up + Strike, repeat up to 3 times. Miss = both fall. All 3 hit: slam down with Strike + fall damage, land safely, creature stays grabbed.',
  },
  {
    id: 'immortal-techniques',
    name: 'Immortal Techniques',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'The first time each round that you use an action that has both the monk and stance traits, you gain 20 temporary Hit Points that last until the start of your next turn.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    prerequisites: ['Master of Many Styles'],
    mechanics: 'First monk+stance action each round grants 20 temp HP until start of next turn.',
  },
  {
    id: 'impossible-technique',
    name: 'Impossible Technique',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'If the triggering effect was an enemy\'s attack hitting you, the enemy rerolls the attack roll and uses the lower result. If the triggering effect was you failing a saving throw, you reroll the saving throw and use the higher result.',
    implemented: 'full',
    traits: ['Fortune', 'Monk'],
    actionCost: 'reaction',
    mechanics: 'Reaction (trigger: enemy attack hits you or you fail a save, req: no armor, not fatigued). Enemy rerolls attack (lower) or you reroll save (higher).',
  },
  {
    id: 'lightning-qi',
    name: 'Lightning Qi',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'If your next action is to cast a qi spell that takes at least two actions to cast, reduce the number of actions to cast it by 1 (minimum 1 action).',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'free',
    prerequisites: ['Qi Spells'],
    mechanics: 'Free action (1/10 min). Next qi spell with 2+ actions: reduce by 1 action (min 1).',
  },
  {
    id: 'deadly-strikes',
    name: 'Deadly Strikes',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 20,
    description: 'You have honed your body to attack with lethal focus. Your unarmed attacks gain the deadly d10 trait, or you increase their deadly trait to d10 if the unarmed attack is already deadly with a smaller die size.',
    implemented: 'full',
    traits: ['Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed attacks gain deadly d10 (or upgrade existing deadly to d10).',
  },
  {
    id: 'golden-body',
    name: 'Golden Body',
    source: 'Age of Ashes',
    category: 'class',
    level: 20,
    description: 'You perfect your body, refining the flex of every muscle and the bend of every joint to maximum efficiency. Your unarmed Strikes gain the deadly d12 trait, and you have fast healing 20, causing you to regain 20 HP at the start of each of your turns provided you have at least 1 HP.',
    implemented: 'full',
    traits: ['Uncommon', 'Monk'],
    actionCost: 'passive',
    mechanics: 'Unarmed Strikes gain deadly d12. Fast healing 20 (regain 20 HP at start of each turn if ≥ 1 HP).',
  },
  {
    id: 'endurance-of-the-rooted-tree',
    name: 'Endurance of the Rooted Tree',
    source: 'Extinction Curse',
    category: 'class',
    level: 20,
    description: 'Just as the Vale of Aroden retains light and life despite inhospitable surroundings, you can sustain yourself regardless of your environment. You don\'t need to eat, drink, or breathe. In addition, you can cast the wholeness of body ki spell almost effortlessly. You can cast it as a free action that triggers at the start of your turn.',
    implemented: 'full',
    traits: ['Uncommon', 'Monk'],
    actionCost: 'passive',
    prerequisites: ['Wholeness of Body'],
    mechanics: 'No need to eat, drink, or breathe. Wholeness of body becomes a free action at start of turn.',
  },
  {
    id: 'vitality-manipulating-stance',
    name: 'Vitality-Manipulating Stance',
    source: 'Fists of the Ruby Phoenix',
    category: 'class',
    level: 20,
    description: 'You have learned to attack meridians and pressure points like your rival Shino Hakusa. You gain a vitality blast ranged unarmed Strike that deals 1d4 negative damage, has a range of 30 feet, and has the unarmed and versatile positive traits. Additionally, when you use Stunning Fist, instead of saving against being stunned, you can choose to have the target make a Fortitude save against your class DC with the following results. You must choose to do this before the target rolls its save. Critical Success: The target is unaffected. Success: The target\'s muscles become temporarily weaker. For 1 round, the target is enfeebled 2, and any time it attempts to take an action with the manipulate trait, the action is disrupted unless it succeeds at a flat check with a DC equal to 5 + its enfeebled value. Failure: As success, but the duration is 1 minute. Critical Failure: As success, but the duration is 1 minute, the flat check is DC 11, and the target takes a –10-foot status penalty to all Speeds for the duration.',
    implemented: 'full',
    traits: ['Uncommon', 'Monk', 'Stance'],
    actionCost: 1,
    mechanics: 'Stance. Gain vitality blast: 1d4 void ranged 30 ft, unarmed, versatile positive. Alt Stunning Fist: Fort vs class DC — fail: enfeebled 2 + manipulate disrupted (DC 5+enfeebled) for 1 round/1 min. Crit fail: 1 min, DC 11, Speeds –10.',
  },
];
