/**
 * Oracle Class Features & Feats — PF2e Remastered (Player Core 2)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=14
 *
 * Key Attribute: CHA | HP: 8 + CON
 * Perception: Trained → Expert (L11, Oracular Senses)
 * Fort: Trained → Expert (L9, Magical Fortitude)
 * Reflex: Trained → Expert (L13, Premonition's Reflexes)
 * Will: Expert → Master (L7, Mysterious Resolve, success→crit) → Legendary (L17, Greater Mysterious Resolve, crit-fail→fail, half on fail)
 * Weapons: Trained simple+unarmed → Expert (L11, Weapon Expertise)
 * Armor: Trained light+unarmored → Expert (L13, Light Armor Expertise)
 * Spellcasting: Divine spontaneous — Trained → Expert (L7) → Master (L15) → Legendary (L19)
 * Class DC: Trained
 *
 * Mysteries (Player Core 2):
 *   Ancestors — Granted Domains: Family, Death; Revelation Spells: ancestral touch, ancestral form
 *   Battle   — Granted Domains: Might, Zeal; Revelation Spells: call to arms, battlefield persistence
 *   Bones    — Granted Domains: Death, Undeath; Revelation Spells: soul siphon, armor of bones
 *   Cosmos   — Granted Domains: Darkness, Star; Revelation Spells: spray of stars, interstellar void
 *   Flames   — Granted Domains: Fire, Sun; Revelation Spells: incendiary aura, whirling flames
 *   Life     — Granted Domains: Healing, Death; Revelation Spells: life link, delay affliction
 *   Lore     — Granted Domains: Knowledge, Truth; Revelation Spells: brain drain, access lore
 *   Tempest  — Granted Domains: Air, Water; Revelation Spells: tempest touch, thunderburst
 *   Time     — Granted Domains: Time, Fate; Revelation Spells: temporal distortion, time skip
 *
 * Cursebound Mechanic:
 *   Maximum cursebound 2 (L1–10), cursebound 3 (L11–16, Major Curse), cursebound 4 (L17+, Extreme Curse)
 *   Removed by Refocusing (also restores 1 Focus Point)
 *
 * Class features: 20 (L1–L19)
 * Class feats: 61 (L1–L20)
 */

import type { FeatEntry } from './featTypes';
import { WEAPON_SPECIALIZATION, createClassFeature } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// ORACLE CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const ORACLE_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'oracle-divine-spellcasting',
    name: 'Oracle Spellcasting',
    source: 'Oracle',
    category: 'class_feature',
    level: 1,
    description: 'You have an unfiltered connection to the great powers of the universe and the planes beyond, and you can let this power spill forth in the form of divine magic. You are a spellcaster, and you can cast spells of the divine tradition using the Cast a Spell activity. As an oracle, when you cast spells, your incantations may spill from your lips rapidly as you speak in tongues or intone in a voice not quite your own, and your gestures might be wild and unrestrained as religious ecstasy briefly touches your mind. Each day, you can cast up to three 1st-rank spells. You must know spells to cast them, and you learn them via the spell repertoire class feature. The number of spells you can cast each day is called your spell slots. Your proficiency rank for divine spell attack modifiers and spell DCs is trained.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-spell-repertoire',
    name: 'Spell Repertoire',
    source: 'Oracle',
    category: 'class_feature',
    level: 1,
    description: 'The collection of spells you can cast is called your spell repertoire. At 1st level, you learn two 1st-rank divine spells of your choice and five divine cantrips of your choice. You choose these from the common spells on the divine list or from other divine spells to which you have access. You can cast any spell in your spell repertoire by using a spell slot of an appropriate spell rank. You add to this spell repertoire as you increase in level. Each time you get a spell slot, you add a spell to your spell repertoire of the same rank. At 2nd level, you select another 1st-rank spell; at 3rd level, you select two 2nd-rank spells, and so on. When you add spells, you might add a higher-rank version of a spell you already have, so you can cast a heightened version of that spell. As you gain new spells in your repertoire, you might want to replace some of the spells you previously learned. Each time you gain a level and learn new spells, you can swap out one of your old spells for a different spell of the same rank. This spell can be a cantrip. You can also swap out spells by retraining during downtime.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-mystery',
    name: 'Mystery',
    source: 'Oracle',
    category: 'class_feature',
    level: 1,
    description: 'An oracle wields divine power, but not from a single divine being. This power could come from a potent concept or ideal, the attention of multiple divine entities whose areas of concern all touch on that subject, or a direct and dangerous conduit to raw divine power. This is the oracle\'s mystery, a source of divine magic not beholden to any deity. Choose the mystery that empowers your magic. Your mystery grants you additional spells, and special focus spells called revelation spells. Your mystery also gives you a unique cursebound ability that lets you draw upon the divine, as well as dictating the effects of the oracular curse that falls upon you when you touch too much of this power. Available Mysteries: Ancestors, Battle, Bones, Cosmos, Flames, Life, Lore, Tempest, Time.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    subChoices: { label: 'Choose a mystery', options: [
      { id: 'ancestors', name: 'Ancestors', description: 'Spirits of the past guide you; spirit magic' },
      { id: 'battle', name: 'Battle', description: 'Martial prowess and combat magic' },
      { id: 'bones', name: 'Bones', description: 'Death, undead, and necromancy' },
      { id: 'cosmos', name: 'Cosmos', description: 'Celestial bodies and cosmic forces' },
      { id: 'flames', name: 'Flames', description: 'Fire and destruction' },
      { id: 'life', name: 'Life', description: 'Healing and vitality' },
      { id: 'lore', name: 'Lore', description: 'Knowledge and divination' },
      { id: 'tempest', name: 'Tempest', description: 'Storms, lightning, and weather' },
      { id: 'time', name: 'Time', description: 'Temporal manipulation' },
    ] },
  },
  {
    id: 'oracle-revelation-spells',
    name: 'Revelation Spells',
    source: 'Oracle',
    category: 'class_feature',
    level: 1,
    description: 'The powers of your mystery manifest in the form of revelation spells, a type of focus spell. It costs 1 Focus Point to cast a focus spell. You refill your focus pool during your daily preparations, and you can regain 1 Focus Point by spending 10 minutes using the Refocus activity to search for omens in a way befitting your mystery. Focus spells are automatically heightened to half your level rounded up, much like cantrips. Focus spells don\'t require spell slots, and you can\'t cast them using spell slots. The maximum Focus Points your focus pool can hold is equal to the number of focus spells you have, but it can never be more than 3 points. You learn a revelation spell at 1st level and start with a focus pool of 1 Focus Point. This spell is an initial revelation spell determined by your mystery.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-oracular-curse',
    name: 'Oracular Curse',
    source: 'Oracle',
    category: 'class_feature',
    level: 1,
    description: 'As an oracle, you can tap into the pure and unmitigated divine power of creation to supplement your spellcasting via cursebound abilities. These abilities grant you special benefits, but the backlash of letting this power into your mortal body manifests as an oracular curse. The more cursebound abilities you use, the more your curse worsens, but you might gain divine benefits even as it tightens its grip on your soul. Your oracular curse is expressed using the cursebound condition, a unique condition that affects only oracles. Immediately after the first time you use a cursebound ability, you become cursebound 1, and if you use a cursebound ability while you are already cursebound, you increase the value of your cursebound condition by 1 after the ability resolves. At lower levels, you can tolerate only a modest amount of divine power, and your cursebound condition can\'t increase beyond cursebound 2. You remain cursebound until you Refocus, which reduces your cursebound condition by 1 in addition to restoring a Focus Point. You cannot mitigate, reduce, or remove the effects of your curse or any ability with the cursebound trait by any means other than Refocusing. At 1st level, you gain a cursebound oracle feat determined by your mystery.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Cursebound progression: max cursebound 2 (L1–10), max cursebound 3 (L11–16 via Major Curse), max cursebound 4 (L17+ via Extreme Curse). Removed only by Refocusing.',
  },
  // ── Level 3 ──
  {
    id: 'oracle-signature-spells',
    name: 'Signature Spells',
    source: 'Oracle',
    category: 'class_feature',
    level: 3,
    description: 'Experience enables you to cast some spells more flexibly. For each spell rank you have access to, choose one spell of that rank to be a signature spell. You don\'t need to learn heightened versions of signature spells separately; instead, you can heighten these spells freely. If you\'ve learned a signature spell at a higher rank than its minimum, you can also cast all its lower-rank versions without learning those separately. If you swap out a signature spell, you can replace it with any spell you could have chosen when you first selected it (i.e., of the same spell rank or lower). You can also retrain specifically to change a signature spell to a different spell of that rank without swapping any spells; this takes as much time as retraining a spell normally does.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  // ── Level 7 ──
  {
    id: 'oracle-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Oracle',
    category: 'class_feature',
    level: 7,
    description: 'The intricacy of your divine power has grown clearer over time. Your proficiency ranks for spell attack modifier and spell DC increase to expert.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-mysterious-resolve',
    name: 'Mysterious Resolve',
    source: 'Oracle',
    category: 'class_feature',
    level: 7,
    description: 'The power of your mystery blazing in your soul makes it harder for other powers to grip your mind. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Will saves: expert → master. Success on Will saves → critical success.',
  },
  // ── Level 9 ──
  {
    id: 'oracle-magical-fortitude',
    name: 'Magical Fortitude',
    source: 'Oracle',
    category: 'class_feature',
    level: 9,
    description: 'Magical power has improved your body\'s resiliency. Your proficiency rank for Fortitude saves increases to expert.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  // ── Level 11 ──
  {
    id: 'oracle-divine-access',
    name: 'Divine Access',
    source: 'Oracle',
    category: 'class_feature',
    level: 11,
    description: 'Your mystery offers you strange access to spells typically reserved for more conventional worshippers. Choose one deity who grants one of your mystery\'s granted domains. Add up to three cleric spells of your choice granted by that deity to your spell list, and to your spell repertoire as soon as you can cast spells of the appropriate rank.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-major-curse',
    name: 'Major Curse',
    source: 'Oracle',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve learned to better tolerate the conflicting powers wreaking havoc on your body. The maximum cursebound value you can have increases from cursebound 2 to cursebound 3.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Maximum cursebound value: 2 → 3.',
  },
  {
    id: 'oracle-oracular-senses',
    name: 'Oracular Senses',
    source: 'Oracle',
    category: 'class_feature',
    level: 11,
    description: 'You have always been able to sense a bit more than others. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Oracle',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve dedicated yourself to learning the intricacies of your weapons. Your proficiency ranks for simple weapons and unarmed attacks increase to expert.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  // ── Level 13 ──
  {
    id: 'oracle-light-armor-expertise',
    name: 'Light Armor Expertise',
    source: 'Oracle',
    category: 'class_feature',
    level: 13,
    description: 'You\'ve learned how to dodge while wearing light or no armor. Your proficiency rank for light armor and unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-premonitions-reflexes',
    name: 'Premonition\'s Reflexes',
    source: 'Oracle',
    category: 'class_feature',
    level: 13,
    description: 'A chill runs through your spine as danger strikes, giving you a hair\'s more time to dodge or cover yourself. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Oracle', 13),
  // ── Level 15 ──
  {
    id: 'oracle-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Oracle',
    category: 'class_feature',
    level: 15,
    description: 'You truly understand the deep and complex divine power within your mystery. Your proficiency ranks for spell attack modifiers and spell DCs increase to master.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  // ── Level 17 ──
  {
    id: 'oracle-extreme-curse',
    name: 'Extreme Curse',
    source: 'Oracle',
    category: 'class_feature',
    level: 17,
    description: 'You have mastered a precarious balance between the conflicting divine powers of your mystery, allowing you to tolerate a perilous degree of divine curse. The maximum cursebound value you can have increases from cursebound 3 to cursebound 4.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Maximum cursebound value: 3 → 4.',
  },
  {
    id: 'oracle-greater-mysterious-resolve',
    name: 'Greater Mysterious Resolve',
    source: 'Oracle',
    category: 'class_feature',
    level: 17,
    description: 'Your time spent in contemplation of the mysteries of creation has given you a powerful mind and soul. Your proficiency rank for Will saves increases to legendary. When you roll a success on a Will save, you get a critical success instead. When you roll a critical failure on a Will save, you get a failure instead. When you fail a Will save against a damaging effect, you take half damage.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Will saves: master → legendary. Success → critical success. Critical failure → failure. Half damage on failed Will saves.',
  },
  // ── Level 19 ──
  {
    id: 'oracle-legendary-spellcaster',
    name: 'Legendary Spellcaster',
    source: 'Oracle',
    category: 'class_feature',
    level: 19,
    description: 'You can harness divine power at a level few others can match. Your proficiency ranks for spell attack modifiers and spell DCs increase to legendary.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-oracular-clarity',
    name: 'Oracular Clarity',
    source: 'Oracle',
    category: 'class_feature',
    level: 19,
    description: 'You now fully grasp the nature of the divine power behind your mystery, allowing you to work magic akin to miracles. Add two common 10th-rank divine spells to your repertoire. You gain a single 10th-rank spell slot you can use to cast one of those two spells using oracle spellcasting. You don\'t gain more 10th-rank spells as you level up, unlike other spell slots, and you can\'t use 10th-rank slots with abilities that give you more spell slots or that let you cast spells without expending spell slots. You can take the Oracular Providence feat to gain a second slot.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
  },
];

// ──────────────────────────────────────────────────────────
// ORACLE CLASS FEATS (Selectable)
// ──────────────────────────────────────────────────────────

export const ORACLE_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ── (8 feats)
  {
    id: 'oracle-foretell-harm',
    name: 'Foretell Harm',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'Your magic echoes ominously as you glimpse injury in the target\'s future. At the beginning of your target\'s next turn, it takes damage equal to twice the triggering spell\'s rank as a seemingly random and minor misfortune finds it. The damage and type of misfortune is of a type matching the spell; for instance, if you dealt fire damage, a flame might spontaneously ignite on them or they might burn a hand on their torch. The target is then temporarily immune to Foretell Harm for 24 hours.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 'free',
    prerequisites: ['Your previous action was to Cast a non-cantrip Spell that dealt damage'],
    mechanics: 'Frequency: once per round. Damage equal to 2 × spell rank at start of target\'s next turn, matching spell damage type. Target then immune 24 hours.',
  },
  {
    id: 'oracle-glean-lore',
    name: 'Glean Lore',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You tap into the collected lore of the divine, accessing a variety of potentially useful information. Attempt a Religion check to understand the information you gain. The GM sets the DC (similar to the DC to Recall Knowledge), potentially adjusting the DC of the check for topics far removed from your mystery. Critical Success: You comprehend the lore accurately or gain a useful clue from the divine about your situation. Success: You learn two pieces of information about the topic, one true and one erroneous, but you don\'t know which is which. Failure: You recall incorrect information or gain an erroneous or misleading clue. Critical Failure: You recall two pieces of incorrect information or gain two erroneous or misleading clues.',
    implemented: 'full',
    traits: ['Divine', 'Oracle', 'Secret'],
    actionCost: 1,
  },
  {
    id: 'oracle-nudge-the-scales',
    name: 'Nudge the Scales',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You lay a finger on the scales of life and death to heal a creature, regardless of whether it\'s living or undead. You restore Hit Points equal to 2 + double your level to one creature within 30 feet. In addition, you can mediate during your daily preparations to place yourself on one side of the scales. Choose life or death. If you align yourself with life, you are healed by vitality healing effects, as normal for most living creatures; if you align yourself with death, you gain the void healing ability, causing you to be healed by void effects that restore Hit Points and any other effects that restore Hit Points to undead creatures.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Healing', 'Oracle', 'Spirit'],
    actionCost: 1,
    mechanics: 'Heals 2 + (2 × level) HP to one creature within 30 feet. During daily preparations, choose life (healed by vitality) or death (void healing).',
    subChoices: { label: 'Choose healing type', options: [
      { id: 'life', name: 'Life (Vitality)', description: 'Healed by vitality energy' },
      { id: 'death', name: 'Death (Void)', description: 'Void healing' },
    ] },
  },
  {
    id: 'oracle-oracular-warning-l1',
    name: 'Oracular Warning',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You have a premonition about impending danger that you use to warn your allies. Each ally within 20 feet gains a +2 status bonus to their initiative roll and gains temporary Hit Points equal to half your level, which last for 1 minute. If you are cursebound 2 when you use Oracular Warning, the bonus increases to +3, and if you are cursebound 3, the bonus increases to +4.',
    implemented: 'full',
    traits: ['Auditory', 'Cursebound', 'Divine', 'Emotion', 'Mental', 'Oracle'],
    actionCost: 'free',
    prerequisites: ['Trigger: You are about to roll for initiative'],
    mechanics: 'Allies within 20 ft: +2 status to initiative + temp HP = half level (1 min). Cursebound 2: +3 bonus. Cursebound 3: +4 bonus.',
  },
  {
    id: 'oracle-reach-spell',
    name: 'Reach Spell',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You can extend your spells\' range. If the next action you use is to Cast a Spell that has a range, increase that spell\'s range by 30 feet. As is standard for increasing spell ranges, if the spell normally has a range of touch, you extend its range to 30 feet.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Concentrate', 'Druid', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  {
    id: 'oracle-trance-of-celerity',
    name: 'Trance of Celerity',
    source: 'Dark Archive',
    category: 'class',
    level: 1,
    description: 'Your feet move faster, almost out of your conscious control. You gain a +5-foot status bonus to your Speeds for 1 minute. If you become cursebound 2 at any point during this duration, the bonus increases to a +10-foot status bonus. If you become cursebound 3, this bonus increases to +15-foot status bonus instead. If you become cursebound 4, this bonus increases to a +20-foot status bonus.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 1,
    mechanics: 'Speed bonus (1 min): +5 ft base, +10 ft at cursebound 2, +15 ft at cursebound 3, +20 ft at cursebound 4.',
  },
  {
    id: 'oracle-whispers-of-weakness',
    name: 'Whispers of Weakness',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'Voices whisper to you how to best lay a creature low. You target one creature within 60 feet; if it has any weaknesses, you learn them, as well as which of its saving throw modifiers is lowest. You also come to understand its movements, gaining a +2 status bonus to your next attack roll (or skill check made as part of an attack action) against that foe before the end of your turn. The target is then temporarily immune for 1 day.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 1,
    mechanics: 'Target within 60 ft: learn weaknesses and lowest save. +2 status to next attack/skill check vs target this turn. Immune 1 day.',
  },
  {
    id: 'oracle-widen-spell',
    name: 'Widen Spell',
    source: 'Player Core 2',
    category: 'class',
    level: 1,
    description: 'You manipulate the energy of your spell, causing it to spread out and affect a wider area. If the next action you use is to Cast a Spell that has an area of a burst, cone, or line and does not have a duration, increase the area of that spell. Add 5 feet to the radius of a burst that normally has a radius of at least 10 feet (a burst with a smaller radius is not affected). Add 5 feet to the length of a cone or line that is normally 15 feet long or smaller, and add 10 feet to the length of a larger cone or line.',
    implemented: 'full',
    traits: ['Druid', 'Manipulate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  // ── Level 2 ── (4 feats)
  {
    id: 'oracle-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'Study broadens your range of simple spells. You add two additional cantrips from the divine spell list to your spell repertoire.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
  },
  {
    id: 'oracle-divine-aegis',
    name: 'Divine Aegis',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'A barrier offers protection against other magic but leaves you exposed to divine energy. Until the beginning of your next turn, you gain a +1 circumstance bonus to saving throws against nondivine magical effects, but you also take a –1 circumstance penalty to saves against divine effects.',
    implemented: 'full',
    traits: ['Divine', 'Oracle'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: You attempt a saving throw against a magical effect, but you haven\'t rolled yet'],
    mechanics: '+1 circumstance to saves vs nondivine magic, –1 circumstance to saves vs divine effects, until start of next turn.',
  },
  {
    id: 'oracle-domain-acumen',
    name: 'Domain Acumen',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'Every oracle\'s mystery touches on a divine domain of the deities that fuel it; you can access that power. Choose one of the domains associated with your mystery for which you don\'t already have an initial domain spell. You gain an initial domain spell from that domain, which you cast as a revelation spell.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Gain initial domain spell from a mystery-associated domain as a revelation spell. Can select multiple times with different domains.',
    subChoices: { label: 'Choose a domain', options: [
      { id: 'ambition', name: 'Ambition', description: 'Ambitious Backdraft initial spell' },
      { id: 'change', name: 'Change', description: 'Adapt Self initial spell' },
      { id: 'cities', name: 'Cities', description: 'Face in the Crowd initial spell' },
      { id: 'creation', name: 'Creation', description: 'Splash of Art initial spell' },
      { id: 'darkness', name: 'Darkness', description: 'Cloak of Shadow initial spell' },
      { id: 'death', name: 'Death', description: 'Death\'s Call initial spell' },
      { id: 'destruction', name: 'Destruction', description: 'Cry of Destruction initial spell' },
      { id: 'dust', name: 'Dust', description: 'Parch initial spell' },
      { id: 'earth', name: 'Earth', description: 'Hurtling Stone initial spell' },
      { id: 'family', name: 'Family', description: 'Soothing Words initial spell' },
      { id: 'fate', name: 'Fate', description: 'Read Fate initial spell' },
      { id: 'fire', name: 'Fire', description: 'Fire Ray initial spell' },
      { id: 'healing', name: 'Healing', description: 'Healer\'s Blessing initial spell' },
      { id: 'knowledge', name: 'Knowledge', description: 'Scholarly Recollection initial spell' },
      { id: 'moon', name: 'Moon', description: 'Moonbeam initial spell' },
      { id: 'nature', name: 'Nature', description: 'Vibrant Thorns initial spell' },
      { id: 'sun', name: 'Sun', description: 'Dazzling Flash initial spell' },
      { id: 'time', name: 'Time', description: 'Delay Consequence initial spell' },
      { id: 'undeath', name: 'Undeath', description: 'Touch of Undeath initial spell' },
      { id: 'water', name: 'Water', description: 'Tidal Surge initial spell' },
    ] },
  },
  {
    id: 'oracle-meddling-futures',
    name: 'Meddling Futures',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'You open yourself to the guidance of whatever spirits or powers deign to help you. Roll 1d4 to see what type of spirit is drawn to you. Your next action must be the type of action the spirit prefers, but you also gain the listed benefit for the action as the spirit guides you. If you attempt to use a different action, you must succeed at a DC 6 flat check or the action is lost. 1 Warrior: You must attempt a Strike. You gain a +1 status bonus to your attack roll and a +2 status bonus to damage, or a +6 status bonus to damage if you are at least cursebound 3. 2 Adept: You must attempt a Perception check or a skill action. You gain a +1 status bonus to the check, or a +2 status bonus if you are cursebound 3. 3 Sage: You must attempt to Cast a Spell. You gain a status bonus to the spell\'s damage or healing equal to the spell\'s rank, or equal to the spell\'s rank + 3 if you are at least cursebound 3. 4 Wanderer: You must attempt a Stride action, or a Fly, Climb, or Burrow action if you have the relevant speed. You gain a +10-foot status bonus to your Speed for the action, or a +20-foot status bonus if you are at least cursebound 3.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 'free',
    mechanics: 'Roll 1d4: 1 (Warrior) Strike +1/+2 or +6 dmg; 2 (Adept) skill +1 or +2; 3 (Sage) spell +rank or +rank+3 dmg/heal; 4 (Wanderer) Stride +10 or +20 ft. DC 6 flat check if different action.',
  },
  // ── Level 4 ── (9 feats)
  {
    id: 'oracle-bespell-strikes',
    name: 'Bespell Strikes',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You siphon spell energy into one weapon you\'re wielding, or into one of your unarmed attacks. Until the end of your turn, the weapon or unarmed attack deals an extra 1d6 force damage and gains the divine trait if it didn\'t have it already. If the spell dealt a different type of damage, the Strike deals this type of damage instead (or one type of your choice if the spell could deal multiple types of damage).',
    implemented: 'full',
    traits: ['Oracle', 'Sorcerer', 'Wizard'],
    actionCost: 'free',
    prerequisites: ['Your most recent action was to cast a non-cantrip spell'],
    mechanics: 'Frequency: once per turn. +1d6 force (or spell damage type) to weapon/unarmed until end of turn. Gains divine trait.',
  },
  {
    id: 'oracle-divine-access-feat',
    name: 'Divine Access',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 4,
    description: 'Your ability to tap into divine magic surpasses the spells traditionally available to you (the divine spell list). Choose one deity who grants one of your mystery\'s granted domains. Add up to three cleric spells of your choice granted by that deity to your spell list. You can select from these spells when you add or swap spells in your spell repertoire.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Choose deity with matching mystery domain. Add up to 3 cleric spells from that deity to spell list. Can select multiple times (different domains or deities).',
  },
  {
    id: 'oracle-irezoko-tattoo',
    name: 'Irezoko Tattoo',
    source: 'Absalom, City of Lost Omens',
    category: 'class',
    level: 4,
    description: 'Your face bears an intricate magical tattoo known as the irezoko, a badge of your understanding of your chosen field of magic and a recognition of your advancement within Absalom\'s College of Mysteries. Choose a class that you are a member of that grants you access to a focus pool. When you take this feat, it gains the trait that applies to your chosen class. Once per day, you may concentrate upon the pattern of your irezoko to recover 1 Focus Point as a three-action activity.',
    implemented: 'full',
    traits: ['Bard', 'Champion', 'Cleric', 'Druid', 'Magus', 'Monk', 'Oracle', 'Psychic', 'Ranger', 'Sorcerer', 'Summoner', 'Uncommon', 'Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['Expert in Arcana or Expert in Occultism', 'Access: Member of the College of Mysteries'],
    mechanics: 'Once per day, 3-action activity to recover 1 Focus Point.',
    subChoices: { label: 'Choose a class with focus pool', options: [
      { id: 'bard', name: 'Bard' }, { id: 'champion', name: 'Champion' }, { id: 'cleric', name: 'Cleric' },
      { id: 'druid', name: 'Druid' }, { id: 'magus', name: 'Magus' }, { id: 'monk', name: 'Monk' },
      { id: 'oracle', name: 'Oracle' }, { id: 'psychic', name: 'Psychic' }, { id: 'ranger', name: 'Ranger' },
      { id: 'sorcerer', name: 'Sorcerer' }, { id: 'summoner', name: 'Summoner' }, { id: 'witch', name: 'Witch' },
      { id: 'wizard', name: 'Wizard' },
    ] },
  },
  {
    id: 'oracle-knowledge-of-shapes',
    name: 'Knowledge of Shapes',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'Inspiration lets you surpass your preconceptions of your spells\' limits. You use Reach Spell or Widen Spell as a free action.',
    implemented: 'full',
    traits: ['Cursebound', 'Oracle', 'Spellshape'],
    actionCost: 'free',
    prerequisites: ['Reach Spell or Widen Spell'],
    mechanics: 'Cursebound. Use Reach Spell or Widen Spell as a free action instead of 1 action.',
  },
  {
    id: 'oracle-prayer-touched-weapon',
    name: 'Prayer-Touched Weapon',
    source: 'Knights of Lastwall',
    category: 'class',
    level: 4,
    description: 'You coat a weapon you\'re wielding in prayers and the divine power given to you by your deity. Until the end of your turn, the weapon deals an extra 1d6 vitality damage. As usual for vitality damage, this damage harms only undead and creatures with void healing.',
    implemented: 'full',
    traits: ['Cleric', 'Oracle', 'Uncommon'],
    actionCost: 'free',
    prerequisites: ['divine spells', 'you follow a good-aligned deity', 'Access: Knights of Lastwall'],
    mechanics: 'Frequency: once per turn. Requirement: most recent action was to cast a non-cantrip divine spell. +1d6 vitality damage until end of turn.',
  },
  {
    id: 'oracle-sacral-lord',
    name: 'Sacral Lord',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'By right of ritual or sheer stubbornness, you have claimed rulership of the land. Claim a defined territory, such as a small section of forest or river, or a district of a larger city. Within its borders, you can cast detect magic, guidance, and sigil as innate divine cantrips, and you gain a +1 circumstance bonus to Make an Impression on creatures that have the celestial, fiend, fey, monitor, or spirit traits. You and your land are linked. Changes to one mirror themselves on the other — if you\'re depressed, gray rain and clammy mist might set in.',
    implemented: 'full',
    traits: ['Champion', 'Oracle', 'Rare'],
    actionCost: 'passive',
    prerequisites: ['Trained in Occultism or Trained in Religion'],
    mechanics: 'Claim territory. Within it: innate divine cantrips (detect magic, guidance, sigil) and +1 circumstance to Make an Impression vs celestial/fiend/fey/monitor/spirit.',
  },
  {
    id: 'oracle-thousand-visions',
    name: 'Thousand Visions',
    source: 'Player Core 2',
    category: 'class',
    level: 4,
    description: 'You open your senses to numerous visions of the immediate future. The visions grant you subtle details of your immediate surroundings within 30 feet. Within this range, you don\'t need to succeed at a flat check to target a concealed creature, you\'re not off-guard to creatures that are hidden from you (unless you\'re off-guard to them for reasons other than the hidden condition), and you need only a successful DC 5 flat check to target a hidden creature. Beyond 30 feet, the visions become overwhelmed with too many possible futures, making all of your senses imprecise beyond this range. The visions persist for 1 minute.',
    implemented: 'full',
    traits: ['Cursebound', 'Oracle', 'Prediction'],
    actionCost: 'free',
    mechanics: 'Cursebound. 1-minute duration. Within 30 ft: no flat check vs concealed, not off-guard vs hidden, DC 5 flat check vs hidden. Beyond 30 ft: all senses imprecise.',
  },
  {
    id: 'oracle-undying-conviction',
    name: 'Undying Conviction',
    source: 'Book of the Dead',
    category: 'class',
    level: 4,
    description: 'Your presence has a bolstering effect on your undead minions. Undead creatures under your control and within a 30-foot emanation around you gain a +2 status bonus to saving throws to resist vitality damage and to Will saving throws to resist effects that would make them controlled.',
    implemented: 'full',
    traits: ['Aura', 'Cleric', 'Necromancy', 'Oracle', 'Uncommon', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['able to create or control undead', 'cleric with a void font, oracle of bones, or necromancer wizard'],
    mechanics: '30-foot emanation. Controlled undead gain +2 status to saves vs vitality damage and vs controlled condition.',
  },
  {
    id: 'oracle-vision-of-weakness',
    name: 'Vision of Weakness',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 4,
    description: 'You can call upon divine insights to single out your foes\' weak points. You learn the vision of weakness revelation spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Gain vision of weakness revelation spell. +1 Focus Point.',
  },
  // ── Level 6 ── (5 feats)
  {
    id: 'oracle-advanced-revelation',
    name: 'Advanced Revelation',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'Divine power reveals greater mysteries to you. You learn the advanced revelation spell associated with your mystery.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    prerequisites: ['initial revelation spell'],
    mechanics: 'Gain advanced revelation spell from your mystery.',
  },
  {
    id: 'oracle-detonating-spell',
    name: 'Detonating Spell',
    source: 'Knights of Lastwall',
    category: 'class',
    level: 6,
    description: 'Your spell becomes volatile and explosive. If the next action you use is to Cast a Spell that deals damage to a single target and the spell successfully damages that target, the spell explodes, dealing splash damage equal to the level of the spell cast to adjacent creatures. Unlike normally, this splash damage doesn\'t apply to the target. The splash damage dealt is of the same type the spell deals.',
    implemented: 'full',
    traits: ['Cleric', 'Concentrate', 'Oracle', 'Sorcerer', 'Uncommon', 'Witch', 'Wizard', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['Access: Knights of Lastwall'],
    mechanics: 'Spellshape. Single-target damage spell gains splash damage = spell rank to adjacent creatures (same damage type).',
  },
  {
    id: 'oracle-gifted-power',
    name: 'Gifted Power',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'Your mystery grants you additional magic. You have an extra spell slot of your highest rank, which you can use only to cast one of your mystery\'s granted spells, heightened to this rank. If you have the divine access class feature or Mysterious Repertoire feat, you can cast spells that you learned from those abilities using the additional spell slot from Gifted Power.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Extra highest-rank spell slot usable only for mystery granted spells (or spells from Divine Access/Mysterious Repertoire).',
  },
  {
    id: 'oracle-spiritual-sense',
    name: 'Spiritual Sense',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You have a vague connection to the Ethereal Plane that enables you to notice spirits. While you\'re exploring but not Searching, the GM rolls a secret check for you to find haunts that usually require Searching, as well as spirits, creatures on the Ethereal Plane, and beings made entirely of spiritual essence such as celestials, fiends, and monitors. You can also potentially notice ethereal creatures and spirits inside solid objects, provided they are within 30 feet of you. This applies while Searching, while Seeking, and on the automatic secret check you gain while exploring even if you aren\'t Searching. You can still notice spirits only on a successful check, and you can\'t see them if they\'re more than 5 feet inside an object. When you notice a creature with this sense, you also learn its location, making it hidden to you if it had been undetected.',
    implemented: 'full',
    traits: ['Divine', 'Oracle'],
    actionCost: 'passive',
    mechanics: 'Automatic secret checks to detect haunts, spirits, ethereal creatures, celestials, fiends, monitors while exploring. Detects through objects within 30 ft (max 5 ft depth).',
  },
  {
    id: 'oracle-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Player Core 2',
    category: 'class',
    level: 6,
    description: 'You don\'t lose spells easily. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn\'t disrupted.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Druid', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'DC 15 flat check to avoid disruption from reactions during spellcasting.',
  },
  // ── Level 8 ── (5 feats)
  {
    id: 'oracle-chaotic-spell',
    name: 'Chaotic Spell',
    source: 'Wake the Dead #3',
    category: 'class',
    level: 8,
    description: 'This is the secret of chaotic magic — your foe can hardly predict and counter your moves if you yourself have no idea what will happen. If the next action you use is to Cast a Spell that deals acid, cold, electricity, fire, or sonic damage, roll a d6. The spell\'s damage type changes to the type below associated with the result of the roll, and each creature who is damaged by the spell takes the listed additional effect. 1 (Acid): Sickened 1. 2 (Cold): –10 ft penalty to all Speeds until end of your next turn. 3 (Electricity): Off-guard until end of your next turn. 4 (Fire): Persistent fire damage equal to the spell\'s level. 5 (Force): No added effect. 6 (Sonic): Deafened for 2 rounds.',
    implemented: 'full',
    traits: ['Bard', 'Manipulate', 'Oracle', 'Sorcerer', 'Uncommon', 'Witch', 'Wizard', 'Spellshape'],
    actionCost: 1,
    mechanics: 'Spellshape. Roll d6 to change damage type of acid/cold/electricity/fire/sonic spell. Each result adds a secondary effect.',
  },
  {
    id: 'oracle-debilitating-dichotomy',
    name: 'Debilitating Dichotomy',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You reveal a glimpse of the impossible conflicts between the divine anathema behind your curse, forcing you to reckon with another\'s conflicts as well. You and one creature within 30 feet each take 9d6 mental damage with a basic Will save, and the target is stunned 1 if it critically fails its save. You get a degree of success one better than you rolled for your saving throw. At 10th level, and every 2 levels thereafter, the damage increases by 3d6.',
    implemented: 'full',
    traits: ['Concentrate', 'Cursebound', 'Divine', 'Mental', 'Oracle'],
    actionCost: 2,
    mechanics: 'You and 1 target within 30 ft: 9d6 mental (basic Will). You get 1 degree better on your save. Target stunned 1 on crit fail. +3d6 every 2 levels after 10th.',
  },
  {
    id: 'oracle-read-disaster',
    name: 'Read Disaster',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You spend 10 minutes and open yourself to the divine mysteries of the world, peering into the most sinister portents of the future. You gain the effects of augury, except you learn only about the dangers ahead; any results of "good" are instead "nothing," and results of "mixed" are instead "bad." If you are legendary in Religion, you take only 1 minute to Read Disaster.',
    implemented: 'full',
    traits: ['Exploration', 'Oracle', 'Prediction'],
    actionCost: 'passive',
    mechanics: '10-minute exploration activity (1 min if legendary Religion). Augury but only warns of dangers (good → nothing, mixed → bad).',
  },
  {
    id: 'oracle-surging-might',
    name: 'Surging Might',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'You focus the power of your spell to overcome enemies\' resistances. If the next action you use is to Cast a Spell, the spell ignores an amount of the target\'s resistance equal to your level against the following types of damage: spirit, vitality, and void. This applies to all damage the spell deals, including persistent damage and damage caused by an ongoing effect of the spell. This doesn\'t cause the spell to ignore immunities, only resistances.',
    implemented: 'full',
    traits: ['Manipulate', 'Oracle', 'Spellshape'],
    actionCost: 1,
    mechanics: 'Spellshape. Next spell ignores resistance = your level vs spirit, vitality, and void damage.',
  },
  {
    id: 'oracle-water-walker',
    name: 'Water Walker',
    source: 'Player Core 2',
    category: 'class',
    level: 8,
    description: 'When in the throes of your curse, your steps take on a supernatural buoyancy. When you are cursebound 1, you can Stride across liquids that don\'t support your weight, but you must end your movement on a surface that can support you or you fall into the liquid as normal. When you are cursebound 2 or worse, you gain the effects of water walk.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Cursebound 1: can Stride across liquid but must end on solid ground. Cursebound 2+: full water walk effect.',
  },
  // ── Level 10 ── (9 feats)
  {
    id: 'oracle-consecrate-spell',
    name: 'Consecrate Spell',
    source: 'Knights of Lastwall',
    category: 'class',
    level: 10,
    description: 'You infuse a spell with the power of your faith, consecrating it. If the next action you use is to Cast a Spell that targets a single undead, you can expend a Focus Point, channeling the power of your focus spells into the primary spell. If you do, the spell you cast deals additional vitality damage equal to the level of your focus spells. As normal for additional damage, this additional damage is doubled if the spell cast requires an attack roll and the result of the attack roll is a critical hit, or if the spell cast requires a saving throw and the result of the saving throw is a critical failure.',
    implemented: 'full',
    traits: ['Cleric', 'Concentrate', 'Oracle', 'Sorcerer', 'Uncommon', 'Spellshape'],
    actionCost: 1,
    prerequisites: ['ability to cast focus spells', 'divine spells', 'Access: Knights of Lastwall'],
    mechanics: 'Spellshape. Expend 1 Focus Point when casting single-target spell vs undead. +vitality damage = focus spell rank. Doubled on crit.',
  },
  {
    id: 'oracle-on-borrowed-time',
    name: 'On Borrowed Time',
    source: 'Dark Archive',
    category: 'class',
    level: 10,
    description: 'You accelerate a foe\'s personal timestream, which causes them to experience time at a faster rate, putting a terrible strain on their mind and body. A creature you target within 30 feet takes 3d6 persistent mental damage with a basic Will save. At the end of the subject\'s turn, they take this persistent damage after all other persistent damage. Before they roll their flat check to end the persistent damage, an additional round passes for them; this affects the duration of all beneficial effects, negative effects, afflictions, conditions, and other persistent damage. The subject attempts saving throws, flat checks, and any other rolls and takes damage as if the time had passed. They don\'t take the persistent mental damage from On Borrowed Time more than once per round. If you are cursebound 2, the persistent damage increases to 4d6. If you are cursebound 3, the persistent damage increases to 5d6.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 2,
    prerequisites: ['time mystery'],
    mechanics: '3d6 persistent mental (basic Will), target within 30 ft. Extra round passes before flat check. Cursebound 2: 4d6. Cursebound 3: 5d6.',
  },
  {
    id: 'oracle-oracular-warning-l10',
    name: 'Oracular Warning',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 10,
    description: 'You have a flash of insight about impending danger related to one ally, and you can shout or gesture to warn that ally of the threat a moment before it materializes. One ally of your choice can roll twice for initiative and use the better result; this is a fortune effect. If you are legendary in Religion, you receive two visions and can warn two allies, granting them both this benefit. You are momentarily thrown off by the divine insight, however, and you must roll twice for your initiative roll and use the worse result. This is a misfortune effect. The two effects are tied together; if you would avoid the misfortune effect for any reason, or if any of your allies would negate their fortune effect, your Oracular Warning does nothing. Depending on whether you use gestures or call out, this action gains either the visual or auditory trait, respectively.',
    implemented: 'full',
    traits: ['Divination', 'Divine', 'Oracle'],
    actionCost: 'free',
    prerequisites: ['Trigger: You are about to roll initiative'],
    mechanics: '1 ally rolls twice for initiative (fortune). You roll twice and take worse (misfortune). Linked effects. Legendary Religion: warn 2 allies.',
  },
  {
    id: 'oracle-quickened-casting',
    name: 'Quickened Casting',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'If your next action is to cast a cantrip or a spell that is at least 2 ranks lower than the highest-rank spell slot you have, reduce the number of actions to cast it by 1 (minimum 1 action).',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Frequency: once per day. Reduce actions to cast cantrip or spell ≥2 ranks lower by 1 (min 1). Only for oracle spells.',
  },
  {
    id: 'oracle-roll-the-bones-of-fate',
    name: 'Roll the Bones of Fate',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You roll a handful of bones to learn (or perhaps influence) the future course of events. Roll 1d4 and use the corresponding result below. Whenever you Roll the Bones of Fate, any effects from a previous usage immediately end. 1 Good: You or an ally within 30 feet can roll twice on your next attack roll or skill check, taking the higher result (fortune). 2 Bad: One creature you are observing within 30 feet must succeed at a Will save against your spell DC; on a failure, the target must roll twice on their next attack roll or skill check, taking the lower result (misfortune). 3 Mixed: You gain the benefits of rolling both a 1 and a 2. 4 Cursed Possibilities: Every creature within 30 feet rolls twice on their next attack roll or skill check; if the highest number rolled is odd, they take the lower result (misfortune), and if even, they take the higher result (fortune).',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle', 'Prediction'],
    actionCost: 1,
    prerequisites: ['bones mystery or lore mystery'],
    mechanics: 'Frequency: once per 10 min. Roll 1d4: 1 (Good) fortune for ally; 2 (Bad) misfortune vs foe (Will save); 3 (Mixed) both; 4 (Cursed) all within 30 ft roll twice, odd = lower, even = higher.',
  },
  {
    id: 'oracle-surging-might-apg',
    name: 'Surging Might',
    source: 'Advanced Player\'s Guide',
    category: 'class',
    level: 10,
    description: 'With a complex gesture, you focus the divine power of your spell to overcome enemies\' resistances. If the next action you use is to Cast a Spell, the spell ignores an amount of the target\'s resistance equal to your level against all the following types of damage: chaotic, evil, good, lawful, negative, and positive. This applies to all damage the spell deals, including persistent damage and damage caused by an ongoing effect of the spell. This doesn\'t cause the spell to ignore immunities, only resistances.',
    implemented: 'full',
    traits: ['Manipulate', 'Oracle', 'Spellshape'],
    actionCost: 1,
    mechanics: 'Spellshape (legacy version). Next spell ignores resistance = your level vs chaotic, evil, good, lawful, negative, positive damage.',
  },
  {
    id: 'oracle-the-dead-walk',
    name: 'The Dead Walk',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'You beseech warrior spirits to come forth and aid you. Two ghostly warriors manifest within a 30-foot emanation of you and each attempt a Strike against an adjacent enemy, using your spell attack modifier. The warriors\' Strikes each deal 4d6 spirit damage and the warriors can flank with one another and with you and your allies. If you are cursebound 2 when you use The Dead Walk, you instead summon three warriors, and if you are cursebound 3, you instead summon four warriors. The warriors disappear at the start of your next turn.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 2,
    prerequisites: ['ancestors mystery or battle mystery'],
    mechanics: 'Summon 2 ghostly warriors (30-ft emanation). Each Strikes for 4d6 spirit (your spell attack). Can flank. Cursebound 2: 3 warriors. Cursebound 3: 4 warriors.',
  },
  {
    id: 'oracle-trial-by-skyfire',
    name: 'Trial by Skyfire',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'Your lips murmur as you portend a great disaster, one you hope you survive. A rain of blazing bolts begins to fall from the heavens in a 10-foot emanation, centered on you, that deals 2d6 fire damage to all creatures in the emanation at the end of each of your turns (basic Reflex save); you can\'t exclude yourself from the emanation. The skyfire persists for 1 minute; while you can\'t Dismiss it, you can suppress the effect for 1 round with a Sustain action. The rain of fire is suppressed if you fall unconscious. If you become cursebound 3 or 4 at any point during Trial by Skyfire\'s duration, the emanation increases to 15 feet and the damage increases to 4d6.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Fire', 'Oracle'],
    actionCost: 1,
    prerequisites: ['cosmos mystery or flames mystery'],
    mechanics: '10-ft emanation centered on you, 2d6 fire at end of each turn (basic Reflex), 1 min. Can Sustain to suppress 1 round. Cursebound 3+: 15-ft, 4d6.',
  },
  {
    id: 'oracle-waters-of-creation',
    name: 'Waters of Creation',
    source: 'Player Core 2',
    category: 'class',
    level: 10,
    description: 'Water is the source of life, and you draw upon this primordial force to heal your allies\' wounds. A gentle ring ripples out from you in a 15-foot emanation, restoring 5d6 Hit Points to creatures in the area. At 12th level and every two levels thereafter, the amount restored increases by 1d6. If you are cursebound 3 when you use Waters of Creation, the amount healed increases to d8s.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Healing', 'Oracle', 'Vitality', 'Water'],
    actionCost: 2,
    prerequisites: ['life mystery or tempest mystery'],
    mechanics: '15-ft emanation: heal 5d6 HP (+1d6 per 2 levels after 12th). Cursebound 3: d8s instead of d6s.',
  },
  // ── Level 12 ── (5 feats)
  {
    id: 'oracle-domain-fluency',
    name: 'Domain Fluency',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You command a deep understanding of the domains related to your mystery. Choose one of the domains associated with your mystery for which you have an initial domain spell. You gain an advanced domain spell from that domain, which you cast as a revelation spell.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    prerequisites: ['Domain Acumen'],
    mechanics: 'Gain advanced domain spell from a mystery-associated domain as a revelation spell.',
  },
  {
    id: 'oracle-epiphany-at-the-crossroads',
    name: 'Epiphany at the Crossroads',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'The crossroads between life and death is a place that can reveal many secrets. You gain the effects of an augury spell in a strange, near-death vision. Empowered by the realization, you then lose the dying condition (becoming wounded 1 or increasing your wounded value by 1, as normal), regain a number of Hit Points equal to twice your level, and can Stand.',
    implemented: 'full',
    traits: ['Divine', 'Oracle'],
    actionCost: 'free',
    prerequisites: ['Trigger: Your turn begins', 'Requirements: You are unconscious and have the dying condition'],
    mechanics: 'Frequency: once per day. When dying and unconscious at start of turn: gain augury effects, lose dying, gain wounded, heal 2 × level HP, Stand.',
  },
  {
    id: 'oracle-greater-revelation',
    name: 'Greater Revelation',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You unlock deeper revelations hidden within your mystery. You gain your mystery\'s greater revelation spell.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    prerequisites: ['initial revelation spell'],
    mechanics: 'Gain greater revelation spell from your mystery.',
  },
  {
    id: 'oracle-magic-sense',
    name: 'Magic Sense',
    source: 'Player Core 2',
    category: 'class',
    level: 12,
    description: 'You have a literal sixth sense for ambient magic in your vicinity. You can sense the presence of magic auras as though you were always using a 1st-rank detect magic spell. This detects magic in your field of vision only. When you Seek, you gain the benefits of a 3rd-rank detect magic spell on things you see (in addition to the normal benefits of Seeking). You can turn this sense off and on with a free action at the start or the end of your turn.',
    implemented: 'full',
    traits: ['Arcane', 'Detection', 'Magus', 'Oracle', 'Sorcerer', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Constant 1st-rank detect magic in field of vision. Seeking adds 3rd-rank detect magic. Toggle with free action.',
  },
  {
    id: 'oracle-necromancers-visage',
    name: 'Necromancer\'s Visage',
    source: 'Book of the Dead',
    category: 'class',
    level: 12,
    description: 'Necromantic energy demonstrates your power over undead, creating a demeanor that commands their fear and respect. Undead creatures can immediately sense your Necromancer\'s Visage and living creatures can sense it with a successful Perception check against your spell DC. Mindless undead won\'t attack you unless directed to by their controller or unless you attack them first. If you take a hostile action against an undead creature or its allies, it\'s temporarily immune to this feat\'s effects for 24 hours. The living find your appearance unsettling; you gain a +1 status bonus to Intimidation checks against living creatures, and you take a –1 status penalty to Diplomacy checks against them.',
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Necromancy', 'Oracle', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['ability to create or control undead', 'cleric with a void font, oracle of bones, or necromancer wizard'],
    mechanics: 'Mindless undead ignore you (unless directed or provoked, then immune 24 hrs). +1 status Intimidation vs living, –1 status Diplomacy vs living.',
  },
  // ── Level 14 ── (7 feats)
  {
    id: 'oracle-forestall-curse',
    name: 'Forestall Curse',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'You\'ve learned to hold back your curse. If the next action you use is a cursebound ability, your cursebound value doesn\'t increase.',
    implemented: 'full',
    traits: ['Concentrate', 'Oracle'],
    actionCost: 'free',
    mechanics: 'Frequency: once per day. Next cursebound ability doesn\'t increase cursebound value.',
  },
  {
    id: 'oracle-lighter-than-air',
    name: 'Lighter than Air',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'Your mysterious steps become even lighter, transcending the mortal world altogether. When you have the cursebound condition, you gain the effects of fly. If you are cursebound 3 or greater, you gain a +10-foot status bonus to your fly Speed.',
    implemented: 'full',
    traits: ['Divine', 'Oracle'],
    actionCost: 'passive',
    prerequisites: ['Water Walker'],
    mechanics: 'While cursebound: gain fly effect. Cursebound 3+: +10-ft status bonus to fly Speed.',
  },
  {
    id: 'oracle-mysterious-repertoire',
    name: 'Mysterious Repertoire',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'Your mystery holds unknowable depths of magic not always associated with the divine. You can have one spell in your spell repertoire not on the divine spell list, in addition to spells you\'ve added to your spell list from abilities like divine access. You cast that spell as a divine spell. You can swap which spell you add and from which tradition as you could any other oracle spell, but you can\'t use this feat to have more than one spell from another tradition in your spell repertoire at the same time.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Add 1 non-divine spell to repertoire, cast as divine. Can swap at level-up. Only 1 at a time.',
  },
  {
    id: 'oracle-purifying-breeze',
    name: 'Purifying Breeze',
    source: 'Knights of Lastwall',
    category: 'class',
    level: 14,
    description: 'You transfer the divine essence of your magic to the air around you, cleansing it of toxins. Attempt a counteract check against each airborne disease or poison effect in a 15-foot radius around you. Regardless of your success or failure, until the beginning of your next turn, all creatures in the purified area gain a +1 status bonus to Fortitude saving throws.',
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Oracle', 'Sorcerer'],
    actionCost: 1,
    prerequisites: ['divine spells', 'Access: Knights of Lastwall', 'Requirements: Most recent action was to cast a non-cantrip spell with the healing trait'],
    mechanics: 'Frequency: once per turn. Counteract airborne diseases/poisons in 15-ft radius. +1 status to Fort saves in area until start of next turn.',
  },
  {
    id: 'oracle-revelations-focus',
    name: 'Revelation\'s Focus',
    source: 'Player Core 2',
    category: 'class',
    level: 14,
    description: 'The further extents of your mystery provide an endless wellspring of magic. You increase the maximum number of Focus Points in your focus pool from 3 to 4. As a revelation spell has a focus cost of 1 Focus Point, this lets you use a revelation spell up to four times before needing to Refocus (as opposed to the normal maximum of three times).',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Max Focus Points: 3 → 4. Can use revelation spells 4 times before Refocusing.',
  },
  {
    id: 'oracle-sacral-monarch',
    name: 'Sacral Monarch',
    source: 'Dark Archive',
    category: 'class',
    level: 14,
    description: 'You have come into your full powers and are truly a monarch of your realm, by your own definition at least. While in your territory, you can cast banishment and inevitable disaster as innate divine spells, each once per day.',
    implemented: 'full',
    traits: ['Champion', 'Oracle'],
    actionCost: 'passive',
    prerequisites: ['Sacral Lord', 'master in Occultism or Religion'],
    mechanics: 'While in territory: 1/day banishment and 1/day inevitable disaster as innate divine spells.',
  },
  {
    id: 'oracle-sepulchral-sublimation',
    name: 'Sepulchral Sublimation',
    source: 'Book of the Dead',
    category: 'class',
    level: 14,
    description: 'You repurpose the void energy that flows through your minions at a moment\'s notice. Instantly destroy one undead minion within 60 feet that is permanently under your control. If your next action is to cast a necromancy spell from a spell slot, you don\'t expend the slot. The spell\'s level must be half the destroyed minion\'s level or lower and the spell can\'t have a duration.',
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Concentrate', 'Necromancy', 'Oracle', 'Wizard'],
    actionCost: 1,
    prerequisites: ['ability to create or control undead', 'cleric with a void font, oracle of bones, or necromancer wizard', 'Requirements: You have at least one undead minion you permanently control'],
    mechanics: 'Destroy 1 controlled undead within 60 ft. Next necromancy spell (slot ≤ half minion level, no duration) doesn\'t expend slot.',
  },
  // ── Level 16 ── (3 feats)
  {
    id: 'oracle-conduit-of-void-and-vitality',
    name: 'Conduit of Void and Vitality',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'You use the unstable energy of your curse to manipulate the most basic of divine magic. You cast a 3-action heal or harm, expending a spell slot as normal. If the spell heals one or more creatures, then one creature healed by this spell regains a number of additional Hit Points equal to 1d8 × your cursebound value; if the spell damages one or more creatures, then one creature harmed by this spell takes additional damage equal to 1d8 × your cursebound value.',
    implemented: 'full',
    traits: ['Cursebound', 'Divine', 'Oracle'],
    actionCost: 2,
    prerequisites: ['any oracle mystery', 'Requirements: You have heal or harm as a signature spell and an available spell slot to cast it with'],
    mechanics: 'Cast 3-action heal or harm. One target gains/takes additional 1d8 × cursebound value HP/damage.',
  },
  {
    id: 'oracle-diverse-mystery',
    name: 'Diverse Mystery',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'You have broadened your understanding of the divine and can tap into the wonders of a different mystery. Select one revelation spell from a mystery other than your own. You can choose only an initial revelation spell or an advanced revelation spell. This spell gains the cursebound trait for you, and when you cast it, you gain the cursebound 1 effects of its mystery in addition to your normal curse effects. Any ability that lets you use a cursebound ability without increasing the severity of your curse also prevents you from gaining this additional curse effect. You can\'t cast your chosen revelation spell if its mystery\'s curse effects directly conflict with or negate the effects of your own mystery\'s curse, the curse would have no effect on you, or if either of these criteria would be met once you finish Casting the Spell.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: 'Gain 1 initial or advanced revelation spell from another mystery. Casting it also applies that mystery\'s cursebound 1 effects.',
    subChoices: { label: 'Choose a mystery to learn from', options: [
      { id: 'ancestors', name: 'Ancestors', description: 'Ancestral Touch or Spirit Veil' },
      { id: 'battle', name: 'Battle', description: 'Call to Arms or Battlefield Persistence' },
      { id: 'bones', name: 'Bones', description: 'Soul Siphon or Armor of Bones' },
      { id: 'cosmos', name: 'Cosmos', description: 'Spray of Stars or Interstellar Void' },
      { id: 'flames', name: 'Flames', description: 'Incendiary Aura or Whirling Flames' },
      { id: 'life', name: 'Life', description: 'Life Link or Delay Affliction' },
      { id: 'lore', name: 'Lore', description: 'Brain Drain or Access Lore' },
      { id: 'tempest', name: 'Tempest', description: 'Tempest Touch or Thunderburst' },
      { id: 'time', name: 'Time', description: 'Temporal Distortion or Time Skip' },
    ] },
  },
  {
    id: 'oracle-portentous-spell',
    name: 'Portentous Spell',
    source: 'Player Core 2',
    category: 'class',
    level: 16,
    description: 'Your spellcasting is rife with strange lights, mild fumes, and other captivating effects that befuddle your foes. If the next action you use is to Cast a Spell, any creature that attempts to use a reaction triggered by your Cast a Spell activity takes a –2 circumstance penalty to attack rolls and skill checks rolled as part of the reaction. In addition, if the spell includes a spell attack or requires a saving throw, creatures you hit or that fail their saves are fascinated with you until the start of your next turn.',
    implemented: 'full',
    traits: ['Manipulate', 'Mental', 'Oracle', 'Spellshape', 'Visual'],
    actionCost: 1,
    mechanics: 'Spellshape. Reactions to your Cast a Spell take –2 circumstance to attacks/checks. Creatures hit or failing saves are fascinated until start of next turn.',
  },
  // ── Level 18 ── (2 feats)
  {
    id: 'oracle-blaze-of-revelation',
    name: 'Blaze of Revelation',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'Your mind and body can, for a short time and with great peril, surpass the final limits of your curse. For 1 minute, you shed torrential flames, become surrounded by spirits, or otherwise overflow with divine power in a way that suits your mystery. On each of your turns during that time, you can cast one revelation spell without spending Focus Points. At the end of the minute, the durations of any revelation spells you cast during that time end, and you must attempt a DC 40 Fortitude save. Critical Success: You aren\'t otherwise affected. Success: You are drained 2 and can\'t reduce or remove this condition until your next preparations. Failure: You are drained 4 and can\'t reduce or remove this condition until your next preparations. Critical Failure: You die.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'free',
    prerequisites: ['Requirements: You are cursebound 4'],
    mechanics: '1-minute duration. Cast 1 revelation spell per turn without Focus Points. Then DC 40 Fort: crit success = fine, success = drained 2, failure = drained 4, crit failure = death.',
  },
  {
    id: 'oracle-divine-effusion',
    name: 'Divine Effusion',
    source: 'Player Core 2',
    category: 'class',
    level: 18,
    description: 'The power of your mystery surges through you like a font of divine energy, even when your own magic dwindles. Twice per day, you can cast a spell after you\'ve run out of spell slots of the appropriate spell rank; the two spells you cast with this feat must be of different spell ranks.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    mechanics: '2/day: cast a spell after running out of spell slots of that rank. Each use must be a different rank.',
  },
  // ── Level 20 ── (4 feats)
  {
    id: 'oracle-mystery-conduit',
    name: 'Mystery Conduit',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'The power of your mystery enables you access to myriad magic. If your next action is to Cast a Spell of 5th rank or lower that has no duration, you do not expend a spell slot.',
    implemented: 'full',
    traits: ['Cursebound', 'Oracle', 'Spellshape'],
    actionCost: 'free',
    mechanics: 'Cursebound. Spellshape. Next spell of 5th rank or lower with no duration doesn\'t expend a slot.',
  },
  {
    id: 'oracle-oracular-providence',
    name: 'Oracular Providence',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'Your mystery grants you access to deep reserves of truly miraculous divine power. You gain an additional 10th-rank spell slot.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    prerequisites: ['Oracular Clarity'],
    mechanics: '+1 additional 10th-rank spell slot.',
  },
  {
    id: 'oracle-paradoxical-mystery',
    name: 'Paradoxical Mystery',
    source: 'Player Core 2',
    category: 'class',
    level: 20,
    description: 'The truest depths of your divine mystery are fathomless and contradictory, granting you changing powers that even you can barely begin to fathom. Each day during your daily preparations, choose one basic or advanced domain spell from any domain from Player Core, one of the domains granted by your mystery, another domain to which you have access, or any initial or advanced revelation spell from another mystery. You gain that spell as a revelation spell until your next daily preparations.',
    implemented: 'full',
    traits: ['Oracle'],
    actionCost: 'passive',
    prerequisites: ['Greater Revelation'],
    mechanics: 'Daily preparations: choose 1 domain spell or revelation spell from any mystery. Gain as revelation spell for the day.',
  },
  {
    id: 'oracle-scapegoat-parallel-self',
    name: 'Scapegoat Parallel Self',
    source: 'Fists of the Ruby Phoenix',
    category: 'class',
    level: 20,
    description: 'Seeing Syndara superimpose creatures with similar metaphysical properties, you\'ve realized a way to manipulate the effects of your oracular curse. You immediately change your curse to its minor, moderate, or major stage, or back to its mild form, exchanging the curse effect with that of a parallel version of yourself in another reality.',
    implemented: 'full',
    traits: ['Uncommon', 'Divine', 'Necromancy', 'Oracle'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: Your turn starts or your oracular curse would advance'],
    mechanics: 'Frequency: once per day. Change curse stage to minor, moderate, major, or mild (effectively changing cursebound value).',
  },
];
