/**
 * Psychic Class Features & Feats — PF2e Remastered (Dark Archive)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=68
 *
 * Key Attribute: INT or CHA (determined by subconscious mind)
 * HP: 6 + CON
 * Perception: Trained → Expert (L11, Extrasensory Perception)
 * Fort: Trained → Expert (L9, Fortitude Expertise)
 * Reflex: Trained → Expert (L5, Precognitive Reflexes)
 * Will: Expert → Master (L11, Walls of Will, success→crit) → Legendary (L17, Fortress of Will, crit-fail→fail, half on fail)
 * Weapons: Trained simple+unarmed → Expert (L11, Weapon Expertise)
 * Armor: Untrained all armor, Trained unarmored → Expert (L13, Personal Barrier)
 * Spellcasting: Occult spontaneous — Trained → Expert (L7) → Master (L15) → Legendary (L19)
 * Class DC: Trained
 *
 * Subconscious Minds (Dark Archive Remastered):
 *   Emotional Acceptance (CHA) — Psyche Action: Restore the Mind
 *   Gathered Lore (INT)        — Psyche Action: Recall the Teachings
 *   Precise Discipline (INT)   — Psyche Action: Calculate Threats
 *   Wandering Reverie (CHA)    — Psyche Action: Fade into Daydreams
 *
 * Conscious Minds (Dark Archive Remastered):
 *   The Distant Grasp   — Telekinesis (telekinetic hand, telekinetic projectile)
 *   The Infinite Eye     — Clairvoyance/Precognition (detect magic, guidance)
 *   The Oscillating Wave — Fire/Cold Energy (frostbite, ignition)
 *   The Silent Whisper   — Telepathy (daze, message)
 *   The Tangible Dream   — Illusion/Force (figment, shield)
 *   The Unbound Step     — Teleportation/Spatial (phase bolt, warp step)
 *
 * Key Mechanic: Unleash Psyche (free action, 2 rounds, +2×spell rank damage, stupefied 1 for 2 rounds after)
 * Key Mechanic: Psi Cantrips can be amped by spending 1 Focus Point (free action)
 * Starting Focus Pool: 2
 *
 * Class features: 20 (L1–L19)
 * Class feats: 47 (L1–L20)
 */

import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// PSYCHIC CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const PSYCHIC_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'psychic-spellcasting',
    name: 'Psychic Spellcasting',
    source: 'Psychic',
    category: 'class_feature',
    level: 1,
    description: 'You access the vast well of power that resides within your own mind, calling forth psychic magic with nothing but thought and will. You are a spellcaster and can cast occult spells using the Cast a Spell activity. You don\'t need to utter incantations to cast your spells, instead exerting your mind toward your intended effect as described in your subconscious mind class feature. Your spells still have clear and noticeable visual and auditory manifestations, as normal for a spellcaster. Each day, you can cast one 1st-rank spell. You must know spells to cast them, and you learn them via the spell repertoire class feature. The number of spells you can cast each day is called your spell slots. Some of your spells require you to attempt a spell attack roll to see how effective they are, or have your enemies roll against your spell DC (typically by attempting a saving throw). Since your key attribute is determined by your subconscious mind, your spell attack rolls and spell DCs use the modifier for the attribute stated in your subconscious mind.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  {
    id: 'psychic-spell-repertoire',
    name: 'Spell Repertoire',
    source: 'Psychic',
    category: 'class_feature',
    level: 1,
    description: 'The collection of spells you can cast is called your spell repertoire. At 1st level, you learn one 1st-rank occult spell of your choice and three occult cantrips of your choice. You choose these from the common spells from the occult list or from other occult spells to which you have access. You can cast any spell in your spell repertoire by using a spell slot of an appropriate spell rank. Your choice of conscious mind also grants you additional spells in your repertoire, starting with an additional 1st-rank spell and two cantrips listed in your conscious mind, which you cast as psi cantrips. You add to this spell repertoire as you increase in level. Each time you get a spell slot, you add a spell to your spell repertoire of the same rank. As you gain new spells in your repertoire, you might want to replace some of the spells you previously learned. Each time you gain a level and learn new spells, you can swap out one of your old spells for a different spell of the same rank. This spell can be a cantrip. You can also swap out spells by retraining during downtime.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  {
    id: 'psychic-psi-cantrips-and-amps',
    name: 'Psi Cantrips and Amps',
    source: 'Psychic',
    category: 'class_feature',
    level: 1,
    description: 'The magic of your mind manifests as psi cantrips, which you can modify by spending Focus Points. Like other cantrips, you can cast psi cantrips as often as you like, and they are automatically heightened to half your level rounded up. Your psi cantrips are in addition to the cantrips you choose from the occult list as part of your psychic spellcasting. At 1st level, you learn three psi cantrips determined by your choice of conscious mind; one is a unique psi cantrip and two are common cantrips, typically from the occult spellcasting tradition, that you always cast as psi cantrips. You start with a focus pool of 2 Focus Points. Instead of gaining focus spells, you use your Focus Points to boost or modify your psi cantrips by applying amps — specialized thoughtforms that alter the expression of your psychic power. Each of your psi cantrips has a special amp heading. Whenever you cast a psi cantrip, you can amp it by spending 1 Focus Point as a free action. You refill your focus pool during your daily preparations, and you can regain Focus Points by spending 10 minutes using the Refocus activity. If you\'ve spent Focus Points only to amp psi cantrips or fuel psychic abilities since the last time you Refocused, you regain 2 Focus Points instead of 1.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Start with 2 Focus Points. Amp psi cantrips by spending 1 FP (free action). Refocus regains 2 FP if only psychic abilities used, otherwise 1 FP.',
  },
  {
    id: 'psychic-unleash-psyche',
    name: 'Unleash Psyche',
    source: 'Psychic',
    category: 'class_feature',
    level: 1,
    description: 'When one thins the barrier between their inner mind and the outer world, one can unleash true psychic power. You call on the depths of your mind and let psychic power flood through. Your Psyche remains Unleashed for 2 rounds or until you fall unconscious, whichever comes first. You can\'t voluntarily quell your unleashed psyche. While your Psyche is Unleashed: you\'re constantly surrounded by the visual manifestation of your psychic magic; when you cast a damaging spell using your psychic spellcasting, you gain a status bonus to its damage equal to double the spell\'s rank (this applies only to initial damage and an individual creature takes this damage only once per spell); you can use actions that have the psyche trait. After your unleashed psyche subsides, your mind must recover from the strain of channeling its full power. You can\'t use Unleash Psyche again for 2 rounds, and you\'re stupefied 1 for 2 rounds.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'free',
    prerequisites: ['Trigger: Your turn begins', 'Requirements: You\'re in an encounter, you Cast a Spell on your previous turn, and you aren\'t stupefied'],
    mechanics: '2-round duration. Spell damage bonus = 2 × spell rank (status). Enables psyche actions. Afterward: stupefied 1 for 2 rounds, can\'t Unleash again for 2 rounds.',
  },
  {
    id: 'psychic-subconscious-mind',
    name: 'Subconscious Mind',
    source: 'Psychic',
    category: 'class_feature',
    level: 1,
    description: 'A psychic\'s power is born in the depths of their psyche, far from the surface. Your subconscious mind fundamentally shapes how you access and wield psychic magic. Choose a subconscious mind from the following options. This choice determines your key attribute, thoughtforms you use while casting, and a 1-action psyche action you can take while you have Unleashed your Psyche. Options: Emotional Acceptance (CHA key; Psyche Action: Restore the Mind — heal ally 2 + double level HP or grant +1 status to Will vs emotion), Gathered Lore (INT key; Psyche Action: Recall the Teachings — count as having prepared to Aid allies within 30 ft, use Occultism for Aid), Precise Discipline (INT key; Psyche Action: Calculate Threats — +2 circumstance to AC and Reflex until start of next turn), Wandering Reverie (CHA key; Psyche Action: Fade into Daydreams — become concealed until start of next turn).',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Choose subconscious mind: Emotional Acceptance (CHA), Gathered Lore (INT), Precise Discipline (INT), or Wandering Reverie (CHA). Determines key attribute and grants a 1-action psyche action.',
    subChoices: { label: 'Choose a subconscious mind', options: [
      { id: 'emotional-acceptance', name: 'Emotional Acceptance', description: 'CHA key ability; psyche action: Emotional Surge' },
      { id: 'gathered-lore', name: 'Gathered Lore', description: 'INT key ability; psyche action: Recall the Teachings' },
      { id: 'precise-discipline', name: 'Precise Discipline', description: 'INT key ability; psyche action: Calculate Threats' },
      { id: 'wandering-reverie', name: 'Wandering Reverie', description: 'CHA key ability; psyche action: Wander Freely' },
    ] },
  },
  {
    id: 'psychic-conscious-mind',
    name: 'Conscious Mind',
    source: 'Psychic',
    category: 'class_feature',
    level: 1,
    description: 'Whatever the subconscious source of a psychic\'s power, all find that a specific external manifestation of their magic comes most easily to them. This conscious outward expression adds several additional spells to your spell repertoire and grants you three psi cantrips. Two of these cantrips are common spells with extra benefits, and the last is unique to your conscious mind. You also get two more unique psi cantrips at higher levels. Options: The Distant Grasp (telekinesis — telekinetic hand, telekinetic projectile), The Infinite Eye (clairvoyance — detect magic, guidance), The Oscillating Wave (fire/cold energy — frostbite, ignition; Conservation of Energy mechanic), The Silent Whisper (telepathy — daze, message), The Tangible Dream (illusion/force — figment, shield), The Unbound Step (teleportation — phase bolt, warp step).',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Choose conscious mind. Grants 3 psi cantrips + additional spells at each spell rank (1st through 8th). The Oscillating Wave alternates fire/cold via Conservation of Energy.',
    subChoices: { label: 'Choose a conscious mind', options: [
      { id: 'the-distant-grasp', name: 'The Distant Grasp', description: 'Telekinetic force; Telekinetic Projectile psi cantrip' },
      { id: 'the-infinite-eye', name: 'The Infinite Eye', description: 'Divination and perception; Detect Magic psi cantrip' },
      { id: 'the-oscillating-wave', name: 'The Oscillating Wave', description: 'Fire/cold energy alternation; Produce Flame psi cantrip' },
      { id: 'the-silent-whisper', name: 'The Silent Whisper', description: 'Telepathy and mental influence; Message psi cantrip' },
      { id: 'the-tangible-dream', name: 'The Tangible Dream', description: 'Illusion made real; Shield psi cantrip' },
      { id: 'the-unbound-step', name: 'The Unbound Step', description: 'Teleportation and spatial manipulation; Phase Bolt psi cantrip' },
    ] },
  },
  // ── Level 3 ──
  {
    id: 'psychic-signature-spells',
    name: 'Signature Spells',
    source: 'Psychic',
    category: 'class_feature',
    level: 3,
    description: 'You\'ve learned to cast some of your spells more flexibly. For each spell rank you have access to, choose one spell of that rank to be a signature spell. You don\'t need to learn heightened versions of signature spells separately; instead, you can heighten these spells freely. If you\'ve learned a signature spell at a higher rank than its minimum, you can also cast all its lower-rank versions without learning those separately. If you swap out a signature spell, you can choose a replacement signature spell of the same spell rank at which you learned the previous spell. You can also retrain specifically to change a signature spell to a different spell of that rank without swapping any spells.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  // ── Level 5 ──
  {
    id: 'psychic-clarity-of-focus',
    name: 'Clarity of Focus',
    source: 'Psychic',
    category: 'class_feature',
    level: 5,
    description: 'Your deepening connection to your mind grants you more power to fuel your psi amps. Increase the number of Focus Points in your focus pool by 1. As normal, this ability can\'t increase the size of your focus pool above 3 points.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: '+1 Focus Point (max 3).',
  },
  {
    id: 'psychic-precognitive-reflexes',
    name: 'Precognitive Reflexes',
    source: 'Psychic',
    category: 'class_feature',
    level: 5,
    description: 'Minor precognition ensures you can react to threats slightly before they occur. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  // ── Level 7 ──
  {
    id: 'psychic-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Psychic',
    category: 'class_feature',
    level: 7,
    description: 'Self-reflection has brought you greater knowledge of yourself and, with it, psychic power. Your proficiency ranks for spell attack modifier and spell DC increase to expert.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  // ── Level 9 ──
  {
    id: 'psychic-fortitude-expertise',
    name: 'Fortitude Expertise',
    source: 'Psychic',
    category: 'class_feature',
    level: 9,
    description: 'Your mind holds your body to a subconscious mental image of yourself. Your proficiency rank for Fortitude saves increases to expert.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  // ── Level 11 ──
  {
    id: 'psychic-extrasensory-perception',
    name: 'Extrasensory Perception',
    source: 'Psychic',
    category: 'class_feature',
    level: 11,
    description: 'Minor applications of clairvoyance let you know when danger is near. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  {
    id: 'psychic-walls-of-will',
    name: 'Walls of Will',
    source: 'Psychic',
    category: 'class_feature',
    level: 11,
    description: 'Your practiced mind resists external influence. Your proficiency rank for Will saves increases to master. When you succeed at a Will save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Will saves: expert → master. Success on Will saves → critical success.',
  },
  {
    id: 'psychic-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Psychic',
    category: 'class_feature',
    level: 11,
    description: 'Training has improved your weapon technique, possibly enhanced by your occult magic. Your proficiency rank for simple weapons and unarmed attacks increases to expert.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  // ── Level 13 ──
  {
    id: 'psychic-personal-barrier',
    name: 'Personal Barrier',
    source: 'Psychic',
    category: 'class_feature',
    level: 13,
    description: 'Subtle telekinetic fields dampen and deflect incoming blows. Your proficiency rank in unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Psychic', 13),
  // ── Level 15 ──
  {
    id: 'psychic-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Psychic',
    category: 'class_feature',
    level: 15,
    description: 'You\'ve gained access to the deepest corners of your own mind. Your proficiency ranks for spell attack modifier and spell DC increase to master.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  // ── Level 17 ──
  {
    id: 'psychic-fortress-of-will',
    name: 'Fortress of Will',
    source: 'Psychic',
    category: 'class_feature',
    level: 17,
    description: 'Your trained mind is as a fortress that none can breach. Your proficiency rank for Will saves increases to legendary. When you critically fail a Will save, you get a failure instead. When you fail a Will save against a damaging effect, you take half damage.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Will saves: master → legendary. Critical failure → failure. Half damage on failed Will saves.',
  },
  // ── Level 19 ──
  {
    id: 'psychic-infinite-mind',
    name: 'Infinite Mind',
    source: 'Psychic',
    category: 'class_feature',
    level: 19,
    description: 'Anything you can imagine is now within the realm of possibility. Add two common 10th-rank occult spells to your repertoire; you gain a single 10th-rank spell slot you can use to cast one of those two spells using psychic spellcasting. You don\'t gain more 10th-rank spells as you level up, unlike other spell slots, and you can\'t use 10th-rank slots with abilities that give you more spell slots or that let you cast spells without expending spell slots. You can take the Mind over Matter psychic feat to gain a second slot.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  {
    id: 'psychic-legendary-spellcaster',
    name: 'Legendary Spellcaster',
    source: 'Psychic',
    category: 'class_feature',
    level: 19,
    description: 'As your training reaches its peak, you understand not just your own mind, but the collective unconscious from which all psychic power stems. Your proficiency ranks for occult spell attack modifier and spell DC increase to legendary.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
];

// ──────────────────────────────────────────────────────────
// PSYCHIC CLASS FEATS (Selectable)
// ──────────────────────────────────────────────────────────

export const PSYCHIC_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ── (4 feats)
  {
    id: 'psychic-ancestral-mind',
    name: 'Ancestral Mind',
    source: 'Dark Archive',
    category: 'class',
    level: 1,
    description: 'By unraveling memories and connections passed down from your progenitors and buried within your unconscious mind, you learn to convert your inherent magic into psychic power. You can cast any innate spells you know from an ancestry feat or heritage using your psychic spellcasting and thoughtforms. When you do so, the spell\'s tradition becomes occult, if it wasn\'t already, and you can use your psychic spellcasting attribute modifier instead of Charisma to determine your spell attack modifier and spell DC.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
  },
  {
    id: 'psychic-counter-thought',
    name: 'Counter Thought',
    source: 'Dark Archive',
    category: 'class',
    level: 1,
    description: 'When a foe Casts a Spell that has the mental trait and you can see its manifestations, you can use your own mental magic to disrupt it. You expend one of your spell slots to counter the triggering creature\'s casting of a spell with the mental trait. You lose your spell slot as if you had cast the triggering spell; this spell slot must be one for which you could Cast a Spell with the mental trait. You then attempt to counteract the triggering spell.',
    implemented: 'full',
    traits: ['Occult', 'Psychic'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: A creature Casts a Spell with the mental trait', 'Requirements: You have an unexpended spell slot you could use to Cast a Spell with the mental trait'],
    mechanics: 'Expend spell slot to counteract a mental spell. Slot must be one you could use to cast a mental spell.',
  },
  {
    id: 'psychic-mental-buffer',
    name: 'Mental Buffer',
    source: 'Dark Archive',
    category: 'class',
    level: 1,
    description: 'Your mind deflects some amount of harm from attacks that induce pain or manipulate your mind directly. You gain resistance to mental damage equal to half your level (minimum 1). This resistance increases to equal to your level while your Psyche is Unleashed.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Resistance to mental damage = half level (min 1). While Psyche Unleashed: resistance = full level.',
  },
  {
    id: 'psychic-psychic-rapport',
    name: 'Psychic Rapport',
    source: 'Dark Archive',
    category: 'class',
    level: 1,
    description: 'Your telepathic sensitivity intensifies when you\'re affected by mental magic, making it easier for you to link to other creatures. After you Cast a Spell with the mental trait, until the start of your next turn, you gain a +1 circumstance bonus to Deception, Diplomacy, and Intimidation checks, and to Perception checks to Sense Motive.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'After casting a mental spell: +1 circumstance to Deception, Diplomacy, Intimidation, and Sense Motive until start of next turn.',
  },
  // ── Level 2 ── (4 feats)
  {
    id: 'psychic-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Player Core 2',
    category: 'class',
    level: 2,
    description: 'Study broadens your range of simple spells. You add two additional cantrips from the occult spell list to your repertoire.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
  },
  {
    id: 'psychic-mental-balm',
    name: 'Mental Balm',
    source: 'Dark Archive',
    category: 'class',
    level: 2,
    description: 'Your spells release soothing mental waves. Use this amp in place of a psi cantrip\'s normal amp entry. You can use this amp only on a psi cantrip that targets or affects you or one or more of your allies and doesn\'t target or affect any enemies. Amp: You or one ally within 30 feet gains a +2 status bonus to Will saves against emotion effects for 1 minute. You can also have the amped psi cantrip attempt to counteract one effect imposing the frightened condition on yourself or the chosen ally, or an effect imposing the stupefied condition that has a duration of 1 hour or less. If you successfully counteract the effect, you remove only the frightened and stupefied conditions, not any other part of the effect.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Amp (replaces normal amp): ally within 30 ft gains +2 status to Will vs emotion (1 min). Can counteract frightened or stupefied (≤1 hr duration).',
  },
  {
    id: 'psychic-psi-burst',
    name: 'Psi Burst',
    source: 'Dark Archive',
    category: 'class',
    level: 2,
    description: 'With a passing thought, you direct violent psychic energies at a nearby creature. Target one creature within 30 feet. It takes 1d4 bludgeoning damage with a basic Reflex save. At 3rd level and every 2 levels thereafter, the damage increases by 1d4.',
    implemented: 'full',
    traits: ['Concentrate', 'Mindshift', 'Occult', 'Psyche', 'Psychic'],
    actionCost: 1,
    mechanics: 'Frequency: once per round. 1d4 bludgeoning (basic Reflex), +1d4 per 2 levels after 3rd. Mindshift: can change to mental damage + Will save.',
  },
  {
    id: 'psychic-warp-space',
    name: 'Warp Space',
    source: 'Dark Archive',
    category: 'class',
    level: 2,
    description: 'You use your magic to bend space, causing your spell to strike from a strange vector. Use this amp in place of a psi cantrip\'s normal amp entry. The amped psi cantrip must have a range. Amp: Choose a square within 30 feet to which you have line of effect and line of sight. Determine your spell\'s line of effect and line of sight from there, as well as whether creatures have cover against the spell. The spell can exceed its normal range as measured from you, as long as it\'s within its normal range from the square you chose.',
    implemented: 'full',
    traits: ['Amp', 'Psychic'],
    actionCost: 'passive',
    mechanics: 'Amp (replaces normal amp): choose origin square within 30 ft. Determine LoE/LoS/cover from that square. Spell range measured from chosen square.',
  },
// ── Level 4 ── (6 feats)
  {
    id: 'psychic-astral-tether',
    name: 'Astral Tether',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'You fling a psychic tether to an opponent to trip them up. When you successfully counteract a spell or reduce a creature to 0 Hit Points with a psychic spell, you can bind a psychic tether to that creature. This tether lasts until the end of your next turn. While the tether is active, the target is off-guard to your attacks. If the target attempts to move, it must succeed at a Will save against your spell DC or become immobilized until the end of its turn. This tether is broken immediately if the target moves beyond 30 feet from you.',
    implemented: 'full',
    traits: ['Occult', 'Psychic'],
    actionCost: 'passive',
    mechanics: 'Trigger: counteract a spell or reduce creature to 0 HP with psychic spell. Target is off-guard vs you. On move: Will save or immobilized. Tether breaks beyond 30 ft.',
  },
  {
    id: 'psychic-homing-beacon',
    name: 'Homing Beacon',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'Your psychic magic marks a creature as a beacon, drawing the attention of their foes. Once per round, when you deal damage to a creature with a psychic spell, you can choose to mark it as a psychic beacon until the start of your next turn. When you or an ally makes a Strike against the marked creature, the attacker ignores the concealed condition against that creature.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Once per round, mark target hit by psychic spell. Marked creature: you and allies ignore concealed condition against it until start of your next turn.',
  },
  {
    id: 'psychic-irezoko-tattoo',
    name: 'Irezoko Tattoo',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'You have an irezoko tattoo on your body that was given to you by a psychic tattoo artist or that you drew yourself. The tattoo allows you to store a psychic thought or impression within it used to cast a Focus Point spell or amp. You can use the Activate action to release the stored psychic energy, allowing you to amp a psi cantrip without spending a Focus Point. You can\'t activate the tattoo if you\'ve Unleashed your Psyche. Once activated, the tattoo is dormant until your next daily preparations.',
    implemented: 'full',
    traits: ['Uncommon', 'Invested', 'Psychic', 'Tattoo'],
    actionCost: 'free',
    mechanics: 'Once per day: amp a psi cantrip without spending FP. Can\'t use while Psyche Unleashed.',
  },
  {
    id: 'psychic-psi-strikes',
    name: 'Psi Strikes',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'You\'ve learned to channel psychic energy into your physical attacks. Your unarmed attacks and attacks with weapons of the simple weapon group deal an extra 1 mental damage. This increases to 2 extra damage if you have a striking rune on your weapon (or its handwraps of mighty blows equivalent) and to 3 extra damage if you have a major striking rune.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Simple weapons + unarmed: +1 mental damage (+2 striking, +3 major striking).',
  },
  {
    id: 'psychic-thoughtform-summoning',
    name: 'Thoughtform Summoning',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'You can manifest creatures from the hidden recesses of your mind. When you cast summon construct, summon elemental, or summon fey, the creature you summon can be a psychic thoughtform of the appropriate type. Thoughtform summoned creatures have the occult trait in addition to their other traits, and they have an appearance consistent with your conscious mind. The summoned creature gains resistance to physical damage equal to its level.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    prerequisites: ['You can cast summon construct, summon elemental, or summon fey'],
    mechanics: 'Summoned creatures become thoughtforms: gain occult trait + resistance to physical damage = level.',
  },
  {
    id: 'psychic-violent-unleash',
    name: 'Violent Unleash',
    source: 'Dark Archive',
    category: 'class',
    level: 4,
    description: 'When you Unleash your Psyche, the explosive wave of psychic energy deals damage to nearby foes. When you Unleash your Psyche, you can choose to deal 1d6 mental damage per spell rank of your highest-rank spell slot to all enemies within a 20-foot emanation (basic Will save). On a failure, a creature is also stunned 1.',
    implemented: 'full',
    traits: ['Occult', 'Psychic'],
    actionCost: 'passive',
    mechanics: 'When Unleashing Psyche: 1d6 mental per highest spell rank in 20-ft emanation (basic Will). Failure: also stunned 1.',
  },
  // ── Level 6 ── (5 feats)
  {
    id: 'psychic-inertial-barrier',
    name: 'Inertial Barrier',
    source: 'Dark Archive',
    category: 'class',
    level: 6,
    description: 'You maintain a barrier of telekinetic force that protects you from harm. You gain resistance 2 to physical damage. While your Psyche is Unleashed, the resistance is equal to your level.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Resistance 2 to physical damage. While Psyche Unleashed: resistance = level.',
  },
  {
    id: 'psychic-parallel-breakthrough',
    name: 'Parallel Breakthrough',
    source: 'Dark Archive',
    category: 'class',
    level: 6,
    description: 'You expand your psi cantrip repertoire by reaching out to a consciousness of a different psychic of a different conscious mind. Choose a conscious mind other than your own. You gain the unique psi cantrip for that conscious mind.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Choose another conscious mind. Gain its unique psi cantrip.',
    subChoices: { label: 'Choose a conscious mind', options: [
      { id: 'the-distant-grasp', name: 'The Distant Grasp', description: 'Telekinetic Rend psi cantrip' },
      { id: 'the-infinite-eye', name: 'The Infinite Eye', description: 'Redistribute Potential psi cantrip' },
      { id: 'the-oscillating-wave', name: 'The Oscillating Wave', description: 'Thermal Stasis psi cantrip' },
      { id: 'the-silent-whisper', name: 'The Silent Whisper', description: 'Shatter Mind psi cantrip' },
      { id: 'the-tangible-dream', name: 'The Tangible Dream', description: 'Imaginary Weapon psi cantrip' },
      { id: 'the-unbound-step', name: 'The Unbound Step', description: 'Warp Space psi cantrip' },
    ] },
  },
  {
    id: 'psychic-sixth-sense',
    name: 'Sixth Sense',
    source: 'Dark Archive',
    category: 'class',
    level: 6,
    description: 'Your psychic abilities also grant you an awareness of the magical and spiritual world. You can sense magical auras and spiritual presences around you. You automatically detect the presence of any magic within 30 feet, though you don\'t learn any details about the magic until you Identify Magic or use another means of discovery. This doesn\'t let you sense hazards or creatures unless they are entirely composed of magical energy. If your Perception proficiency rank is expert, you gain a +1 status bonus to your checks to Identify Magic.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Auto-detect magic within 30 ft (no details). +1 status to Identify Magic if Perception expert.',
  },
  {
    id: 'psychic-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Dark Archive',
    category: 'class',
    level: 6,
    description: 'You don\'t lose spells easily. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn\'t disrupted.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'DC 15 flat check to avoid spellcasting disruption from reactions.',
  },
  {
    id: 'psychic-strain-mind',
    name: 'Strain Mind',
    source: 'Dark Archive',
    category: 'class',
    level: 6,
    description: 'You push your mind past safe limits but can achieve incredible feats by doing so. You can cast one additional spell that is 2 or more ranks lower than the highest-rank spell you can cast. After casting this strain spell, you become stupefied 1 (or increase your stupefied condition by 1). You can\'t reduce the stupefied condition from Strain Mind until you Refocus or until your next daily preparations.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Cast 1 extra spell (2+ ranks lower than max). Become stupefied 1 (can\'t reduce until Refocus/daily prep).',
  },
  // ── Level 8 ── (6 feats)
  {
    id: 'psychic-brain-drain',
    name: 'Brain Drain',
    source: 'Dark Archive',
    category: 'class',
    level: 8,
    description: 'With a wracking bolt of thought, you drain knowledge from a foe\'s mind. You target one creature within 30 feet and deal 5d6 mental damage, with a basic Will save against your spell DC. If the creature fails this save, you can also have it become stupefied 1 for 1 minute. You gain the knowledge the creature loses — you choose one skill in which the creature is trained. For 1 minute, you become trained in that skill if you weren\'t already and gain a +1 status bonus to checks with it.',
    implemented: 'full',
    traits: ['Occult', 'Psyche', 'Psychic'],
    actionCost: 2,
    mechanics: '30 ft, 5d6 mental (basic Will). Failure: stupefied 1 (1 min). You become trained in chosen skill (+1 status) for 1 min.',
    subChoices: { label: 'Choose a skill', options: [
      { id: 'acrobatics', name: 'Acrobatics' },
      { id: 'arcana', name: 'Arcana' },
      { id: 'athletics', name: 'Athletics' },
      { id: 'crafting', name: 'Crafting' },
      { id: 'deception', name: 'Deception' },
      { id: 'diplomacy', name: 'Diplomacy' },
      { id: 'intimidation', name: 'Intimidation' },
      { id: 'medicine', name: 'Medicine' },
      { id: 'nature', name: 'Nature' },
      { id: 'occultism', name: 'Occultism' },
      { id: 'performance', name: 'Performance' },
      { id: 'religion', name: 'Religion' },
      { id: 'society', name: 'Society' },
      { id: 'stealth', name: 'Stealth' },
      { id: 'survival', name: 'Survival' },
      { id: 'thievery', name: 'Thievery' },
    ] },
  },
  {
    id: 'psychic-dark-personas-presence',
    name: "Dark Persona's Presence",
    source: 'Dark Archive',
    category: 'class',
    level: 8,
    description: 'When you Unleash your Psyche, a dark side of your personality rises to the surface and unsettles those around you. When you Unleash your Psyche, you can choose to emit a 20-foot aura for the duration. Enemies that begin their turn within the aura or enter it must attempt a Will save against your spell DC. On a failure, they are frightened 1 (frightened 2 on a critical failure). A creature that succeeds at its save is temporarily immune for 1 minute. This is an emotion, fear, and mental effect.',
    implemented: 'full',
    traits: ['Aura', 'Emotion', 'Fear', 'Mental', 'Occult', 'Psychic'],
    actionCost: 'passive',
    mechanics: 'When Unleashing Psyche: 20-ft aura. Enemies entering or starting turn: Will save or frightened 1 (crit fail: frightened 2). Success: immune 1 min.',
  },
  {
    id: 'psychic-mental-static',
    name: 'Mental Static',
    source: 'Dark Archive',
    category: 'class',
    level: 8,
    description: 'You protect an ally by disrupting a foe\'s concentration with mental noise. The triggering attack roll is compared to an AC 2 higher than the ally\'s actual AC. If this turns the hit into a miss, you can\'t use Mental Static again for 1d4 rounds.',
    implemented: 'full',
    traits: ['Concentrate', 'Occult', 'Psychic'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: An ally within 30 feet is hit or critically hit by an attack'],
    mechanics: 'Reaction: treat ally\'s AC as +2 vs triggering attack. If this changes hit→miss, can\'t use again for 1d4 rounds.',
  },
  {
    id: 'psychic-remove-presence',
    name: 'Remove Presence',
    source: 'Dark Archive',
    category: 'class',
    level: 8,
    description: 'You shroud your psychic signature, making it harder for others to notice you. You are concealed. This concealment can\'t be used to Hide or Sneak. If you take a hostile action, the concealment ends and you can\'t use Remove Presence again for 10 minutes.',
    implemented: 'full',
    traits: ['Illusion', 'Occult', 'Psyche', 'Psychic'],
    actionCost: 1,
    mechanics: 'Concealed (can\'t Hide/Sneak). Ends on hostile action; 10-minute cooldown.',
  },
  {
    id: 'psychic-thoughtsense',
    name: 'Thoughtsense',
    source: 'Dark Archive',
    category: 'class',
    level: 8,
    description: 'You can detect the psychic signatures of conscious creatures around you. You gain an imprecise thoughtsense with a range of 30 feet. This allows you to sense any non-mindless creature within range, even if a creature is invisible or otherwise undetectable to your other senses. This sense doesn\'t allow you to differentiate between creatures — just to detect the presence of a mind.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Imprecise thoughtsense 30 ft. Detects non-mindless creatures (even invisible). Can\'t differentiate creatures.',
  },
  {
    id: 'psychic-whispering-steps',
    name: 'Whispering Steps',
    source: 'Dark Archive',
    category: 'class',
    level: 8,
    description: 'The world is full of murmuring spirits and the remnants of thoughts whose echoes are caught in stone and soil. You gain a +2 status bonus to Survival checks to Sense Direction and to Track, and you don\'t take penalties to Track for the passage of time, extinguished tracks, or obscured tracks unless caused by an effect of a higher rank than half your level. While your Psyche is Unleashed, you additionally gain imprecise tremorsense with a range of 30 feet.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: '+2 status to Sense Direction and Track. Ignore time/track penalties ≤ half level rank. Psyche Unleashed: 30-ft tremorsense.',
  },
// ── Level 10 ── (5 feats)
  {
    id: 'psychic-dream-guise',
    name: 'Dream Guise',
    source: 'Dark Archive',
    category: 'class',
    level: 10,
    description: 'While your mind wanders in a reverie, your body language and mannerisms change to match the creatures around you. When your Psyche is Unleashed, you can take on a dream guise by spending 1 action. You look, sound, and smell like a typical member of one species of creatures within 30 feet of you, gaining a +4 status bonus to Impersonate checks to pretend to be that type of creature. This doesn\'t change your actual size, and identifying you as unusual requires the creature to attempt a Perception check against your Deception DC. This effect lasts until your unleashed psyche subsides.',
    implemented: 'full',
    traits: ['Illusion', 'Mental', 'Occult', 'Psychic'],
    actionCost: 1,
    prerequisites: ['Subconscious mind: Wandering Reverie'],
    mechanics: 'While Psyche Unleashed: 1 action to disguise as creature type within 30 ft. +4 status to Impersonate. Lasts until Psyche subsides.',
  },
  {
    id: 'psychic-emotional-surge',
    name: 'Emotional Surge',
    source: 'Dark Archive',
    category: 'class',
    level: 10,
    description: 'Your acceptance of emotions as a raw source of power heightens to the point where you can channel sheer feelings. When your Psyche is Unleashed and you cast a spell that has the emotion trait, you add your full casting attribute modifier to the spell\'s damage instead of half (if the spell deals damage) or gain a +1 status bonus to the spell DC (if it doesn\'t deal damage).',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    prerequisites: ['Subconscious mind: Emotional Acceptance'],
    mechanics: 'While Psyche Unleashed: emotion spells get full attribute mod to damage (instead of half) or +1 status to spell DC.',
  },
  {
    id: 'psychic-impose-order',
    name: 'Impose Order (Psychic)',
    source: 'Dark Archive',
    category: 'class',
    level: 10,
    description: 'You bring discipline to a chaotic situation. When your Psyche is Unleashed, you can spend 2 actions to impose psychic order. Each ally within 30 feet can immediately attempt a new saving throw against one mental effect currently affecting them, with a +2 circumstance bonus. This is a fortune effect. After using Impose Order, you can\'t use it again for 10 minutes.',
    implemented: 'full',
    traits: ['Fortune', 'Mental', 'Occult', 'Psyche', 'Psychic'],
    actionCost: 2,
    prerequisites: ['Subconscious mind: Precise Discipline'],
    mechanics: 'While Psyche Unleashed: allies within 30 ft get new save (+2 circumstance) vs one mental effect. Fortune. 10-min cooldown.',
  },
  {
    id: 'psychic-scour-the-library',
    name: 'Scour the Library',
    source: 'Dark Archive',
    category: 'class',
    level: 10,
    description: 'Your repository of gathered knowledge can be quickly tapped. While your Psyche is Unleashed, once per round you can Recall Knowledge as a free action at the start of your turn. You use Occultism for this check, and you gain a +2 circumstance bonus to this check.',
    implemented: 'full',
    traits: ['Psyche', 'Psychic'],
    actionCost: 'passive',
    prerequisites: ['Subconscious mind: Gathered Lore'],
    mechanics: 'While Psyche Unleashed: free action Recall Knowledge (Occultism, +2 circumstance) once per round at start of turn.',
  },
  {
    id: 'psychic-signature-spell-expansion',
    name: 'Signature Spell Expansion',
    source: 'Dark Archive',
    category: 'class',
    level: 10,
    description: 'Your repertoire is so robust that you can quickly access a wider range of your spells. You gain one additional signature spell per spell rank for which you have psychic spell slots.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    prerequisites: ['Signature spells'],
  },
  // ── Level 12 ── (4 feats)
  {
    id: 'psychic-amp-focus',
    name: 'Amp Focus',
    source: 'Dark Archive',
    category: 'class',
    level: 12,
    description: 'Your amps have been refined, allowing you to maintain them for longer periods. You gain an additional Focus Point, increasing your focus pool to a maximum of 3 Focus Points.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: '+1 Focus Point. Maximum focus pool: 3.',
  },
  {
    id: 'psychic-foreseen-failure',
    name: 'Foreseen Failure',
    source: 'Dark Archive',
    category: 'class',
    level: 12,
    description: 'You glimpse the future and see the triggering spell failing. You can attempt a countercheck against the triggering spell with a +2 circumstance bonus.',
    implemented: 'full',
    traits: ['Concentrate', 'Fortune', 'Occult', 'Psychic'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: A creature within 30 feet that you can observe Casts a Spell'],
    mechanics: 'Reaction: counteract triggering spell with +2 circumstance bonus. Fortune trait.',
  },
  {
    id: 'psychic-no',
    name: 'No!!!',
    source: 'Dark Archive',
    category: 'class',
    level: 12,
    description: 'You psychically scream a defensive thought with such force that it disrupts an attack against an ally. An ally within 30 feet who is hit by an attack gains resistance to all damage against the triggering attack equal to 2 + your level. At 18th level, the resistance increases to 4 + your level.',
    implemented: 'full',
    traits: ['Concentrate', 'Mental', 'Occult', 'Psychic'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: An ally within 30 feet is hit by an attack'],
    mechanics: 'Reaction: ally gains resistance to all damage vs triggering attack = 2 + level. At 18th level: 4 + level.',
  },
  {
    id: 'psychic-psi-catastrophe',
    name: 'Psi Catastrophe',
    source: 'Dark Archive',
    category: 'class',
    level: 12,
    description: 'When your unleashed psyche subsides, you direct the explosive release of energy to harm your foes. When your unleashed psyche subsides (other than due to falling unconscious), you can direct a catastrophic wave of psychic energy at foes. Each enemy within a 30-foot emanation takes 1d6 mental damage per spell rank of your highest-rank spell slot (basic Will save against your spell DC). A creature that fails the save is additionally stunned 1 (stunned 2 on a critical failure).',
    implemented: 'full',
    traits: ['Mental', 'Occult', 'Psychic'],
    actionCost: 'passive',
    mechanics: 'When Psyche subsides: 30-ft emanation, 1d6 mental per highest spell rank (basic Will). Failure: stunned 1 (crit fail: stunned 2).',
  },
  // ── Level 14 ── (3 feats)
  {
    id: 'psychic-conscious-spell-specialization',
    name: 'Conscious Spell Specialization',
    source: 'Dark Archive',
    category: 'class',
    level: 14,
    description: 'You\'ve delved deeper into the manifestation of your conscious mind. You gain a focus spell based on your conscious mind. The Distant Grasp gains telekinetic assault, The Infinite Eye gains eye of the oracle, The Oscillating Wave gains thermal stasis, The Silent Whisper gains mind\'s echo, The Tangible Dream gains dream passage, The Unbound Step gains tesseract tunnel. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Gain a focus spell from your conscious mind. +1 Focus Point.',
  },
  {
    id: 'psychic-deep-roots',
    name: 'Deep Roots',
    source: 'Dark Archive',
    category: 'class',
    level: 14,
    description: 'Your Psyche reaches deep into the soil of your subconscious, bolstering your resilience. When your Psyche is Unleashed, you gain a +2 circumstance bonus to saves against effects with the mental trait. When you successfully save against a mental effect while your Psyche is Unleashed, you can immediately Recall Knowledge about the creature that created the mental effect as a free action.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'While Psyche Unleashed: +2 circumstance to saves vs mental. On successful save vs mental: free Recall Knowledge about source.',
  },
  {
    id: 'psychic-shatter-space',
    name: 'Shatter Space',
    source: 'Dark Archive',
    category: 'class',
    level: 14,
    description: 'You can rip the fabric of space with your psychic power, creating a hazardous zone. You shatter a 20-foot burst within 120 feet into a bizarre spatial fracture. Each creature in the area takes 10d6 slashing damage (basic Reflex save against your spell DC). The fractured space then becomes difficult terrain for 1 minute. A creature that enters the area or ends its turn there takes 3d6 slashing damage (basic Reflex save). You can\'t use Shatter Space again for 1d4 rounds.',
    implemented: 'full',
    traits: ['Occult', 'Psyche', 'Psychic'],
    actionCost: 3,
    mechanics: '20-ft burst in 120 ft: 10d6 slashing (basic Reflex). Area becomes difficult terrain (1 min): 3d6 slashing per entry/end. 1d4 round cooldown.',
  },
// ── Level 16 ── (3 feats)
  {
    id: 'psychic-constant-levitation',
    name: 'Constant Levitation',
    source: 'Dark Archive',
    category: 'class',
    level: 16,
    description: 'You can levitate at all times without any effort. You gain a fly Speed equal to your Speed. While your Psyche is Unleashed, your fly Speed increases by 10 feet.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Fly Speed = Speed. Psyche Unleashed: fly Speed +10 ft.',
  },
  {
    id: 'psychic-target-of-psychic-ire',
    name: 'Target of Psychic Ire',
    source: 'Dark Archive',
    category: 'class',
    level: 16,
    description: 'You turn your concentrated fury against a single target and overwhelm their mind. Choose a creature within 60 feet. The creature must attempt a Will save against your spell DC. Regardless of the result, the creature is then temporarily immune for 1 day. Critical Success: The creature is unaffected. Success: The creature takes 6d6 mental damage. Failure: The creature takes 12d6 mental damage and is stunned 1. Critical Failure: The creature takes 12d6 mental damage and is stunned 3.',
    implemented: 'full',
    traits: ['Concentrate', 'Mental', 'Occult', 'Psyche', 'Psychic'],
    actionCost: 2,
    mechanics: '60 ft, Will save. Success: 6d6 mental. Failure: 12d6 mental + stunned 1. Crit Fail: 12d6 + stunned 3. 1/day per target.',
  },
  {
    id: 'psychic-wandering-thoughts',
    name: 'Wandering Thoughts',
    source: 'Dark Archive',
    category: 'class',
    level: 16,
    description: 'Your mind drifts across the psychic landscape, passively absorbing the information it encounters. For the purpose of using Recall Knowledge, you are trained in all Lore skills. While your Psyche is Unleashed, you\'re an expert instead. You can use Occultism instead of a specific Lore skill for the Recall Knowledge check, using the higher of the two.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Trained in all Lore (Expert while Psyche Unleashed). Can use Occultism for Recall Knowledge in place of Lore.',
  },
  // ── Level 18 ── (3 feats)
  {
    id: 'psychic-all-in-your-head',
    name: 'All in your Head',
    source: 'Dark Archive',
    category: 'class',
    level: 18,
    description: 'You use your psychic powers to convince yourself you\'re not hurt, healing your body through the power of belief alone. You regain 5d10+40 Hit Points and gain a +4 status bonus to saving throws against mental effects for 1 round. You can\'t use All in your Head again for 10 minutes.',
    implemented: 'full',
    traits: ['Concentrate', 'Healing', 'Mental', 'Occult', 'Psyche', 'Psychic'],
    actionCost: 1,
    mechanics: 'Heal 5d10+40 HP. +4 status to saves vs mental for 1 round. 10-min cooldown.',
  },
  {
    id: 'psychic-cranial-detonation',
    name: 'Cranial Detonation',
    source: 'Dark Archive',
    category: 'class',
    level: 18,
    description: 'You focus so much psychic energy into a creature\'s head that it explodes in a shower of gore. Target one creature within 60 feet. It takes 8d12 mental damage with a basic Will save against your spell DC. If the creature is reduced to 0 Hit Points, its head explodes, killing it instantly unless it can survive without a head. You can\'t use Cranial Detonation again for 1d4 rounds.',
    implemented: 'full',
    traits: ['Death', 'Mental', 'Occult', 'Psyche', 'Psychic'],
    actionCost: 2,
    mechanics: '60 ft, 8d12 mental (basic Will). If reduced to 0 HP: head explodes (instant death unless can survive headless). 1d4 round cooldown.',
  },
  {
    id: 'psychic-twin-psyche',
    name: 'Twin Psyche',
    source: 'Dark Archive',
    category: 'class',
    level: 18,
    description: 'You split your psyche into two autonomous parts, each capable of directing psychic magic. When you Unleash your Psyche, your psyche splits, and you gain an additional 3 actions that you can use only for psyche actions or to Cast a Spell using your psychic spellcasting. All your other turn actions still proceed as normal.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'When Psyche Unleashed: gain 3 extra actions (only for psyche actions or psychic spellcasting).',
  },
  // ── Level 20 ── (4 feats)
  {
    id: 'psychic-automatic-psychic-action',
    name: 'Automatic Psychic Action',
    source: 'Dark Archive',
    category: 'class',
    level: 20,
    description: 'Your power wants to be free. You\'re permanently quickened, and can use the additional action only for psyche actions.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'Permanently quickened. Extra action usable only for psyche actions (feats with the Psyche trait).',
  },
  {
    id: 'psychic-become-thought',
    name: 'Become Thought',
    source: 'Dark Archive',
    category: 'class',
    level: 20,
    description: 'You shed your physical body and become a being of pure psychic energy. You gain the incorporeal trait, a fly Speed of 60 feet, and immunity to disease and poison, but you can no longer eat, drink, sleep, or breathe. Once per day, you can shift back to your physical form for 10 minutes. In your incorporeal form, you can pass through solid objects but can\'t end your turn inside one. Your spells gain the incorporeal trait while you\'re incorporeal.',
    implemented: 'full',
    traits: ['Occult', 'Polymorph', 'Psychic', 'Transmutation'],
    actionCost: 'passive',
    mechanics: 'Permanent incorporeal: fly 60 ft, immune to disease/poison. Physical form 10 min/day. Can pass through objects.',
  },
  {
    id: 'psychic-mind-over-matter',
    name: 'Mind over Matter',
    source: 'Dark Archive',
    category: 'class',
    level: 20,
    description: 'Your mind is so powerful it can overcome the limits of the physical. You gain an additional 10th-rank spell slot. At the start of each day during daily preparations, you choose whether to fill this slot with a 10th-rank occult spell or to leave it empty and have it serve as an additional slot for your Infinite Mind class feature.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    prerequisites: ['Infinite Mind'],
    mechanics: 'Additional 10th-rank spell slot (choose 10th-rank occult spell or extra Infinite Mind slot daily).',
    subChoices: { label: 'Choose daily slot use', options: [
      { id: 'occult-spell', name: '10th-Rank Occult Spell', description: 'Fill the slot with a 10th-rank occult spell' },
      { id: 'infinite-mind', name: 'Infinite Mind Slot', description: 'Leave empty as an additional Infinite Mind slot' },
    ] },
  },
  {
    id: 'psychic-unlimited-potential',
    name: 'Unlimited Potential',
    source: 'Dark Archive',
    category: 'class',
    level: 20,
    description: 'Your psychic power has reached its ultimate expression. When you Unleash your Psyche, you regain all your Focus Points and immediately amp a psi cantrip as a free action. While your Psyche is Unleashed, you don\'t need to spend a Focus Point to amp a psi cantrip, though you can still use only one amp per psi cantrip.',
    implemented: 'full',
    traits: ['Psychic'],
    actionCost: 'passive',
    mechanics: 'On Unleash Psyche: refill Focus Pool + free amp. While Unleashed: amp without spending FP (1 amp per cantrip).',
  },
];
