/**
 * Ranger Class Features & Feats — PF2e Remastered (Player Core)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=9
 *
 * Key Attribute: Strength or Dexterity
 * HP: 10 + CON
 * Perception: Expert → Master (L7) → Legendary (L15)
 * Fort: Expert → Master (L11, Warden's Endurance, success→crit)
 * Reflex: Expert → Master (L7, Natural Reflexes, success→crit) → Legendary (L15, Greater Natural Reflexes)
 * Will: Trained → Expert (L3, Will Expertise)
 * Weapons: Trained simple/martial/unarmed → Expert (L5) → Master (L13)
 * Armor: Trained light/medium/unarmored → Expert (L11) → Master (L19)
 * Class DC: Trained → Expert (L9) → Master (L17)
 *
 * Hunter's Edge options:
 *   Flurry   — reduced MAP vs hunted prey (–3/–6, agile –2/–4)
 *   Outwit   — +2 circumstance to Deception/Intimidation/Stealth/Recall Knowledge vs prey, +1 AC vs prey
 *   Precision — first hit per round deals +1d8 precision (→ 2d8 at L11, → 3d8 at L19)
 *
 * Warden Spells: Primal focus spells gained via the Initiate Warden → Advanced → Masterful → Peerless chain.
 *   Spellcasting attribute: Wisdom. Focus pool scales with number of warden spells (max 3).
 *
 * Class features: 20 (L1–L19) — 18 inline + 2 CCF (Weapon Specialization L7, Greater Weapon Specialization L15)
 * Class feats: 56 (L1–L20)
 */

import type { FeatEntry } from './featTypes';
import { TERRAIN_OPTIONS } from './subChoiceOptions';
import {
  createClassFeature,
  WEAPON_SPECIALIZATION,
  GREATER_WEAPON_SPECIALIZATION,
} from './sharedFeats';

// ──────────────────────────────────────────────────────────
// RANGER CLASS FEATURES (Automatically Granted)
// ──────────────────────────────────────────────────────────

export const RANGER_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──
  {
    id: 'ranger-hunt-prey',
    name: 'Hunt Prey',
    source: 'Ranger',
    category: 'class_feature',
    level: 1,
    description: 'When you focus your attention on a single foe, you become unstoppable in your pursuit. You gain the Hunt Prey action. You designate a single creature as your prey and focus your attacks against that creature. You must be able to see or hear the prey, or you must be tracking the prey during exploration. You gain a +2 circumstance bonus to Perception checks when you Seek your prey and a +2 circumstance bonus to Survival checks when you Track your prey. You also ignore the penalty for making ranged attacks within your second range increment against the prey you\'re hunting. You can have only one creature designated as your prey at a time. If you use Hunt Prey against a creature when you already have a creature designated, the prior creature loses the designation and the new prey gains the designation. Your designation lasts until your next daily preparations.',
    implemented: 'full',
    traits: ['Concentrate', 'Ranger'],
    actionCost: 1,
    mechanics: '+2 circumstance to Seek and Track prey. Ignore 2nd range increment penalty vs prey. 1 prey at a time, lasts until daily prep.',
  },
  {
    id: 'ranger-hunters-edge',
    name: "Hunter's Edge",
    source: 'Ranger',
    category: 'class_feature',
    level: 1,
    description: 'You have trained to become a skilled hunter and tracker, gaining an extra benefit when you Hunt Prey depending on the focus of your training. Choose a hunter\'s edge: Flurry (your multiple attack penalty for attacks against your hunted prey is –3/–6, or –2/–4 with an agile weapon), Outwit (you gain a +2 circumstance bonus to Deception, Intimidation, Stealth, and Recall Knowledge checks against your prey, and a +1 circumstance bonus to AC against your prey\'s attacks), or Precision (the first time you hit your hunted prey in a round, you deal 1d8 additional precision damage; this increases to 2d8 at 11th level and 3d8 at 19th level).',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Choose Flurry (MAP –3/–6, agile –2/–4), Outwit (+2 skills/+1 AC vs prey), or Precision (+1d8/+2d8/+3d8 first hit per round).',
    subChoices: { label: "Choose a hunter's edge", options: [
      { id: 'flurry', name: 'Flurry', description: 'Multiple attack penalty vs prey is –3/–6 (–2/–4 with agile)' },
      { id: 'outwit', name: 'Outwit', description: '+2 circumstance to Deception/Intimidation/Stealth/Recall Knowledge vs prey, +1 AC' },
      { id: 'precision', name: 'Precision', description: '+1d8 precision damage on first hit per round (scales to 2d8/3d8)' },
    ] },
  },
  // ── Level 3 ──
  {
    id: 'ranger-will-expertise',
    name: 'Will Expertise',
    source: 'Ranger',
    category: 'class_feature',
    level: 3,
    description: 'Your mental defenses grow stronger. Your proficiency rank for Will saves increases to expert.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  // ── Level 5 ──
  {
    id: 'ranger-weapon-expertise',
    name: 'Ranger Weapon Expertise',
    source: 'Ranger',
    category: 'class_feature',
    level: 5,
    description: 'You gain every advantage from your weapons. Your proficiency rank for martial weapons, simple weapons, and unarmed attacks increases to expert. You gain access to the critical specialization effects of all such weapons and unarmed attacks when attacking your hunted prey.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Weapons → expert. Critical specialization effects activate only vs hunted prey.',
  },
  {
    id: 'ranger-trackless-journey',
    name: 'Trackless Journey',
    source: 'Ranger',
    category: 'class_feature',
    level: 5,
    description: 'When you move through natural terrains, you are hard to track. You always gain the benefits of the Cover Tracks action in such terrains, without moving at half your Speed.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  // ── Level 7 ──
  {
    id: 'ranger-natural-reflexes',
    name: 'Natural Reflexes',
    source: 'Ranger',
    category: 'class_feature',
    level: 7,
    description: 'You\'ve honed your reflexes dodging falling trees and pounding hail. Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Reflex → master. Success on Reflex saves → critical success.',
  },
  {
    id: 'ranger-perception-mastery',
    name: 'Perception Mastery',
    source: 'Ranger',
    category: 'class_feature',
    level: 7,
    description: 'You have highly developed acuity and attention to detail. Your proficiency rank for Perception increases to master.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  createClassFeature(WEAPON_SPECIALIZATION, 'Ranger', 7),
  // ── Level 9 ──
  {
    id: 'ranger-natures-edge',
    name: "Nature's Edge",
    source: 'Ranger',
    category: 'class_feature',
    level: 9,
    description: 'You always find the weak points in your foes\' defenses when they\'re on unfavorable terrain. Enemies are off-guard to you if they\'re in difficult terrain.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'All enemies in difficult terrain are off-guard to you (–2 AC).',
  },
  {
    id: 'ranger-ranger-expertise',
    name: 'Ranger Expertise',
    source: 'Ranger',
    category: 'class_feature',
    level: 9,
    description: 'You\'ve gained techniques that improve your cunning and skill. Your proficiency rank for your ranger class DC increases to expert. If you have warden spells, your proficiency rank for spell attacks and spell DCs increases to expert.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  // ── Level 11 ──
  {
    id: 'ranger-wardens-endurance',
    name: "Warden's Endurance",
    source: 'Ranger',
    category: 'class_feature',
    level: 11,
    description: 'You shake off a grizzly\'s grab or a poison\'s ill effects with equal ease. Your proficiency rank for Fortitude saves increases to master. When you roll a success on a Fortitude save, you get a critical success instead.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Fortitude → master. Success on Fortitude saves → critical success.',
  },
  {
    id: 'ranger-medium-armor-expertise',
    name: 'Medium Armor Expertise',
    source: 'Ranger',
    category: 'class_feature',
    level: 11,
    description: 'You\'ve learned to defend yourself better against attacks. Your proficiency ranks for light armor, medium armor, and unarmored defense increase to expert.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  {
    id: 'ranger-unimpeded-journey',
    name: 'Unimpeded Journey',
    source: 'Ranger',
    category: 'class_feature',
    level: 11,
    description: 'You move quickly through obstacles, whether they\'re tumbled stone or tangled undergrowth. You can ignore the effects of difficult terrain. As normal for ignoring difficult terrain, this also lets you treat the hindrances of greater difficult terrain as those of difficult terrain.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Ignore difficult terrain. Greater difficult terrain treated as difficult terrain.',
  },
  // ── Level 13 ──
  {
    id: 'ranger-martial-weapon-mastery',
    name: 'Martial Weapon Mastery',
    source: 'Ranger',
    category: 'class_feature',
    level: 13,
    description: 'You fully understand the intricacies of weapons. Your proficiency ranks for unarmed attacks, simple weapons, and martial weapons increase to master.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  // ── Level 15 ──
  {
    id: 'ranger-greater-natural-reflexes',
    name: 'Greater Natural Reflexes',
    source: 'Ranger',
    category: 'class_feature',
    level: 15,
    description: 'You avoid explosions with reflexes a cat would envy. Your proficiency rank for Reflex saves increases to legendary. When you roll a critical failure on a Reflex save, you get a failure instead. When you fail a Reflex save against an effect that deals damage, you halve the damage you take.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Reflex → legendary. Critical failure → failure. Half damage on failed Reflex saves.',
  },
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Ranger', 15),
  {
    id: 'ranger-perception-legend',
    name: 'Perception Legend',
    source: 'Ranger',
    category: 'class_feature',
    level: 15,
    description: 'You notice the almost imperceptible. Your proficiency rank for Perception increases to legendary.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  // ── Level 17 ──
  {
    id: 'ranger-masterful-hunter',
    name: 'Masterful Hunter',
    source: 'Ranger',
    category: 'class_feature',
    level: 17,
    description: 'You have honed your abilities as a hunter to incredible levels. Your proficiency rank for your ranger class DC increases to master. If you have warden spells, your proficiency rank for spell attacks and spell DCs increases to master. When using a ranged weapon that you have master proficiency in, you can ignore the penalty if attacking your hunted prey within the weapon\'s second and third range increments. If you have master proficiency in Perception, you gain a +4 circumstance bonus to Perception checks when you Seek your prey, and if you have master proficiency in Survival, you gain a +4 circumstance bonus to Survival checks when you Track your prey. You also gain an additional benefit depending on your hunter\'s edge. Flurry: your MAP becomes –2/–4 (–1/–2 agile) with master weapon proficiency. Outwit: skill bonuses increase to +4 and AC bonus to +2 with master proficiency. Precision: second hit also deals 1d8 precision (2d8 at 19th), third hit at 19th deals 1d8.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Class DC → master. Warden spell proficiency → master. Ignore 2nd+3rd range increment penalties. Seek/Track bonus → +4. Upgrades hunter\'s edge.',
  },
  // ── Level 19 ──
  {
    id: 'ranger-medium-armor-mastery',
    name: 'Medium Armor Mastery',
    source: 'Ranger',
    category: 'class_feature',
    level: 19,
    description: 'Your skill with light and medium armor improves, increasing your ability to avoid blows. Your proficiency ranks for light and medium armor, as well as for unarmored defense, increase to master.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  {
    id: 'ranger-swift-prey',
    name: 'Swift Prey',
    source: 'Ranger',
    category: 'class_feature',
    level: 19,
    description: 'You size up your prey with a glance. You can use Hunt Prey as a free action if it\'s your first action of your turn.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Hunt Prey becomes a free action if it\'s first action of turn.',
  },
];

// ──────────────────────────────────────────────────────────
// RANGER CLASS FEATS (Selectable)
// ──────────────────────────────────────────────────────────

export const RANGER_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ── (6 feats)
  {
    id: 'ranger-animal-companion',
    name: 'Animal Companion',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You gain the service of a young animal companion that travels with you on your adventures and obeys any simple commands you give it to the best of its abilities. When you Hunt Prey, your animal companion gains the action\'s benefits and your hunter\'s edge benefit if you have one.',
    implemented: 'full',
    traits: ['Druid', 'Ranger'],
    actionCost: 'passive',
  },
  {
    id: 'ranger-crossbow-ace',
    name: 'Crossbow Ace',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'Your deep understanding of the crossbow allows you to reload efficiently while moving yourself out of the line of return fire. Either Create a Diversion or Take Cover, then Interact to reload. As normal, you must meet the requirements to Take Cover; you must be prone, benefiting from cover, or near a feature that allows you to Take Cover.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 1,
    prerequisites: ['You are wielding a crossbow with reload 1 or higher'],
  },
  {
    id: 'ranger-hunted-shot',
    name: 'Hunted Shot',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You take two quick shots against the one you hunt. Make two Strikes against your prey with the required weapon. If both hit the same creature, combine their damage for the purpose of resistances and weaknesses. Apply your multiple attack penalty to each Strike normally.',
    implemented: 'full',
    traits: ['Flourish', 'Ranger'],
    actionCost: 1,
    prerequisites: ['You are wielding a ranged weapon with reload 0'],
  },
  {
    id: 'ranger-initiate-warden',
    name: 'Initiate Warden',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You\'ve trained with one of the ranger sects known as wardens, who practice a specialized type of primal magic. You gain your choice of one warden spell from the initial warden spells (or another you have access to). Special: You can take this feat multiple times, choosing a different initial warden spell each time.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Gain 1 initial warden spell (primal focus spell). Grants focus pool if first warden spell. Can take multiple times.',
  },
  {
    id: 'ranger-monster-hunter',
    name: 'Monster Hunter',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You quickly assess your prey and apply what you know. As part of the action used to Hunt your Prey, you can attempt a check to Recall Knowledge about your prey. When you critically succeed at identifying your hunted prey with Recall Knowledge, you note a weakness in the creature\'s defenses in addition to any other benefits. You gain a +1 circumstance bonus to your next attack roll against that prey, and any ally you tell gains the same benefit. You can give bonuses from Monster Hunter only once per day against a particular creature.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Recall Knowledge as part of Hunt Prey. Crit success: +1 circumstance to next attack for you and allies (1/day per creature).',
  },
  {
    id: 'ranger-twin-takedown',
    name: 'Twin Takedown',
    source: 'Player Core',
    category: 'class',
    level: 1,
    description: 'You swiftly attack your hunted prey with each of your weapons, potentially combining their damage into a single devastating attack. Make two Strikes against your hunted prey, one with each of the required weapons. If both hit the same hunted prey, combine their damage for the purpose of its resistances and weaknesses. Apply your multiple attack penalty to each Strike normally.',
    implemented: 'full',
    traits: ['Flourish', 'Ranger'],
    actionCost: 1,
    prerequisites: ['You are wielding two melee weapons, each in a different hand'],
  },
  // ── Level 2 ── (5 feats)
  {
    id: 'ranger-animal-empathy',
    name: 'Animal Empathy',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You have a connection to the creatures of the natural world that allows you to communicate with them on a rudimentary level. You can use Diplomacy to Make an Impression on animals and to make very simple Requests of them. In most cases, wild animals will give you time to make your case.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  {
    id: 'ranger-favored-terrain',
    name: 'Favored Terrain',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You have studied a specific terrain to overcome its challenges. Choose aquatic, arctic, desert, forest, mountain, plains, sky, swamp, or underground as your favored terrain. When in that terrain, you can ignore the effects of non-magical difficult terrain. If you have the Unimpeded Journey class feature, you gain a second benefit while in your favored terrain, depending on your choice: Aquatic (swim Speed = Speed), Arctic/Desert (eat/drink 1/10 normal, immune severe/extreme temperature, walk on ice/sand at full Speed), Forest/Mountain/Underground (climb Speed = Speed), Plains (+10-foot status to land Speed), Sky (+10-foot status to fly Speed), Swamp (move across bogs at full Speed).',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Choose terrain. Ignore non-magical difficult terrain there. With Unimpeded Journey: gain enhanced movement benefit.',
    subChoices: { label: 'Choose a terrain', options: TERRAIN_OPTIONS },
  },
  {
    id: 'ranger-hunters-aim',
    name: "Hunter's Aim",
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'When you focus on aiming, your attack becomes particularly accurate. Make a ranged weapon Strike against your hunted prey. On this Strike, you gain a +2 circumstance bonus to the attack roll and ignore your prey\'s concealed condition and any lesser cover.',
    implemented: 'full',
    traits: ['Concentrate', 'Ranger'],
    actionCost: 2,
    mechanics: 'Ranged Strike vs prey: +2 circumstance to attack, ignore concealed and lesser cover.',
  },
  {
    id: 'ranger-monster-warden',
    name: 'Monster Warden',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You understand how to defend against your prey. When you grant bonuses from Monster Hunter, each creature who benefits also gains a +2 circumstance bonus either to their AC the next time the creature attacks them or to their next saving throw against an effect from that particular creature (whichever comes first).',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Monster Hunter'],
    mechanics: 'Allies benefiting from Monster Hunter also get +2 circumstance to AC vs prey attack or next save vs prey effect.',
  },
  {
    id: 'ranger-quick-draw',
    name: 'Quick Draw',
    source: 'Player Core',
    category: 'class',
    level: 2,
    description: 'You are quick on the draw. You Interact to draw a weapon, then Strike with that weapon.',
    implemented: 'full',
    traits: ['Gunslinger', 'Ranger', 'Rogue'],
    actionCost: 1,
  },
// ── Level 4 ── (7 feats)
  {
    id: 'ranger-advanced-warden',
    name: 'Advanced Warden',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You unlock more powerful primal spells. You gain your choice of one warden spell from the advanced warden spells (or another you have access to). Special: You can take this feat multiple times, choosing a different advanced warden spell each time.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Initiate Warden'],
    mechanics: 'Gain 1 advanced warden spell. Can take multiple times.',
  },
  {
    id: 'ranger-companions-cry',
    name: "Companion's Cry",
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You can urge your companion to do its utmost. You can spend 2 actions to Command an Animal instead of 1 when commanding your animal companion. If you do, your animal companion uses an additional action.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['An animal companion'],
    mechanics: 'Spend 2 actions to Command Animal → companion gets 1 extra action.',
  },
  {
    id: 'ranger-disrupt-prey',
    name: 'Disrupt Prey',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'Make a melee Strike against your prey. If the attack is a critical hit, you disrupt the triggering action.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: Your hunted prey is within your reach, and it uses a manipulate action, uses a move action, or leaves a square during a move action it\'s using'],
    mechanics: 'Reaction: melee Strike vs prey. Critical hit disrupts their action.',
  },
  {
    id: 'ranger-far-shot',
    name: 'Far Shot',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'Your experience in the field has taught you how to focus your aim at a distance, increasing your accuracy. Double your weapons\' range increments.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  {
    id: 'ranger-favored-prey',
    name: 'Favored Prey',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You have studied a specific type of wild creature and can hunt it more easily. When you gain this feat, choose animals, beasts, dragons, or both fungi and plants as your favored prey. When you roll initiative and can see an enemy that belongs to the chosen category, you can Hunt Prey as a free action, designating that enemy. You can use this free action even if you haven\'t identified the creature yet with Recall Knowledge. The benefit doesn\'t apply against favored enemies disguised as other creatures, and the GM determines whether it applies against a creature disguised as a favored prey.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Choose creature type (animals, beasts, dragons, or fungi+plants). Free Hunt Prey on initiative if you see that type.',
    subChoices: { label: 'Choose favored prey', options: [
      { id: 'animals', name: 'Animals' },
      { id: 'beasts', name: 'Beasts' },
      { id: 'dragons', name: 'Dragons' },
      { id: 'fungi-plants', name: 'Fungi and Plants' },
    ] },
  },
  {
    id: 'ranger-running-reload',
    name: 'Running Reload',
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You can reload your weapon on the move. You Stride, Step, or Sneak, then Interact to reload.',
    implemented: 'full',
    traits: ['Gunslinger', 'Ranger'],
    actionCost: 1,
  },
  {
    id: 'ranger-scouts-warning',
    name: "Scout's Warning",
    source: 'Player Core',
    category: 'class',
    level: 4,
    description: 'You visually or audibly warn your allies of danger, granting them each a +1 circumstance bonus to their initiative rolls, or a +2 circumstance bonus if you\'re using the Scout exploration activity. Depending on whether you use gestures or call out, this action gains either the visual or the auditory trait, respectively.',
    implemented: 'full',
    traits: ['Ranger', 'Rogue'],
    actionCost: 'free',
    prerequisites: ['Trigger: You are about to roll a Perception or Survival check for initiative'],
    mechanics: 'Free action: allies get +1 circumstance to initiative (+2 if Scouting).',
  },
  // ── Level 6 ── (6 feats)
  {
    id: 'ranger-additional-recollection',
    name: 'Additional Recollection',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You scan the battlefield quickly, remembering critical details about multiple opponents you face. You immediately attempt a check to Recall Knowledge about a different creature you can perceive.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'free',
    prerequisites: ['Trigger: You succeed or critically succeed at a check to Recall Knowledge on your hunted prey'],
  },
  {
    id: 'ranger-masterful-warden',
    name: 'Masterful Warden',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'Your mastery of warden magic increases. You gain your choice of one warden spell from the master warden spells (or another you have access to). Special: You can take this feat multiple times, choosing a different master warden spell each time.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Initiate Warden'],
    mechanics: 'Gain 1 master warden spell. Can take multiple times.',
  },
  {
    id: 'ranger-mature-animal-companion',
    name: 'Mature Animal Companion',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'Your animal companion becomes a mature animal companion and gains additional capabilities. During an encounter, even if you don\'t use the Command an Animal action, your animal companion can still use 1 action that round on your turn to Strike or Stride (or Burrow, Climb, or Swim if it has that Speed). It can do this at any point during your turn, as long as you aren\'t currently taking an action. If it does, that\'s all the actions it gets that round — you can\'t Command it later.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Animal Companion'],
    mechanics: 'Companion becomes mature. Gets 1 free action per round (Strike or Stride) without Command.',
  },
  {
    id: 'ranger-skirmish-strike',
    name: 'Skirmish Strike',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'Your feet and weapon move in tandem. Either Step and then Strike, or Strike and then Step.',
    implemented: 'full',
    traits: ['Flourish', 'Ranger', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'ranger-snap-shot',
    name: 'Snap Shot',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'You can react with ranged weapons when a creature is in close quarters. You can use a reaction that normally allows you to make a melee weapon Strike to instead make a ranged weapon Strike. You must be Striking an adjacent target. If necessary for the reaction\'s trigger, you treat your ranged weapon as if it had a reach of 5 feet. If the reaction has other requirements, such as wielding a specific kind of weapon, Snap Shot doesn\'t allow you to ignore them; it allows you only to replace a melee weapon Strike with a ranged weapon Strike.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Use ranged weapon for melee-reaction Strikes against adjacent targets. Ranged weapon treated as 5-ft reach for triggers.',
  },
  {
    id: 'ranger-swift-tracker',
    name: 'Swift Tracker',
    source: 'Player Core',
    category: 'class',
    level: 6,
    description: 'Your keen eyes catch signs of passage even when you\'re moving. You can move at your full Speed while you Track. If you have master proficiency in Survival, you don\'t need to attempt a new Survival check every hour while Tracking. If you have legendary proficiency in Survival, you can use another exploration activity while Tracking. If you roll Survival for initiative while tracking your hunted prey, when you start your first turn of the encounter, you can Stride toward your hunted prey as a free action.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Expert in Survival', 'Experienced Tracker'],
    mechanics: 'Track at full Speed. Master Survival: no hourly checks. Legendary: additional exploration activity. Free Stride toward prey on initiative.',
  },
  // ── Level 8 ── (4 feats)
  {
    id: 'ranger-deadly-aim',
    name: 'Deadly Aim',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You aim for your prey\'s weak spots, making your shot more challenging but dealing more damage if you hit. Make a ranged Strike against your hunted prey at a –2 penalty. You gain a +4 circumstance bonus to damage on that Strike. This bonus increases to +6 at 11th level and +8 at 15th level.',
    implemented: 'full',
    traits: ['Flourish', 'Ranger'],
    actionCost: 1,
    prerequisites: ['Weapon Specialization'],
    mechanics: 'Ranged Strike vs prey at –2 attack for +4 damage (+6 at L11, +8 at L15).',
  },
  {
    id: 'ranger-hazard-finder',
    name: 'Hazard Finder',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You have an intuitive ability to sense hazards. You gain a +1 circumstance bonus to Perception checks to find traps and hazards, to AC against their attacks, and to saves against their effects. You can find hazards that would normally require you to Search even if you aren\'t Searching.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: '+1 circumstance to find hazards, AC vs hazards, and saves vs hazards. Find hazards without Searching.',
  },
  {
    id: 'ranger-terrain-master',
    name: 'Terrain Master',
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You are able to adapt to your surroundings in any natural terrain. You can spend 1 hour practicing in your current terrain in order to make it your favored terrain, replacing your current favored terrain temporarily. If you spend a full day out of the new favored terrain, your favored terrain reverts back to your original choice when you took the Favored Terrain feat.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Master in Survival', 'Favored Terrain'],
    mechanics: '1 hour to adopt current terrain as favored. Reverts after 1 day away.',
  },
  {
    id: 'ranger-wardens-boon',
    name: "Warden's Boon",
    source: 'Player Core',
    category: 'class',
    level: 8,
    description: 'You point out vulnerabilities present in your hunted prey, granting the benefits listed in Hunt Prey and your hunter\'s edge to an ally until the end of their next turn. Depending on whether you call out or use gestures, this action gains either the auditory or visual trait.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 1,
    mechanics: 'Grant Hunt Prey benefits + hunter\'s edge to 1 ally vs your prey until end of their next turn.',
  },
// ── Level 10 ── (4 feats)
  {
    id: 'ranger-camouflage',
    name: 'Camouflage',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You alter your appearance to blend in to the wilderness. In natural terrain, you can Hide and Sneak even without cover or being concealed.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Master in Stealth'],
  },
  {
    id: 'ranger-incredible-companion',
    name: 'Incredible Companion',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'Your animal companion continues to grow and develop. It becomes a nimble or savage animal companion (your choice), gaining additional capabilities determined by the type of companion.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Mature Animal Companion'],
    mechanics: 'Companion becomes nimble or savage.',
  },
  {
    id: 'ranger-master-monster-hunter',
    name: 'Master Monster Hunter',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'You have a nearly encyclopedic knowledge of all creatures of the world. You can use Nature to Recall Knowledge to identify any creature. In addition, you gain the benefits of Monster Hunter (and Monster Warden, if you have it) on a success as well as a critical success.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Master in Nature', 'Monster Hunter'],
    mechanics: 'Use Nature to Recall Knowledge on any creature. Monster Hunter benefits on success (not just crit success).',
  },
  {
    id: 'ranger-peerless-warden',
    name: 'Peerless Warden',
    source: 'Player Core',
    category: 'class',
    level: 10,
    description: 'Your mastery of primal magic has given you access to the greatest secrets of warden magic. You gain your choice of one warden spell from the peerless warden spells (or another you have access to). Special: You can take this feat multiple times, choosing a different peerless warden spell each time.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Initiate Warden'],
    mechanics: 'Gain 1 peerless warden spell. Can take multiple times.',
  },
  // ── Level 12 ── (5 feats)
  {
    id: 'ranger-distracting-shot',
    name: 'Distracting Shot',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'The sheer power of your attacks, or the overwhelming number of them, leaves an enemy flustered. If you critically hit your hunted prey with a ranged weapon, or hit it at least twice on the same turn with a ranged weapon, it\'s off-guard until the start of your next turn.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Crit hit or 2+ ranged hits on same turn vs prey → prey is off-guard until start of next turn.',
  },
  {
    id: 'ranger-double-prey',
    name: 'Double Prey',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'You can focus on two foes at once, hunting both of them down. When you use the Hunt Prey action, you can pick two creatures as your prey.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
  },
  {
    id: 'ranger-second-sting',
    name: 'Second Sting',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'You read your prey\'s movements and transform them into openings, so failures with one weapon set up glancing blows with the other. Make a melee Strike with one of the required weapons against your hunted prey. The Strike gains the following failure effect. Failure: You deal the damage the other required weapon would have dealt on a hit, excluding all damage dice. (This removes dice from weapon runes, spells, and special abilities, not just weapon damage dice.)',
    implemented: 'full',
    traits: ['Press', 'Ranger'],
    actionCost: 1,
    prerequisites: ['You are wielding two melee weapons, each in a different hand'],
    mechanics: 'Press Strike vs prey. On failure: deal flat damage (no dice) of other weapon.',
  },
  {
    id: 'ranger-side-by-side',
    name: 'Side by Side',
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'You and your animal companion fight in tandem. Whenever you and your animal companion are adjacent to the same foe, you are both flanking that foe with each other, regardless of your actual positions.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['An animal companion'],
    mechanics: 'You and companion always flank any foe you\'re both adjacent to.',
  },
  {
    id: 'ranger-wardens-focus',
    name: "Warden's Focus",
    source: 'Player Core',
    category: 'class',
    level: 12,
    description: 'Your connection with your surroundings deepens and expands, allowing you to draw in more of nature\'s primal power as you focus. If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Warden spells'],
    mechanics: 'Refocus recovers 2 FP if you spent 2+ FP since last Refocus.',
  },
  // ── Level 14 ── (4 feats)
  {
    id: 'ranger-sense-the-unseen',
    name: 'Sense the Unseen',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'When you look for foes, you can catch even the slightest cues, such as their minute movements or the shifting of air currents on your skin. Even though you failed at the triggering check, you automatically sense undetected creatures in the area where you Sought, making them merely hidden to you.',
    implemented: 'full',
    traits: ['Investigator', 'Ranger', 'Rogue'],
    actionCost: 'reaction',
    prerequisites: ['Trigger: You fail a check to Seek'],
    mechanics: 'Reaction on failed Seek: undetected creatures become hidden instead.',
  },
  {
    id: 'ranger-shared-prey',
    name: 'Shared Prey',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'Hunting as a duo, you and your ally both single out your prey. When you use Hunt Prey and select only one prey, you can grant your Hunt Prey benefits and hunter\'s edge to an ally in addition to gaining them yourself. The ally retains these benefits until you use Hunt Prey again.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Double Prey', "Warden's Boon"],
    mechanics: 'When hunting 1 prey: share Hunt Prey + hunter\'s edge with 1 ally permanently (until new Hunt Prey).',
  },
  {
    id: 'ranger-stealthy-companion',
    name: 'Stealthy Companion',
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'You\'ve trained your animal companion to blend in to its surroundings. Your animal companion gains the benefit of the Camouflage feat. If your companion is a specialized ambusher, its proficiency rank for Stealth increases to master (or legendary if it was already master).',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Animal Companion', 'Camouflage'],
    mechanics: 'Companion gains Camouflage. Ambusher specialization: Stealth → master (or legendary).',
  },
  {
    id: 'ranger-wardens-guidance',
    name: "Warden's Guidance",
    source: 'Player Core',
    category: 'class',
    level: 14,
    description: 'You convey your prey\'s location to your allies with a series of careful words or gestures. As long as your hunted prey is observed by you, all your allies who roll failures and critical failures when Seeking it get a success instead. Your allies need to be able to see or hear you to gain this benefit. You have to be able to call out or make visible gestures for your allies to get this benefit.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    mechanics: 'Allies\' failed/crit-failed Seek checks vs your observed prey → success.',
  },
// ── Level 16 ── (5 feats)
  {
    id: 'ranger-greater-distracting-shot',
    name: 'Greater Distracting Shot',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'Even a single missile can throw off your enemy\'s balance, and more powerful attacks leave it flustered for longer. If you hit your hunted prey with a ranged weapon, it\'s off-guard until the start of your next turn. If you critically hit your prey or hit it twice on the same turn with a ranged weapon, it\'s off-guard until the end of your next turn instead.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Distracting Shot'],
    mechanics: 'Hit prey ranged → off-guard until start of next turn. Crit or 2+ hits → off-guard until end of next turn.',
  },
  {
    id: 'ranger-improved-twin-riposte',
    name: 'Improved Twin Riposte',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'At the start of each of your turns, you gain an additional reaction that you can use only to perform a Twin Riposte. You can use Twin Riposte even if you aren\'t benefiting from Twin Parry (though you must be wielding two melee weapons, one in each hand).',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Twin Riposte'],
    mechanics: 'Extra reaction per turn (Twin Riposte only). Can Twin Riposte without Twin Parry.',
  },
  {
    id: 'ranger-legendary-monster-hunter',
    name: 'Legendary Monster Hunter',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'Your knowledge of monsters is so incredible that it reveals glaring flaws in your prey. Your bonus from Monster Hunter (and the bonus from Monster Warden if you have it) increases from +1 to +2 for you and any allies who benefit.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Nature', 'Master Monster Hunter'],
    mechanics: 'Monster Hunter/Warden bonus increases from +1 to +2.',
  },
  {
    id: 'ranger-specialized-companion',
    name: 'Specialized Companion',
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'Your animal companion continues to grow in power and ability, and it is now cunning enough to become specialized. Your animal companion gains one specialization of your choice. Special: You can select this feat up to three times. Each time, add a different specialization to your companion.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Incredible Companion'],
    mechanics: 'Companion gains 1 specialization. Can take up to 3 times.',
  },
  {
    id: 'ranger-wardens-reload',
    name: "Warden's Reload",
    source: 'Player Core',
    category: 'class',
    level: 16,
    description: 'Your mastery of magic and weapons like the crossbow allow you to wield both with equal ease. Interact to reload a weapon you are currently wielding.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'free',
    prerequisites: ['Frequency: once per round', 'Your last action or activity this turn was to cast a warden spell'],
    mechanics: 'Free action: reload after casting a warden spell. Once per round.',
  },
  // ── Level 18 ── (6 feats)
  {
    id: 'ranger-impossible-flurry',
    name: 'Impossible Flurry',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'You forgo precision to attack at an impossible speed. Make three melee Strikes with each of the required weapons. Your first attack with each weapon takes the multiple attack penalty as though you had already made one attack this turn. All of the remaining Strikes take the maximum multiple attack penalty.',
    implemented: 'full',
    traits: ['Flourish', 'Ranger'],
    actionCost: 3,
    prerequisites: ['You are wielding two melee weapons, each in a different hand'],
    mechanics: '6 total melee Strikes (3 per weapon). First of each at MAP-1, rest at max MAP.',
  },
  {
    id: 'ranger-impossible-volley',
    name: 'Impossible Volley',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'You fire a volley at all foes in an area. Make one Strike with a –2 penalty against each enemy within a 10-foot-radius burst centered at or beyond your weapon\'s volley range. Roll the damage only once for all targets. Each attack counts toward your multiple attack penalty, but do not increase your penalty until you have made all your attacks.',
    implemented: 'full',
    traits: ['Fighter', 'Flourish', 'Ranger'],
    actionCost: 3,
    prerequisites: ['You are wielding a ranged weapon with the volley trait and reload 0'],
    mechanics: 'Strike each enemy in 10-ft burst at –2. Single damage roll. MAP increments after all Strikes.',
  },
  {
    id: 'ranger-manifold-edge',
    name: 'Manifold Edge',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'You\'ve learned to leverage every possible edge. When you use Hunt Prey, you can gain a different hunter\'s edge benefit instead of the one you selected at 1st level. If you do, you don\'t gain the additional benefit from masterful hunter.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ["Hunter's edge", 'Masterful Hunter'],
    mechanics: 'When Hunting Prey: choose a different hunter\'s edge. Forfeits Masterful Hunter upgrade for that edge.',
    subChoices: { label: 'Choose alternate edge', options: [
      { id: 'flurry', name: 'Flurry', description: 'Reduced MAP for second and third attacks' },
      { id: 'precision', name: 'Precision', description: 'Extra precision damage on first hit each round' },
      { id: 'outwit', name: 'Outwit', description: '+2 circumstance to Deception, Intimidation, Stealth, Recall Knowledge vs prey' },
    ] },
  },
  {
    id: 'ranger-masterful-companion',
    name: 'Masterful Companion',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'Your animal companion shares your incredible hunting skills, allowing it to take down your shared prey with ease. When you Hunt Prey, your animal companion gains the masterful hunter benefit associated with your hunter\'s edge, rather than just your original hunter\'s edge benefit.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Masterful Hunter', 'Animal Companion'],
    mechanics: 'Companion gains Masterful Hunter edge upgrade (not just base edge).',
  },
  {
    id: 'ranger-perfect-shot',
    name: 'Perfect Shot',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'After watching the motions of combat with incredible intensity and precision, you fire at your prey at the perfect moment to deliver maximum pain. Make a ranged Strike with the required weapon against your hunted prey. If you hit, the Strike deals maximum damage. After the Strike, your turn ends.',
    implemented: 'full',
    traits: ['Flourish', 'Ranger'],
    actionCost: 3,
    prerequisites: ['You are wielding a loaded ranged weapon with reload 1 or more, and you have not reloaded your weapon since your last turn'],
    mechanics: 'Ranged Strike vs prey deals maximum damage on hit. Turn ends after Strike.',
  },
  {
    id: 'ranger-shadow-hunter',
    name: 'Shadow Hunter',
    source: 'Player Core',
    category: 'class',
    level: 18,
    description: 'You blend in to your surroundings so well that others have trouble telling you apart from the terrain. While in natural terrain, you\'re always concealed from all foes if you choose to be, except for your hunted prey.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Camouflage'],
    mechanics: 'In natural terrain: always concealed from all foes except hunted prey.',
  },
  // ── Level 20 ── (4 feats)
  {
    id: 'ranger-legendary-shot',
    name: 'Legendary Shot',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'You focus on your hunted prey, perceiving angles, air resistance, and every variable that would affect your ranged attack. If you have master proficiency with your ranged weapon, you can ignore the penalty for attacking up to five range increments away when attacking your hunted prey.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Perception', 'Far Shot'],
    mechanics: 'With master weapon proficiency: ignore range penalties up to 5th range increment vs prey.',
  },
  {
    id: 'ranger-to-the-ends-of-the-earth',
    name: 'To the Ends of the Earth',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'Your ability to track your prey has surpassed explanation, allowing you to trace your prey\'s movements and predict its location with ease. When you use Hunt Prey on a creature within 100 feet, you can follow that creature\'s movements, allowing you to know the creature\'s exact location no matter how far away it becomes, as long as it remains your prey. You must be legendary in Nature to track your prey\'s location across teleportation or planar travel. This feat gains the detection and primal traits if you\'re legendary in Nature.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Survival'],
    mechanics: 'Hunt Prey within 100 ft → know exact location at any distance. Legendary Nature: track across teleportation/planes.',
  },
  {
    id: 'ranger-triple-threat',
    name: 'Triple Threat',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'You can divide your attention three ways when hunting. When you use Hunt Prey, you can designate three creatures as prey, designate two creatures as prey and share the effect with one ally (as Shared Prey), or designate one creature as prey and share the effect with two allies.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Shared Prey'],
    mechanics: 'Hunt Prey: 3 prey, or 2 prey + 1 ally, or 1 prey + 2 allies.',
  },
  {
    id: 'ranger-ultimate-skirmisher',
    name: 'Ultimate Skirmisher',
    source: 'Player Core',
    category: 'class',
    level: 20,
    description: 'You are so skilled at navigating the wild, your movement is completely unaffected by terrain. You ignore the effects of all difficult terrain, greater difficult terrain, and hazardous terrain, and you don\'t trigger traps and hazards that are triggered by moving into an area (such as trip wires and pressure plates), unless you want to.',
    implemented: 'full',
    traits: ['Ranger'],
    actionCost: 'passive',
    prerequisites: ['Unimpeded Journey'],
    mechanics: 'Ignore all difficult/greater difficult/hazardous terrain. Don\'t trigger movement-activated traps unless desired.',
  },
];
