import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION, GREATER_WEAPON_SPECIALIZATION } from './sharedFeats';

// ————————————————————————————————————————————————————————————
// ROGUE CLASS FEATURES (Automatically Granted)
// PF2e Remaster — Player Core
// ————————————————————————————————————————————————————————————

const RAW_ROGUE_CLASS_FEATURES: FeatEntry[] = [
  // —— Level 1 ——————————————————————————————————————————————
  {
    id: 'rogues-racket',
    name: "Rogue's Racket",
    source: 'Rogue',
    category: 'class_feature',
    level: 1,
    description: "You've begun to develop your techniques and approach to a job, while building your reputation in rogues' circles. Choose a rogue's racket: Thief (Dex key, trained in Thievery, add Dex to damage with finesse melee), Ruffian (Str key, trained in Intimidation and medium armor, sneak attack with broader weapons, crit specialization on off-guard foes), Scoundrel (Cha key, trained in Deception and Diplomacy, enhanced Feint with free Step on agile/finesse), or Mastermind (Int key, trained in Society plus one of Arcana/Nature/Occultism/Religion, successful Recall Knowledge makes foe off-guard).",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Racket selection sets creature.rogueRacket field. Sneak Attack weapon eligibility in combatActions.ts:canDealSneakAttack(). Feint bonus (Scoundrel) in Feint action. Recall Knowledge (Mastermind) off-guard effect.',
    subChoices: { label: "Choose a rogue's racket", options: [
      { id: 'thief', name: 'Thief', description: 'Dex key ability; add Dex to damage with finesse melee weapons' },
      { id: 'ruffian', name: 'Ruffian', description: 'Str key ability; sneak attack with broader weapons, medium armor' },
      { id: 'scoundrel', name: 'Scoundrel', description: 'Cha key ability; enhanced Feint with free Step on agile/finesse' },
      { id: 'mastermind', name: 'Mastermind', description: 'Int key ability; Recall Knowledge makes foe off-guard' },
    ] },
  },
  {
    id: 'sneak-attack',
    name: 'Sneak Attack',
    source: 'Rogue',
    category: 'class_feature',
    level: 1,
    description: "When your enemy can't properly defend itself, you take advantage to deal extra damage. If you Strike a creature that has the off-guard condition with an agile or finesse melee weapon, an agile or finesse unarmed attack, a ranged weapon attack, or a ranged unarmed attack, you deal an extra 1d6 precision damage. For a ranged attack with a thrown melee weapon, that weapon must also be agile or finesse. Increase the number of dice by one at 5th (2d6), 11th (3d6), and 17th (4d6) levels.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'surprise-attack',
    name: 'Surprise Attack',
    source: 'Rogue',
    category: 'class_feature',
    level: 1,
    description: "You spring into combat faster than foes can react. On the first round of combat, if you roll Deception or Stealth for initiative, creatures that haven't acted are off-guard to you.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // —— Level 3 ——————————————————————————————————————————————
  {
    id: 'deny-advantage',
    name: 'Deny Advantage',
    source: 'Rogue',
    category: 'class_feature',
    level: 3,
    description: "As someone who takes advantage of openings, you are careful not to leave such gaps yourself. You aren't off-guard to hidden, undetected, or flanking creatures of your level or lower, or creatures of your level or lower using surprise attack. However, they can still help their allies flank.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // —— Level 5 ——————————————————————————————————————————————
  {
    id: 'weapon-tricks',
    name: 'Weapon Tricks',
    source: 'Rogue',
    category: 'class_feature',
    level: 5,
    description: "You gain expert proficiency in simple weapons, martial weapons, and unarmed attacks. When you critically succeed at an attack roll against an off-guard creature while using an agile or finesse weapon or an agile or finesse unarmed attack, you apply the critical specialization effect for that weapon or unarmed attack.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Proficiency increase: simpleWeapons → expert, martialWeapons → expert, unarmed → expert. Critical specialization on crit vs off-guard with agile/finesse.',
  },
  // —— Level 7 ——————————————————————————————————————————————
  {
    id: 'evasive-reflexes',
    name: 'Evasive Reflexes',
    source: 'Rogue',
    category: 'class_feature',
    level: 7,
    description: "You've learned to move quickly to avoid explosions, dragons' breath, and worse. Your proficiency rank for Reflex saves increases to master. When you roll a success on a Reflex save, you get a critical success instead.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'perception-mastery',
    name: 'Perception Mastery',
    source: 'Rogue',
    category: 'class_feature',
    level: 7,
    description: "You've developed keen awareness and attention to detail. Your proficiency rank for Perception increases to master.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // Weapon Specialization — uses shared template
  createClassFeature(WEAPON_SPECIALIZATION, 'Rogue', 7),
  // —— Level 9 ——————————————————————————————————————————————
  {
    id: 'debilitating-strike',
    name: 'Debilitating Strike',
    source: 'Rogue',
    category: 'class_feature',
    level: 9,
    description: "When taking advantage of an opening, you both hinder and harm your foe. You gain the Debilitating Strike free action. Trigger: Your Strike hits an off-guard creature and deals damage. You apply one of the following debilitations, which lasts until the end of your next turn: the target takes a -10-foot status penalty to its Speeds, or the target becomes enfeebled 1.",
    implemented: 'full',
    actionCost: 'free',
    traits: ['Rogue'],
  },
  {
    id: 'rogue-resilience',
    name: 'Rogue Resilience',
    source: 'Rogue',
    category: 'class_feature',
    level: 9,
    description: "Your physique is incredibly hardy. Your proficiency rank for Fortitude saves increases to expert. When you roll a success on a Fortitude save, you get a critical success instead.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // —— Level 11 —————————————————————————————————————————————
  {
    id: 'rogue-expertise',
    name: 'Rogue Expertise',
    source: 'Rogue',
    category: 'class_feature',
    level: 11,
    description: "Your techniques are now harder to resist. Your proficiency rank for your rogue class DC increases to expert.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // —— Level 13 —————————————————————————————————————————————
  {
    id: 'greater-rogue-reflexes',
    name: 'Greater Rogue Reflexes',
    source: 'Rogue',
    category: 'class_feature',
    level: 13,
    description: "You elude danger to a degree that few can match. Your proficiency rank for Reflex saves increases to legendary. When you roll a critical failure on a Reflex save, you get a failure instead. When you roll a failure on a Reflex save against a damaging effect, you take half damage.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'perception-legend',
    name: 'Perception Legend',
    source: 'Rogue',
    category: 'class_feature',
    level: 13,
    description: "You notice things almost impossible for an ordinary person to detect. Your proficiency rank for Perception increases to legendary.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'light-armor-expertise',
    name: 'Light Armor Expertise',
    source: 'Rogue',
    category: 'class_feature',
    level: 13,
    description: "You've learned how to dodge while wearing light or no armor. Your proficiency ranks for light armor and unarmored defense increase to expert.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'master-tricks',
    name: 'Master Tricks',
    source: 'Rogue',
    category: 'class_feature',
    level: 13,
    description: "You've mastered a rogue's fighting moves. Your proficiency ranks increase to master for all simple weapons, martial weapons, and unarmed attacks.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // —— Level 15 —————————————————————————————————————————————
  {
    id: 'double-debilitation',
    name: 'Double Debilitation',
    source: 'Rogue',
    category: 'class_feature',
    level: 15,
    description: "Your opportunistic attacks are particularly detrimental. When you use Debilitating Strike, you can apply two debilitations simultaneously; removing one removes both.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // Greater Weapon Specialization — uses shared template
  createClassFeature(GREATER_WEAPON_SPECIALIZATION, 'Rogue', 15),
  // —— Level 17 —————————————————————————————————————————————
  {
    id: 'agile-mind',
    name: 'Agile Mind',
    source: 'Rogue',
    category: 'class_feature',
    level: 17,
    description: "You play mental games and employ cognitive tricks to throw off mind-altering effects. Your proficiency rank for Will saves increases to master. When you roll a success at a Will save, you get a critical success instead.",
    implemented: 'full',
    actionCost: 'passive',
  },
  // —— Level 19 —————————————————————————————————————————————
  {
    id: 'light-armor-mastery',
    name: 'Light Armor Mastery',
    source: 'Rogue',
    category: 'class_feature',
    level: 19,
    description: "Your skill with light armor improves, increasing your ability to dodge blows. Your proficiency ranks for light armor and unarmored defense increase to master.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'master-strike',
    name: 'Master Strike',
    source: 'Rogue',
    category: 'class_feature',
    level: 19,
    description: "You can incapacitate an unwary foe with a single strike. Your proficiency rank for your rogue class DC increases to master. You gain the Master Strike free action. Trigger: Your Strike hits an off-guard creature and deals damage. The target attempts a Fortitude save against your class DC and then becomes temporarily immune for 1 day. Critical Success: The target is unaffected. Success: The target is enfeebled 2 until the end of your next turn. Failure: The target is paralyzed for 4 rounds. Critical Failure: The target is paralyzed for 4 rounds, knocked unconscious for 2 hours, or killed (your choice).",
    implemented: 'full',
    actionCost: 'free',
    traits: ['Incapacitation', 'Rogue'],
  },
];

export const ROGUE_CLASS_FEATURES: FeatEntry[] = RAW_ROGUE_CLASS_FEATURES.map((feat) => {
  if (feat.traits && feat.traits.length > 0) return feat;
  return { ...feat, traits: ['Rogue'] };
});

// ————————————————————————————————————————————————————————————
// ROGUE SELECTABLE FEATS — PF2e Remaster (Player Core)
// Levels 1–20
// ————————————————————————————————————————————————————————————

export const ROGUE_CLASS_FEATS: FeatEntry[] = [
  // —— Level 1 ——————————————————————————————————————————————
  {
    id: 'nimble-dodge',
    name: 'Nimble Dodge',
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "You deftly dodge out of the way, gaining a +2 circumstance bonus to AC against the triggering attack. Trigger: A creature targets you with an attack and you can see the attacker. Requirements: You are not encumbered.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'overextending-feint',
    name: 'Overextending Feint',
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "You goad a foe into overextending. On a successful Feint, you can use the following effects instead of any other effects that would occur when you Feint. Critical Success: The target takes a -2 circumstance penalty to all attack rolls against you before the end of its next turn. Success: The target takes a -2 circumstance penalty to its next attack roll against you before the end of its next turn.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Trained in Deception'],
  },
  {
    id: 'plant-evidence',
    name: 'Plant Evidence',
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "You can put a single item you're holding of light or negligible Bulk onto a person without them noticing by succeeding at a Thievery check against their Perception DC. If you have the ruffian racket, you can do this as a free action when you successfully Shove a target.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
    prerequisites: ['Pickpocket'],
  },
  {
    id: 'trap-finder',
    name: 'Trap Finder',
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "You have an intuitive sense that alerts you to the presence of traps. You gain a +1 circumstance bonus to Perception checks to find traps, to AC against attacks made by traps, and to saves against traps. Even if you aren't Searching, you get a check to find traps that normally require you to be Searching. You still need to meet any other requirements to find the trap. You can disable traps that require a proficiency rank of master in Thievery. If you have master proficiency in Thievery, you can disable traps that require a proficiency rank of legendary instead, and your circumstance bonuses against traps increase to +2.",
    implemented: 'full',
    traits: ['Investigator', 'Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'tumble-behind-rogue',
    name: 'Tumble Behind',
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "You tumble under and behind your foe, your rapid movement letting you catch them off guard. When you successfully Tumble Through, the foe whose space you passed through is off-guard against the next attack you make before the end of your turn.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'twin-feint',
    name: 'Twin Feint',
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "You use an attack with one weapon to distract your foe from a second attack coming at a different angle. Make one Strike with each of your two melee weapons, both against the same target. The target is automatically off-guard against the second attack. Apply your multiple attack penalty to the Strikes normally. Requirements: You are wielding two melee weapons, each in a different hand.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
  },
  {
    id: 'youre-next',
    name: "You're Next",
    source: 'Rogue',
    category: 'class',
    level: 1,
    description: "After downing a foe, you menace another. Attempt to Demoralize a creature within 60 feet, with a +2 circumstance bonus. If you have legendary proficiency in Intimidation, you can use this as a free action with the same trigger. Trigger: You reduce an enemy to 0 Hit Points.",
    implemented: 'full',
    traits: ['Emotion', 'Fear', 'Mental', 'Rogue', 'Visual'],
    actionCost: 'reaction',
    prerequisites: ['Trained in Intimidation'],
  },

  // —— Level 2 ——————————————————————————————————————————————
  {
    id: 'brutal-beating',
    name: 'Brutal Beating',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "Your critical hits shake your foes' confidence. Whenever your Strike is a critical hit and deals damage, the target is frightened 1.",
    implemented: 'full',
    traits: ['Emotion', 'Fear', 'Mental', 'Rogue'],
    actionCost: 'passive',
    prerequisites: ['Ruffian Racket'],
  },
  {
    id: 'clever-gambit',
    name: 'Clever Gambit',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "Your battle tactics are aided by assessing your foe's capabilities and range. You Step or Stride; this movement doesn't trigger reactions from the triggering creature. Trigger: Your Strike critically hits and deals damage to a creature you've identified with Recall Knowledge.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
    prerequisites: ['Mastermind Racket'],
  },
  {
    id: 'distracting-feint',
    name: 'Distracting Feint',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "Your Feints are far more distracting than normal. While a creature is off-guard by your Feint, it also takes a -2 circumstance penalty to Perception checks and Reflex saves.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Scoundrel Racket'],
  },
  {
    id: 'mobility',
    name: 'Mobility',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "You move without leaving an opening. When you Stride and move half your Speed or less, that movement does not trigger reactions. You can use Mobility when Climbing, Flying, or Swimming instead of Striding if you have the corresponding movement type.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'quick-draw',
    name: 'Quick Draw',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "You draw your weapon and attack with the same motion. You Interact to draw a weapon, then Strike with that weapon.",
    implemented: 'full',
    traits: ['Gunslinger', 'Ranger', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'strong-arm',
    name: 'Strong Arm',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "When you Strike with a thrown weapon, the weapon's range increment increases by 10 feet.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'unbalancing-blow',
    name: 'Unbalancing Blow',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "Interweaving attacks, you unbalance your foes. Whenever your Strike is a critical hit and deals damage, the target is off-guard against your attacks until the end of your next turn.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Thief Racket'],
  },
  {
    id: 'underhanded-assault',
    name: 'Underhanded Assault',
    source: 'Rogue',
    category: 'class',
    level: 2,
    description: "You capitalize on the distraction provided by an ally. You Sneak up to a foe adjacent to one of your allies. You can roll against the foe you're Sneaking up on, even if it's currently observing you, as though you were hidden. You take a -2 penalty on your Stealth check. If your Stealth check against the chosen foe succeeds, you can make a melee Strike against that foe at the end of your Sneak.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
    prerequisites: ['Trained in Stealth'],
  },

  // —— Level 4 ——————————————————————————————————————————————
  {
    id: 'dread-striker',
    name: 'Dread Striker',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You capitalize on your enemies' fear to slip past their defenses. Any creature that has the frightened condition is also off-guard against your attacks.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'head-stomp',
    name: 'Head Stomp',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "Make an unarmed melee Strike against a prone target. If it hits, until the end of your next turn the target is stupefied 1 (or stupefied 2 on a critical hit) and off-guard.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
  },
  {
    id: 'mug',
    name: 'Mug',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You make a quick attack and rob your foe in the process. Make a melee Strike against an adjacent enemy. If you hit and deal sneak attack damage, you can also attempt to Steal from the target, even if the target is in combat.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
  },
  {
    id: 'poison-weapon',
    name: 'Poison Weapon',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You apply a contact poison or injury poison to a wielded weapon; if you have a free hand, you can Interact to draw a poison as part of this action. During your daily preparations, you can prepare a number of simple injury poisons equal to your level. These deal 1d4 poison damage with no saving throw, are usable only by you, and expire at your next daily preparations.",
    implemented: 'full',
    traits: ['Manipulate', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'predictable',
    name: 'Predictable!',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "By observing an opponent, you can get a sense of their next move and prepare to counter or resist it. Choose one target and attempt a Perception check to Sense Motive against the foe's Deception DC or a hard DC of the foe's level, whichever is higher. Critical Success: +2 circumstance bonus to AC and next save against the creature until the start of your next turn. Success: +1 circumstance bonus instead. Critical Failure: -1 circumstance penalty to AC and next save against the creature until the start of your next turn.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
  },
  {
    id: 'reactive-pursuit',
    name: 'Reactive Pursuit',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You keep pace with a retreating foe. You Stride, but you must end your movement adjacent to the triggering enemy. Your move does not trigger reactions from the triggering enemy. You can use Reactive Pursuit to Burrow, Climb, Fly, or Swim instead of Stride if you have the corresponding movement type. Trigger: An adjacent foe moves away from you, and you can reach at least one space adjacent to the foe with a Stride action.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'sabotage',
    name: 'Sabotage',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You subtly damage others' equipment. Choose one item that a creature within your reach wields or carries (must have moving parts). Attempt a Thievery check against the Reflex DC of the creature. Damage dealt by Sabotage can't take the item below its Broken Threshold. Critical Success: You deal damage equal to four times your Thievery proficiency bonus. Success: You deal damage equal to double your Thievery proficiency bonus. Critical Failure: Temporarily immune to your Sabotage for 1 day. Requirements: You have a free hand.",
    implemented: 'full',
    traits: ['Incapacitation', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'scouts-warning',
    name: "Scout's Warning",
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You visually or audibly warn your allies of danger, granting them each a +1 circumstance bonus to their initiative rolls, or a +2 circumstance bonus if you're using the Scout exploration activity. Depending on whether you use gestures or call out, this action gains either the visual or the auditory trait. Trigger: You are about to roll a Perception or Survival check for initiative.",
    implemented: 'full',
    traits: ['Ranger', 'Rogue'],
    actionCost: 'free',
  },
  {
    id: 'scoundrels-surprise',
    name: "Scoundrel's Surprise",
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You drop your disguise at the right moment and surprise your target. After you Impersonate someone else using a disguise kit, you can remove your disguise with a dramatic gesture. Any creatures that previously failed to see through your disguise are off-guard against the next attack you make before the end of your turn.",
    implemented: 'full',
    traits: ['Manipulate', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'the-harder-they-fall-rogue',
    name: 'The Harder They Fall',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "You make your foes fall painfully when you trip them. When you successfully Trip an off-guard foe, your target takes 1d6 bludgeoning damage. On a critical success, the target takes 1d6 bludgeoning damage plus your sneak attack damage.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'twin-distraction',
    name: 'Twin Distraction',
    source: 'Rogue',
    category: 'class',
    level: 4,
    description: "Your movements with two weapons are so swift and disorienting that they befuddle your opponent. When using Twin Feint, if both your Strikes deal damage to a targeted creature, the target must succeed at a Will saving throw against your class DC or become stupefied 1 until the end of your next turn. Requirements: You are wielding two melee weapons, each in a different hand.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Twin Feint'],
  },

  // —— Level 6 ——————————————————————————————————————————————
  {
    id: 'analyze-weakness',
    name: 'Analyze Weakness',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "Your knowledge of a creature's physiology helps you attack with pinpoint accuracy. You carefully study a creature that you've identified to scope out particularly weak points. The next time you deal sneak attack damage to the chosen creature with a Strike before the end of your turn, add an additional 2d6 precision damage. At 11th level the additional damage becomes 3d6, and at 17th level it becomes 4d6.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
    prerequisites: ['Sneak Attack 2d6'],
  },
  {
    id: 'anticipate-ambush',
    name: 'Anticipate Ambush',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "You keep watch for any hidden creatures or dangerous sites, moving at half your travel Speed. If you're Anticipating an Ambush at the start of an encounter, you roll a Perception check for initiative, and all enemies rolling Stealth for initiative take a -2 circumstance penalty to their Stealth checks.",
    implemented: 'full',
    traits: ['Exploration', 'Rogue'],
    actionCost: 'passive',
    prerequisites: ['Expert in Stealth'],
  },
  {
    id: 'far-throw',
    name: 'Far Throw',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "When you Strike with a thrown weapon, you take only a -1 penalty for each additional range increment between you and the target, rather than a -2 penalty.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'gang-up',
    name: 'Gang Up',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "You and your allies harry an opponent in concert. You can flank an enemy if it's within reach of both you and an ally — you and your ally don't have to be on opposite sides. This benefits your allies as well as you, but only if they're flanking with you, not each other. The other requirements for flanking must still be met.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'light-step',
    name: 'Light Step',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "You aren't bothered by tricky footing. When you Stride or Step, you can ignore difficult terrain.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'shove-down',
    name: 'Shove Down',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "You leverage your weight to topple foes that you move. You attempt to Trip the target, even if the target is no longer in your reach. Requirements: Your last action was a successful Shove.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'free',
    prerequisites: ['Trained in Athletics'],
  },
  {
    id: 'skirmish-strike',
    name: 'Skirmish Strike',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "Your feet and weapon move in tandem. Either Step and then Strike, or Strike and then Step.",
    implemented: 'full',
    traits: ['Flourish', 'Ranger', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'sly-disarm',
    name: 'Sly Disarm',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "You can Disarm a creature through sleight of hand rather than brute force. You can use Thievery instead of Athletics when you attempt a Disarm. When you use Thievery to attempt a Disarm and succeed, the target is off-guard against the next attack you make before the end of your turn.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'twist-the-knife',
    name: 'Twist the Knife',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "After stabbing your opponent in a weak spot, you tear the wound open. You deal persistent bleed damage to the target equal to your number of sneak attack damage dice. Requirements: Your last action was a melee Strike that dealt sneak attack damage to an off-guard target.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
  },
  {
    id: 'watch-your-back',
    name: 'Watch Your Back',
    source: 'Rogue',
    category: 'class',
    level: 6,
    description: "You menace the target, stoking their fears and drawing their attention. Attempt an Intimidation check against the Will DC of a target within 30 feet. If you succeed, for 1 minute, that target gains a +2 status bonus to Perception checks against you, but it takes a -2 status penalty to Will saves against fear effects.",
    implemented: 'full',
    traits: ['Emotion', 'Fear', 'Mental', 'Rogue'],
    actionCost: 1,
    prerequisites: ['Trained in Intimidation'],
  },

  // —— Level 8 ——————————————————————————————————————————————
  {
    id: 'blind-fight',
    name: 'Blind-Fight',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "Your battle instincts make you more aware of concealed and invisible opponents. You don't need to succeed at a flat check to target concealed creatures. You're not off-guard to creatures that are hidden from you (unless you're off-guard to them for reasons other than the hidden condition), and you need only a successful DC 5 flat check to target a hidden creature. While you're adjacent to an undetected creature of your level or lower, it is instead only hidden from you.",
    implemented: 'full',
    traits: ['Fighter', 'Investigator', 'Ranger', 'Rogue'],
    actionCost: 'passive',
    prerequisites: ['Master in Perception'],
  },
  {
    id: 'bullseye',
    name: 'Bullseye',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You carefully take aim to avoid your foe's concealment and cover. On your next Strike with a thrown weapon before the end of your turn, you gain a +1 circumstance bonus to your attack roll and ignore your target's concealed condition, as well as the target's lesser cover or standard cover; if the target had greater cover, they instead have only standard cover against the Strike.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
  },
  {
    id: 'delay-trap',
    name: 'Delay Trap',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You try to jam the workings of a trap to delay its effects. Attempt a Thievery check to Disable a Device on the trap. Critical Success: You either prevent the trap from being triggered or delay the activation until the start or end of your next turn. Success: As above, but the GM chooses whichever is worse for you. Failure: No effect. Critical Failure: You're off-guard until the start of your next turn. Trigger: A trap within your reach is triggered.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'improved-poison-weapon',
    name: 'Improved Poison Weapon',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You deliver poisons in ways that maximize their harmful effects. When you apply a simple poison with Poison Weapon, the poison deals 2d4 poison damage instead of 1d4 poison damage. You don't waste a poison you apply with Poison Weapon on a critically failed attack roll.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Poison Weapon'],
  },
  {
    id: 'inspired-stratagem',
    name: 'Inspired Stratagem',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "During your daily preparations, you can review stratagems for the day's adventures with up to five allies. Later, you can quickly advise them using the Inspired Stratagem reaction (fortune, linguistic). Trigger: An ally you reviewed stratagems with is about to attempt an attack roll or skill check. Effect: The ally rolls the triggering check twice and takes the better result. That ally then becomes temporarily immune to your Inspired Stratagem until your next daily preparations.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'nimble-roll',
    name: 'Nimble Roll',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You throw yourself into a roll to escape imminent danger. You can use Nimble Dodge before attempting a Reflex save in addition to its original trigger. If you do, the circumstance bonus applies to your Reflex save against the triggering effect. When you use Nimble Dodge and the triggering attack fails or critically fails, or when you succeed or critically succeed at the saving throw, you can also Stride up to 10 feet as part of the reaction. If you do, the reaction gains the move trait.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Nimble Dodge'],
  },
  {
    id: 'opportune-backstab',
    name: 'Opportune Backstab',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "When your enemy is hit by your ally, you capitalize upon the distraction. Make a Strike against the triggering creature. Trigger: A creature within your melee reach is hit by a melee attack from one of your allies.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'predictive-purchase-rogue',
    name: 'Predictive Purchase',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You somehow manage to have just the thing for the situation. You gain the Prescient Planner and Prescient Consumable feats. When using Prescient Planner, you can draw the item from your backpack (or a similar container) as a 2-action activity instead of taking 1 minute to do so.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'ricochet-stance-rogue',
    name: 'Ricochet Stance',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You adopt a stance to rebound your thrown weapons toward you. While you are in this stance, any thrown weapons you use as part of a ranged Strike to deal bludgeoning or slashing damage immediately return to your hand, enabling you to use them for additional Strikes. You must be within the weapon's listed range increment and have a hand free to catch the weapon. If you make a ranged Strike with a thrown weapon outside of its listed range increment, it instead flies back toward you a number of feet equal to its listed range increment and then falls to the ground.",
    implemented: 'full',
    traits: ['Rogue', 'Stance'],
    actionCost: 1,
  },
  {
    id: 'sidestep',
    name: 'Sidestep',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You deftly step aside and gently redirect an attack. You redirect the triggering attack to a creature of your choice that is adjacent to you and within the attack's reach or maximum range. The attacker rerolls the Strike's attack roll against the new target. Trigger: The attack roll for a Strike targeting you fails or critically fails.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'sly-striker',
    name: 'Sly Striker',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "Your attacks deal more damage, even against creatures that aren't off-guard. When you succeed or critically succeed at a Strike against a creature that isn't off-guard, you also deal 1d6 precision damage. This applies only if you're using a weapon or unarmed attack you could deal sneak attack damage with. At 14th level, if you would normally deal 3d6 or more sneak attack damage to off-guard creatures, you deal 2d6 precision damage to creatures that aren't off-guard.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Sneak Attack'],
  },
  {
    id: 'swipe-souvenir',
    name: 'Swipe Souvenir',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "When you wriggle free from an enemy's grasp, you take something of theirs with you. You attempt to Escape from being grabbed or restrained by a creature. If you succeed, you can also attempt to Steal from the creature, even if the creature is in combat. Requirements: You're grabbed or restrained by a creature.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
  },
  {
    id: 'tactical-entry',
    name: 'Tactical Entry',
    source: 'Rogue',
    category: 'class',
    level: 8,
    description: "You Stride. This movement doesn't trigger any reactions. Requirements: You rolled Stealth for initiative in this encounter, and neither you nor any enemies have acted yet.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'free',
    prerequisites: ['Master in Stealth'],
  },

  // —— Level 10 —————————————————————————————————————————————
  {
    id: 'methodical-debilitations',
    name: 'Methodical Debilitations',
    source: 'Rogue',
    category: 'class',
    level: 10,
    description: "You strategically craft your debilitations to lessen or negate an enemy's tactical advantages. Add the following debilitations to the list you can choose from when you use Debilitating Strike. Debilitation: The target can't flank or contribute to allies' flanking. Debilitation: The target doesn't gain a circumstance bonus to AC from Raising a Shield, lesser cover, or standard cover; it gains a +2 circumstance bonus to AC only from greater cover or Taking Cover.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Mastermind Racket', 'Debilitating Strike'],
  },
  {
    id: 'nimble-strike',
    name: 'Nimble Strike',
    source: 'Rogue',
    category: 'class',
    level: 10,
    description: "You're cunning enough to find an opening in an opponent's attack. When you use your Nimble Dodge reaction, you can make a melee Strike against the triggering creature. This Strike doesn't count toward your multiple attack penalty, and your multiple attack penalty doesn't apply to this Strike. If you use the Nimble Roll feat, you can make this Strike at any point during your roll.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Nimble Roll'],
  },
  {
    id: 'precise-debilitations',
    name: 'Precise Debilitations',
    source: 'Rogue',
    category: 'class',
    level: 10,
    description: "You attack with great precision. Add the following debilitations to the list you can choose from when you use Debilitating Strike. Debilitation: The target takes an additional 2d6 precision damage from your attacks. Debilitation: The target becomes off-guard.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Thief Racket', 'Debilitating Strike'],
  },
  {
    id: 'sneak-adept',
    name: 'Sneak Adept',
    source: 'Rogue',
    category: 'class',
    level: 10,
    description: "It's almost impossible to spot you. When you roll a failure on a Sneak action, you get a success instead. You can still critically fail.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Master in Stealth'],
  },
  {
    id: 'tactical-debilitations',
    name: 'Tactical Debilitations',
    source: 'Rogue',
    category: 'class',
    level: 10,
    description: "You learn new debilitations that grant you tactical advantages against your foes. Add the following debilitations to the list you can choose from when you use Debilitating Strike. Debilitation: The target can't use reactions. Debilitation: The target can't flank or contribute to allies' flanking.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Scoundrel Racket', 'Debilitating Strike'],
  },
  {
    id: 'vicious-debilitations',
    name: 'Vicious Debilitations',
    source: 'Rogue',
    category: 'class',
    level: 10,
    description: "The debilitations you dish out seriously impair your foes. Add the following debilitations to the list you can choose from when you use Debilitating Strike. Debilitation: The target gains weakness 5 to your choice of bludgeoning, piercing, or slashing damage. Debilitation: The target becomes clumsy 1.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Ruffian Racket', 'Debilitating Strike'],
  },

  // —— Level 12 —————————————————————————————————————————————
  {
    id: 'bloody-debilitation',
    name: 'Bloody Debilitation',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "Your attacks slice arteries and veins. Add the following debilitation to the list you can choose from when you use Debilitating Strike. Debilitation: The target takes 3d6 persistent bleed damage.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Trained in Medicine', 'Debilitating Strike'],
  },
  {
    id: 'critical-debilitation',
    name: 'Critical Debilitation',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "Your debilitations are especially effective on your most powerful attacks. Whenever you critically succeed at an attack roll against an enemy and use Debilitating Strike, add the following debilitation to the list you can choose from. Debilitation: The target attempts a Fortitude save against your class DC. Critical Success: The target is unaffected. Success: The target is slowed 1 until the end of your next turn. Failure: The target is slowed 2 until the end of your next turn. Critical Failure: The target is paralyzed until the end of your next turn.",
    implemented: 'full',
    traits: ['Incapacitation', 'Rogue'],
    actionCost: 'passive',
    prerequisites: ['Debilitating Strike'],
  },
  {
    id: 'fantastic-leap',
    name: 'Fantastic Leap',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "You launch yourself through the air at a foe. Attempt a High Jump or Long Jump. If you attempt a High Jump, determine the height of your jump as though determining the length of a Long Jump. At the end of your jump, you can make a melee Strike. After your Strike, you fall to the ground if you're in the air. If the distance of your fall is no more than the height of your jump, you take no damage and land upright.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
  },
  {
    id: 'felling-shot',
    name: 'Felling Shot',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "Your ranged attacks can shoot an unprepared foe right out of the air. Make a ranged Strike against an off-guard creature. If the Strike is a success and deals damage, the target must attempt a Reflex save against your class DC. Success: The target is unaffected. Failure: The target falls up to 120 feet. If it hits the ground, it takes no damage from the fall. Critical Failure: As failure, and the target can't fly, jump, levitate, or otherwise leave the ground until the end of your next turn.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
  },
  {
    id: 'preparation',
    name: 'Preparation',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "You survey the battlefield, calculating the possibilities. You gain one additional reaction, which you can use before the beginning of your next turn for any rogue reaction.",
    implemented: 'full',
    traits: ['Flourish', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'reactive-interference',
    name: 'Reactive Interference',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "Grabbing a sleeve, swiping with your weapon, or creating another obstruction, you reflexively foil an enemy's response. If the triggering creature's level is equal to or lower than yours, you disrupt the triggering reaction. If the triggering creature's level is higher than yours, you must make an attack roll against its AC. On a success, you disrupt the reaction. Trigger: An adjacent enemy begins to use a reaction.",
    implemented: 'full',
    traits: ['Commander', 'Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'ricochet-feint',
    name: 'Ricochet Feint',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "While in Ricochet Stance, you can bounce a thrown weapon off a foe to distract them. You can attempt a Feint against a creature within the first range increment of a thrown weapon you are wielding, rather than only creatures within your melee reach.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Ricochet Stance'],
  },
  {
    id: 'spring-from-the-shadows',
    name: 'Spring from the Shadows',
    source: 'Rogue',
    category: 'class',
    level: 12,
    description: "You leap from hiding and assail your target. You Stride up to your Speed, but you must end your movement next to an enemy you're hidden from or undetected by. You then Strike that enemy; you remain hidden from or undetected by that creature until after you Strike. You can use Spring from the Shadows while Burrowing, Climbing, Flying, or Swimming instead of Striding if you have the corresponding movement type.",
    implemented: 'full',
    traits: ['Flourish', 'Rogue'],
    actionCost: 1,
  },

  // —— Level 14 —————————————————————————————————————————————
  {
    id: 'defensive-roll',
    name: 'Defensive Roll',
    source: 'Rogue',
    category: 'class',
    level: 14,
    description: "Dropping into a roll to disperse the force of the blow, you can partially evade a lethal attack and stay conscious. You take half damage from the triggering attack. Trigger: A physical attack would reduce you to 0 Hit Points. Frequency: once per 10 minutes.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'free',
  },
  {
    id: 'instant-opening',
    name: 'Instant Opening',
    source: 'Rogue',
    category: 'class',
    level: 14,
    description: "You distract your opponent with a few choice words or a rude gesture. Choose a target within 30 feet. It's off-guard against your attacks until the end of your next turn. Depending on the way you describe your distraction, this action gains either the auditory or visual trait.",
    implemented: 'full',
    traits: ['Concentrate', 'Rogue'],
    actionCost: 1,
  },
  {
    id: 'leave-an-opening',
    name: 'Leave an Opening',
    source: 'Rogue',
    category: 'class',
    level: 14,
    description: "When you hit hard enough, you leave an opening so your ally can jump in on the action. Whenever you critically hit an off-guard opponent with a melee attack and deal damage, the target triggers a Reactive Strike reaction from one ally of your choice who has that reaction, as if the enemy had used a manipulate action.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'sense-the-unseen',
    name: 'Sense the Unseen',
    source: 'Rogue',
    category: 'class',
    level: 14,
    description: "When you look for foes, you can catch even the slightest cues, such as their minute movements or the shifting of air currents on your skin. Even though you failed at the triggering check, you automatically sense any undetected creatures in the area where you're Seeking, making them merely hidden to you. Trigger: You fail a check to Seek.",
    implemented: 'full',
    traits: ['Investigator', 'Ranger', 'Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'stay-down',
    name: 'Stay Down!',
    source: 'Rogue',
    category: 'class',
    level: 14,
    description: "You have ways of keeping your foes down. Attempt an Athletics check against the triggering foe's Fortitude DC. On a success, the action is disrupted, causing the creature to remain prone. On a critical success, the creature also can't Stand until its next turn. Trigger: A prone foe within your reach Stands.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
    prerequisites: ['Master in Athletics'],
  },

  // —— Level 16 —————————————————————————————————————————————
  {
    id: 'blank-slate',
    name: 'Blank Slate',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "Your deceptions confound even the most powerful magic that could spy on you. Detection, revelation, and scrying effects pass right over you, your possessions, and your auras, detecting nothing unless the detecting effect has a counteract rank of 10 or higher. For example, detect magic would still detect other magic in the area but not any magic on you, truesight wouldn't reveal you, locate or scrying wouldn't find you, and so on.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Deception'],
  },
  {
    id: 'cloud-step',
    name: 'Cloud Step',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "Using fantastic acrobatic skill, you can walk for brief stretches across insubstantial surfaces. When you Stride, you can move across water, air, and solid surfaces that can hold only limited weight as if they were normal ground. If you Stride over a trap with a weight-sensitive pressure plate, you don't trigger it. At the end of your turn, you sink, fall, break fragile surfaces, or trigger traps as normal for your current location.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Legendary in Acrobatics'],
  },
  {
    id: 'cognitive-loophole',
    name: 'Cognitive Loophole',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "You can find a loophole in a mental effect to temporarily overcome it. Until the end of your next turn, you ignore a single mental effect. You can suppress a particular effect using Cognitive Loophole only once. You can't use Cognitive Loophole to suppress an effect you chose to have affect you. Special: You can use this reaction even if the mental effect is preventing you from using reactions. Trigger: Your turn ends. Requirements: You are currently affected by a mental effect.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
  },
  {
    id: 'dispelling-slice',
    name: 'Dispelling Slice',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "Your sneak attack slices through the threads binding magic to a target. Make a Strike against an off-guard creature. If your Strike deals sneak attack damage, you attempt to counteract a single spell of your choice active on the target. Your counteract rank is equal to half your level (rounded up), and your counteract check modifier is equal to your class DC - 10.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 2,
  },
  {
    id: 'perfect-distraction',
    name: 'Perfect Distraction',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "You use clever tactics to mislead your foes as you sneak away. You Sneak while leaving a decoy behind. The decoy acts as the spell mislead, though you aren't invisible, just undetected. You can continue to concentrate to move your decoy, as with the spell, whether or not you remain hidden throughout the duration. Once you use Perfect Distraction, you need to spend 10 minutes to set up another decoy before you can use it again.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 1,
    prerequisites: ['Legendary in Deception'],
  },
  {
    id: 'reconstruct-the-scene',
    name: 'Reconstruct the Scene',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "You spend 1 minute surveying a small location (such as a single room) to get an impression of events that occurred there in the last day. This involves moving about the area and studying footprints, spilled drinks or blood, and so forth. You get an indistinct mental impression of significant events that happened there. This gives you clues and details of the past, including the overall events and their time frame, but it's not a perfect record. This also isn't enough to identify who was involved in these events if you weren't already aware the person was there. As determined by the GM, you also pick out various seemingly small details that could serve as important clues.",
    implemented: 'full',
    traits: ['Concentrate', 'Investigator', 'Rogue'],
    actionCost: 'passive',
  },
  {
    id: 'swift-elusion',
    name: 'Swift Elusion',
    source: 'Rogue',
    category: 'class',
    level: 16,
    description: "Attempt an Acrobatics check against the foe's Reflex DC. If you succeed, either Stride to a different space adjacent to the foe or move the foe to a different space adjacent to you. Trigger: A foe ends its movement adjacent to you.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
    prerequisites: ['Legendary in Acrobatics'],
  },

  // —— Level 18 —————————————————————————————————————————————
  {
    id: 'implausible-infiltration',
    name: 'Implausible Infiltration',
    source: 'Rogue',
    category: 'class',
    level: 18,
    description: "You find tiny imperfections and somehow fit yourself through them, possibly moving directly through the wall or floor. Your movement attempt fails if the wall or floor is made of something other than wood, plaster, or stone; is thicker than 10 feet; or contains even a thin layer of metal. If you have a climb Speed, you can use this ability to attempt to move through a ceiling. Requirements: You are adjacent to a floor or vertical wall.",
    implemented: 'full',
    traits: ['Magical', 'Move', 'Rogue'],
    actionCost: 2,
    prerequisites: ['Legendary in Acrobatics', 'Quick Squeeze'],
  },
  {
    id: 'implausible-purchase',
    name: 'Implausible Purchase',
    source: 'Rogue',
    category: 'class',
    level: 18,
    description: "You can use Prescient Planner even if you have already used it after purchasing goods, and you can Interact to draw the item as a single action instead of a 2-action activity. In addition, five times per day, you can use Prescient Planner to pull out a common consumable item up to 6 levels lower than your level.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Predictive Purchase'],
  },
  {
    id: 'powerful-sneak',
    name: 'Powerful Sneak',
    source: 'Rogue',
    category: 'class',
    level: 18,
    description: "You've learned to exploit your enemies' openings. Your sneak attack damage ignores any immunity or resistance the target has to precision damage. In addition, when you Sneak, you can designate one creature you're undetected by at the end of that action. On the next attack you make against that creature before the end of your next turn, any sneak attack die you roll that's less than 3 is a 3 instead. This has no benefit if your next attack against the creature doesn't deal sneak attack damage, and if you designate a new creature you lose the benefit on any previous one.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
  },

  // —— Level 20 —————————————————————————————————————————————
  {
    id: 'hidden-paragon',
    name: 'Hidden Paragon',
    source: 'Rogue',
    category: 'class',
    level: 20,
    description: "When you slip out of sight, you disappear. You become invisible for 1 minute, even if you use a hostile action. Not even revealing light, see the unseen, or similar effects can reveal you, though creatures can still use the Seek action to locate you as normal. Trigger: You successfully use Stealth to Hide and become hidden from all of your current foes, or use Stealth to Sneak and become undetected to all your current foes. Frequency: once per hour.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'reaction',
    prerequisites: ['Legendary in Stealth'],
  },
  {
    id: 'impossible-striker',
    name: 'Impossible Striker',
    source: 'Rogue',
    category: 'class',
    level: 20,
    description: "Nothing can prevent you from making a sneak attack, even if your opponent can see every blow coming. Instead of dealing the damage from Sly Striker, you can deal your full sneak attack damage to a target even if the target isn't off-guard.",
    implemented: 'full',
    traits: ['Rogue'],
    actionCost: 'passive',
    prerequisites: ['Sly Striker'],
  },
  {
    id: 'reactive-distraction',
    name: 'Reactive Distraction',
    source: 'Rogue',
    category: 'class',
    level: 20,
    description: "You reactively switch with your decoy to foil your foe. You use Perfect Distraction, even if you were observed, as long as you end the movement of your Sneak while concealed or in a location with cover or greater cover. Your decoy is targeted by the attack or effect instead of you. In the case of an area effect, if your Sneak doesn't move you out of the area, both you and the decoy are targeted by the effect. Trigger: You would be hit by an attack or targeted by an effect, or you are within an effect's area. Requirements: You have Perfect Distraction ready to use.",
    implemented: 'full',
    traits: ['Concentrate', 'Manipulate', 'Rogue'],
    actionCost: 'reaction',
    prerequisites: ['Legendary in Deception', 'Perfect Distraction'],
  },
];
