/**
 * Spell definitions and utilities for PF2e Rebirth
 *
 * AUTO-GENERATED by scripts/foundry-import/import-spells.js
 * Source: scripts/foundry-import/source/spells.source.json
 * Do not edit this file manually; rerun npm run import:foundry.
 */
export type DamageType = 'bludgeoning' | 'piercing' | 'slashing' | 'bleed' | 'fire' | 'cold' | 'electricity' | 'sonic' | 'acid' | 'vitality' | 'void' | 'spirit' | 'poison' | 'mental' | 'force' | 'precision' | 'negative';
export interface SpellHeightening {
    type: 'interval' | 'fixed';
    interval?: number;
    damage?: string;
    perInterval?: string;
    fixedLevels?: Record<number, string>;
}
export interface Spell {
    id: string;
    name: string;
    rank: number;
    traditions: ('arcane' | 'divine' | 'occult' | 'primal')[];
    cost: number;
    range: number;
    description: string;
    icon: string;
    targetType: 'single' | 'aoe';
    aoeRadius?: number;
    aoeShape?: 'burst' | 'emanation' | 'cone' | 'line';
    saveDC?: number;
    saveType?: 'reflex' | 'fortitude' | 'will';
    basicSave?: boolean;
    damageType?: DamageType;
    damageFormula?: string;
    persistentDamageFormula?: string;
    persistentDamageChance?: 'always' | 'critical-failure' | 'failure';
    heightening?: SpellHeightening;
    focus?: boolean;
    sustained?: boolean;
}
export declare const SPELL_CATALOG: Record<string, Spell>;
/**
 * Legacy (pre-Remaster) spell ID → Remaster spell ID.
 * Allows code written with old names to find spells by their new IDs.
 */
export declare const LEGACY_SPELL_ALIASES: Record<string, string>;
export declare function getSpell(spellId: string): Spell | undefined;
/**
 * Look up a spell by its display name (case-insensitive).
 * Handles Pathbuilder names like "Sure Strike" → finds 'true-strike' entry.
 * Also strips suffixes like " (Archetype)" from Pathbuilder focus spell names.
 * Checks both Remaster and legacy display names.
 */
export declare function getSpellByName(displayName: string): Spell | undefined;
/**
 * Convert a Pathbuilder spell display name to a SPELL_CATALOG id.
 * Returns the spell id if found, or a kebab-case fallback.
 * Handles both legacy and Remaster names.
 * Examples:
 *   "Sure Strike" → "sure-strike"
 *   "True Strike" → "sure-strike" (via legacy alias)
 *   "Warp Step (Archetype)" → "warp-step"
 *   "Fireball" → "fireball"
 */
export declare function resolveSpellId(displayName: string): string;
export declare const rollDamageFormula: (formula: string) => {
    results: number[];
    total: number;
};
