// Sub-choice option sets for feats that require the player to choose from a list
// Cantrips are extracted from the SPELL_CATALOG (rank 0 spells) by tradition

type SubChoiceOption = { id: string; name: string; description?: string };

export const ARCANE_CANTRIP_OPTIONS: SubChoiceOption[] = [
  { id: "acid-splash", name: "Acid Splash" },
  { id: "ancient-dust", name: "Ancient Dust" },
  { id: "approximate", name: "Approximate" },
  { id: "bramble-bush", name: "Bramble Bush" },
  { id: "bullhorn", name: "Bullhorn" },
  { id: "caustic-blast", name: "Caustic Blast" },
  { id: "daze", name: "Daze" },
  { id: "deep-breath", name: "Deep Breath" },
  { id: "detect-magic", name: "Detect Magic" },
  { id: "detect-metal", name: "Detect Metal" },
  { id: "draw-moisture", name: "Draw Moisture" },
  { id: "eat-fire", name: "Eat Fire" },
  { id: "electric-arc", name: "Electric Arc" },
  { id: "elemental-counter", name: "Elemental Counter" },
  { id: "figment", name: "Figment" },
  { id: "frostbite", name: "Frostbite" },
  { id: "gale-blast", name: "Gale Blast" },
  { id: "ghost-sound", name: "Ghost Sound" },
  { id: "glamorize", name: "Glamorize" },
  { id: "glass-shield", name: "Glass Shield" },
  { id: "glowing-trail", name: "Glowing Trail" },
  { id: "gouging-claw", name: "Gouging Claw" },
  { id: "ignition", name: "Ignition" },
  { id: "illuminate", name: "Illuminate" },
  { id: "infectious-enthusiasm", name: "Infectious Enthusiasm" },
  { id: "invoke-true-name", name: "Invoke True Name" },
  { id: "light", name: "Light" },
  { id: "live-wire", name: "Live Wire" },
  { id: "mage-hand", name: "Mage Hand" },
  { id: "message", name: "Message" },
  { id: "musical-accompaniment", name: "Musical Accompaniment" },
  { id: "needle-darts", name: "Needle Darts" },
  { id: "prestidigitation", name: "Prestidigitation" },
  { id: "protect-companion", name: "Protect Companion" },
  { id: "puff-of-poison", name: "Puff of Poison" },
  { id: "read-aura", name: "Read Aura" },
  { id: "root-reading", name: "Root Reading" },
  { id: "scatter-scree", name: "Scatter Scree" },
  { id: "shield", name: "Shield" },
  { id: "sigil", name: "Sigil" },
  { id: "slashing-gust", name: "Slashing Gust" },
  { id: "spout", name: "Spout" },
  { id: "summon-instrument", name: "Summon Instrument" },
  { id: "take-root", name: "Take Root" },
  { id: "tangle-vine", name: "Tangle Vine" },
  { id: "telekinetic-hand", name: "Telekinetic Hand" },
  { id: "telekinetic-projectile", name: "Telekinetic Projectile" },
  { id: "timber", name: "Timber" },
  { id: "time-sense", name: "Time Sense" },
  { id: "torturous-trauma", name: "Torturous Trauma" },
  { id: "tremor-signs", name: "Tremor Signs" },
  { id: "void-warp", name: "Void Warp" },
];

export const DIVINE_CANTRIP_OPTIONS: SubChoiceOption[] = [
  { id: "ancient-dust", name: "Ancient Dust" },
  { id: "approximate", name: "Approximate" },
  { id: "bullhorn", name: "Bullhorn" },
  { id: "daze", name: "Daze" },
  { id: "detect-magic", name: "Detect Magic" },
  { id: "detect-metal", name: "Detect Metal" },
  { id: "divine-lance", name: "Divine Lance" },
  { id: "draw-moisture", name: "Draw Moisture" },
  { id: "forbidding-ward", name: "Forbidding Ward" },
  { id: "glamorize", name: "Glamorize" },
  { id: "glowing-trail", name: "Glowing Trail" },
  { id: "guidance", name: "Guidance" },
  { id: "haunting-hymn", name: "Haunting Hymn" },
  { id: "illuminate", name: "Illuminate" },
  { id: "inside-ropes", name: "Inside Ropes" },
  { id: "invoke-true-name", name: "Invoke True Name" },
  { id: "know-the-way", name: "Know the Way" },
  { id: "light", name: "Light" },
  { id: "message", name: "Message" },
  { id: "needle-darts", name: "Needle Darts" },
  { id: "prestidigitation", name: "Prestidigitation" },
  { id: "protect-companion", name: "Protect Companion" },
  { id: "read-aura", name: "Read Aura" },
  { id: "read-the-air", name: "Read the Air" },
  { id: "rousing-splash", name: "Rousing Splash" },
  { id: "shield", name: "Shield" },
  { id: "sigil", name: "Sigil" },
  { id: "stabilize", name: "Stabilize" },
  { id: "summon-instrument", name: "Summon Instrument" },
  { id: "torturous-trauma", name: "Torturous Trauma" },
  { id: "tremor-signs", name: "Tremor Signs" },
  { id: "vitality-lash", name: "Vitality Lash" },
  { id: "wash-your-luck", name: "Wash Your Luck" },
];

export const OCCULT_CANTRIP_OPTIONS: SubChoiceOption[] = [
  { id: "approximate", name: "Approximate" },
  { id: "bullhorn", name: "Bullhorn" },
  { id: "dancing-blade", name: "Dancing Blade" },
  { id: "daze", name: "Daze" },
  { id: "detect-magic", name: "Detect Magic" },
  { id: "detect-metal", name: "Detect Metal" },
  { id: "eat-fire", name: "Eat Fire" },
  { id: "figment", name: "Figment" },
  { id: "forbidden-thought", name: "Forbidden Thought" },
  { id: "forbidding-ward", name: "Forbidding Ward" },
  { id: "ghost-sound", name: "Ghost Sound" },
  { id: "glamorize", name: "Glamorize" },
  { id: "glimpse-weakness", name: "Glimpse Weakness" },
  { id: "glowing-trail", name: "Glowing Trail" },
  { id: "guidance", name: "Guidance" },
  { id: "haunting-hymn", name: "Haunting Hymn" },
  { id: "illuminate", name: "Illuminate" },
  { id: "imaginary-weapon", name: "Imaginary Weapon" },
  { id: "infectious-enthusiasm", name: "Infectious Enthusiasm" },
  { id: "inside-ropes", name: "Inside Ropes" },
  { id: "invoke-true-name", name: "Invoke True Name" },
  { id: "join-pasts", name: "Join Pasts" },
  { id: "know-the-way", name: "Know the Way" },
  { id: "light", name: "Light" },
  { id: "mage-hand", name: "Mage Hand" },
  { id: "message", name: "Message" },
  { id: "musical-accompaniment", name: "Musical Accompaniment" },
  { id: "needle-darts", name: "Needle Darts" },
  { id: "phase-bolt", name: "Phase Bolt" },
  { id: "prestidigitation", name: "Prestidigitation" },
  { id: "protect-companion", name: "Protect Companion" },
  { id: "read-aura", name: "Read Aura" },
  { id: "read-the-air", name: "Read the Air" },
  { id: "redistribute-potential", name: "Redistribute Potential" },
  { id: "shield", name: "Shield" },
  { id: "sigil", name: "Sigil" },
  { id: "summon-instrument", name: "Summon Instrument" },
  { id: "tame", name: "Tame" },
  { id: "telekinetic-hand", name: "Telekinetic Hand" },
  { id: "telekinetic-projectile", name: "Telekinetic Projectile" },
  { id: "telekinetic-rend", name: "Telekinetic Rend" },
  { id: "time-sense", name: "Time Sense" },
  { id: "tremor-signs", name: "Tremor Signs" },
  { id: "void-warp", name: "Void Warp" },
  { id: "warp-step", name: "Warp Step" },
  { id: "wash-your-luck", name: "Wash Your Luck" },
];

export const PRIMAL_CANTRIP_OPTIONS: SubChoiceOption[] = [
  { id: "acid-splash", name: "Acid Splash" },
  { id: "approximate", name: "Approximate" },
  { id: "bramble-bush", name: "Bramble Bush" },
  { id: "caustic-blast", name: "Caustic Blast" },
  { id: "deep-breath", name: "Deep Breath" },
  { id: "detect-magic", name: "Detect Magic" },
  { id: "detect-metal", name: "Detect Metal" },
  { id: "draw-moisture", name: "Draw Moisture" },
  { id: "eat-fire", name: "Eat Fire" },
  { id: "electric-arc", name: "Electric Arc" },
  { id: "elemental-counter", name: "Elemental Counter" },
  { id: "frostbite", name: "Frostbite" },
  { id: "gale-blast", name: "Gale Blast" },
  { id: "glamorize", name: "Glamorize" },
  { id: "glass-shield", name: "Glass Shield" },
  { id: "glowing-trail", name: "Glowing Trail" },
  { id: "gouging-claw", name: "Gouging Claw" },
  { id: "guidance", name: "Guidance" },
  { id: "healing-plaster", name: "Healing Plaster" },
  { id: "ignition", name: "Ignition" },
  { id: "illuminate", name: "Illuminate" },
  { id: "inside-ropes", name: "Inside Ropes" },
  { id: "invoke-true-name", name: "Invoke True Name" },
  { id: "know-the-way", name: "Know the Way" },
  { id: "light", name: "Light" },
  { id: "live-wire", name: "Live Wire" },
  { id: "needle-darts", name: "Needle Darts" },
  { id: "prestidigitation", name: "Prestidigitation" },
  { id: "protect-companion", name: "Protect Companion" },
  { id: "puff-of-poison", name: "Puff of Poison" },
  { id: "read-aura", name: "Read Aura" },
  { id: "root-reading", name: "Root Reading" },
  { id: "rousing-splash", name: "Rousing Splash" },
  { id: "scatter-scree", name: "Scatter Scree" },
  { id: "sigil", name: "Sigil" },
  { id: "slashing-gust", name: "Slashing Gust" },
  { id: "spout", name: "Spout" },
  { id: "stabilize", name: "Stabilize" },
  { id: "take-root", name: "Take Root" },
  { id: "tame", name: "Tame" },
  { id: "tangle-vine", name: "Tangle Vine" },
  { id: "timber", name: "Timber" },
  { id: "tremor-signs", name: "Tremor Signs" },
];

// ── Common sub-choice sets ──

export const SKILL_OPTIONS: SubChoiceOption[] = [
  { id: "acrobatics", name: "Acrobatics" },
  { id: "arcana", name: "Arcana" },
  { id: "athletics", name: "Athletics" },
  { id: "crafting", name: "Crafting" },
  { id: "deception", name: "Deception" },
  { id: "diplomacy", name: "Diplomacy" },
  { id: "intimidation", name: "Intimidation" },
  { id: "medicine", name: "Medicine" },
  { id: "nature", name: "Nature" },
  { id: "occultism", name: "Occultism" },
  { id: "performance", name: "Performance" },
  { id: "religion", name: "Religion" },
  { id: "society", name: "Society" },
  { id: "stealth", name: "Stealth" },
  { id: "survival", name: "Survival" },
  { id: "thievery", name: "Thievery" },
];

export const TERRAIN_OPTIONS: SubChoiceOption[] = [
  { id: "aquatic", name: "Aquatic" },
  { id: "arctic", name: "Arctic" },
  { id: "desert", name: "Desert" },
  { id: "forest", name: "Forest" },
  { id: "mountain", name: "Mountain" },
  { id: "plains", name: "Plains" },
  { id: "sky", name: "Sky" },
  { id: "swamp", name: "Swamp" },
  { id: "underground", name: "Underground" },
];

export const ANCESTRY_OPTIONS: SubChoiceOption[] = [
  { id: "anadi", name: "Anadi" },
  { id: "android", name: "Android" },
  { id: "automaton", name: "Automaton" },
  { id: "azarketi", name: "Azarketi" },
  { id: "catfolk", name: "Catfolk" },
  { id: "conrasu", name: "Conrasu" },
  { id: "dwarf", name: "Dwarf" },
  { id: "elf", name: "Elf" },
  { id: "fetchling", name: "Fetchling" },
  { id: "fleshwarp", name: "Fleshwarp" },
  { id: "gnoll", name: "Gnoll" },
  { id: "gnome", name: "Gnome" },
  { id: "goblin", name: "Goblin" },
  { id: "goloma", name: "Goloma" },
  { id: "grippli", name: "Grippli" },
  { id: "halfling", name: "Halfling" },
  { id: "hobgoblin", name: "Hobgoblin" },
  { id: "human", name: "Human" },
  { id: "kitsune", name: "Kitsune" },
  { id: "kobold", name: "Kobold" },
  { id: "leshy", name: "Leshy" },
  { id: "lizardfolk", name: "Lizardfolk" },
  { id: "nagaji", name: "Nagaji" },
  { id: "orc", name: "Orc" },
  { id: "poppet", name: "Poppet" },
  { id: "ratfolk", name: "Ratfolk" },
  { id: "shisk", name: "Shisk" },
  { id: "shoony", name: "Shoony" },
  { id: "skeleton", name: "Skeleton" },
  { id: "sprite", name: "Sprite" },
  { id: "strix", name: "Strix" },
  { id: "tengu", name: "Tengu" },
  { id: "vanara", name: "Vanara" },
  { id: "vishkanya", name: "Vishkanya" },
];

export const DAMAGE_TYPE_OPTIONS: SubChoiceOption[] = [
  { id: "acid", name: "Acid" },
  { id: "cold", name: "Cold" },
  { id: "electricity", name: "Electricity" },
  { id: "fire", name: "Fire" },
  { id: "poison", name: "Poison" },
  { id: "sonic", name: "Sonic" },
];

// Helper: build a cantrip sub-choice for a given tradition
export function cantripSubChoice(tradition: 'arcane' | 'divine' | 'occult' | 'primal') {
  const map = { arcane: ARCANE_CANTRIP_OPTIONS, divine: DIVINE_CANTRIP_OPTIONS, occult: OCCULT_CANTRIP_OPTIONS, primal: PRIMAL_CANTRIP_OPTIONS };
  return { label: `Choose a  cantrip`, options: map[tradition] };
}

// ── Deity domain options (PF2e Remastered) ──

export const DOMAIN_OPTIONS: SubChoiceOption[] = [
  { id: 'ambition', name: 'Ambition' },
  { id: 'change', name: 'Change' },
  { id: 'cities', name: 'Cities' },
  { id: 'cold', name: 'Cold' },
  { id: 'confidence', name: 'Confidence' },
  { id: 'creation', name: 'Creation' },
  { id: 'darkness', name: 'Darkness' },
  { id: 'death', name: 'Death' },
  { id: 'decay', name: 'Decay' },
  { id: 'delirium', name: 'Delirium' },
  { id: 'destruction', name: 'Destruction' },
  { id: 'dreams', name: 'Dreams' },
  { id: 'dust', name: 'Dust' },
  { id: 'duty', name: 'Duty' },
  { id: 'earth', name: 'Earth' },
  { id: 'family', name: 'Family' },
  { id: 'fate', name: 'Fate' },
  { id: 'fire', name: 'Fire' },
  { id: 'freedom', name: 'Freedom' },
  { id: 'glyph', name: 'Glyph' },
  { id: 'healing', name: 'Healing' },
  { id: 'indulgence', name: 'Indulgence' },
  { id: 'knowledge', name: 'Knowledge' },
  { id: 'lightning', name: 'Lightning' },
  { id: 'luck', name: 'Luck' },
  { id: 'magic', name: 'Magic' },
  { id: 'might', name: 'Might' },
  { id: 'moon', name: 'Moon' },
  { id: 'nature', name: 'Nature' },
  { id: 'nightmares', name: 'Nightmares' },
  { id: 'pain', name: 'Pain' },
  { id: 'passion', name: 'Passion' },
  { id: 'perfection', name: 'Perfection' },
  { id: 'protection', name: 'Protection' },
  { id: 'repose', name: 'Repose' },
  { id: 'secrecy', name: 'Secrecy' },
  { id: 'sorrow', name: 'Sorrow' },
  { id: 'soul', name: 'Soul' },
  { id: 'star', name: 'Star' },
  { id: 'sun', name: 'Sun' },
  { id: 'swarm', name: 'Swarm' },
  { id: 'time', name: 'Time' },
  { id: 'travel', name: 'Travel' },
  { id: 'trickery', name: 'Trickery' },
  { id: 'truth', name: 'Truth' },
  { id: 'tyranny', name: 'Tyranny' },
  { id: 'undeath', name: 'Undeath' },
  { id: 'vigil', name: 'Vigil' },
  { id: 'void', name: 'Void' },
  { id: 'water', name: 'Water' },
  { id: 'wealth', name: 'Wealth' },
  { id: 'wyrmkin', name: 'Wyrmkin' },
  { id: 'zeal', name: 'Zeal' },
];

// ── Kineticist impulse feat options (all feats with the Impulse trait) ──

export const IMPULSE_FEAT_OPTIONS: SubChoiceOption[] = [
  // Level 1
  { id: 'kineticist-aerial-boomerang', name: 'Aerial Boomerang (1st, Air)' },
  { id: 'kineticist-air-cushion', name: 'Air Cushion (1st, Air)' },
  { id: 'kineticist-armor-in-earth', name: 'Armor in Earth (1st, Earth)' },
  { id: 'kineticist-burning-jet', name: 'Burning Jet (1st, Fire)' },
  { id: 'kineticist-deflecting-wave', name: 'Deflecting Wave (1st, Water)' },
  { id: 'kineticist-eternal-torch', name: 'Eternal Torch (1st, Fire)' },
  { id: 'kineticist-flash-forge', name: 'Flash Forge (1st, Metal)' },
  { id: 'kineticist-flying-flame', name: 'Flying Flame (1st, Fire)' },
  { id: 'kineticist-four-winds', name: 'Four Winds (1st, Air)' },
  { id: 'kineticist-fresh-produce', name: 'Fresh Produce (1st, Wood)' },
  { id: 'kineticist-geologic-attunement', name: 'Geologic Attunement (1st, Earth)' },
  { id: 'kineticist-hail-of-splinters', name: 'Hail of Splinters (1st, Wood)' },
  { id: 'kineticist-hardwood-armor', name: 'Hardwood Armor (1st, Wood)' },
  { id: 'kineticist-magnetic-pinions', name: 'Magnetic Pinions (1st, Metal)' },
  { id: 'kineticist-metal-carapace', name: 'Metal Carapace (1st, Metal)' },
  { id: 'kineticist-oceans-balm', name: "Ocean's Balm (1st, Water)" },
  { id: 'kineticist-scorching-column', name: 'Scorching Column (1st, Fire)' },
  { id: 'kineticist-shard-strike', name: 'Shard Strike (1st, Metal)' },
  { id: 'kineticist-stepping-stones', name: 'Stepping Stones (1st, Earth)' },
  { id: 'kineticist-tidal-hands', name: 'Tidal Hands (1st, Water)' },
  { id: 'kineticist-timber-sentinel', name: 'Timber Sentinel (1st, Wood)' },
  { id: 'kineticist-tremor', name: 'Tremor (1st, Earth)' },
  { id: 'kineticist-whisper-on-the-wind', name: 'Whisper on the Wind (1st, Air)' },
  { id: 'kineticist-winters-clutch', name: "Winter's Clutch (1st, Water)" },
  // Level 4
  { id: 'kineticist-air-shroud', name: 'Air Shroud (4th, Air)' },
  { id: 'kineticist-ambush-bladderwort', name: 'Ambush Bladderwort (4th, Water+Wood)' },
  { id: 'kineticist-blazing-wave', name: 'Blazing Wave (4th, Fire)' },
  { id: 'kineticist-born-to-the-trees', name: 'Born to the Trees (4th, Wood)' },
  { id: 'kineticist-calcifying-sand', name: 'Calcifying Sand (4th, Earth)' },
  { id: 'kineticist-command-elemental', name: 'Command Elemental (4th, Universal)' },
  { id: 'kineticist-igneogenesis', name: 'Igneogenesis (4th, Earth)' },
  { id: 'kineticist-lava-leap', name: 'Lava Leap (4th, Earth+Fire)' },
  { id: 'kineticist-lightning-dash', name: 'Lightning Dash (4th, Air)' },
  { id: 'kineticist-living-bonfire', name: 'Living Bonfire (4th, Fire+Wood)' },
  { id: 'kineticist-magnetic-field', name: 'Magnetic Field (4th, Metal)' },
  { id: 'kineticist-plate-in-treasure', name: 'Plate in Treasure (4th, Metal)' },
  { id: 'kineticist-rain-of-rust', name: 'Rain of Rust (4th, Metal+Water)' },
  { id: 'kineticist-ravel-of-thorns', name: 'Ravel of Thorns (4th, Wood)' },
  { id: 'kineticist-return-to-the-sea', name: 'Return to the Sea (4th, Water)' },
  { id: 'kineticist-thermal-nimbus', name: 'Thermal Nimbus (4th, Fire)' },
  { id: 'kineticist-tumbling-lumber', name: 'Tumbling Lumber (4th, Wood)' },
  { id: 'kineticist-whirling-grindstone', name: 'Whirling Grindstone (4th, Earth+Metal)' },
  { id: 'kineticist-winter-sleet', name: 'Winter Sleet (4th, Water)' },
  // Level 6
  { id: 'kineticist-counter-element', name: 'Counter Element (6th, Universal)' },
  { id: 'kineticist-fearsome-familiar', name: 'Fearsome Familiar (6th, Universal)' },
  { id: 'kineticist-clear-as-air', name: 'Clear as Air (6th, Air)' },
  { id: 'kineticist-flinging-updraft', name: 'Flinging Updraft (6th, Air)' },
  { id: 'kineticist-sand-snatcher', name: 'Sand Snatcher (6th, Earth)' },
  { id: 'kineticist-weight-of-stone', name: 'Weight of Stone (6th, Earth)' },
  { id: 'kineticist-crawling-fire', name: 'Crawling Fire (6th, Fire)' },
  { id: 'kineticist-volcanic-escape', name: 'Volcanic Escape (6th, Fire)' },
  { id: 'kineticist-consume-power', name: 'Consume Power (6th, Metal)' },
  { id: 'kineticist-scrap-barricade', name: 'Scrap Barricade (6th, Metal)' },
  { id: 'kineticist-driving-rain', name: 'Driving Rain (6th, Water)' },
  { id: 'kineticist-torrent-in-the-blood', name: 'Torrent in the Blood (6th, Water)' },
  { id: 'kineticist-dash-of-herbs', name: 'Dash of Herbs (6th, Wood)' },
  { id: 'kineticist-wooden-palisade', name: 'Wooden Palisade (6th, Wood)' },
  { id: 'kineticist-ash-strider', name: 'Ash Strider (6th, Air+Fire)' },
  { id: 'kineticist-desert-wind', name: 'Desert Wind (6th, Air+Earth)' },
  { id: 'kineticist-elemental-artillery', name: 'Elemental Artillery (6th, Metal+Wood)' },
  { id: 'kineticist-jagged-berms', name: 'Jagged Berms (6th, Earth+Wood)' },
  { id: 'kineticist-lightning-rod', name: 'Lightning Rod (6th, Air+Metal)' },
  { id: 'kineticist-molten-wire', name: 'Molten Wire (6th, Fire+Metal)' },
  { id: 'kineticist-rising-hurricane', name: 'Rising Hurricane (6th, Air+Water)' },
  { id: 'kineticist-roiling-mudslide', name: 'Roiling Mudslide (6th, Earth+Water)' },
  { id: 'kineticist-steam-knight', name: 'Steam Knight (6th, Fire+Water)' },
  { id: 'kineticist-tree-of-duality', name: 'Tree of Duality (6th, Air+Wood)' },
  // Level 8
  { id: 'kineticist-purify-element', name: 'Purify Element (8th, Universal)' },
  { id: 'kineticist-cyclonic-ascent', name: 'Cyclonic Ascent (8th, Air)' },
  { id: 'kineticist-storm-spiral', name: 'Storm Spiral (8th, Air)' },
  { id: 'kineticist-spike-skin', name: 'Spike Skin (8th, Earth)' },
  { id: 'kineticist-swim-through-earth', name: 'Swim Through Earth (8th, Earth)' },
  { id: 'kineticist-kindle-inner-flames', name: 'Kindle Inner Flames (8th, Fire)' },
  { id: 'kineticist-solar-detonation', name: 'Solar Detonation (8th, Fire)' },
  { id: 'kineticist-conductive-sphere', name: 'Conductive Sphere (8th, Metal)' },
  { id: 'kineticist-retch-rust', name: 'Retch Rust (8th, Metal)' },
  { id: 'kineticist-call-the-hurricane', name: 'Call the Hurricane (8th, Water)' },
  { id: 'kineticist-impenetrable-fog', name: 'Impenetrable Fog (8th, Water)' },
  { id: 'kineticist-drifting-pollen', name: 'Drifting Pollen (8th, Wood)' },
  { id: 'kineticist-sanguivolent-roots', name: 'Sanguivolent Roots (8th, Wood)' },
  // Level 12
  { id: 'kineticist-ghosts-in-the-storm', name: 'Ghosts in the Storm (12th, Air)' },
  { id: 'kineticist-wiles-on-the-wind', name: 'Wiles on the Wind (12th, Air)' },
  { id: 'kineticist-rattle-the-earth', name: 'Rattle the Earth (12th, Earth)' },
  { id: 'kineticist-rock-rampart', name: 'Rock Rampart (12th, Earth)' },
  { id: 'kineticist-architect-of-flame', name: 'Architect of Flame (12th, Fire)' },
  { id: 'kineticist-furnace-form', name: 'Furnace Form (12th, Fire)' },
  { id: 'kineticist-rain-of-razors', name: 'Rain of Razors (12th, Metal)' },
  { id: 'kineticist-shattershields', name: 'Shattershields (12th, Metal)' },
  { id: 'kineticist-glacial-prison', name: 'Glacial Prison (12th, Water)' },
  { id: 'kineticist-sea-glass-guardians', name: 'Sea Glass Guardians (12th, Water)' },
  { id: 'kineticist-hedge-maze', name: 'Hedge Maze (12th, Wood)' },
  { id: 'kineticist-witchwood-seed', name: 'Witchwood Seed (12th, Wood)' },
  // Level 14
  { id: 'kineticist-body-of-air', name: 'Body of Air (14th, Air)' },
  { id: 'kineticist-assume-earths-mantle', name: "Assume Earth's Mantle (14th, Earth)" },
  { id: 'kineticist-walk-through-the-conflagration', name: 'Walk Through the Conflagration (14th, Fire)' },
  { id: 'kineticist-alloy-flesh-and-steel', name: 'Alloy Flesh and Steel (14th, Metal)' },
  { id: 'kineticist-barrier-of-boreal-frost', name: 'Barrier of Boreal Frost (14th, Water)' },
  { id: 'kineticist-orchards-endurance', name: "Orchard's Endurance (14th, Wood)" },
  // Level 16
  { id: 'kineticist-imperious-aura', name: 'Imperious Aura (16th, Universal)' },
  // Level 18
  { id: 'kineticist-crowned-in-tempests-fury', name: "Crowned in Tempest's Fury (18th, Air)" },
  { id: 'kineticist-infinite-expanse-of-bluest-heaven', name: 'Infinite Expanse of Bluest Heaven (18th, Air)' },
  { id: 'kineticist-rebirth-in-living-stone', name: 'Rebirth in Living Stone (18th, Earth)' },
  { id: 'kineticist-the-shattered-mountain-weeps', name: 'The Shattered Mountain Weeps (18th, Earth)' },
  { id: 'kineticist-all-shall-end-in-flames', name: 'All Shall End in Flames (18th, Fire)' },
  { id: 'kineticist-ignite-the-sun', name: 'Ignite the Sun (18th, Fire)' },
  { id: 'kineticist-beasts-of-slumbering-steel', name: 'Beasts of Slumbering Steel (18th, Metal)' },
  { id: 'kineticist-ride-the-tsunami', name: 'Ride the Tsunami (18th, Water)' },
  { id: 'kineticist-usurp-the-lunar-reins', name: 'Usurp the Lunar Reins (18th, Water)' },
  { id: 'kineticist-rouse-the-forests-fury', name: "Rouse the Forest's Fury (18th, Wood)" },
  { id: 'kineticist-turn-the-wheel-of-seasons', name: 'Turn the Wheel of Seasons (18th, Wood)' },
];
