import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// SUMMONER CLASS FEATURES (Automatically Granted)
// PF2e — Secrets of Magic
// ──────────────────────────────────────────────────────────

const RAW_SUMMONER_CLASS_FEATURES: FeatEntry[] = [
  // —— Level 1 ——————————————————————————————————————————————
  {
    id: 'summoner-eidolon',
    name: 'Eidolon',
    source: 'Summoner',
    category: 'class_feature',
    level: 1,
    description:
      'You have a connection with a powerful and usually otherworldly entity called an eidolon, and you can use your life force as a conduit to manifest this ephemeral entity into the mortal world. Your eidolon determines your spellcasting tradition. Choose an eidolon type: Angel (divine), Anger Phantom (occult), Beast (primal), Construct (arcane), Demon (divine), Devotion Phantom (occult), Dragon (arcane), Elemental (primal), Fey (primal), Plant (primal), Psychopomp (divine), or Undead (divine). Your magical connection takes the form of a sigil on each of your bodies that glows while the eidolon is manifested and can\'t be covered or disguised. You and your eidolon share your actions, multiple attack penalty, and Hit Points. Each round, you can use any of your actions for yourself or your eidolon. You bring your eidolon into reality with Manifest Eidolon (3 actions, concentrate, conjuration, manipulate, teleportation): your eidolon appears in an adjacent open space and can take a single action; it must remain within 100 feet of you. You coordinate actions with Act Together (1–3 actions, tandem, frequency once per round): one of you takes an action or activity using the same number of actions, and the other takes a single action. You communicate telepathically at all times. Share Senses (1 action, concentrate, divination, scrying): project your senses into your eidolon for up to 1 minute, losing your own sensory information; your eidolon can also use this ability to project into you.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics:
      'Builder must capture eidolon type selection. Eidolon type determines tradition (arcane/divine/occult/primal), stats, starting unarmed attacks, and skills. Shared HP pool — damage to either reduces the pool, healing to either recovers it. If both affected by same effect, apply only once (greater amount). Shared actions — 3 actions per round total split between summoner and eidolon. Eidolon is not a minion; does not have minion or summoned trait. If either slowed/stunned/quickened, apply only the more severe effect. Manifest Eidolon is 3 actions; eidolon must stay within 100 ft; if forced beyond or summoner hits 0 HP, eidolon unmanifests. Act Together once per round. Eidolon can wear/use only eidolon-trait items (max 2 invested). Eidolon benefits from summoner\'s invested item bonuses to Perception/skills, armor potency/resilient runes (for AC/saves), and handwraps runes (for Strikes).',
    subChoices: { label: 'Choose an eidolon type', options: [
      { id: 'angel', name: 'Angel Eidolon', description: 'Divine tradition; celestial protector' },
      { id: 'anger-phantom', name: 'Anger Phantom Eidolon', description: 'Occult tradition; wrathful spirit' },
      { id: 'beast', name: 'Beast Eidolon', description: 'Primal tradition; natural animal' },
      { id: 'construct', name: 'Construct Eidolon', description: 'Arcane tradition; crafted creature' },
      { id: 'demon', name: 'Demon Eidolon', description: 'Divine tradition; fiendish tempter' },
      { id: 'devotion-phantom', name: 'Devotion Phantom Eidolon', description: 'Occult tradition; loyal spirit' },
      { id: 'dragon', name: 'Dragon Eidolon', description: 'Arcane tradition; draconic ally' },
      { id: 'elemental', name: 'Elemental Eidolon', description: 'Primal tradition; elemental being' },
      { id: 'fey', name: 'Fey Eidolon', description: 'Primal tradition; fey trickster' },
      { id: 'plant', name: 'Plant Eidolon', description: 'Primal tradition; verdant guardian' },
      { id: 'psychopomp', name: 'Psychopomp Eidolon', description: 'Divine tradition; death\'s shepherd' },
      { id: 'undead', name: 'Undead Eidolon', description: 'Divine tradition; undead thrall' },
    ] },
  },
  {
    id: 'summoner-summoner-spellcasting',
    name: 'Summoner Spellcasting',
    source: 'Summoner',
    category: 'class_feature',
    level: 1,
    description:
      'Your link to your eidolon grants you limited magic connected to your eidolon\'s nature. You can cast spells using the Cast a Spell activity and supply material, somatic, and verbal components. Because of the magic you draw from your eidolon, you can usually replace material components with somatic components, so you don\'t need a material component pouch. You use bounded spellcasting — fewer spell slots than a full caster, with a maximum of 4 slots at any time starting at 4th level. At 1st level you can cast one 1st-rank spell and five cantrips. Beginning at 5th level, you lose lower-rank spell slots as you gain higher-rank ones. Your key attribute is Charisma.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics:
      'Bounded spontaneous caster. Tradition determined by eidolon type. Slots per day: L1: 1×1st; L2: 2×1st; L3: 2×1st+1×2nd; L4: 2×1st+2×2nd; L5 onward: lose lowest rank, max 4 slots total (2+2 of top two ranks). 5 cantrips at all levels. Cantrips auto-heighten to half level rounded up. Spell attack/DC use CHA. Proficiency: trained→expert (L9)→master (L17).',
  },
  {
    id: 'summoner-spell-repertoire',
    name: 'Spell Repertoire',
    source: 'Summoner',
    category: 'class_feature',
    level: 1,
    description:
      'At 1st level, you learn two 1st-rank spells and five cantrips from your eidolon\'s tradition. You add to this repertoire as you increase in level — each time you gain a spell slot, you add a spell of the same rank. At 4th level your repertoire reaches its maximum of five spells. At 5th level, when you lose your lowest spell slots, you also lose two spells from your repertoire. Each time you gain a level and learn new spells, you can swap out one old spell for a different spell of the same rank. At 6th level and every even level thereafter, you can swap any number of spells (keeping at least one of your lowest available rank).',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics:
      'Repertoire starts: 2 spells (1st-rank) + 5 cantrips. Max size: 5 spells + 5 cantrips. At L5+ when losing lower slots, also lose 2 spells. Swap 1 spell per level-up (same rank). At even levels L6+, swap any number (keep ≥1 at lowest rank). Cantrips can also be swapped.',
  },
  {
    id: 'summoner-link-spells',
    name: 'Link Spells',
    source: 'Summoner',
    category: 'class_feature',
    level: 1,
    description:
      'Your connection to your eidolon allows you to cast link spells — special focus spells forged through your shared connection. It costs 1 Focus Point to cast a focus spell. You start with a focus pool of 1 Focus Point, refilled during daily preparations or by spending 10 minutes using the Refocus activity to connect with your eidolon. Focus spells are automatically heightened to half your level rounded up. You learn the evolution surge link spell, which grants your eidolon one of several useful benefits. You also learn the boost eidolon link cantrip, which briefly improves your eidolon\'s attack power and doesn\'t cost Focus Points.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics:
      'Focus pool starts at 1 (max 3). Refocus by connecting with eidolon (conversation, play, meditation). Link cantrips (like boost eidolon) are free — no Focus Point cost. Evolution surge (focus spell): grants eidolon one benefit. Boost eidolon (link cantrip): increases eidolon\'s next attack damage. Feats can add more link spells and increase focus pool.',
  },
  {
    id: 'summoner-evolution-feat',
    name: 'Evolution Feat',
    source: 'Summoner',
    category: 'class_feature',
    level: 1,
    description:
      'You gain an evolution feat for your eidolon at 1st level, representing the differences that make it unique from other eidolons of its type. Evolution feats are a special type of summoner class feat that customize your eidolon through your shared link. If you retrain this feat, the replacement must also be an evolution feat.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics:
      'Builder must offer selection of evolution feats (feats with the Evolution trait) at L1. Retraining must stay within evolution feats.',
  },

  // —— Level 3 ——————————————————————————————————————————————
  {
    id: 'summoner-shared-vigilance',
    name: 'Shared Vigilance',
    source: 'Summoner',
    category: 'class_feature',
    level: 3,
    description:
      'You and your eidolon work together to remain alert to threats around you, allowing you to perceive far more together than you could individually. Your proficiency rank in Perception and your eidolon\'s proficiency rank in Perception increase to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Perception proficiency → expert for both summoner and eidolon.',
  },
  {
    id: 'summoner-unlimited-signature-spells',
    name: 'Unlimited Signature Spells',
    source: 'Summoner',
    category: 'class_feature',
    level: 3,
    description:
      'All of your spells are signature spells. That means that if you know a spell, you can heighten it freely by casting it from a higher-rank spell slot, up to the maximum rank of spell you can cast. You can similarly cast any of its lower-rank versions without learning them separately.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Every spell in repertoire is a signature spell — can be freely heightened to any available rank or cast at lower ranks.',
  },

  // —— Level 5 ——————————————————————————————————————————————
  {
    id: 'summoner-eidolon-unarmed-expertise',
    name: 'Eidolon Unarmed Expertise',
    source: 'Summoner',
    category: 'class_feature',
    level: 5,
    description:
      'Your eidolon becomes more capable of using its unarmed attacks. Its proficiency rank for unarmed attacks increases to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon unarmed attack proficiency → expert.',
  },

  // —— Level 7 ——————————————————————————————————————————————
  {
    id: 'summoner-eidolon-symbiosis',
    name: 'Eidolon Symbiosis',
    source: 'Summoner',
    category: 'class_feature',
    level: 7,
    description:
      'Your connection with your eidolon strengthens, granting your eidolon access to a new ability depending on its type, as described in Eidolon Abilities in each eidolon\'s entry.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics:
      'Eidolon gains symbiosis ability determined by its type (e.g., Angel: hallowed strikes; Beast: beast\'s charge; Dragon: breath weapon; etc.). Builder must look up the specific ability for the chosen eidolon type.',
  },
  {
    id: 'summoner-eidolon-weapon-specialization',
    name: 'Eidolon Weapon Specialization',
    source: 'Summoner',
    category: 'class_feature',
    level: 7,
    description:
      'Your eidolon has learned how to inflict greater injuries with its unarmed attacks. It deals 2 additional damage with unarmed attacks in which it\'s an expert. This damage increases to 3 if it\'s a master, and 4 if it\'s legendary.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon bonus damage: +2 (expert), +3 (master), +4 (legendary). Applies to eidolon unarmed attacks only.',
  },

  // —— Level 9 ——————————————————————————————————————————————
  {
    id: 'summoner-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Summoner',
    category: 'class_feature',
    level: 9,
    description:
      'As your connection to your eidolon deepens, the power of your spells increases. Your proficiency ranks for spell attack rolls and spell DCs for spells of your eidolon\'s tradition increase to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Spell attack/DC proficiency → expert.',
  },
  {
    id: 'summoner-shared-reflexes',
    name: 'Shared Reflexes',
    source: 'Summoner',
    category: 'class_feature',
    level: 9,
    description:
      'You and your eidolon boost each other\'s reflexes, allowing you both to roll away from danger. Your proficiency rank for Reflex saves and your eidolon\'s proficiency rank for Reflex saves increase to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Reflex save proficiency → expert for both summoner and eidolon.',
  },

  // —— Level 11 —————————————————————————————————————————————
  {
    id: 'summoner-eidolon-defensive-expertise',
    name: 'Eidolon Defensive Expertise',
    source: 'Summoner',
    category: 'class_feature',
    level: 11,
    description:
      'Your eidolon increases its ability to avoid attacks. Its proficiency rank for unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon unarmored defense proficiency → expert.',
  },
  {
    id: 'summoner-simple-weapon-expertise',
    name: 'Simple Weapon Expertise',
    source: 'Summoner',
    category: 'class_feature',
    level: 11,
    description:
      'Training and magic improved your weapon technique. Your proficiency rank for simple weapons and unarmed attacks increases to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Simple weapons and unarmed attacks proficiency → expert.',
  },
  {
    id: 'summoner-twin-juggernauts',
    name: 'Twin Juggernauts',
    source: 'Summoner',
    category: 'class_feature',
    level: 11,
    description:
      'You and your eidolon fight off physical hardship together with your shared life force. Your proficiency rank for Fortitude saves and your eidolon\'s proficiency rank for Fortitude saves increase to master. When you roll a success on a Fortitude save, you get a critical success instead. When your eidolon rolls a success on a Fortitude save, it gets a critical success instead.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Fortitude save proficiency → master for both summoner and eidolon. Success → critical success on Fortitude saves for both.',
  },

  // —— Level 13 —————————————————————————————————————————————
  {
    id: 'summoner-defensive-robes',
    name: 'Defensive Robes',
    source: 'Summoner',
    category: 'class_feature',
    level: 13,
    description:
      'The flow of magic around you increases your ability to avoid attacks. Your proficiency rank in unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Unarmored defense proficiency → expert.',
  },
  {
    id: 'summoner-eidolon-unarmed-mastery',
    name: 'Eidolon Unarmed Mastery',
    source: 'Summoner',
    category: 'class_feature',
    level: 13,
    description:
      'Your eidolon truly masters its unarmed attacks, reaching greater heights. Its proficiency rank for unarmed attacks increases to master.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon unarmed attack proficiency → master.',
  },
  // Weapon Specialization (L13) — uses shared template
  createClassFeature(WEAPON_SPECIALIZATION, 'Summoner', 13),

  // —— Level 15 —————————————————————————————————————————————
  {
    id: 'summoner-greater-eidolon-specialization',
    name: 'Greater Eidolon Specialization',
    source: 'Summoner',
    category: 'class_feature',
    level: 15,
    description:
      'Your eidolon\'s damage from weapon specialization increases to 4 with unarmed attacks in which it\'s an expert, 6 if it\'s a master, and 8 if it\'s legendary.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon bonus damage: +4 (expert), +6 (master), +8 (legendary). Replaces Eidolon Weapon Specialization values.',
  },
  {
    id: 'summoner-shared-resolve',
    name: 'Shared Resolve',
    source: 'Summoner',
    category: 'class_feature',
    level: 15,
    description:
      'You and your eidolon steel your mind together against effects that threaten you, each protecting the other\'s mind from danger. Your and your eidolon\'s proficiency ranks for Will saves increase to master. When you roll a success on a Will save, you get a critical success instead. When your eidolon rolls a success on a Will save, it gets a critical success instead.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Will save proficiency → master for both summoner and eidolon. Success → critical success on Will saves for both.',
  },

  // —— Level 17 —————————————————————————————————————————————
  {
    id: 'summoner-eidolon-transcendence',
    name: 'Eidolon Transcendence',
    source: 'Summoner',
    category: 'class_feature',
    level: 17,
    description:
      'Your connection with your eidolon approaches its peak, granting your eidolon access to a powerful new ability depending on its type, as described in Eidolon Abilities in each eidolon\'s entry. This ability also increases one of the eidolon\'s ability scores by 2.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains transcendence ability determined by its type. One eidolon ability score increases by 2. Builder must look up the specific ability for the chosen eidolon type.',
  },
  {
    id: 'summoner-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Summoner',
    category: 'class_feature',
    level: 17,
    description:
      'Your connection to your eidolon is strong enough to grant you mastery over associated spells. Your proficiency ranks for spell attack rolls and spell DCs for spells of your eidolon\'s tradition increase to master.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Spell attack/DC proficiency → master.',
  },

  // —— Level 19 —————————————————————————————————————————————
  {
    id: 'summoner-eidolon-defensive-mastery',
    name: 'Eidolon Defensive Mastery',
    source: 'Summoner',
    category: 'class_feature',
    level: 19,
    description:
      'Your eidolon\'s form becomes particularly difficult to assail. Its proficiency rank for unarmored defense increases to master.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon unarmored defense proficiency → master.',
  },
  {
    id: 'summoner-instant-manifestation',
    name: 'Instant Manifestation',
    source: 'Summoner',
    category: 'class_feature',
    level: 19,
    description:
      'You can manifest your eidolon with incredible speed. You can use Manifest Eidolon as a single action, instead of a three-action activity.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Manifest Eidolon becomes 1 action instead of 3 actions.',
  },
];

export const SUMMONER_CLASS_FEATURES: FeatEntry[] = RAW_SUMMONER_CLASS_FEATURES.map(f => ({
  ...f,
  traits: f.traits ?? ['Summoner'],
}));

// ──────────────────────────────────────────────────────────
// SUMMONER CLASS FEATS
// PF2e — Secrets of Magic + Legacy supplements
// ──────────────────────────────────────────────────────────

const RAW_SUMMONER_CLASS_FEATS: FeatEntry[] = [
  // —— Level 1 ——————————————————————————————————————————————
  {
    id: 'summoner-advanced-weaponry',
    name: 'Advanced Weaponry',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'Your eidolon\'s attack evolves. Choose one of your eidolon\'s starting melee unarmed attacks. It gains one of the following traits, chosen when you gain the feat: disarm, grapple, nonlethal, shove, trip, or versatile bludgeoning, piercing, or slashing.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Choose one starting melee unarmed attack and one trait: disarm, grapple, nonlethal, shove, trip, or versatile (B/P/S).',
    subChoices: { label: 'Choose attack trait', options: [
      { id: 'disarm', name: 'Disarm' },
      { id: 'grapple', name: 'Grapple' },
      { id: 'nonlethal', name: 'Nonlethal' },
      { id: 'shove', name: 'Shove' },
      { id: 'trip', name: 'Trip' },
      { id: 'versatile-b', name: 'Versatile Bludgeoning' },
      { id: 'versatile-p', name: 'Versatile Piercing' },
      { id: 'versatile-s', name: 'Versatile Slashing' },
    ] },
  },
  {
    id: 'summoner-dual-studies',
    name: 'Dual Studies',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'You and your eidolon have some skills you practice on your own. Choose two skills. Your eidolon becomes trained in one of those skills and you become trained in the other skill. At 7th level, you each become an expert in the chosen skills. These skill proficiencies are not shared between you and your eidolon.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Choose 2 skills. Eidolon trained in one, summoner trained in the other. At L7, both become expert. These are NOT shared proficiencies.',
  },
  {
    id: 'summoner-energy-heart',
    name: 'Energy Heart',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'Your eidolon\'s heart beats with energy. Choose an energy damage type other than force. One of its unarmed attacks changes its damage type to the chosen type, and it gains resistance to that type equal to half your level (minimum 1).',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Choose energy type (not force). One unarmed attack changes to that damage type. Eidolon gains resistance to that type = half level (min 1). Leads to: Dual Energy Heart, Energy Resistance.',
    subChoices: { label: 'Choose an energy type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'sonic', name: 'Sonic' },
      { id: 'vitality', name: 'Vitality' },
      { id: 'void', name: 'Void' },
    ] },
  },
  {
    id: 'summoner-expanded-senses',
    name: 'Expanded Senses',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'Your eidolon evolves more acute senses. Your eidolon gains low-light vision and darkvision, as well as scent as an imprecise sense with a range of 30 feet.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains: low-light vision, darkvision, scent (imprecise 30 ft).',
  },
  {
    id: 'summoner-extend-boost',
    name: 'Extend Boost',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'You can increase the duration of your eidolon\'s boosts. You learn the extend boost link spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Learn extend boost link spell. Focus pool +1.',
  },
  {
    id: 'summoner-glider-form',
    name: 'Glider Form',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'Your eidolon evolves wings, a buoyant body, or some other means to control descent. It glides slowly toward the ground, 5 feet down and up to 25 feet forward through the air. As long as it spends at least 1 action gliding each round and has not yet reached the ground, it remains in the air at the end of your turn.',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Move', 'Summoner'],
    actionCost: 1,
    mechanics: 'Eidolon glides: 5 ft down, up to 25 ft forward. Must spend ≥1 action/round to stay aloft. Leads to: Airborne Form.',
  },
  {
    id: 'summoner-meld-into-eidolon',
    name: 'Meld into Eidolon',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'Your physical form can combine with that of your eidolon. You Manifest your Eidolon, but instead of summoning it into an adjacent space, you become it. While manifested this way, you use its statistics and can\'t act except to direct it to use Manifest Eidolon to unmanifest. You can\'t cast spells, activate or benefit from your magic items, use tandem actions, or use other abilities requiring you to act separately. You can\'t be separately targeted while melded. When you reach 0 HP, your eidolon unmanifests leaving your body behind, unconscious and dying. You can Meld into Eidolon while your eidolon is already manifested if it\'s adjacent to you.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 3,
    mechanics: 'Manifest Eidolon variant: you merge into eidolon. Use eidolon stats. Can\'t act, cast spells, use tandem, or benefit from your items. Can\'t be targeted separately. At 0 HP eidolon unmanifests and summoner is unconscious/dying.',
  },
  {
    id: 'summoner-unfetter-eidolon',
    name: 'Unfetter Eidolon',
    source: 'Summoner',
    category: 'class',
    level: 1,
    description:
      'You can allow your eidolon to travel far from your side. You learn the unfetter eidolon link spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Learn unfetter eidolon link spell. Focus pool +1.',
  },

  // —— Level 2 ——————————————————————————————————————————————
  {
    id: 'summoner-alacritous-action',
    name: 'Alacritous Action',
    source: 'Summoner',
    category: 'class',
    level: 2,
    description:
      'Your eidolon moves more quickly. It gains a +10-foot status bonus to its Speed.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains +10-foot status bonus to Speed.',
  },
  {
    id: 'summoner-amphibious-form',
    name: 'Amphibious Form',
    source: 'Summoner',
    category: 'class',
    level: 2,
    description:
      'Your eidolon adapts to life on land and underwater. It gains the amphibious trait, allowing it to breathe in water and air and to avoid the normal –2 penalty for making bludgeoning and slashing unarmed Strikes underwater. It gains a swim Speed equal to its land Speed or 25 feet, whichever is less; or if it is normally aquatic, it gains a land Speed equal to its swim Speed or 25 feet, whichever is less.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains amphibious trait. No –2 penalty for B/S strikes underwater. Swim Speed = min(land Speed, 25 ft) or land Speed = min(swim Speed, 25 ft) if aquatic.',
  },
  {
    id: 'summoner-magical-understudy',
    name: 'Magical Understudy',
    source: 'Summoner',
    category: 'class',
    level: 2,
    description:
      'Your eidolon evolves to cast spells. It gains the Cast a Spell activity and learns two cantrips of its tradition, which it can cast as innate spells.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains Cast a Spell and 2 innate cantrips of its tradition. Leads to: Magical Adept, Share Eidolon Magic.',
  },
  {
    id: 'summoner-ranged-combatant',
    name: 'Ranged Combatant',
    source: 'Summoner',
    category: 'class',
    level: 2,
    description:
      'Spines, flame jets, and holy blasts are just some of the ways your eidolon might strike from a distance. It gains a ranged unarmed attack with a range increment of 30 feet that deals 1d4 damage and has the magical and propulsive traits. When you select this feat, choose a damage type: acid, bludgeoning, cold, electricity, fire, negative, piercing, positive, or slashing. If your eidolon is a celestial, fiend, or monitor with an alignment other than true neutral, you can choose a damage type in its alignment.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains ranged unarmed attack: 30 ft range increment, 1d4 damage, magical + propulsive traits. Choose damage type from: acid, bludgeoning, cold, electricity, fire, negative, piercing, positive, slashing (or alignment type if celestial/fiend/monitor).',
    subChoices: { label: 'Choose damage type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'bludgeoning', name: 'Bludgeoning' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'negative', name: 'Negative' },
      { id: 'piercing', name: 'Piercing' },
      { id: 'positive', name: 'Positive' },
      { id: 'slashing', name: 'Slashing' },
    ] },
  },
  {
    id: 'summoner-reinforce-eidolon',
    name: 'Reinforce Eidolon',
    source: 'Summoner',
    category: 'class',
    level: 2,
    description:
      'You buffer your eidolon. You gain the reinforce eidolon link cantrip.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Learn reinforce eidolon link cantrip (free to cast, no Focus Point cost).',
  },
  {
    id: 'summoner-steed-form',
    name: 'Steed Form',
    source: 'Summoner',
    category: 'class',
    level: 2,
    description:
      'Your eidolon changes to make it particularly effective as your mount. While you ride it, you get your full number of actions each round instead of reducing them to 2. This applies only when you ride your eidolon, not when anyone else does. Your eidolon must still be at least one size category larger than you to ride it. Since you work together to move, your eidolon\'s move actions while you\'re mounted gain the tandem trait.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'While mounted on eidolon: full actions (not reduced to 2). Eidolon must be ≥1 size larger. Eidolon move actions while mounted gain tandem trait. Only applies when summoner rides eidolon.',
  },
  // —— Level 4 ——————————————————————————————————————————————
  {
    id: 'summoner-bloodletting-claws',
    name: 'Bloodletting Claws',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'Your eidolon inflicts bleeding wounds on a telling blow. If your eidolon critically hits with a melee unarmed Strike that deals slashing or piercing damage, its target takes 1d6 persistent bleed damage. Your eidolon gains an item bonus to this bleed damage equal to the unarmed attack\'s item bonus to attack rolls. This is a critical specialization effect.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'On eidolon melee unarmed crit (slashing or piercing): target takes 1d6 persistent bleed + item bonus to bleed = attack\'s item bonus. Critical specialization effect. Leads to: Blood Frenzy.',
  },
  {
    id: 'summoner-defend-summoner',
    name: 'Defend Summoner',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'Your eidolon blocks attacks against you. After your eidolon uses this action, you gain a +2 circumstance bonus to AC until the beginning of your next turn. This bonus applies only while you\'re within your eidolon\'s reach (in most cases, this means your eidolon is adjacent to you or in your space).',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Summoner'],
    actionCost: 1,
    mechanics: 'Eidolon action. Summoner gains +2 circumstance bonus to AC until start of next turn. Only while within eidolon\'s reach.',
  },
  {
    id: 'summoner-dual-energy-heart',
    name: 'Dual Energy Heart',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'A second energy dwells in your eidolon. Choose an additional energy damage type. Your eidolon\'s unarmed attack that deals energy damage gains the versatile trait for the second energy damage type, and your eidolon gains resistance to the second type of energy damage equal to half your level.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Energy Heart'],
    mechanics: 'Choose second energy type. Energy unarmed attack gains versatile (second type). Eidolon gains resistance to second type = half level.',
    subChoices: { label: 'Choose second energy type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'sonic', name: 'Sonic' },
      { id: 'vitality', name: 'Vitality' },
      { id: 'void', name: 'Void' },
    ] },
  },
  {
    id: 'summoner-lifelink-surge',
    name: 'Lifelink Surge',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'You learn the lifelink surge link spell. Increase the number of Focus Points in your focus pool by 1.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Learn lifelink surge link spell. Focus pool +1.',
  },
  {
    id: 'summoner-reactive-dismissal',
    name: 'Reactive Dismissal',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'You abruptly dismiss your eidolon to reduce the damage it takes, though this makes summoning it again more difficult. Reduce the triggering damage to your eidolon by double your level, and your eidolon unmanifests. You can\'t Manifest your Eidolon again until after the end of your next turn.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'reaction',
    mechanics: 'Trigger: Your eidolon would take damage. Reduce damage by 2×level. Eidolon unmanifests. Can\'t re-manifest until after end of next turn.',
  },
  {
    id: 'summoner-shrink-down',
    name: 'Shrink Down',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'Your eidolon can shrink to fit into small spaces. Your eidolon reduces in size, to a minimum of size Small. It can use this action again while shrunk to return to its normal size. Its reach becomes 5 feet, or 10 feet if shrinking to Large with Towering Size.',
    implemented: 'full',
    traits: ['Concentrate', 'Eidolon', 'Evolution', 'Summoner', 'Transmutation'],
    actionCost: 1,
    mechanics: 'Eidolon shrinks to min Small. Use again to return to normal. Reach becomes 5 ft (or 10 ft if Large via Towering Size). Leads to: Miniaturize.',
  },
  {
    id: 'summoner-skilled-partner',
    name: 'Skilled Partner',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'Your eidolon gains a 1st-level skill feat and a 2nd-level or lower skill feat. At 7th level, your eidolon gains an additional skill feat, of 7th level or lower.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains: one 1st-level skill feat + one ≤2nd-level skill feat. At L7: additional ≤7th-level skill feat.',
  },
  {
    id: 'summoner-tandem-movement',
    name: 'Tandem Movement',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'You and your eidolon move together. You each use a single action to Stride. Either of you that has the corresponding movement type can Burrow, Climb, Fly, or Swim instead.',
    implemented: 'full',
    traits: ['Summoner', 'Tandem'],
    actionCost: 1,
    mechanics: 'Both summoner and eidolon Stride (or Burrow/Climb/Fly/Swim if applicable) as part of one action.',
  },
  {
    id: 'summoner-vibration-sense',
    name: 'Vibration Sense',
    source: 'Summoner',
    category: 'class',
    level: 4,
    description:
      'Your eidolon gains tremorsense as an imprecise sense with a range of 30 feet. If aquatic, it gains wavesense as an imprecise sense with a range of 30 feet instead. If amphibious, it gains both.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains tremorsense (imprecise 30 ft). Aquatic: wavesense instead. Amphibious: both.',
  },

  // —— Level 6 ——————————————————————————————————————————————
  {
    id: 'summoner-blood-frenzy',
    name: 'Blood Frenzy',
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'Your eidolon flies into a frenzy. It gains the benefits of boost eidolon and gains temporary HP equal to your level, but takes a –2 penalty to AC. It can\'t voluntarily end the frenzy or start another frenzy while in the frenzy. The frenzy lasts for 1 minute, after which your eidolon is fatigued for 1 minute and can\'t start another frenzy for 1 minute.',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Summoner'],
    actionCost: 1,
    prerequisites: ['Bloodletting Claws'],
    mechanics: 'Eidolon action. Requires: last action dealt bleed to a living creature. Gains boost eidolon + temp HP = level, –2 AC penalty. Duration: 1 min. After: fatigued 1 min, can\'t frenzy for 1 min.',
  },
  {
    id: 'summoner-eidolons-opportunity',
    name: "Eidolon's Opportunity",
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'Your eidolon makes a melee Strike against the triggering creature. If the attack is a critical hit and the trigger was a manipulate action, your eidolon disrupts that action. This Strike doesn\'t count toward your multiple attack penalty, and your multiple attack penalty doesn\'t apply to this Strike.',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Summoner'],
    actionCost: 'reaction',
    mechanics: 'Trigger: A creature within eidolon\'s reach uses a manipulate or move action, makes a ranged attack, or leaves a square during a move action. Eidolon melee Strike. Crit on manipulate disrupts it. No MAP interaction.',
  },
  {
    id: 'summoner-eidolons-wrath',
    name: "Eidolon's Wrath",
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'Your eidolon gains the eidolon\'s wrath focus spell, which it casts, instead of you. You determine the damage type when you gain the feat: acid, cold, electricity, fire, negative, positive, or sonic. If your eidolon is a celestial, fiend, or monitor with an alignment other than true neutral, you can choose a damage type in its alignment. Increase the number of Focus Points in your focus pool by 1. As normal, your eidolon shares your Focus Points.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains eidolon\'s wrath focus spell (cast by eidolon). Choose damage type: acid, cold, electricity, fire, negative, positive, sonic (or alignment type). Focus pool +1. Eidolon shares focus pool.',
    subChoices: { label: 'Choose damage type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'negative', name: 'Negative' },
      { id: 'positive', name: 'Positive' },
      { id: 'sonic', name: 'Sonic' },
      { id: 'chaotic', name: 'Chaotic', description: 'Alignment damage (if applicable)' },
      { id: 'lawful', name: 'Lawful', description: 'Alignment damage (if applicable)' },
      { id: 'evil', name: 'Evil', description: 'Alignment damage (if applicable)' },
      { id: 'good', name: 'Good', description: 'Alignment damage (if applicable)' },
    ] },
  },
  {
    id: 'summoner-master-summoner',
    name: 'Master Summoner',
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'During daily preparations, you can designate one of your spell slots to become two summoning slots of the same spell rank, from which you can cast only summoning or incarnate spells.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Daily prep: sacrifice 1 spell slot → 2 summoning slots (same level). Only for summoning or incarnate spells. Leads to: Legendary Summoner.',
    subChoices: { label: 'Choose spell slot to sacrifice', options: [
      { id: 'highest-rank', name: 'Highest-rank spell slot', description: 'Sacrifice one of your top-rank slots' },
      { id: 'lower-rank', name: 'Lower-rank spell slot', description: 'Sacrifice one of your second-highest-rank slots' },
    ] },
  },
  {
    id: 'summoner-ostentatious-arrival',
    name: 'Ostentatious Arrival',
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'If the next action you take is to Manifest your Eidolon as a three-action activity, or to Cast a three-action summoning Spell, the creature appears in an explosion. All creatures except you in a 10-foot emanation around the creature take 1d4 fire damage per spell rank for a summoning spell, or 1d4 damage per 2 levels for Manifesting your Eidolon. If the creature has the acid, cold, electricity, fire, sonic, or water trait, the damage is that type instead (or cold damage for the water trait). If the creature has more than one of these traits, you choose which damage type to deal.',
    implemented: 'full',
    traits: ['Concentrate', 'Manipulate', 'Metamagic', 'Summoner'],
    actionCost: 'free',
    mechanics: 'Free action before 3-action Manifest Eidolon or 3-action summoning spell. 10-ft emanation around creature. Damage: 1d4/spell rank (summoning) or 1d4/2 levels (manifest). Fire default; changes to acid/cold/electricity/fire/sonic if creature has that trait.',
  },
  {
    id: 'summoner-phase-out',
    name: 'Phase Out',
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'Your eidolon phases out of reality slightly, gaining resistance to all damage (except force and negative) equal to half your level. It\'s not incorporeal, but it can\'t use Strikes or actions that require a fully physical form, such as Grapple, Shove, or Trip. Your eidolon can return to its normal form with a single action, which has the concentrate trait.',
    implemented: 'full',
    traits: ['Concentrate', 'Evolution', 'Summoner', 'Transmutation'],
    actionCost: 3,
    prerequisites: ['Your eidolon is a phantom'],
    mechanics: 'Eidolon gains resistance to all damage (except force and negative) = half level. Can\'t Strike or use physical actions (Grapple, Shove, Trip). 1-action (concentrate) to return to normal.',
  },
  {
    id: 'summoner-tandem-strike',
    name: 'Tandem Strike',
    source: 'Summoner',
    category: 'class',
    level: 6,
    description:
      'You and your eidolon each attack, seamlessly targeting the same foe without interfering with each other\'s movements. Your eidolon makes a melee Strike, and then you make a melee Strike against the same creature. Both attacks count toward your multiple attack penalty, but the penalty doesn\'t increase until after both attacks have been made.',
    implemented: 'full',
    traits: ['Summoner', 'Tandem'],
    actionCost: 2,
    mechanics: 'Requirement: creature in both your and eidolon\'s reach. Eidolon melee Strike + you melee Strike vs same target. Both count toward MAP, but MAP doesn\'t increase until after both Strikes.',
  },

  // —— Level 8 ——————————————————————————————————————————————
  {
    id: 'summoner-boost-summons',
    name: 'Boost Summons',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Augmenting your eidolon extends to creatures you summon. When you cast boost eidolon, in addition to your eidolon, it also targets your summoned creatures within 60 feet.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Boost eidolon also affects summoned creatures within 60 ft.',
  },
  {
    id: 'summoner-constricting-hold',
    name: 'Constricting Hold',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Your eidolon constricts the creature, dealing bludgeoning damage equal to your eidolon\'s level plus its Strength modifier, with a basic Fortitude save against your spell DC.',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Summoner'],
    actionCost: 1,
    mechanics: 'Eidolon action. Requirement: eidolon has a creature grabbed or restrained. Damage: eidolon level + STR mod (bludgeoning). Basic Fortitude save vs spell DC.',
  },
  {
    id: 'summoner-energy-resistance',
    name: 'Energy Resistance',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Your eidolon has stronger resistance. Its resistance from Energy Heart and Dual Energy Heart increase to your level.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Energy Heart'],
    mechanics: 'Energy Heart and Dual Energy Heart resistances increase from half level to full level.',
  },
  {
    id: 'summoner-hulking-size',
    name: 'Hulking Size',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Your eidolon grows substantially. Your eidolon becomes Large, instead of its previous size, and its reach increases to 10 feet. This doesn\'t change any of its other statistics.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon becomes Large, reach 10 ft. No other stat changes. Leads to: Towering Size.',
  },
  {
    id: 'summoner-magical-adept',
    name: 'Magical Adept',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Your eidolon gains more magic. Choose one 2nd-level spell and one 1st-level spell of your eidolon\'s tradition. Your eidolon can cast them each once per day as innate spells. At every even level after you take this feat, your eidolon can swap one of these innate spells for a new innate spell that\'s 2 or more levels lower than your highest-level spell slot.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Magical Understudy'],
    mechanics: 'Eidolon gains: 1 innate 2nd-level spell + 1 innate 1st-level spell (tradition-matching). 1/day each. Swap 1 at each even level (must be ≥2 levels below highest slot). Leads to: Share Eidolon Magic, Magical Master.',
  },
  {
    id: 'summoner-miniaturize',
    name: 'Miniaturize',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Your eidolon can shrink even further. When using Shrink Down, your eidolon can reduce its size to Tiny. When Tiny, its reach is 0 feet.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Shrink Down'],
    mechanics: 'Shrink Down can now shrink eidolon to Tiny (reach 0 ft).',
  },
  {
    id: 'summoner-protective-pose',
    name: 'Protective Pose',
    source: 'Summoner',
    category: 'class',
    level: 8,
    description:
      'Many physical poses can fortify one\'s health, but some poses need more than one body to accomplish. As you and your eidolon pose in tandem, you each channel qi into a protective barrier in a 30-foot emanation until the start of your next turn. Creatures within range of either you or your eidolon gain resistance to your choice of acid, cold, electricity, fire, or sonic damage equal to half your level. In addition, any Medicine check targeting a creature with this resistance gets a +1 status bonus (or a +2 status bonus if you\'re a master in Medicine).',
    implemented: 'full',
    traits: ['Manipulate', 'Summoner', 'Uncommon'],
    actionCost: 2,
    prerequisites: ['Trained in Medicine'],
    mechanics: 'Requirement: you and eidolon within 30 ft of each other. 30-ft emanation from both. Choose acid/cold/electricity/fire/sonic. Resistance = half level until start of next turn. Medicine checks on affected creatures: +1 status (+2 if master Medicine). Access: Tian Xia origin.',
    subChoices: { label: 'Choose damage type to resist', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
      { id: 'sonic', name: 'Sonic' },
    ] },
  },
  // —— Level 10 —————————————————————————————————————————————
  {
    id: 'summoner-burrowing-form',
    name: 'Burrowing Form',
    source: 'Summoner',
    category: 'class',
    level: 10,
    description:
      'Your eidolon can burrow through loose dirt. Your eidolon gains a burrow Speed of 15 feet.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains burrow Speed 15 ft.',
  },
  {
    id: 'summoner-merciless-rend',
    name: 'Merciless Rend',
    source: 'Summoner',
    category: 'class',
    level: 10,
    description:
      'Your eidolon rends its foes. It automatically deals the damage from its secondary attack to the enemy.',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Summoner'],
    actionCost: 1,
    mechanics: 'Eidolon action. Requirement: eidolon hit the same enemy with two consecutive Strikes with its secondary attack this turn and dealt slashing damage with both. Auto-deals secondary attack damage.',
  },
  {
    id: 'summoner-protective-bond',
    name: 'Protective Bond',
    source: 'Summoner',
    category: 'class',
    level: 10,
    description:
      'The power of your bond can protect you and your eidolon from harm. If you and your eidolon would take different amounts of damage from the area effect, you take the lower amount of damage instead of the greater amount of damage.',
    implemented: 'full',
    traits: ['Abjuration', 'Summoner'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You and eidolon are in a damaging area effect. Take the lower damage amount instead of the greater. Special: gains the trait of eidolon\'s tradition.',
  },
  {
    id: 'summoner-pushing-attack',
    name: 'Pushing Attack',
    source: 'Summoner',
    category: 'class',
    level: 10,
    description:
      'Your eidolon has an attack that pushes away enemies. Choose one of the eidolon\'s unarmed attacks with the shove trait. It gains the Push action for that attack.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Choose one eidolon unarmed attack with shove trait. It gains the Push action (auto-Shove on hit).',
    subChoices: { label: 'Choose eidolon attack', options: [
      { id: 'primary', name: 'Primary Attack', description: 'Apply Push to your eidolon\'s primary unarmed attack' },
      { id: 'secondary', name: 'Secondary Attack', description: 'Apply Push to your eidolon\'s secondary unarmed attack' },
    ] },
  },
  {
    id: 'summoner-transpose',
    name: 'Transpose',
    source: 'Summoner',
    category: 'class',
    level: 10,
    description:
      'You switch places with your eidolon. You each teleport to the other\'s position.',
    implemented: 'full',
    traits: ['Concentrate', 'Conjuration', 'Manipulate', 'Summoner', 'Teleportation'],
    actionCost: 1,
    mechanics: 'Swap positions with eidolon via teleportation. Special: gains the trait of eidolon\'s tradition.',
  },
  {
    id: 'summoner-weighty-impact',
    name: 'Weighty Impact',
    source: 'Summoner',
    category: 'class',
    level: 10,
    description:
      'Your eidolon knocks enemies down. Choose one of the eidolon\'s unarmed attacks with the trip trait. It gains the Knockdown action for that attack.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Choose one eidolon unarmed attack with trip trait. It gains the Knockdown action (auto-Trip on hit).',
    subChoices: { label: 'Choose eidolon attack', options: [
      { id: 'primary', name: 'Primary Attack', description: 'Apply Knockdown to your eidolon\'s primary unarmed attack' },
      { id: 'secondary', name: 'Secondary Attack', description: 'Apply Knockdown to your eidolon\'s secondary unarmed attack' },
    ] },
  },

  // —— Level 12 —————————————————————————————————————————————
  {
    id: 'summoner-flexible-transmogrification',
    name: 'Flexible Transmogrification',
    source: 'Summoner',
    category: 'class',
    level: 12,
    description:
      'You\'ve learned how to transmogrify your eidolon to suit the circumstances of the day. Each day, choose one evolution feat of 6th level or lower during your daily preparations. Your eidolon gains that feat until your next daily preparations.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Daily prep: choose one evolution feat ≤6th level. Eidolon gains it until next daily prep.',
    subChoices: { label: 'Choose evolution feat', options: [
      { id: 'summoner-advanced-weaponry', name: 'Advanced Weaponry (1st)', description: 'Eidolon gains a weapon trait' },
      { id: 'summoner-energy-heart', name: 'Energy Heart (1st)', description: 'Eidolon gains energy damage type' },
      { id: 'summoner-expanded-senses', name: 'Expanded Senses (1st)', description: 'Eidolon gains darkvision or scent' },
      { id: 'summoner-glider-form', name: 'Glider Form (1st)', description: 'Eidolon gains gliding wings' },
      { id: 'summoner-alacritous-action', name: 'Alacritous Action (2nd)', description: 'Eidolon gains extra simple action' },
      { id: 'summoner-amphibious-form', name: 'Amphibious Form (2nd)', description: 'Eidolon can breathe underwater' },
      { id: 'summoner-magical-understudy', name: 'Magical Understudy (2nd)', description: 'Eidolon casts a cantrip' },
      { id: 'summoner-ranged-combatant', name: 'Ranged Combatant (2nd)', description: 'Eidolon gains ranged unarmed attack' },
      { id: 'summoner-steed-form', name: 'Steed Form (2nd)', description: 'Eidolon becomes a mount' },
      { id: 'summoner-bloodletting-claws', name: 'Bloodletting Claws (4th)', description: 'Eidolon attacks cause persistent bleed' },
      { id: 'summoner-defend-summoner', name: 'Defend Summoner (4th)', description: 'Eidolon shields you from damage' },
      { id: 'summoner-dual-energy-heart', name: 'Dual Energy Heart (4th)', description: 'Eidolon gains second energy type' },
      { id: 'summoner-shrink-down', name: 'Shrink Down (4th)', description: 'Eidolon reduces to Small size' },
      { id: 'summoner-vibration-sense', name: 'Vibration Sense (4th)', description: 'Eidolon gains tremorsense' },
      { id: 'summoner-blood-frenzy', name: 'Blood Frenzy (6th)', description: 'Eidolon gains attack bonus vs bleeding foes' },
      { id: 'summoner-eidolons-opportunity', name: "Eidolon's Opportunity (6th)", description: 'Eidolon gains Attack of Opportunity' },
      { id: 'summoner-eidolons-wrath', name: "Eidolon's Wrath (6th)", description: 'Eidolon AoE energy damage' },
      { id: 'summoner-phase-out', name: 'Phase Out (6th)', description: 'Eidolon becomes incorporeal briefly' },
    ] },
  },
  {
    id: 'summoner-grasping-limbs',
    name: 'Grasping Limbs',
    source: 'Summoner',
    category: 'class',
    level: 12,
    description:
      'Your eidolon grabs enemies. Choose one of the eidolon\'s unarmed attacks with the grapple trait. It gains the Grab action on that unarmed attack.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Choose one eidolon unarmed attack with grapple trait. It gains the Grab action (auto-Grapple on hit).',
    subChoices: { label: 'Choose eidolon attack', options: [
      { id: 'primary', name: 'Primary Attack', description: 'Apply Grab to your eidolon\'s primary unarmed attack' },
      { id: 'secondary', name: 'Secondary Attack', description: 'Apply Grab to your eidolon\'s secondary unarmed attack' },
    ] },
  },
  {
    id: 'summoner-link-focus',
    name: 'Link Focus',
    source: 'Summoner',
    category: 'class',
    level: 12,
    description:
      'Your focus recovers faster. If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    prerequisites: ['Link spells'],
    mechanics: 'When Refocusing: if ≥2 FP spent since last Refocus, recover 2 FP instead of 1. Leads to: Link Wellspring.',
  },
  {
    id: 'summoner-summoners-call',
    name: "Summoner's Call",
    source: 'Summoner',
    category: 'class',
    level: 12,
    description:
      'In a moment of danger, you call your eidolon to your side. Your eidolon teleports to an open space adjacent to you.',
    implemented: 'full',
    traits: ['Concentrate', 'Conjuration', 'Summoner', 'Teleportation'],
    actionCost: 'reaction',
    mechanics: 'Trigger: You or your eidolon take damage from a foe or hazard. Requirement: eidolon is manifested more than 5 ft away. Eidolon teleports adjacent to you. Special: gains the trait of eidolon\'s tradition.',
  },
  {
    id: 'summoner-towering-size',
    name: 'Towering Size',
    source: 'Summoner',
    category: 'class',
    level: 12,
    description:
      'Your eidolon becomes even bigger. It becomes Huge, instead of Large, and the reach on all its attacks increases to 15 feet.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Hulking Size'],
    mechanics: 'Eidolon becomes Huge (was Large from Hulking Size). All attack reach → 15 ft.',
  },

  // —— Level 14 —————————————————————————————————————————————
  {
    id: 'summoner-airborne-form',
    name: 'Airborne Form',
    source: 'Summoner',
    category: 'class',
    level: 14,
    description:
      'Your eidolon can fly. It gains a fly Speed equal to its Speed.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Glider Form'],
    mechanics: 'Eidolon gains fly Speed = its land Speed.',
  },
  {
    id: 'summoner-resilient-shell',
    name: 'Resilient Shell',
    source: 'Summoner',
    category: 'class',
    level: 14,
    description:
      'Your eidolon is resilient against attacks. It gains resistance to physical damage equal to its Constitution modifier.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains resistance to physical damage = CON modifier.',
  },
  {
    id: 'summoner-share-eidolon-magic',
    name: 'Share Eidolon Magic',
    source: 'Summoner',
    category: 'class',
    level: 14,
    description:
      'Your eidolon shares innate spells with you. You can cast the innate spells your eidolon gained from Magical Understudy, Magical Adept, and Magical Master. You and your eidolon share the same daily uses of these innate spells.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    prerequisites: ['Magical Understudy'],
    mechanics: 'Summoner can cast eidolon\'s innate spells from Magical Understudy/Adept/Master. Shared daily uses.',
  },
  {
    id: 'summoner-spell-repelling-form',
    name: 'Spell-Repelling Form',
    source: 'Summoner',
    category: 'class',
    level: 14,
    description:
      'Your eidolon evolves to protect itself from the danger posed by spells. It gains a +1 status bonus to all saving throws against magic.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains +1 status bonus to all saves vs magic.',
  },
  // —— Level 16 —————————————————————————————————————————————
  {
    id: 'summoner-effortless-concentration',
    name: 'Effortless Concentration',
    source: 'Summoner',
    category: 'class',
    level: 16,
    description:
      'You maintain a spell with hardly a thought. You immediately gain the effects of the Sustain a Spell action, allowing you to extend the duration of one of your active class spells.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'free',
    mechanics: 'Trigger: Your turn begins. Free action Sustain a Spell on one active summoner spell. Shared feat (also available to Bard, Druid, Sorcerer, Witch, Wizard).',
  },
  {
    id: 'summoner-ever-vigilant-senses',
    name: 'Ever-Vigilant Senses',
    source: 'Summoner',
    category: 'class',
    level: 16,
    description:
      'Your eidolon has enhanced senses. It gains a +2 circumstance bonus to Perception, and can\'t be flanked except by creatures that are higher level than it. It can see invisible creatures and objects; they appear translucent and are concealed. When your eidolon moves within 30 feet of an illusion that can be disbelieved, the GM rolls a secret check to disbelieve it, even if your eidolon didn\'t spend an action to Interact.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    mechanics: 'Eidolon gains: +2 circumstance bonus to Perception, can\'t be flanked (except by higher-level creatures), sees invisible (concealed), auto-disbelieve illusions within 30 ft (secret GM check).',
  },
  {
    id: 'summoner-trample',
    name: 'Trample',
    source: 'Summoner',
    category: 'class',
    level: 16,
    description:
      'Your eidolon Strides up to double its Speed and can move through the spaces of creatures at least one size smaller, Trampling each creature whose space it enters. It can attempt to Trample the same creature only once in a single Trample. It deals bludgeoning damage equal to the damage of its secondary attack against these creatures, which can attempt a basic Reflex save against your spell DC.',
    implemented: 'full',
    traits: ['Eidolon', 'Evolution', 'Summoner'],
    actionCost: 3,
    mechanics: 'Eidolon Strides up to 2× Speed. Moves through spaces of creatures ≥1 size smaller. Each trampled creature: bludgeoning damage = secondary attack damage, basic Reflex save vs spell DC. Each creature trampled at most once per use.',
  },

  // —— Level 18 —————————————————————————————————————————————
  {
    id: 'summoner-link-wellspring',
    name: 'Link Wellspring',
    source: 'Summoner',
    category: 'class',
    level: 18,
    description:
      'Your bond replenishes your focus. If you have spent at least 3 Focus Points since the last time you Refocused, you recover 3 Focus Points when you Refocus instead of 1.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    prerequisites: ['Link Focus'],
    mechanics: 'When Refocusing: if ≥3 FP spent since last Refocus, recover 3 FP instead of 1.',
  },
  {
    id: 'summoner-magical-master',
    name: 'Magical Master',
    source: 'Summoner',
    category: 'class',
    level: 18,
    description:
      'Your eidolon gains a bevy of lower-level spells. Choose an innate spell of your eidolon\'s tradition of each of the spell ranks from 1 to 7 in which your eidolon doesn\'t currently have an innate spell from Magical Adept. Your eidolon can cast each once per day as innate spells. You can swap these spells at every even level, but your eidolon can never know more than one spell of each spell rank 1 through 7.',
    implemented: 'full',
    traits: ['Evolution', 'Summoner'],
    actionCost: 'passive',
    prerequisites: ['Magical Adept'],
    mechanics: 'Eidolon gains innate spells filling each level 1–7 that doesn\'t already have one from Magical Adept. 1/day each. Swap at even levels. Max 1 spell per level 1–7.',
  },
  {
    id: 'summoner-true-transmogrification',
    name: 'True Transmogrification',
    source: 'Summoner',
    category: 'class',
    level: 18,
    description:
      'You transmogrify your eidolon each day. During your daily preparations, you can swap out any number of your evolution feats, each for a different evolution feat of an appropriate level for which you meet the prerequisites. These swaps last until your next daily preparations.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Daily prep: swap any number of evolution feats for other evolution feats (level-appropriate, meet prerequisites). Lasts until next daily prep.',
    subChoices: { label: 'Choose primary evolution swap', options: [
      { id: 'summoner-advanced-weaponry', name: 'Advanced Weaponry (1st)' },
      { id: 'summoner-energy-heart', name: 'Energy Heart (1st)' },
      { id: 'summoner-expanded-senses', name: 'Expanded Senses (1st)' },
      { id: 'summoner-glider-form', name: 'Glider Form (1st)' },
      { id: 'summoner-alacritous-action', name: 'Alacritous Action (2nd)' },
      { id: 'summoner-amphibious-form', name: 'Amphibious Form (2nd)' },
      { id: 'summoner-magical-understudy', name: 'Magical Understudy (2nd)' },
      { id: 'summoner-ranged-combatant', name: 'Ranged Combatant (2nd)' },
      { id: 'summoner-steed-form', name: 'Steed Form (2nd)' },
      { id: 'summoner-bloodletting-claws', name: 'Bloodletting Claws (4th)' },
      { id: 'summoner-defend-summoner', name: 'Defend Summoner (4th)' },
      { id: 'summoner-dual-energy-heart', name: 'Dual Energy Heart (4th)' },
      { id: 'summoner-shrink-down', name: 'Shrink Down (4th)' },
      { id: 'summoner-vibration-sense', name: 'Vibration Sense (4th)' },
      { id: 'summoner-blood-frenzy', name: 'Blood Frenzy (6th)' },
      { id: 'summoner-eidolons-opportunity', name: "Eidolon's Opportunity (6th)" },
      { id: 'summoner-eidolons-wrath', name: "Eidolon's Wrath (6th)" },
      { id: 'summoner-phase-out', name: 'Phase Out (6th)' },
      { id: 'summoner-constricting-hold', name: 'Constricting Hold (8th)' },
      { id: 'summoner-energy-resistance', name: 'Energy Resistance (8th)' },
      { id: 'summoner-hulking-size', name: 'Hulking Size (8th)' },
      { id: 'summoner-magical-adept', name: 'Magical Adept (8th)' },
      { id: 'summoner-miniaturize', name: 'Miniaturize (8th)' },
      { id: 'summoner-burrowing-form', name: 'Burrowing Form (10th)' },
      { id: 'summoner-merciless-rend', name: 'Merciless Rend (10th)' },
      { id: 'summoner-pushing-attack', name: 'Pushing Attack (10th)' },
      { id: 'summoner-weighty-impact', name: 'Weighty Impact (10th)' },
      { id: 'summoner-grasping-limbs', name: 'Grasping Limbs (12th)' },
      { id: 'summoner-towering-size', name: 'Towering Size (12th)' },
      { id: 'summoner-airborne-form', name: 'Airborne Form (14th)' },
      { id: 'summoner-resilient-shell', name: 'Resilient Shell (14th)' },
      { id: 'summoner-spell-repelling-form', name: 'Spell-Repelling Form (14th)' },
      { id: 'summoner-ever-vigilant-senses', name: 'Ever-Vigilant Senses (16th)' },
      { id: 'summoner-trample', name: 'Trample (16th)' },
      { id: 'summoner-magical-master', name: 'Magical Master (18th)' },
    ] },
  },

  // —— Level 20 —————————————————————————————————————————————
  {
    id: 'summoner-eternal-boost',
    name: 'Eternal Boost',
    source: 'Summoner',
    category: 'class',
    level: 20,
    description:
      'Your link with your eidolon is so intense that you continuously reinforce its abilities. You are permanently quickened; you can use your extra action only to cast boost eidolon or reinforce eidolon. While in exploration mode, you can declare that you are also continually casting boost eidolon or reinforce eidolon even while using a different exploration activity. If you do, even before your first turn in a combat encounter, that cantrip is active as if you had cast it on your previous turn.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    mechanics: 'Permanently quickened (extra action: boost eidolon or reinforce eidolon only). In exploration mode, can continually cast boost/reinforce eidolon alongside another exploration activity; starts combat already active.',
  },
  {
    id: 'summoner-legendary-summoner',
    name: 'Legendary Summoner',
    source: 'Summoner',
    category: 'class',
    level: 20,
    description:
      'Your ability to summon extends past your other spellcasting. When you sacrifice a 9th-level spell slot to gain two summoning slots using Master Summoner, you can use those slots to cast summoning spells heightened to 10th level. You can\'t use these spell slots for any purpose other than casting the summoning spells, and you don\'t count as having 10th-level spell slots for other abilities or rules.',
    implemented: 'full',
    traits: ['Summoner'],
    actionCost: 'passive',
    prerequisites: ['Master Summoner'],
    mechanics: 'Master Summoner with 9th-level slot → 2 summoning slots that can cast at 10th level. Only for summoning spells. Does not count as having 10th-level slots.',
  },
  {
    id: 'summoner-twin-eidolon',
    name: 'Twin Eidolon',
    source: 'Summoner',
    category: 'class',
    level: 20,
    description:
      'You can transform to match your eidolon. When you Manifest your Eidolon, you can call upon its powers to transform yourself into a duplicate until it unmanifests. You can\'t use this if you Manifest your Eidolon in an unusual way, such as Meld into Eidolon. While using Twin Eidolon, you use your eidolon\'s statistics other than your mental ability modifiers, including its evolutions. You can\'t cast spells (except spells your eidolon could cast), Activate or otherwise benefit from magic items that normally benefit you and not your eidolon, or use other actions it can\'t perform. Any of its spells you cast with limited uses count against your eidolon\'s uses. You can Manifest your Eidolon again to end this effect.',
    implemented: 'full',
    traits: ['Polymorph', 'Summoner', 'Transmutation'],
    actionCost: 'passive',
    mechanics: 'When Manifesting Eidolon (normal way only): transform into eidolon duplicate. Use eidolon stats (keep mental ability modifiers). Can\'t cast spells (except eidolon\'s) or use non-eidolon items. Shared spell uses. Manifest Eidolon again to end. Special: gains the trait of eidolon\'s tradition.',
  },
];

export const SUMMONER_CLASS_FEATS: FeatEntry[] = RAW_SUMMONER_CLASS_FEATS.map(f => ({
  ...f,
  traits: f.traits ?? ['Summoner'],
}));
