/**
 * Weapon definitions for PF2e Rebirth
 *
 * AUTO-GENERATED by scripts/foundry-import/import-weapons.js
 * Source: scripts/foundry-import/source/weapons.source.json
 * Do not edit this file manually; rerun npm run import:foundry.
 */
import { DamageType } from './spells';
export interface Weapon {
    id: string;
    name: string;
    damageFormula: string;
    damageType: DamageType;
    type: 'melee' | 'ranged';
    range?: number;
    reach?: number;
    hands: number;
    proficiencyCategory: 'unarmed' | 'simple' | 'martial' | 'advanced';
    rarity: 'common' | 'uncommon' | 'rare' | 'unique';
    traits: string[];
    price: number;
    icon: string;
    description: string;
}
export declare const WEAPON_CATALOG: Record<string, Weapon>;
export declare const getWeapon: (weaponId: string) => Weapon | undefined;
