"use strict";
/**
 * Weapon definitions for PF2e Rebirth
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.getWeapon = exports.WEAPON_CATALOG = void 0;
// Weapon catalog
exports.WEAPON_CATALOG = {
    'short-sword': {
        id: 'short-sword',
        name: 'Short Sword',
        damageFormula: '1d6',
        damageType: 'piercing',
        type: 'melee',
        range: 1,
        hands: 1,
        proficiencyCategory: 'martial',
        rarity: 'common',
        traits: ['agile', 'finesse'],
        icon: '⚔️',
        description: 'A versatile one-handed sword',
    },
    'greatsword': {
        id: 'greatsword',
        name: 'Greatsword',
        damageFormula: '1d12',
        damageType: 'slashing',
        type: 'melee',
        range: 1,
        hands: 2,
        proficiencyCategory: 'martial',
        rarity: 'common',
        traits: [],
        icon: '🗡️',
        description: 'A large two-handed sword dealing heavy damage',
    },
    'warhammer': {
        id: 'warhammer',
        name: 'Warhammer',
        damageFormula: '1d8',
        damageType: 'bludgeoning',
        type: 'melee',
        range: 1,
        hands: 1,
        proficiencyCategory: 'martial',
        rarity: 'common',
        traits: ['shove'],
        icon: '🔨',
        description: 'A one-handed hammer, versatile for bludgeoning damage',
    },
    'shortbow': {
        id: 'shortbow',
        name: 'Shortbow',
        damageFormula: '1d6',
        damageType: 'piercing',
        type: 'ranged',
        range: 12,
        hands: 2,
        proficiencyCategory: 'martial',
        rarity: 'common',
        traits: ['deadly d10'],
        icon: '🏹',
        description: 'A ranged bow effective at mid-range combat',
    },
    'longbow': {
        id: 'longbow',
        name: 'Longbow',
        damageFormula: '1d8',
        damageType: 'piercing',
        type: 'ranged',
        range: 20,
        hands: 2,
        proficiencyCategory: 'martial',
        rarity: 'common',
        traits: ['deadly d10', 'volley 30'],
        icon: '🏹',
        description: 'A powerful ranged bow with exceptional range',
    },
    'club': {
        id: 'club',
        name: 'Club',
        damageFormula: '1d6',
        damageType: 'bludgeoning',
        type: 'melee',
        range: 1,
        hands: 1,
        proficiencyCategory: 'simple',
        rarity: 'common',
        traits: ['thrown 10'],
        icon: '🪵',
        description: 'A simple wooden club',
    },
    'dagger': {
        id: 'dagger',
        name: 'Dagger',
        damageFormula: '1d4',
        damageType: 'piercing',
        type: 'melee',
        range: 1,
        hands: 1,
        proficiencyCategory: 'simple',
        rarity: 'common',
        traits: ['agile', 'finesse', 'thrown 10'],
        icon: '🗡️',
        description: 'A small piercing weapon, useful for thrown attacks',
    },
};
const getWeapon = (weaponId) => {
    return exports.WEAPON_CATALOG[weaponId];
};
exports.getWeapon = getWeapon;
