/**
 * Witch Class Features & Feats — PF2e Remaster (Player Core)
 * Source: https://2e.aonprd.com/Classes.aspx?ID=38
 *
 * Key Attribute: INT | HP: 6 + CON
 * Perception: Trained → Expert (L11)
 * Fort: Trained → Expert (L5, Magical Fortitude)
 * Reflex: Trained → Expert (L9)
 * Will: Expert → Master (L17, Will of the Pupil: success → crit)
 * Weapons: Trained simple + unarmed → Expert (L11)
 * Armor: Untrained all; Unarmored Trained → Expert (L13, Defensive Robes)
 * Spellcasting: Patron tradition, prepared, 5 cantrips, standard full-caster slots
 * Patron: Determines tradition, hex cantrip, granted spell, familiar ability
 * Familiar: Witch familiar with 2 extra abilities (+1 at L6/L12/L18)
 * Hexes: Focus spells (1 FP pool), hex cantrips (no FP), 1 hex per turn limit
 * Patrons (16): Baba Yaga, Choir Politic, Cobyslarni, Devourer of Decay,
 *   Faith's Flamekeeper, Mosquito Witch, Paradox of Opposites, Ripple in the Deep,
 *   Silence in Snow, Spinner of Threads, Starless Shadow, The Inscribed One,
 *   The Resentment, The Unseen Broker, Whisper of Wings, Wilding Steward
 */

import type { FeatEntry } from './featTypes';
import { WEAPON_SPECIALIZATION, createClassFeature } from './sharedFeats';

// ── Witch Class Features ─────────────────────────────────

const RAW_WITCH_CLASS_FEATURES: FeatEntry[] = [
  {
    id: 'witch-patron',
    name: 'Patron',
    source: 'Witch',
    category: 'class_feature',
    level: 1,
    description:
      'You weren\'t born with the power to cast spells, nor have you spent years dedicated to worship, study, or uncovering mystical secrets. Your magic instead has been gifted to you by a potent being, one who knows that by empowering you so, you\'ll further the being\'s agenda in the world. This entity is typically mysterious and distant, revealing little of their identity and motivations. Rather than interacting with you directly, your patron works through a familiar—a mystical creature that teaches you, serves as the conduit for your patron\'s magic, and maybe even keeps an eye on you. At 1st level, choose your patron, which determines your spellcasting tradition and grants you the skill for that tradition of magic, your first witch\'s lesson, and a unique familiar ability.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics:
      'Choose 1 of 16 patrons. Baba Yaga (Rare/Occult, Spirit Object, Chilling Spray), Choir Politic (Divine, Share Vision, Share Lore), Cobyslarni (Rare/Occult, Information Overload, Déjà Vu), Devourer of Decay (Primal, Scrounger\'s Glee, Enfeeble), Faith\'s Flamekeeper (Divine, Stoke the Heart, Command), Mosquito Witch (Rare/Primal, Buzzing Bites, Pest Form), Paradox of Opposites (Divine, Trade Death for Life, Sleep), Ripple in the Deep (Primal, Sting of the Sea, Dizzying Colors/Grease), Silence in Snow (Primal, Clinging Ice, Gust of Wind), Spinner of Threads (Occult, Nudge Fate, Sure Strike), Starless Shadow (Occult, Shroud of Night, Fear), The Inscribed One (Arcane, Discern Secrets, Runic Weapon), The Resentment (Occult, Evil Eye, Enfeeble), The Unseen Broker (Occult, Pact Broker, Command), Whisper of Wings (Primal, Murmuration, Gentle Landing), Wilding Steward (Primal, Wilding Word, Summon Animal/Plant/Fungus). Each patron grants: tradition, patron skill, hex cantrip, granted spell, and unique familiar ability.',
    subChoices: { label: 'Choose a patron', options: [
      { id: 'baba-yaga', name: 'Baba Yaga', description: 'Rare; Occult tradition; Spirit Object hex' },
      { id: 'choir-politic', name: 'Choir Politic', description: 'Divine tradition; Share Vision hex' },
      { id: 'cobyslarni', name: 'Cobyslarni', description: 'Rare; Occult tradition; Information Overload hex' },
      { id: 'devourer-of-decay', name: 'Devourer of Decay', description: 'Primal tradition; Scrounger\'s Glee hex' },
      { id: 'faiths-flamekeeper', name: "Faith's Flamekeeper", description: 'Divine tradition; Stoke the Heart hex' },
      { id: 'mosquito-witch', name: 'Mosquito Witch', description: 'Rare; Primal tradition; Buzzing Bites hex' },
      { id: 'paradox-of-opposites', name: 'Paradox of Opposites', description: 'Divine tradition; Trade Death for Life hex' },
      { id: 'ripple-in-the-deep', name: 'Ripple in the Deep', description: 'Primal tradition; Sting of the Sea hex' },
      { id: 'silence-in-snow', name: 'Silence in Snow', description: 'Primal tradition; Clinging Ice hex' },
      { id: 'spinner-of-threads', name: 'Spinner of Threads', description: 'Occult tradition; Nudge Fate hex' },
      { id: 'starless-shadow', name: 'Starless Shadow', description: 'Occult tradition; Shroud of Night hex' },
      { id: 'the-inscribed-one', name: 'The Inscribed One', description: 'Arcane tradition; Discern Secrets hex' },
      { id: 'the-resentment', name: 'The Resentment', description: 'Occult tradition; Evil Eye hex' },
      { id: 'the-unseen-broker', name: 'The Unseen Broker', description: 'Occult tradition; Pact Broker hex' },
      { id: 'whisper-of-wings', name: 'Whisper of Wings', description: 'Primal tradition; Murmuration hex' },
      { id: 'wilding-steward', name: 'Wilding Steward', description: 'Primal tradition; Wilding Word hex' },
    ] },
  },
  {
    id: 'witch-spellcasting',
    name: 'Witch Spellcasting',
    source: 'Witch',
    category: 'class_feature',
    level: 1,
    description:
      'Using your familiar as a conduit, your patron provides you the power to cast spells. You can cast spells of your patron\'s tradition using the Cast a Spell activity. At 1st level, you can prepare up to two 1st-rank spells and five cantrips each morning from the spells your familiar knows. Prepared spells remain available to you until you cast them or until you prepare your spells again. As you increase in level, the number of spells you can prepare each day increases, as does the highest rank of spell you can cast. Some of your spells require you to attempt a spell attack or have your enemies roll against your spell DC. Since your key attribute is Intelligence, your spell attack modifier and spell DC use your Intelligence modifier. Cantrips are automatically heightened to half your level rounded up.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Prepared caster (from familiar). Tradition determined by patron. Key attribute: Intelligence. 5 cantrips, slots: 2 at L1 → 3 (standard full-caster progression).',
  },
  {
    id: 'witch-familiar',
    name: 'Familiar',
    source: 'Witch',
    category: 'class_feature',
    level: 1,
    description:
      'Your patron has sent you a familiar, a mystical creature that teaches you magic and facilitates your spells. This familiar follows the familiar rules, though as it\'s a direct conduit between you and your patron, it\'s more powerful than typical familiars. Your familiar gains two additional familiar abilities: one is a unique ability based on your patron (always selected), and the other is an additional familiar ability that can be selected daily. Your familiar gains another extra ability at 6th, 12th, and 18th levels. Your familiar starts knowing 10 cantrips, five 1st-rank spells, and one additional spell from your patron\'s initial lesson. Each time you gain a level, your patron teaches your familiar two new spells. Your familiar can learn new spells by consuming a written version over 1 hour. If your familiar dies, your patron replaces it during your next daily preparations; the new familiar knows the same spells.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: '+2 bonus abilities at L1 (1 patron-locked, 1 free), +1 at L6/L12/L18. Starts knowing 10 cantrips + 5 1st-rank spells + 1 patron lesson spell. +2 new spells per witch level. Can learn new spells by consuming written version (1 hour) or from another witch familiar. Patron replaces slain familiar at next daily preparations; inherits all spells.',
  },
  {
    id: 'witch-hex-spells',
    name: 'Hex Spells',
    source: 'Witch',
    category: 'class_feature',
    level: 1,
    description:
      'Hex spells are a type of focus spell shaped by your patron and sent through your familiar. It costs 1 Focus Point to cast a focus spell, and you start with a focus pool of 1 Focus Point. You refill your focus pool during daily preparations and can regain 1 Focus Point by spending 10 minutes using the Refocus activity to commune with your familiar. Focus spells are automatically heightened to half your level rounded up. You can use only one hex each turn; attempts to use a second hex fail and the actions are lost. You learn your choice of the patron\'s puppet hex or phase familiar hex.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Focus pool: 1 FP (max 3). Refocus: commune with familiar 10 minutes. Limit: 1 hex per turn (includes both hex cantrips and hex focus spells). Initial choice: Patron\'s Puppet or Phase Familiar.',
  },
  {
    id: 'witch-hex-cantrips',
    name: 'Hex Cantrips',
    source: 'Witch',
    category: 'class_feature',
    level: 1,
    description:
      'Hex cantrips are special hexes that don\'t cost Focus Points, so you can cast them as often as you like, though you can still use only one hex each turn. Hex cantrips are in addition to the cantrips you choose with witch spellcasting and aren\'t counted toward your prepared cantrips. You gain a hex cantrip determined by your choice of patron.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'No Focus Point cost. Still subject to 1 hex per turn limit. Hex cantrip determined by patron choice.',
  },
  {
    id: 'witch-magical-fortitude',
    name: 'Magical Fortitude',
    source: 'Witch',
    category: 'class_feature',
    level: 5,
    description: "Your patron's power boosts your physical resiliency. Your proficiency rank for Fortitude saves increases to expert.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Fortitude save proficiency → expert.',
  },
  {
    id: 'witch-familiar-ability-6',
    name: 'Familiar Ability (6th)',
    source: 'Witch',
    category: 'class_feature',
    level: 6,
    description: 'Your familiar gains an additional familiar ability.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: '+1 additional familiar ability.',
  },
  {
    id: 'witch-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Witch',
    category: 'class_feature',
    level: 7,
    description: "You've learned to better control the power your patron has granted you. Your proficiency ranks for spell attack modifier and spell DC increase to expert.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Spell attack modifier and spell DC proficiency → expert.',
  },
  {
    id: 'witch-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Witch',
    category: 'class_feature',
    level: 9,
    description: 'Your reflexes are lightning fast, helping you avoid danger. Your proficiency rank for Reflex saves increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Reflex save proficiency → expert.',
  },
  {
    id: 'witch-perception-expertise',
    name: 'Perception Expertise',
    source: 'Witch',
    category: 'class_feature',
    level: 11,
    description: 'You remain alert to threats around you. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Perception proficiency → expert.',
  },
  {
    id: 'witch-weapon-expertise',
    name: 'Weapon Expertise',
    source: 'Witch',
    category: 'class_feature',
    level: 11,
    description: "Through sheer experience, you've improved your technique with your weapons. Your proficiency ranks for simple weapons and unarmed attacks increase to expert.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Simple weapons and unarmed attacks proficiency → expert.',
  },
  {
    id: 'witch-familiar-ability-12',
    name: 'Familiar Ability (12th)',
    source: 'Witch',
    category: 'class_feature',
    level: 12,
    description: 'Your familiar gains an additional familiar ability.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: '+1 additional familiar ability.',
  },
  {
    id: 'witch-defensive-robes',
    name: 'Defensive Robes',
    source: 'Witch',
    category: 'class_feature',
    level: 13,
    description: 'The flow of magic through your spellcasting and your defensive training combine to help you get out of the way before an attack. Your proficiency rank in unarmored defense increases to expert.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Unarmored defense proficiency → expert.',
  },
  // Weapon Specialization at L13 handled via CCF below
  {
    id: 'witch-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Witch',
    category: 'class_feature',
    level: 15,
    description: "You've achieved mastery over your patron's magic. Your proficiency ranks for spell attack modifier and spell DC increase to master.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Spell attack modifier and spell DC proficiency → master.',
  },
  {
    id: 'witch-will-of-the-pupil',
    name: 'Will of the Pupil',
    source: 'Witch',
    category: 'class_feature',
    level: 17,
    description: 'Communion with your familiar has steeled your mental fortitude. Your proficiency rank for Will saves increases to master. When you roll a success on a Will save, you get a critical success instead.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Will save proficiency → master. Success on Will saves → critical success.',
  },
  {
    id: 'witch-familiar-ability-18',
    name: 'Familiar Ability (18th)',
    source: 'Witch',
    category: 'class_feature',
    level: 18,
    description: 'Your familiar gains an additional familiar ability.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: '+1 additional familiar ability.',
  },
  {
    id: 'witch-legendary-spellcaster',
    name: 'Legendary Spellcaster',
    source: 'Witch',
    category: 'class_feature',
    level: 19,
    description: "You've perfected your command of the magic your patron provides. Your proficiency ranks for spell attack modifier and spell DC increase to legendary.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Spell attack modifier and spell DC proficiency → legendary.',
  },
  {
    id: 'witch-patrons-gift',
    name: "Patron's Gift",
    source: 'Witch',
    category: 'class_feature',
    level: 19,
    description:
      "Your patron grants you the power to command incredible works of magic. You gain a single 10th-rank spell slot and can prepare a spell in that slot using witch spellcasting. Unlike with other spell slots, you can't use 10th-rank slots with abilities that give you more spell slots or that let you cast spells without expending spell slots. You don't gain more 10th-rank spells as you level up, but you can take the Patron's Truth feat to gain a second slot.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: '1 tenth-rank spell slot. Cannot be enhanced by abilities that grant extra slots or free casting.',
  },
];

export const WITCH_CLASS_FEATURES: FeatEntry[] = [
  ...RAW_WITCH_CLASS_FEATURES.map(f => ({ ...f, traits: f.traits ?? ['Witch'] })),
  createClassFeature(WEAPON_SPECIALIZATION, 'Witch', 13),
];

// ── Witch Class Feats ────────────────────────────────────

const RAW_WITCH_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'witch-cackle',
    name: 'Cackle',
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      "Your patron's power fills you with confidence, letting you sustain a magical working even as a quick burst of laughter leaves your lips. You learn the cackle hex cantrip.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Learn the cackle hex cantrip. Cackle is a free-action hex cantrip that lets you Sustain a Spell that has the hex and sustain traits.',
  },
  {
    id: 'witch-cauldron',
    name: 'Cauldron',
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      "You can brew magic in your cauldron, creating useful magical concoctions. You can use the Craft activity to create oils and potions. You immediately gain the formulas for four common 1st-level oils or potions. At 4th level and every 2 levels beyond that, you gain the formula for a common oil or potion of that level or lower. If you have a familiar, you can have your familiar learn these formulas rather than storing them in a formula book. During your daily preparations, you can create one temporary oil or potion using a formula you know. If you have master proficiency in spell DC, you can create a batch of two temporary oils or potions, and if you have legendary proficiency, a batch of three. Temporary items become inert at your next daily preparations and have no value.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Formulas: 4 common 1st-level oils/potions; +1 formula at L4 and every 2 levels. Daily brew: 1 temporary oil/potion (2 at master spell DC, 3 at legendary). Leads to Double, Double and Witch\'s Bottle.',
  },
  {
    id: 'witch-counterspell',
    name: 'Counterspell',
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      "When a foe Casts a Spell and you can see its manifestations, you can use your magic to disrupt it. You expend a prepared spell to counter the triggering creature's casting of that same spell. You lose your spell slot as if you had cast the triggering spell. You then attempt to counteract the triggering spell.",
    implemented: 'full',
    traits: ['Witch', 'Wizard'],
    actionCost: 'reaction',
    mechanics: 'Trigger: a creature Casts a Spell that you have prepared. This feat gains the trait of your spell tradition. Leads to Clever Counterspell, Reflect Spell.',
  },
  {
    id: 'witch-reach-spell',
    name: 'Reach Spell',
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      'You can extend the range of your spells. If the next action you use is to Cast a Spell that has a range, increase that range by 30 feet. As is standard for increasing spell ranges, if the spell normally has a range of touch, you extend its range to 30 feet.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Concentrate', 'Druid', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  {
    id: 'witch-widen-spell',
    name: 'Widen Spell',
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      'You manipulate the energy of your spell, causing it to spread out and affect a wider area. If the next action you use is to Cast a Spell that has an area of a burst, cone, or line and does not have a duration, increase the area of that spell. Add 5 feet to the radius of a burst that normally has a radius of at least 10 feet (a burst with a smaller radius is not affected). Add 5 feet to the length of a cone or line that is normally 15 feet long or smaller, and add 10 feet to the length of a larger cone or line.',
    implemented: 'full',
    traits: ['Druid', 'Manipulate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  {
    id: 'witch-witchs-armaments',
    name: "Witch's Armaments",
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      "Your patron's power changes your body to ensure you are never defenseless. You gain one of the following unarmed attacks: Eldritch Nails (1d6 slashing, brawling group, agile + unarmed traits), Iron Teeth (1d8 piercing, brawling group), or Living Hair (1d4 bludgeoning, brawling group, agile + disarm + finesse + trip + unarmed traits). You can take this feat more than once, gaining a different unarmed attack each time.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Choose: Eldritch Nails (1d6 slashing, brawling, agile + unarmed), Iron Teeth (1d8 piercing, brawling), or Living Hair (1d4 bludgeoning, brawling, agile + disarm + finesse + trip + unarmed). Can be taken multiple times for different attacks. Leads to Demon\'s Hair, Sympathetic Strike, Wild Witch\'s Armaments.',
    subChoices: { label: 'Choose an armament', options: [
      { id: 'eldritch-nails', name: 'Eldritch Nails', description: '1d6 slashing, brawling, agile + unarmed' },
      { id: 'iron-teeth', name: 'Iron Teeth', description: '1d8 piercing, brawling' },
      { id: 'living-hair', name: 'Living Hair', description: '1d4 bludgeoning, brawling, agile + disarm + finesse + trip + unarmed' },
    ] },
  },
  {
    id: 'witch-wortwitch',
    name: 'Wortwitch',
    source: 'Witch',
    category: 'class',
    level: 1,
    description:
      "You have a particular affinity for leafy plants. Your patron grants you a leshy familiar. If you already had a familiar, this leshy replaces your previous familiar. In addition, you gain the ability to see through leaves, vines, and other foliage. You don't take circumstance penalties to ranged spell attacks or Perception checks caused by foliage, and your targeted attacks don't require a flat check to succeed against a target concealed only by such vegetation.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Legacy (Advanced Player\'s Guide). Gain a leshy familiar. Ignore foliage concealment for spell attacks and Perception.',
  },
  // ── Level 2 ──────────────────────────────────────────
  {
    id: 'witch-basic-lesson',
    name: 'Basic Lesson',
    source: 'Witch',
    category: 'class',
    level: 2,
    description:
      'Your patron grants you a special lesson, revealing a hidden facet of its nature. Choose a basic lesson. You gain its associated hex, and your familiar learns the associated spell.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics:
      'Basic lessons: Dreams (Veil of Dreams hex, Sleep spell), Life (Life Boost hex, Spirit Link), Protection (Blood Ward hex, Mystic Armor), The Elements (Elemental Betrayal hex, choose Breathe Fire/Gust of Wind/Hydraulic Push/Pummeling Rubble), Vengeance (Needle of Vengeance hex, Phantom Pain), Calamity [Uncommon, Legacy] (Stumbling Curse hex, Ill Omen).',
    subChoices: { label: 'Choose a basic lesson', options: [
      { id: 'dreams', name: 'Dreams', description: 'Veil of Dreams hex + Sleep' },
      { id: 'life', name: 'Life', description: 'Life Boost hex + Spirit Link' },
      { id: 'protection', name: 'Protection', description: 'Blood Ward hex + Mystic Armor' },
      { id: 'the-elements', name: 'The Elements', description: 'Elemental Betrayal hex + element spell' },
      { id: 'vengeance', name: 'Vengeance', description: 'Needle of Vengeance hex + Phantom Pain' },
      { id: 'calamity', name: 'Calamity (Uncommon)', description: 'Stumbling Curse hex + Ill Omen' },
    ] },
  },
  {
    id: 'witch-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Witch',
    category: 'class',
    level: 2,
    description: 'A broader study of your magical tradition has expanded the number of cantrips you can cast. You can prepare two additional cantrips each day.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: '+2 prepared cantrips per day.',
  },
  {
    id: 'witch-conceal-spell',
    name: 'Conceal Spell',
    source: 'Witch',
    category: 'class',
    level: 2,
    description:
      "Through sheer mental effort, you can simplify the incantations and gestures needed to spellcast, leaving them barely noticeable. If the next action you use is to Cast a Spell, the spell gains the subtle trait, hiding the shining runes, sparks of magic, and other manifestations that would usually give away your spellcasting. The trait hides only the spell's spellcasting actions and manifestations, not its effects, so an observer might still see a ray streak out from you or see you vanish into thin air.",
    implemented: 'full',
    traits: ['Animist', 'Concentrate', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
  },
  {
    id: 'witch-enhanced-familiar',
    name: 'Enhanced Familiar',
    source: 'Witch',
    category: 'class',
    level: 2,
    description:
      "You infuse your familiar with additional magical energy, increasing its abilities. You can select four familiar or master abilities each day, instead of two. As a witch, add the bonus familiar abilities you gain for being a witch to this amount.",
    implemented: 'full',
    traits: ['Animist', 'Druid', 'Magus', 'Sorcerer', 'Thaumaturge', 'Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['A familiar'],
    mechanics: 'Familiar abilities: 4/day (base, from 2). Witch bonus abilities stack. Leads to Incredible Familiar.',
  },
  {
    id: 'witch-familiars-language',
    name: "Familiar's Language",
    source: 'Witch',
    category: 'class',
    level: 2,
    description:
      "You've learned to speak with your familiar and other creatures like it. You can ask questions of, receive answers from, and use the Diplomacy skill with creatures of the same family of animals as your familiar. For example, if your familiar were a cat, you could gain the effects of speak with animals for any felines. This ability doesn't make them more friendly than normal. If your familiar ever changes to a different creature, you can't use this ability for 1 week while you absorb your new familiar's language.",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ['A familiar'],
    mechanics: 'This feat gains the trait corresponding to the tradition of spells you cast (arcane, divine, occult, or primal).',
  },
  {
    id: 'witch-scatter-swarm',
    name: 'Scatter Swarm',
    source: 'Witch',
    category: 'class',
    level: 2,
    description:
      "Your patron reaches through your familiar to magically disperse a group of smaller threats. A swarm that shares a space with your familiar takes damage equal to the swarm's weakness to area damage. You choose whether this is acid, cold, electricity, or fire damage, and this action gains the trait of the damage type you choose.",
    implemented: 'full',
    traits: ['Magical', 'Witch'],
    actionCost: 1,
    mechanics: 'Frequency: once per round. Source: Howl of the Wild. Damage type: choose acid, cold, electricity, or fire.',    subChoices: { label: 'Choose a damage type', options: [
      { id: 'acid', name: 'Acid' },
      { id: 'cold', name: 'Cold' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'fire', name: 'Fire' },
    ] },  },
  // ── Level 4 ──────────────────────────────────────────
  {
    id: 'witch-improved-familiar',
    name: 'Improved Familiar (Witch)',
    source: 'Witch',
    category: 'class',
    level: 4,
    description:
      'You find it easy to attract a powerful and unusual familiar to your side. The number of abilities required to make your familiar a specific familiar is two lower than normal.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Legacy (Advanced Player\'s Guide). Reduces specific familiar ability cost by 2.',
  },
  {
    id: 'witch-irezoko-tattoo',
    name: 'Irezoko Tattoo',
    source: 'Witch',
    category: 'class',
    level: 4,
    description:
      "Your face bears an intricate magical tattoo known as the irezoko, a badge of your understanding of your chosen field of magic and a recognition of your advancement within Absalom's College of Mysteries. Choose a class that grants you access to a focus pool. Once per day, you may concentrate upon the pattern of your irezoko to recover 1 Focus Point as a three-action activity.",
    implemented: 'full',
    traits: ['Uncommon', 'Bard', 'Cleric', 'Druid', 'Oracle', 'Psychic', 'Sorcerer', 'Summoner', 'Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['Expert in Arcana or Occultism'],
    mechanics: 'Legacy (Absalom, City of Lost Omens). Recover 1 Focus Point 1/day (3-action activity). Requires College of Mysteries access.',
    subChoices: { label: 'Choose a class with focus pool', options: [
      { id: 'bard', name: 'Bard' }, { id: 'champion', name: 'Champion' }, { id: 'cleric', name: 'Cleric' },
      { id: 'druid', name: 'Druid' }, { id: 'magus', name: 'Magus' }, { id: 'monk', name: 'Monk' },
      { id: 'oracle', name: 'Oracle' }, { id: 'psychic', name: 'Psychic' }, { id: 'ranger', name: 'Ranger' },
      { id: 'sorcerer', name: 'Sorcerer' }, { id: 'summoner', name: 'Summoner' }, { id: 'witch', name: 'Witch' },
      { id: 'wizard', name: 'Wizard' },
    ] },
  },
  {
    id: 'witch-portents-of-the-haruspex',
    name: 'Portents of the Haruspex',
    source: 'Witch',
    category: 'class',
    level: 4,
    description:
      "Although the divinations of a haruspex traditionally require organs and lengthy interpretation, you've learned how to glimpse the future in a more simple fashion by reading creatures' wounds. Roll 1d12 to determine the damage type favored by your prediction. The next time before the end of your next turn that you or your allies deal that damage type to an enemy, that enemy has weakness equal to your level against that damage. (d12 table: 1=Acid, 2–3=Bludgeoning, 4=Cold, 5=Electricity, 6=Fire, 7=Mental, 8–9=Piercing, 10=Poison, 11–12=Slashing.)",
    implemented: 'full',
    traits: ['Concentrate', 'Prediction', 'Witch'],
    actionCost: 'reaction',
    mechanics: 'Trigger: creature within 30 ft reduced to 0 HP without body destruction. Source: Howl of the Wild.',
  },
  {
    id: 'witch-rites-of-convocation',
    name: 'Rites of Convocation',
    source: 'Witch',
    category: 'class',
    level: 4,
    description:
      "Your patron grants you the power to summon other creatures to aid you. Choose one summon spell (such as summon animal, summon construct, and so forth) that appears on the spell list of your spellcasting tradition. You can spend 10 minutes in communion with your familiar to replace one spell you've prepared in one of your witch spell slots with the spell you chose, heightened to the same rank. The spell you replaced must be of at least the summon spell's minimum spell rank.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Swap a prepared spell for a chosen summon spell (10-minute communion). The replacement must be same rank or higher.',
  },
  {
    id: 'witch-sympathetic-strike',
    name: 'Sympathetic Strike',
    source: 'Witch',
    category: 'class',
    level: 4,
    description:
      "You collect your patron's magic into one of your witch armaments, causing them to shine with runes, light, or another signifier of your patron. Make an unarmed Strike with one of your witch's armaments. If you hit, you establish a sympathetic link with the target, making it easier for your patron to affect them. Until the beginning of your next turn, the target takes a −1 circumstance penalty to its saves against your hexes, or a −2 penalty if the triggering Strike was a critical hit.",
    implemented: 'full',
    actionCost: 1,
    prerequisites: ["Witch's Armaments"],
    mechanics: 'Frequency: once per round. On hit: −1 circumstance penalty to saves vs your hexes (−2 on critical hit) until start of your next turn.',
  },
  {
    id: 'witch-syu-tak-nwas-skillful-tresses',
    name: "Syu Tak-Nwa's Skillful Tresses",
    source: 'Witch',
    category: 'class',
    level: 4,
    description:
      "You can expertly control your living hair and use it to perform various tasks. You can perform simple Interact actions with your hair such as opening an unlocked door or picking up objects. Your hair can't perform actions that require fingers or significant manual dexterity, including any action that would require a check to accomplish. Your hair can hold items of up to 1 Bulk, but can't Activate or attack with any items it's holding.",
    implemented: 'full',
    traits: ['Uncommon', 'Witch'],
    actionCost: 'passive',
    prerequisites: ["Living Hair (from Witch's Armaments)"],
    mechanics: "Legacy (Pathfinder #166). Hair performs simple Interact actions, holds up to 1 Bulk. No attacks or Activate with held items.",
  },
  // ── Level 6 ──────────────────────────────────────────
  {
    id: 'witch-ceremonial-knife',
    name: 'Ceremonial Knife',
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      "You have prepared a special knife to direct energies when spellcasting. During your daily preparations, you and your familiar can perform a short ritual over a weapon in the knife group—typically a dagger. This causes the knife to function as a magic wand, containing any one 1st-rank spell your familiar knows. You, and only you, can Activate the knife to Cast the Spell within it, as normal for a wand. You can attempt to overcharge the knife, and this can break or destroy it as normal. You can have only one ceremonial knife at a time. At 8th level (and every 2 levels thereafter), the maximum rank of spell your ceremonial knife can hold increases by 1.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Spell rank: 1st (increases by +1 every 2 levels from L8). Functions as a wand (can overcharge). Limit: 1 ceremonial knife at a time.',
  },
  {
    id: 'witch-detonating-spell',
    name: 'Detonating Spell',
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      "Your spell becomes volatile and explosive. If the next action you use is to Cast a Spell that deals damage to a single target and the spell successfully damages that target, the spell explodes, dealing splash damage equal to the level of the spell cast to adjacent creatures. Unlike normally, this splash damage doesn't apply to the target. The splash damage is of the same type the spell deals.",
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Concentrate', 'Metamagic', 'Oracle', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Legacy (Knights of Lastwall). Splash damage = spell rank to adjacent creatures. Requires Knights of Lastwall access.',
  },
  {
    id: 'witch-divine-emissary',
    name: 'Divine Emissary',
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      "Your familiar is a divine emissary, sent to you by your deity or patron and infused with celestial powers. You can select one additional familiar ability each day, which must be one of the following divine emissary abilities: Erudite (Aid on Religion checks), Luminous (30-ft bright light), Medic (cast 1-action heal once/day at spell rank −2), or Radiant (resistance to evil and void damage equal to half your level).",
    implemented: 'full',
    traits: ['Uncommon', 'Sorcerer', 'Witch'],
    actionCost: 'passive',
    prerequisites: ['A familiar', 'You follow a good-aligned deity or patron'],
    mechanics: 'Legacy (Knights of Lastwall). +1 familiar ability (divine emissary only). Requires Knights of Lastwall access.',
    subChoices: { label: 'Choose divine emissary ability', options: [
      { id: 'erudite', name: 'Erudite', description: 'Aid on Religion checks; auto-succeed/crit if master' },
      { id: 'luminous', name: 'Luminous', description: '30-ft bright light, toggleable' },
      { id: 'medic', name: 'Medic', description: 'Cast 1-action heal once/day at spell rank -2' },
      { id: 'radiant', name: 'Radiant', description: 'Resistance to evil and void = half level' },
    ] },
  },
  {
    id: 'witch-greater-lesson',
    name: 'Greater Lesson',
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      'Your patron grants you greater knowledge. Choose a greater or basic lesson. You gain its associated hex, and your familiar learns the associated spell.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics:
      'Greater lessons: Favors (Return the Favor hex, Mind of Menace), Decay (Mycological Malady hex, Insect Form), Memory (Unravel Knowledge hex, Hypercognition), Mischief (Deceiver\'s Cloak hex, Mad Monkeys), Shadow (Malicious Shadow hex, Chilling Darkness), Snow (Personal Blizzard hex, Wall of Wind), The Flock (Sheltering Wings hex, Levitate), The Shark (Blood in the Water hex, Feet to Fins), Vows (Censure Falsehoods hex, Ring of Truth). Also allows any basic lesson.',
    subChoices: { label: 'Choose a greater lesson', options: [
      { id: 'lesson-of-favors', name: 'Lesson of Favors', description: 'Return the Favor hex + Mind of Menace spell' },
      { id: 'lesson-of-decay', name: 'Lesson of Decay', description: 'Mycological Malady hex + Insect Form spell' },
      { id: 'lesson-of-memory', name: 'Lesson of Memory', description: 'Unravel Knowledge hex + Hypercognition spell' },
      { id: 'lesson-of-mischief', name: 'Lesson of Mischief', description: 'Deceiver\'s Cloak hex + Mad Monkeys spell' },
      { id: 'lesson-of-shadow', name: 'Lesson of Shadow', description: 'Malicious Shadow hex + Chilling Darkness spell' },
      { id: 'lesson-of-snow', name: 'Lesson of Snow', description: 'Personal Blizzard hex + Wall of Wind spell' },
      { id: 'lesson-of-the-flock', name: 'Lesson of the Flock', description: 'Sheltering Wings hex + Levitate spell' },
      { id: 'lesson-of-the-shark', name: 'Lesson of the Shark', description: 'Blood in the Water hex + Feet to Fins spell' },
      { id: 'lesson-of-vows', name: 'Lesson of Vows', description: 'Censure Falsehoods hex + Ring of Truth spell' },
    ] },
  },
  {
    id: 'witch-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      "You don't lose spells easily. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn't disrupted.",
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Druid', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
  },
  {
    id: 'witch-syu-tak-nwas-deadly-hair',
    name: "Syu Tak-Nwa's Deadly Hair",
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      'Your hair unarmed attack deals 1d6 bludgeoning damage and gains the grapple trait.',
    implemented: 'full',
    traits: ['Uncommon', 'Witch'],
    actionCost: 'passive',
    prerequisites: ["Living Hair (from Witch's Armaments)"],
    mechanics: "Legacy (Pathfinder #166). Upgrades Living Hair to 1d6 bludgeoning + grapple trait.",
  },
  {
    id: 'witch-wild-witchs-armaments',
    name: "Wild Witch's Armaments",
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      "Your patron's power continues to enhance your natural offensive capabilities. Eldritch Nails: if you hit the same enemy with two consecutive nails Strikes, deal additional slashing damage equal to half your level on the second Strike. Iron Teeth: a creature you critically hit must succeed at a Fortitude save vs your class/spell DC or become sickened 1. Living Hair: you gain a quills ranged unarmed strike (1d4 piercing, range 15 ft, dart group).",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ["Witch's Armaments"],
    mechanics: 'Source: Howl of the Wild. Gain additional effects for each Witch\'s Armaments option you have.',
  },
  {
    id: 'witch-witchs-charge',
    name: "Witch's Charge",
    source: 'Witch',
    category: 'class',
    level: 6,
    description:
      "You forge a magical link with another creature, granting you awareness of that creature's condition and creating a conduit for spellcasting. During your daily preparations, you can designate one willing creature as your charge. You are always aware of your charge's direction from you, its distance from you, and any conditions affecting it. In addition, you can cast spells with a range of touch on your charge from a range of 30 feet. These effects persist until your next daily preparations.",
    implemented: 'full',
    traits: ['Detection', 'Witch'],
    actionCost: 'passive',
    mechanics: 'This feat gains the trait of your spell tradition. Leads to Witch\'s Communion.',
  },
  // ── Level 8 ──────────────────────────────────────────
  {
    id: 'witch-chaotic-spell',
    name: 'Chaotic Spell',
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "This is the secret of chaotic magic—your moves are unpredictable if you yourself have no idea what will happen. If the next action you use is to Cast a Spell that deals acid, cold, electricity, fire, or sonic damage, roll a d6. The spell's damage type changes accordingly (1=Acid+Sickened 1, 2=Cold+Speed penalty, 3=Electricity+off-guard, 4=Fire+persistent fire, 5=Force+no extra, 6=Sonic+Deafened 2 rounds), and each damaged creature takes the additional effect.",
    implemented: 'full',
    traits: ['Uncommon', 'Bard', 'Manipulate', 'Metamagic', 'Oracle', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Legacy (Wake the Dead #3). Randomize damage type + bonus effect on d6.',
  },
  {
    id: 'witch-helts-spelldance',
    name: "Helt's Spelldance",
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "Ostentatiously performing, you move across the battlefield, taking foes aback and creating an opening for your spell. Attempt a Performance check against all observers' Perception DCs. Then Stride once or twice. During this movement, you don't trigger reactions from creatures you beat. After movement, you can Cast a Spell (2-action if 1 Stride, 1-action if 2 Strides). Critical success on the check gives targets −1 circumstance penalty to saves. Observers become temporarily immune for 10 minutes.",
    implemented: 'full',
    traits: ['Uncommon', 'Bard', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 3,
    prerequisites: ['Expert in Performance'],
    mechanics: 'Legacy (Firebrands). Requires Firebrands second mark or higher access.',
  },
  {
    id: 'witch-incredible-familiar',
    name: 'Incredible Familiar',
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      'Your familiar is imbued with even more magic than other familiars. You can select a base of six familiar or master abilities each day, instead of four. As a witch, add the bonus familiar abilities you gain for being a witch to this amount.',
    implemented: 'full',
    traits: ['Animist', 'Thaumaturge', 'Witch'],
    actionCost: 'passive',
    prerequisites: ['Enhanced Familiar'],
    mechanics: 'Familiar abilities: 6/day (base, from 4). Witch bonus abilities stack on top.',
  },
  {
    id: 'witch-murksight',
    name: 'Murksight',
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "Your vision pierces through non-magical fog, mist, rain, and snow. You don't take circumstance penalties to ranged attacks or Perception checks caused by non-magical precipitation, and your targeted attacks don't require a flat check to succeed against a target concealed only by such effects.",
    implemented: 'full',
    actionCost: 'passive',
  },
  {
    id: 'witch-spirit-familiar',
    name: 'Spirit Familiar',
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "Your familiar can subsume its body to become pure spirit. Your familiar gains the Shed Spirit activity (2 actions, spirit trait, once per 10 minutes): your familiar's spirit exits its body and flies at an enemy within 20 feet, dealing 6d6 spirit damage with a basic Will save against your spell DC. If it dealt damage, it then flies to an ally within 30 feet of the enemy, restoring HP equal to half the damage dealt. Your familiar re-forms in its original square. At 9th level and every 2 levels thereafter, the attack deals an additional 2d6 damage.",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ['Divine or occult patron'],
    mechanics: 'Base damage: 6d6 spirit (Will save). Scaling: +2d6 at L9 and every 2 levels. Healing: half damage dealt to ally within 30 ft.',
  },
  {
    id: 'witch-stitched-familiar',
    name: 'Stitched Familiar',
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "Your familiar can shed its material form, becoming a mass of animated magic. Your familiar gains the Stitching Strike activity (2 actions, once per 10 minutes): your familiar unravels into magical fibers that encompass an enemy within 30 feet, dealing 6d6 slashing damage with a basic Reflex save against your spell DC. On a failure, the target is also immobilized for 1 round or until it Escapes against your spell DC. Your familiar re-forms in its original square. At 9th level and every 2 levels thereafter, the attack deals an additional 2d6 damage.",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ['Arcane or primal patron'],
    mechanics: 'Base damage: 6d6 slashing (Reflex save). Scaling: +2d6 at L9 and every 2 levels. On failure: immobilized 1 round (or Escape).',
  },
  {
    id: 'witch-syu-tak-nwas-hexed-locks',
    name: "Syu Tak-Nwa's Hexed Locks",
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "Your hair unarmed attack gains the reach trait. You can deliver hexes through your hair. When you successfully cast a hex focus spell that requires 2 or more actions to cast and that doesn't require a spell attack roll, if your target is within your reach, as part of the spellcasting activity you can make a hair Strike against the foe before applying any effects of the hex. If this Strike misses, the hex has no effect.",
    implemented: 'full',
    traits: ['Uncommon', 'Witch'],
    actionCost: 'passive',
    prerequisites: ["Living Hair (from Witch's Armaments)"],
    mechanics: "Legacy (Pathfinder #166). Hair gains reach. Deliver hexes via hair Strike (miss = hex has no effect).",
  },
  {
    id: 'witch-witchs-bottle',
    name: "Witch's Bottle",
    source: 'Witch',
    category: 'class',
    level: 8,
    description:
      "You spend 10 minutes and 1 Focus Point brewing a special potion containing the power of one of your hexes that targets a creature. A creature that consumes this potion is targeted by the hex. If the hex has a sustained duration and you have cackle, you can cast cackle into the bottle just before you seal it to extend the hex's duration by 1 round. Any potion you create this way loses its power at your next daily preparations. While the potion is in your possession, you can render it inert using a single action (concentrate). You can't regain the Focus Point spent until the potion is consumed or loses its magic.",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ['Cauldron'],
    mechanics: 'Cost: 10 minutes + 1 Focus Point. Duration: until next daily preparations. Optional +1 round if you have Cackle.',
  },
  // ── Level 10 ─────────────────────────────────────────
  {
    id: 'witch-double-double',
    name: 'Double, Double',
    source: 'Witch',
    category: 'class',
    level: 10,
    description:
      'For each temporary oil or potion you brew during your daily preparations, you brew two copies of it. This allows you to brew two temporary oils or potions each day, four if you have master proficiency in spell DC, or six if you have legendary proficiency.',
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ['Cauldron'],
    mechanics: 'Double all Cauldron temporary brews: 2/day (4 at master spell DC, 6 at legendary).',
  },
  {
    id: 'witch-major-lesson',
    name: 'Major Lesson',
    source: 'Witch',
    category: 'class',
    level: 10,
    description:
      'Your patron grants you even greater secrets. Choose a major, greater, or basic lesson. You gain its associated hex, and your familiar learns the associated spell. You can select this feat a second time if you\'re 14th level or higher, and a third time if you\'re 18th level or higher. Choose a different lesson each time.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics:
      'Major lessons: Bargains (Over the Coals hex, Subconscious Suggestion), Death (Curse of Death hex, Raise Dead), Renewal (Restorative Moment hex, Field of Life), The Frozen Queen [Rare, Legacy] (Glacial Heart hex, Wall of Ice). Also allows any greater or basic lesson. Can be taken up to 3 times (L10, L14+, L18+); different lesson each time.',
    subChoices: { label: 'Choose a lesson', options: [
      { id: 'bargains', name: 'Major: Bargains', description: 'Over the Coals hex + Subconscious Suggestion' },
      { id: 'death', name: 'Major: Death', description: 'Curse of Death hex + Raise Dead' },
      { id: 'renewal', name: 'Major: Renewal', description: 'Restorative Moment hex + Field of Life' },
      { id: 'frozen-queen', name: 'Major: Frozen Queen (Rare)', description: 'Glacial Heart hex + Wall of Ice' },
      { id: 'dreams', name: 'Basic: Dreams', description: 'Veil of Dreams hex + Sleep' },
      { id: 'life', name: 'Basic: Life', description: 'Life Boost hex + Spirit Link' },
      { id: 'protection', name: 'Basic: Protection', description: 'Blood Ward hex + Mystic Armor' },
      { id: 'the-elements', name: 'Basic: The Elements', description: 'Elemental Betrayal hex + element spell' },
      { id: 'vengeance', name: 'Basic: Vengeance', description: 'Needle of Vengeance hex + Phantom Pain' },
    ] },
  },
  {
    id: 'witch-quickened-casting',
    name: 'Quickened Casting',
    source: 'Witch',
    category: 'class',
    level: 10,
    description:
      'If your next action is to cast a cantrip or a spell that is at least 2 ranks lower than the highest-rank spell slot you have, reduce the number of actions to cast it by 1 (minimum 1 action).',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Frequency: once per day.',
  },
  {
    id: 'witch-witchs-communion',
    name: "Witch's Communion",
    source: 'Witch',
    category: 'class',
    level: 10,
    description:
      "You can keep watch over multiple charges. Each day during your preparations, you can designate a number of charges equal to your Intelligence modifier instead of just one.",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ["Witch's Charge"],
    mechanics: 'Charges: INT modifier (from 1). All Witch\'s Charge benefits apply to each.',
  },
  // ── Level 12 ─────────────────────────────────────────
  {
    id: 'witch-coven-spell',
    name: 'Coven Spell',
    source: 'Witch',
    category: 'class',
    level: 12,
    description:
      "You link your magic to an ally's spell to empower it at a critical moment. Choose one of the following effects to add to the ally's spell: the spell gains a status bonus to damage equal to the spell's rank, or you apply one of your spellshape feats to the ally's spell (provided the spell is a valid target and you can pay any costs). If you can't pay the spellshape's costs, it has no effect.",
    implemented: 'full',
    traits: ['Spellshape', 'Witch'],
    actionCost: 'reaction',
    mechanics: 'Trigger: an ally within 30 ft Casts a Spell. Options: status bonus to damage equal to spell rank, or apply one of your spellshape feats to the ally\'s spell.',
  },
  {
    id: 'witch-familiars-eyes',
    name: "Familiar's Eyes",
    source: 'Witch',
    category: 'class',
    level: 12,
    description:
      "You can see through the eyes of your familiar to gain its perspective. You project your senses into your familiar; for the duration you lose all sensory information from your own body, but can sense through your familiar's senses using your own Perception. You can Dismiss this effect. While using your familiar's senses, you can speak through the familiar and communicate with it telepathically.",
    implemented: 'full',
    traits: ['Concentrate', 'Divination', 'Witch'],
    actionCost: 1,
    prerequisites: ['A familiar'],
    mechanics: 'Legacy (Advanced Player\'s Guide). This feat gains the trait matching your spell tradition.',
  },
  {
    id: 'witch-hex-focus',
    name: 'Hex Focus',
    source: 'Witch',
    category: 'class',
    level: 12,
    description:
      'Your connection to your patron is so strong that your hexes recover more energy. Whenever you Refocus, you regain all of your Focus Points, not just one.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Refocus restores all Focus Points (up to 3) instead of just 1.',
  },
  {
    id: 'witch-witchs-broom',
    name: "Witch's Broom",
    source: 'Witch',
    category: 'class',
    level: 12,
    description:
      "You anoint a broom, staff, or polearm to serve as a vehicle during your daily preparations. While astride the anointed item, you have a fly Speed of 20 feet. You take a −10-foot penalty to your fly Speed if you're encumbered and carrying more than 20 Bulk, and you fall if you're carrying more than 30 Bulk. You can Craft your anointed item into a flying broomstick as if you had the formula, using your witch spell DC for the Craft check. If the anointed item is already a flying broomstick, you instead gain a +10-foot status bonus to its fly Speed.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Fly Speed: 20 ft. Penalty: −10 ft if encumbered (over 20 Bulk). Falls if carrying more than 30 Bulk. +10-ft status bonus to existing flying broomstick.',
  },
  // ── Level 14 ─────────────────────────────────────────
  {
    id: 'witch-patrons-presence',
    name: "Patron's Presence",
    source: 'Witch',
    category: 'class',
    level: 14,
    description:
      "Your patron exerts its presence through your familiar, unsettling your enemies. Your familiar gains the Patron's Presence activity (2 actions, aura + concentrate, once per hour): your familiar creates a 15-foot emanation. Each enemy within must succeed at a Will save against your spell DC or become stupefied 2 (stupefied 3 on a critical failure). The effect lasts until the end of the enemy's next turn. Your familiar can Sustain the aura for up to 1 minute.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Frequency: once per hour. Area: 15-ft emanation. Save: Will vs spell DC. Effect: stupefied 2 (3 on crit fail). Sustain: up to 1 minute.',
  },
  {
    id: 'witch-reflect-spell',
    name: 'Reflect Spell',
    source: 'Witch',
    category: 'class',
    level: 14,
    description:
      "When you successfully use Counterspell to counteract a spell, you can turn it back on its caster. You send the spell back at the caster, who becomes the new target for the spell or the center of the spell's area, using the same spell DC and spell attack modifier. The reflected spell affects only the original caster, even if it is an area spell. The spell's caster can attempt a save and use other defenses as normal.",
    implemented: 'full',
    traits: ['Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['Counterspell'],
    mechanics: 'Modify Counterspell: on success, reflect the spell back at its caster. Only affects original caster.',
  },
  {
    id: 'witch-rites-of-transfiguration',
    name: 'Rites of Transfiguration',
    source: 'Witch',
    category: 'class',
    level: 14,
    description:
      "Your patron teaches your familiar the secrets of transformation. Your familiar learns the cursed metamorphosis spell, even if it isn't on your tradition's spell list. You can spend 10 minutes to replace one prepared spell of 6th rank or higher with a cursed metamorphosis spell of the same rank.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Familiar learns cursed metamorphosis (any tradition). Swap a 6th+ rank prepared spell via 10-minute ritual.',
  },
  // ── Level 16 ─────────────────────────────────────────
  {
    id: 'witch-effortless-concentration',
    name: 'Effortless Concentration',
    source: 'Witch',
    category: 'class',
    level: 16,
    description:
      'You can maintain a spell with hardly a thought. You immediately gain the effects of the Sustain action, allowing you to extend the duration of one of your active spells.',
    implemented: 'full',
    traits: ['Bard', 'Druid', 'Sorcerer', 'Summoner', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Trigger: your turn begins. Restriction: only for cantrips or spells from the class matching this feat.',
  },
  {
    id: 'witch-siphon-power',
    name: 'Siphon Power',
    source: 'Witch',
    category: 'class',
    level: 16,
    description:
      "You draw upon your patron's power to cast a spell without expending your normal resources. You cast one spell your familiar knows from your patron or lessons without spending a spell slot or having it prepared. The spell must be at least 1 rank lower than your highest-rank spell slot.",
    implemented: 'full',
    actionCost: 'free',
    mechanics: 'Frequency: once per day. Requirement: you haven\'t acted yet on your turn. Spell must be at least 1 rank lower than highest-rank slot. This action gains the trait of your spell tradition.',
  },
  // ── Level 18 ─────────────────────────────────────────
  {
    id: 'witch-patrons-claim',
    name: "Patron's Claim",
    source: 'Witch',
    category: 'class',
    level: 18,
    description:
      "Your patron extends its influence through your familiar in a terrifying display of power. Your familiar gains the Patron's Claim activity (2 actions, concentrate, once per hour): your familiar's mouth opens unnaturally wide, and the limb of your patron stretches out to grasp at a creature within 30 feet. The target takes 10d10 spirit damage with a basic Fortitude save against your spell DC. On a failure, the target is also drained 2 (drained 4 on a critical failure), and you regain 1 Focus Point.",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Frequency: once per hour. Damage: 10d10 spirit (basic Fort save). Failure: drained 2 (drained 4 on crit fail). Regain 1 Focus Point on damage dealt.',
  },
  {
    id: 'witch-split-hex',
    name: 'Split Hex',
    source: 'Witch',
    category: 'class',
    level: 18,
    description:
      "You split the power of your hex to affect another target. If the next action you use is to Cast a Spell that is a harmful hex with a single target, rather than targeting a single creature, you reduce the spell's rank by 2 and select a second target within range.",
    implemented: 'full',
    traits: ['Concentrate', 'Spellshape', 'Witch'],
    actionCost: 1,
    mechanics: 'Harmful single-target hex → target 2 creatures but spell rank reduced by 2.',
  },
  // ── Level 20 ─────────────────────────────────────────
  {
    id: 'witch-demons-hair',
    name: "Demon's Hair",
    source: 'Witch',
    category: 'class',
    level: 20,
    description:
      "Your hair constantly wriggles and writhes. Your damage die for your hair unarmed Strike increases by one step and it gains the reach and versatile slashing traits. Your familiar assumes partial control over your hair; as long as your familiar is alive and within 30 feet, you are permanently quickened, and you can use the extra action only to make a hair Strike. You can deliver hexes through your hair. When you successfully cast a non-cantrip hex that requires 2 or more actions to cast and that doesn't require a spell attack roll, if your target is within your reach, as part of the spellcasting activity you can make a hair Strike against them before applying any effects of the hex. If this Strike misses, the hex has no effect.",
    implemented: 'full',
    traits: ['Uncommon', 'Witch'],
    actionCost: 'passive',
    prerequisites: ['Living Hair'],
    mechanics: "Legacy (Pathfinder #168, PFS Limited). Hair die +1 step, gains reach + versatile slashing. Permanently quickened (hair Strike only). Deliver hexes via hair. If hair already has reach, gains sweep instead.",
  },
  {
    id: 'witch-hex-master',
    name: 'Hex Master',
    source: 'Witch',
    category: 'class',
    level: 20,
    description:
      'You embody the link to your patron so completely that you can cast your hexes in rapid succession. You are no longer limited to casting only a single hex each turn. In addition, when you cast cackle to sustain a hex, you gain the effects of Sustain for all your active hexes that have a duration of sustained.',
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'Remove 1-hex-per-turn limit. Cackle now Sustains ALL active sustained hexes simultaneously.',
  },
  {
    id: 'witch-patrons-truth',
    name: "Patron's Truth",
    source: 'Witch',
    category: 'class',
    level: 20,
    description:
      "You have mastered the greatest secrets of your patron's magic and learned a fundamental truth about your patron, even if their identity still remains a mystery. You gain an additional 10th-rank spell slot.",
    implemented: 'full',
    actionCost: 'passive',
    prerequisites: ["Patron's Gift"],
    mechanics: '+1 additional 10th-rank spell slot (total 2 with Patron\'s Gift).',
  },
  {
    id: 'witch-witchs-hut',
    name: "Witch's Hut",
    source: 'Witch',
    category: 'class',
    level: 20,
    description:
      "You perform a 1-day rite to bind a hut, house, wagon, tent, or similar construction of up to Huge size to your will, transforming it into a living creature. The hut uses your AC, saving throws, and Perception modifier. It has 150 HP, Hardness 10, and is immune to bleed, healing, paralyzed, poison, and all mental-based conditions. If destroyed, you can perform the rite again. You can have only one active hut at a time. You can command the hut (1 action, auditory + concentrate) with: Guard (attacks intruders with your spell attack modifier), Hide (10th-rank illusion disguise, your spell DC), Leap (10th-rank teleport with contents), Lock (cast lock on all doors/windows), or Move (sprouts legs, Speed 60 feet, imprecise for combat).",
    implemented: 'full',
    actionCost: 'passive',
    mechanics: 'HP 150, Hardness 10. Commands (1 action): Guard (attacks intruders), Hide (10th-rank illusion), Leap (10th-rank teleport), Lock (lock all doors/windows), Move (Speed 60 ft, non-combat). Continues following last order if you die.',
  },
];

export const WITCH_CLASS_FEATS: FeatEntry[] = RAW_WITCH_CLASS_FEATS.map(f => ({
  ...f,
  traits: f.traits ?? ['Witch'],
}));
