import type { FeatEntry } from './featTypes';
import { createClassFeature, WEAPON_SPECIALIZATION } from './sharedFeats';

// ──────────────────────────────────────────────────────────
// WIZARD — CLASS FEATURES & FEATS (Remastered, Player Core)
// ──────────────────────────────────────────────────────────

const RAW_WIZARD_CLASS_FEATURES: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'wizard-spellcasting',
    name: 'Arcane Spellcasting',
    source: 'Wizard',
    category: 'class_feature',
    level: 1,
    description:
      'Through dedicated study and practice, you can construct spells with academic rigor by shaping arcane magic. You are a spellcaster, and you can cast spells of the arcane tradition using the Cast a Spell activity. At 1st level, you can prepare up to two 1st-rank spells and five cantrips each morning from your spellbook, plus one extra curriculum cantrip and one extra curriculum spell of each rank from your arcane school. As you increase in level, the number of spells you can prepare each day increases, as does the highest rank of spell you can cast.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Prepared arcane casting (INT-based). Spellbook: starts with 10 cantrips + 5 1st-rank spells + 2 curriculum spells. Gains 2 spells per level + 1 curriculum spell at each new rank. Spell attack/DC trained at L1, expert at L7, master at L15, legendary at L19.',
  },
  {
    id: 'wizard-arcane-thesis',
    name: 'Arcane Thesis',
    source: 'Wizard',
    category: 'class_feature',
    level: 1,
    description:
      'During your studies to become a full-fledged wizard, you produced a thesis of unique magical research. You gain a special benefit depending on the topic of your thesis research. Choose one of: Experimental Spellshaping, Improved Familiar Attunement, Spell Blending, Spell Substitution, or Staff Nexus.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics:
      'Choose 1 of 5 theses: Experimental Spellshaping (free L1 spellshape feat + daily swap of spellshape feat up to half level from L4), Improved Familiar Attunement (free Familiar feat + extra familiar ability at L1/6/12/18 + Drain Familiar replaces Drain Bonded Item), Spell Blending (trade 2 same-rank slots for 1 slot up to 2 ranks higher, or trade 1 slot for 2 cantrips), Spell Substitution (10-min swap of 1 prepared spell from spellbook), Staff Nexus (makeshift staff with 1 cantrip + 1 1st-rank spell; merge with other staves; expend spells for charges; scales at L8 2 spells, L16 3 spells).',
    subChoices: { label: 'Choose an arcane thesis', options: [
      { id: 'experimental-spellshaping', name: 'Experimental Spellshaping', description: 'Free spellshape feat + daily swap' },
      { id: 'improved-familiar-attunement', name: 'Improved Familiar Attunement', description: 'Enhanced familiar with extra abilities' },
      { id: 'spell-blending', name: 'Spell Blending', description: 'Trade spell slots for higher-rank slots or cantrips' },
      { id: 'spell-substitution', name: 'Spell Substitution', description: '10-minute swap of prepared spells' },
      { id: 'staff-nexus', name: 'Staff Nexus', description: 'Makeshift staff that merges with other staves' },
    ] },
  },
  {
    id: 'wizard-arcane-school',
    name: 'Arcane School',
    source: 'Wizard',
    category: 'class_feature',
    level: 1,
    description:
      "Most wizards acquire their knowledge from a formal institution. You choose your arcane school, gaining curriculum spells and school focus spells. You get an extra curriculum cantrip slot and an extra curriculum spell slot at each rank. You start with 1 Focus Point and an initial school spell (focus spell). Schools: Ars Grammatica (runes/wards), Battle Magic (combat evocations), Civic Wizardry (construction/divination), Mentalism (illusions/enchantments), Protean Form (polymorph/transmutation), The Boundary (summoning/necromancy/planes), or Unified Magical Theory (no curriculum, extra Drain Bonded Item uses + bonus feat). Seven additional supplement schools exist.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics:
      'Choose 1 of 14 schools. Player Core (7): Ars Grammatica (protective wards), Battle Magic (force bolt), Civic Wizardry (earthworks), Mentalism (charming push), Protean Form (scramble body), The Boundary (fortify summoning), Unified Magical Theory (hand of the apprentice — no curriculum, Drain Bonded Item 1/day per spell rank, +1 bonus L1 wizard feat). Supplement (7): Red Mantis Magic, Gates, Kalistrade, Magical Technologies, Rooted Wisdom, Thassilonian Rune Magic, The Reclamation. Each school grants: +1 curriculum cantrip slot, +1 curriculum spell slot per rank, initial focus spell, focus pool 1. Refocus: 10 min studying spellbook.',    subChoices: { label: 'Choose an arcane school', options: [
      { id: 'ars-grammatica', name: 'Ars Grammatica', description: 'Protective wards and runic magic' },
      { id: 'battle-magic', name: 'Battle Magic', description: 'Force bolt and combat spells' },
      { id: 'civic-wizardry', name: 'Civic Wizardry', description: 'Earthworks and civic structure magic' },
      { id: 'mentalism', name: 'Mentalism', description: 'Charming push and mind-affecting spells' },
      { id: 'protean-form', name: 'Protean Form', description: 'Scramble body and transmutation' },
      { id: 'the-boundary', name: 'The Boundary', description: 'Fortify summoning and conjuration' },
      { id: 'unified-magical-theory', name: 'Unified Magical Theory', description: 'No curriculum; flexible Drain Bonded Item' },
      { id: 'school-of-the-gates', name: 'School of the Gates', description: 'Summoning and planar magic' },
      { id: 'kalistrade', name: 'School of Kalistrade', description: 'Commerce and negotiation magic' },
      { id: 'magical-technologies', name: 'Magical Technologies', description: 'Clockwork and arcane engineering' },
      { id: 'red-mantis-magic', name: 'Red Mantis Magic', description: 'Assassination and illusion' },
      { id: 'rooted-wisdom', name: 'Rooted Wisdom', description: 'Nature-wisdom arcane magic' },
      { id: 'thassilonian-rune-magic', name: 'Thassilonian Rune Magic', description: 'Ancient sin-based magic specialization' },
      { id: 'the-reclamation', name: 'The Reclamation', description: 'Recovery and restoration magic' },
    ] },  },
  {
    id: 'wizard-arcane-bond',
    name: 'Arcane Bond',
    source: 'Wizard',
    category: 'class_feature',
    level: 1,
    description:
      'You place some of your magical power in a bonded item. Each day when you prepare your spells, you can designate a single item you own as your bonded item. This is typically an item associated with spellcasting, such as a wand, ring, or staff, but you are free to designate a weapon or other item. You gain the Drain Bonded Item free action.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Designate 1 item as bonded item during daily preparations. Grants the Drain Bonded Item free action. Improved Familiar Attunement thesis: bonded item replaced by familiar (Drain Familiar instead).',
  },
  {
    id: 'wizard-drain-bonded-item',
    name: 'Drain Bonded Item',
    source: 'Wizard',
    category: 'class_feature',
    level: 1,
    description:
      "You expend the magical power stored in your bonded item. During your turn, you gain the ability to cast one spell you prepared today and already cast, without spending a spell slot. You must still Cast the Spell and meet the spell's other requirements.",
    implemented: 'full',
    traits: ['Arcane', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Free action, once per day (requirement: bonded item on person). Recast a prepared spell already cast today without expending a slot. Unified Magical Theory: once per day per spell rank instead. Improved Familiar Attunement: uses Drain Familiar (same mechanics, draws from familiar).',
  },
  // ── Level 5 ──────────────────────────────────────────
  {
    id: 'wizard-reflex-expertise',
    name: 'Reflex Expertise',
    source: 'Wizard',
    category: 'class_feature',
    level: 5,
    description: "You've developed a knack for dodging danger. Your proficiency rank for Reflex saves increases to expert.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 5, upgrade Reflex save proficiency to expert.',
  },
  // ── Level 7 ──────────────────────────────────────────
  {
    id: 'wizard-expert-spellcaster',
    name: 'Expert Spellcaster',
    source: 'Wizard',
    category: 'class_feature',
    level: 7,
    description: 'Extended practice of the arcane has improved your capabilities. Your proficiency ranks for spell attack modifier and spell DC increase to expert.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 7, upgrade spell attack modifier and spell DC to expert.',
  },
  // ── Level 9 ──────────────────────────────────────────
  {
    id: 'wizard-magical-fortitude',
    name: 'Magical Fortitude',
    source: 'Wizard',
    category: 'class_feature',
    level: 9,
    description: "Magical power has improved your body's resiliency. Your proficiency rank for Fortitude saves increases to expert.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 9, upgrade Fortitude save proficiency to expert.',
  },
  // ── Level 11 ─────────────────────────────────────────
  {
    id: 'wizard-perception-expertise',
    name: 'Perception Expertise',
    source: 'Wizard',
    category: 'class_feature',
    level: 11,
    description: 'You remain alert to threats around you. Your proficiency rank for Perception increases to expert.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 11, upgrade Perception proficiency to expert.',
  },
  {
    id: 'wizard-weapon-expertise',
    name: 'Wizard Weapon Expertise',
    source: 'Wizard',
    category: 'class_feature',
    level: 11,
    description: "Through sheer experience, you've improved your technique with your weapons. Your proficiency ranks for simple weapons and unarmed attacks increase to expert.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 11, upgrade simple weapons and unarmed attacks proficiency to expert.',
  },
  // ── Level 13 ─────────────────────────────────────────
  {
    id: 'wizard-defensive-robes',
    name: 'Defensive Robes',
    source: 'Wizard',
    category: 'class_feature',
    level: 13,
    description: 'The flow of magic and your training combine to help you avoid attacks. Your proficiency rank in unarmored defense increases to expert.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 13, upgrade unarmored defense proficiency to expert.',
  },
  // Weapon Specialization (L13) — shared template
  createClassFeature(WEAPON_SPECIALIZATION, 'Wizard', 13),
  // ── Level 15 ─────────────────────────────────────────
  {
    id: 'wizard-master-spellcaster',
    name: 'Master Spellcaster',
    source: 'Wizard',
    category: 'class_feature',
    level: 15,
    description: 'You command superlative spellcasting ability. Your proficiency ranks for spell attack modifier and spell DC increase to master.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 15, upgrade spell attack modifier and spell DC to master.',
  },
  // ── Level 17 ─────────────────────────────────────────
  {
    id: 'wizard-prodigious-will',
    name: 'Prodigious Will',
    source: 'Wizard',
    category: 'class_feature',
    level: 17,
    description: "Your mind is simply too complex and sophisticated to be tampered with. Your proficiency rank for Will saves increases to master. When you roll a success at a Will save, you get a critical success instead.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 17, upgrade Will save proficiency to master. Success on Will saves becomes critical success.',
  },
  // ── Level 19 ─────────────────────────────────────────
  {
    id: 'wizard-archwizards-spellcraft',
    name: "Archwizard's Spellcraft",
    source: 'Wizard',
    category: 'class_feature',
    level: 19,
    description:
      "You command the most potent arcane magic and can cast a spell of truly incredible power. You gain a single 10th-rank spell slot and can prepare a spell in that slot using wizard spellcasting. Unlike with other spell slots, you can't use 10th-rank slots with abilities that give you more spell slots or that let you cast spells without expending spell slots. You don't gain more 10th-rank spells as you level up, but you can take the Archwizard's Might feat to gain a second slot.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: "Grant 1 spell slot at rank 10. Cannot be duplicated by slot-granting abilities. Archwizard's Might feat grants a 2nd 10th-rank slot.",
  },
  {
    id: 'wizard-legendary-spellcaster',
    name: 'Legendary Spellcaster',
    source: 'Wizard',
    category: 'class_feature',
    level: 19,
    description: 'You are a consummate spellcaster, blending both arcane theory and practical spellcraft. Your proficiency ranks for spell attack modifier and spell DC increase to legendary.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'At level 19, upgrade spell attack modifier and spell DC to legendary.',
  },
];

export const WIZARD_CLASS_FEATURES: FeatEntry[] = RAW_WIZARD_CLASS_FEATURES.map(f => ({
  ...f,
  traits: f.traits ?? ['Wizard'],
}));

// ──────────────────────────────────────────────────────────
// WIZARD CLASS FEATS (Selectable)
// ──────────────────────────────────────────────────────────

const RAW_WIZARD_CLASS_FEATS: FeatEntry[] = [
  // ── Level 1 ──────────────────────────────────────────
  {
    id: 'wizard-counterspell',
    name: 'Counterspell',
    source: 'Wizard',
    category: 'class',
    level: 1,
    description:
      'When a foe Casts a Spell and you can see its manifestations, you can use your own magic to disrupt it. You expend a prepared spell to counter the triggering creature\'s casting of that same spell. You lose your spell slot as if you had cast the triggering spell. You then attempt to counteract the triggering spell.',
    implemented: 'full',
    traits: ['Witch', 'Wizard'],
    actionCost: 'reaction',
    mechanics: 'Trigger: a creature Casts a Spell you have prepared. Expend a matching prepared spell to attempt a counteract check. Leads to Clever Counterspell, Reflect Spell.',
  },
  {
    id: 'wizard-familiar',
    name: 'Familiar',
    source: 'Wizard',
    category: 'class',
    level: 1,
    description:
      'You make a pact with a creature that serves you and assists your spellcasting. You gain a familiar.',
    implemented: 'full',
    traits: ['Magus', 'Sorcerer', 'Thaumaturge', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Grants a familiar companion with 2 familiar/master abilities per day (base). Improved Familiar Attunement thesis: starts with extra abilities. Leads to Enhanced Familiar.',
  },
  {
    id: 'wizard-reach-spell',
    name: 'Reach Spell',
    source: 'Wizard',
    category: 'class',
    level: 1,
    description:
      "You can extend your spells' range. If the next action you use is to Cast a Spell that has a range, increase that spell's range by 30 feet. As is standard for increasing spell ranges, if the spell normally has a range of touch, you extend its range to 30 feet.",
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Concentrate', 'Druid', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. Increase next spell range by 30 ft. Touch spells become 30-ft range.',
  },
  {
    id: 'wizard-spellbook-prodigy',
    name: 'Spellbook Prodigy',
    source: 'Wizard',
    category: 'class',
    level: 1,
    description:
      'You are a consummate professional when it comes to recording and deciphering spells. You gain the Magical Shorthand skill feat. Additionally, if you critically fail to Learn a Spell, you can try again later — treat the critical failure as a failure instead.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    prerequisites: ['Trained in Arcana'],
    mechanics: 'Free Magical Shorthand skill feat. Critical failure on Learn a Spell becomes a regular failure (can retry).',
  },
  {
    id: 'wizard-widen-spell',
    name: 'Widen Spell',
    source: 'Wizard',
    category: 'class',
    level: 1,
    description:
      'You manipulate the energy of your spell, causing it to spread out and affect a wider area. If the next action you use is to Cast a Spell that has an area of a burst, cone, or line and does not have a duration, increase the area of that spell. Add 5 feet to the radius of a burst that normally has a radius of at least 10 feet. Add 5 feet to the length of a cone or line that is normally 15 feet long or smaller, and add 10 feet to the length of a larger cone or line.',
    implemented: 'full',
    traits: ['Druid', 'Manipulate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. +5 ft to burst radius (10 ft+ base). +5 ft to cones/lines 15 ft or less; +10 ft to larger. Only works on spells without a duration.',
  },
  // ── Level 2 ──────────────────────────────────────────
  {
    id: 'wizard-cantrip-expansion',
    name: 'Cantrip Expansion',
    source: 'Wizard',
    category: 'class',
    level: 2,
    description:
      'Study broadens your range of simple spells. You can prepare two additional cantrips each day.',
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Magus', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Prepared casters: +2 cantrip preparations per day. Spontaneous casters: +2 cantrips in repertoire.',
  },
  {
    id: 'wizard-conceal-spell',
    name: 'Conceal Spell',
    source: 'Wizard',
    category: 'class',
    level: 2,
    description:
      "Hiding your gestures and incantations within other speech and movement, you attempt to conceal the fact that you are Casting a Spell. If the next action you use is to Cast a Spell, the spell gains the subtle trait, hiding the shining runes, sparks of magic, and other manifestations that would usually give away your spellcasting. The trait hides only the spell's spellcasting actions and manifestations, not its effects.",
    implemented: 'full',
    traits: ['Animist', 'Concentrate', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. Next Cast a Spell gains the subtle trait, hiding spellcasting actions/manifestations (not effects).',
  },
  {
    id: 'wizard-energy-ablation',
    name: 'Energy Ablation',
    source: 'Wizard',
    category: 'class',
    level: 2,
    description:
      "You study the energy of your spell and convert some of it to a protective barrier. If the next action you use is to Cast a Spell that deals acid, cold, electricity, fire, or sonic damage, before you cast it, you gain resistance to that type of damage equal to the spell's rank. The resistance lasts until the end of your next turn.",
    implemented: 'full',
    traits: ['Spellshape', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. Gain resistance to the spell\'s energy type equal to spell rank. Lasts until end of next turn.',
  },
  {
    id: 'wizard-enhanced-familiar',
    name: 'Enhanced Familiar',
    source: 'Wizard',
    category: 'class',
    level: 2,
    description:
      'You infuse your familiar with additional magical energy, increasing its abilities. You can select four familiar or master abilities each day, instead of two.',
    implemented: 'full',
    traits: ['Animist', 'Druid', 'Magus', 'Sorcerer', 'Thaumaturge', 'Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['A familiar'],
    mechanics: 'Familiar/master abilities per day: base 2 becomes 4. Improved Familiar Attunement thesis: base is already higher.',
  },
  {
    id: 'wizard-nonlethal-spell',
    name: 'Nonlethal Spell',
    source: 'Wizard',
    category: 'class',
    level: 2,
    description:
      "You blunt the force of your spell to avoid dealing a killing blow. If the next action you use is to Cast a Spell that deals damage and doesn't have the death or void trait, that spell gains the nonlethal trait.",
    implemented: 'full',
    traits: ['Manipulate', 'Spellshape', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. Next damage spell gains nonlethal trait. Cannot be used on spells with death or void traits.',
  },
  // ── Level 4 ──────────────────────────────────────────
  {
    id: 'wizard-bespell-strikes',
    name: 'Bespell Strikes',
    source: 'Wizard',
    category: 'class',
    level: 4,
    description:
      "You channel the magical energy of spells you cast into your weapon and body. After you cast a non-cantrip spell, your next weapon or unarmed Strike deals an extra 1d6 force damage, or 1d6 of the same damage type the spell dealt if it dealt damage. This extra damage lasts until the end of your turn.",
    implemented: 'full',
    traits: ['Oracle', 'Sorcerer', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Frequency: once per turn. After casting a non-cantrip spell, next Strike deals +1d6 force (or matching spell damage type). Lasts until end of turn. Wizard: Strike gains arcane trait.',
  },
  {
    id: 'wizard-call-wizardly-tools',
    name: 'Call Wizardly Tools',
    source: 'Wizard',
    category: 'class',
    level: 4,
    description:
      "You magically call your bonded item or spellbook to you. The item teleports into your hand from up to 1 mile away. The item must weigh 1 Bulk or less. If the item is in another creature's possession, this ability fails.",
    implemented: 'full',
    traits: ['Concentrate', 'Teleportation', 'Wizard'],
    actionCost: 1,
    prerequisites: ['Arcane bond'],
    mechanics: 'Teleports bonded item or spellbook to hand. Range: up to 1 mile. Max 1 Bulk. Fails if held by another creature.',
  },
  {
    id: 'wizard-irezoko-tattoo',
    name: 'Irezoko Tattoo',
    source: 'Wizard',
    category: 'class',
    level: 4,
    description:
      'Your face bears an intricate magical tattoo known as the irezoko. Choose a class that you are a member of that grants you access to a focus pool. Once per day, you may concentrate upon the pattern of your irezoko to recover 1 Focus Point as a three-action activity.',
    implemented: 'full',
    traits: ['Uncommon', 'Barbarian', 'Bard', 'Champion', 'Cleric', 'Druid', 'Fighter', 'Gunslinger', 'Inventor', 'Magus', 'Monk', 'Oracle', 'Ranger', 'Rogue', 'Sorcerer', 'Summoner', 'Swashbuckler', 'Witch', 'Wizard'],
    actionCost: 3,
    prerequisites: ['Expert in Arcana or Occultism'],
    mechanics: 'Legacy (Absalom, City of Lost Omens). Requires College of Mysteries access. 1/day: recover 1 Focus Point (3-action activity). Requires a class with a focus pool.',
    subChoices: { label: 'Choose a class with focus pool', options: [
      { id: 'bard', name: 'Bard' }, { id: 'champion', name: 'Champion' }, { id: 'cleric', name: 'Cleric' },
      { id: 'druid', name: 'Druid' }, { id: 'magus', name: 'Magus' }, { id: 'monk', name: 'Monk' },
      { id: 'oracle', name: 'Oracle' }, { id: 'psychic', name: 'Psychic' }, { id: 'ranger', name: 'Ranger' },
      { id: 'sorcerer', name: 'Sorcerer' }, { id: 'summoner', name: 'Summoner' }, { id: 'witch', name: 'Witch' },
      { id: 'wizard', name: 'Wizard' },
    ] },
  },
  {
    id: 'wizard-linked-focus',
    name: 'Linked Focus',
    source: 'Wizard',
    category: 'class',
    level: 4,
    description:
      "You have linked your bonded item and your focus, so that channeling one restores the other. Once per day, when you Drain your Bonded Item to cast a spell that is in your arcane school's curriculum, you also regain 1 Focus Point.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    prerequisites: ['Arcane bond', 'Arcane school'],
    mechanics: '1/day: Drain Bonded Item on a curriculum spell also regains 1 Focus Point.',
  },
  {
    id: 'wizard-spell-protection-array',
    name: 'Spell Protection Array',
    source: 'Wizard',
    category: 'class',
    level: 4,
    description:
      'You create a small protective magical field. Choose a point within 30 feet. You create a 5-foot burst centered on that point. Creatures inside the burst gain a +1 status bonus to saving throws against magic. You can Sustain this effect for up to 1 minute.',
    implemented: 'full',
    traits: ['Arcane', 'Manipulate', 'Wizard'],
    actionCost: 1,
    mechanics: '5-ft burst within 30 ft. +1 status bonus to saves vs magic for creatures inside. Sustain up to 1 minute.',
  },
  {
    id: 'wizard-undying-conviction',
    name: 'Undying Conviction',
    source: 'Wizard',
    category: 'class',
    level: 4,
    description:
      'Your presence has a bolstering effect on your undead minions. Undead creatures under your control and within a 30-foot emanation gain a +2 status bonus to saving throws to resist positive damage and to Will saving throws to resist effects that would make them controlled.',
    implemented: 'full',
    traits: ['Uncommon', 'Aura', 'Cleric', 'Necromancy', 'Oracle', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['Able to create or control undead'],
    mechanics: 'Legacy (Book of the Dead). 30-ft aura. Undead minions: +2 status bonus to saves vs vitality damage and vs controlled effects.',
  },
  // ── Level 6 ──────────────────────────────────────────
  {
    id: 'wizard-convincing-illusion',
    name: 'Convincing Illusion',
    source: 'Wizard',
    category: 'class',
    level: 6,
    description:
      "You use your deceptive skills to reinforce your illusions. When a creature succeeds (but doesn't critically succeed) at disbelieving your illusion spell, you can attempt a Deception check against that creature's Perception DC. If you succeed, the creature fails to disbelieve the illusion instead.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'reaction',
    prerequisites: ['Expert in Deception'],
    mechanics: 'Trigger: creature succeeds (non-critical) at Perception check or Will save to disbelieve your illusion. Deception check vs Perception DC; success means the creature fails to disbelieve.',
  },
  {
    id: 'wizard-detonating-spell',
    name: 'Detonating Spell',
    source: 'Wizard',
    category: 'class',
    level: 6,
    description:
      "Your spell becomes volatile and explosive. If the next action you use is to Cast a Spell that deals damage to a single target and the spell successfully damages the target, it also deals splash damage equal to the spell's rank to creatures within 5 feet of the target. This splash damage doesn't apply to the primary target. The splash damage type matches the spell's damage type.",
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Concentrate', 'Metamagic', 'Oracle', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Legacy (Knights of Lastwall). Metamagic. Single-target damage spell gains splash damage = spell rank to adjacent creatures (not primary target).',
  },
  {
    id: 'wizard-explosive-arrival',
    name: 'Explosive Arrival',
    source: 'Wizard',
    category: 'class',
    level: 6,
    description:
      'You imbue a summoned creature with a burst of destructive energy. If the next action you use is to Cast a Spell that summons a creature, the summoned creature arrives in an explosion. When it appears, it deals 1d4 fire damage per rank of the spell in a 10-foot emanation centered on the summoned creature.',
    implemented: 'full',
    traits: ['Concentrate', 'Manipulate', 'Spellshape', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Spellshape (free action). Before summoning spell: summoned creature deals 1d4 fire per spell rank in 10-ft emanation on arrival.',
  },
  {
    id: 'wizard-irresistible-magic',
    name: 'Irresistible Magic',
    source: 'Wizard',
    category: 'class',
    level: 6,
    description:
      "Your spells overwhelm even those with magical defenses. When a creature has a status bonus to saving throws against magic (such as from a spell or magic item), that bonus is reduced by 1 against your spells (minimum +0).",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: "Passive. Creatures' status bonuses to saves vs magic are reduced by 1 (minimum +0) against your spells.",
  },
  {
    id: 'wizard-split-slot',
    name: 'Split Slot',
    source: 'Wizard',
    category: 'class',
    level: 6,
    description:
      "You can prepare two spells in a single spell slot, as long as both spells are at least 1 rank lower than your highest-rank spell slot. When you cast one of the spells from that slot, the unused spell dissipates. You choose which spell to cast at the time of casting. You can split only one slot per day in this way.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Prepare 2 spells in 1 slot (both at least 1 rank lower than highest). Choose which to cast; the other dissipates. 1 split slot per day.',
  },
  {
    id: 'wizard-steady-spellcasting',
    name: 'Steady Spellcasting',
    source: 'Wizard',
    category: 'class',
    level: 6,
    description:
      "Confident in your technique, you don't easily lose your concentration when you Cast a Spell. If a reaction would disrupt your spellcasting action, attempt a DC 15 flat check. If you succeed, your action isn't disrupted.",
    implemented: 'full',
    traits: ['Bard', 'Cleric', 'Druid', 'Oracle', 'Psychic', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Passive. DC 15 flat check when a reaction would disrupt your spellcasting. Success: spellcasting is not disrupted.',
  },
  // ── Level 8 ──────────────────────────────────────────
  {
    id: 'wizard-advanced-school-spell',
    name: 'Advanced School Spell',
    source: 'Wizard',
    category: 'class',
    level: 8,
    description:
      'You gain access to the advanced teachings of your arcane institution, learning a powerful new school spell. You gain the advanced school spell for your arcane school.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Grants the advanced focus spell for your chosen arcane school: Ars Grammatica (rune of observation), Battle Magic (energy absorption), Civic Wizardry (community restoration), Mentalism (invisibility cloak), Protean Form (shifting form), The Boundary (spiral of horrors), Unified Magical Theory (interdisciplinary incantation).',
  },
  {
    id: 'wizard-bond-conservation',
    name: 'Bond Conservation',
    source: 'Wizard',
    category: 'class',
    level: 8,
    description:
      "By careful parceling of magical energy, you can conserve your bonded item's power to cast additional spells. If the next action you use is to Cast a Spell using the extra spell slot from Drain Bonded Item, you gain an extra use of Drain Bonded Item that day. This extra use must be used to cast a spell at least 2 ranks lower than the first spell cast with Drain Bonded Item.",
    implemented: 'full',
    traits: ['Manipulate', 'Spellshape', 'Wizard'],
    actionCost: 1,
    prerequisites: ['Arcane bond'],
    mechanics: 'Spellshape. Before casting via Drain Bonded Item: gain an extra Drain Bonded Item use that day for a spell 2+ ranks lower.',
  },
  {
    id: 'wizard-chaotic-spell',
    name: 'Chaotic Spell',
    source: 'Wizard',
    category: 'class',
    level: 8,
    description:
      "You add a chaotic and unpredictable element to your spell. If the next action you use is to Cast a Spell that deals acid, cold, electricity, fire, or sonic damage, roll 1d6 to determine the spell's damage type and an additional effect: 1=Acid+Sickened 1, 2=Cold+Speed penalty, 3=Electricity+off-guard, 4=Fire+persistent fire damage equal to spell rank, 5=Force+no extra, 6=Sonic+Deafened 2 rounds.",
    implemented: 'full',
    traits: ['Uncommon', 'Bard', 'Manipulate', 'Metamagic', 'Oracle', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 1,
    mechanics: 'Legacy (Wake the Dead #3). Metamagic. Randomize energy damage type (d6) + bonus debuff per result.',
  },
  {
    id: 'wizard-form-retention',
    name: 'Form Retention',
    source: 'Wizard',
    category: 'class',
    level: 8,
    description:
      'When preparing a polymorph spell that lasts 1 minute and grants a battle form, you can prepare the spell in a slot 2 ranks higher than normal. This doesn\'t grant any of the normal benefits of heightening a spell, but the spell lasts up to 10 minutes.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Prepare battle form polymorph spell in a slot 2 ranks higher to extend duration from 1 minute to 10 minutes. No other heightening benefits.',
  },
  {
    id: 'wizard-helts-spelldance',
    name: "Helt's Spelldance",
    source: 'Wizard',
    category: 'class',
    level: 8,
    description:
      "You combine spellcasting with a daring dance. Attempt a Performance check against all observers' Perception DCs. Then Stride once or twice. During this movement, you don't trigger reactions from creatures against whose Perception DC you succeeded. After your movement, Cast a Spell: 1 or 2 actions if you Strode once, or only 1 action if you Strode twice. Critical success: targets take a \u22121 circumstance penalty to saves vs the spell. Creatures are temporarily immune for 10 minutes.",
    implemented: 'full',
    traits: ['Uncommon', 'Bard', 'Sorcerer', 'Witch', 'Wizard'],
    actionCost: 3,
    prerequisites: ['Expert in Performance'],
    mechanics: 'Legacy (Firebrands). Requires Firebrands second mark access. Performance vs Perception DCs. Stride 1\u20132 times avoiding reactions from succeeded targets. Cast a Spell after (action limit based on Strides). Crit success: \u22121 circumstance penalty to saves.',
  },
  {
    id: 'wizard-knowledge-is-power',
    name: 'Knowledge is Power',
    source: 'Wizard',
    category: 'class',
    level: 8,
    description:
      "When you critically succeed at a Recall Knowledge check about a creature, you can invoke your knowledge to make the creature take a \u22121 circumstance penalty to either AC and saves against the next attack you make against it, or the next spell you cast that it needs to defend against. The creature takes the same penalty to its attack or DC the next time it attacks you or causes you to attempt a save. Shareable with allies. Expires after 1 minute if unused.",
    implemented: 'full',
    traits: ['Magus', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'On critical success Recall Knowledge: target takes \u22121 circumstance penalty to AC/saves vs your next attack/spell, OR \u22121 to its attack/DC vs you. Shareable with allies. Expires after 1 minute.',
  },
  // ── Level 10 ─────────────────────────────────────────
  {
    id: 'wizard-overwhelming-energy',
    name: 'Overwhelming Energy',
    source: 'Wizard',
    category: 'class',
    level: 10,
    description:
      "With a complex gesture, you call upon the power of your spell to overcome enemies' resistances. If the next action you use is to Cast a Spell, the spell ignores an amount of the target's resistance to acid, cold, electricity, fire, or sonic damage equal to your level. This applies to all damage the spell deals, including persistent damage and damage caused by an ongoing effect of the spell. A creature's immunities are unaffected.",
    implemented: 'full',
    traits: ['Druid', 'Manipulate', 'Sorcerer', 'Spellshape', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. Next spell ignores energy resistance equal to your level (acid, cold, electricity, fire, sonic). Includes persistent and ongoing spell damage. Does NOT bypass immunities.',
  },
  {
    id: 'wizard-quickened-casting',
    name: 'Quickened Casting',
    source: 'Wizard',
    category: 'class',
    level: 10,
    description:
      'If your next action is to cast a cantrip or a spell that is at least 2 ranks lower than the highest-rank spell slot you have, reduce the number of actions to cast it by 1 (minimum 1 action).',
    implemented: 'full',
    traits: ['Bard', 'Concentrate', 'Oracle', 'Sorcerer', 'Spellshape', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Frequency: once per day. Reduce casting time by 1 action (minimum 1). Only for cantrips or spells 2+ ranks lower than highest slot. Class-locked to Wizard arcane spells.',
  },
  {
    id: 'wizard-scroll-adept',
    name: 'Scroll Adept',
    source: 'Wizard',
    category: 'class',
    level: 10,
    description:
      "During your daily preparations, you can create two temporary scrolls containing arcane spells from your spellbook. Each scroll must be of a different spell rank, and both spell ranks must be 2 or more ranks lower than your highest-rank spell. Any scrolls you create this way become non-magical the next time you make your daily preparations. A temporary scroll has no value if sold. At master proficiency in your spellcasting, you can create 3 scrolls. At legendary proficiency, you can create 4 scrolls.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Daily prep: create 2 temporary scrolls (different ranks, 2+ lower than highest). Expire at next daily prep; no sale value. Master: 3 scrolls. Legendary: 4 scrolls.',
  },
  // ── Level 12 ─────────────────────────────────────────
  {
    id: 'wizard-clever-counterspell',
    name: 'Clever Counterspell',
    source: 'Wizard',
    category: 'class',
    level: 12,
    description:
      "You creatively apply your prepared spells to Counterspell a much wider variety of your opponents' magic. Instead of being able to counter a foe's spell with Counterspell only if you have that same spell prepared, you can use Counterspell as long as you have the spell the foe is casting in your spellbook. When you use Counterspell in this way, you must still expend a prepared spell; the prepared spell you expend must share a trait with the triggering spell other than concentrate, manipulate, or its tradition trait.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    prerequisites: ['Counterspell', 'Quick Recognition'],
    mechanics: 'Modify Counterspell: can counter any spell in your spellbook (not just prepared). Must expend a prepared spell sharing a trait with the triggering spell (excluding concentrate, manipulate, tradition).',
  },
  {
    id: 'wizard-forcible-energy',
    name: 'Forcible Energy',
    source: 'Wizard',
    category: 'class',
    level: 12,
    description:
      "You perform complex manipulations to make the energy from your spells so powerful that your enemies remain vulnerable to it afterward. If your next action is to Cast a Spell that deals acid, cold, electricity, fire, or sonic damage, you can select one target that was damaged to gain weakness 5 to that damage type until the end of your next turn.",
    implemented: 'full',
    traits: ['Manipulate', 'Spellshape', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. After energy damage spell: 1 damaged target gains weakness 5 to that damage type until end of your next turn.',
  },
  {
    id: 'wizard-keen-magical-detection',
    name: 'Keen Magical Detection',
    source: 'Wizard',
    category: 'class',
    level: 12,
    description:
      "You sense magical dangers. When using the Detect Magic exploration activity, you can roll initiative twice and use the better result so long as at least one opponent has a magical effect or magic item and is in range of your detect magic.",
    implemented: 'full',
    traits: ['Fortune', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'While using Detect Magic exploration activity: roll initiative twice, use better result (requires magical opponent in range). Fortune trait.',
  },
  {
    id: 'wizard-magic-sense',
    name: 'Magic Sense',
    source: 'Wizard',
    category: 'class',
    level: 12,
    description:
      'You have a literal sixth sense for ambient magic in your vicinity. You can sense the presence of magic auras as though you were always using a 1st-rank detect magic spell. This detects magic in your field of vision only. When you Seek, you gain the benefits of a 3rd-rank detect magic spell on things you see (in addition to the normal benefits of Seeking). You can turn this sense off and back on as a free action at the start or the end of your turn.',
    implemented: 'full',
    traits: ['Arcane', 'Detection', 'Magus', 'Oracle', 'Sorcerer', 'Wizard'],
    actionCost: 'passive',
    mechanics: 'Passive detect magic (1st-rank, field of vision only). When Seeking: 3rd-rank detect magic on seen things. Toggle on/off as free action at start or end of turn.',
  },
  {
    id: 'wizard-necromancers-visage',
    name: "Necromancer's Visage",
    source: 'Wizard',
    category: 'class',
    level: 12,
    description:
      "Necromantic energy demonstrates your power over undead, creating a demeanor that commands their fear and respect. Each time an undead creature 2 or more levels lower than you attacks you, it must attempt a Will save against your spell DC. Critical success: permanently immune. Success: can attack normally this turn. Failure: wastes the action, can't attack you this turn. Critical failure: wastes the action, can't attack you while Visage persists. Hostile actions end it; restore via 10 minutes.",
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Necromancy', 'Oracle', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['Able to create or control undead'],
    mechanics: 'Legacy (Book of the Dead). Undead 2+ levels lower must Will save to attack you. Failure: wastes action. Crit fail: can never attack you while Visage persists. Hostile action ends it; restore via 10-min activity.',
  },
  // ── Level 14 ─────────────────────────────────────────
  {
    id: 'wizard-bonded-focus',
    name: 'Bonded Focus',
    source: 'Wizard',
    category: 'class',
    level: 14,
    description:
      'Your connection to your bonded item increases your focus pool. Whenever you Refocus while your bonded item is in your possession, you completely refill your focus pool.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    prerequisites: ['Arcane bond'],
    mechanics: 'Refocus with bonded item: completely refill focus pool (up to 3).',
  },
  {
    id: 'wizard-reflect-spell',
    name: 'Reflect Spell',
    source: 'Wizard',
    category: 'class',
    level: 14,
    description:
      "When you successfully use Counterspell to counteract a spell that affects targeted creatures or an area, you can turn that spell's effect back on its caster. When reflected, the spell affects only the original caster, even if it's an area spell or it would normally affect more than one creature. The original caster can attempt a save and use other defenses against the reflected spell as normal.",
    implemented: 'full',
    traits: ['Witch', 'Wizard'],
    actionCost: 'passive',
    prerequisites: ['Counterspell'],
    mechanics: 'Modify Counterspell: on success, reflect the spell back at its caster. Only affects original caster even for area spells.',
  },
  {
    id: 'wizard-secondary-detonation-array',
    name: 'Secondary Detonation Array',
    source: 'Wizard',
    category: 'class',
    level: 14,
    description:
      "You divert some of your spell's energy into an unstable runic array. If your next action is to Cast a Spell that affects an area, a glowing magic circle appears in a 5-foot burst centered within that area. At the beginning of your next turn, the circle detonates, dealing 1d6 force damage per rank of the spell to all creatures within the circle, with a basic Reflex save.",
    implemented: 'full',
    traits: ['Manipulate', 'Spellshape', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. After area spell: place 5-ft burst in the area. Detonates at start of next turn: 1d6 force per spell rank (basic Reflex).',
  },
  {
    id: 'wizard-sepulchral-sublimation',
    name: 'Sepulchral Sublimation',
    source: 'Wizard',
    category: 'class',
    level: 14,
    description:
      "You repurpose the negative energy that flows through your minions at a moment's notice. Instantly destroy one undead minion within 60 feet that is permanently under your control. If your next action is to cast a necromancy spell from a spell slot, you don't expend the slot. The spell's level must be half the destroyed minion's level or lower and the spell can't have a duration.",
    implemented: 'full',
    traits: ['Uncommon', 'Cleric', 'Concentrate', 'Metamagic', 'Necromancy', 'Oracle', 'Wizard'],
    actionCost: 1,
    prerequisites: ['Able to create or control undead'],
    mechanics: 'Legacy (Book of the Dead). Destroy 1 controlled undead within 60 ft. Next necromancy spell (rank up to half minion level, no duration) doesn\'t expend its slot.',
  },
  {
    id: 'wizard-shift-spell',
    name: 'Shift Spell',
    source: 'Wizard',
    category: 'class',
    level: 14,
    description:
      "You have an active spell that affects an area and you are within the spell's range. You move the spell's area to a new location within 120 feet. The spell's remaining duration is reduced by half. The spell no longer affects its previous area.",
    implemented: 'full',
    traits: ['Uncommon', 'Wizard'],
    actionCost: 1,
    mechanics: 'Legacy (Pathfinder #167). Requires Magaambya access. Move active area spell within 120 ft. Duration halved. Previous area no longer affected.',
  },
  {
    id: 'wizard-superior-bond',
    name: 'Superior Bond',
    source: 'Wizard',
    category: 'class',
    level: 14,
    description:
      'When you draw upon your bonded item, you can leave a bit of energy within it for later use. You can use Drain Bonded Item one additional time per day, but only to cast a spell 2 or more ranks lower than your highest-rank wizard spell slot.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    prerequisites: ['Arcane bond'],
    mechanics: '+1 additional Drain Bonded Item use per day, restricted to spells 2+ ranks lower than highest wizard slot.',
  },
  // ── Level 16 ─────────────────────────────────────────
  {
    id: 'wizard-effortless-concentration',
    name: 'Effortless Concentration',
    source: 'Wizard',
    category: 'class',
    level: 16,
    description:
      'You can maintain a spell with hardly a thought. You immediately gain the effects of the Sustain action, allowing you to extend the duration of one of your active spells.',
    implemented: 'full',
    traits: ['Bard', 'Druid', 'Sorcerer', 'Summoner', 'Witch', 'Wizard'],
    actionCost: 'free',
    mechanics: 'Trigger: your turn begins. Auto-Sustain one active spell. Only for cantrips or spells from the class matching this feat.',
  },
  {
    id: 'wizard-scintillating-spell',
    name: 'Scintillating Spell',
    source: 'Wizard',
    category: 'class',
    level: 16,
    description:
      "Your spells become a radiant display of light and color. If your next action is to Cast a Spell that doesn't have the darkness trait, has no duration, and requires creatures to attempt a Reflex save, the spell explodes in a spray of scintillating lights, in addition to its other effects. Each creature that failed its Reflex save against the spell is dazzled for 1 round, and those who critically failed are instead blinded for 1 round.",
    implemented: 'full',
    traits: ['Concentrate', 'Light', 'Sorcerer', 'Spellshape', 'Wizard'],
    actionCost: 1,
    mechanics: 'Spellshape. Spell with Reflex save (no darkness trait, no duration): failed save = dazzled 1 round; critical failure = blinded 1 round.',
  },
  {
    id: 'wizard-spell-tinker',
    name: 'Spell Tinker',
    source: 'Wizard',
    category: 'class',
    level: 16,
    description:
      "You've learned to alter choices you make when casting spells on yourself. After casting a spell on only yourself that offers several choices of effect (such as resist energy or a polymorph spell that offers several potential forms), you can alter the choice you made when Casting the Spell (for instance, choosing a different type of damage for resist energy). You can't use this feat if the benefits of the spell have already been used up or if the effects of the first choice would persist after switching.",
    implemented: 'full',
    traits: ['Concentrate', 'Wizard'],
    actionCost: 2,
    mechanics: 'After casting a self-only spell with multiple effect choices: change your selection (e.g., different resist energy type, different polymorph form). Cannot use if benefits already consumed or first choice effects would persist.',
  },
  // ── Level 18 ─────────────────────────────────────────
  {
    id: 'wizard-infinite-possibilities',
    name: 'Infinite Possibilities',
    source: 'Wizard',
    category: 'class',
    level: 18,
    description:
      "You can prepare a spell slot that exists in your mind as many different possibilities at once. Once during your daily preparations, you can use a spell slot to hold that infinite potential, rather than using it to prepare a spell. You can use this spell slot to cast any spell from your spellbook that's at least 2 ranks lower than the slot you designate; the spell acts in all ways as a spell of 2 ranks lower. You don't have any particular spell prepared in that slot until you cast it.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Daily prep: 1 slot becomes a wildcard. Cast any spellbook spell at least 2 ranks lower than the slot; spell acts as 2 ranks lower. No specific spell prepared until cast.',
  },
  {
    id: 'wizard-reprepare-spell',
    name: 'Reprepare Spell',
    source: 'Wizard',
    category: 'class',
    level: 18,
    description:
      "You've discovered how to reuse some of your spell slots over and over. You can spend 10 minutes to prepare a spell that you already cast today, regaining access to that spell slot. The spell must be of 4th rank or lower and can't have a duration. You can reprepare a spell in this way even if you've already reprepared that spell previously in the same day. If you have the spell substitution arcane thesis, you can instead prepare a different spell in an expended slot, as long as the new spell doesn't have a duration.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: '10-min activity: reprepare a cast spell (rank 4 or lower, no duration). Repeatable. Spell Substitution thesis: can prepare a different spell in the expended slot (no duration restriction lifted).',
  },
  {
    id: 'wizard-second-thoughts',
    name: 'Second Thoughts',
    source: 'Wizard',
    category: 'class',
    level: 18,
    description:
      "When your target proves resilient to your magical deceptions, you can try them again on someone else. You can Cast the triggering Spell a second time, targeting a different creature, without expending an additional spell slot. You can do so only until the end of your next turn, and you can't use Second Thoughts on it after the second casting of the spell.",
    implemented: 'full',
    traits: ['Concentrate', 'Mental', 'Wizard'],
    actionCost: 'reaction',
    mechanics: 'Trigger: you cast a mental spell targeting 1 creature, and it critically succeeds at its Will save. Recast the same spell at a different target (no extra slot) before end of next turn. Cannot chain.',
  },
  // ── Level 20 ─────────────────────────────────────────
  {
    id: 'wizard-archwizards-might',
    name: "Archwizard's Might",
    source: 'Wizard',
    category: 'class',
    level: 20,
    description:
      'You have mastered the greatest secrets of arcane magic. You gain an additional 10th-rank spell slot.',
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    prerequisites: ["Archwizard's Spellcraft"],
    mechanics: "+1 additional 10th-rank spell slot (total 2 with Archwizard's Spellcraft).",
  },
  {
    id: 'wizard-reclaim-spell',
    name: 'Reclaim Spell',
    source: 'Wizard',
    category: 'class',
    level: 20,
    description:
      'You have learned to manipulate reflections of magic, similar to the resonant reflections. You reclaim the magic of an ongoing spell, using it to reprepare a spell with a duration. You Dismiss a Spell of 4th level or lower that you cast today from a spell slot with at least half its duration remaining, even if that spell can\'t normally be Dismissed. You can then spend 10 minutes to reprepare the spell in that spell slot, as Reprepare Spell.',
    implemented: 'full',
    traits: ['Uncommon', 'Wizard'],
    actionCost: 1,
    prerequisites: ['Reprepare Spell'],
    mechanics: 'Legacy (Pathfinder #156). Dismiss an active spell (rank 4 or lower, half duration remaining). Then reprepare in that slot via 10-min activity.',
  },
  {
    id: 'wizard-spell-combination',
    name: 'Spell Combination',
    source: 'Wizard',
    category: 'class',
    level: 20,
    description:
      "You can merge spells, producing multiple effects with a single casting. One slot of each rank of spell you can cast (except 2nd and 1st) becomes a spell combination slot. When you prepare spells, you can fill a combination slot with two spells, each 2+ ranks below the slot's rank. Both must target only one creature/object and use the same attack/save method. When cast, it affects one target but applies both spells' effects. Uses shorter range of the two.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Combination slots at each rank 3+. Fill with 2 spells (each 2+ ranks lower than slot). Both must be single-target and share attack/save type. Cast as 1 spell affecting 1 target with both effects. Uses shorter range.',
  },
  {
    id: 'wizard-spell-mastery',
    name: 'Spell Mastery',
    source: 'Wizard',
    category: 'class',
    level: 20,
    description:
      "You have mastered a handful of spells to such a degree that you can cast them even if you haven't prepared them in advance. Select any four spells of 9th rank or lower that are in your spellbook; each spell you select must be of a different rank. These spells are automatically prepared when you make your daily preparations, and you gain an extra spell slot for each spell. You can select a different combination by spending 1 week of downtime retraining.",
    implemented: 'full',
    traits: ['Wizard'],
    actionCost: 'passive',
    mechanics: 'Select 4 spells of different ranks (9th or lower) from spellbook. Each is auto-prepared + gains an extra slot. Retrain via 1 week downtime.',
  },
  {
    id: 'wizard-worldsphere-gravity',
    name: 'Worldsphere Gravity',
    source: 'Wizard',
    category: 'class',
    level: 20,
    description:
      "Though creating demiplanes usually requires lengthy rituals, you know how to establish minor planar effects. If your next action is to Cast a Spell of at least 5th level from your spell slots that affects an area, you can apply one planar effect to a 20-foot burst centered within the spell's area for 1 minute: Gravitational Morass (greater difficult terrain; flying creatures Reflex save or fall, taking bludgeoning damage equal to half distance fallen), or Flowing Time (creature starting turn in burst is affected by haste on that turn).",
    implemented: 'full',
    traits: ['Uncommon', 'Metamagic', 'Wizard'],
    actionCost: 1,
    mechanics: 'Legacy (Pathfinder #168). Frequency: once per hour. Metamagic before area spell (5th+ rank): apply 20-ft burst planar effect for 1 min. Options: Gravitational Morass (greater difficult terrain + falling for fliers) or Flowing Time (haste for creatures starting turn in burst).',
  },
];

export const WIZARD_CLASS_FEATS: FeatEntry[] = RAW_WIZARD_CLASS_FEATS.map(f => ({
  ...f,
  traits: f.traits ?? ['Wizard'],
}));
